### PR TITLE
[`pyupgrade`] Fix handling of `\N` in raw strings (`UP032`)

### LINKED ISSUE #22060: UP032 fix misinterprets `\N` in a raw string as an escape sequence
### Summary

The fix for [`f-string` (UP032)](https://docs.astral.sh/ruff/rules/f-string/) can introduce a runtime error by misinterpreting `\N` in a raw string literal, where it is not an escape sequence. The fix in #21901 should not apply to raw strings. [Example](https://play.ruff.rs/8003ac00-7f7d-458f-8752-3667a768a40d):
```console
$ cat >up032.py <<'# EOF'
print(r"\N{angle}AOB = {angle}°".format(angle=180))
# EOF

$ python up032.py
\N180AOB = 180°

$ ruff --isolated check up032.py --select UP032 --fix
Found 1 error (1 fixed, 0 remaining).

$ cat up032.py
print(rf"\N{angle}AOB = {180}°")

$ python up032.py 2>&1 | tail -n 1
NameError: name 'angle' is not defined. Did you mean: 'range'?
```

### Version

ruff 0.14.10 (45bbb4cbf 2025-12-18)

### PR DESCRIPTION
**Pull request by denyszhak**
**Summary:**

Fixes UP032 autofix incorrectly converting raw strings with `\N{...}` to f-strings, which changes semantics and causes runtime errors.

Fixes #22060 

## Test Plan

- Added test case for raw strings with \N{...}
- Regular strings with \N{...} still autofix correctly
- All 119 pyupgrade tests pass

### CODE REVIEW

**Comment by dscorbett** [comment]
This PR suppresses the fix when a raw string contains `\N{`. That is suboptimal because there is no need to suppress the fix. For example, `r"\N{angle}AOB = {angle}°".format(angle=180)` can safely be fixed to `rf"\N{180}AOB = {180}°"`. Instead, a better solution is to suppress for raw strings the `pending_escape` logic introduced in #21901.

**Comment by denyszhak** [comment]
> This PR suppresses the fix when a raw string contains `\N{`. That is suboptimal because there is no need to suppress the fix. For example, `r"\N{angle}AOB = {angle}°".format(angle=180)` can safely be fixed to `rf"\N{180}AOB = {180}°"`. Instead, a better solution is to suppress for raw strings the `pending_escape` logic introduced in #21901.

@dscorbett @ntBre does it make sense now?

File: crates/ruff_python_literal/src/format.rs [hunk 1]
```diff
@@ -697,23 +699,12 @@ impl FormatString {
...
-pub trait FromTemplate<'a>: Sized {
-    type Err;
-    fn from_str(s: &'a str) -> Result<Self, Self::Err>;
-}
 
-impl<'a> FromTemplate<'a> for FormatString {
-    type Err = FormatParseError;
-
-    fn from_str(text: &'a str) -> Result<Self, Self::Err> {
+    pub fn parse(text: &str, is_raw: bool) -> Result<Self, FormatParseError> {
```
Comment (ntBre) [inline crates/ruff_python_literal/src/format.rs]: Instead of exposing this `parse` method, why don't we add a new `from_raw_str` constructor. I'm a bit confused why we have this trait to begin with since this is the only implementation of the trait. I'm also wondering if any of our other uses of `from_str` should consider whether the input is a raw string, but I think preserving both `from_str` and `from_raw_str` as the public API would help to guide users in that direction. We don't necessarily need to vet all the other uses here. What do you think?

Concretely, I'm suggesting something like this:


```suggestion
    fn parse(text: &str, is_raw: bool) -> Result<Self, FormatParseError> {
```

and 

```rust
pub trait FromTemplate<'a>: Sized {
    type Err;
    fn from_str(s: &'a str) -> Result<Self, Self::Err>;
    fn from_raw_str(s: &'a str) -> Result<Self, Self::Err>;
}

impl<'a> FromTemplate<'a> for FormatString {
    type Err = FormatParseError;

    fn from_str(text: &'a str) -> Result<Self, Self::Err> {
        FormatString::parse(text, false)
    }

    fn from_raw_str(text: &'a str) -> Result<Self, Self::Err> {
        FormatString::parse(text, true)
    }
}
```

or we could just delete the trait entirely:

```rust
impl FormatString {
    pub fn from_str(text: &str) -> Result<Self, FormatParseError> {
        FormatString::parse(text, false)
    }

    pub fn from_raw_str(text: &str) -> Result<Self, FormatParseError> {
        FormatString::parse(text, true)
    }
}
```

File: crates/ruff_python_literal/src/format.rs [hunk 2]
```diff
@@ -697,23 +699,12 @@ impl FormatString {
...
         let mut cur_text: &str = text;
         let mut parts: Vec<FormatPart> = Vec::new();
         while !cur_text.is_empty() {
-            // Try to parse both literals and bracketed format parts until we
-            // run out of text
```
Comment (ntBre) [inline crates/ruff_python_literal/src/format.rs:715]: Was this comment outdated or should we keep it?

**Comment by denyszhak** [comment]
@ntBre sorry I somehow missed your response, PR stayed silent and some time after I just stopped checking and only now noticed

I agree with your comments and than you for pushing those commits!
