### PR TITLE
[`ruff`] Fix false positives and negatives in `RUF010`

### LINKED ISSUE #16325: RUF010 has false positives and false negatives
### Description

[`explicit-f-string-type-conversion` (RUF010)](https://docs.astral.sh/ruff/rules/explicit-f-string-type-conversion/) has many errors in Ruff 0.9.7.

If the argument to `ascii`, `repr`, or `str` is a comprehension or display for a set or dictionary, the rule does not report it.
```console
$ cat >ruf010_1.py <<'# EOF'
print(f"{ascii({})}")
# EOF

$ ruff --isolated check --select RUF010 ruf010_1.py
All checks passed!
```
That false negative is intentional, to fix #5530, but a better solution is to add a space as `ruff format` does.
```python
print(f"{ {}!a}")
```

Skipping those comprehensions and displays does not fix that problem anyway. If the argument starts with one but continues further, the rule introduces a syntax error.
```console
$ cat >ruf010_2.py <<'# EOF'
print(f"{ascii({} | {})}")
# EOF

$ ruff --isolated check --select RUF010 ruf010_2.py --diff 2>&1 | grep error:
error: Fix introduced a syntax error. Reverting all changes.
```

The fix is suppressed when the conversion function expression is not exactly `ascii`, `repr`, or `str`. Since the rule is able to detect equivalent expressions it should be able to fix them.
```console
$ cat >ruf010_3.py <<'# EOF'
import builtins
print(f"{builtins.ascii(1)}")
print(f"{𝑎𝑠𝑐𝑖𝑖(1)}")
# EOF

$ ruff --isolated check --select RUF010 ruf010_3.py --output-format concise
ruf010_3.py:2:10: RUF010 Use explicit conversion flag
ruf010_3.py:3:10: RUF010 Use explicit conversion flag
Found 2 errors.
```

The fix for an expression followed by an equals sign is not safe, because it changes behavior. In that specific case, the fix should be marked unsafe or should be suppressed.
```console
$ cat >ruf010_4.py <<'# EOF'
print(f"{ascii(1)=}")
# EOF

$ python ruf010_4.py
ascii(1)='1'

$ ruff --isolated check --select RUF010 ruf010_4.py --fix
Found 1 error (1 fixed, 0 remaining).

$ cat ruf010_4.py
print(f"{1=!a}")

$ python ruf010_4.py
1=1
```

RUF010 introduces a syntax error when the argument is an unparenthesized lambda expression. The fix should add parentheses around the lambda expression.
```console
$ cat >ruf010_5.py <<'# EOF'
print(f"{ascii(lambda: 1)}")
# EOF

$ ruff --isolated check --select RUF010 ruf010_5.py --diff 2>&1 | grep error:
error: Fix introduced a syntax error. Reverting all changes.
```

When the argument is an unparenthesized assignment expression, the fix misinterprets the colon of the `:=` as the sigil of a format specifier. The fix should add parentheses around the assignment expression.
```console
$ cat >ruf010_6.py <<'# EOF'
x = 1
print(f"{ascii(x := 2)}")
# EOF

$ python ruf010_6.py
2

$ ruff --isolated check --select RUF010 ruf010_6.py --fix
Found 1 error (1 fixed, 0 remaining).

$ python ruf010_6.py
Traceback (most recent call last):
  File "ruf010_6.py", line 2, in <module>
    print(f"{x := 2!a}")
            ^^^^^^^^^^
ValueError: Invalid format specifier '= 2!a' for object of type 'int'
```

The fix deletes the star from a starred expression. RUF010 should be suppressed in that context.
```console
$ cat >ruf010_7.py <<'# EOF'
args = (b"\xa1", "latin-1")
print(f"{str(*args)}")
# EOF

$ python ruf010_7.py
¡

$ ruff --isolated check --select RUF010 ruf010_7.py --fix
Found 1 error (1 fixed, 0 remaining).

$ cat ruf010_7.py 
args = (b"\xa1", "latin-1")
print(f"{args!s}")

$ python ruf010_7.py
(b'\xa1', 'latin-1')
```

### PR DESCRIPTION
**Pull request by LaBatata101**
## Summary

The fix is suppressed if the f-string has debug text or call expression arguments contains a starred expression, ex:
```python
f"{ascii(1)=}"
f"{ascii(*arg)}"
```

Fixes #16325

## Test Plan

Add regression tests

### CODE REVIEW

**Comment by LaBatata101** [comment]
I don't get why the rule is not being trigged for the tests I added when ran with `cargo test`. But it's fine in a standalone file.

```python
f"{str({})}"

f"{ascii({} | {})}"

import builtins

f"{builtins.repr(1)}"

f"{ascii(1)=}"

f"{ascii(lambda: 1)}"

f"{ascii(x := 2)}"

```
Running with `cargo run -p ruff -- check sample.py --preview --no-cache --select RUF010 ` give me these diagnostics
```
sample2.py:1:4: RUF010 [*] Use explicit conversion flag
  |
1 | f"{str({})}"
  |    ^^^^^^^ RUF010
2 |
3 | f"{ascii({} | {})}"
  |
  = help: Replace with conversion flag

sample2.py:3:4: RUF010 [*] Use explicit conversion flag
  |
1 | f"{str({})}"
2 |
3 | f"{ascii({} | {})}"
  |    ^^^^^^^^^^^^^^ RUF010
4 |
5 | import builtins
  |
  = help: Replace with conversion flag

sample2.py:7:4: RUF010 [*] Use explicit conversion flag
  |
5 | import builtins
6 |
7 | f"{builtins.repr(1)}"
  |    ^^^^^^^^^^^^^^^^ RUF010
8 |
9 | f"{ascii(1)=}"
  |
  = help: Replace with conversion flag

sample2.py:9:4: RUF010 Use explicit conversion flag
   |
 7 | f"{builtins.repr(1)}"
 8 |
 9 | f"{ascii(1)=}"
   |    ^^^^^^^^ RUF010
10 |
11 | f"{ascii(lambda: 1)}"
   |
   = help: Replace with conversion flag

sample2.py:11:4: RUF010 [*] Use explicit conversion flag
   |
 9 | f"{ascii(1)=}"
10 |
11 | f"{ascii(lambda: 1)}"
   |    ^^^^^^^^^^^^^^^^ RUF010
12 |
13 | f"{ascii(x := 2)}"
   |
   = help: Replace with conversion flag

sample2.py:13:4: RUF010 [*] Use explicit conversion flag
   |
11 | f"{ascii(lambda: 1)}"
12 |
13 | f"{ascii(x := 2)}"
   |    ^^^^^^^^^^^^^ RUF010
   |
   = help: Replace with conversion flag

Found 6 errors.
[*] 5 fixable with the `--fix` option.
``` 

But in the tests it only flags for the `f"{str({})}"` and `f"{builtins.repr(1)}"`.

**Comment by chirizxc** [comment]
> I don't get why the rule is not being trigged for the tests I added when ran with `cargo test`. But it's fine in a standalone file.

i think you forgot to add a new snapshot

File: crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs [hunk 1]
```diff
@@ -68,84 +65,113 @@ pub(crate) fn explicit_f_string_type_conversion(checker: &Checker, f_string: &as
...
+        if matches!(arg, Expr::Starred(_)) {
+            return;
         }
 
-        if !checker
-            .semantic()
-            .resolve_builtin_symbol(func)
-            .is_some_and(|builtin| matches!(builtin, "str" | "repr" | "ascii"))
-        {
+        if !builtin_symbol.is_some_and(|builtin| matches!(builtin, "str" | "repr" | "ascii")) {
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: I think we should move this right after line 72 or integrate it into the match on line 74 like so:

```rust
        let Some(builtin_symbol) = checker.semantic().resolve_builtin_symbol(&call.func) else {
	continue;
}

        let arg = match builtin_symbol {
            // Handles the cases: `f"{str(object=arg)}"` and `f"{str(arg)}"`
            "str" if call.arguments.len() == 1 => {
                let Some(arg) = call.arguments.find_argument_value("object", 0) else {
                    continue;
                };
                arg
            }
            "repr" | "ascii" => {
                // Can't be a conversion otherwise.
                if !call.arguments.keywords.is_empty() {
                    continue;
                }

                // Can't be a conversion otherwise.
                let [arg] = call.arguments.args.as_ref() else {
                    continue;
                };
                arg
            },
						_ => continue,
        };
```

File: crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs [hunk 2]
```diff
@@ -68,84 +65,113 @@ pub(crate) fn explicit_f_string_type_conversion(checker: &Checker, f_string: &as
...
+        anyhow::bail!("Don't support fixing f-string with debug text!");
+    }
+
+    let name = UnqualifiedName::from_expr(&call.func).unwrap();
+    let conversion = match name.segments() {
+        ["str"] | ["builtins", "str"] => "s",
+        ["repr"] | ["builtins", "repr"] => "r",
+        ["ascii"] | ["builtins", "ascii"] => "a",
+        _ => anyhow::bail!("Unexpected function call: `{:?}`", &call.func),
+    };
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: Can't we match on the `builtin_symbol` here (e.g. by having a `Conversion` enum that we resolve early on) rather than resolving the caller name again?

That should also remove the unreachable `anyhow::bail`

File: crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs [hunk 3]
```diff
@@ -68,84 +65,113 @@ pub(crate) fn explicit_f_string_type_conversion(checker: &Checker, f_string: &as
...
+
+struct ContainsCurlyBraceVisitor {
+    result: bool,
+}
+
+impl<'a> Visitor<'a> for ContainsCurlyBraceVisitor {
+    fn visit_expr(&mut self, expr: &'a Expr) {
+        match expr {
+            Expr::Dict(_) | Expr::Set(_) | Expr::DictComp(_) | Expr::SetComp(_) => {
+                self.result = true;
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: I think this is overly strict. What we want here is to know if the left-most expression has a curly brace. See https://github.com/astral-sh/ruff/blob/45cd117ea4a361db9041304462bca7b8be7a8a80/crates/ruff_python_formatter/src/other/interpolated_string_element.rs#L276

An easier approach here could be to inspect the token stream instead and see if the first token in the expression body is a ` {`

File: crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs [hunk 4]
```diff
@@ -68,84 +65,113 @@ pub(crate) fn explicit_f_string_type_conversion(checker: &Checker, f_string: &as
...
-        match name.value {
-            "str" => {
-                formatted_string_expression.conversion = Some("s");
-            }
-            "repr" => {
-                formatted_string_expression.conversion = Some("r");
-            }
-            "ascii" => {
-                formatted_string_expression.conversion = Some("a");
+    if element
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: Can you explain why it's necessary to rewrite the entire fix here?

Comment (LaBatata101) [reply crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: With `transform_expression` I didn't have much control of how the f-string output was created. I didn't find a way to handle the special cases for curly braces, which we need to prepend a white space, and the lambda/named expressions that needed to be parenthesized.

File: crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs [hunk 5]
```diff
@@ -68,84 +66,126 @@ pub(crate) fn explicit_f_string_type_conversion(checker: &Checker, f_string: &as
...
+        .as_interpolation()
+        .is_some_and(|interpolation| interpolation.debug_text.is_some())
+    {
+        anyhow::bail!("Don't support fixing f-string with debug text!");
+    }
+
+    let arg_str = checker.locator().slice(arg);
+    let contains_curly_brace = checker
+        .tokens()
+        .in_range(arg.range())
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: I don't think this is correct. E.g we don't want to add a space for an expression like:

```py
1 if b({ "key": "test" }) else 10
```

File: crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs (hunk 4 above)
Comment (MichaReiser) [reply crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: Can't we do the same as you're doing here by:

1. Testing if the expression starts with a `{` 
2. If so, pad the start with a space

Another option would be to preserve the whitespace between `{` and the `expression`.

Comment (LaBatata101) [reply crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: It could probably work for the `{` case, but for the case where we need to parenthesize the `lambda` and `named` expression, I think it wouldn't work. In the previous implementation of the fix, it would change the node fields to apply the fix and then use the node to generate the string. There is no way -- at least I couldn't find it -- to tell the code that is generating the string from the node to parenthesize the `lambda` /`named` expression before the conversion flag.

Basically, there's no way of telling it to do this part:
https://github.com/astral-sh/ruff/blob/9c2bce2758fb618c0eb4c50fe250b52eccee84c2/crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs#L141-L142

Comment (MichaReiser) [reply crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: Can't we do the wrapping on `output`?

```rust
.map(|output| Fix::safe_edit(Edit::range_replacement(format!(" {output}), f_string.range())))
```

I wasn't aware of the lambda changes (doesn't seem to be mentioned in the summary). Could we, once again, try to preserve the parentheses instead of adding special handling?

Comment (LaBatata101) [reply crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: > doesn't seem to be mentioned in the summary

My bad, sorry.

Ok, so I managed to use the old fix implementation for the changes. But there is still the need for this check: 
https://github.com/astral-sh/ruff/blob/568f4f4c3608d8a302235cdc04d0afca1f8b2da8/crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs#L188-L190
because we can't use `parenthesized_range` with the nodes from `libcst`.

File: crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs [hunk 6]
```diff
@@ -142,10 +157,65 @@ fn convert_call_to_conversion_flag(
             "ascii" => {
                 formatted_string_expression.conversion = Some("a");
             }
-            _ => bail!("Unexpected function call: `{:?}`", name.value),
+            _ => anyhow::bail!("Unexpected function call: `{:?}`", name.value),
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: Can we use the `conversion` that we extracted in the outer call instead of matching on `name.value`. This would allow us to remove this arm entirely

File: crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs [hunk 7]
```diff
@@ -68,62 +73,72 @@ pub(crate) fn explicit_f_string_type_conversion(checker: &Checker, f_string: &as
...
     locator: &Locator,
     stylist: &Stylist,
 ) -> Result<Fix> {
+    if element
+        .as_interpolation()
+        .is_some_and(|interpolation| interpolation.debug_text.is_some())
+    {
+        anyhow::bail!("Don't support fixing f-string with debug text!");
+    }
     let source_code = locator.slice(f_string);
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: I suggest moving this out of `convert_call_to_conversion_flag` as this is a known limitations that doesn't require logging when it fails.

File: crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs [hunk 8]
```diff
@@ -68,62 +73,72 @@ pub(crate) fn explicit_f_string_type_conversion(checker: &Checker, f_string: &as
...
+        };
 
-        if !checker
-            .semantic()
-            .resolve_builtin_symbol(func)
-            .is_some_and(|builtin| matches!(builtin, "str" | "repr" | "ascii"))
-        {
-            continue;
+        // Suppress lint for starred expressions.
+        if matches!(arg, Expr::Starred(_)) {
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: Nit:
```suggestion
        if arg.is_expr_starred() {
```

File: crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs [hunk 9]
```diff
@@ -142,10 +157,65 @@ fn convert_call_to_conversion_flag(
...
+        } else {
+            call.args[0].value.clone()
+        };
+
         Ok(expression)
     })
     .map(|output| Fix::safe_edit(Edit::range_replacement(output, f_string.range())))
 }
+
+fn contains_brace(expr: &Expression) -> bool {
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: This incorrectly returns `false` for 

```py
a = "some string"
f"{repr({a: 1} + b)}"
```

We need to look at the left most expression. 

I think the easiest is to look at the token stream and see if the first non trivia token is a `{`.

File: crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs [hunk 10]
```diff
@@ -142,10 +157,65 @@ fn convert_call_to_conversion_flag(
...
+
+        formatted_string_expression.expression = if needs_paren(&call.args[0].value) {
+            call.args[0]
+                .value
+                .clone()
+                .with_parens(LeftParen::default(), RightParen::default())
+        } else {
+            call.args[0].value.clone()
+        };
+
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: Can't we move this into the `map` arm and make it based on Ruff's input AST?

Comment (LaBatata101) [reply crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: I think we can't do that without reparsing the f-string expression, because in the `map` arm we only have the generated string of the `fstring` CST node.

Comment (MichaReiser) [reply crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: but can't we inspect the `f_string` variable?

Comment (LaBatata101) [reply crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: We can, but I don't see how it is going to help. In the `map` we already have the built fix string, and in this case we don't want to parenthesize the entire f-string, just a part of it.

File: crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs [hunk 11]
```diff
@@ -68,84 +72,148 @@ pub(crate) fn explicit_f_string_type_conversion(checker: &Checker, f_string: &as
...
+        .after(call.arguments.start())
+        .iter()
+        // Skip the trivia tokens and the `(` from the arguments
+        .find(|token| !token.kind().is_trivia() && token.kind() != TokenKind::Lpar)
+        .is_some_and(|token| matches!(token.kind(), TokenKind::Lbrace))
+}
+
+fn needs_paren(expr: &Expression) -> bool {
+    matches!(expr, Expression::Lambda(_) | Expression::NamedExpr(_))
+}
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: We should add tests demonstrating this behavior. I think this is also another place where we could use `OperatorPrecedence` instead of listing all expressions where any precedence lower or equal to lambda require parenthesizing.

File: crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs (hunk 10 above)
Comment (MichaReiser) [reply crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: That's what I had in mind:

```patch
Subject: [PATCH] Rename `knot_benchmark` to `ty_benchmark`
---
Index: crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs b/crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs
--- a/crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs	(revision 13921af61d95c86f1cddfbad51471c0654b72162)
+++ b/crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs	(date 1750839908748)
@@ -122,7 +122,7 @@
         }
 
         diagnostic.try_set_fix(|| {
-            convert_call_to_conversion_flag(checker, conversion, f_string, index, element)
+            convert_call_to_conversion_flag(checker, conversion, f_string, index, arg)
         });
     }
 }
@@ -133,7 +133,7 @@
     conversion: Conversion,
     f_string: &ast::FString,
     index: usize,
-    element: &InterpolatedStringElement,
+    arg: &Expr,
 ) -> Result<Fix> {
     let source_code = checker.locator().slice(f_string);
     transform_expression(source_code, checker.stylist(), |mut expression| {
@@ -145,7 +145,7 @@
 
         formatted_string_expression.conversion = Some(conversion.as_str());
 
-        if contains_brace(checker, element) {
+        if starts_with_lbrace(checker, arg) {
             formatted_string_expression.whitespace_before_expression = space();
         }
 
@@ -163,26 +163,19 @@
     .map(|output| Fix::safe_edit(Edit::range_replacement(output, f_string.range())))
 }
 
-fn contains_brace(checker: &Checker, element: &InterpolatedStringElement) -> bool {
-    let Some(interpolation) = element.as_interpolation() else {
-        return false;
-    };
-    let Some(call) = interpolation.expression.as_call_expr() else {
-        return false;
-    };
-
+fn starts_with_lbrace(checker: &Checker, arg: &Expr) -> bool {
     checker
         .tokens()
-        .after(call.arguments.start())
+        .in_range(arg.range())
         .iter()
         // Skip the trivia tokens and the `(` from the arguments
         .find(|token| !token.kind().is_trivia() && token.kind() != TokenKind::Lpar)
         .is_some_and(|token| matches!(token.kind(), TokenKind::Lbrace))
 }
 
-fn needs_paren(expr: &Expression) -> bool {
-    matches!(expr, Expression::Lambda(_) | Expression::NamedExpr(_))
-}
+// fn needs_paren(expr: &Expr) -> bool {
+//     matches!(expr, Expr::Lambda(_) | Expr::Named(_))
+// }
 
 /// Represents the three built-in Python conversion functions that can be replaced
 /// with f-string conversion flags.
```

File: crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs (hunk 11 above)
Comment (LaBatata101) [reply crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: > We should add tests demonstrating this behavior.

We already have it, here:
https://github.com/astral-sh/ruff/blob/13921af61d95c86f1cddfbad51471c0654b72162/crates/ruff_linter/resources/test/fixtures/ruff/RUF010.py#L50-L52

Comment (MichaReiser) [reply crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: It might then be unnecessary? Because I don't see any failing tests if I change the code to:


```rust
        formatted_string_expression.expression =
        // if needs_paren(OperatorPrecedence::from_expr(arg))
        // {
        //     call.args[0]
        //         .value
        //         .clone()
        //         .with_parens(LeftParen::default(), RightParen::default())
        // } else {
            call.args[0].value.clone();
        // };
```

File: crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs [hunk 12]
```diff
@@ -68,84 +72,142 @@ pub(crate) fn explicit_f_string_type_conversion(checker: &Checker, f_string: &as
...
 }
+
+fn starts_with_brace(checker: &Checker, arg: &Expr) -> bool {
+    checker
+        .tokens()
+        .in_range(arg.range())
+        .iter()
+        // Skip the trivia tokens and the `(` from the arguments
+        .find(|token| !token.kind().is_trivia() && token.kind() != TokenKind::Lpar)
+        .is_some_and(|token| matches!(token.kind(), TokenKind::Lbrace))
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: I don't think we still need to skip over lparentheses still because we're now only iterating over the `arg` tokens?

```suggestion
    checker
        .tokens()
        .in_range(arg.range())
        .iter()
        // Skip the trivia tokens and the `(` from the arguments
        .skip_while(|token| token.kind().is_trivia())
        .next()
        .is_some_and(|token| matches!(token.kind(), TokenKind::Lbrace))
```

File: crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs (hunk 11 above)
Comment (LaBatata101) [reply crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: Oh, the diagnostic was not triggering for those cases in the test file because the `ascii` binding is being shadowed. I didn't notice that, thanks for pointing that out! Should be fixed now.

File: crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs (hunk 12 above)
Comment (LaBatata101) [reply crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: You're right, thanks!

**Review by MichaReiser — APPROVED** [review]
Thank you. This is great!
