### PR TITLE
[ty] Don't allow inlay hint edits when introducing a non global scope symbol

### LINKED ISSUE #3313: Inlay hint auto-import incorrectly assumes that members are module submembers.
### Summary

[Playground](https://play.ty.dev/aed7320e-7f9e-4f3d-8c28-00c66ab957ef)

`main.py`:

```py
from dataclasses import dataclass
from module import Outer


def wrap[T](x: T) -> list[T]:
    return [x]

y = wrap(Outer.Inner())
```

`module.py`:

```py
class Outer:
    class Inner: ...
```

Applying the inline on `y` adds the `Inner`  to `from module import Outer`, but `Inner` is not a member of `module`, it's a member of `Outer`.

### Version

_No response_

### PR DESCRIPTION
**Pull request by MatthewMckee4**
## Summary

Fixes https://github.com/astral-sh/ty/issues/3313

When we are trying to import a symbol from another file,
and that symbol is not in the global scope, we should not
provide an edit, there are some cases where this is maybe 
okay, like with the enum case, but in general we should
not allow this.

## Test Plan

ty_ide

### CODE REVIEW

File: crates/ty_ide/src/inlay_hints.rs [hunk 1]
```diff
@@ -86,6 +86,13 @@ impl InlayHint {
                             return None;
                         }
 
+                        // Only module-level names can be imported with `from <module> import <name>`.
```
Comment (MichaReiser) [inline crates/ty_ide/src/inlay_hints.rs:84]: I think we should move this check above the `definition.file(db) == file` to also handle cases like this (may be worth adding a test for it)

```py
class Outer:
   class Inner: ...
   def make(self) -> "Outer.Inner":
       return Outer.Inner()

x = Outer().make()
```

**Review by MichaReiser — APPROVED** [review]
Thank you

File: crates/ty_ide/src/inlay_hints.rs [hunk 2]
```diff
@@ -2840,20 +2847,6 @@ Source with applied edits:
...
-        1 + from typing import Literal
-        2 |
-        3 | from enum import Enum
-        4 |
-        --------------------------------------------------------------------------------
-        6 |     RED = 1
-        7 |     BLUE = 2
-        8 |
-          - x = Color.RED
-        9 + x: Literal[Color.RED] = Color.RED
```
Comment (MatthewMckee4) [inline crates/ty_ide/src/inlay_hints.rs:2856]: Obviously this is what we expected. Perhaps we would be good to suggest `: Color`, but not right now

**Comment by MichaReiser** [comment]
Thank you :)
