### PR TITLE
[`pyupgrade`] Fix syntax error on string with newline escape and comment (`UP037`)

### LINKED ISSUE #19835: UP037 fix causes syntax error on string with newline escape and comment
### Summary

If a quoted annotation contains a newline escape (`\n`) before a comment (`#`), the fix for [quoted-annotation (UP037)](https://docs.astral.sh/ruff/rules/quoted-annotation/#quoted-annotation-up037) will cause a syntax error [playground](https://play.ruff.rs/43c56f81-29c2-401e-895b-f1f01d29c128):
```powershell
PS ~>echo @'
from __future__ import annotations
def foo(bar: "A\n#"): ...
'@ | uvx ruff check --select UP037 - --fix 2>&1 | rg "syntax error"
error: Fix introduced a syntax error. Reverting all changes.
```
The fix works fine if the newline is instead added using a multiline string, so (completely guessing) this might be fixable by making these cases also take that code path.
```powershell
PS ~>echo @'
from __future__ import annotations
def foo(bar: """A
#"""): ...
'@ | uvx ruff check --select UP037 - --fix
from __future__ import annotations
def foo(bar: (A
#
)): ...
Found 1 error (1 fixed, 0 remaining).
```

### Version

ruff 0.12.8 (f51a228f0 2025-08-07)

### PR DESCRIPTION
**Pull request by danparizher**
## Summary

Fixes a syntax error introduced by `UP037` when a quoted annotation contains a trailing comment.

Fixes #19835.

## Problem
The logic for detecting trailing comments in quoted annotations was brittle, relying on a fixed offset (`len() - 2`) from the end of the token stream. This failed to correctly identify comments in strings like `"A\n#"`, leading to invalid code generation where the closing parenthesis of the function definition was commented out.

## Approach
Updated the logic in `crates/ruff_linter/src/rules/pyupgrade/rules/quoted_annotation.rs` to detect trailing comments. It now iterates backwards through the tokens of the annotation string, skipping any newline tokens, to find if the last significant token is a comment.

## Test Plan
Added regression tests to `crates/ruff_linter/resources/test/fixtures/pyupgrade/UP037_0.py`.
Verified with:
`cargo test -p ruff_linter pyupgrade::tests`

### CODE REVIEW

File: crates/ruff_linter/src/rules/pyupgrade/rules/quoted_annotation.rs [hunk 1]
```diff
@@ -115,9 +115,9 @@ pub(crate) fn quoted_annotation(checker: &Checker, annotation: &str, range: Text
 
     let last_token_is_comment = checker
         .tokens()
-        // The actual last token will always be a logical newline,
-        // so we check the second to last
-        .get(checker.tokens().len().saturating_sub(2))
+        .iter()
+        .rev()
+        .find(|tok| !tok.kind().is_any_newline())
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/pyupgrade/rules/quoted_annotation.rs]: Minor simplification:

```suggestion
        .rfind(|tok| !tok.kind().is_any_newline())
```

**Review by ntBre — COMMENTED** [review]
Thanks! This looks good to me, but I'm curious for @dylwil3 to take a quick look since  he wrote this comment about the logical newline. I printed out the tokens here, and it seems the last token is a comment instead of a newline:

```
[crates/ruff_linter/src/rules/pyupgrade/rules/quoted_annotation.rs:116:5] &checker.tokens() = Tokens {
    raw: [
        Name 0..1,
        Newline 1..2,
        Comment 2..3,
    ],
}
```

I just want to make sure we're not being too permissive here or running into a bug from another part of the code.
