### PR TITLE
[red-knot] Add line number to mdtest panic message about language tag mismatch

### LINKED ISSUE #16898: [red-knot] Add line number to mdtest panic message about language tag mismatch
I just hit this panic message while writing an mdtest:

```
failures:

---- mdtest__import_star stdout ----

thread 'mdtest__import_star' panicked at crates/red_knot_test/src/lib.rs:42:13:
Error parsing `/Users/alexw/dev/ruff/crates/red_knot_python_semantic/resources/mdtest/import/star.md`: File extension of test file path `a.pyi` in test `Only explicit re-exports are considered re-exported from `.pyi` files` does not match language specified `py` of code block
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It's a very useful message, but it would be great if it told me which line number the bad language tag has so that I could jump straight there and fix it

### PR DESCRIPTION
**Pull request by MatthewMckee4**
## Summary

Fixes #16898 

## Test Plan

Update test for lang mismatch panic

### CODE REVIEW

**Comment by MatthewMckee4** [comment]
Need to change this slightly

File: crates/red_knot_test/src/parser.rs [hunk 1]
```diff
@@ -750,6 +751,10 @@ impl<'s> Parser<'s> {
     fn offset(&self) -> TextSize {
         self.source_len - self.cursor.text_len()
     }
+
+    fn line_index(&self, char_index: TextSize) -> TextSize {
+        TextSize::new(self.source.count_lines(TextRange::up_to(char_index)))
+    }
```
Comment (MichaReiser) [inline crates/red_knot_test/src/parser.rs:757]: This shouldn't return a `TextSize`. We only use `TextSize` for byte offsets. What I understand this method does is that it returns the number of lines. It should use `OneIndexed` or `usize`)

Comment (MatthewMckee4) [reply crates/red_knot_test/src/parser.rs:757]: count_lines returns u32, i assume this would be okay?

Comment (MichaReiser) [reply crates/red_knot_test/src/parser.rs]: Yes, a `u32` works too. Anything other than `TextSize`

**Review by MichaReiser — APPROVED** [review]
