### PR TITLE
fix(ERA001): detect commented out `case` statements, add more one-line support

### LINKED ISSUE #10031: `ERA001` does not detect commented out `case` statements
Commented out `case` statements are ignored if they are missing a body, or have a body and fit on one line:

```python
match 1:
    # case 1:          # commented code ignored
    # case 1: print()  # commented code ignored

    case 1:
        pass
        # print()  # commented code found

# if 1: print()  # commented code found

if 1:
    pass
    # print()  # commented code found
```

Running:

```
$ ruff --version
ruff 0.2.2

$ ruff file.py --output-format=concise
file.py:7:9: ERA001 Found commented-out code
file.py:9:1: ERA001 Found commented-out code
file.py:13:5: ERA001 Found commented-out code
```

The first 2 `case` blocks should be counted but aren't. Often times I will duplicate and comment out a `case` statement to figure out why a pattern isn't matching, only to forget to remove the commented out case.

The example with the case/body on one line is less of an issue but still odd, perhaps the `case` statement is preventing the body from being detected.

### PR DESCRIPTION
**Pull request by omh1280**
## Summary

Closes #10031 

- Detect commented out `case` statements. Playground repro: https://play.ruff.rs/5a305aa9-6e5c-4fa4-999a-8fc427ab9a23
- Add more support for one-line commented out code.

## Test Plan

Unit tested and tested with
```sh
cargo run -p ruff -- check crates/ruff_linter/resources/test/fixtures/eradicate/ERA001.py --no-cache --preview --select ERA001
```

TODO:
- [x] `cargo insta test`

### CODE REVIEW

File: crates/ruff_linter/src/rules/eradicate/rules/commented_out_code.rs [hunk 1]
```diff
@@ -47,7 +47,8 @@ fn is_standalone_comment(line: &str) -> bool {
     for char in line.chars() {
         if char == '#' {
             return true;
-        } else if !char.is_whitespace() {
+        }
+        if !char.is_whitespace() {
```
Comment (charliermarsh) [inline crates/ruff_linter/src/rules/eradicate/rules/commented_out_code.rs:51]: Was this change intentional? Just checking.

**Review by charliermarsh — COMMENTED** [review]
Thanks!

File: crates/ruff_linter/src/rules/eradicate/detection.rs [hunk 2]
```diff
@@ -26,7 +26,7 @@ static HASH_NUMBER: Lazy<Regex> = Lazy::new(|| Regex::new(r"#\d").unwrap());
 static POSITIVE_CASES: Lazy<RegexSet> = Lazy::new(|| {
     RegexSet::new([
         // Keywords
-        r"^(?:elif\s+.*\s*:|else\s*:|try\s*:|finally\s*:|except\s+.*\s*:)$",
+        r"^(?:elif\s+.*\s*:|else\s*:|try\s*:|finally\s*:|except\s+.*\s*:|case\s+.*\s*:.*)$",
```
Comment (omh1280) [inline crates/ruff_linter/src/rules/eradicate/detection.rs:29]: note: this group ends with `.*` to detect the one-line case:
```python
case "hi": print()
```

Comment (charliermarsh) [reply crates/ruff_linter/src/rules/eradicate/detection.rs:29]: I feel like the other cases don't catch that -- can you try to add a test case with `try` followed by a one-line body?

Comment (omh1280) [reply crates/ruff_linter/src/rules/eradicate/detection.rs:29]: Yep - I think this will catch more non-code statements though like "to try: use iterators" or something. I'll write some tests to see

Comment (omh1280) [reply crates/ruff_linter/src/rules/eradicate/detection.rs:29]: Ok seems to work well, should I add `.*` for all of the cases and tests?

Comment (charliermarsh) [reply crates/ruff_linter/src/rules/eradicate/detection.rs]: Let's remove the trailing `.*` from this PR, and we can open a separate PR to add `.*` to all of the cases. It'll make it easier to approve and merge these as separate changes.

Comment (omh1280) [reply crates/ruff_linter/src/rules/eradicate/detection.rs]: Cool will do

Comment (charliermarsh) [reply crates/ruff_linter/src/rules/eradicate/detection.rs]: Ah sorry, I meant the opposite: can we remove the `.*` from here, so that we don't support one-line for _any_ of the patterns (like before this PR), and then open a separate PR that adds the `.*` to all of them at once?

Comment (omh1280) [reply crates/ruff_linter/src/rules/eradicate/detection.rs]: Yep, that's what I understood you to mean!

Comment (omh1280) [reply crates/ruff_linter/src/rules/eradicate/detection.rs]: Done! Ticket opened, I'll open that PR next.

**Comment by charliermarsh** [comment]
Thank you!

File: crates/ruff_linter/src/rules/eradicate/detection.rs (hunk 2 above)
Comment (charliermarsh) [reply crates/ruff_linter/src/rules/eradicate/detection.rs]: > Yep, that's what I understood you to mean! I'll do that and open an issue to add .* in another PR

(Oops, sorry, I think I was looking at the code, and thought you'd already pushed!)
