### PR TITLE
[`ruff`] Parenthesize generator expressions in f-strings (`RUF010`)

### LINKED ISSUE #19433: RUF010 fix should parenthesize generator expressions
### Summary

The fix for [`explicit-f-string-type-conversion` (RUF010)](https://docs.astral.sh/ruff/rules/explicit-f-string-type-conversion/) introduces a syntax error when the formatted expression is an unparenthesized generator. [Example](https://play.ruff.rs/94ef25a8-861d-4694-83b5-18a75ff34d8f):
```console
$ cat >ruf010.py <<'# EOF'
f"{ascii(x for x in [])}"
# EOF

$ ruff --isolated check ruf010.py --select RUF010 --diff 2>&1 | grep error:
error: Fix introduced a syntax error. Reverting all changes.
```

### Version

ruff 0.12.4 (ee2759b36 2025-07-17)

### PR DESCRIPTION
**Pull request by danparizher**
## Summary

Fixes #19433

### CODE REVIEW

File: crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs [hunk 1]
```diff
@@ -178,6 +177,16 @@ fn needs_paren(precedence: OperatorPrecedence) -> bool {
     precedence <= OperatorPrecedence::Lambda
 }
 
+fn needs_paren_expr(arg: &Expr) -> bool {
+    // Generator expressions need to be parenthesized in f-string expressions
+    if arg.is_generator_expr() {
+        return true;
+    }
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: We should also add a test for an already-parenthesized generator to make sure we don't add a duplicate set of parentheses. We can check the `parenthesized` field on the generator expression in that case:

https://github.com/astral-sh/ruff/blob/e867830848f6cc996186ecaf6570c43a56c0cf2c/crates/ruff_linter/src/rules/perflint/rules/manual_list_comprehension.rs#L409-L412

That's an example from a recent PR.

File: crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs [hunk 2]
```diff
@@ -178,6 +177,19 @@ fn needs_paren(precedence: OperatorPrecedence) -> bool {
     precedence <= OperatorPrecedence::Lambda
 }
 
+fn needs_paren_expr(arg: &Expr) -> bool {
+    // Generator expressions need to be parenthesized in f-string expressions
+    if let Some(generator) = arg.as_generator_expr() {
+        if generator.parenthesized {
+            return false;
+        }
+        return true;
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]:
```suggestion
        return !generator.parenthesized;
```

File: crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs [hunk 3]
```diff
@@ -178,6 +177,19 @@ fn needs_paren(precedence: OperatorPrecedence) -> bool {
...
+    }
+
+    // Check precedence for other expressions
+    needs_paren(OperatorPrecedence::from_expr(arg))
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/ruff/rules/explicit_f_string_type_conversion.rs:187]: This is fine for now, but I wonder if a better fix would be to handle unparenthesized generator expressions differently in `OperatorPrecedence::from_expr`. It doesn't really seem to fit into the rest of the precedence hierarchy, though.

**Review by ntBre — APPROVED** [review]
Thanks!
