### PR TITLE
Fix syntax error false positives for `await` outside functions

### LINKED ISSUE #21750: `F704` wrong "await outside of a function" when using generators
### Describe the Bug
Await can be outside of a function if is in code that won't be executed automatically (ex: async generators).

> `await` statement outside of a function

This code is correct, yet ruff complains:

```python
import asyncio

async def test2():
    return "test"

async def a_gen():
    for i in range(3):
        yield test2()

a = (await cor async for cor in a_gen()) # `await` statement outside of a function F704

async def main():
    async for i in a:
        print(i)

if __name__ == "__main__":
    asyncio.run(main())
```

I suggest changing F704  so awaits are ok inside async generators that are basically syntax sugar of a function.

of course for now we can do the equivalent:

```python
async def a():
    for cor in a_gen():
        yield await cor
```

### Version

_No response_

### PR DESCRIPTION
**Pull request by ntBre**
## Summary

Fixes #21750 and a related bug in `PLE1142`. We were not properly considering generators to be valid `await` contexts, which caused the `F704` issue. One of the tests I added for this also uncovered an issue in `PLE1142` for comprehensions nested within async generators because we were only checking the current scope rather than traversing the nested context.

## Test Plan

Both of these rules are implemented as semantic syntax errors, so I added tests (and fixes) in both Ruff and ty.

### CODE REVIEW

File: crates/ty_python_semantic/src/semantic_index/builder.rs [hunk 1]
```diff
@@ -2894,11 +2899,14 @@ impl SemanticSyntaxContext for SemanticIndexBuilder<'_, '_> {
         matches!(kind, ScopeKind::Function | ScopeKind::Lambda)
     }
 
-    fn in_generator_scope(&self) -> bool {
-        matches!(
-            self.scopes[self.current_scope()].node(),
-            NodeWithScopeKind::GeneratorExpression(_)
-        )
+    fn in_generator_context(&self) -> bool {
+        for scope_info in self.scope_stack.iter().rev() {
```
Comment (MichaReiser) [inline crates/ty_python_semantic/src/semantic_index/builder.rs]: The `rev` doesn't seem necessary, given that we only care about whether there's any

**Review by MichaReiser — APPROVED** [review]
