### PR TITLE
[`pylint`] Update `missing-maxsplit-arg` docs and error to suggest proper usage (`PLC0207`)

### LINKED ISSUE #18383: missing-maxsplit-arg (PLC0207) is wrong when accessing on the last value
### Summary

```
>>> url = "www.example.com"
>>> url.split(".", maxsplit=1)[0]
'www'
>>> url.split(".", maxsplit=1)[-1]
'example.com'
>>> url.split(".")[-1]
'com'
```
we can see the the maxsplit change the result when getting the last element, but ruff suggest: PLC0207 Accessing only the first or **last element** of `str.split()` without setting `maxsplit=1`
but this rule doesn't make sense for the last element, it should only be suggested for the first element, or I'm missing something 🤔 

### Version

ruff 0.11.12 (aee3af0f7 2025-05-29)

### PR DESCRIPTION
**Pull request by junhsonjb**
## Summary

Fix #18383 by updating the documentation and error message to explain that users should use `rsplit` in order to access the last element of the result with `maxsplit=1`

## Test Plan

Only documentation and an error message was changed. As such, snapshots were updated to reflect the new error message. With this change, all existing tests pass.

### CODE REVIEW

**Comment by junhsonjb** [comment]
Thanks for the comments, that makes sense! I just patched some updates to address them!

File: crates/ruff_linter/src/rules/pylint/rules/missing_maxsplit_arg.rs [hunk 1]
```diff
@@ -29,14 +29,37 @@ use crate::checkers::ast::Checker;
...
     #[derive_message_formats]
     fn message(&self) -> String {
-        "Accessing only the first or last element of `str.split()` without setting `maxsplit=1`"
-            .to_string()
+        let MissingMaxsplitArg { index, function } = self;
+
+        let correct_function = match index {
+            0 => "split",
+            -1 => "rsplit",
+            _ => "", // We should never hit this case
```
Comment (MeGaGiGaGon) [inline crates/ruff_linter/src/rules/pylint/rules/missing_maxsplit_arg.rs]: This should probably be an `unreachable!` instead, since if that case is hit it should cause a failure instead of a silent issue.

File: crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLC0207_missing_maxsplit_arg.py.snap [hunk 2]
```diff
@@ -21,7 +21,7 @@ missing_maxsplit_arg.py:15:1: PLC0207 Accessing only the first or last element o
 17 | "1,2,3".rsplit(",")[-1]  # [missing-maxsplit-arg]
    |
 
-missing_maxsplit_arg.py:16:1: PLC0207 Accessing only the first or last element of `str.split()` without setting `maxsplit=1`
+missing_maxsplit_arg.py:16:1: PLC0207 Instead of `str.rsplit()`, call `str.split()` and pass `maxsplit=1`
```
Comment (MeGaGiGaGon) [inline crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLC0207_missing_maxsplit_arg.py.snap:24]: I think you need to have both the split type and split index in `MissingMaxsplitArg`, since this is currently making the message backwards (first should stay as `split`, second should recommend switching to `rsplit`)
Edit: Looks like I failed at selecting the range, but "first" references the change above this one.

Comment (junhsonjb) [reply crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLC0207_missing_maxsplit_arg.py.snap:24]: Just so that I'm clear, which cases do you mean by "first" and "second"? This particular error message (line 24 of the `.snap` file) recommends `split` because the python code is accessing the first element. With `maxsplit=1` (which we're also recommending), we need to call `split` or else we'd get the wrong output.

`rsplit` would give us something like this:
```python
>>> "1,2,3".rsplit(",", maxsplit=1)
['1,2', '3']
```
So, getting slice index `0` would yield `'1,2'` instead of the presumably desired `'1'`.

---

Also, the split type is being passed into `MissingMaxsplitArg`. It's currently called `function` (but I'm thinking that this could be named better, so I'll go in and change that)

Comment (MeGaGiGaGon) [reply crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLC0207_missing_maxsplit_arg.py.snap:24]: Condensed down to just the error and message:

```snap
14 | "1,2,3".split(",")[0]  # [missing-maxsplit-arg]
   | ^^^^^^^^^^^^^^^^^^^^^ PLC0207
missing_maxsplit_arg.py:15:1: PLC0207 Instead of `str.split()`, call `str.rsplit()` and pass `maxsplit=1`


15 | "1,2,3".split(",")[-1]  # [missing-maxsplit-arg]
   | ^^^^^^^^^^^^^^^^^^^^^^ PLC0207
missing_maxsplit_arg.py:16:1: PLC0207 Instead of `str.rsplit()`, call `str.split()` and pass `maxsplit=1`
```
The messages are backwards. `"1,2,3".split(",")[0]` should stay as `split`, but the message says to use `rsplit`. `"1,2,3".split(",")[-1]` should switch to `rsplit`, but the message says to use `split` instead of `rsplit` dispite the code not having `rsplit` to begin with.

File: crates/ruff_linter/src/rules/pylint/rules/missing_maxsplit_arg.rs (hunk 1 above)
Comment (ntBre) [reply crates/ruff_linter/src/rules/pylint/rules/missing_maxsplit_arg.rs]: I think we should probably define a simple enum instead of using an `i64`. That way we can check for known values up front and bail out of the whole diagnostic. Then we can `match` exhaustively here.

File: crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLC0207_missing_maxsplit_arg.py.snap (hunk 2 above)
Comment (junhsonjb) [reply crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLC0207_missing_maxsplit_arg.py.snap:24]: Thank you! I've just taken a closer look at the snapshot file and I believe that each listed error pertains to the code snippet __below__ it, rather than above. For example, the first error message in the code block above refers to line 15 of the fixture (`missing_maxsplit_arg.py:15:1`). The code snippet above that error message is for line 14, meanwhile the code snippet _below it_ is for line 15 and the split types do match.

To help illustrate, here's an excerpt of the snapshot with a few comments for clarity. I've prefixed each with `# NOTE:` to differentiate from comments originally in the fixture:
```
---
source: crates/ruff_linter/src/rules/pylint/mod.rs
---
missing_maxsplit_arg.py:14:1: PLC0207 Pass `maxsplit=1` into `str.split()`  # NOTE: this error is for the call to `split()` on line 14
   |
12 | # Errors
13 | ## Test split called directly on string literal
14 | "1,2,3".split(",")[0]  # [missing-maxsplit-arg]. # NOTE: in line 14, we call `split()`
   | ^^^^^^^^^^^^^^^^^^^^^ PLC0207
15 | "1,2,3".split(",")[-1]  # [missing-maxsplit-arg]
16 | "1,2,3".rsplit(",")[0]  # [missing-maxsplit-arg]
   |

missing_maxsplit_arg.py:15:1: PLC0207 Instead of `str.split()`, call `str.rsplit()` and pass `maxsplit=1`  # NOTE: on line 15 we call `split()` as noted by this error message ("instead of `str.split()` ...")
   |
13 | ## Test split called directly on string literal
14 | "1,2,3".split(",")[0]  # [missing-maxsplit-arg]
15 | "1,2,3".split(",")[-1]  # [missing-maxsplit-arg]  # NOTE: call to `split()` on line 15
   | ^^^^^^^^^^^^^^^^^^^^^^ PLC0207
16 | "1,2,3".rsplit(",")[0]  # [missing-maxsplit-arg]
17 | "1,2,3".rsplit(",")[-1]  # [missing-maxsplit-arg]
   |

missing_maxsplit_arg.py:16:1: PLC0207 Instead of `str.rsplit()`, call `str.split()` and pass `maxsplit=1`  # NOTE: on line 16 we call `rsplit()`, as noted by this error message
   |
14 | "1,2,3".split(",")[0]  # [missing-maxsplit-arg]
15 | "1,2,3".split(",")[-1]  # [missing-maxsplit-arg]
16 | "1,2,3".rsplit(",")[0]  # [missing-maxsplit-arg]  # NOTE: call to `rsplit()` on line 16
   | ^^^^^^^^^^^^^^^^^^^^^^ PLC0207
17 | "1,2,3".rsplit(",")[-1]  # [missing-maxsplit-arg]
   |
```

So based on this structure, I think the split types are consistent with the messages, rather than swapped. Let me know what you think! 🙂

Comment (MeGaGiGaGon) [reply crates/ruff_linter/src/rules/pylint/snapshots/ruff_linter__rules__pylint__tests__PLC0207_missing_maxsplit_arg.py.snap:24]: Yep, you're right, I was misreading it

**Comment by junhsonjb** [comment]
Hey @ntBre — just wanted to check in on this. I’ve pushed some updates addressing your feedback above. When you get the chance, let me know if there’s anything else you’d like me to adjust. Thanks again! 🙂

**Review by ntBre — APPROVED** [review]
This looks great, thank you! And thanks for the ping.

I'm pretty sure these changes give us all the information we need to generate an autofix too. Feel free to work on that in a follow-up PR if you're interested :)

**Comment by junhsonjb** [comment]
> This looks great, thank you! And thanks for the ping.
> 
> I'm pretty sure these changes give us all the information we need to generate an autofix too. Feel free to work on that in a follow-up PR if you're interested :)

@ntBre Great idea! PR is [here](https://github.com/astral-sh/ruff/pull/19387)
