### PR TITLE
Do not fix `NamedTuple` calls containing both a list of fields and keywords

### LINKED ISSUE #5794: Does `crates/ruff/resources/test/fixtures/pyupgrade/UP014.py` contain incorrect `NamedTuple` calls?
https://github.com/astral-sh/ruff/blob/f012ed2d77272bfdd75f6988c2658e36fbf63102/crates/ruff/resources/test/fixtures/pyupgrade/UP014.py#L7-L12

Is this a valid `NamedTuple` call?

```
> python3 --version
Python 3.11.4

> cat a.py
from typing import NamedTuple

MyType = NamedTuple(
    "MyType",
    [("a", int), ("b", str), ("c", list[bool])],
    defaults=["foo", [True]],
)

> python a.py
Traceback (most recent call last):
  File "/home/haru/Desktop/repositories/ruff/a.py", line 3, in <module>
    MyType = NamedTuple(
             ^^^^^^^^^^^
  File "/home/haru/miniconda3/envs/py311/lib/python3.11/typing.py", line 2916, in NamedTuple
    raise TypeError("Either list of fields or keywords"
TypeError: Either list of fields or keywords can be provided to NamedTuple, not both
```

### PR DESCRIPTION
**Pull request by harupy**
## Summary

Fixes #5794

## Test Plan

Existing tests

### CODE REVIEW

File: crates/ruff/src/rules/pyupgrade/rules/convert_named_tuple_functional_to_class.rs [hunk 1]
```diff
@@ -228,9 +195,19 @@ pub(crate) fn convert_named_tuple_functional_to_class(
...
+    // ```
+    // NamedTuple(
+    //     "MyType",
+    //     [("a", int), ("b", str)],
+    //     defaults=[0, ""],
+    // )
+    // ```
+    if args.len() > 1 && !keywords.is_empty() {
+        return;
+    }
```
Comment (harupy) [inline crates/ruff/src/rules/pyupgrade/rules/convert_named_tuple_functional_to_class.rs:208]: Is this needed?

**Comment by harupy** [comment]
Hmm, the current implementation doesn't support auto-fix for `NamedTuple` calls where fields are supplied as keywords arguments:

```
MyType = typing.NamedTuple("MyType", a=int, b=tuple[str, ...])
```

File: crates/ruff/resources/test/fixtures/pyupgrade/UP014.py [hunk 2]
```diff
@@ -4,23 +4,9 @@
 # with complex annotations
 MyType = NamedTuple("MyType", [("a", int), ("b", tuple[str, ...])])
 
-# with default values as list
-MyType = NamedTuple(
-    "MyType",
-    [("a", int), ("b", str), ("c", list[bool])],
-    defaults=["foo", [True]],
-)
-
```
Comment (harupy) [inline crates/ruff/resources/test/fixtures/pyupgrade/UP014.py:13]: Removed `NamedTuple` calls that cause a runtime error.

**Comment by harupy** [comment]
@charliermarsh thanks for the update!
