### PR TITLE
Fix/#13070 defer annotations when future is active

### LINKED ISSUE #13070: [red-knot] defer annotation resolution when __future__.annotations is active
Red-knot panics on this:

```python
class IndexingMixin:
    def iloc(self) -> _iLocIndexer:
        return True


@doc(IndexingMixin.iloc)
class _iLocIndexer:
    pass
```

Changing the return type of `IndexingMixing.iloc` or changing the `_iLocIndexer` decorator to not reference `IndexingMixing.iloc` removes the panic

Source: https://github.com/pandas-dev/pandas/blob/0c24b20bd9cd743bd5f5afceb1a6fef54a2dbdc1/pandas/core/indexing.py#L4

### PR DESCRIPTION
**Pull request by Slyces**
## Summary

This PR tries to provide support for deferred resolution of type-hints in files with `from __future__ import annotations`. Fixes #13070.

### Implementation

Currently, the method `is_stub` is already used in multiple places to resolve deferred annotations. As all current usage of `is_stubs` are dedicated to deferred type inference, I decided in this implementation to refactor `is_stubs` && `has_future_annotations` together in `are_all_types_deferred`.
We can also keep them separate and always test them together.

The main difficulty is how to know if that flag is active. I tried an implementation that checks this when building the semantic index. I do not know if it's the best choice (as `SemanticIndex` doesn't have any attribute similar to this), but the building of the semantic index already parses every statement in the file, which was ideal to find this flag.

Happy to get any feedback on a better spot for this if you can think of one.

## Test Plan

There is currently one test addressing deferred annotations resolution, focused on builtins. I don't quite understand why builtins require deferred annotations, so I focused on test cases I encounter when coding in python.

In my experience, the two most common occurrences requiring deferred annotations (in regular code) are:
- Referencing a symbol before it's defined
- Referencing a class inside one of its own methods

Some testing led me to find that we don't currently support [type resolution for methods](https://github.com/astral-sh/ruff/blob/4eb849aed3a6df9ce0f45dd7a2fdb525e31e61e3/crates/red_knot_python_semantic/src/types.rs#L439), so I only tested the case of referencing a symbol before its definition.

I added 3 separate test case, all with the same base code:
```python
def get_foo() -> Foo: ...
class Foo: ...
foo = get_foo()  # Resolved if and only if deferred annotations are active
```
- Inside a source file (`*.py`, `foo` must not resolve (`Unknown`)
- Inside a stub file (`*.pyi`), `foo` must resolve to `Foo`
- Inside a source file **with __future__.annotations**, `foo` must resolve to `Foo`

### CODE REVIEW

File: crates/red_knot_python_semantic/src/types/infer.rs [hunk 1]
```diff
@@ -318,9 +318,10 @@ impl<'db> TypeInferenceBuilder<'db> {
         self.types.has_deferred |= inference.has_deferred;
     }
 
-    /// Are we currently inferring types in a stub file?
-    fn is_stub(&self) -> bool {
-        self.file.is_stub(self.db.upcast())
+    /// Are we currently inferring types in file with deferred types?
+    /// This is true for stub files and files with `__future__.annotations`
+    fn are_all_types_deferred(&self) -> bool {
+        self.file.is_stub(self.db.upcast()) || self.index.has_future_annotations()
```
Comment (carljm) [inline crates/red_knot_python_semantic/src/types/infer.rs:324]: nit: checking `has_future_annotations()` is slightly cheaper, maybe let's do that first?

**Review by carljm — APPROVED** [review]
This is fantastic, thank you!!

The semantic index builder is the right place to look for this, and the semantic index is the right place to put it. Any analysis that we can do without requiring a dependency on other files, we want to do in semantic indexing.

I suspect the performance regression on the incremental check is because tomllib (which we are using for our benchmark) does use `from __future__ import annotations`, and deferred types require an extra Salsa query and thus increase Salsa overhead on incremental check.

So I suspect that requiring `from __future__ import annotations` to be the first statement in a file won't help with the performance.

And I'm not sure if we even want to require it. A mis-placed `from __future__ import annotations` won't work at runtime (the module won't even import), but for our purposes I think we should assume the user intended for it to take effect, and we should still check the code assuming its use. Otherwise accidentally adding a line before your `from __future__ import annotations` could suddenly result in a ton of bogus diagnostics on your forward-reference annotations, which isn't really useful.

I think we should add a comment to this effect, where we check for `from __future__ import annotations` in the semantic index builder.

And I think we should emit a diagnostic in type inference if we run across a misplaced `__future__` import. But this is pretty much a separate thing and could be its own PR.

File: crates/red_knot_python_semantic/src/semantic_index/builder.rs [hunk 2]
```diff
@@ -543,7 +549,15 @@ where
                         &alias.name.id
                     };
 
+                    // Look for imports `from __future__ import annotations`, ignore `as ...`
+                    self.has_future_annotations |= alias.name.id.as_str() == "annotations"
```
Comment (carljm) [inline crates/red_knot_python_semantic/src/semantic_index/builder.rs:553]: Something like this:

```suggestion
                    // Look for imports `from __future__ import annotations`, ignore `as ...`.
                    // We intentionally don't enforce the rules about location of `__future__` imports here,
                    // we assume the user's intent was to apply the `__future__` import, so we still check
                    // using it (and will also emit a diagnostic about a mis-placed `__future__` import.)
                    self.has_future_annotations |= alias.name.id.as_str() == "annotations"
```

**Comment by Slyces** [comment]
> So I suspect that requiring from __future__ import annotations to be the first statement in a file won't help with the performance.

That's somewhat of a relief (if it's true) because the implementation I have so far is not ideal. I will still try to go through with it to make sure that it is not the source of the regression

**Comment by Slyces** [comment]
While this is not related to the PR, I did waste some time on the difference between "expected Unknown" (e.g. resolution failed) vs. "Not implemented Unknown" (e.g. this case should yield a value for the current AST but we didn't code it yet).

Would it be worth considering a temporary value (until red-knot is feature complete or almost so) that would make this difference obvious? To be fair I'll also be more careful next time now that I know 🙂

**Comment by carljm** [comment]
> Would it be worth considering a temporary value (until red-knot is feature complete or almost so) that would make this difference obvious?

That's an interesting idea! I think we could have `Type::Unknown` contain another enum indicating the source of the unknown (mypy does something similar, @AlexWaygood has mentioned this before). Then most code handling Unknowns wouldn't have to care (we wouldn't have to add a new branch in every place that handles types), but we could display them differently.

This seems like a net positive to me! Not sure I would get to it soon, but if you're interested in doing it, I'd certainly consider a PR.

**Comment by AlexWaygood** [comment]
> That's an interesting idea! I think we could have `Type::Unknown` contain another enum indicating the source of the unknown (mypy does something similar, @AlexWaygood has mentioned this before). Then most code handling Unknowns wouldn't have to care (we wouldn't have to add a new branch in every place that handles types), but we could display them differently.

Yes, see #12986 for previous discussion! I think the main concern was how to handle the inner enum in unions and intersections.

File: crates/red_knot_python_semantic/src/semantic_index/builder.rs [hunk 3]
```diff
@@ -543,7 +549,19 @@ where
...
+                    // Look for imports `from __future__ import annotations`, ignore `as ...`
+                    // We intentionally don't enforce the rules about location of `__future__`
+                    // imports here, we assume the user's intent was to apply the `__future__`
+                    // import, so we still check using it (and will also emit a diagnostic about a
+                    // miss-placed `__future__` import.)
+                    self.has_future_annotations |= alias.name.id.as_str() == "annotations"
+                        && node
+                            .module
+                            .as_ref()
+                            .is_some_and(|module| module.id().as_str() == "__future__");
```
Comment (MichaReiser) [inline crates/red_knot_python_semantic/src/semantic_index/builder.rs:561]:
```suggestion
                    self.has_future_annotations |= alias.name.id == "annotations"
                        && node
                            .module
                            .as_ref()
                            .is_some_and(|module| module.id() == "__future__");
```

Comment (MichaReiser) [reply crates/red_knot_python_semantic/src/semantic_index/builder.rs:561]: Or even

```rust
                    self.has_future_annotations |= alias.name.id == "annotations"
                        && node.module.as_deref() == Some("__future__");
```

File: crates/red_knot_python_semantic/src/semantic_index/builder.rs [hunk 4]
```diff
@@ -45,6 +45,9 @@ pub(super) struct SemanticIndexBuilder<'db> {
     /// Flow states at each `break` in the current loop.
     loop_break_states: Vec<FlowSnapshot>,
 
+    /// Flags about the file's global scope
+    has_future_annotations: bool,
```
Comment (MichaReiser) [inline crates/red_knot_python_semantic/src/semantic_index/builder.rs:49]: We probably want to make this a bit flag long term but a boolean is just fine for now :)

**Review by MichaReiser — APPROVED** [review]
This is great. Thanks you

**Comment by MichaReiser** [comment]
It's a bit a problem that I can't acknowledge the codspeed regression because the URl doesn't work haha

Okay, there's a way. Navigate to the runs page and open the results from there https://codspeed.io/astral-sh/ruff/runs/66ebdbcf6ba711013f9a14a5
