### PR TITLE
[red-knot] avoid inferring types if unpacking fails

### LINKED ISSUE #15199: [red-knot] Avoid inferring types in error case during unpacking
Refer: https://github.com/astral-sh/ruff/pull/15086#discussion_r1896889031

### PR DESCRIPTION
**Pull request by mtshiba**
## Summary

This PR closes #15199.

The change I just made is to set all variables to type `Unknown` if unpacking fails, but in some cases this may be excessive.
For example:

```py
a, b, c = "ab"
reveal_type(a)  # Unknown, but it would be reasonable to think of it as LiteralString
reveal_type(c)  # Unknown
```

```py
# Failed to unpack before the starred expression
(a, b, *c, d, e) = (1,)
reveal_type(a)  # Unknown
reveal_type(b)  # Unknown
...
# Failed to unpack after the starred expression
(a, b, *c, d, e) = (1, 2, 3)
reveal_type(a)  # Unknown, but should it be Literal[1]?
reveal_type(b)  # Unknown, but should it be Literal[2]?
reveal_type(c)  # Todo
reveal_type(d)  # Unknown
reveal_type(e)  # Unknown
```

I will modify it if you think it would be better to make it a different type than just `Unknown`.

## Test Plan

I have made appropriate modifications to the test cases affected by this change, and also added some more test cases.

### CODE REVIEW

File: crates/red_knot_python_semantic/src/types/unpacker.rs [hunk 1]
```diff
@@ -121,7 +121,7 @@ impl<'db> Unpacker<'db> {
                     if let Some(tuple_ty) = ty.into_tuple() {
                         let tuple_ty_elements = self.tuple_ty_elements(target, elts, tuple_ty);
 
-                        match elts.len().cmp(&tuple_ty_elements.len()) {
+                        let invalid_unpacking = match elts.len().cmp(&tuple_ty_elements.len()) {
```
Comment (dhruvmanila) [inline crates/red_knot_python_semantic/src/types/unpacker.rs:124]: I think the value of this is not exactly what it represents because in `tuple_ty_elements` method, we would return a vector of unknowns that's exactly the same length as the number of targets but that's mainly because the error message is a little bit different in that case.

I don't think there's any action item here except that I'd probably rename this variable to something like `length_mismatch`.

**Review by dhruvmanila — CHANGES_REQUESTED** [review]
Thank you for doing this! There are couple of changes around simplification and using `Unknown` even in the case of starred unpacking but otherwise this looks good.

**Review by carljm — APPROVED** [review]
Looks good to me with the changes from Dhruv's review!
