### PR TITLE
[`pylint`] Do not report calls when object type and argument type mismatch, remove custom escape handling logic (`PLE1310`)

### LINKED ISSUE #15968: PLE1310 fails on `bytes.strip`
### Description

[`bad-str-strip-call` (PLE1310)](https://docs.astral.sh/ruff/rules/bad-str-strip-call/) in Ruff 0.9.4 flags a `bytes.strip` call when its argument is a `str`, but that is a false positive because `bytes.strip` does not accept a `str` argument.
```console
$ cat >ple1310.py <<'# EOF'
b"".strip("//")
# EOF

$ python ple1310.py 2>&1 | tail -n 1
TypeError: a bytes-like object is required, not 'str'

$ ruff --isolated check --select PLE1310 ple1310.py --output-format concise
ple1310.py:1:11: PLE1310 String `strip` call contains duplicate characters
Found 1 error.
```
PLE1310 does not flag a `bytes.strip` call when its argument is a `bytes`, which a false negative.
```console
$ echo 'b"".strip(b"//")' | ruff --isolated check --select PLE1310 -
All checks passed!
```

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
## Summary

Resolves #15968.

Previously, these would be considered violations:

```python
b''.strip('//')
''.lstrip('//', foo = "bar")
```

...while these are not:

```python
b''.strip(b'//')
''.strip('\\b\\x08')
```

Ruff will now not report when the types of the object and that of the argument mismatch, or when there are extra arguments.

## Test Plan

`cargo nextest run` and `cargo insta test`.

### CODE REVIEW

File: crates/ruff_linter/src/rules/pylint/rules/bad_str_strip_call.rs [hunk 1]
```diff
@@ -120,52 +143,73 @@ impl fmt::Display for RemovalKind {
...
-            let pair = format!("\\{ch}");
-            if !seen.insert(pair) {
-                return true;
-            }
-        } else if ch == '\\' {
-            escaped = true;
-        } else if !seen.insert(ch.to_string()) {
-            return true;
-        }
-    }
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pylint/rules/bad_str_strip_call.rs:140]: Can you explain why it's no longer necessary to handle escapes?

File: crates/ruff_linter/resources/test/fixtures/pylint/bad_str_strip_call.py [hunk 2]
```diff
@@ -64,10 +64,39 @@
 u''.lstrip('http://')
 
 # PLE1310
-b''.rstrip('http://')
+b''.rstrip(b'http://')
```
Comment (MichaReiser) [inline crates/ruff_linter/resources/test/fixtures/pylint/bad_str_strip_call.py:67]: Let's add a test that uses escaped backslashes

```suggestion
"\\test".strip("\\")
```
