### PR TITLE
Raise syntax error for mixing `except` and `except*`

### LINKED ISSUE #14860: Raise syntax error if there are both `except` and `except*` in the same `try` block
The task is to fix this TODO:

https://github.com/astral-sh/ruff/blob/1bd8fbb6e862259a4515f180c2b2ab119d3ffc23/crates/ruff_python_parser/src/parser/statement.rs#L1341-L1355

I'd consider this as a bug because the AST marks the entire `try` block as containing an `except*` and because the parser doesn't raise a syntax error, the formatter will add the `*` to all `except` block (https://play.ruff.rs/059d8f35-5f66-4be5-887e-9f38fa75b40e):

```diff
  try:
      pass
- except:
+ except*:
      pass
  except* ExceptionGroup:
      pass
```

CPython parser (not the compiler) also raises a syntax error:

```console
$ pbpaste | python -m ast -
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/dhruv/.pyenv/versions/3.12.1/lib/python3.12/ast.py", line 1834, in <module>
    main()
  File "/Users/dhruv/.pyenv/versions/3.12.1/lib/python3.12/ast.py", line 1830, in main
    tree = parse(source, args.infile.name, args.mode, type_comments=args.no_type_comments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dhruv/.pyenv/versions/3.12.1/lib/python3.12/ast.py", line 52, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<stdin>", line 5
    except* ExceptionGroup:
    ^^^^^^^
SyntaxError: cannot have both 'except' and 'except*' on the same 'try'
```

### PR DESCRIPTION
**Pull request by dylwil3**
This PR adds a syntax error if the parser encounters a `TryStmt` that has except clauses both with and without a star.

The displayed error points to each except clause that contradicts the original except clause kind. So, for example,

```python
try:
    ....
except:     #<-- we assume this is the desired except kind
    ....
except*:    #<---  error will point here
    ....
except*:    #<--- and here
    ....
```

Closes #14860

### CODE REVIEW

**Comment by dylwil3** [comment]
It's not clear to me if it would be better to just put a single displayed error on the entire `TryStmt`? Happy to change it.

File: crates/ruff_python_parser/src/parser/statement.rs [hunk 1]
```diff
@@ -1353,11 +1351,36 @@ impl<'src> Parser<'src> {
...
         let handlers = self.parse_clauses(Clause::Except, |p| {
             let (handler, kind) = p.parse_except_clause();
-            is_star |= kind.is_star();
+            if is_star.is_none() {
+                is_star = Some(kind.is_star());
+            } else if is_star.is_some_and(|seen_star| seen_star != kind.is_star()) {
+                mixed_except_ranges.push(handler.range());
+            }
             handler
         });
```
Comment (MichaReiser) [inline crates/ruff_python_parser/src/parser/statement.rs:1373]: Nit
```suggestion
            if is_star.is_none() {
                is_star = Some(kind.is_star());
            } else if is_star != Some(kind.is_star()) {
                mixed_except_ranges.push(handler.range());
            }
            handler
        });
```

**Review by MichaReiser — APPROVED** [review]
I think the syntax error is fine the way it is. Thank you
