### PR TITLE
[`pyupgrade`] Handle end-of-line comments for `quoted-annotation` (`UP037`)

### LINKED ISSUE #15816: UP037 fix crashes when a terminal comment follows a literal
### Description

The fix for [`quoted-annotation` (UP037)](https://docs.astral.sh/ruff/rules/quoted-annotation/) crashes Ruff 0.9.3 when a quoted annotation ends with a comment and contains a string or number literal, which can occur with `Annotated` or `Literal`.

```console
$ cat >up037.py <<'# EOF'
from __future__ import annotations
from typing import Literal
def f() -> "Literal[0]#":
    return 0
# EOF

$ ruff check --isolated --select UP037 up037.py --diff

error: Fix introduced a syntax error. Reverting all changes.

This indicates a bug in Ruff. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BFix%20error%5D

...quoting the contents of `up037.py`, the rule codes UP037, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!


```

### PR DESCRIPTION
**Pull request by dylwil3**
This PR uses the tokens of the parsed annotation available in the `Checker`, instead of re-lexing (using `SimpleTokenizer`) the annotation. This avoids some limitations of the `SimpleTokenizer`, such as not being able to handle number and string literals.

Closes #15816 .

### CODE REVIEW

File: crates/ruff_linter/src/rules/pyupgrade/rules/quoted_annotation.rs [hunk 1]
```diff
@@ -87,14 +87,14 @@ pub(crate) fn quoted_annotation(checker: &mut Checker, annotation: &str, range:
...
-        tokenizer.last(),
-        Some(SimpleToken {
-            kind: SimpleTokenKind::Comment,
-            ..
-        })
-    );
+    let last_token_is_comment = checker
+        // Inside an annotation, the `checker.tokens()`
+        // returns the tokens for the parsed annotation.
+        .tokens()
```
Comment (dhruvmanila) [inline crates/ruff_linter/src/rules/pyupgrade/rules/quoted_annotation.rs:93]: nit: I'd remove this comment as the information exists as docs to `checker.tokens` method

File: crates/ruff_linter/src/rules/pyupgrade/rules/quoted_annotation.rs [hunk 2]
```diff
@@ -87,14 +87,14 @@ pub(crate) fn quoted_annotation(checker: &mut Checker, annotation: &str, range:
...
+        // The actual last token will always be a logical newline,
+        // so we check the second to last
+        .get((checker.tokens().len()) - 2)
```
Comment (dhruvmanila) [inline crates/ruff_linter/src/rules/pyupgrade/rules/quoted_annotation.rs:96]: The parentheses doesn't seem necessary here.

What would happen if the annotation only contains the comment character i.e., `foo: "#"` which would give `Comment, Newline`? And, similarly for empty annotation like `foo: ""` which would just give `Newline`. I think we should use `saturating_sub` here.

```suggestion
        .get(checker.tokens().len() - 2)
```

Comment (dylwil3) [reply crates/ruff_linter/src/rules/pyupgrade/rules/quoted_annotation.rs:96]: I don't think either of those cases can occur inside this lint check because it is applied to _parsed_ annotations, and those two examples are syntax errors.

https://github.com/astral-sh/ruff/blob/3125332ec1bc86494feef57c6a6c64d3591a4831/crates/ruff_linter/src/checkers/ast/mod.rs#L2341-L2356

But I agree about the saturating subtraction!

**Review by dhruvmanila — APPROVED** [review]
