### PR TITLE
[`pyupgrade`] Do not report when a UTF-8 comment is followed by a non-UTF-8 one (`UP009`)

### LINKED ISSUE #14704: UP009 fix changes a file from UTF-8 to a different declared encoding
The fix for [`utf8-encoding-declaration` (UP009)](https://docs.astral.sh/ruff/rules/utf8-encoding-declaration/) in Ruff 0.8.1 changes the file’s declared encoding when the redundant UTF-8 encoding declaration is followed by a non-UTF-8 encoding declaration. In that case, the UTF-8 declaration is not completely redundant, because it blocks the following declaration from having an effect. The fix should insert up to 2 blank lines so the other declarations have no effect, or the fix should delete the other declarations, or the check should not report a violation.

Example of a syntax error:
```console
$ printf '\xef\xbb\xbf# coding: utf-8\n# coding: ascii\nprint("success")\n' >up009_1.py
$ python up009_1.py
success
$ ruff check --isolated --select UP009 up009_1.py --fix
Found 1 error (1 fixed, 0 remaining).
$ python up009_1.py
SyntaxError: encoding problem: ascii with BOM
```

Example of changed behavior:
```console
$ printf '# coding: utf-8\n# coding: latin-1\nprint("\xc3\xa5")\n' >up009_2.py
$ python up009_2.py
å
$ ruff check --isolated --select UP009 up009_2.py --fix
Found 1 error (1 fixed, 0 remaining).
$ python up009_2.py
Ã¥
```

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
## Summary

Resolves #14704.

## Test Plan

`cargo nextest run` and `cargo insta test`.

### CODE REVIEW

File: crates/ruff_linter/src/rules/pyupgrade/rules/unnecessary_coding_comment.rs [hunk 1]
```diff
@@ -57,46 +67,85 @@ pub(crate) fn unnecessary_coding_comment(
...
-
-            let mut diagnostic = Diagnostic::new(UTF8EncodingDeclaration, *comment_range);
-            diagnostic.set_fix(Fix::safe_edit(Edit::deletion(
-                line_range.start(),
-                line_range.end(),
-            )));
-            diagnostics.push(diagnostic);
+        [Some(CodingComment::UTF8(ranges_1)), Some(CodingComment::UTF8(ranges_2))] => {
+            report(diagnostics, ranges_1.line_range, ranges_1.self_range);
+            report(diagnostics, ranges_2.line_range, ranges_2.self_range);
```
Comment (dscorbett) [inline crates/ruff_linter/src/rules/pyupgrade/rules/unnecessary_coding_comment.rs:85]: If this block removes both UTF-8 encoding declarations, what happens if there is a third, non-UTF-8 encoding declaration?
```python
# coding=utf-8
# coding=utf-8
# coding=ascii
```

I think it would be better to only offer the fix for `ranges_1`. If it safe to delete `ranges_2` too, that can happen on the next iteration.

File: crates/ruff_linter/src/rules/pyupgrade/rules/unnecessary_coding_comment.rs [hunk 2]
```diff
@@ -57,46 +67,85 @@ pub(crate) fn unnecessary_coding_comment(
...
+
+    let part_of_interest = CODING_COMMENT_REGEX.captures(locator.slice(line_range))?;
+    let coding_name = part_of_interest.name("name")?.as_str();
+
+    #[allow(deprecated)]
+    let index = locator.compute_line_index(line_range.start());
+
+    if index.to_zero_indexed() > 1 {
+        return None;
+    }
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pyupgrade/rules/unnecessary_coding_comment.rs:131]: Oh wow, this still uses the old API. We can address this in a follow up PR but I think we could easily replace this with `locator.slice(TextRange::up_to(line_range.start())` and then count the number of  lines by calling `locator.full_line_end` until it reaches the end of the range. We could add this as a method to `LineRanges`

File: crates/ruff_linter/src/rules/pyupgrade/rules/unnecessary_coding_comment.rs (hunk 1 above)
Comment (MichaReiser) [reply crates/ruff_linter/src/rules/pyupgrade/rules/unnecessary_coding_comment.rs:85]: In that case, we shouldn't raise a diagnostic for the second encoding comment.

File: crates/ruff_linter/src/rules/pyupgrade/rules/unnecessary_coding_comment.rs [hunk 3]
```diff
@@ -57,46 +67,85 @@ pub(crate) fn unnecessary_coding_comment(
...
-            .trim()
-            .is_empty()
-        {
-            continue;
-        }
+    let coding_comments = comment_ranges
+        .iter()
+        .take(2)
+        .map(|comment_range| coding_comment(locator, indexer, *comment_range))
+        .collect::<Vec<_>>();
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pyupgrade/rules/unnecessary_coding_comment.rs:74]: It would be great if we can avoid collecting the comments here to avoid the allocation. I think doing so should also reduce the amount of code needed below.

```rust
let mut comments = comment_ranges.iter().take(...)...

let Some(first) = comments.next() else {
	return None;
}

if let Some(CodingComment::Other) = comments.next() {
	return None;
}

```

**Review by MichaReiser — CHANGES_REQUESTED** [review]
We should address the case when there are multiple coding comments (that might also be on lines other than the first two)

File: crates/ruff_source_file/src/line_ranges.rs [hunk 4]
```diff
@@ -295,6 +295,40 @@ pub trait LineRanges {
...
+
+            if last_line_end <= offset {
+                count += 1;
+            } else {
+                break;
+            }
+        }
+
+        count
+    }
```
Comment (MichaReiser) [inline crates/ruff_source_file/src/line_ranges.rs:331]: Nit: i'd change the method to take a text range instead. It makes it more flexible and it also avoids that the function never terminates if `offset` == `len(text)`
```suggestion
    /// Returns the zero-based index of the line containing `offset`.
    ///
    /// ## Examples
    ///
    /// ```
    /// # use ruff_text_size::{Ranged, TextRange, TextSize};
    /// # use ruff_source_file::LineRanges;
    ///
    /// let text = "First line\nsecond line\r\nthird line";
    ///
    /// assert_eq!(text.count_lines_until(TextSize::from(5)), 0);
    /// assert_eq!(text.count_lines_until(TextSize::from(23)), 1);
    /// assert_eq!(text.count_lines_until(TextSize::from(24)), 2);
    /// ```
    ///
    /// ## Panics
    /// If `offset` is out of bounds.
    fn count_lines(&self, range: TextRange) -> u32 {
        let mut count = 0;
        let mut offset = range.start();

				loop {
					let line_end = self.full_line_end(offset);
					if line_end < range.end() {
						count += 1;
						offset = line_end;
				} else {
					break count;
				}
    }
```

File: crates/ruff_linter/resources/test/fixtures/pyupgrade/UP009_utf8_utf8_other.py
Comment (MichaReiser) [inline crates/ruff_linter/resources/test/fixtures/pyupgrade/UP009_utf8_utf8_other.py:1]: Nice tests.

Could we add a test for

```
print("the following is not a coding comment")
# -*- coding: utf8 -*-
```

The PEP is surprisingly not specific about whether this coding statement is valid or not (I'd assume it isn't but the PEP doesn't mention anything about a statement before the coding block so maybe it is?)

**Review by MichaReiser — COMMENTED** [review]
Wow, thanks for implementing the `count_lines` method! 

There's one more edge case that needs handling

```
#! /usr/bin/env/python
# -*- coding: utf-8 -*-
# -*- coding: ascii -*-
```

The second comment gets flagged as unnecessary, which is incorrect because removing it would change the encoding to ascii

File: crates/ruff_linter/resources/test/fixtures/pyupgrade/UP009_utf8_utf8_other.py
Comment (dscorbett) [reply crates/ruff_linter/resources/test/fixtures/pyupgrade/UP009_utf8_utf8_other.py:1]: [Python’s documentation](https://docs.python.org/3/reference/lexical_analysis.html#encoding-declarations) says “The encoding declaration must appear on a line of its own. If it is the second line, the first line must also be a comment-only line.” so that is just a normal comment, not an encoding declaration.

**Comment by MichaReiser** [comment]
@InSyncWithFoo what's the status of this PR? Is it ready for re-review?

File: crates/ruff_linter/resources/test/fixtures/pyupgrade/UP009_utf8_utf8_other.py
Comment (MichaReiser) [reply crates/ruff_linter/resources/test/fixtures/pyupgrade/UP009_utf8_utf8_other.py:1]: Thanks @dscorbett  for the link. That's what I expected. Let's add a test if there isn't one already:

```
# -*- coding: utf8 -*-
print("the following is not a coding comment")
# -*- coding: ascii -*-
```

File: crates/ruff_source_file/src/line_ranges.rs (hunk 4 above)
Comment (MichaReiser) [reply crates/ruff_source_file/src/line_ranges.rs]: Yes, it is different but `count_lines_until` can be expressed by `count_lines(TextRange::up_to(offset))` 

That's why I'd prefer to only expose the more generic solution because it allows solving more use cacses.

**Review by MichaReiser — CHANGES_REQUESTED** [review]
Thanks for addressing the feedback.

The rule currently incorrectly flags the following comments:

```
x = 10
# -*- coding: utf-8 -*-
# -*- coding: utf-8 -*-
```

```
x = 10
# -*- coding: utf-8 -*-
```

I think we need to make the `comment_ranges` iterator more stateful. It should never return `Some` after it has seen any non-comment. It might be worth implementing a custom iterator and tracking some internal state.
