### PR TITLE
[red-knot] Add a new `Type::KnownInstanceType` variant

### LINKED ISSUE #14114: [red-knot] fix handling of known instances in `Type` relation methods
We currently represent "known instances" (e.g. special forms like `typing.Literal`, which are an instance of `typing._SpecialForm`, but need to be handled differently from other instances of `typing._SpecialForm`) as an `InstanceType` with a `known` field that is `Some(...)`.

This makes it easy to handle a known instance as if it were a regular instance type (by ignoring the `known` field), and in some cases (e.g. `Type::member`) that is correct and convenient. But in other cases (e.g. `Type::is_equivalent_to`) it is not correct, and we currently have a bug that we would consider the known-instance type of `typing.Literal` as equivalent to the general instance type for `typing._SpecialForm`, and we would fail to consider it a singleton type or a single-valued type (even though it is both.)

An instance type with `known.is_some()` is semantically quite different from an instance type with `known.is_none()`. The former is a singleton type that represents exactly one runtime object; the latter is an open type that represents many runtime objects, including instances of unknown subclasses. It is too error-prone to represent these very-different types as a single `Type` variant. We should instead introduce a dedicated `Type::KnownInstance` variant and force ourselves to handle these explicitly in all `Type` variant matches.

### PR DESCRIPTION
**Pull request by AlexWaygood**
## Summary

Fixes #14114. I don't think I can really describe the problems with our current architecture (and therefore the motivations for this PR) any better than @carljm did in that issue, so I'll just copy it out here!

---

We currently represent "known instances" (e.g. special forms like `typing.Literal`, which are an instance of `typing._SpecialForm`, but need to be handled differently from other instances of `typing._SpecialForm`) as an `InstanceType` with a `known` field that is `Some(...)`.

This makes it easy to handle a known instance as if it were a regular instance type (by ignoring the `known` field), and in some cases (e.g. `Type::member`) that is correct and convenient. But in other cases (e.g. `Type::is_equivalent_to`) it is not correct, and we currently have a bug that we would consider the known-instance type of `typing.Literal` as equivalent to the general instance type for `typing._SpecialForm`, and we would fail to consider it a singleton type or a single-valued type (even though it is both.)

An instance type with `known.is_some()` is semantically quite different from an instance type with `known.is_none()`. The former is a singleton type that represents exactly one runtime object; the latter is an open type that represents many runtime objects, including instances of unknown subclasses. It is too error-prone to represent these very-different types as a single `Type` variant. We should instead introduce a dedicated `Type::KnownInstance` variant and force ourselves to handle these explicitly in all `Type` variant matches.

## Possible followups

There is still a little bit of awkwardness in our current design in some places, in that we first infer the symbol `typing.Literal` as a `_SpecialForm` instance, and then later convert that instance-type into a known-instance-type. We could also use this `KnownInstanceType` enum to account for other special runtime symbols such as `builtins.Ellipsis` or `builtins.NotImplemented`.

I think these might be worth pursuing, but I didn't do them here as they didn't seem essential right now, and I wanted to keep the diff relatively minimal.

## Test Plan

`cargo test -p red_knot_python_semantic`. New unit tests added for `Type::is_subtype_of`.

### CODE REVIEW

File: crates/red_knot_python_semantic/src/types.rs [hunk 1]
```diff
@@ -335,6 +335,8 @@ pub enum Type<'db> {
     SubclassOf(SubclassOfType<'db>),
     /// The set of Python objects with the given class in their __class__'s method resolution order
     Instance(InstanceType<'db>),
+    /// A specific symbol that is special enough at runtime to be treated as its own type
```
Comment (carljm) [inline crates/red_knot_python_semantic/src/types.rs:338]:
```suggestion
    /// A single Python object that requires special treatment in the type system
```

File: crates/red_knot_python_semantic/src/types/narrow.rs [hunk 2]
```diff
@@ -353,7 +353,9 @@ impl<'db> NarrowingConstraintsBuilder<'db> {
                     let to_constraint = match function {
                         KnownConstraintFunction::IsInstance => {
                             |class_literal: ClassLiteralType<'db>| {
-                                Type::anonymous_instance(class_literal.class)
+                                Type::Instance(InstanceType {
+                                    class: class_literal.class,
+                                })
```
Comment (carljm) [inline crates/red_knot_python_semantic/src/types/narrow.rs:358]: We do this a lot in this PR, I wonder about a `Class::to_instance_type()` method for it?

**Review by carljm — APPROVED** [review]
Looks great, thank you!!

**Comment by carljm** [comment]
I think I might resolve conflicts and land this, if that's OK with you? I'm realizing that I think I want to represent a TypeVar (not as a type, but the type of the typevar's own symbol, e.g. `T` in `def f[T](): ...`) as a `KnownInstanceType` with fallback type `typing.TypeVar`.

File: crates/red_knot_python_semantic/src/types/narrow.rs (hunk 2 above)
Comment (carljm) [reply crates/red_knot_python_semantic/src/types/narrow.rs:358]: This can be considered separately as a follow-up if it's worth it

**Comment by AlexWaygood** [comment]
Go for it! It's late here and I'm still travelling back from choir 👍

File: crates/red_knot_python_semantic/src/types/narrow.rs (hunk 2 above)
Comment (AlexWaygood) [reply crates/red_knot_python_semantic/src/types/narrow.rs:358]: https://github.com/astral-sh/ruff/pull/14215
