### PR TITLE
Implement `Invalid rule provided` as rule RUF102 with `--fix`

### LINKED ISSUE #17084: Implement "Invalid rule code provided to `# noqa`" as rule
### Summary

I have a lot of warning about codes which were removed in ruff:

`warning: Invalid rule code provided to '# noqa' at foo.py:123: ASYNC101`

It would be nice if that wasn't a warning but another ruff rule, so that i can easily let the wrong codes be removed with `--fix`.

### PR DESCRIPTION
**Pull request by maxmynter**
Closes #17084

## Summary
This PR adds a new rule (RUF102) to detect and fix invalid rule codes in `noqa` comments. 
Invalid rule codes in `noqa` directives serve no purpose and may indicate outdated code suppressions.

This extends the previous behaviour originating from `crates/ruff_linter/src/noqa.rs` which would only emit a warnigs.
With this rule a `--fix` is available.

The rule:
1. Analyzes all `noqa` directives to identify invalid rule codes
2. Provides autofix functionality to:
   - Remove the entire comment if all codes are invalid
   - Remove only the invalid codes when mixed with valid codes
3. Preserves original comment formatting and whitespace where possible

Example cases:
- `# noqa: XYZ111` → Remove entire comment (keep empty line)
- `# noqa: XYZ222, XYZ333` → Remove entire comment (keep empty line)
-  `# noqa: F401, INVALID123` → Keep only valid codes (`# noqa: F401`)

## Test Plan
- Added tests in `crates/ruff_linter/resources/test/fixtures/ruff/RUF102.py` covering different example cases.

## Notes 
- This does not handle cases where parsing fails. E.g. `# noqa: NON_EXISTENT, ANOTHER_INVALID` causes a `LexicalError` and the diagnostic is not propagated and we cannot handle the diagnostic. I am also unsure what proper `fix` handling would be and making the user aware we don't understand the codes is probably the best bet.
- The rule is added to the Preview rule group as it's a new addition

## Questions
- Should we remove the warnings, now that we have a rule?
- Is the current fix behavior appropriate for all cases, particularly the handling of whitespace and line deletions?
- I'm new to the codebase; let me know if there are rule utilities which could have used but didn't.

### CODE REVIEW

File: crates/ruff_linter/src/rules/ruff/mod.rs [hunk 1]
```diff
@@ -314,6 +314,16 @@ mod tests {
         Ok(())
     }
 
+    #[test]
+    fn ruf102() -> Result<()> {
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/ruff/mod.rs:318]: Can this be part of the general `rules` test up above?

**Comment by maxmynter** [comment]
Sorry for the CI issues, I thought that clippy runs with checking the pre-commit hooks. 

I thought I generated the docs with `cargo dev generate-all` and they are in the comment in the rule file. Am I supposed to do that differently?

File: crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs [hunk 2]
```diff
@@ -0,0 +1,157 @@
...
+    noqa_directives: &NoqaDirectives,
+    locator: &Locator,
+) {
+    for line in noqa_directives.lines() {
+        let Directive::Codes(directive) = &line.directive else {
+            continue;
+        };
+
+        let mut invalid_code_refs = vec![];
+        let mut valid_codes = vec![];
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs:59]: Having to always collect all codes only to be able to generate the fix isn't ideal for performance (this requires a fair amount of writes). 

I'd rewrite this to only track if all codes are invalid and then re-iterate over the noqa codes when generating the fix and skip over the known invalid codes.

File: crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs [hunk 3]
```diff
@@ -0,0 +1,157 @@
...
+
+    let mut diagnostic = Diagnostic::new(
+        InvalidRuleCode {
+            rule_code: invalid_codes,
+        },
+        directive.range(),
+    );
+
+    let original_text = locator.slice(line.range());
+    if let Some(comment_start) = original_text.find('#') {
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs:102]: Does this work with `# test # noqa: invalid`? Could we use `line.directive.range` (assuming `directive` is the `Codes` variant) here?

File: crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs [hunk 4]
```diff
@@ -0,0 +1,157 @@
...
+        let Directive::Codes(directive) = &line.directive else {
+            continue;
+        };
+
+        let mut invalid_code_refs = vec![];
+        let mut valid_codes = vec![];
+
+        for code in directive.iter() {
+            let code_str = code.as_str();
+            if Rule::from_code(code.as_str()).is_err() {
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs:63]: Can you test that this rule respects https://docs.astral.sh/ruff/settings/#lint_external

File: crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs [hunk 5]
```diff
@@ -0,0 +1,157 @@
...
+
+fn update_noqa(line: &NoqaDirectiveLine<'_>, valid_codes: &[&str], locator: &Locator) -> String {
+    let noqa_slice = "noqa:";
+    let formatted_codes = valid_codes.join(", ");
+    let original_text = locator.slice(line.range());
+
+    if let Some(noqa_idx) = original_text.find(noqa_slice) {
+        let prefix_end = noqa_idx + noqa_slice.len();
+        let prefix = &original_text[..prefix_end];
+        let codes_part = &original_text[prefix_end..];
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs:146]: Nit: I think there's a `split_at(prefix_end)` method that gives you both the before and after parts

File: crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs [hunk 6]
```diff
@@ -0,0 +1,157 @@
...
+        let whitespace_len = codes_part.chars().take_while(|c| c.is_whitespace()).count();
+        format!(
+            "{}{}{}",
+            prefix,
+            &codes_part[..whitespace_len],
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs:151]: This will panic if there is any non-ASCII whitespace because you pass the character count instead of the length in bytes. You'll have to use find or similar to find the end.

**Review by MichaReiser — CHANGES_REQUESTED** [review]

File: crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs (hunk 3 above)
Comment (maxmynter) [reply crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs]: Thanks for the directive suggestion. It's much cleaner (adressed in [f7014db](https://github.com/astral-sh/ruff/pull/17138/commits/f7014dbeb31f9d0805723358d57f442bfa7b020c)).

Regarding multiple comments on a line it removes the invalid parts
- `# test # noqa: INVALID111` → `# test`
- `# test # noqa: INVALID111, VALID111` → `# test # noqa: VALID111`

I've added tests for this in [5cc8305](https://github.com/astral-sh/ruff/pull/17138/commits/5cc83056e74b67c10fa889ae722947cfc5b99dcc). 

I guess this is the desired behaviour. Having stale comments isn't nice, but auto removing ones that should stay is worse. What do you think. 

Note: I'm writing it with uppercase ASCII plus a number because otherwise it's not parsed as a rule code; in this case the comment remains untouched.

File: crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs (hunk 4 above)
Comment (maxmynter) [reply crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs]: It didn't. I added a fix ([3f50765](https://github.com/astral-sh/ruff/pull/17138/commits/3f5076561ccae439d5fda1e2317e18a1582de184)) and test ([e734d3d](https://github.com/astral-sh/ruff/pull/17138/commits/e734d3db6e81383484f43c7de8a2b74041892a32)).

File: crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs (hunk 5 above)
Comment (maxmynter) [reply crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs]: Adressed in [2be49a0](https://github.com/astral-sh/ruff/pull/17138/commits/2be49a000fb06a45e1ea3cbca1bbb1d44c32eac2)

File: crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs (hunk 6 above)
Comment (maxmynter) [reply crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs]: Adressed in [e3f4e07](https://github.com/astral-sh/ruff/pull/17138/commits/e3f4e07105f3c733b1fc1617cc7284ab18e5915a)

File: crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs (hunk 2 above)
Comment (maxmynter) [reply crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs]: Adressed in [52abe14](https://github.com/astral-sh/ruff/pull/17138/commits/52abe145626186fea7ed68f6012ed791f085f269)

File: crates/ruff_linter/src/rules/ruff/mod.rs (hunk 1 above)
Comment (maxmynter) [reply crates/ruff_linter/src/rules/ruff/mod.rs:319]: I moved the test you were refering to to the general rules test. The additional logic handling externals (see below) need (i think) separate handling so i kept these parts standalone. Let me know if that is not the case.

Changes in [d34476f](https://github.com/astral-sh/ruff/pull/17138/commits/d34476f430d7a2417aa2929749fa19174f86fa8a)

Comment (ntBre) [reply crates/ruff_linter/src/rules/ruff/mod.rs:319]: I think that does need to be separate, thanks!

File: crates/ruff_linter/src/rules/ruff/mod.rs [hunk 7]
```diff
@@ -314,6 +315,20 @@ mod tests {
...
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/mod.rs:319]: NIt:
``` suggestion
    fn ruf102_external_rules() -> Result<()> {
```

File: crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs [hunk 8]
```diff
@@ -0,0 +1,159 @@
...
+/// Use instead:
+/// ```python
+/// import os
+/// ```
+///
+/// Or if there are still valid codes needed:
+/// ```python
+/// import os  # noqa: E402
+/// ```
+
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs:30]:
```suggestion
```

Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs:30]: It would be great to link to the `external` setting similar to `unused-noqa`: https://docs.astral.sh/ruff/rules/unused-noqa/

File: crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs [hunk 9]
```diff
@@ -0,0 +1,159 @@
...
+            continue;
+        };
+
+        let mut invalid_code_refs = vec![];
+        let mut all_invalid = true;
+
+        for code in directive.iter() {
+            let code_str = code.as_str();
+            if external.iter().any(|ext| code_str.starts_with(ext))
+                || Rule::from_code(code.as_str()).is_ok()
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs:65]:
```suggestion
            if Rule::from_code(code.as_str()).is_ok() || external.iter().any(|ext| code_str.starts_with(ext))
```

This might be faster because it checks the common case first.

Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs:65]:
```suggestion
            if external.iter().any(|ext| code_str.starts_with(ext))
                || Rule::from_code(code_str)).is_ok()
```

File: crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs [hunk 10]
```diff
@@ -0,0 +1,159 @@
...
+
+        if all_invalid {
+            handle_all_codes_invalid(diagnostics, directive);
+        } else {
+            let valid_codes = directive
+                .iter()
+                .filter_map(|code| {
+                    let code_str = code.as_str();
+                    if external.iter().any(|ext| code_str.starts_with(ext))
+                        || Rule::from_code(code_str).is_ok()
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs:85]: Nit: Maybe consider moving this to a small helper function and use it here and when checking above.

File: crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs [hunk 11]
```diff
@@ -0,0 +1,159 @@
...
+            handle_some_codes_invalid(diagnostics, &invalid_code_refs, &valid_codes, line, locator);
+        }
+    }
+}
+
+fn handle_all_codes_invalid(diagnostics: &mut Vec<Diagnostic>, directive: &Codes<'_>) {
+    let invalid_codes = directive
+        .iter()
+        .map(crate::noqa::Code::as_str)
+        .collect::<Vec<_>>()
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs:102]: Could we reuse the collected `invalid_code_refs` and pass them to this function instead of collecting them again?

File: crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs [hunk 12]
```diff
@@ -0,0 +1,159 @@
...
+                        None
+                    }
+                })
+                .collect::<Vec<_>>();
+            handle_some_codes_invalid(diagnostics, &invalid_code_refs, &valid_codes, line, locator);
+        }
+    }
+}
+
+fn handle_all_codes_invalid(diagnostics: &mut Vec<Diagnostic>, directive: &Codes<'_>) {
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs:98]: Nit: To reduce the number of arguments:
```suggestion
fn create_all_codes_invalid_diagnostic(directive: &Codes<'_>) -> Diagnostic {
```

File: crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs [hunk 13]
```diff
@@ -0,0 +1,159 @@
...
+        let mut diagnostic = Diagnostic::new(
+            InvalidRuleCode {
+                rule_code: invalid_code.as_str().to_string(),
+            },
+            invalid_code.range(),
+        );
+
+        diagnostic.set_fix(fix.clone());
+        diagnostics.push(diagnostic);
+    }
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs:136]: And another case for multispan diagnostics... 

I think I'd be surprised that applying the fix for a specific code replaces all invalid codes and not just the one where I positioned my cursor on. 

That's why I think we should either:

* Only create one diagnostic that fixes all invalid codes at once (multispan diagnostics would be great)
* Create a diagnostic for each invalid code, the fix only removes that one code.

**Review by MichaReiser — COMMENTED** [review]
Thanks for incorporating external. This mostly looks good. The main thing we've to figure out is how to handle noqa comments where more than one code is invalid. Maybe @dylwil3 has an opinion on this?

**Comment by maxmynter** [comment]
Sorry everyone who just got pinged for a code review. 

I accidentally pushed from the tip of main and it autorequested from everyone who contributed since forked.

My bad :/

File: crates/ruff_linter/src/rules/ruff/mod.rs (hunk 7 above)
Comment (maxmynter) [reply crates/ruff_linter/src/rules/ruff/mod.rs]: Adressed in [3050304](https://github.com/astral-sh/ruff/pull/17138/commits/3050304436fe33ca7e2fff3edf4b557edc6bc777)

File: crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs (hunk 8 above)
Comment (maxmynter) [reply crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs]: Adressed in [2fe49fb](https://github.com/astral-sh/ruff/pull/17138/commits/2fe49fb1b94dd11666f5bb841dfc6fb2fb9c3044)

Comment (maxmynter) [reply crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs]: Adressed in [2fe49fb](https://github.com/astral-sh/ruff/pull/17138/commits/2fe49fb1b94dd11666f5bb841dfc6fb2fb9c3044)

File: crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs (hunk 11 above)
Comment (maxmynter) [reply crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs:104]: We need to loop over the `directive` if we want to preserve the total order rule with only filtering codes for single code fixes.

File: crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs (hunk 13 above)
Comment (maxmynter) [reply crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs:138]: I think single code fixes are more appropriate. Errors could come from e.g. forgetting to apply an external rule. In that case I would not like to apply the fix but rather add the external rule. 

It would be annoying to not be able to apply the other fixes. 

What do you think?

File: crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs (hunk 9 above)
Comment (maxmynter) [reply crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs]: Adressed in [e9de061](https://github.com/astral-sh/ruff/pull/17138/commits/e9de061507c31e6087ac3cdfa5bcb551b5ebbc04)

File: crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs (hunk 10 above)
Comment (maxmynter) [reply crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs]: Adressed in [921f066](https://github.com/astral-sh/ruff/pull/17138/commits/921f0663f93257af10cdc8a5aec7fb7f34bad877)

File: crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs (hunk 12 above)
Comment (maxmynter) [reply crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs]: Adressed in [921f066](https://github.com/astral-sh/ruff/pull/17138/commits/921f0663f93257af10cdc8a5aec7fb7f34bad877)

File: crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs (hunk 13 above)
Comment (maxmynter) [reply crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs]: I'm unsure what you mean by multispan diagnostics or what the exact requirements are. Is that already established in Ruff or something you plan on integrating.

In [921f066](https://github.com/astral-sh/ruff/pull/17138/commits/921f0663f93257af10cdc8a5aec7fb7f34bad877) i fixed the handling to create one diagnostic for each invalid code.

Comment (MichaReiser) [reply crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs]: > I'm unsure what you mean by multispan diagnostics or what the exact requirements are. Is that already established in Ruff or something you plan on integrating.

Sorry, it's something we plan on implementing. This was mainly directed at @ntBre

**Review by MichaReiser — APPROVED** [review]

File: crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs (hunk 13 above)
Comment (dhruvmanila) [reply crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs]: We could create a tracking issue for it which can then be referenced by the reviewers and the references itself becomes a list of known places which can be improved.

Comment (ntBre) [reply crates/ruff_linter/src/rules/ruff/rules/invalid_rule_code.rs]: Oh yes, of course!

**Comment by maxmynter** [comment]
Thanks for merging @MichaReiser !

If you have the bandwith, I would love a short explanation on your rationale in [e1998a1](https://github.com/astral-sh/ruff/pull/17138/commits/e1998a1e3426ef2140f6c18bdc87b9a8ddc5c35c) (no worries if not). 

I agree that it reads much nicer, so I'm curious if you have any tips / resources on how you think about intended changes so i can deliver more quality out of the gate :)
