### PR TITLE
[`flake8-bugbear`] Support non-context-manager calls in `B017`

### LINKED ISSUE #19050: [`flake8-bugbear`] `B017` does not support non-`with` calls
### Summary

I found this while working on https://github.com/astral-sh/ruff/issues/18972

[assert-raises-exception (B017)](https://docs.astral.sh/ruff/rules/assert-raises-exception/#assert-raises-exception-b017) does not lint on non-`with` calls, even though both `unittest` and `pytest` support them:
https://play.ruff.rs/c875da29-d677-4f97-ad23-2efd2fa88231
```py
import unittest

def func_that_will_raise():
    raise ValueError

class Tests(unittest.TestCase):
    def test_raises(self):
        with self.assertRaises(Exception):  # B017
            func_that_will_raise()
        self.assertRaises(Exception, func_that_will_raise)  # No error


import pytest

def test_raises():
    with pytest.raises(Exception):  # B017
        func_that_will_raise()

pytest.raises(Exception, func_that_will_raise)  # No error
```
[`unittest` docs on `assertRaises`](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaises)
[`pytest` docs on alternate `raises` form](https://docs.pytest.org/en/stable/how-to/assert.html#alternate-pytest-raises-form-legacy)

### Version

playground

### PR DESCRIPTION
**Pull request by danparizher**
## Summary

Fixes #19050

### CODE REVIEW

File: crates/ruff_linter/src/rules/flake8_bugbear/rules/assert_raises_exception.rs [hunk 1]
```diff
@@ -103,3 +103,43 @@ pub(crate) fn assert_raises_exception(checker: &Checker, items: &[WithItem]) {
         checker.report_diagnostic(AssertRaisesException { exception }, item.range());
     }
 }
+
+/// B017 (call form)
+pub(crate) fn assert_raises_exception_call(checker: &Checker, call: &ast::ExprCall) {
+    let semantic = checker.semantic();
+
+    let func = &call.func;
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/flake8_bugbear/rules/assert_raises_exception.rs]: Would it help to destructure the whole `ExprCall` here? I think we could use `func`, `arguments`, and even `range` down below.

```suggestion
    let ast::ExprCall { func, arguments, range, .. } = call;
```

File: crates/ruff_linter/src/rules/flake8_bugbear/rules/assert_raises_exception.rs [hunk 2]
```diff
@@ -103,3 +103,43 @@ pub(crate) fn assert_raises_exception(checker: &Checker, items: &[WithItem]) {
...
+        return;
+    };
+
+    let exception = match builtin_symbol {
+        "Exception" => ExceptionKind::Exception,
+        "BaseException" => ExceptionKind::BaseException,
+        _ => return,
+    };
+
+    checker.report_diagnostic(AssertRaisesException { exception }, call.func.range());
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/flake8_bugbear/rules/assert_raises_exception.rs]: Do you think we could reuse the code from `assert_raises_exception` for this? This looks correct and pretty similar, but I think we want to keep the two in sync. I could be missing a bigger difference, but intuitively it seems like once we've destructured the `Call` in `assert_raises_exception`, the logic should be the same.

File: crates/ruff_linter/src/rules/flake8_bugbear/rules/assert_raises_exception.rs (hunk 1 above)
Comment (danparizher) [reply crates/ruff_linter/src/rules/flake8_bugbear/rules/assert_raises_exception.rs]: Good idea — done. `assert_raises_exception_call` now takes it so we can use it directly.

File: crates/ruff_linter/src/rules/flake8_bugbear/rules/assert_raises_exception.rs (hunk 2 above)
Comment (danparizher) [reply crates/ruff_linter/src/rules/flake8_bugbear/rules/assert_raises_exception.rs]: Absolutely. I pulled the shared checks into a helper, `detect_blind_exception`, which both the context-manager path and the new call-form path now invoke. This keeps the two in sync.

**Comment by danparizher** [comment]
Preview flag added. The call-form check only runs when `is_assert_raises_exception_call_enabled(settings)` is `true`.

**Comment by ntBre** [comment]
Great, thanks! Could you also add a preview test? You can just make a copy of the `rules` function and the `B017` `test_case` and set `LinterSettings::preview` to `PreviewMode::Enabled`.

https://github.com/astral-sh/ruff/blob/48366a7bbb5e555b288b4a00e5bc862670e8dbc1/crates/ruff_linter/src/rules/flake8_bugbear/mod.rs#L73-L81

**Comment by danparizher** [comment]
Added!

File: crates/ruff_linter/src/rules/flake8_bugbear/rules/assert_raises_exception.rs [hunk 3]
```diff
@@ -56,6 +56,39 @@ impl fmt::Display for ExceptionKind {
...
+
+    let is_pytest_raises = semantic
+        .resolve_qualified_name(func)
+        .is_some_and(|qualified_name| matches!(qualified_name.segments(), ["pytest", "raises"]));
+
+    if !(is_assert_raises || is_pytest_raises) {
+        return None;
+    }
+
+    if is_pytest_raises && arguments.find_keyword("match").is_some() {
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/flake8_bugbear/rules/assert_raises_exception.rs]: I think this is supposed to be `is_none` like before right?

```suggestion
    if is_pytest_raises && arguments.find_keyword("match").is_none() {
```

It's a little hard to tell because the diff shifted around, but I'm pretty sure one of the snapshots is showing a different result.

I think this `is_some` is actually correct and the existing `is_none` is a bug unless I'm misunderstanding something, but I'd rather handle that separately, I guess.

File: crates/ruff_linter/resources/test/fixtures/flake8_bugbear/B017.py [hunk 4]
```diff
@@ -40,6 +40,10 @@ def raises_with_absolute_reference(self):
         with self.assertRaises(asyncio.CancelledError):
             Foo()
 
+    def call_form_raises(self) -> None:
+        self.assertRaises(Exception, something_else)
+        self.assertRaises(BaseException, something_else)
+
```
Comment (ntBre) [inline crates/ruff_linter/resources/test/fixtures/flake8_bugbear/B017.py]: I know it would mess up the nice sections here, but it would be easier for reviewing the test diff if these were at the bottom with the other new tests. If you put enough blank lines, the non-preview snapshot should be unchanged, and only the new preview snapshot will be different. Alternatively, you could rename this file to B017_0.py and add B017_1.py with the new tests.

I was fine with this layout before, but I'd like to be sure we're not changing any logic with the `is_none` vs `is_some` thing, and this will make that easier.

File: crates/ruff_linter/src/rules/flake8_bugbear/rules/assert_raises_exception.rs [hunk 5]
```diff
@@ -73,33 +106,31 @@ pub(crate) fn assert_raises_exception(checker: &Checker, items: &[WithItem]) {
...
+        arguments,
+        range: _,
+        node_index: _,
+    }: &ast::ExprCall,
+) {
+    let semantic = checker.semantic();
+
+    if arguments.args.len() < 2 && arguments.find_argument("func", 1).is_none() {
+        return;
+    }
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/flake8_bugbear/rules/assert_raises_exception.rs:140]: I don't think this `find_argument` call will ever succeed. If we have fewer than 2 arguments, there won't be an argument in position 1, only a maximum of 1 argument in position 0. Should this be an `||`? If so, we might need a test exercising this.

File: crates/ruff_linter/src/rules/flake8_bugbear/rules/assert_raises_exception.rs [hunk 6]
```diff
@@ -73,33 +106,31 @@ pub(crate) fn assert_raises_exception(checker: &Checker, items: &[WithItem]) {
...
 
-        checker.report_diagnostic(AssertRaisesException { exception }, item.range());
+    if let Some(exception) = detect_blind_exception(semantic, func.as_ref(), arguments) {
+        checker.report_diagnostic(AssertRaisesException { exception }, func.range());
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/flake8_bugbear/rules/assert_raises_exception.rs]: I think this is supposed to be the `call` range to match the `with` version.

```suggestion
        checker.report_diagnostic(AssertRaisesException { exception }, range);
```

with `range` from the `ExprCall` above.

**Review by ntBre — COMMENTED** [review]
Thanks!

I noticed a few more things here, but it's looking good.

File: crates/ruff_linter/src/rules/flake8_bugbear/rules/assert_raises_exception.rs (hunk 5 above)
Comment (danparizher) [reply crates/ruff_linter/src/rules/flake8_bugbear/rules/assert_raises_exception.rs:140]: My understanding is that `Arguments::find_argument` doesn’t just look at positional arguments – it first looks for a keyword with the given name and only falls back to the positional slot if that keyword isn’t present:

```rust
pub fn find_argument(&self, name: &str, position: usize) -> Option<ArgOrKeyword> {
    self.find_keyword(name)              // ← check `func=…`
        .map(ArgOrKeyword::from)
        .or_else(|| self.find_positional(position).map(ArgOrKeyword::from))
}
```
So in a call such as
```python
pytest.raises(Exception, func=my_func)
```
- `arguments.args.len()` is `1` (the `Exception`), so `len() < 2` is `true`.
- `find_argument("func", 1)` does return `Some(...)` because it finds the keyword `func=…`.

If we changed the guard to `||`, we would exit early whenever either condition is true, and we’d wrongly skip the check in the keyword-argument case.

File: crates/ruff_linter/src/rules/flake8_bugbear/rules/assert_raises_exception.rs (hunk 3 above)
Comment (danparizher) [reply crates/ruff_linter/src/rules/flake8_bugbear/rules/assert_raises_exception.rs]: Unless I'm missing something, I believe `is_some()` is the right test here. `pytest.raises(..., match="pattern")` is a form that already narrows the check to a specific exception message (equivalent to the `assertRaisesRegex` case for `unittest`), so when that `match=` keyword is present we want to *skip* B017, because it’s no longer a “blind” exception assertion.

File: crates/ruff_linter/src/rules/flake8_bugbear/rules/assert_raises_exception.rs (hunk 5 above)
Comment (ntBre) [reply crates/ruff_linter/src/rules/flake8_bugbear/rules/assert_raises_exception.rs:140]: Ahh, I think you're right. `arguments.args.len()` is only the positional arguments. I was thinking of `arguments.len()`, which includes both.

File: crates/ruff_linter/src/rules/flake8_bugbear/rules/assert_raises_exception.rs (hunk 3 above)
Comment (ntBre) [reply crates/ruff_linter/src/rules/flake8_bugbear/rules/assert_raises_exception.rs]: Hmm, maybe I got confused by the logic here. The snapshot on `main` looks correct. Let's regroup the test cases and make sure none of the stable results change, but I think you may be right.

`is_some` definitely makes sense intuitively, I guess the condition was negated in the original code.

File: crates/ruff_linter/resources/test/fixtures/flake8_bugbear/B017.py (hunk 4 above)
Comment (danparizher) [reply crates/ruff_linter/resources/test/fixtures/flake8_bugbear/B017.py]: I split up the test cases, let me know if that's what you were looking for. Feel free to commit directly if there is another format that makes more sense 🙂

File: crates/ruff_linter/src/rules/flake8_bugbear/snapshots/ruff_linter__rules__flake8_bugbear__tests__B017_B017_0.py.snap [hunk 7]
```diff
@@ -35,7 +35,16 @@ B017.py:48:10: B017 Do not assert blind exception: `Exception`
...
+B017_0.py:51:10: B017 Do not assert blind exception: `Exception`
+   |
+49 |         raise ValueError("Hello")
+50 |
+51 |     with pytest.raises(Exception, "hello"):
+   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ B017
+52 |         raise ValueError("This is fine")
+   |
+
+B017_0.py:57:36: B017 Do not assert blind exception: `Exception`
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/flake8_bugbear/snapshots/ruff_linter__rules__flake8_bugbear__tests__B017_B017_0.py.snap]: I pushed a couple of commits to minimize the diff a bit more. I think something _is_ slightly off with the new logic because it looks like this is getting flagged now when it should be allowed, but I haven't pinned down where it is.

Comment (danparizher) [reply crates/ruff_linter/src/rules/flake8_bugbear/snapshots/ruff_linter__rules__flake8_bugbear__tests__B017_B017_0.py.snap]: I found the issue—we weren't considering the second positional string/bytes literal argument. I added in that additional check so now it's not registering as a false positive anymore.
