### PR TITLE
Fix reference definition labels for backtick-quoted shortcut links

### LINKED ISSUE #16010: Backtick-quoted shortcut links in rule documentation
`FAST002`'s rule documentation reads:

`````markdown
The [FastAPI documentation] recommends the use of [`typing.Annotated`] for
<!-- ... -->
[fastAPI documentation]: https://fastapi.tiangolo.com/tutorial/query-params-str-validations/?h=annotated#advantages-of-annotated
[typing.Annotated]: https://docs.python.org/3/library/typing.html#typing.Annotated
`````

This is how PyCharm renders it:

And GitHub:

> The [FastAPI documentation] recommends the use of [`typing.Annotated`] for
> 
> [fastAPI documentation]: https://fastapi.tiangolo.com/tutorial/query-params-str-validations/?h=annotated#advantages-of-annotated
> [typing.Annotated]: https://docs.python.org/3/library/typing.html#typing.Annotated

CommonMark dingus [is no different](https://spec.commonmark.org/dingus/?text=The%20%5BFastAPI%20documentation%5D%20recommends%20the%20use%20of%20%5B%60typing.Annotated%60%5D%20for%0A%3C!--%20...%20--%3E%0A%5BfastAPI%20documentation%5D%3A%20https%3A%2F%2Ffastapi.tiangolo.com%2Ftutorial%2Fquery-params-str-validations%2F%3Fh%3Dannotated%23advantages-of-annotated%0A%5Btyping.Annotated%5D%3A%20https%3A%2F%2Fdocs.python.org%2F3%2Flibrary%2Ftyping.html%23typing.Annotated%0A):

```html
<p>The <a href="https://fastapi.tiangolo.com/tutorial/query-params-str-validations/?h=annotated#advantages-of-annotated">FastAPI documentation</a> recommends the use of [<code>typing.Annotated</code>] for</p>
```

---

[Shortcut reference links](https://spec.commonmark.org/0.31.2/#shortcut-reference-link) of the form ```[`something`]``` must have a corresponding [link reference definition](https://spec.commonmark.org/0.31.2/#link-reference-definition) whose [label](https://spec.commonmark.org/0.31.2/#link-label) is also backtick-quoted (related: #14348).

For reference, the matching algorithm is [defined](https://spec.commonmark.org/0.31.2/#matches) as:

> One label <b>matches</b> another just in case their normalized forms are equal. To normalize a label, strip off the opening and closing brackets, perform the <i>Unicode case fold</i>, strip leading and trailing spaces, tabs, and line endings, and collapse consecutive internal spaces, tabs, and line endings to a single space.

Here's what a fix would look like:

```diff
 The [FastAPI documentation] recommends the use of [`typing.Annotated`] for
 <!-- ... -->
 [fastAPI documentation]: https://fastapi.tiangolo.com/tutorial/query-params-str-validations/?h=annotated#advantages-of-annotated
-[typing.Annotated]: https://docs.python.org/3/library/typing.html#typing.Annotated
+[`typing.Annotated`]: https://docs.python.org/3/library/typing.html#typing.Annotated
```

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
## Summary

Resolves #16010.

The changes boil down to something like this:

```diff
-/// The [FastAPI documentation] recommends the use of [`typing.Annotated`]
+/// The [FastAPI documentation] recommends the use of [`typing.Annotated`][typing-annotated]

-/// [typing.Annotated]: https://docs.python.org/3/library/typing.html#typing.Annotated
+/// [typing-annotated]: https://docs.python.org/3/library/typing.html#typing.Annotated
```

## Test Plan

Mkdocs:

GitHub:

> ## Why is this bad?
> The [FastAPI documentation] recommends the use of [`typing.Annotated`][typing-annotated]
> 
> ...
>
> [FastAPI documentation]: https://fastapi.tiangolo.com/tutorial/query-params-str-validations/?h=annotated#advantages-of-annotated
> [typing-annotated]: https://docs.python.org/3/library/typing.html#typing.Annotated

[CommonMark dingus](https://spec.commonmark.org/dingus/?text=%23%23%20Why%20is%20this%20bad%3F%0AThe%20%5BFastAPI%20documentation%5D%20recommends%20the%20use%20of%20%5B%60typing.Annotated%60%5D%5Btyping-annotated%5D%0A%0A...%0A%0A%5BFastAPI%20documentation%5D%3A%20https%3A%2F%2Ffastapi.tiangolo.com%2Ftutorial%2Fquery-params-str-validations%2F%3Fh%3Dannotated%23advantages-of-annotated%0A%5Btyping-annotated%5D%3A%20https%3A%2F%2Fdocs.python.org%2F3%2Flibrary%2Ftyping.html%23typing.Annotated):

```html
<h2>Why is this bad?</h2>
<p>The <a href="https://fastapi.tiangolo.com/tutorial/query-params-str-validations/?h=annotated#advantages-of-annotated">FastAPI documentation</a> recommends the use of <a href="https://docs.python.org/3/library/typing.html#typing.Annotated"><code>typing.Annotated</code></a></p>
<p>...</p>
```

### CODE REVIEW

**Comment by Daverball** [comment]
> I _think_ that's all of them. More importantly, there should be a test somewhere so that such a link can't possibly be accidentally introduced again. Where would I even put that?

Possibly here? https://github.com/astral-sh/ruff/blob/main/scripts/check_docs_formatted.py

That's where all of the other custom docs checks appear to happen. Although the main purpose appears to be ensuring that the examples are formatted correctly, there are a couple of unrelated checks as well, like ensuring the required sections for rule docs are present.

File: crates/ruff_linter/src/rules/ruff/rules/unsafe_markup_use.rs [hunk 1]
```diff
@@ -70,9 +70,8 @@ use crate::{checkers::ast::Checker, settings::LinterSettings};
 ///
 /// ## References
 /// - [MarkupSafe](https://pypi.org/project/MarkupSafe/)
-/// - [`markupsafe.Markup`](https://markupsafe.palletsprojects.com/en/stable/escaping/#markupsafe.Markup)
```
Comment (Daverball) [inline crates/ruff_linter/src/rules/ruff/rules/unsafe_markup_use.rs:73]: This is getting rid of the link in the references section (which is rendered), so I don't think we want to remove this. You could omit the explicit url portion of the reference, since it's technically redundant, although given that the labels in  the references section are sometimes changed to a more verbose, descriptive, style, I used an explicit link, so changing the label later on is easy. I don't think i have seen any shortcut links be used in other references sections.

**Comment by MichaReiser** [comment]
Would you mind updating your test plan and showing the rendered documentation for a page before/after your change (doesn't have to be for all of them, just pick one ;))

**Review by MichaReiser — APPROVED** [review]
It would be great if we'd have some linting or at least, guidance in the contribution guidelines. I otherwise worry, that we'll introduce incompatible links in the future. But that's something we can do separately. 

Thank you!
