### PR TITLE
[red-knot] Callable types are disjoint from literals

### LINKED ISSUE #17144: [red-knot] `subtype_of_implies_not_disjoint_from` property test is now flaky
I got this property test failure on a local PR branch:

```
failures:

---- types::property_tests::stable::subtype_of_implies_not_disjoint_from stdout ----

thread 'types::property_tests::stable::subtype_of_implies_not_disjoint_from' panicked at /Users/alexw/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/quickcheck-1.0.3/src/tester.rs:165:28:
[quickcheck] TEST FAILED. Arguments: (Intersection { pos: [Callable { params: List([Param { kind: PositionalOnly, name: Some(Name("n1")), annotated_ty: Some(KnownClassInstance(Object)), default_ty: None }]), returns: Some(StringLiteral("")) }, StringLiteral("")], neg: [] }, LiteralString)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Which I minimized down to this:

```py
from typing import Callable, Literal, LiteralString
from knot_extensions import Intersection, static_assert, is_subtype_of, is_disjoint_from

static_assert(is_subtype_of(Intersection[Callable[[], None], Literal[""]], LiteralString))
static_assert(not is_disjoint_from(Intersection[Callable[[], None], Literal[""]], LiteralString))  # This assertion fails, but should logically hold true if the first assertion passes!
```

And the minimal repro also reproduces on `main`: https://playknot.ruff.rs/8cad645a-b986-42b8-baa7-ef8b75e81b3e

cc. @dhruvmanila

### PR DESCRIPTION
**Pull request by dhruvmanila**
## Summary

A callable type is disjoint from other literal types. For example, `Type::StringLiteral` must be an instance of exactly `str`, not a subclass of `str`, and `str` is not callable. The same applies to other literal types.

This should hopefully fix #17144, I couldn't produce any failures after running property tests multiple times.

## Test Plan

Add test cases for disjointness check between callable and other literal types.

Run property tests multiple times.

### CODE REVIEW

File: crates/red_knot_python_semantic/src/types.rs [hunk 1]
```diff
@@ -1393,6 +1393,20 @@ impl<'db> Type<'db> {
...
+            )
+            | (
+                Type::StringLiteral(_) | Type::BytesLiteral(_) | Type::SliceLiteral(_),
+                Type::Callable(_),
+            ) => {
+                // A callable type is disjoint from other literal types. For example,
+                // `Type::StringLiteral` must be an instance of exactly `str`, not a subclass
+                // of `str`, and `str` is not callable. The same applies to other literal types.
+                true
+            }
```
Comment (dhruvmanila) [inline crates/red_knot_python_semantic/src/types.rs:1408]: Other literals are handled directly with a catch-all combination:

* `BooleanLiteral`: https://github.com/astral-sh/ruff/blob/c2bb5d52507621ec5905dbb72ce187d989dd934f/crates/red_knot_python_semantic/src/types.rs#L1311-L1311
* `IntLiteral`: https://github.com/astral-sh/ruff/blob/c2bb5d52507621ec5905dbb72ce187d989dd934f/crates/red_knot_python_semantic/src/types.rs#L1320-L1320
* `LiteralString`: https://github.com/astral-sh/ruff/blob/c2bb5d52507621ec5905dbb72ce187d989dd934f/crates/red_knot_python_semantic/src/types.rs#L1339-L1339

**Review by AlexWaygood — APPROVED** [review]
Thank you! One interesting thing to note is that `Callable` types are _not_ necessarily disjoint from `ModuleLiteral` types, as it _is_ possible for a module to be a subclass of `types.ModuleType` (you have to manually inject it into `sys.modules` at runtime, but once it's imported in another module it _would_ be recognised by red-knot as a `ModuleLiteral` type). And that subclass of `types.ModuleType` could possibly be callable.

This isn't something you get wrong in this PR, just something you might find interesting!
