### PR TITLE
[`refurb`] Mark `single-item-membership-test` fix as always unsafe (`FURB171`)

### LINKED ISSUE #20255: `single-item-membership-test` (FURB171) should be marked unsafe
### Summary

[`single-item-membership-test` (FURB171)](https://docs.astral.sh/ruff/rules/single-item-membership-test/) can change behavior in two ways. First, `in` tries both `is` and `==`, whereas the fix is just `==`, which changes behavior for values like NaN. There is no way to know in general which values it is safe for, although it would be possible for this rule to safely special-case certain expressions like `str` and number literals. Second, `in` returns a `bool` whereas `==` can return anything. The current fix is only safe in boolean contexts like a `bool` argument or an `if` condition. Otherwise, the fix should be marked unsafe or the fix should wrap the expression in a `bool` call (or use the `not` operator, in the negated case). [Example](https://play.ruff.rs/764834c7-4ee1-4126-b270-9ce50dc5f014):
```console
$ cat >furb171.py <<'# EOF'
import numpy as np
print(np.nan in [np.nan])
print(np.zeros(1) in [np.zeros(1)])
# EOF

$ python furb171.py
True
True

$ ruff --isolated check furb171.py --select FURB171 --preview --fix
Found 2 errors (2 fixed, 0 remaining).

$ cat furb171.py
import numpy as np
print(np.nan == np.nan)
print(np.zeros(1) == np.zeros(1))

$ python furb171.py
False
[ True]
```
When the container is a string literal and the fix is currently marked safe, that’s fine. This is only an issue for `list`, `tuple`, `set`, and `frozenset`.

### Version

ruff 0.12.12 (c6516e9b6 2025-09-04)

### PR DESCRIPTION
**Pull request by TaKO8Ki**
## Summary

Fixes #20255

Mark single-item-membership-test fixes as always unsafe

- Always set `Applicability::Unsafe` for FURB171 fixes
- Update “Fix safety” docs to reflect always-unsafe behavior
- Expand tests (not in, nested set/frozenset, commented args)

## Test Plan

I have added new test cases to `crates/ruff_linter/resources/test/fixtures/refurb/FURB171_0.py` and `crates/ruff_linter/resources/test/fixtures/refurb/FURB171_1.py`.

### CODE REVIEW

File: crates/ruff_linter/src/rules/refurb/rules/single_item_membership_test.rs [hunk 1]
```diff
@@ -100,12 +98,8 @@ pub(crate) fn single_item_membership_test(
...
     );
 
-    let applicability =
-        if right.is_string_literal_expr() || checker.comment_ranges().intersects(expr.range()) {
-            Applicability::Unsafe
-        } else {
-            Applicability::Safe
-        };
+    // All supported cases can change runtime behavior; mark as unsafe.
+    let applicability = Applicability::Unsafe;
```
Comment (TaKO8Ki) [inline crates/ruff_linter/src/rules/refurb/rules/single_item_membership_test.rs]: Previously, fixes were marked unsafe only for string literals and when comments intersected the edit range, but single‑item list/tuple/set/frozenset cases can also
  change behavior (e.g., NaN identity differences and non‑boolean eq), so we now mark all FURB171 fixes as unsafe.

File: crates/ruff_linter/src/rules/refurb/rules/single_item_membership_test.rs [hunk 2]
```diff
@@ -100,12 +98,8 @@ pub(crate) fn single_item_membership_test(
...
 
     let fix = Fix::applicable_edit(edit, applicability);
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/single_item_membership_test.rs]: We could just use `Fix::unsafe_edit` now that it's always unsafe instead of a separate `applicability`.

File: crates/ruff_linter/src/rules/refurb/rules/single_item_membership_test.rs [hunk 3]
```diff
@@ -27,13 +27,11 @@ use crate::{Applicability, Edit, Fix, FixAvailability, Violation};
...
 ///
-/// When the right-hand side is a string, the fix is marked as unsafe.
-/// This is because `c in "a"` is true both when `c` is `"a"` and when `c` is the empty string,
-/// so the fix can change the behavior of your program in these cases.
-///
-/// Additionally, if there are comments within the fix's range,
-/// it will also be marked as unsafe.
+/// Converting `in`/`not in` against a single-item container to `==`/`!=` can
+/// change runtime behavior: `in` may consider identity (e.g., `NaN`), it always
+/// yields a `bool`, and comments within the replacement range may be removed.
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/single_item_membership_test.rs]: I think we should probably preserve the details about strings from the original docs. The `in` vs `==` thing seems pretty niche, while the string case seems more likely, so it feels worth mentioning both.

File: crates/ruff_linter/src/rules/refurb/rules/single_item_membership_test.rs (hunk 2 above)
Comment (TaKO8Ki) [reply crates/ruff_linter/src/rules/refurb/rules/single_item_membership_test.rs]: I've replaced it with `unsafe_edit`.

File: crates/ruff_linter/src/rules/refurb/rules/single_item_membership_test.rs (hunk 3 above)
Comment (TaKO8Ki) [reply crates/ruff_linter/src/rules/refurb/rules/single_item_membership_test.rs]: I have revived a part of original docs.

File: crates/ruff_linter/src/rules/refurb/rules/single_item_membership_test.rs [hunk 4]
```diff
@@ -27,13 +27,14 @@ use crate::{Applicability, Edit, Fix, FixAvailability, Violation};
...
-/// When the right-hand side is a string, the fix is marked as unsafe.
+/// When the right-hand side is a string, this fix can change the behavior of your program.
 /// This is because `c in "a"` is true both when `c` is `"a"` and when `c` is the empty string,
-/// so the fix can change the behavior of your program in these cases.
 ///
-/// Additionally, if there are comments within the fix's range,
-/// it will also be marked as unsafe.
+/// Converting `in`/`not in` against a single-item container to `==`/`!=` can
+/// change runtime behavior: `in` may consider identity (e.g., `NaN`), it always
+/// yields a `bool`, and comments within the replacement range may be removed.
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/single_item_membership_test.rs]:
```suggestion
/// Additionally, converting `in`/`not in` against a single-item container to `==`/`!=` can
/// change runtime behavior: `in` may consider identity (e.g., `NaN`) and always
/// yields a `bool`. 
///
/// Comments within the replacement range will also be removed.
```

File: crates/ruff_linter/src/rules/refurb/rules/single_item_membership_test.rs [hunk 5]
```diff
@@ -27,13 +27,14 @@ use crate::{Applicability, Edit, Fix, FixAvailability, Violation};
 /// ```
 ///
 /// ## Fix safety
+/// The fix is always marked as unsafe.
 ///
-/// When the right-hand side is a string, the fix is marked as unsafe.
+/// When the right-hand side is a string, this fix can change the behavior of your program.
 /// This is because `c in "a"` is true both when `c` is `"a"` and when `c` is the empty string,
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/single_item_membership_test.rs]:
```suggestion
/// This is because `c in "a"` is true both when `c` is `"a"` and when `c` is the empty string.
```

**Review by ntBre — APPROVED** [review]
Thank you! Just a couple of small docs nits that I'll apply and then merge this :)
