### PR TITLE
Fix bug where methods defined using lambdas were flagged by FURB118

### LINKED ISSUE #13829: [preview] FURB118 can be unsafe for methods
If you run with `preview` set, then the FURB118 check makes an unsafe replacement, you can see me rolling back the change https://github.com/wntrblm/nox/pull/870/commits/a91dbe2356a42bf8d2f03021ccd3b19a903484c8 to make the tests pass, the difference in behavior can be shown with this MWE:

```pycon
>>> class A:
...     pass
...  
>>> A.__eq__ = lambda a, b: a == b
>>> A() == A()
Traceback (most recent call last):
  File "<python-input-5>", line 1, in <module>
    A() == A()
  File "<python-input-4>", line 1, in <lambda>
    A.__eq__ = lambda a, b: a == b
                            ^^^^^^
  File "<python-input-4>", line 1, in <lambda>
    A.__eq__ = lambda a, b: a == b
                            ^^^^^^
  File "<python-input-4>", line 1, in <lambda>
    A.__eq__ = lambda a, b: a == b
                            ^^^^^^
  [Previous line repeated 988 more times]
RecursionError: maximum recursion depth exceeded
>>> import operator
>>> A.__eq__ = operator.eq
>>> A() == A()
Traceback (most recent call last):
  File "<python-input-8>", line 1, in <module>
    A() == A()
TypeError: eq expected 2 arguments, got 1
```

### PR DESCRIPTION
**Pull request by AlexWaygood**
## Summary

Fixes #13829.

Replacing an instance method definition with an `operator`-module function doesn't work, because instance methods need to be callable objects with `__get__` methods ("descriptors"), and while user-defined functions are descriptors, this is not true for the `operator`-module functions. We already avoid flagging user-defined methods that are defined using `def` statements, but we currently incorrectly flag user-defined functions that are defined by assigning `lambda`s to variables in class bodies. I.e., this is a perfectly valid definition of an instance method, and FURB118's suggestion to replace the lambda with `operator.eq` function would break it:

```py
class Spam:
    foo = lambda self, other: self == other
```

As a demonstration in the REPL:

```pycon
>>> class Spam:
...     foo = lambda self, other: self == other
...     
>>> Spam().foo(Spam())
False
>>> from operator import eq
>>> class Spam:
...     foo = eq
...     
>>> Spam().foo(Spam())
Traceback (most recent call last):
  File "<python-input-4>", line 1, in <module>
    Spam().foo(Spam())
    ~~~~~~~~~~^^^^^^^^
TypeError: eq expected 2 arguments, got 1
```

This PR fixes things so that `lambda` assignments in class bodies are considered off-limits for the rule in the same way as `def` statements in class bodies. It also makes the fix-safety docs more expansive, so that they're clearer that there's a wider range of reasons why the rule might be unsafe than just the keyword-argument issue.

## Test Plan

I added a new fixture that confirms that all function definitions in class bodies are ignored by the rule.

### CODE REVIEW

**Comment by AlexWaygood** [comment]
Hmm, the `airflow` hits in the ecosystem check are false negatives. I think I can avoid them.

File: crates/ruff_linter/src/checkers/ast/analyze/expression.rs [hunk 1]
```diff
@@ -1650,6 +1650,11 @@ pub(crate) fn expression(expr: &Expr, checker: &mut Checker) {
                 ruff::rules::assignment_in_assert(checker, expr);
             }
         }
+        Expr::Lambda(lambda_expr) => {
+            if checker.enabled(Rule::ReimplementedOperator) {
+                refurb::rules::reimplemented_operator(checker, &lambda_expr.into());
+            }
+        }
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/checkers/ast/analyze/expression.rs:1657]: This needed to be moved from `deferred_lambdas.rs` to `expressions.rs` because otherwise the semantic model doesn't understand that the lambda it's analysing is ever inside a class scope. As far as I can tell, there's no particular advantage associated with deferring the analysis of this rule to after the semantic model has been fully built; it never analyses any bindings or uses of bindings

**Comment by AlexWaygood** [comment]
https://github.com/astral-sh/ruff/pull/14639/commits/7e13565d1feb8af7a2b8c6fe0e1b8066195c0cc9 got rid of the new false negatives this PR initially introduced on `airflow`. The remaining ecosystem hit on `zerver` is also a false negative, but I think it's acceptable personally. Flagging lambdas inside assignments in class scopes is too risky.

File: crates/ruff_linter/src/checkers/ast/analyze/expression.rs (hunk 1 above)
Comment (MichaReiser) [reply crates/ruff_linter/src/checkers/ast/analyze/expression.rs:1657]: Thanks for writing this comment. It saved me quiet some time guessing why it was moved.

File: crates/ruff_linter/src/rules/refurb/rules/reimplemented_operator.rs [hunk 2]
```diff
@@ -78,11 +91,15 @@ impl Violation for ReimplementedOperator {
...
+    // Ignore methods, whether defined using the `def` keyword or via a `lambda` assignment.
+    if checker.semantic().current_scope().kind.is_class()
+        && (target.is_function_def()
+            || checker
+                .semantic()
+                .current_statements()
+                .any(|stmt| matches!(stmt, Stmt::AnnAssign(_) | Stmt::Assign(_))))
+    {
+        return;
     }
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/refurb/rules/reimplemented_operator.rs:104]: A comment explaining why we're testing for an assignment might be helpful. 

I wonder if we could avoid the false positive by testing if there's a parent expression. If that's the case, then the operator can't be the assignment's value?

**Review by MichaReiser — APPROVED** [review]
Thank you

File: crates/ruff_linter/src/rules/refurb/rules/reimplemented_operator.rs (hunk 2 above)
Comment (AlexWaygood) [reply crates/ruff_linter/src/rules/refurb/rules/reimplemented_operator.rs:104]: > I wonder if we could avoid the false positive by testing if there's a parent expression. If that's the case, then the operator can't be the assignment's value?

I don't think that's the case -- a lot of functions take an input function, do something with the function (monkey-patch an attribute onto the function, or store the function in a global registry somewhere, etc.), then return the same function. That's a very common pattern for decorators, for example:
- https://github.com/python/cpython/blob/3a77980002845c22e5b294ca47a12d62bf5baf53/Lib/typing.py#L2706-L2739
- https://github.com/python/cpython/blob/3a77980002845c22e5b294ca47a12d62bf5baf53/Lib/typing.py#L3738-L3770
- https://github.com/python/cpython/blob/3a77980002845c22e5b294ca47a12d62bf5baf53/Lib/typing.py#L2582-L2615

So all of these are still valid method definitions, and it would be a false positive if we flagged them with FURB118:

```py
from typing import final, override, no_type_check

class Foo:
    a = final(lambda self, other: self == other)
    b = override(lambda self, other: self == other)
    c = no_type_check(lambda self, other: self == other)
    d = final(override(no_type_check(lambda self, other: self == other)))
```

I'll add more tests involving constructs like these

Comment (AlexWaygood) [reply crates/ruff_linter/src/rules/refurb/rules/reimplemented_operator.rs:104]: One heuristic that might work would be if we still emitted diagnostics for lambdas in `key=` arguments, since lambdas are very often used as `key` functions and it's very likely that the lambda will be thrown away if it's passed as a `key` function. That would avoid the false negative on the `zerver` codebase.

Complex heuristics like that make the rule harder to understand for users, though, so there's a tradeoff there. I think I'd prefer to avoid it for now.

Comment (MichaReiser) [reply crates/ruff_linter/src/rules/refurb/rules/reimplemented_operator.rs:104]: Oh, okay, that's indeed complicated. I'm fine keeping it as is.

File: crates/ruff_linter/src/checkers/ast/analyze/expression.rs (hunk 1 above)
Comment (AlexWaygood) [reply crates/ruff_linter/src/checkers/ast/analyze/expression.rs:1657]: it took _me_ a little while to figure out why the semantic model didn't think lambdas inside class scopes were inside class scopes 😅

File: crates/ruff_linter/resources/test/fixtures/refurb/FURB118.py [hunk 3]
```diff
@@ -93,3 +93,30 @@ def add(x, y):
...
+    def x(self, other):
+        return self == other
+
+class Bar:
+    y = lambda self, other: self == other
+
+from typing import Callable
+class Baz:
+    z: Callable = lambda self, other: self == other
+
```
[the remark this answers is not in the document]
Comment (AlexWaygood) [reply crates/ruff_linter/resources/test/fixtures/refurb/FURB118.py:109]: done
