### PR TITLE
Avoid infinite loop between `I002` and `PYI025` 

### LINKED ISSUE #20891: [Infinite loop] F401, I002, and PYI025
### Summary

Ruff fails to converge when [`unused-import` (F401)](https://docs.astral.sh/ruff/rules/unused-import/), [`missing-required-import` (I002)](https://docs.astral.sh/ruff/rules/missing-required-import/), and [`unaliased-collections-abc-set-import` (PYI025)](https://docs.astral.sh/ruff/rules/unaliased-collections-abc-set-import/) are selected and `from collections.abc import Set` is a required import.
```console
$ echo 1 | ruff --isolated check --select F401,I002,PYI025 --config 'lint.isort.required-imports = ["from collections.abc import Set"]' - --unsafe-fixes --diff

error: Failed to converge after 100 iterations.

This indicates a bug in Ruff. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BInfinite%20loop%5D

...quoting the contents of `-`, the rule codes PYI025, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

@@ -1 +1,2 @@
+from collections.abc import Set
 1

Would fix 100 errors.
```

### Version

ruff 0.14.0 (beea8cdfe 2025-10-07)

### PR DESCRIPTION
**Pull request by kar-ganap**
## Summary

Fixes #20891.

When `lint.isort.required-imports` includes `from collections.abc import Set` (unaliased) and PYI025 is enabled, the two rules conflict: I002 inserts the unaliased import, while PYI025 demands it be aliased as `AbstractSet`. This causes an infinite autofix loop ("Failed to converge after 100 iterations").

Rather than patching the import-insertion logic at the rule level, this PR rejects the contradictory configuration at startup in `Configuration::into_settings()`, following the existing pattern established by `conflicting_import_settings()`. The error message explains the conflict and suggests two resolutions: alias the required import as `AbstractSet`, or disable PYI025.

### Prior art

PR #21115 took a different approach (modifying `add_required_imports.rs` and `imports.rs` to relax alias matching). As noted in review, the better fix is to "reject this configuration entirely at an earlier stage" since it doesn't make sense to simultaneously require an unaliased import and forbid it. This PR implements that suggestion directly.

## Test plan

- 3 unit tests: conflicting config → error, aliased as `AbstractSet` → ok, PYI025 not enabled → ok
- Reproduction case: `ruff check --config ruff.toml --unsafe-fixes --fix` now emits a clear configuration error instead of entering the infinite loop
- `cargo test -p ruff_workspace` — all 26 tests pass

### CODE REVIEW

**Comment by kar-ganap** [comment]
Gentle ping — this has been open since Feb 16 with clean CI and zero ecosystem impact. The approach follows the pattern suggested in #20891 (reject conflicting configuration at startup rather than working around it at the rule level). Would appreciate a review when someone has a chance.

File: crates/ruff_workspace/src/configuration.rs [hunk 1]
```diff
@@ -2181,4 +2216,60 @@ mod tests {
 
         Ok(())
     }
+
+    mod pyi025_conflict {
```
Comment (ntBre) [inline crates/ruff_workspace/src/configuration.rs]: Let's just add CLI tests like these:

https://github.com/astral-sh/ruff/blob/7778f653833ead6a54df1f51fb3479b35385eae4/crates/ruff/tests/cli/lint.rs#L2842-L2872

That will also get us snapshots to verify the full contents of the error message.

Comment (kar-ganap) [reply crates/ruff_workspace/src/configuration.rs]: Done — replaced the unit tests with CLI snapshot tests in `crates/ruff/tests/cli/lint.rs`, following the pattern from the existing `flake8_import_convention_unused_aliased_import` tests. Three tests:

1. `required_import_set_conflicts_with_pyi025` — unaliased `Set` + PYI025 → exit code 2 with error message
2. `required_import_set_aliased_as_abstract_set_no_conflict` — aliased as `AbstractSet` → no config error
3. `required_import_set_without_pyi025_no_conflict` — PYI025 not selected → no config error
