### PR TITLE
[flake8_bugbear] fix: improve docs for `no_explicit_stacklevel`

### LINKED ISSUE #22395: no-explicit-stacklevel (B028) should allow no stacklevel when skip_file_prefixes is provided
### Summary

According to the [python documentation](https://docs.python.org/3/library/warnings.html#warnings.warn)

> The `skip_file_prefixes` keyword argument can be used to indicate which stack frames are ignored when counting stack levels. [...] When prefixes are supplied, `stacklevel` is implicitly overridden to be `max(2, stacklevel)`.
> [...]
> Changed in version 3.12: Added skip_file_prefixes.

If `skip_file_prefixes` is provided, then the stacklevel is already set to at least 2, and the user has already explicitly skipped certain stack frames by prefix. The resulting warning will already give the caller more context about the warning since it will output a stack frame higher up than the one the warning was issued from, most likely outside of the issuing package (i.e. the caller's actual call).

Therefore I believe [the B028 rule](https://docs.astral.sh/ruff/rules/no-explicit-stacklevel/) should be updated to allow either of the two parameters instead of only `stacklevel`.

### PR DESCRIPTION
**Pull request by caiquejjx**
## Summary
Closes #22395

### CODE REVIEW

File: crates/ruff_linter/src/rules/flake8_bugbear/rules/no_explicit_stacklevel.rs [hunk 1]
```diff
@@ -16,7 +16,8 @@ use crate::{checkers::ast::Checker, fix::edits::add_argument};
 /// from higher up the stack.
 ///
 /// It's recommended to use a `stacklevel` of 2 or higher, to give the caller
-/// more context about the warning.
+/// more context about the warning, or to set the prefixes of the files
+/// which stack frames should be ignored when counting stack levels.
```
Comment (dylwil3) [inline crates/ruff_linter/src/rules/flake8_bugbear/rules/no_explicit_stacklevel.rs]: The option to use `skip_file_prefixes` is only available for Python versions 3.12 and higher. So maybe more like:

```
/// more context about the warning. 
/// 
/// In Python 3.12 and higher, one may also use `skip_file_prefixes` to specify
/// which file prefixes are ignored when counting the stack level. This implicitly overrides the `stacklevel` to be
/// at least 2, according to the [Python documentation].
```

and then add a link to https://docs.python.org/3/library/warnings.html#warnings.warn at the bottom.

File: crates/ruff_linter/src/rules/flake8_bugbear/rules/no_explicit_stacklevel.rs [hunk 2]
```diff
@@ -47,11 +48,12 @@ pub(crate) struct NoExplicitStacklevel;
 impl AlwaysFixableViolation for NoExplicitStacklevel {
     #[derive_message_formats]
     fn message(&self) -> String {
-        "No explicit `stacklevel` keyword argument found".to_string()
+        "No explicit `stacklevel` and `skip_file_prefixes` keyword argument found".to_string()
     }
 
     fn fix_title(&self) -> String {
-        "Set `stacklevel=2`".to_string()
+        "Set `stacklevel=2` or add the desired prefixes to be ignored to `skip_file_prefixes`"
```
Comment (dylwil3) [inline crates/ruff_linter/src/rules/flake8_bugbear/rules/no_explicit_stacklevel.rs]: I think we can just leave this fix title. It's still the case that we want the stacklevel to be at least 2, and it just happens to be the case that there's another way to achieve that. This also means we don't have to give a different message depending on the Python version.

File: crates/ruff_linter/src/rules/flake8_bugbear/rules/no_explicit_stacklevel.rs [hunk 3]
```diff
@@ -47,11 +48,12 @@ pub(crate) struct NoExplicitStacklevel;
 impl AlwaysFixableViolation for NoExplicitStacklevel {
     #[derive_message_formats]
     fn message(&self) -> String {
-        "No explicit `stacklevel` keyword argument found".to_string()
+        "No explicit `stacklevel` and `skip_file_prefixes` keyword argument found".to_string()
```
Comment (dylwil3) [inline crates/ruff_linter/src/rules/flake8_bugbear/rules/no_explicit_stacklevel.rs]: I don't think we need to mention `skip_file_prefixes` here, especially because it is version-dependent. (I think it is also sort of an "accidental" solution to the problem being linted for here.)

```suggestion
        "No explicit `stacklevel` provided".to_string()
```

File: crates/ruff_linter/src/rules/flake8_bugbear/rules/no_explicit_stacklevel.rs (hunk 1 above)
Comment (caiquejjx) [reply crates/ruff_linter/src/rules/flake8_bugbear/rules/no_explicit_stacklevel.rs]: ohh mb, i forgot this is only for python 3.12 and above.
Applied those changes and there is a link to the docs already so I didn't need to add it

File: crates/ruff_linter/src/rules/flake8_bugbear/rules/no_explicit_stacklevel.rs [hunk 4]
```diff
@@ -18,6 +18,10 @@ use crate::{checkers::ast::Checker, fix::edits::add_argument};
 /// It's recommended to use a `stacklevel` of 2 or higher, to give the caller
 /// more context about the warning.
 ///
+/// In Python 3.12 and higher, one may also use `skip_file_prefixes` to specify
+/// which file prefixes are ignored when counting the stack level. This implicitly overrides the `stacklevel` to be
+/// at least 2, according to the [Python documentation].
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/flake8_bugbear/rules/no_explicit_stacklevel.rs:23]: Does this link work? I don't think it will match up with the one below in the `## References` section, but I'd have to test the docs locally to be sure.

Comment (caiquejjx) [reply crates/ruff_linter/src/rules/flake8_bugbear/rules/no_explicit_stacklevel.rs:23]: You're right! I added now a reusable doc link that serves for both docs references nicely:

https://github.com/user-attachments/assets/2b949f00-2852-4d31-b323-13953dfa7868

**Review by dylwil3 — APPROVED** [review]
Thank you!
