### PR TITLE
[`flake8-return`] Fix `RET504` autofix generating a syntax error

### LINKED ISSUE #18411: RET504 fix uses the equals sign from a comment
### Summary

The fix for [`unnecessary-assign` (RET504)](https://docs.astral.sh/ruff/rules/unnecessary-assign/) assumes that the first equals sign in the assignment statement is the one that does the assignment. However, if the first equals sign is in a comment, the fix can fail because of a syntax error. The fix should seek the first equals sign token, not the first equals sign character.
```console
$ cat >ret504.py <<'# EOF'
def f():
    (#=
    x) = 1
    return x
# EOF

$ ruff --isolated check ret504.py --select RET504 --unsafe-fixes --diff 2>&1 | grep error:
error: Fix introduced a syntax error. Reverting all changes.
```

### Version

ruff 0.11.12 (aee3af0f7 2025-05-29)

### PR DESCRIPTION
**Pull request by LaBatata101**
## Summary

Fixes #18411

## Test Plan

Add regression test.

### CODE REVIEW

File: crates/ruff_linter/src/rules/flake8_return/rules/function.rs [hunk 1]
```diff
@@ -615,33 +613,11 @@ fn unnecessary_assign(checker: &Checker, stack: &Stack) {
...
                 // Replace from the start of the assignment statement to the end of the equals
                 // sign.
-                TextRange::new(
-                    assign.start(),
-                    assign
-                        .range()
-                        .start()
-                        .add(TextSize::try_from(after_equals)?),
-                ),
+                TextRange::new(assign.start(), assign.value.start()),
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_return/rules/function.rs]: This now produces a syntax error for:

```py
def f():
    x = (1
              )
    return x
```

**Review by MichaReiser — CHANGES_REQUESTED** [review]
This can now result in a different syntax error

File: crates/ruff_linter/src/rules/flake8_return/rules/function.rs [hunk 2]
```diff
@@ -614,17 +613,17 @@ fn unnecessary_assign(checker: &Checker, stack: &Stack) {
...
 
-            // Replace the `x = 1` statement with `return 1`.
-            let content = checker.locator().slice(assign);
-            let equals_index = content
-                .find('=')
-                .ok_or(anyhow::anyhow!("expected '=' in assignment statement"))?;
-            let after_equals = equals_index + 1;
+            let eq_token = checker
+                .tokens()
+                .iter()
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_return/rules/function.rs]: Iterating over all tokens is unnecessarily slow. Especially given that you know exactly what token you're looking for. You can use `checker.tokens().in_range(assign.range()`  or `after(assign.start)` instead

File: crates/ruff_linter/src/rules/flake8_return/rules/function.rs [hunk 3]
```diff
@@ -614,17 +613,17 @@ fn unnecessary_assign(checker: &Checker, stack: &Stack) {
...
+                .find(|token| token.kind() == TokenKind::Equal)
+                .unwrap();
 
+            let content = checker.source();
+            // Replace the `x = 1` statement with `return 1`.
             let replace_assign = Edit::range_replacement(
-                // If necessary, add whitespace after the `return` keyword.
-                // Ex) Convert `x=y` to `return y` (instead of `returny`).
-                if content[after_equals..]
+                if content[eq_token.range().end().to_usize()..]
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_return/rules/function.rs]:
```suggestion
                if content[eq_token.end().to_usize()..]
```

File: crates/ruff_linter/src/rules/flake8_return/rules/function.rs (hunk 2 above)
Comment (MichaReiser) [reply crates/ruff_linter/src/rules/flake8_return/rules/function.rs]: I think the safest here is to use `before` and take all tokens up to the start of the assignment value. Then use `rfind` to find the last equal sign
