### PR TITLE
[ty] Fix receiver coloring for aliased decorators

### LINKED ISSUE #3358: Semantic tokens: Misclassifies first parameter when `staticmethod` is aliased
### Summary

```py
sm = staticmethod

class C:
    @sm
    def f(x): 
        ...

    @staticmethod
    def g(x): 
        ...
```

[Playground](https://play.ty.dev/9853e858-4e10-493d-98a2-3add0835f610)

ty misclassifies `x` in `f(x)` as `selfParameter`, when it should be `parameter`. It correctly classifies `x` as `parameter` in `g(x)`. I'm not sure why the aliasing is an issue here.

### Version

_No response_

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

We already expose `is_classmethod`, etc., on function type, and those methods already support aliasing, so the LSP just uses those directly now.

Closes https://github.com/astral-sh/ty/issues/3358.

### CODE REVIEW

File: crates/ty_python_semantic/src/types/ide_support.rs [hunk 1]
```diff
@@ -31,6 +31,38 @@ use resolve_definition::{find_symbol_in_scope, resolve_definition};
...
+/// The implicit receiver kind for a method-like function.
+#[derive(Debug, Clone, Copy, PartialEq, Eq)]
+pub enum MethodReceiverKind {
+    /// The function has an implicit class receiver, conventionally named `cls`.
+    Cls,
+    /// The function has no implicit receiver, as with a static method.
+    None,
+    /// The function has an implicit instance receiver, conventionally named `self`.
+    Self_,
+}
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/ide_support.rs]: this feels like it does basically the same thing as https://github.com/astral-sh/ruff/blob/398262cb8f6e906174fba43540b3fde132e6014d/crates/ty_python_semantic/src/types/class.rs#L2114-L2140 -- could we just make that enum `pub` and use it from this crate?

Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/ide_support.rs]: Mine is nicer, it has docs!

**Review by AlexWaygood — APPROVED** [review]
I think we can simplify even more:

```diff
diff --git a/crates/ty_ide/src/semantic_tokens.rs b/crates/ty_ide/src/semantic_tokens.rs
index 15a02fd6d7..b3c2716c6d 100644
--- a/crates/ty_ide/src/semantic_tokens.rs
+++ b/crates/ty_ide/src/semantic_tokens.rs
@@ -547,14 +547,11 @@ impl<'db> SemanticTokenVisitor<'db> {
         if is_first && self.in_class_scope {
             let method_decorator = func
                 .inferred_type(self.model)
-                .and_then(|ty| match ty {
-                    Type::FunctionLiteral(function_ty) => Some(function_ty),
-                    _ => None,
-                })
+                .and_then(Type::as_function_literal)
                 .and_then(|function_ty| {
-                    MethodDecorator::try_from_fn_type(self.model.db(), function_ty).ok()
+                    MethodDecorator::try_from_fn_type(self.model.db(), function_ty)
                 })
-                .unwrap_or(MethodDecorator::None);
+                .unwrap_or_default();
 
             match method_decorator {
                 MethodDecorator::StaticMethod => SemanticTokenType::Parameter,
diff --git a/crates/ty_python_semantic/src/types.rs b/crates/ty_python_semantic/src/types.rs
index 41bf4d8dd3..6acf3ab57c 100644
--- a/crates/ty_python_semantic/src/types.rs
+++ b/crates/ty_python_semantic/src/types.rs
@@ -1535,7 +1535,7 @@ impl<'db> Type<'db> {
         }
     }
 
-    pub(crate) const fn as_function_literal(self) -> Option<FunctionType<'db>> {
+    pub const fn as_function_literal(self) -> Option<FunctionType<'db>> {
         match self {
             Type::FunctionLiteral(function_type) => Some(function_type),
             _ => None,
diff --git a/crates/ty_python_semantic/src/types/class.rs b/crates/ty_python_semantic/src/types/class.rs
index b4d83c3078..77f73a7b59 100644
--- a/crates/ty_python_semantic/src/types/class.rs
+++ b/crates/ty_python_semantic/src/types/class.rs
@@ -2112,9 +2112,10 @@ pub(super) struct AbstractMethod<'db> {
 }
 
 /// The decorator category for a method-like function.
-#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
+#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
 pub enum MethodDecorator {
     /// An instance method with an implicit instance receiver, conventionally named `self`.
+    #[default]
     None,
     /// A classmethod with an implicit class receiver, conventionally named `cls`.
     ClassMethod,
@@ -2124,12 +2125,12 @@ pub enum MethodDecorator {
 
 impl MethodDecorator {
     /// Returns the decorator category for a function type.
-    pub fn try_from_fn_type(db: &dyn Db, fn_type: FunctionType) -> Result<Self, ()> {
+    pub fn try_from_fn_type(db: &dyn Db, fn_type: FunctionType) -> Option<Self> {
         match (fn_type.is_classmethod(db), fn_type.is_staticmethod(db)) {
-            (true, true) => Err(()), // A method can't be static and class method at the same time.
-            (true, false) => Ok(Self::ClassMethod),
-            (false, true) => Ok(Self::StaticMethod),
-            (false, false) => Ok(Self::None),
+            (true, true) => None, // A method can't be static and class method at the same time.
+            (true, false) => Some(Self::ClassMethod),
+            (false, true) => Some(Self::StaticMethod),
+            (false, false) => Some(Self::None),
         }
     }
 
diff --git a/crates/ty_python_semantic/src/types/diagnostic.rs b/crates/ty_python_semantic/src/types/diagnostic.rs
index 9f92b704e9..827b6b7d5e 100644
--- a/crates/ty_python_semantic/src/types/diagnostic.rs
+++ b/crates/ty_python_semantic/src/types/diagnostic.rs
@@ -5744,9 +5744,10 @@ pub(super) fn report_invalid_method_override<'db>(
             ty: Type::FunctionLiteral(superclass_function),
             ..
         }) = class_member(superclass)
-        && let Ok(superclass_function_kind) =
+        && let Some(superclass_function_kind) =
             MethodDecorator::try_from_fn_type(db, superclass_function)
-        && let Ok(subclass_function_kind) = MethodDecorator::try_from_fn_type(db, subclass_function)
+        && let Some(subclass_function_kind) =
+            MethodDecorator::try_from_fn_type(db, subclass_function)
         && superclass_function_kind != subclass_function_kind
     {
         diagnostic.info(format_args!(
diff --git a/crates/ty_python_semantic/src/types/infer/builder.rs b/crates/ty_python_semantic/src/types/infer/builder.rs
index 772206c939..a117309a25 100644
--- a/crates/ty_python_semantic/src/types/infer/builder.rs
+++ b/crates/ty_python_semantic/src/types/infer/builder.rs
@@ -8179,15 +8179,15 @@ impl<'db, 'ast> TypeInferenceBuilder<'db, 'ast> {
         };
 
         let attribute_exists = match MethodDecorator::try_from_fn_type(self.db(), function_type) {
-            Ok(MethodDecorator::ClassMethod) => !Type::instance(self.db(), class)
+            Some(MethodDecorator::ClassMethod) => !Type::instance(self.db(), class)
                 .class_member(self.db(), id.clone())
                 .place
                 .is_undefined(),
-            Ok(MethodDecorator::None) => !Type::instance(self.db(), class)
+            Some(MethodDecorator::None) => !Type::instance(self.db(), class)
                 .member(self.db(), id)
                 .place
                 .is_undefined(),
-            Ok(MethodDecorator::StaticMethod) | Err(()) => false,
+            Some(MethodDecorator::StaticMethod) | None => false,
         };
 
         if attribute_exists {
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 2]
```diff
@@ -2111,25 +2111,38 @@ pub(super) struct AbstractMethod<'db> {
...
     ClassMethod,
+    /// A staticmethod with no implicit receiver.
     StaticMethod,
 }
 
+#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
+pub enum MethodDecoratorError {
+    /// A method can't be static and a class method at the same time.
+    ConflictingDecorators,
+}
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]: I'd just make the method return `Option<Self>`, as per the diff I posted. A single-variant enum for the error seems silly

Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/class.rs]: Mmm, I'm mixed on this, but not a big deal.

Comment (AlexWaygood) [reply crates/ty_python_semantic/src/types/class.rs]: oh because of `Some(Self::None)`? That... is a bit weird, I'll grant you 😆 We could just rename the enum to `MethodKind` and the variant to `InstanceMethod`, though

File: crates/ty_python_semantic/src/types/class.rs [hunk 3]
```diff
@@ -2111,25 +2111,30 @@ pub(super) struct AbstractMethod<'db> {
...
 impl MethodDecorator {
-    pub(crate) fn try_from_fn_type(db: &dyn Db, fn_type: FunctionType) -> Result<Self, ()> {
+    /// Returns the decorator category for a function type.
+    pub fn try_from_fn_type(db: &dyn Db, fn_type: FunctionType) -> Option<Self> {
         match (fn_type.is_classmethod(db), fn_type.is_staticmethod(db)) {
-            (true, true) => Err(()), // A method can't be static and class method at the same time.
-            (true, false) => Ok(Self::ClassMethod),
-            (false, true) => Ok(Self::StaticMethod),
-            (false, false) => Ok(Self::None),
+            (true, true) => None,
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
            (true, true) => None,  // A method can't be static and class method at the same time.
```
