### PR TITLE
[flake8-bugbear] Clarify RUF071 fix safety for non-path string comparisons

### LINKED ISSUE #24028: `os-path-commonprefix` (RUF071): update documentation
RUF071 recommends using `os.path.commonpath` over `os.path.commonprefix`. However, that is not always desirable, and sometimes even incorrect. The documentation should cover the differences in semantics as well as cases where RUF071 should be ignored.

> This rule's recommendation is confusing for those using `os.path.commonprefix` with non-path strings (which I think is perfectly legitimate):
> ```
>>> commonprefix(["123", "124"])
> '12'
>>> commonpath(["123", "124"])
> ''
> ```
> 
> I am not sure of the status of a `string.commonprefix` method in Python 3.15, but I think ruff's wording should be more carefully consider use cases such the one above. 

 _Originally posted by @bersbersbers in [#22981](https://github.com/astral-sh/ruff/issues/22981#issuecomment-4066272148)_

### PR DESCRIPTION
**Pull request by chinar-amrutkar**
## Summary

Fixes #24028

Added documentation explaining that `os.path.commonprefix` is valid for non-path string comparisons (e.g., finding a common prefix among version numbers or identifiers), and that `os.path.commonpath` cannot be used as a drop-in replacement in those cases since it raises `ValueError` on non-path strings.

Added a "Fix safety" section explaining why the fix is marked as unsafe, with concrete examples showing the semantic difference between `commonprefix` (character-by-character) and `commonpath` (path-component-level).

## Test Plan

Existing tests pass. Documentation change only (rule definition in `os_path_commonprefix.rs`).

### CODE REVIEW

File: crates/ruff_linter/src/rules/ruff/rules/os_path_commonprefix.rs [hunk 1]
```diff
@@ -35,6 +39,32 @@ use crate::{Edit, Fix, FixAvailability, Violation};
...
+/// option.
+///
+/// For example:
+///
+/// ```python
+/// import os
+///
+/// # commonprefix works on non-path strings
+/// os.path.commonprefix(["12345", "12378"])  # "123"
+/// os.path.commonpath(["12345", "12378"])    # raises ValueError
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/ruff/rules/os_path_commonprefix.rs]: This doesn't raise a `ValueError`, it just returns the empty string:

```pycon
>>> import os
>>> os.path.commonprefix(["12345", "12378"])
'123'
>>> os.path.commonpath(["12345", "12378"])
''
>>>
```

File: crates/ruff_linter/src/rules/ruff/rules/os_path_commonprefix.rs [hunk 2]
```diff
@@ -35,6 +39,32 @@ use crate::{Edit, Fix, FixAvailability, Violation};
...
+///
+/// - `commonprefix` performs a character-by-character string comparison
+///   and returns the longest common string prefix.
+/// - `commonpath` compares path components and returns the longest common
+///   path prefix.
+///
+/// If you are intentionally using `commonprefix` for non-path string
+/// comparisons (e.g., finding a common prefix among arbitrary strings
+/// like version numbers or identifiers), ignore this rule using
+/// `# noqa: RUF071` or the [`lint.ruff.per-file-ignores`] configuration
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/ruff/rules/os_path_commonprefix.rs]: It might make sense to link to our suppression docs here instead of calling out these two specific mechanisms: https://docs.astral.sh/ruff/linter/#error-suppression.

File: crates/ruff_linter/src/rules/ruff/rules/os_path_commonprefix.rs [hunk 3]
```diff
@@ -17,6 +17,10 @@ use crate::{Edit, Fix, FixAvailability, Violation};
 ///
 /// `os.path.commonpath` correctly compares path components.
 ///
+/// Note that `os.path.commonprefix` is valid for non-path string
+/// comparisons (e.g., finding a common prefix among version numbers
+/// or identifiers). In such cases, this rule should be ignored.
+///
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/ruff/rules/os_path_commonprefix.rs]: I think I would revert this piece as it seems redundant with part of the new fix safety docs down below.

**Comment by chinar-amrutkar** [comment]
@ntBre Thanks for the review! I have addressed all three points:

1. Fixed the ValueError claim - commonpath returns "" not raises. 
2. Replaced the specific suppression mentions with a link to the general suppression docs.
3. Removed the redundant non-path note from the "Why is this bad?" section since the "Fix safety" section already covers it.
