### PR TITLE
[ty] Treat `[*xs]` as an irrefutable pattern

### LINKED ISSUE #3304: Support `[*xs]` as a wildcard pattern when matching on `Sequence[…]`
### Summary

Hello, I ran into this (I did quickly check the issues but sorry if this a duplicate):

```py
def main_1(paths: Sequence[str]) -> None:
    match paths:
        case []:
            value = 0
        case [_first]:
            value = 1
        case [_first, _second]:
            value = 2
        case [*_paths]:
            raise ValueError

    print(value)  # error[possibly-unresolved-reference] from ty. OK for mypy.


def main_2(paths: Sequence[str]) -> None:
    match paths:
        case []:
            value = 0
        case [first]:
            value = 1
        case [_first, _second]:
            value = 2
        case [_first, _second, *_paths]:
            raise ValueError

    print(value)  # error[possibly-unresolved-reference] from ty. OK for mypy.
```
Here all cases are clearly handled, so it would be nice to detect that the variable will always be assigned. Mypy does, apparently.

~~What's kind of strange is that the following works for ty, but not for mypy:~~
```py
def main_3(paths: Sequence[str]) -> int:  # mypy error: Missing return statement. OK for ty
    match paths:
        case []:
            return 0
        case [first]:
            return 1
        case [first, second]:
            return 2
        case [first, second, *_paths]:
            raise ValueError
```

### Version

ty 0.0.32 (4d1e1fc57 2026-04-20)

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Closes https://github.com/astral-sh/ty/issues/3304.

### CODE REVIEW

File: crates/ty_python_core/src/builder.rs [hunk 1]
```diff
@@ -1352,6 +1352,17 @@ impl<'db, 'ast> SemanticIndexBuilder<'db, 'ast> {
                     ClassPatternKind::Refutable
                 })
             }
+            ast::Pattern::MatchSequence(pattern) => {
+                // `case [*rest]` matches every sequence, while all other sequence patterns
+                // are refutable because they impose a minimum and/or exact length.
+                PatternPredicateKind::Sequence(
+                    if matches!(pattern.patterns.as_slice(), [ast::Pattern::MatchStar(_)]) {
+                        ClassPatternKind::Irrefutable
```
Comment (carljm) [inline crates/ty_python_core/src/builder.rs:1360]: I had to stop and think about the meaning of `ClassPatternKind::Irrefutable`, because this pattern is only irrefutable under the condition that the subject is a subtype of `Sequence[object] & ~str & ~bytes & ~bytearray`, and that's totally implicit here; we just have to get it right in `narrow.rs`. That seems a bit error-prone, though it's fine as long as we get it right. And the same is already true for at least `MatchMapping` above, so this PR doesn't change that pattern.

File: crates/ty_python_semantic/resources/mdtest/conditional/match.md [hunk 2]
```diff
@@ -33,6 +33,49 @@ def _(target: int):
...
+        case []:
+            value = 0
+        case [_first]:
+            value = 1
+        case [_first, _second]:
+            value = 2
+        case [*_paths]:
+            raise ValueError
+
+    print(value)
```
Comment (carljm) [inline crates/ty_python_semantic/resources/mdtest/conditional/match.md]: I think these tests would have the same coverage but be more informative if every branch were terminal and we `reveal_type(paths)` here at the end.

File: crates/ty_python_semantic/resources/mdtest/conditional/match.md [hunk 3]
```diff
@@ -33,6 +33,49 @@ def _(target: int):
...
+from collections.abc import Sequence
+
+def sequence_star_pattern_is_exhaustive(paths: list[int]) -> None:
+    match paths:
+        case []:
+            value = 0
+        case [_first]:
+            value = 1
+        case [_first, _second]:
+            value = 2
```
Comment (carljm) [inline crates/ty_python_semantic/resources/mdtest/conditional/match.md]: Does the existence of these cases contribute anything to the test? IMO it just adds confusion about how we're detecting exhaustiveness. This test is all about `[*xs]`, let's make that clearer?

File: crates/ty_python_semantic/resources/mdtest/conditional/match.md [hunk 4]
```diff
@@ -33,6 +33,49 @@ def _(target: int):
...
+        case [*_paths]:
+            raise ValueError
+
+    print(value)  # error: [possibly-unresolved-reference]
```
Comment (carljm) [inline crates/ty_python_semantic/resources/mdtest/conditional/match.md]: If we did a `reveal_type(paths)` here as recommended above (with all match branches terminal), we could also add a comment on _why_ we see the strange complex type that we do (i.e. discuss how `str` and `bytes` and `bytearray` are subtypes of `Sequence` but don't match sequence patterns). And a TODO about how some of these intersections (e.g. `bytes & Sequence[str]`, `bytearray & Sequence[str]`) ought to simplify to `Never` and disappear, if we fix https://github.com/astral-sh/ty/issues/3314

File: crates/ty_python_semantic/resources/mdtest/conditional/match.md [hunk 5]
```diff
@@ -33,6 +33,49 @@ def _(target: int):
...
+def sequence_prefix_star_pattern_is_not_catch_all(paths: Sequence[str]) -> None:
+    match paths:
+        case []:
+            value = 0
+        case [_first]:
+            value = 1
+        case [_first, _second, *_paths]:
+            raise ValueError
+
+    print(value)  # error: [possibly-unresolved-reference]
```
Comment (carljm) [inline crates/ty_python_semantic/resources/mdtest/conditional/match.md]: `reveal_type` here also would be more informative about what types we see as possibly leaking through. (In this case, the full `Sequence[str]` type.)

File: crates/ty_python_semantic/resources/mdtest/import/star.md [hunk 6]
```diff
@@ -243,7 +243,7 @@ print((
     L,
     M,  # error: [possibly-unresolved-reference]
     N,  # error: [possibly-unresolved-reference]
-    O,  # error: [possibly-unresolved-reference]
+    O,  # error: [unresolved-reference]
```
Comment (carljm) [inline crates/ty_python_semantic/resources/mdtest/import/star.md]: We are losing the point of this test, which is that we do see `O` as importable via the star import. Need to fix the match up in `exporter.py` so the `[O]` case is not shadowed by the `[*N]` case.

File: crates/ty_python_semantic/resources/mdtest/narrow/match.md [hunk 7]
```diff
@@ -151,6 +151,26 @@ def test_match_refutable(x: dict | int) -> None:
...
+
+```py
+from collections.abc import Sequence
+
+def test_match_star(x: Sequence[int] | int) -> None:
+    match x:
+        case [*rest]:
+            reveal_type(x)  # revealed: (Sequence[int] & ~str & ~bytes & ~bytearray) | (int & Sequence[object])
+        case _:
+            reveal_type(x)  # revealed: (int & ~Sequence[object]) | (Sequence[int] & str) | bytes | bytearray
```
Comment (carljm) [inline crates/ty_python_semantic/resources/mdtest/narrow/match.md:170]: I think a comment about why we see these types, and a TODO for https://github.com/astral-sh/ty/issues/3314, would both make sense here also.

**Review by carljm — APPROVED** [review]
Nice!
