### PR TITLE
Check `pyproject.toml` correctly when it is passed via stdin

### LINKED ISSUE #16950: `pyproject.toml` is ignored when passed via stdin
This works:

```shell
$ cat pyproject.toml
[project]
name = 1

$ ruff check --isolated --select RUF200 pyproject.toml
pyproject.toml:2:8: RUF200 Failed to parse pyproject.toml: invalid type: integer `1`, expected a string
  |
1 | [project]
2 | name = 1
  |        ^ RUF200
  |

Found 1 error.
```

This doesn't:

```shell
$ ruff check --isolated --select RUF200 --stdin-filename pyproject.toml -
[project]
name = 1
All checks passed!
```

These two commands should work similarly.

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
## Summary

Resolves #16950 and [a 1.5-year-old TODO comment](https://github.com/astral-sh/ruff/blame/8d16a5c8c98089b0d1be3e3fd68954be62dd2598/crates/ruff/src/diagnostics.rs#L380).

After this change, a `pyproject.toml` will be linted the same as any Python files would when passed via stdin.

## Test Plan

Integration tests.

### CODE REVIEW

File: crates/ruff/src/diagnostics.rs [hunk 1]
```diff
@@ -377,13 +376,28 @@ pub(crate) fn lint_stdin(
...
 ) -> Result<Diagnostics> {
-    // TODO(charlie): Support `pyproject.toml`.
     let source_type = match path.and_then(|path| settings.linter.extension.get(path)) {
         None => match path.map(SourceType::from).unwrap_or_default() {
             SourceType::Python(source_type) => source_type,
-            SourceType::Toml(_) => {
-                return Ok(Diagnostics::default());
+
+            SourceType::Toml(source_type) if source_type.is_pyproject() => {
+                let path = path.unwrap();
```
Comment (MichaReiser) [inline crates/ruff/src/diagnostics.rs:384]: We should only call `lint_pyproject_toml` if the user has any pyproject.toml related rule enabled, similar to 

https://github.com/astral-sh/ruff/blob/74f64d3f96d76fc252512acf30cf45b252be58f7/crates/ruff/src/diagnostics.rs#L229-L239

Could we share some of the logic between `lint_path` and `lint_stdin`

Comment (MichaReiser) [reply crates/ruff/src/diagnostics.rs:393]: I think there's definitely an opportunity to share more but I can see how it is out of the scope for this PR
