### PR TITLE
[red-knot] Add a build.rs file to `red_knot_python_semantic`, and document pitfalls of using `rstest` in combination with `mdtest`

### LINKED ISSUE #13732: [red-knot] `mdtest` doesn't spot a new Markdown test file has been added until you force a rebuild of the crate being tested
I just did the following:
- Wrote some new red-knot code in a new PR branch
- Added a new Markdown test for the code that I was sure was going to fail
- Ran `cargo test -p red_knot_python_semantic`, was mystified at the lack of failures
- After a little bit, figured out that the test wasn't being run at all
- As soon as I added a random newline to `red_knot_python_semantic`, it triggered a rebuild of the crate and the new Markdown test file was picked up by `mdtest`, as expected.

I think this has actually happened to me a few times over the last few days, but this is the first time I realised exactly what was going on...

### PR DESCRIPTION
**Pull request by AlexWaygood**
## Summary

Fixes #13732. `rstest` generates tests at build time rather than at runtime, so it doesn't necessarily notice new Markdown tests being added to a `resources` directory unless you add some mechanism to force a rebuild of the crate. The [`rstest` docs](https://docs.rs/rstest/0.23.0/rstest/attr.rstest.html#files-path-as-input-arguments) recommend using a `build.rs` script for this purpose; I've done so here for the `red_knot_python_semantic` crate, and added some docs to the `red_knot_test` README so that we don't forget to do so when adding `mdtest`-based tests to other red-knot crates.

## Test Plan

I locally tested by adding a new Markdown test file to `crates/red_knot_python_semantic/resources/mdtest` with some deliberate errors. I then ran `cargo test -p red_knot_python_semantic` (without having made any other changes to the crate that would have triggered a rebuild). The `build.rs` file successfully forced a rebuild, and the test correctly failed.

~~Here's a screenshot of how the `NOTE` block I've added to the README is rendered on GitHub:~~

<details>
<summary>Screenshot</summary>

image

</details>

~~Unfortunately it doesn't seem to be universal Markdown syntax, e.g. VSCode doesn't render the `NOTE` block in the same way.~~

(Edit: I abandoned the fancy Markdown because our linters hated it.)

### CODE REVIEW

**Comment by AlexWaygood** [comment]
> Here's a screenshot of how the `NOTE` block I've added to the README is rendered on GitHub:

Ugh, `mdformat` doesn't like this. I tried adding these plugins to `.pre-commit-config.yaml`:

```diff
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
index 710e128b2..92330acef 100644
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -29,6 +29,8 @@ repos:
           - mdformat-mkdocs
           - mdformat-admon
           - mdformat-footnote
+          - mdformat-gfm
+          - mdformat-gfm-alerts
         exclude: |
           (?x)^(
             docs/formatter/black\.md
```

but then mdformat fails to parse some other files (I think probably because mkdocs-flavoured Markdown and GitHub-flavoured Markdown are different, so `mdformat-mkdocs` and `mdformat-gfm` are pulling it in different directions?

```
Error: Could not format "/Users/alexw/dev/ruff/crates/red_knot/docs/tracing.md".

The formatted Markdown renders to different HTML than the input Markdown. This
is likely a bug in mdformat. Please create an issue report here, including the
input Markdown: https://github.com/executablebooks/mdformat/issues
```

I could use embedded HTML, but that seems over the top; I guess I'll just not be fancy.

File: crates/red_knot_python_semantic/build.rs [hunk 1]
```diff
@@ -0,0 +1,4 @@
+/// Rebuild the crate if a test file is added or removed from
+pub fn main() {
+    println!("cargo:rerun-if-changed=resources/mdtest/*.md");
```
Comment (sharkdp) [inline crates/red_knot_python_semantic/build.rs:3]: I ran into #13732 as well this morning, so I appreciate that we try to fix it. But it looks like doing this with a glob forces a recompilation *every time*, even if nothing has changed in the Markdown files(?).

When working on these tests, most of the time we're probably just editing Markdown files, not adding new ones. With this change, we make all of of those `cargo test`/`cargo test mdtest`/… calls much slower. We can probably workaround this locally by running the test executable directly (not via `cargo`). But that's another thing that developers would need to be taught :face_with_diagonal_mouth:

Comment (sharkdp) [reply crates/red_knot_python_semantic/build.rs]: > It looks like maybe we're not really meant to use globs here

Ah, yes. That was the problem. I can confirm that it works as intended now :+1: 

> I think the slowdown in having to rebuild the crate to run the tests is a _reasonable_ price to pay for avoiding the confusion from #13732

Agreed, #13732 should be fixed. And I don't have any other ideas on how to solve it... except for a hard-coded list of Markdown files somewhere, and that would be a big downside in terms of ergonomics.

**Review by sharkdp — APPROVED** [review]

**Comment by carljm** [comment]
Looks great, thank you!!
