### PR TITLE
[ty] Avoid panic from double inference with missing functional Enum names

### LINKED ISSUE #3272: Calling Enum with a single argument panics
### Summary

When type checking this program ty panics:

```
from enum import Enum
Enum("Color")
```
https://play.ty.dev/209c89fb-d5d3-4ddb-991b-5db5a3588ecc

While the program is not correct if you start typing in between the parenthesis to fill in the arguments ty will crash.

I'll try to send a fix for it tonight.
I found this with a fuzzer.

### Version

11a6493c9

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Given `Enum("Color")`, we inferred the first argument, then returned `None` later if `names_arg` was empty, which led us to double-infer the first argument.

Closes https://github.com/astral-sh/ty/issues/3272.

### CODE REVIEW

File: crates/ty_python_semantic/src/types/infer/builder/enum_call.rs [hunk 1]
```diff
@@ -392,8 +415,6 @@ impl<'db> TypeInferenceBuilder<'db, '_> {
             ));
         }
 
-        // Without `names`, this is a value-lookup call, not functional enum creation.
```
Comment (charliermarsh) [inline crates/ty_python_semantic/src/types/infer/builder/enum_call.rs:395]: This isn't really correct... Value lookup would be for an `Enum` subclass?

**Review by carljm — APPROVED** [review]

**Comment by carljm** [comment]
Oops, I approved this without waiting for Codex review to finish, and it caught another panic case introduced by this PR. With apologies, I'll just quote Codex (I have not verified this finding):

> When the call is written with a value= keyword and no names argument, name_arg is already kw.value, so this branch infers the same expression once via self.infer_expression(name_arg, ...) and then again in the for kw in keywords loop. That second inference trips store_expression_type's assert_eq!(previous, None) and crashes ty instead of emitting the new missing-argument diagnostic; for example, Enum(value="Color") now panics the checker.

**Comment by charliermarsh** [comment]
FML

**Comment by charliermarsh** [comment]
I got it :)
