### PR TITLE
[`ruff`] Add exception for `ctypes.Structure._fields_` (`RUF012`)

### LINKED ISSUE #22166: RUF012 warns for ctypes Structure._fields_
### Summary

The class variable `_fields_` on ctypes `Structure` objects, e.g.
```python
class mount_attr(ctypes.Structure):
    _fields_ = [
        ("attr_set", ctypes.c_uint64),
        ("attr_clr", ctypes.c_uint64),
        ("propagation", ctypes.c_uint64),
        ("userns_fd", ctypes.c_uint64),
    ]
```
will trigger RUF012, but [documentation says](https://docs.python.org/3/library/ctypes.html#ctypes.Structure._fields_)
> The _fields_ class variable can only be set once. Later assignments will raise an [AttributeError](https://docs.python.org/3/library/exceptions.html#AttributeError).

so an exception to this rule would be helpful.

### PR DESCRIPTION
**Pull request by caiquejjx**
Closes #22166 
## Summary
Adds an exception for `ctypes.Structure._fields_` to the rule RUF012 as it has it's own way of enforcing immutability:

> The fields class variable can only be set once. Later assignments will raise an [AttributeError](https://docs.python.org/3/library/exceptions.html#AttributeError).

### CODE REVIEW

**Comment by amyreese** [comment]
Can you add a test case to the snapshots demonstrating the expected passing case?

**Comment by caiquejjx** [comment]
@amyreese Done, thanks

File: crates/ruff_linter/src/rules/ruff/rules/mutable_class_default.rs [hunk 1]
```diff
@@ -140,6 +140,14 @@ pub(crate) fn mutable_class_default(checker: &Checker, class_def: &ast::StmtClas
                             .is_some_and(|name| class_var_targets.contains(&name.id))
                 }) && is_mutable_expr(value, checker.semantic())
                 {
+                    // The `_fields_` property of a `ctypes.Structure` base class has it's
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/ruff/rules/mutable_class_default.rs]:
```suggestion
                    // The `_fields_` property of a `ctypes.Structure` base class has its
```

**Review by ntBre — APPROVED** [review]
Thank you! This looks great.

I'm just waiting on the release today to finish to merge this.
