### PR TITLE
Attribute panics to the mdtests that cause them

### LINKED ISSUE #13899: [red-knot] mdtest doesn't tell you the path of the Markdown file if there's a panic
If there's a panic in an mdtest, mdtest tells you the name of the test that panicked, but not the path to the file that contains the test:

```
failures:

---- mdtest__call_callable_instance stdout ----
thread 'mdtest__call_callable_instance' panicked at crates/red_knot_python_semantic/src/types/infer.rs:861:18:
no entry found for key
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by dcreager**
This updates the mdtest harness to catch any panics that occur during type checking, and to display the panic message as an mdtest failure.  (We don't know which specific line causes the failure, so we attribute panics to the first line of the test case.)

Sample output (for an artificial panic):

```
---- mdtest__unary_integers stdout ----

integers.md - Unary Operations - Unary Addition

  crates/red_knot_python_semantic/resources/mdtest/unary/integers.md:6 panicked at crates/red_knot_python_semantic/src/types/infer.rs:3264:66:
  crates/red_knot_python_semantic/resources/mdtest/unary/integers.md:6 bonk

To rerun this specific test, set the environment variable: MDTEST_TEST_FILTER="integers.md - Unary Operations - Unary Addition"
MDTEST_TEST_FILTER="integers.md - Unary Operations - Unary Addition" cargo test -p red_knot_python_semantic --test mdtest -- mdtest__unary_integers

integers.md - Unary Operations - Unary Subtraction

  crates/red_knot_python_semantic/resources/mdtest/unary/integers.md:14 panicked at crates/red_knot_python_semantic/src/types/infer.rs:3265:66:
  crates/red_knot_python_semantic/resources/mdtest/unary/integers.md:14 foobar

To rerun this specific test, set the environment variable: MDTEST_TEST_FILTER="integers.md - Unary Operations - Unary Subtraction"
MDTEST_TEST_FILTER="integers.md - Unary Operations - Unary Subtraction" cargo test -p red_knot_python_semantic --test mdtest -- mdtest__unary_integers
```

Closes #13899

### CODE REVIEW

File: crates/ruff_db/src/panic.rs [hunk 1]
```diff
@@ -21,7 +21,7 @@ thread_local! {
 
 /// [`catch_unwind`](std::panic::catch_unwind) wrapper that sets a custom [`set_hook`](std::panic::set_hook)
 /// to extract the backtrace. The original panic-hook gets restored before returning.
-pub(crate) fn catch_unwind<F, R>(f: F) -> Result<R, PanicError>
+pub fn catch_unwind<F, R>(f: F) -> Result<R, PanicError>
```
Comment (dcreager) [inline crates/ruff_db/src/panic.rs:24]: All of the chatter in this crate is just to publicize this existing helper function.

File: crates/red_knot_test/src/lib.rs [hunk 2]
```diff
@@ -136,7 +137,25 @@ fn run_test(db: &mut db::Db, test: &parser::MarkdownTest) -> Result<(), Failures
...
+                Err(info) => {
+                    eprintln!("panic in test");
+                    let mut by_line = matcher::FailuresByLine::default();
+                    by_line.push(
+                        OneIndexed::from_zero_indexed(0),
+                        info.info
+                            .to_string()
+                            .split('\n')
+                            .map(String::from)
+                            .collect(),
```
Comment (dcreager) [inline crates/red_knot_test/src/lib.rs:151]: This does not include the full backtrace of the panic, since that seemed to be more verbose than we need at this point.  If we want it, we just change `info.info` to `info` here.

**Review by AlexWaygood — APPROVED** [review]
Nice, this looks great! :D

**Review by MichaReiser — APPROVED** [review]
Neat

**Comment by AlexWaygood** [comment]
Hmm, this PR unfortunately now seems to be suppressing some of the internal error messages from `red_knot_test`, for example this one here:

https://github.com/astral-sh/ruff/blob/b26448926a8c2f61befa17b8ffa1dd0ac3232c9c/crates/red_knot_test/src/lib.rs#L32-L37

On a PR branch I'm working on, I got this (not very informative!) test failure:

image

If I revert this commit on that PR branch, I get this instead, which is much more helpful:

image

**Comment by AlexWaygood** [comment]
I opened https://github.com/astral-sh/ruff/issues/15317 so we don't forget about this 👍
