### PR TITLE
[`flake8-bugbear`] Fix `mutable-contextvar-default (B039)` to resolve annotated function calls properly

### LINKED ISSUE #14525: B039 considers `frozenset` to be mutable
```
$ cat foo.py 
from contextvars import ContextVar

foo = ContextVar('foo', default=frozenset[str]())
$ ruff check --select B039 foo.py
foo.py:3:33: B039 Do not use mutable data structures for `ContextVar` defaults
  |
1 | from contextvars import ContextVar
2 | 
3 | foo = ContextVar('foo', default=frozenset[str]())
  |                                 ^^^^^^^^^^^^^^^^ B039
  |
  = help: Replace with `None`; initialize with `.set()``

Found 1 error.
$ ruff --version                 
ruff 0.8.0
```

### PR DESCRIPTION
**Pull request by harupy**
## Summary

Fix #14525

## Test Plan

New test cases

### CODE REVIEW

File: crates/ruff_linter/src/rules/flake8_bugbear/rules/mutable_contextvar_default.rs [hunk 1]
```diff
@@ -96,7 +97,7 @@ pub(crate) fn mutable_contextvar_default(checker: &mut Checker, call: &ast::Expr
                     && !is_immutable_func(func, checker.semantic(), &extend_immutable_calls)))
         && checker
             .semantic()
-            .resolve_qualified_name(&call.func)
+            .resolve_qualified_name(map_subscript(&call.func))
```
Comment (harupy) [inline crates/ruff_linter/src/rules/flake8_bugbear/rules/mutable_contextvar_default.rs:100]: It's unrelated to this PR, shoud we check if `call.func` first before checkking if `arguments` has a keyword `default`?

**Review by charliermarsh — APPROVED** [review]

**Comment by charliermarsh** [comment]
Thanks!
