### PR TITLE
[red-knot] resolve source/stubs over namespace packages

### LINKED ISSUE #12278: [red-knot] Module resolver has incorrect behaviour if a single-file module and potential namespace package coexist
The following test should pass, but fails:

```diff
diff --git a/crates/red_knot_module_resolver/src/resolver.rs b/crates/red_knot_module_resolver/src/resolver.rs
index 71b807871..5decee0c6 100644
--- a/crates/red_knot_module_resolver/src/resolver.rs
+++ b/crates/red_knot_module_resolver/src/resolver.rs
@@ -1140,4 +1140,21 @@ mod tests {
             system_path_to_file(&db, stdlib.join("functools.pyi"))
         );
     }
+
+    #[test]
+    fn single_file_takes_priority_over_namespace_package() {
+        const SRC: &[FileSpec] = &[("foo.py", "x = 1"), ("foo/bar.py", "x = 2")];
+
+        let TestCase { db, src, .. } = TestCaseBuilder::new().with_src_files(SRC).build();
+
+        let foo_module_name = ModuleName::new_static("foo").unwrap();
+        let foo_bar_module_name = ModuleName::new_static("foo.bar").unwrap();
+
+        // `foo.py` takes priority over the `foo` directory;
+        // `foo.bar` isn't recognised as a module:
+        let foo_module = resolve_module(&db, foo_module_name.clone()).unwrap();
+        let foo_path = src.join("foo.py");
+        assert_eq!(&foo_path, foo_module.file().path(&db));
+        assert_eq!(resolve_module(&db, foo_bar_module_name.clone()), None);
+    }
 }
```

At runtime, Python considers that a `foo` module exists and considers that a `foo.bar` module does not exist (it does not view the `foo` module as a package, as the `foo.py` file takes priority over the `foo` directory). The red-knot module resolver currently has the opposite understanding: it believes that there is no module `foo`, and that there _is_ a module `foo.bar`.

### PR DESCRIPTION
**Pull request by Slyces**
This PR tries to fix #12278. That issue doesn't have the tag `help-wanted`, so I'm not sure if I can contribute a fix

### Expected Behaviour

In python, a `module` can actually be 3 things:
- Regular file
- Package (directory with `__init__.py`)
- Namespace package (directory without `__init__.py`)

In the import logic, when resolving `foo.bar.baz`, we should have the following priority:
```
└─ foo
   └─ bar
      ├─ baz           <-- regular package over module
      │  └─ __init__.py
      └─ baz.py
```
**works**
```
└─ foo
   └─ bar
      ├─ baz.py        <-- module over namespace package
      └─ baz           <-- namespace package invisible (because of module)
         └─ ...
```
**doesn't work**

### Current Implementation

Currently, the code properly imports regular packages over modules, but when a namespace package is here, it makes a module with the same name invisible, which is the opposite of what we want.

We want to guarantee 3 things:
- Regular package has priority over module (covered in existing test)
- Module has priority over namespace package (new test)
- A namespace package is made invisible by a module of the same name (new test)

### Fixes

We have 2 core problems in our logic:
- We properly resolve a namespace package when a module of the same name exists
- When a package (root, regular, namespace) is located and we try to resolve the last component `foo`
  - If `foo` is a directory, we consider it's a regular package
    - If the `foo` directory was a namespace package, it fails and we don't test `foo` as a module
  - If `foo` is not a directory, we try to resolve it as a module

This is fixed by:
- Adding a check in package resolution to skip shadowed namespace packages
- Changing the way we resolve modules to not rely on `foo` being a directory
  - We directly check `foo/__init__`
  - If that doesn't work, we fallback to `foo`
  
## Test Plan

The issue #12278 introduces a unit test that should pass after the issue is fixed.
This test is included in the PR.

### CODE REVIEW

**Comment by carljm** [comment]
> That issue doesn't have the tag `help-wanted`, so I'm not sure if I can contribute a fix

There's no problem working on an issue that doesn't have the `help-wanted` tag, it just slightly increases the risk that there are unexplored complexities or we aren't sure how we want to address it yet :) It might be a good idea to comment on the issue before you start work, to reduce the chance of wasted work because two people work on an issue at once, or because the issue is stale, or whatever.

**Comment by AlexWaygood** [comment]
And in this particular case, the contribution is very welcome!

**Comment by carljm** [comment]
Going to leave review on this one to Alex and Micha, who are more familiar with the module resolver implementation.

File: crates/red_knot_python_semantic/src/module_resolver/path.rs [hunk 1]
```diff
@@ -59,6 +60,27 @@ impl ModulePath {
...
+    #[must_use]
+    pub(super) fn resolve_pure_module(
+        &self,
+        resolver: &ResolverContext,
+    ) -> Option<(File, ModuleKind)> {
+        let kind = if self.relative_path.ends_with("__init__") {
+            ModuleKind::Package
+        } else {
+            ModuleKind::Module
+        };
```
Comment (MichaReiser) [inline crates/red_knot_python_semantic/src/module_resolver/path.rs:72]: It seems to me that we can push `kind` out of this function. As far as I can tell, the kind is always `Module` for line 573 and `Package` for line 578

File: crates/red_knot_python_semantic/src/module_resolver/path.rs [hunk 2]
```diff
@@ -59,6 +60,27 @@ impl ModulePath {
         self.relative_path.push(component);
     }
 
+    #[must_use]
+    pub(super) fn resolve_pure_module(
+        &self,
+        resolver: &ResolverContext,
+    ) -> Option<(File, ModuleKind)> {
+        let kind = if self.relative_path.ends_with("__init__") {
```
Comment (MichaReiser) [inline crates/red_knot_python_semantic/src/module_resolver/path.rs:68]: Nit: I'm inclined to move this method out of `path` because `path` currently has no *resolution* mehtods. It only has methods to probe the structure. 

I do find the word *pure* unclear in this context. I think I know what you wanted to express with it. Maybe `resolve_file_module`?

**Review by MichaReiser — APPROVED** [review]

**Review by MichaReiser — COMMENTED** [review]
Overall looks great. Thank you. I've a few small nit comments and I'd like Alex to take a look as well

File: crates/red_knot_python_semantic/src/module_resolver/path.rs (hunk 2 above)
Comment (Slyces) [reply crates/red_knot_python_semantic/src/module_resolver/path.rs:68]: The intention was to differentiate from `packages` which are also technically modules.
But I also think `resolve_file_module` is better (and achieves the same thing), thanks for the suggestion!

Comment (slassourreuille) [reply crates/red_knot_python_semantic/src/module_resolver/path.rs]: Hi @MichaReiser, I've applied your comments:
- I keep a method `is_file_module` in the `ModulePath` to use in the `resolve_package` method
  (I think this fits the pattern of available methods)
- I moved the method `resolve_file_module` to `resolve.rs`

Comment (Slyces) [reply crates/red_knot_python_semantic/src/module_resolver/path.rs]: Hi @MichaReiser, I've applied your comments:
- I keep a method is_file_module in the ModulePath to use in the resolve_package method
  (I think this fits the pattern of available methods)
- I moved the method resolve_file_module to resolve.rs

File: crates/red_knot_python_semantic/src/module_resolver/path.rs [hunk 3]
```diff
@@ -59,6 +59,15 @@ impl ModulePath {
...
     }
 
+    #[must_use]
+    pub(super) fn is_file_module(&self, resolver: &ResolverContext) -> bool {
+        self.with_pyi_extension().to_file(resolver).is_some()
+            || self
+                .with_py_extension()
+                .and_then(|path| path.to_file(resolver))
+                .is_some()
+    }
```
Comment (AlexWaygood) [inline crates/red_knot_python_semantic/src/module_resolver/path.rs]: I think I would call this method something like `with_any_python_extension()`, and have it return `Option<File>`. Callers of the method from `resolver.rs` that just need to know whether the path exists on disk with a Python extension can then just do `path.with_any_python_extensions(resolver).is_some()`, and we'll be able to remove the `resolve_file_module()` function from `resolver.rs` (because this will then do the same thing as that function):

```suggestion
    /// If `self` exists on disk with either a `.pyi` or `.py` extension,
    /// return the [`File`] corresponding to that path.
    ///
    /// `.pyi` files take priority, as they always have priority when
    /// resolving modules.
    #[must_use]
    pub(super) fn with_any_python_extension(&self, resolver: &ResolverContext) -> Option<File> {
        self.with_pyi_extension().to_file(resolver).or_else(|| {
            self
                .with_py_extension()
                .and_then(|path| path.to_file(resolver))
            })
    }
```

Comment (AlexWaygood) [reply crates/red_knot_python_semantic/src/module_resolver/path.rs]: oh, I think you addressed this moments before I commented :-)

Comment (Slyces) [reply crates/red_knot_python_semantic/src/module_resolver/path.rs]: So I think the method exists, right now it's named `is_file_module`, but I can agree on any name :)
It's also been moved to `resolve.rs` under MichaReiser's comments that it didn't really match existing methods in `ModulePath`

Comment (AlexWaygood) [reply crates/red_knot_python_semantic/src/module_resolver/path.rs]: Yup, I agree that it doesn't really belong in `path.rs`, `resolver.rs` is better!

Comment (Slyces) [reply crates/red_knot_python_semantic/src/module_resolver/path.rs]: I'll add the docstring though, I think it helps :)

File: crates/red_knot_python_semantic/src/module_resolver/resolver.rs [hunk 4]
```diff
@@ -569,24 +569,19 @@ fn resolve_name(db: &dyn Db, name: &ModuleName) -> Option<(SearchPath, File, Mod
...
                 }
 
-                if let Some(module) = package_path
-                    .with_py_extension()
-                    .and_then(|path| path.to_file(&resolver_state))
-                {
-                    return Some((search_path.clone(), module, kind));
+                // If we found a module (but no package), return it
+                if let Some(module) = file_module {
+                    return Some((search_path.clone(), module, ModuleKind::Module));
```
Comment (AlexWaygood) [inline crates/red_knot_python_semantic/src/module_resolver/resolver.rs:584]: This logic can be simplified slightly if we make the `ModulePath::join()` function in `path.rs` public (it already exists, but it's currently a test-only private function). Something like this should work (the diff is relative to your PR branch):

```diff
diff --git a/crates/red_knot_python_semantic/src/module_resolver/path.rs b/crates/red_knot_python_semantic/src/module_resolver/path.rs
index a49d1dc20..76c00b1c2 100644
--- a/crates/red_knot_python_semantic/src/module_resolver/path.rs
+++ b/crates/red_knot_python_semantic/src/module_resolver/path.rs
@@ -59,6 +59,13 @@ impl ModulePath {
         self.relative_path.push(component);
     }
 
+    #[must_use]
+    pub(crate) fn join(&self, component: &str) -> ModulePath {
+        let mut result = self.clone();
+        result.push(component);
+        result
+    }
+
     #[must_use]
     pub(super) fn is_directory(&self, resolver: &ResolverContext) -> bool {
         let ModulePath {
@@ -634,15 +641,6 @@ mod tests {
 
     use super::*;
 
-    impl ModulePath {
-        #[must_use]
-        fn join(&self, component: &str) -> ModulePath {
-            let mut result = self.clone();
-            result.push(component);
-            result
-        }
-    }
-
     impl SearchPath {
         fn join(&self, component: &str) -> ModulePath {
             self.to_module_path().join(component)
diff --git a/crates/red_knot_python_semantic/src/module_resolver/resolver.rs b/crates/red_knot_python_semantic/src/module_resolver/resolver.rs
index 50aaf9dbd..294ad477d 100644
--- a/crates/red_knot_python_semantic/src/module_resolver/resolver.rs
+++ b/crates/red_knot_python_semantic/src/module_resolver/resolver.rs
@@ -569,18 +569,13 @@ fn resolve_name(db: &dyn Db, name: &ModuleName) -> Option<(SearchPath, File, Mod
 
                 package_path.push(module_name);
 
-                // Try to resolve a stub/module with the current name
-                let file_module = resolve_file_module(&package_path, &resolver_state);
-
-                // Then check if a regular package exists with the same name (it takes
-                // precedence)
-                package_path.push("__init__");
-                if let Some(regular_package) = resolve_file_module(&package_path, &resolver_state) {
+                // Regular packages take first priority:
+                if let Some(regular_package) = resolve_file_module(&package_path.join("__init__"), &resolver_state) {
                     return Some((search_path.clone(), regular_package, ModuleKind::Package));
                 }
 
-                // If we found a module (but no package), return it
-                if let Some(module) = file_module {
+                // If there's a single-file module (but no package), return it
+                if let Some(module) = resolve_file_module(&package_path, &resolver_state) {
                     return Some((search_path.clone(), module, ModuleKind::Module));
                 }
```

Comment (MichaReiser) [reply crates/red_knot_python_semantic/src/module_resolver/resolver.rs:584]: The reason for using `push` is because it avoids allocating a new path.

Comment (AlexWaygood) [reply crates/red_knot_python_semantic/src/module_resolver/resolver.rs:584]: My main point is that if the path resolves to a regular package, we're doing an unnecessary `resolve_file_module()` call. I doubt it matters much in terms of performance but I think it could be written slightly more clearly. If we want to avoid allocating, we could add a `.pop()` method:

```diff
--- a/crates/red_knot_python_semantic/src/module_resolver/path.rs
+++ b/crates/red_knot_python_semantic/src/module_resolver/path.rs
@@ -59,6 +59,10 @@ impl ModulePath {
         self.relative_path.push(component);
     }
 
+    pub(crate) fn pop(&mut self) {
+        self.relative_path.pop();
+    }
+
     #[must_use]
     pub(super) fn is_directory(&self, resolver: &ResolverContext) -> bool {
         let ModulePath {
diff --git a/crates/red_knot_python_semantic/src/module_resolver/resolver.rs b/crates/red_knot_python_semantic/src/module_resolver/resolver.rs
index 68f08118e..c563d0b80 100644
--- a/crates/red_knot_python_semantic/src/module_resolver/resolver.rs
+++ b/crates/red_knot_python_semantic/src/module_resolver/resolver.rs
@@ -569,9 +569,6 @@ fn resolve_name(db: &dyn Db, name: &ModuleName) -> Option<(SearchPath, File, Mod
 
                 package_path.push(module_name);
 
-                // Try to resolve a stub/module with the current name
-                let file_module = resolve_file_module(&package_path, &resolver_state);
-
                 // Then check if a regular package exists with the same name (it takes
                 // precedence)
                 package_path.push("__init__");
@@ -579,8 +576,9 @@ fn resolve_name(db: &dyn Db, name: &ModuleName) -> Option<(SearchPath, File, Mod
                     return Some((search_path.clone(), regular_package, ModuleKind::Package));
                 }
 
-                // If we found a module (but no package), return it
-                if let Some(module) = file_module {
+                // If we can find a module (but no package), return it
+                package_path.pop();
+                if let Some(module) = resolve_file_module(&package_path, &resolver_state) {
                     return Some((search_path.clone(), module, ModuleKind::Module));
                 }
```

Comment (Slyces) [reply crates/red_knot_python_semantic/src/module_resolver/resolver.rs:584]: I think I find either options (`join` or `pop`) clearer than the existing implementation

**Review by AlexWaygood — APPROVED** [review]
Looks great. Thanks, this was an excellent contribution @Slyces! :D
