### PR TITLE
[red-knot] Break up call binding into two phases

### LINKED ISSUE #15460: [red-knot] match arguments to parameters before inferring argument types
In the medium term, we will need contextual type inference of argument types. (This will be more relevant once we have generics.) Some specific examples are at https://discuss.python.org/t/pep-747-typeexpr-type-hint-for-a-type-expression/55984/67. PEP 747 will also add a new case of this. This means we will have to know which parameter an argument maps to, before we infer the type of the argument expression.

In the short term, this will allow us to fix a bug with how we handle `KnownFunction::parameter_expectations`. It's _parameter_ expectations, but we apply it naively to _argument_ indices, giving the wrong answer when arguments are out-of-order with keywords. This bug currently shows up when `typing.cast` is called with out-of-order keyword arguments.

### PR DESCRIPTION
**Pull request by dcreager**
This breaks up call binding into two phases:

- **_Matching parameters_** just looks at the names and kinds (positional/keyword) of each formal and actual parameters, and matches them up.  Most of the current call binding errors happen during this phase.

- Once we have matched up formal and actual parameters, we can **_infer types_** of each actual parameter, and **_check_** that each one is assignable to the corresponding formal parameter type.

As part of this, we add information to each formal parameter about whether it is a type form or not. Once [PEP 747](https://peps.python.org/pep-0747/) is finalized, we can hook that up to this internal type form representation. This replaces the `ParameterExpectations` type, which did the same thing in a more ad hoc way.

While we're here, we add a new fluent API for building `Parameter`s, which makes our signature constructors a bit nicer to read.  We also eliminate a TODO where we were consuming types from the argument list instead of the bound parameter list when evaluating our special-case known functions.

Closes #15460

### CODE REVIEW

**Comment by MichaReiser** [comment]
Is this PR WIP or ready for review?

**Comment by dcreager** [comment]
> Is this PR WIP or ready for review?

Doh! I remembered to update everything except for the title :joy:   It's ready for review

File: crates/red_knot_python_semantic/src/types/call/arguments.rs [hunk 1]
```diff
@@ -1,88 +1,179 @@
...
+    form: Cell<ArgumentForm>,
+
+    /// The inferred type of this argument. Will be `Type::Unknown` if we haven't inferred a type
+    /// for this argument yet.
+    #[allow(clippy::struct_field_names)]
+    argument_type: Cell<Type<'db>>,
+
+    /// The inferred type of this argument when/if it is used as a `TypeForm`. Will be
+    /// `Type::Unknown` if we haven't inferred a type-form type for this argument yet.
+    type_form_type: Cell<Type<'db>>,
```
Comment (carljm) [inline crates/red_knot_python_semantic/src/types/call/arguments.rs:74]: If I understand correctly, storing two separate types here allows us to share a single set of arguments, even if we use those arguments to call e.g. a union of callables, in which the same argument might need to be inferred as a value expression for one of the callables and a type form for the other.

(Does our type inference approach actually support that case in this PR? Either way, should we add a test for that case?)

My concern here is that while this works for "type expression vs value expression", it doesn't scale to generalized "type context." (See https://github.com/astral-sh/ruff/issues/16838 for a writeup on what I mean by "type context" here.) Assuming we will need generalized type context, we will I think eventually either need to clone arguments, or we'll need a more generalized representation here that can store any number of types for a given argument, keyed by the context type perhaps?

But as long as we are aware of this, and have a rough idea how we'd approach it (and maybe mention it in a TODO comment, or in a comment over on https://github.com/astral-sh/ruff/issues/16838 ?), it could still be OK to go with this version for now.

**Review by carljm — COMMENTED** [review]
Haven't finished my review yet, but leaving a few initial comments since I need to head out for a bit now.

File: crates/red_knot_python_semantic/src/types/call/arguments.rs [hunk 2]
```diff
@@ -1,88 +1,179 @@
...
-        self.0.get(1).map(Argument::ty)
+#[derive(Clone, Debug)]
+pub(crate) struct Argument<'a, 'db> {
+    kind: ArgumentKind<'a>,
+    form: Cell<ArgumentForm>,
+
+    /// The inferred type of this argument. Will be `Type::Unknown` if we haven't inferred a type
+    /// for this argument yet.
+    #[allow(clippy::struct_field_names)]
+    argument_type: Cell<Type<'db>>,
```
Comment (carljm) [inline crates/red_knot_python_semantic/src/types/call/arguments.rs:70]: What were your considerations in using Unknown to represent "no type inferred yet" vs using an `Option<Type>` here? Given that `Unknown` is also a valid inferred type for an argument, the latter seems semantically clearer about whether we've inferred a type for this argument yet. But maybe in practice we don't need that clarity?

File: crates/red_knot_python_semantic/src/types/call/arguments.rs [hunk 3]
```diff
@@ -1,88 +1,179 @@
...
+
 use super::Type;
 
-/// Typed arguments for a single call, in source order.
+/// Typed arguments for a single call, in source order, with an optional bound self/cls parameter.
 #[derive(Clone, Debug, Default)]
-pub(crate) struct CallArguments<'a, 'db>(Vec<Argument<'a, 'db>>);
+pub(crate) struct CallArguments<'a, 'db> {
+    bound_self: Option<Argument<'a, 'db>>,
+    arguments: Rc<[Argument<'a, 'db>]>,
```
[the remark this answers is not in the document]
Comment (MichaReiser) [reply crates/red_knot_python_semantic/src/types/call/arguments.rs:12]: I think it's worth making this a comment on `arguments`. The reason of `Rc` is definetely not "appearant" (and one of our first uses in Red Knot?)

File: crates/red_knot_python_semantic/src/types/call/arguments.rs [hunk 4]
```diff
@@ -1,88 +1,179 @@
...
+}
 
 impl<'a, 'db> CallArguments<'a, 'db> {
     /// Create a [`CallArguments`] with no arguments.
     pub(crate) fn none() -> Self {
-        Self(Vec::new())
+        Self {
+            bound_self: None,
+            arguments: vec![].into(),
```
Comment (MichaReiser) [inline crates/red_knot_python_semantic/src/types/call/arguments.rs:20]: Nit: Would `Default::default()` work?
```suggestion
            arguments: Default::default(),
```

File: crates/red_knot_python_semantic/src/types/call/arguments.rs [hunk 5]
```diff
@@ -1,88 +1,179 @@
...
     /// Create a [`CallArguments`] from an iterator over non-variadic positional argument types.
     pub(crate) fn positional(positional_tys: impl IntoIterator<Item = Type<'db>>) -> Self {
         positional_tys
             .into_iter()
-            .map(Argument::Positional)
+            .map(|ty| Argument::positional().with_argument_type(ty))
             .collect()
     }
 
     /// Prepend an extra positional argument.
```
Comment (MichaReiser) [inline crates/red_knot_python_semantic/src/types/call/arguments.rs:32]: Can we add a `## Panics` section to the documentation that explains that this method can only be called for `self` when `bound_self` is `None`. 

The alternative would be to make this method return an `Option` or a `Result` and use explicit `unwrap` calls. But that might be somewhat annoying if there are too many call sites. 

After reviewing the entire PR: It seems that this variant bubbles all the way up to `Type::try_*` methods. I think we should document this invariant on all methods where it is necessary or enforce it by changing the signature.

File: crates/red_knot_python_semantic/src/types/call/arguments.rs [hunk 6]
```diff
@@ -1,88 +1,179 @@
+use std::cell::Cell;
+use std::rc::Rc;
+
+use bitflags::bitflags;
+
 use super::Type;
 
-/// Typed arguments for a single call, in source order.
+/// Typed arguments for a single call, in source order, with an optional bound self/cls parameter.
```
Comment (MichaReiser) [inline crates/red_knot_python_semantic/src/types/call/arguments.rs:8]: I think it would be good to document that `CallArguments` should be light to clone because the operation is performent frequently during call binding.

File: crates/red_knot_python_semantic/src/types/call/bind.rs [hunk 7]
```diff
@@ -135,20 +153,300 @@ impl<'db> Bindings<'db> {
             first.report_diagnostics(context, node);
         }
     }
+
+    /// Evaluates the return type of certain known callables, where we have special-case logic to
+    /// determine the return type in a way that isn't directly expressible in the type system.
+    fn evaluate_special_cases(&mut self, db: &'db dyn Db) {
```
Comment (MichaReiser) [inline crates/red_knot_python_semantic/src/types/call/bind.rs:159]: Nit: Should we rename this to `evalute_known_cases` to reuse our existing terminology around known classes, functions?

File: crates/red_knot_python_semantic/src/types/call/bind.rs [hunk 8]
```diff
@@ -183,23 +482,16 @@ pub(crate) struct CallableBinding<'db> {
...
     ) -> Self {
         // If this callable is a bound method, prepend the self instance onto the arguments list
         // before checking.
-        let arguments = if let Some(bound_type) = signature.bound_type {
-            Cow::Owned(arguments.with_self(bound_type))
-        } else {
-            Cow::Borrowed(arguments)
-        };
+        if let Some(bound_type) = signature.bound_type {
+            arguments = arguments.with_self(bound_type);
```
Comment (MichaReiser) [inline crates/red_knot_python_semantic/src/types/call/bind.rs:493]: It seems that this path might now panic if `arguments` already has `self` bound. 

We should at least document this constraint on `match_parameters` but it makes me think if we should change the signature to return a `Result` or `Option` here to have the caller *guarantee* that `arguments` isn't bound yet.

File: crates/red_knot_python_semantic/src/types/call/bind.rs [hunk 9]
```diff
@@ -170,11 +468,12 @@ impl<'a, 'db> IntoIterator for &'a mut Bindings<'db> {
 /// overloads, we store this error information for each overload.
 ///
 /// [overloads]: https://github.com/python/typing/pull/1839
-#[derive(Debug, Clone, PartialEq, Eq)]
-pub(crate) struct CallableBinding<'db> {
+#[derive(Debug, Clone)]
```
Comment (MichaReiser) [inline crates/red_knot_python_semantic/src/types/call/bind.rs:471]: Nit: Is it still necessary that all these types are `Clone`?

File: crates/red_knot_python_semantic/src/types/call/bind.rs [hunk 10]
```diff
@@ -333,27 +632,30 @@ impl<'db> CallableBinding<'db> {
...
 pub(crate) struct Binding<'db> {
     /// Return type of the call.
     return_ty: Type<'db>,
 
-    /// Bound types for parameters, in parameter source order.
-    parameter_tys: Box<[Type<'db>]>,
+    /// The formal parameter that each argument is matched with, in argument source order, or
+    /// `usize::MAX` if the argument was not matched to any parameter.
+    argument_parameters: Box<[usize]>,
```
Comment (MichaReiser) [inline crates/red_knot_python_semantic/src/types/call/bind.rs:642]: I'd prefer an `Option<usize>` over the maigc use of `usize::MAX` or to introduce a newtype wrapper that behaves as `Option<usize>` but does the `magic` encoding internally (e.g. by using an `Option<NonZeroUsize>` internally and that maps the indices by 1 offset).

File: crates/red_knot_python_semantic/src/types/call.rs [hunk 11]
```diff
@@ -4,15 +4,18 @@ use crate::Db;
...
 pub(super) use bind::Bindings;
 
 /// Wraps a [`Bindings`] for an unsuccessful call with information about why the call was
 /// unsuccessful.
 ///
 /// The bindings are boxed so that we do not pass around large `Err` variants on the stack.
-#[derive(Debug, Clone, PartialEq, Eq)]
-pub(crate) struct CallError<'db>(pub(crate) CallErrorKind, pub(crate) Box<Bindings<'db>>);
+#[derive(Debug, Clone)]
+pub(crate) struct CallError<'call, 'db>(
```
Comment (MichaReiser) [inline crates/red_knot_python_semantic/src/types/call.rs:15]: Do we need the precision of both lifetimes or could we use one unified `'a` lifetime for both `call` and `db`?

It seems to me that `call` will always be the shorter lifetime of the two.

File: crates/red_knot_python_semantic/src/types/call/arguments.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (dcreager) [reply crates/red_knot_python_semantic/src/types/call/arguments.rs:12]: > What I understand from your sentence in the PR summary is that we only perform type inference once we matched all parameters?

Yes that's right

> Does this happen exactly once or is it possible that this operation is performed more than once (e.g. once for every matching signature?)

This is related to @carljm comment https://github.com/astral-sh/ruff/pull/16546#discussion_r2002195997

As of right now, we peform type inference on each argument at most once. We do not infer a different type for an argument for each matching signature. As we move towards supporting generics, we will have to do more work per argument for each matching signature. But I am purposefully trying to keep this PR simpler by not bringing that into play yet.

> I'm asking because I'm a bit concerned about the `Cell` use in `Argument` because we then loose the static assertion that type inference can happen exactly once (you could hold on to multiple `Arguments` that all point to the same shared slice but then infer the type with differently matched parameters).

Before we had that as a static guarantee because `Argument` had no mutuator methods — you had to provide the inferred type when you created it. If I understand your concern, it's less about using `Cell` in particular and more about having a mutator method at all, is that right? Would you have the same worry if it was a more normal `&mut self` mutator method? Because there would still be no static guarantee that you didn't call it twice.

I could pull the argument types out into a separate Rust type, which you would create after `match_parameters` and then pass in to `check_types`. But I think then we'd lose the static guarantee that the `ArgumentTypes` that you pass in in step two was created for the `CallArguments` that you pass in in step one.

File: crates/red_knot_python_semantic/src/types/call/arguments.rs (hunk 1 above)
Comment (dcreager) [reply crates/red_knot_python_semantic/src/types/call/arguments.rs:74]: > (Does our type inference approach actually support that case in this PR? Either way, should we add a test for that case?)

In theory yes https://github.com/astral-sh/ruff/pull/16546#discussion_r2001792198, but that's a good suggestion to add a test for it

> have a rough idea how we'd approach it

For that I assumed that we would eventually move the inferred argument types down into `Binding`, so that we could store separate inferred types for each signature.  I wanted to avoid that in this PR, since I didn't want to repeat the inference step for each matched signature.  (`infer_expression` and `infer_type_expression` don't seem to be salsa queries, and so we wouldn't get memoization of those for free, unless I'm misunderstanding something)

My suggestion for @MichaReiser's comment https://github.com/astral-sh/ruff/pull/16546#discussion_r2003341589 might work for this too — go ahead and create `ArgumentTypes`, with a single inferred type for each argument, and put it in `Bindings` since we currently only do inference once per call.  (Actually put it there twice: once for holding value types, and one for type form types.)

Or, just eat the cost of doing inference once per signature now, since we know we'll need to at some point anyway?

Comment (dcreager) [reply crates/red_knot_python_semantic/src/types/call/arguments.rs:74]: > Assuming we will need generalized type context, we will I think eventually either need to clone arguments

Put differently, with type contexts, we will definitely need to perform inference multiple times on each argument.  One thing I noticed fixing some tests on this PR is that we currently have to make sure to infer a type for each argument, even if the argument was not successfully matched to a parameter.  That is, we actually can't infer argument types _at most_ once, it has to be _exactly_ once.  This is because the argument expression might contain standalone expressions, and we have tests that verify that we end up inferring and storing a type for each of those.  If we don't make sure to visit non-matched arguments, we can miss some of those.

Will that be an issue inferring arguments multiple times? Will the standalone expression machinery handle that correctly? (Will it be possible to infer different types for standalone expressions inside of an argument that ends up with different inferred types for different signatures? Or will we just collapse those down into a union?)

File: crates/red_knot_python_semantic/src/types/call/arguments.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (dcreager) [reply crates/red_knot_python_semantic/src/types/call/arguments.rs:12]: I don't think we can use `Rc::get_mut` because with how it's formulated right now, we _need_ that sharing. Each signature might have to bind a different `self`/`cls` argument to the front of the argument list, but we also only want to perform type inference once on the (non-bound) arguments that are the same for each signature. The bindings themselves have to store the arguments so that they can be type-checked in the later call, and the outer code in `infer.rs` also needs to store the arguments so that it can do the actual type inference.

[the remark this answers is not in the document]
Comment (carljm) [reply crates/red_knot_python_semantic/src/types/call/arguments.rs:12]: > how we avoid that we don't accidentally end up mutating the same underlying `Argument` that is shared by using `Rc<[Argument]>`

My understanding is that the whole point of this structure is that we _do_ want to mutate the same underlying shared `Argument`; it gives us a place to store the inferred type for that argument, to avoid inferring it multiple times.

**Comment by dcreager** [comment]
I'm reworking this with a different way of representing arguments and types per @MichaReiser and @carljm's comments.  Putting this back to draft while I do that.

File: crates/red_knot_python_semantic/src/types/call/arguments.rs (hunk 1 above)
Comment (carljm) [reply crates/red_knot_python_semantic/src/types/call/arguments.rs:74]: This all makes sense. I'm fine in general with keeping this PR simpler by not expanding scope to cover the future need for type context, I would just suggest recording our best understanding of how the current approach is limited and what we may need to do instead in future, either in a TODO comment or in a new issue. (It could even just be as a comment over on #16838.)

> One thing I noticed fixing some tests on this PR is that we currently have to make sure to infer a type for each argument, even if the argument was not successfully matched to a parameter. That is, we actually can't infer argument types _at most_ once, it has to be _exactly_ once. This is because the argument expression might contain standalone expressions, and we have tests that verify that we end up inferring and storing a type for each of those. If we don't make sure to visit non-matched arguments, we can miss some of those.

Yes, this requirement originates with our desire to have some type for every expression, both for IDE uses and for typed-linter use cases. It isn't actually limited to just standalone expressions, it's a requirement currently that _every_ expression have a type.

> Will that be an issue inferring arguments multiple times? Will the standalone expression machinery handle that correctly? (Will it be possible to infer different types for standalone expressions inside of an argument that ends up with different inferred types for different signatures? Or will we just collapse those down into a union?)

The purpose of standalone expressions is that inferring a type for them does go through a query (`infer_expression_types`). I think for expressions (like call arguments) that may need to be inferred multiple times with different type contexts, we will need to make them standalone expressions, and we will need to add the type context as an argument to `infer_expression_types`, so we automatically get Salsa caching keyed on the expression+context pair.

And then, yes, we will need to decide how to ultimately provide a single type for that expression to, say, IDE hover, or a typed linter rule. Not sure I have a better idea for that than the union? It should be relatively rare in practice that we call a union of callables where different elements of the union have different type contexts for the same argument.

Comment (dcreager) [reply crates/red_knot_python_semantic/src/types/call/arguments.rs:74]: > It isn't actually limited to just standalone expressions, it's a requirement currently that _every_ expression have a type.

Ah right, thank you for calling that out!

> And then, yes, we will need to decide how to ultimately provide a single type for that expression to, say, IDE hover, or a typed linter rule. Not sure I have a better idea for that than the union? It should be relatively rare in practice that we call a union of callables where different elements of the union have different type contexts for the same argument.

My more pressing (and mundane) concern was that `store_expression_type` currently panics if you try to store a type for an expression more than once. I wasn't certain if that's just there to help catch unexpected bugs, or if it's protecting something more fundamental that would be hard to reconcile with inferring expressions multiple times in different contexts.

Comment (carljm) [reply crates/red_knot_python_semantic/src/types/call/arguments.rs:74]: > My more pressing (and mundane) concern was that `store_expression_type` currently panics if you try to store a type for an expression more than once. I wasn't certain if that's just there to help catch unexpected bugs, or if it's protecting something more fundamental that would be hard to reconcile with inferring expressions multiple times in different contexts.

It's aiming to catch bugs where we accidentally do unnecessary repeat work, or accidentally include an expression in multiple different inference regions. I've been aware that this will eventually need modification to handle speculative inference or inference with differing type contexts, but haven't yet worked out a detailed plan for it. Ideally we would keep some protection against accidental duplication by using explicit API for cases where we really do want to infer the same expression tree multiple times. (One possibility implied above is that we only do this for standalone expressions, and so we have special cases around merging the result of `infer_expression_types` back into the enclosing region that account for the fact that we might need to integrate multiple inferences.)

File: crates/red_knot_python_semantic/src/types/call/arguments.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (dcreager) [reply crates/red_knot_python_semantic/src/types/call/arguments.rs]: This is moot now that I'm doing value form XOR type form

Comment (dcreager) [reply crates/red_knot_python_semantic/src/types/call/arguments.rs]: This is moot with the new represenation, where you have to provide a callback to infer each argument type when constructing a `CallArgumentTypes`.  You now either (a) have all argument types uninferred, in which case you have a `CallArguments`, or (b) have inferred all argument types, in which case you have a `CallArgumentTypes`.

File: crates/red_knot_python_semantic/src/types/call/arguments.rs (hunk 1 above)
Comment (dcreager) [reply crates/red_knot_python_semantic/src/types/call/arguments.rs]: > My more pressing (and mundane) concern was that `store_expression_type` currently panics if you try to store a type for an expression more than once.

In working on a test case, I realized that this is an issue already, even without inferring argument types separately for each signature — if you were to use an argument as both a value and a type, we would infer its expression twice, and end up trying to store a type for that expression twice.

So for now I've changed this PR to say that an argument must be used **either** as a value or as a type form for all of the signatures in any particular call site.

File: crates/red_knot_python_semantic/src/types/call/arguments.rs (hunk 4 above)
Comment (dcreager) [reply crates/red_knot_python_semantic/src/types/call/arguments.rs]: Done (now with `VecDeque`)

File: crates/red_knot_python_semantic/src/types/call/arguments.rs (hunk 5 above)
Comment (dcreager) [reply crates/red_knot_python_semantic/src/types/call/arguments.rs]: This no longer panics with the new representation

File: crates/red_knot_python_semantic/src/types/call/arguments.rs (hunk 6 above)
Comment (dcreager) [reply crates/red_knot_python_semantic/src/types/call/arguments.rs]: We don't clone this anymore, we use the `push_self`/`pop_self` methods to modify a single one in place.

File: crates/red_knot_python_semantic/src/types/call/bind.rs (hunk 7 above)
Comment (dcreager) [reply crates/red_knot_python_semantic/src/types/call/bind.rs]: Done

File: crates/red_knot_python_semantic/src/types/call/bind.rs (hunk 8 above)
Comment (dcreager) [reply crates/red_knot_python_semantic/src/types/call/bind.rs]: This can no longer panic, and we no longer clone.  Instead we `push_front` onto the `VecDeque` and `pop_front` before returning

File: crates/red_knot_python_semantic/src/types/call/bind.rs (hunk 9 above)
Comment (dcreager) [reply crates/red_knot_python_semantic/src/types/call/bind.rs]: Nope! Removed

File: crates/red_knot_python_semantic/src/types/call/bind.rs (hunk 10 above)
Comment (dcreager) [reply crates/red_knot_python_semantic/src/types/call/bind.rs]: Done

File: crates/red_knot_python_semantic/src/types/call.rs (hunk 11 above)
Comment (dcreager) [reply crates/red_knot_python_semantic/src/types/call.rs]: The extra lifetime went away with the new representation

File: crates/red_knot_python_semantic/src/types.rs [hunk 12]
```diff
@@ -1689,7 +1689,7 @@ impl<'db> Type<'db> {
 
         if let Symbol::Type(descr_get, descr_get_boundness) = descr_get {
             let return_ty = descr_get
-                .try_call(db, &CallArguments::positional([self, instance, owner]))
+                .try_call(db, CallArgumentTypes::positional([self, instance, owner]))
```
Comment (dcreager) [inline crates/red_knot_python_semantic/src/types.rs:1692]: There are a lot of cases like this where we make a call "internally".  Here we're not really _inferring_ the types of the arguments; they're provided directly.  This is also handled nicely with the new representation: you construct `CallArgumentTypes`, since you have argument types ready to specify.

**Review by dcreager — COMMENTED** [review]
Okay, I've pushed up a new representation that I think is nicer, and addresses most of the concerns.

In summary:

`CallArguments` goes back to being a simple list of `Argument`s, which look exactly like they did before. This does not store argument types.

Once you are ready to perform type inference on an argument list, you transform the `CallArguments` into a `CallArgumentTypes`. You provide a callback to infer each argument type. That makes it impossible to have incomplete partially inferred state.

This also makes it clearer which information each phase requires, since `match_parameters` takes in a `CallArguments`, and `check_types` takes in a `CallArgumentTypes`.

We don't store `CallArguments` in any of the bindings types anymore, which means we don't need to make them cheap to clone, and we don't need any interior mutability tricks to let the type inference code update shared state.

To handle bound `self`/`cls` parameters, we now use `VecDeque` instead of `Vec` for both `CallArguments` and `CallArgumentTypes`.  That lets us cheaply push the bound parameter onto the front of the argument list when needed, and pop it back off when we're done.

File: crates/red_knot_python_semantic/src/types/call/arguments.rs [hunk 13]
```diff
@@ -1,88 +1,116 @@
...
 
-    /// Create a [`CallArguments`] from an iterator over non-variadic positional argument types.
-    pub(crate) fn positional(positional_tys: impl IntoIterator<Item = Type<'db>>) -> Self {
-        positional_tys
-            .into_iter()
-            .map(Argument::Positional)
-            .collect()
+    /// Pop the extra synthetic argument from the front of this argument list.
+    pub(crate) fn pop_self(&mut self) {
+        self.0.pop_front();
```
Comment (MichaReiser) [inline crates/red_knot_python_semantic/src/types/call/arguments.rs:19]: Do we need an assertion that the front attribute is `Synthetic` to avoid cases where someone calls `pop_self` without having called `push_self` before? 

Or should we use an `Option` for the `self` argument (I don't know if that's the approach that you had initially), as it seems that we never need to return a slice (which wouldn't work with `VecDeque` anyway) and we only ever need to mutate the first element.

File: crates/red_knot_python_semantic/src/types/call/arguments.rs [hunk 14]
```diff
@@ -1,88 +1,116 @@
...
+    types: VecDeque<Type<'db>>,
+}
 
-    // TODO this should be eliminated in favor of [`bind_call`]
-    pub(crate) fn second_argument(&self) -> Option<Type<'db>> {
-        self.0.get(1).map(Argument::ty)
+impl<'a, 'db> CallArgumentTypes<'a, 'db> {
+    /// Create a [`CallArgumentTypes`] with no arguments.
+    pub(crate) fn none() -> Self {
+        let arguments = CallArguments(VecDeque::default());
```
Comment (MichaReiser) [inline crates/red_knot_python_semantic/src/types/call/arguments.rs:60]:
```suggestion
        let arguments = CallArguments::default();
```

**Review by MichaReiser — APPROVED** [review]

File: crates/red_knot_python_semantic/src/types/call/bind.rs [hunk 15]
```diff
@@ -333,27 +694,35 @@ impl<'db> CallableBinding<'db> {
...
+#[derive(Debug)]
 pub(crate) struct Binding<'db> {
     /// Return type of the call.
     return_ty: Type<'db>,
 
-    /// Bound types for parameters, in parameter source order.
-    parameter_tys: Box<[Type<'db>]>,
+    /// The formal parameter that each argument is matched with, in argument source order, or
+    /// `usize::MAX` if the argument was not matched to any parameter.
+    argument_parameters: Box<[Option<usize>]>,
```
Comment (dhruvmanila) [inline crates/red_knot_python_semantic/src/types/call/bind.rs:704]: Does the field documentation need to be updated to reflect that change of using `None` instead of `usize::MAX`?

**Review by dhruvmanila — COMMENTED** [review]
I haven't done a thorough review, I'm mainly looking at the PR to keep up with the changes happening on main. I think the changes looks good, will defer it to Carl/Micha for the final review.

File: crates/red_knot_python_semantic/src/types/call/bind.rs (hunk 15 above)
Comment (dcreager) [reply crates/red_knot_python_semantic/src/types/call/bind.rs]: It sure does! Thanks, good catch

File: crates/red_knot_python_semantic/src/types/call/arguments.rs (hunk 13 above)
Comment (dcreager) [reply crates/red_knot_python_semantic/src/types/call/arguments.rs]: I changed this to a `with_self` method that does the pushing/popping in the right pattern, instead of adding assertions or more complex types to ensure the caller does the right thing.

File: crates/red_knot_python_semantic/src/types/call/bind.rs [hunk 16]
```diff
@@ -26,29 +29,79 @@ use ruff_text_size::Ranged;
...
+    signatures: Signatures<'db>,
     /// By using `SmallVec`, we avoid an extra heap allocation for the common case of a non-union
     /// type.
     elements: SmallVec<[CallableBinding<'db>; 1]>,
+
+    /// Whether each argument will be used as a value and/or a type form in this call.
+    ///
+    /// TODO: We will eventually infer completely different argument types for each signature, once
+    /// we are able to use the annotated parameter types as type contexts for that inference. At
+    /// that point, this field will move down into `CallBinding` or `Binding`.
```
Comment (carljm) [inline crates/red_knot_python_semantic/src/types/call/bind.rs:43]: This TODO may not be accurate, given our conversation today? Totally up to you how you want to handle this.

**Review by carljm — APPROVED** [review]
Love this. Love the Parameter fluent builder, love the new type-safe distinction between `CallArguments` and `CallArgumentTypes`. Fantastic!

File: crates/red_knot_python_semantic/src/types/call/bind.rs (hunk 16 above)
Comment (dcreager) [reply crates/red_knot_python_semantic/src/types/call/bind.rs]: Removed
