### PR TITLE
[`pyupgrade`] Prevent infinite loop with `I002` (`UP010`, `UP035`)

### LINKED ISSUE #16802: [Infinite loop] I002 and UP035
### Summary

Ruff fails to converge when [`missing-required-import` (I002)](https://docs.astral.sh/ruff/rules/missing-required-import/) and [`deprecated-import` (UP035)](https://docs.astral.sh/ruff/rules/deprecated-import/) are selected and a deprecated import is required.

```console
$ echo 1 | ruff --isolated check - --select I002,UP035 --config 'lint.isort.required-imports=["from collections import Sequence"]' --fix

error: Failed to converge after 100 iterations.

This indicates a bug in Ruff. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BInfinite%20loop%5D

...quoting the contents of `-`, the rule codes I002, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
from collections.abc import Sequence
1
-:1:1: I002 Missing required import: `from collections import Sequence`
Found 101 errors (100 fixed, 1 remaining).
[*] 1 fixable with the `--fix` option.
```

### Version

ruff 0.11.0 (2cd25ef64 2025-03-14)

### LINKED ISSUE #18729: [Infinite loop] I002 and UP010
### Summary

Ruff fails to converge when [`missing-required-import` (I002)](https://docs.astral.sh/ruff/rules/missing-required-import/) and [`unnecessary-future-import` (UP010)](https://docs.astral.sh/ruff/rules/unnecessary-future-import/) are selected and an unnecessary import is required.

```console
$ echo 1 | ruff --isolated check - --select I002,UP010 --config 'lint.isort.required-imports=["from __future__ import generator_stop"]' --fix

error: Failed to converge after 100 iterations.

This indicates a bug in Ruff. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BInfinite%20loop%5D

...quoting the contents of `-`, the rule codes I002, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

1
-:1:1: I002 Missing required import: `from __future__ import generator_stop`
Found 101 errors (100 fixed, 1 remaining).
[*] 1 fixable with the `--fix` option.
```

### Version

ruff 0.12.0 (87f0feb21 2025-06-17)

### PR DESCRIPTION
**Pull request by danparizher**
## Summary

Fixes #18729 and fixes #16802

## Test Plan

Manually verified via CLI that Ruff no longer enters an infinite loop by running:
```sh
echo 1 | ruff --isolated check - --select I002,UP010 --fix
```
with `required-imports = ["from __future__ import generator_stop"]` set in the config, confirming “All checks passed!” and no snapshots were generated.

### CODE REVIEW

File: crates/ruff_linter/src/rules/pyupgrade/rules/unnecessary_future_import.rs [hunk 1]
```diff
@@ -91,6 +92,44 @@ pub(crate) fn unnecessary_future_import(checker: &Checker, stmt: &Stmt, names: &
...
+                    },
+                });
+                checker
+                    .settings()
+                    .isort
+                    .required_imports
+                    .contains(&name_import)
+            }
+            _ => false,
+        };
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/pyupgrade/rules/unnecessary_future_import.rs]: This looks like a nice potential helper function. Refactoring it like that would both allow us to reuse some code here with an early return and share this with UP035, which I think could use the same fix (https://github.com/astral-sh/ruff/issues/16802). I'd suggest something like:

```rust
fn helper_function(/* ... */) -> bool {
  let name_import = match stmt {
              ruff_python_ast::Stmt::ImportFrom(ruff_python_ast::StmtImportFrom {
                  module,
                  level,
                  ..
              }) => {
                  NameImport::ImportFrom(MemberNameImport {
                      module: module.as_ref().map(std::string::ToString::to_string),
                      name: ruff_python_semantic::Alias {
                          name: alias.name.to_string(),
                          as_name: None,
                      },
                      level: *level,
                  })
              }
              ruff_python_ast::Stmt::Import(_) => {
                  NameImport::Import(ModuleNameImport {
                      name: ruff_python_semantic::Alias {
                          name: alias.name.to_string(),
                          as_name: None,
                      },
                  })

              }
              _ => return false,
          };
                  checker
                      .settings()
                      .isort
                      .required_imports
                      .contains(&name_import)
}
```

modulo the horrific formatting from me editing this on GitHub and with a real function name and arguments.

**Review by ntBre — COMMENTED** [review]
Thanks! I had one suggestion to refactor the fix here, and we should also add a test. Since the fix is on the UP010 side, I think it would make sense to add a unit test in the `pyupgrade` module too. You should be able to select both rules and use the normal snapshot infrastructure otherwise.

**Comment by danparizher** [comment]
Thanks, I extracted that as a function and also added a check into `crates\ruff_linter\src\rules\pyupgrade\rules\deprecated_import.rs`. Let me know if that's correct. For adding tests for the whole `pyupgrade` module, what would that look like? Would appreciate recommendations

File: crates/ruff_linter/src/rules/pyupgrade/rules/unnecessary_future_import.rs [hunk 2]
```diff
@@ -85,51 +85,48 @@ const PY37_PLUS_REMOVE_FUTURES: &[&str] = &[
     "generator_stop",
 ];
 
+pub(crate) fn is_import_required_by_isort(checker: &Checker, stmt: &Stmt, alias: &Alias) -> bool {
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/pyupgrade/rules/unnecessary_future_import.rs]: I think we could pass a `StmtRef` here and avoid the clone in UP035.

File: crates/ruff_linter/src/rules/pyupgrade/rules/deprecated_import.rs [hunk 3]
```diff
@@ -719,6 +720,12 @@ pub(crate) fn deprecated_import(checker: &Checker, import_from_stmt: &StmtImport
         return;
     }
 
+    for alias in &import_from_stmt.names {
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/pyupgrade/rules/deprecated_import.rs]: I'm not totally sure, but this feels like it could be overly restrictive. This should be equivalent to:

```rust
    if import_from_stmt.names.iter().any(|alias| {
        is_import_required_by_isort(checker, StmtRef::ImportFrom(import_from_stmt), alias)
    }) {
        return;
    }
```

and I'm wondering if `all` might be the better condition than `any`. In terms of a test case, I tried this:

```rust
    #[test]
    fn i002_conflict() {
        let diagnostics = test_snippet(
            "from pipes import quote, Template",
            &settings::LinterSettings {
                isort: isort::settings::Settings {
                    required_imports: BTreeSet::from_iter([
                        // https://github.com/astral-sh/ruff/issues/18729
                        NameImport::ImportFrom(MemberNameImport::member(
                            "__future__".to_string(),
                            "generator_stop".to_string(),
                        )),
                        // https://github.com/astral-sh/ruff/issues/16802
                        NameImport::ImportFrom(MemberNameImport::member(
                            "collections".to_string(),
                            "Sequence".to_string(),
                        )),
                        // Only bail out if _all_ the names in UP035 are required. `pipes.Template`
                        // isn't flagged by UP035, so requiring it shouldn't prevent `pipes.quote`
                        // from getting a diagnostic.
                        NameImport::ImportFrom(MemberNameImport::member(
                            "pipes".to_string(),
                            "Template".to_string(),
                        )),
                    ]),
                    ..Default::default()
                },
                ..settings::LinterSettings::for_rules([
                    Rule::MissingRequiredImport,
                    Rule::UnnecessaryFutureImport,
                    Rule::DeprecatedImport,
                ])
            },
        );
        assert_diagnostics!(diagnostics, @r"
        <filename>:1:1: UP035 [*] Import from `shlex` instead: `quote`
          |
        1 | from pipes import quote, Template
          | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ UP035
          |
          = help: Import from `shlex`

        ℹ Safe fix
        1   |-from pipes import quote, Template
          1 |+from pipes import Template
          2 |+from shlex import quote

        <filename>:1:1: I002 [*] Missing required import: `from __future__ import generator_stop`
        ℹ Safe fix
          1 |+from __future__ import generator_stop
        1 2 | from pipes import quote, Template

        <filename>:1:1: I002 [*] Missing required import: `from collections import Sequence`
        ℹ Safe fix
          1 |+from collections import Sequence
        1 2 | from pipes import quote, Template
        ");
    }
```

after switching to `all`. I think it makes sense to flag `quote` even if `Template` is required. What do  you think?

I think that's consistent with the `continue` instead of `return` in UP010.

Comment (ntBre) [reply crates/ruff_linter/src/rules/pyupgrade/rules/deprecated_import.rs]: Actually, this may just not be the right place to inject the check. Somewhere in here we should actually inspect the `alias` being replaced. That might be the more natural place to check `is_import_required_by_isort`.

Comment (danparizher) [reply crates/ruff_linter/src/rules/pyupgrade/rules/deprecated_import.rs]: I think the `continue` approach makes the most sense. I envision collecting skipped aliases and filtering them out during processing. Feel free to iterate on the commit how you see fit. 🙂

**Comment by ntBre** [comment]
I pushed a few changes:
- Stored the required imports on `ImportReplacer` instead of a `HashSet` so we can avoid allocating that up front
- Pushed to `unmatched_names` instead of continuing in `partition_imports` (this was causing the `from pipes import Template` import to be dropped when removing the `quote` import)
- Combined `i002_conflict` and `up035_partial_required_import`, that's what I had in mind initially. I don't think we need both tests separately
- Tried to simplify `is_import_required_by_isort` a bit

I'm not sure if the simplification actually paid off. It seems nice not to allocate strings for the `NameImport`s, but now we have to call `qualified_name` repeatedly in the `any` check. Your version wasn't showing any performance regression, so if this regresses performance at all, I'll just put it back.
