### PR TITLE
[`pyupgrade`] Better messages and diagnostic range (`UP015`)

### LINKED ISSUE #15863: `UP015`'s range and message are slightly incorrect
Minimal reproducible example ([playground](https://play.ruff.rs/b66038dc-2266-4210-b181-6487d53a44f2)):

```python
open(
    '.txt',
    'r'
)
```

<pre><code>$ ruff check --isolated --select <a href="https://docs.astral.sh/ruff/rules/redundant-open-modes/">UP015</a>
.py:1:1: UP015 [*] Unnecessary open mode parameters
  |
1 | / open(
2 | |     '.txt',
3 | |     'r'
4 | | )
  | |_^ UP015
  |
  = help: Remove open mode parameters

Found 1 error.
[*] 1 fixable with the `--fix` option.
</code></pre>

There is only one `mode` parameter, and the value passed to that parameter is called an <em>argument</em>. Additionally, the range is much wider than is necessary; it should cover that argument but nothing else.

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
## Summary

Resolves #15863.

In preview, diagnostic ranges will now be limited to that of the argument. Rule documentation, variable names, error messages and fix titles have all been modified to use "argument" consistently.

## Test Plan

`cargo nextest run` and `cargo insta test`.

### CODE REVIEW

File: crates/ruff_linter/src/rules/pyupgrade/rules/redundant_open_modes.rs [hunk 1]
```diff
@@ -40,18 +39,18 @@ impl AlwaysFixableViolation for RedundantOpenModes {
     fn message(&self) -> String {
         let RedundantOpenModes { replacement } = self;
         if replacement.is_empty() {
-            "Unnecessary open mode parameters".to_string()
+            "Unnecessary open mode argument".to_string()
         } else {
-            format!("Unnecessary open mode parameters, use \"{replacement}\"")
+            format!("Unnecessary open modes, use `{replacement}`")
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pyupgrade/rules/redundant_open_modes.rs:44]:
```suggestion
            format!("Unnecessary open mode argument, use `{replacement}`")
```

Should we use the singular form here too or are there cases where there are multiple possible open modes?

File: crates/ruff_linter/src/rules/pyupgrade/rules/redundant_open_modes.rs [hunk 2]
```diff
@@ -71,68 +70,71 @@ pub(crate) fn redundant_open_modes(checker: &mut Checker, call: &ast::ExprCall)
...
-fn create_remove_param_fix(
+fn create_remove_argument_fix(
     call: &ast::ExprCall,
-    mode_param: &Expr,
+    mode_arg: &Expr,
     tokens: &Tokens,
 ) -> Result<Edit> {
-    // Find the last comma before mode_param and create a deletion fix
-    // starting from the comma and ending after mode_param.
+    // Find the last comma before mode_arg and create a deletion fix
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pyupgrade/rules/redundant_open_modes.rs:129]: Maybe for another PR, should this use our generic `remove_argument` helper instead of rolling its own function for this?

File: crates/ruff_linter/src/rules/pyupgrade/rules/redundant_open_modes.rs [hunk 3]
```diff
@@ -40,18 +39,18 @@ impl AlwaysFixableViolation for RedundantOpenModes {
...
-            format!("Unnecessary open mode parameters, use \"{replacement}\"")
+            format!("Unnecessary open modes, use `{replacement}`")
         }
     }
 
     fn fix_title(&self) -> String {
         let RedundantOpenModes { replacement } = self;
         if replacement.is_empty() {
-            "Remove open mode parameters".to_string()
+            "Remove open mode argument".to_string()
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pyupgrade/rules/redundant_open_modes.rs:51]: I find the `open mode` hard to read. Maybe simplify to "Remove `mode` argument"

**Review by MichaReiser — APPROVED** [review]
Thanks. A few small nits but overall this looks good

File: crates/ruff_linter/src/rules/pyupgrade/rules/redundant_open_modes.rs (hunk 1 above)
Comment (MichaReiser) [reply crates/ruff_linter/src/rules/pyupgrade/rules/redundant_open_modes.rs]: That's fair. I still think singular makes sense here because even with `rb`, there's only a single `mode` argument (the mode might be multiple characters but it's always a single argument)

Comment (MichaReiser) [reply crates/ruff_linter/src/rules/pyupgrade/rules/redundant_open_modes.rs]: I'm then leaning towards removing the `argument` everywhere and instead just use `Unnecessary open mode, use {replacement}`

Comment (MichaReiser) [reply crates/ruff_linter/src/rules/pyupgrade/rules/redundant_open_modes.rs]: That's what I had in mind, based on your explanation but please let me know if you've concerns. I'm sure you know the rule much better by now than I do

**Review by MichaReiser — APPROVED** [review]
