### PR TITLE
[`red-knot`] Allow subclasses of Any to be assignable to Callable types

### LINKED ISSUE #17701: [red-knot] Subclasses of Any should be assignable to `Callable`
Subclasses of `Any` should be assignable to `Callable`. This should not be an error:

```py
from typing import Callable, Any


class MyMock(Any):
    pass

def f(c: Callable):
    c()

f(MyMock())  # Argument to this function is incorrect: Expected `(...) -> Unknown`, found `MyMock`
```
(https://types.ruff.rs/e0ded89d-526c-430e-a9c5-d02b8945f81d)

### PR DESCRIPTION
**Pull request by Kalmaegi**
## Summary

Fixes #17701. I'm uncertain whether this Python code needs to be added to the test cases. I'd be happy to supplement it if needed.

### CODE REVIEW

File: crates/red_knot_python_semantic/src/types.rs [hunk 1]
```diff
@@ -1288,6 +1288,12 @@ impl<'db> Type<'db> {
     ///
     /// [assignable to]: https://typing.python.org/en/latest/spec/concepts.html#the-assignable-to-or-consistent-subtyping-relation
     pub(crate) fn is_assignable_to(self, db: &'db dyn Db, target: Type<'db>) -> bool {
+        // PEP 484: Any and its subclasses are assignable to all types.
```
Comment (carljm) [inline crates/red_knot_python_semantic/src/types.rs:1291]: The typing spec does not specify the behavior of subclassing `Any`, it just says it should be possible. And PEP 484 is a historical document, not an authoritative source (and it also doesn't mention subclassing `Any`). So there is no simple statement from authority that we are following here. Rather, we are following the "core concepts" section of the typing spec, and reasoning from that basis. The `Any` that is inherited can be "materialized" to any type, therefore `C` (where `class C(Any): ...`) is assignable to non-final types, because that `Any` could "materialize" to any non-final type. But it is not assignable to final types, because that `Any` cannot materialize to a final type (it would lead to an invalid inheritance from a final type.) Similar logic applies to literal types; there is no possible type that the `Any` in `class C(Any): ...` could materialize to, which would make an instance of `C` assignable, to, e.g., a `Literal` type.

**Review by carljm — CHANGES_REQUESTED** [review]
Thanks for the PR!

As @sharkdp mentioned on the issue, there should be some exceptions here. One of those exceptions (subclass of `Any` can't be a subclass of a final class) we already have a test for, which is causing the tests to fail on this PR. I think all literal types should also be excluded (an instance of an `Any` subclass can't possibly inhabit `Literal[1]` or any other literal type).

I am not 100% sure that a separate catchall check at the top of the function will still be the clearest implementation here, once we account for all the exceptions. It depends on the balance of how many types we have to carve out of this catchall, vs how many we'd have to add a dedicated check for inheritance-from-Any to.

And yes, Python code samples should be added to the mdtests in this PR demonstrating the cases we want to handle that were not previously handled.

File: crates/red_knot_python_semantic/src/types.rs (hunk 1 above)
Comment (Kalmaegi) [reply crates/red_knot_python_semantic/src/types.rs]: Thank you very much! I thought we needed to link a rule here XD.

**Comment by Kalmaegi** [comment]
> Thanks for the PR!
> 
> As @sharkdp mentioned on the issue, there should be some exceptions here. One of those exceptions (subclass of `Any` can't be a subclass of a final class) we already have a test for, which is causing the tests to fail on this PR. I think all literal types should also be excluded (an instance of an `Any` subclass can't possibly inhabit `Literal[1]` or any other literal type).
> 
> I am not 100% sure that a separate catchall check at the top of the function will still be the clearest implementation here, once we account for all the exceptions. It depends on the balance of how many types we have to carve out of this catchall, vs how many we'd have to add a dedicated check for inheritance-from-Any to.
> 
> And yes, Python code samples should be added to the mdtests in this PR demonstrating the cases we want to handle that were not previously handled.

I checked for existing tests and found that assignments from Any to both Final and Literal are already covered. I just added a test for the Callable case.
I haven’t found other cases that need special handling for now—just these two. Since we’re checking `self ` at the start of the method, I think this placement works reasonably well XD

**Comment by Kalmaegi** [comment]
> > I checked for existing tests and found that assignments from Any to both Final and Literal are already covered.
> 
> Where do we cover assignments to literals? It looks like it is possibly to assign to a literal on your branch. You will need a test that makes sure that instances of `Subclass(Any)` are not assignable to something like `Literal[1]`:
> 
> ```python
> from typing import Any, Literal
> 
> class C(Any):
>     pass
> 
> x: Literal[1] = C()  # this should fail, but does not on your branch.
> ```
> 
> As @carljm mentioned, it might be better to follow a "opt in" strategy, i.e. to handle special cases to the existing match statement. This way, we make sure that we exhaustively handle all type variants; and that we properly treat union and intersection types. For example:
> 
> ```python
> from typing import final, Any
> 
> @final
> class F1: ...
> 
> @final
> class F2: ...
> 
> class Subclass(Any): ...
> 
> f: F1 | F2 = Subclass()  # this should fail, but does not on your branch.
> ```

Ah, sorry about that—I misread the test. I’ll update the code accordingly.

**Review by sharkdp — APPROVED** [review]
@Kalmaegi I didn't really see any evidence in the newly added tests here that we need the catch-all case. In fact, there were some new ecosystem false-positives that looked incorrect (see below). It might be that we're still missing some cases where we should allow assignability, but until then, I'd rather be conservative and only allow assignability to `Callable` specifically. I changed the code to reflect this, hope that's fine for you. These false positives are now gone after the update:
```diff
pytest-robotframework (https://github.com/detachhead/pytest-robotframework)
+ error[lint:invalid-argument-type] pytest_robotframework/_internal/pytest/plugin.py:374:26: Argument to this function is incorrect: Expected `PytestRuntestProtocolHooks`, found `PytestRuntestProtocolHooks`
- Found 322 diagnostics
+ Found 323 diagnostics

mypy-protobuf (https://github.com/dropbox/mypy-protobuf)
+ error[lint:invalid-argument-type] mypy_protobuf/main.py:134:64: Argument to this function is incorrect: Expected `FileDescriptorProto`, found `FileDescriptorProto`
+ error[lint:invalid-argument-type] mypy_protobuf/main.py:135:59: Argument to this function is incorrect: Expected `FileDescriptorProto`, found `FileDescriptorProto`
+ error[lint:invalid-argument-type] mypy_protobuf/main.py:941:22: Argument to this function is incorrect: Expected `FieldDescriptorProto`, found `FieldDescriptorProto`
```

Thank you for working on this.

**Comment by Kalmaegi** [comment]
> @Kalmaegi I didn't really see any evidence in the newly added tests here that we need the catch-all case. In fact, there were some new ecosystem false-positives that looked incorrect (see below). It might be that we're still missing some cases where we should allow assignability, but until then, I'd rather be conservative and only allow assignability to `Callable` specifically. I changed the code to reflect this, hope that's fine for you. These false positives are now gone after the update:
> 
> ```diff
> pytest-robotframework (https://github.com/detachhead/pytest-robotframework)
> + error[lint:invalid-argument-type] pytest_robotframework/_internal/pytest/plugin.py:374:26: Argument to this function is incorrect: Expected `PytestRuntestProtocolHooks`, found `PytestRuntestProtocolHooks`
> - Found 322 diagnostics
> + Found 323 diagnostics
> 
> mypy-protobuf (https://github.com/dropbox/mypy-protobuf)
> + error[lint:invalid-argument-type] mypy_protobuf/main.py:134:64: Argument to this function is incorrect: Expected `FileDescriptorProto`, found `FileDescriptorProto`
> + error[lint:invalid-argument-type] mypy_protobuf/main.py:135:59: Argument to this function is incorrect: Expected `FileDescriptorProto`, found `FileDescriptorProto`
> + error[lint:invalid-argument-type] mypy_protobuf/main.py:941:22: Argument to this function is incorrect: Expected `FieldDescriptorProto`, found `FieldDescriptorProto`
> ```
> 
> Thank you for working on this.

@sharkdp Thank you so much for your help. I'm still familiarizing myself with the project structure, so some of my ideas might be a bit rudimentary.
