### PR TITLE
[`flake8-datetimez`] Usages of `datetime.max`/`datetime.min` (`DTZ901`)

### LINKED ISSUE #13217: Report DTZ violation on `datetime.datetime.max` and `min`
Currently, ruff is properly detecting most cases where a `datetime` object is used without a timezone info, however, it does not report the use of `datetime.max` or `datetime.min`, which are constants that don't have a timezone set, which could end up causing pretty annoying and confusing issues.

One example that I've recently ran into:

```python
from datetime import datetime

MAX_TIME = datetime.max.timestamp()  # ValueError: year 10000 is out of range
```

This happens because the datetime here was blindly constructed with no tz info to be: `datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)`, however, my timezone is UTC+2, and timestamp is always calculated in UTC, yet the overflow check there is just numeric for the 10k year. This means I end up having my `datetime.max` over the max UTC timestamp by 2 hours. What people should instead do here is something like: `datetime.max.replace(tzinfo=UTC)`.

In my case, I was able to catch this quickly, because of the exception, however, for people with timezones that are smaller than UTC, rather than bigger, they wouldn't even notice something like this and it could lead to inconsistencies in the max timestamps.

It might therefore be worth it to have ruff report the use of these constants without `replace`, with a new DTZ rule.

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
## Summary

Resolves #13217.

## Test Plan

`cargo nextest run` and `cargo insta test`.

### CODE REVIEW

File: crates/ruff_linter/src/rules/flake8_datetimez/rules/datetime_max_min.rs [hunk 1]
```diff
@@ -0,0 +1,120 @@
...
+        return;
+    }
+
+    let diagnostic = Diagnostic::new(DatetimeMaxMin(maxmin), expr.range());
+
+    checker.diagnostics.push(diagnostic);
+}
+
+/// Check if the current expression has the pattern `foo.replace(tzinfo=bar)`.
+pub(super) fn followed_by_replace_tzinfo(checker: &Checker) -> bool {
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_datetimez/rules/datetime_max_min.rs:104]:
```suggestion
pub(super) fn followed_by_replace_tzinfo(semantic: &SemanticModel -> bool {
```

File: crates/ruff_linter/src/codes.rs [hunk 2]
```diff
@@ -706,6 +706,7 @@ pub fn code_to_rule(linter: Linter, code: &str) -> Option<(RuleGroup, Rule)> {
         (Flake8Datetimez, "007") => (RuleGroup::Stable, rules::flake8_datetimez::rules::CallDatetimeStrptimeWithoutZone),
         (Flake8Datetimez, "011") => (RuleGroup::Stable, rules::flake8_datetimez::rules::CallDateToday),
         (Flake8Datetimez, "012") => (RuleGroup::Stable, rules::flake8_datetimez::rules::CallDateFromtimestamp),
+        (Flake8Datetimez, "901") => (RuleGroup::Preview, rules::flake8_datetimez::rules::DatetimeMaxMin),
```
Comment (MichaReiser) [inline crates/ruff_linter/src/codes.rs:709]: I assume the reason for using `9XX` is to make it clear that this isn't an upstream rule?
