### PR TITLE
[ty] Guard recursive protocol signature comparisons

### LINKED ISSUE #3208: Infinite loop/hang with generic Protocol whose methods return self-type with different wrapped type parameters
### Summary

ty hangs indefinitely when checking a generic Protocol that has two methods returning the same Protocol with differently-wrapped type parameters, where one method lazily imports a subclass.

This is likely a variant of #1736 that evades the cycle detection fix — instead of a single recursive wrapper producing `C[set[set[set[...]]]]`, two different wrappers (`Tagged` and `Wrapped`) produce a new type pair at each recursion step.

### How to reproduce

Four files. Run `ty check --project . src/pkg/config.py` from the project root.

`pyproject.toml`:
```toml
[project]
name = "repro"
version = "0.0.1"
requires-python = ">=3.12"
```

`src/pkg/__init__.py`: empty

`src/pkg/base.py`:
```python
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Protocol


class Base[I, O](ABC):
    @abstractmethod
    async def run(self, input: I) -> O: ...


class BaseFactory[I, O](Protocol):
    async def create(self) -> Base[I, O]: ...


@dataclass(frozen=True)
class Tagged[T, U, V]:
    value: T


@dataclass(frozen=True)
class Wrapped[T]:
    inner: T
```

`src/pkg/config.py`:
```python
from typing import Protocol
from pkg.base import Base, BaseFactory, Tagged, Wrapped


class Impl[I, O](Base[I, O]):
    async def run(self, input: I) -> O:
        raise NotImplementedError


class Factory[I, O](BaseFactory[I, O], Protocol):
    async def create(self) -> Impl[I, O]: ...

    def tag[U, V](self) -> "Factory[Tagged[I, U, V], O]":
        from pkg.wrapper import TaggedFactory
        return TaggedFactory(inner=self)  # type: ignore

    def wrap(self) -> "Factory[Wrapped[I], O]": ...
```

`src/pkg/wrapper.py`:
```python
from dataclasses import dataclass
from pkg.config import Factory, Impl


@dataclass
class TaggedFactory[I, O, U, V](Factory["Tagged[I, U, V]", O]):
    inner: Factory[I, O]

    async def create(self) -> Impl["Tagged[I, U, V]", O]:
        raise NotImplementedError
```

### Notes

Removing any one of these makes ty complete normally:

- The `wrap()` stub method (even though it has no body)
- The `tag()` method body (keeping just `...`)
- The `BaseFactory` base class (or changing `create()` to return `None` instead of `Base[I, O]`)
- The narrowed return type on `Factory.create()` (i.e., returning `Base` instead of `Impl`)

### Version

ty 0.0.28

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

This PR adds a recursion guard for signature comparisons (keyed by (source definition, target definition, relation)), used to prevent a stack overflow in structural protocol matching. Previously, recursive protocols would just recurse with a new specialization; now, we assume success when we see the same pair in a single check, and continue from there.

Closes https://github.com/astral-sh/ty/issues/3208.

### CODE REVIEW

File: crates/ty_python_semantic/src/types/signatures.rs [hunk 1]
```diff
@@ -1190,6 +1224,20 @@ impl<'c, 'db> TypeRelationChecker<'_, 'c, 'db> {
...
+        source: &Signature<'db>,
+        target: &Signature<'db>,
+        work: impl FnOnce() -> ConstraintSet<'db, 'c>,
+    ) -> ConstraintSet<'db, 'c> {
+        let Some(key) = SignatureRelationKey::from_signatures(source, target, self.relation) else {
+            return work();
+        };
+
+        self.signature_relation_visitor
+            .visit(&key, || self.always(), work)
```
Comment (ibraheemdev) [inline crates/ty_python_semantic/src/types/signatures.rs:1262]: This seems to be the most critical part of this PR, might be worth adding some comments here regarding why `self.always()` is correct as the cycle initial value (it is correct, I think).

**Review by ibraheemdev — APPROVED** [review]
This makes sense to me.
