### PR TITLE
[`refurb`] Avoid `None | None` as well as better detection and fix (`FURB168`)

### LINKED ISSUE #15776: FURB168 false negative and false positives
### Description

[`isinstance-type-none` (FURB168)](https://docs.astral.sh/ruff/rules/isinstance-type-none/) has a false negative and two false positives in Ruff 0.9.3.

The rule only triggers when the first argument to `isinstance` is an identifier. This is a false negative because any expression would work in that context.
```console
$ cat >furb168_1.py <<'#EOF'
d = {"x": 1}
print(isinstance(d.get("x"), type(None)))
#EOF

$ python furb168_1.py
False

$ ruff --isolated check --preview --select FURB168 furb168_1.py
All checks passed!
```
If the expression consists purely of certain literals and operators, like `1 + 1`, applying the FURB168 fix would produce a warning like `SyntaxWarning: "is" with 'int' literal. Did you mean "=="?`. That might be a reason the rule is currently so restricted, but I think it is better to apply the fix: the code is suspect either way but at least with the fix the user gets an explicit warning.

The first false positive is that the rule does not check whether `type` is the built-in `type`. (It does correctly check `isinstance`.)
```console
$ cat >furb168_2.py <<'#EOF'
def type(x):
    return int
i = 1
print(isinstance(i, type(None)))
#EOF

$ python furb168_2.py
True

$ ruff --isolated check --preview --select FURB168 furb168_2.py --fix
Found 1 error (1 fixed, 0 remaining).

$ cat furb168_2.py
def type(x):
    return int
i = 1
print(i is None)

$ python furb168_2.py
False
```

The second false positive is that `None | None` is accepted as meaning `type(None)`. That raises a `TypeError` which the fix suppresses.
```
$ cat >furb168_3.py <<'#EOF'
print(isinstance(abs, None | None))
#EOF

$ python furb168_3.py
Traceback (most recent call last):
  File "furb168_3.py", line 1, in <module>
    print(isinstance(abs, None | None))
                          ~~~~~^~~~~~
TypeError: unsupported operand type(s) for |: 'NoneType' and 'NoneType'

$ ruff --isolated check --preview --select FURB168 furb168_3.py --fix
Found 1 error (1 fixed, 0 remaining).

$ python furb168_3.py
False
```

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
## Summary

Resolves #15776.

The rule has been rewritten to address the problems discussed at the aforementioned issue. Additionally, `Union[]` is now detected and the fix marked as unsafe if there are any comments in the range.

## Test Plan

`cargo nextest run` and `cargo insta test`.

### CODE REVIEW

File: crates/ruff_linter/src/rules/refurb/rules/isinstance_type_none.rs [hunk 1]
```diff
@@ -88,29 +85,63 @@ fn is_none(expr: &Expr) -> bool {
...
-                    if id.as_str() == "type" {
-                        return matches!(arguments.args.first(), Some(Expr::NoneLiteral(_)));
-                    }
+            }) => {
+                if !semantic.match_builtin_expr(func, "type") {
+                    return false;
                 }
-                false
+
+                matches!(arguments.args.as_ref(), [Expr::NoneLiteral(_)])
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/refurb/rules/isinstance_type_none.rs:93]: I think we should probably also check that `arguments.keywords.is_empty()`

File: crates/ruff_linter/src/rules/refurb/rules/isinstance_type_none.rs [hunk 2]
```diff
@@ -88,29 +85,63 @@ fn is_none(expr: &Expr) -> bool {
...
 
             // Otherwise, return false.
             _ => false,
         }
     }
-    inner(expr, false)
+    inner(expr, false, semantic)
+}
+
+fn replace_with_identity_check(expr: &Expr, range: TextRange, checker: &mut Checker) -> Fix {
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/refurb/rules/isinstance_type_none.rs:121]: This doesn't need to be `&mut`, since you don't use any methods on `Checker` in this function that require a mutable reference

```suggestion
fn replace_with_identity_check(expr: &Expr, range: TextRange, checker: &Checker) -> Fix {
```

File: crates/ruff_linter/src/rules/refurb/rules/isinstance_type_none.rs [hunk 3]
```diff
@@ -88,29 +85,63 @@ fn is_none(expr: &Expr) -> bool {
...
+        comparators: [ast::ExprNoneLiteral::default().into()].into(),
+        range: TextRange::default(),
+    });
+
+    let new_content = generator.expr(&new_expr);
+    let new_content = if semantic.current_expression_parent().is_some() {
+        format!("({new_content})")
+    } else {
+        new_content
+    };
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/refurb/rules/isinstance_type_none.rs:136]: Using the generator seems overkill for this. Couldn't we just do it like this?

```suggestion
    let semantic = checker.semantic();
    let lhs_source = &checker.source()[expr.range()];

    let new_content = if semantic.current_expression_parent().is_some() {
        format!("({lhs_source} is None)")
    } else {
        format!("{lhs_source} is None")
    };
```

File: crates/ruff_linter/src/rules/refurb/rules/isinstance_type_none.rs [hunk 4]
```diff
@@ -88,29 +85,63 @@ fn is_none(expr: &Expr) -> bool {
...
                 ..
-            }) => inner(left, true) && inner(right, true),
+            }) => {
+                // `None | None` is a `TypeError` at runtime
+                if left.is_none_literal_expr() && right.is_none_literal_expr() {
+                    return false;
+                }
+
+                inner(left, true, semantic) && inner(right, true, semantic)
+            }
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/refurb/rules/isinstance_type_none.rs:112]: I think the implication of https://github.com/astral-sh/ruff/issues/15776 is really that we should _never_ emit this diagnostic for `isinstance()` used with PEP-604 unions including `None`. We don't want to emit a lint on this -- this rule is concerned with style, but there's a correctness error here:

```py
isinstance(x, None | None)`
```

But we also don't want to emit a lint on this, I don't think:

```py
isinstance(x, str | None)`
```

Because it isn't really a _simplification_ to rewrite that as

```py
isinstance(x, str) or x is None
```

But having said that, maybe we _should_ be emitting a lint on these (and we don't currently). They only work on Python 3.10+:

```py
from typing import Union

isinstance(x, Union[None])
isinstance(x, Union[None, None])
```

It's unlikely that anybody would write those kinds of things deliberately, but I could easily see them being produced by codemod tools or code-generation tools.

**Review by AlexWaygood — COMMENTED** [review]
Thank you!

File: crates/ruff_linter/src/rules/refurb/rules/isinstance_type_none.rs [hunk 5]
```diff
@@ -88,29 +85,81 @@ fn is_none(expr: &Expr) -> bool {
...
+        format!("({new_content})")
+    } else {
+        new_content
+    };
+
+    let applicability = if checker.comment_ranges().intersects(range) {
+        Applicability::Unsafe
+    } else {
+        Applicability::Safe
+    };
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/refurb/rules/isinstance_type_none.rs:160]: Please could you add a `## Fix safety` section to the docs stating why the fix is sometimes marked as unsafe?

**Review by AlexWaygood — APPROVED** [review]
thanks!
