### PR TITLE
Fix `''' ""'''` formatting

### LINKED ISSUE #7460: Formatter instability: String normalization inserts whitespace
## Input

```python
value_text  = ''' value=""'''
```

## Format 1
Which gets normalized to which isn't the same as the input

```python
value_text = """ value="""""
```

## Format 2
Inserts a space between the implicit concatenated strings

```python
value_text = """ value=""" ""
```

The real issue is why the string gets normalized to `Format 1`, It should keep the single quotes.

Sourced by #7445

### PR DESCRIPTION
**Pull request by konstin**
## Summary

`''' ""'''` is an edge case that was previously incorrectly formatted as `""" """""`.

Fixes #7460

## Test Plan

Added regression test

### CODE REVIEW

File: crates/ruff_python_formatter/src/expression/string.rs [hunk 1]
```diff
@@ -543,10 +543,17 @@ fn preferred_quotes(
...
+                                Some(c) if c == configured_quote_char => {
+                                    // `"""` or `'''`
+                                    chars.next();
+                                    uses_triple_quotes = true;
+                                }
+                                Some(_) => {}
+                                None => {
+                                    // Handle `''' ""'''`
+                                    uses_triple_quotes = true;
+                                }
```
Comment (MichaReiser) [inline crates/ruff_python_formatter/src/expression/string.rs:556]: Can you explain the fix? 

I'm asking because I would expect `preferred_quotes` to return single here because it contains two `"`... Changing the quotes to `"` would require two escapes... which is more than when keeping the single quotes.

File: crates/ruff_python_formatter/src/expression/string.rs [hunk 2]
```diff
@@ -543,10 +543,17 @@ fn preferred_quotes(
...
 
-                            if chars.peek().copied() == Some(configured_quote_char) {
-                                // `"""` or `'''`
-                                chars.next();
-                                uses_triple_quotes = true;
+                            match chars.peek().copied() {
+                                Some(c) if c == configured_quote_char => {
+                                    // `"""` or `'''`
+                                    chars.next();
+                                    uses_triple_quotes = true;
```
Comment (MichaReiser) [inline crates/ruff_python_formatter/src/expression/string.rs:550]: Nit: We should break when setting `uses_triple_quotes`
