### PR TITLE
[red-knot] detect unreachable attribute assignments

### LINKED ISSUE #15967: [red-knot] Detect unreachable attributes assignments
This is probably not a high-priority feature, but it would be great if we could detect attribute assignments in unreachable code sections, and eliminate them from the set of possible answers:

```py
class C:
    def __init__(self) -> None:
        if True:
            self.x = 1
        else:
            self.x = "a"

        return

        self.y = "unreachable"

reveal_type(C().x)  # should be `Unknown | Literal[1]` (i.e. not include `Literal["a"]`)

# Should be an error:
C().y
```

Note that we have one existing test for this here:

https://github.com/astral-sh/ruff/blob/16f2a93fca20082179df082bc16a2c5095933772/crates/red_knot_python_semantic/resources/mdtest/attributes.md?plain=1#L434-L448

### PR DESCRIPTION
**Pull request by mtshiba**
## Summary

This PR closes #15967.

Attribute assignments that are statically known to be unreachable are excluded from consideration for implicit instance attribute type inference. If none of the assignments are found to be reachable, an `unresolved-attribute` error is reported.

## Test Plan

[A test case](https://github.com/astral-sh/ruff/blob/main/crates/red_knot_python_semantic/resources/mdtest/attributes.md#attributes-defined-in-statically-known-to-be-false-branches) marked as TODO now work as intended, and new test cases have been added.

### CODE REVIEW

File: crates/red_knot_python_semantic/src/semantic_index.rs [hunk 1]
```diff
@@ -129,6 +144,9 @@ pub(crate) struct SemanticIndex<'db> {
     /// List of all symbol tables in this file, indexed by scope.
     symbol_tables: IndexVec<FileScopeId, Arc<SymbolTable>>,
 
+    /// List of all instance attribute tables in this file, indexed by scope.
+    instance_attribute_tables: IndexVec<FileScopeId, Arc<SymbolTable>>,
+
```
Comment (MichaReiser) [inline crates/red_knot_python_semantic/src/semantic_index.rs:149]: Would it be possible to store the additional state inside of `attribute_assignments`?

Comment (carljm) [reply crates/red_knot_python_semantic/src/semantic_index.rs:149]: I think it goes deeper than this. If we see an attribute assignment like `self.x = "foo"` in `__init__` method, the only symbol in the scope of `__init__` that is involved here is `self`. What we are newly tracking in this PR is the "symbol namespace" of "names assigned to `self` in methods". So it's not just tracking some existing symbol ID, we are creating a whole new symbol table for this new namespace, that before was not tracked at all. And we also add support to the use-def map so that we can track conditional visibility of these names as well.

It's a clever and interesting approach. Off the top of my head, I also wonder whether we need both the `attribute_assignments` map and the new `instance_attribute_tables`. It seems like the latter should be able to replace the former entirely, as we can just query the symbol table and the use-def map to get all assigned names?

Comment (carljm) [reply crates/red_knot_python_semantic/src/semantic_index.rs:149]: Would definitely be interested in @sharkdp's thoughts on this PR, as the author of the `instance_attributes` work.

Comment (carljm) [reply crates/red_knot_python_semantic/src/semantic_index.rs:149]: My main "a priori" concern with this PR would have been the cost of adding `instance_attribute_tables` to every scope, even though we only use it in some scopes. But codspeed says no regression; I guess the cost of an empty symbol table and empty extra set of symbol states in the use-def map is not that high?

Comment (mtshiba) [reply crates/red_knot_python_semantic/src/semantic_index.rs:149]: Yes, I thought that a new field were needed to track the visibility of instance attributes, but we can actually divert some existing structure. That is, we can add an empty definition to `UseDefMapBuilder::all_definitions` to make it publish a `ScopedDefinitionID`, which will correspond to the instance attribute assignment.
Since `self.x = 1` and `x = 1` are different things, we need to have them as different symbol states from `symbol_states/public_symbols`, and in addition, the (reachable) instance attributes must remain visible after the method is returned since they are accessible from the outside.

As you say, the essence of this PR is the addition of states to manage instance attributes.
It was not needed in this PR, but if we want to do more analysis for instance attributes in the future, we may need to add a new variant representing attribute assignment to `DefinitionKind` instead of adding an empty definition to `all_definitions`.

File: crates/red_knot_python_semantic/src/semantic_index/use_def.rs [hunk 2]
```diff
@@ -391,6 +403,23 @@ impl<'db> UseDefMap<'db> {
...
+        &self,
+        db: &dyn crate::Db,
+        symbol: ScopedSymbolId,
+        id: ScopedDefinitionId,
+    ) -> Truthiness {
+        let visibility = self
+            .attribute_assignments(symbol)
+            .find_map(|bind| (id == bind.definition_id).then_some(bind.visibility_constraint));
+        let Some(visibility) = visibility else {
+            // Overwritten (e.g. `self.x = 1; self.x = 2`)
```
Comment (sharkdp) [inline crates/red_knot_python_semantic/src/semantic_index/use_def.rs:416]: This is an improvement that we should probably add a test for?

```py
class C:
    def __init__(self):
        self.x = 1
        self.x = "a"

reveal_type(C().x)
```

Previously, we would infer `Unknown | Literal[1, 2]` in that case, and now we infer the more correct `Unknown | Literal[2]`.

File: crates/red_knot_python_semantic/src/types/class.rs [hunk 3]
```diff
@@ -503,8 +503,22 @@ impl<'db> Class<'db> {
...
+
         for attribute_assignment in attribute_assignments {
-            match attribute_assignment {
+            let scope = attribute_assignment.assignment.scope(db);
+            let use_def = use_def_map(db, scope);
+            let table = instance_attribute_table(db, scope);
+            let symbol = table.symbol_id_by_name(name).unwrap();
+            if use_def
+                .is_attribute_assignment_visible(db, symbol, attribute_assignment.definition_id)
+                .is_always_false()
```
Comment (sharkdp) [inline crates/red_knot_python_semantic/src/types/class.rs:515]: The changes in this PR would probably also allow us to add a more fine-granular possibly-unbound handling for instance attributes. In a case like this …

```py
class C:
    def f(self, cond: bool):
        if cond:
            self.x = 1

C().x
```

… we could use the full return type of `is_attribute_assignment_visible` to see that `x` is not definitely bound.

Boundness of implicit instance instance attributes is treated a bit inconsistently at the moment. We treat them as always possibly-unbound in some situations (e.g. in the descriptor protocol implementation), since we don't (attempt to) understand if that method `f` has been called or not.

But on the other hand, we do not emit a possibly-unbound-attribute diagnostic in a case like above, because `f` *could* have been called. So we don't set an explicit `Boundness::PossiblyUnboud` state for implicit instance attributes, as that would lead to many false positive diagnostics.

I'm not sure if there is much value in adding a more sophisticated understanding, but it seems reasonable to emit a possibly-unbound-attribute diagnostic in the example above. Because even if `f` is called, `x` is still possibly-unbound.

File: crates/red_knot_python_semantic/src/semantic_index.rs (hunk 1 above)
Comment (sharkdp) [reply crates/red_knot_python_semantic/src/semantic_index.rs:149]: > Would definitely be interested in @sharkdp's thoughts on this PR, as the author of the instance_attributes work.

I also think this looks great, especially because it doesn't just solve the unreachable-attribute assignment case, but also allows us to distinguish between those two cases:
```py
self.x = 1
self.x = 2
```
and
```py
if cond:
    self.x = 1
else:
    self.x = 2
```


> Off the top of my head, I also wonder whether we need both the `attribute_assignments` map and the new `instance_attribute_tables`. It seems like the latter should be able to replace the former entirely, as we can just query the symbol table and the use-def map to get all assigned names?

I agree. I would be great if we could attempt to make that change in this PR.

**Comment by mtshiba** [comment]
While trying to solve the issue, I noticed that the following code does not pass:

```python
class C:
    def __init__(self):
        def closure():
            self.a: str = "a"
        closure()

C().a # should be OK
```

It appears that the `SemanticIndexBuilder::register_attribute_assignment` does not take closures into account.
I'm trying to fix this, but this may be an issue that should be resolved in another PR.

**Comment by mtshiba** [comment]
The commit I just made completely removes `SemanticIndex::attribute_assignments/AttributeAssignment`.
Attribute assignments are now stored in `SemanticIndex::all_definitions`.

I noticed that we can also track attribute assignments in comprehension/named/augmented assignments as well, so I will be working on that.

File: crates/red_knot_python_semantic/src/semantic_index.rs [hunk 4]
```diff
@@ -187,6 +192,10 @@ impl<'db> SemanticIndex<'db> {
         self.symbol_tables[scope_id].clone()
     }
 
+    pub(super) fn instance_attribute_table(&self, scope_id: FileScopeId) -> Arc<SymbolTable> {
```
Comment (MichaReiser) [inline crates/red_knot_python_semantic/src/semantic_index.rs:195]: The main motivation for using an `Arc` for the `SymbolTable` was so that we could return them from a salsa query that is specific per scope (instead of the entire `semantic_index`). However, it looks like no such query exists any more, so we should remove the `Arc` wrapper

File: crates/red_knot_python_semantic/src/types/class.rs [hunk 5]
```diff
@@ -28,6 +32,160 @@ use super::{
     TypeQualifiers, TypeVarInstance,
 };
 
+/// Tries to find declarations/bindings of an instance attribute named `name` that are only
+/// "implicitly" defined in a method of the class that corresponds to `class_body_scope`.
+#[allow(clippy::needless_pass_by_value)]
+#[salsa::tracked]
+fn implicit_instance_attribute<'db>(
```
Comment (MichaReiser) [inline crates/red_knot_python_semantic/src/types/class.rs:39]: What's the reason for moving this function out of `Class`? It makes the diff harder to review

File: crates/red_knot_python_semantic/src/types/class.rs [hunk 6]
```diff
@@ -28,6 +32,160 @@ use super::{
     TypeQualifiers, TypeVarInstance,
 };
 
+/// Tries to find declarations/bindings of an instance attribute named `name` that are only
+/// "implicitly" defined in a method of the class that corresponds to `class_body_scope`.
+#[allow(clippy::needless_pass_by_value)]
+#[salsa::tracked]
```
Comment (MichaReiser) [inline crates/red_knot_python_semantic/src/types/class.rs:38]: Have you investigated where the performance regression is coming from? 

I suspect that it is because this function is now a salsa query and its arguments are somewhat expensive (requires hashing and allocating a name). Gating the `attribute_assignments` and `is_attribute_assignment_visible` methods behind a query is important because they access `semantic_index` or `node`. However, it makes me wonder if we could change the methods so that they wouldn't have to depend on the entire `semantic_index` or access specific nodes.

File: crates/red_knot_python_semantic/src/types/class.rs [hunk 7]
```diff
@@ -28,6 +32,160 @@ use super::{
...
+fn implicit_instance_attribute<'db>(
+    db: &'db dyn Db,
+    class_body_scope: ScopeId<'db>,
+    name: Box<str>, // tracked functions do not accept a borrowed `str` with an implicit lifetime
```
Comment (MichaReiser) [inline crates/red_knot_python_semantic/src/types/class.rs:42]:
```suggestion
    name: Name, // tracked functions do not accept a borrowed `str` with an implicit lifetime
```

File: crates/red_knot_python_semantic/src/types/class.rs (hunk 6 above)
Comment (mtshiba) [reply crates/red_knot_python_semantic/src/types/class.rs]: Thanks. Initially I thought the performance regression was caused by removing `salsa::tracked` of `attribute_assignments`, but changing the field types of `{Assignment, ForStmt, WithItem}DefinitionKind` may be the true cause (there seems to be a regression with type inference on these).

File: crates/red_knot_python_semantic/src/types/class.rs (hunk 3 above)
Comment (sharkdp) [reply crates/red_knot_python_semantic/src/types/class.rs]: It looks like this leads to many new diagnostics in the ecosystem checks. Did you have a chance to investigate this?

Comment (mtshiba) [reply crates/red_knot_python_semantic/src/types/class.rs]: I found that the following code would result in a `possibly-unbound-attribute` warning.

* case 1: may loop forever in `__init__`

```python
from typing import Iterable

class Foo:
    def __init__(self, iterable: Iterable[int], cond: bool) -> None:
        self.x = 1

        # These loops may never stop
        for _ in iterable:
            pass
        while cond:
            pass

foo = Foo([], False)
# error: [possibly-unbound-attribute]
foo.x
```

* case 2: may throw an error in `__init__`

```python
class Foo:
    def __init__(self, b: bytes, cond: bool) -> None:
        try:
            s = b.decode()
        except UnicodeDecodeError:
            raise ValueError("Invalid UTF-8 sequence")
        if cond:
            raise ValueError("Something went wrong")

        self.s = s

foo = Foo(b"abc")
# error: [possibly-unbound-attribute]
foo.s
```

These are false positive warnings; when creating a `SemanticIndex`, it would be necessary to treat the recording of visibility for attribute assignments differently than for name assignments.

File: crates/red_knot_python_semantic/src/semantic_index.rs [hunk 8]
```diff
@@ -98,22 +96,30 @@ pub(crate) fn use_def_map<'db>(db: &'db dyn Db, scope: ScopeId<'db>) -> Arc<UseD
...
+    let class_scope_id = class_body_scope.file_scope_id(db);
+
+    DescendantsIter::new(index, class_scope_id)
+        .filter_map(move |(file_scope_id, maybe_method)| {
+            if maybe_method
+                .parent()
+                .is_none_or(|parent| parent != class_scope_id)
+            {
+                return None;
+            }
```
Comment (carljm) [inline crates/red_knot_python_semantic/src/semantic_index.rs:115]: This logic is already implemented as `ChildrenIter`, should we just use that instead of `DescendantsIter`?

(There's no efficiency improvement, the implementation of `ChildrenIter` is effectively the same, it just avoids re-implementing the logic.)

File: crates/red_knot_python_semantic/src/semantic_index.rs [hunk 9]
```diff
@@ -98,22 +96,30 @@ pub(crate) fn use_def_map<'db>(db: &'db dyn Db, scope: ScopeId<'db>) -> Arc<UseD
 }
 
 /// Returns all attribute assignments for a specific class body scope.
-///
-/// Using [`attribute_assignments`] over [`semantic_index`] has the advantage that
-/// Salsa can avoid invalidating dependent queries if this scope's instance attributes
-/// are unchanged.
-#[salsa::tracked]
-pub(crate) fn attribute_assignments<'db>(
+pub(crate) fn attribute_assignments<'db, 's>(
```
Comment (carljm) [inline crates/red_knot_python_semantic/src/semantic_index.rs:99]: We should probably mention in the doc comment for this function that calling it adopts a direct dependency on the AST of the file containing `class_body_scope`, since we access the semantic index for that file.
```suggestion
///
/// Only call this when doing type inference on the same file as `class_body_scope`, otherwise it
/// introduces a direct dependency on that file's AST.
pub(crate) fn attribute_assignments<'db, 's>(
```

File: crates/red_knot_python_semantic/src/semantic_index/builder.rs [hunk 10]
```diff
@@ -1893,19 +1909,83 @@ where
...
-                            attribute_expression_id: expression_id,
-                            unpack,
-                        },
-                    );
+                match self.current_assignment() {
+                    Some(CurrentAssignment::Assign { node, unpack, .. }) => {
+                        // SAFETY: `value` and `expr` belong to the `self.module` tree
+                        #[allow(unsafe_code)]
+                        let assignment = AssignmentDefinitionKind::new(
+                            TargetKind::from(unpack),
```
Comment (carljm) [inline crates/red_knot_python_semantic/src/semantic_index/builder.rs:1917]: In this PR, `TargetKind` still has only two variants, `Name` and `Sequence`, but now we end up using `Name` also when the target is an attribute. This should be fixed in some way, since it's misleading.

It seems maybe we don't ever need to distinguish between name target and attribute target using the `TargetKind`? In which case we could rename the `Name` variant to `NameOrAttribute`. Or we could add a third variant, `Attribute`, and make sure we pass `Attribute` variant here. The latter seems nicer in that we preserve more information, but if we don't need that information maybe it's not worth it.

File: crates/red_knot_python_semantic/src/semantic_index/use_def.rs [hunk 11]
```diff
@@ -271,17 +272,20 @@ use crate::semantic_index::narrowing_constraints::{
...
+use crate::semantic_index::{symbol_table, use_def_map};
+use crate::types::Truthiness;
 
 mod symbol_state;
 
 /// Applicable definitions and constraints for every use of a name.
 #[derive(Debug, PartialEq, Eq, salsa::Update)]
 pub(crate) struct UseDefMap<'db> {
-    /// Array of [`Definition`] in this scope. Only the first entry should be `None`;
+    /// Array of [`Definition`] in this scope. The first entry should be `None`;
```
Comment (carljm) [inline crates/red_knot_python_semantic/src/semantic_index/use_def.rs:288]: Does this PR introduce `None` entries elsewhere in the array? If not, we can revert this change?

File: crates/red_knot_python_semantic/src/semantic_index/use_def.rs [hunk 12]
```diff
@@ -317,6 +321,9 @@ pub(crate) struct UseDefMap<'db> {
     /// [`SymbolState`] visible at end of scope for each symbol.
     public_symbols: IndexVec<ScopedSymbolId, SymbolState>,
 
+    /// [`SymbolState`] for each instance attribute.
+    instance_attribute_states: IndexVec<ScopedSymbolId, SymbolState>,
```
Comment (carljm) [inline crates/red_knot_python_semantic/src/semantic_index/use_def.rs:325]: nit: we could just call this `instance_attributes`.

We don't call `public_symbols` `public_symbol_states`, even though it is also an indexvec of `SymbolState`.

File: crates/red_knot_python_semantic/src/semantic_index/use_def.rs [hunk 13]
```diff
@@ -352,6 +359,13 @@ impl<'db> UseDefMap<'db> {
         self.bindings_iterator(self.public_symbols[symbol].bindings())
     }
 
+    pub(crate) fn attribute_assignments(
```
Comment (carljm) [inline crates/red_knot_python_semantic/src/semantic_index/use_def.rs:362]: Just for naming consistency I suppose we could call this `instance_attribute_bindings`?

File: crates/red_knot_python_semantic/src/semantic_index/use_def.rs [hunk 14]
```diff
@@ -391,6 +405,45 @@ impl<'db> UseDefMap<'db> {
...
+    pub(crate) fn is_attribute_assignment_visible(
+        &self,
+        db: &dyn crate::Db,
+        binding: &BindingWithConstraints<'_, 'db>,
+        class_body_scope: ScopeId,
+    ) -> Truthiness {
+        let definition = binding.binding.as_ref().unwrap();
+        // The attribute assignment inherits the visibility of the method which contains it
+        let maybe_method_scope = definition.scope(db);
+        let is_method_visible = if let Some(method_def) = maybe_method_scope.node(db).as_function()
```
Comment (carljm) [inline crates/red_knot_python_semantic/src/semantic_index/use_def.rs:417]: Do we have any tests for an attribute assignment inside a definitely-not-existing method? I.e. do any tests fail if we remove this `is_method_visible` check?

**Review by carljm — COMMENTED** [review]
Haven't finished my review but I have to head out, so submitting the comments I have so far. Thanks for your work on this!

Given the false positives observed, I'm not sure we should keep the possibly-unbound-attribute checks, but I'm still thinking about whether there is a satisfactory way to address the false positive cases. It may have some overlap with https://github.com/astral-sh/ruff/issues/15777

File: crates/red_knot_python_semantic/src/semantic_index/use_def.rs (hunk 14 above)
Comment (mtshiba) [reply crates/red_knot_python_semantic/src/semantic_index/use_def.rs:417]: I added a test to check the visibility of an attribute defined in a definitely-non-existing-method.

**Comment by mtshiba** [comment]
Support for attribute assignments in comprehension/aug-assign/named-expression is incomplete, but considering that it is still not implemented in the main branch and that it was not originally planned in this PR, this may be work that should be done in another PR.

I believe that the implementation of the feature originally planned in this PR is almost complete and ready for final review.

File: crates/red_knot_python_semantic/src/types/class.rs [hunk 15]
```diff
@@ -853,81 +857,216 @@ impl<'db> ClassLiteralType<'db> {
...
+        for (attribute_assignments, method_scope_id) in
+            attribute_assignments(db, class_body_scope, name)
+        {
+            let method_scope = method_scope_id.to_scope_id(db, file);
+            let method_map = use_def_map(db, method_scope);
+
+            // The attribute assignment inherits the visibility of the method which contains it
+            let is_method_visible = if let Some(method_def) = method_scope.node(db).as_function() {
+                let method = index.expect_single_definition(method_def);
+                let class_table = symbol_table(db, class_body_scope);
```
Comment (carljm) [inline crates/red_knot_python_semantic/src/types/class.rs:882]: Can't we just get this once at the top of the function? It won't ever change.

**Review by carljm — APPROVED** [review]
This looks pretty good to me! It turns `ClassLiteralType::implicit_instance_attribute` into even more of a monster method, but I think I'm ok with that for now: it has a clear responsibility, and the logic in it is well encapsulated; if we need to break it up for better reuse in future, we can do that.

@sharkdp if you have a chance, I'd like to make sure this looks good to you as well.

File: crates/red_knot_python_semantic/src/types/class.rs [hunk 16]
```diff
@@ -853,81 +857,216 @@ impl<'db> ClassLiteralType<'db> {
...
+                        is_attribute_bound = Truthiness::AlwaysTrue;
+                    }
+                    Truthiness::Ambiguous => {
+                        if is_attribute_bound.is_always_false() {
+                            is_attribute_bound = Truthiness::Ambiguous;
+                        }
+                    }
+                    Truthiness::AlwaysFalse => {
+                        continue;
+                    }
```
Comment (sharkdp) [inline crates/red_knot_python_semantic/src/types/class.rs:928]: Elegant!

**Review by sharkdp — APPROVED** [review]
This looks great — thank you very much. I have just one minor comment, which I can also resolve myself before merging this.
