### PR TITLE
[red-knot] fix lookup of nonlocal names in deferred annotations

### LINKED ISSUE #13176: [red-knot] fix deferred annotations referencing other scopes
Our current handling for resolving deferred annotations uses the inferred types of symbols as they exist at the end of the current scope (rather than the current point in control flow of the current scope), which is correct (or at least the most reasonable option) since their resolution is deferred.

But it currently does this by piggy-backing on the same logic we use for e.g. import resolution, where the name must exist in the scope's namespace, there's no fallback to other scopes. So we can't resolve a deferred annotation that's a builtin, or a global or nonlocal referred to from a nested scope. This should be fixed.

### PR DESCRIPTION
**Pull request by carljm**
Initially I had deferred annotation name lookups reuse the "public symbol type", since that gives the correct "from end of scope" view of reaching definitions that we want. But there is a key difference; public symbol types are based only on definitions in the queried scope (or "name in the given namespace" in runtime terms), they don't ever look up a name in nonlocal/global/builtin scopes. Deferred annotation resolution should do this lookup.

Add a test, and fix deferred name resolution to support nonlocal/global/builtin names.

Fixes #13176

### CODE REVIEW

File: crates/red_knot_python_semantic/src/types/infer.rs [hunk 1]
```diff
@@ -1827,15 +1826,17 @@ impl<'db> TypeInferenceBuilder<'db> {
...
     fn lookup_name(&self, name: &ast::name::Name) -> Type<'db> {
         let file_scope_id = self.scope.file_scope_id(self.db);
-        let symbols = self.index.symbol_table(file_scope_id);
-        let symbol = symbols
+        let is_defined = self
+            .index
+            .symbol_table(file_scope_id)
             .symbol_by_name(name)
-            .expect("Expected the symbol table to create a symbol for every Name node");
+            .expect("Expected the symbol table to create a symbol for every Name node")
```
Comment (MichaReiser) [inline crates/red_knot_python_semantic/src/types/infer.rs:1833]: TIL I learned from @dhruvmanila. Sharing for you https://doc.rust-lang.org/std/error/index.html#common-message-styles

**Review by MichaReiser — APPROVED** [review]

File: crates/red_knot_python_semantic/src/types/infer.rs [hunk 2]
```diff
@@ -3544,6 +3552,22 @@ mod tests {
...
+    #[test]
+    fn deferred_annotation_builtin() -> anyhow::Result<()> {
+        let mut db = setup_db();
+        db.write_file("/src/a.pyi", "class C(object): pass")?;
+        let file = system_path_to_file(&db, "/src/a.pyi").unwrap();
+        let ty = global_symbol_ty_by_name(&db, file, "C");
+
+        let Some(base) = ty.expect_class().bases(&db).next() else {
+            panic!("expected at least one base");
+        };
```
Comment (AlexWaygood) [inline crates/red_knot_python_semantic/src/types/infer.rs:3564]: nit

```suggestion

        let base = ty
            .expect_class()
            .bases(&db)
            .next()
            .expect("there should be at least one base");
```

**Review by AlexWaygood — APPROVED** [review]
