### PR TITLE
Don't format trailing comma for lambda arguments

### LINKED ISSUE #5892: Formatter: arguments get wrong trailing comma
We format
```python
def f(
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = lambda x: y,
):
    pass

def f(
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = lambda x: y,
):
    pass
```
as

```python
def f(
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = lambda x,: y,
):
    pass


def f(
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa=lambda x: y,
):
    pass
```
(notice the trailing comma after the `x`). It needs to be investigated why we add the comma in the first place

This causes unstable formatting:

```python
def f(
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = lambda x: x,
):
    pass
```

```
---
--- Formatted once
+++ Formatted twice
@@ -1,4 +1,5 @@
 def f(
-    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = lambda x,: x,
+    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = lambda x,
+    : x,
 ):
     pass
---

Formatted once:
---
def f(
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = lambda x,: x,
):
    pass
---

Formatted twice:
---
def f(
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = lambda x,
    : x,
):
    pass
---
```

---

I assume this instability is the same bug:

```python
f(s=lambda d,id,blob,timestamp=None,encryption_revision=1,sequester_blob=None:{},)
```

```
---
--- Formatted once
+++ Formatted twice
@@ -4,5 +4,6 @@
     blob,
     timestamp=None,
     encryption_revision=1,
-    sequester_blob=None,: {},
+    sequester_blob=None,
+    : {},
 )
---

Formatted once:
---
f(
    s=lambda d,
    id,
    blob,
    timestamp=None,
    encryption_revision=1,
    sequester_blob=None,: {},
)
---

Formatted twice:
---
f(
    s=lambda d,
    id,
    blob,
    timestamp=None,
    encryption_revision=1,
    sequester_blob=None,
    : {},
)
---
```

### PR DESCRIPTION
**Pull request by konstin**
**Summary** lambda arguments don't have parentheses, so they shouldn't get a magic trailing comma either. This fixes some unstable formatting

**Test Plan** Added a regression test.

89 (from previously 145) instances of unstable formatting remaining.

```
$ cargo run --bin ruff_dev --release -- format-dev --stability-check --error-file formatter-ecosystem-errors.txt --multi-project target/checkouts > formatter-ecosystem-progress.txt
$ rg "Unstable formatting" target/formatter-ecosystem-errors.txt | wc -l
89
```

Closes #5892

### CODE REVIEW

**Comment by konstin** [comment]
Current dependencies on/for this PR:
* main
  * **PR #5944** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff/5944" target="_blank">Graphite</a> 
    * **PR #5946** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff/5946" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/astral-sh/ruff/5946?utm_source=stack-comment).

File: crates/ruff_python_formatter/src/other/arguments.rs [hunk 1]
```diff
@@ -149,7 +149,10 @@ impl FormatNodeRule<Arguments> for FormatArguments {
 
             joiner.finish()?;
 
-            write!(f, [if_group_breaks(&text(","))])?;
+            // lambdas have no parentheses, so they also don't get a magic trailing comma
+            if self.parentheses != ArgumentsParentheses::SkipInsideLambda {
```
Comment (MichaReiser) [inline crates/ruff_python_formatter/src/other/arguments.rs:153]: Unrelated to this PR. Do we need to test if the magic trailing comma option is enabled?

**Review by MichaReiser — APPROVED** [review]

File: crates/ruff_python_formatter/src/other/arguments.rs (hunk 1 above)
Comment (konstin) [reply crates/ruff_python_formatter/src/other/arguments.rs:154]: lambdas seem to have their own trailing comma rules that are different magic trailing comma

Comment (MichaReiser) [reply crates/ruff_python_formatter/src/other/arguments.rs:154]: That makes sense. But do we need to respect the magic trailing comma option for regular arguments?

Comment (konstin) [reply crates/ruff_python_formatter/src/other/arguments.rs:154]: We do,
```python
def f(a,): pass
```
gets formatted as
```python
def f(
    a,
):
    pass
```

Comment (MichaReiser) [reply crates/ruff_python_formatter/src/other/arguments.rs:154]: But do we need to respect `context.options.magic_trailing_comma()`?

**Review by MichaReiser — APPROVED** [review]

File: crates/ruff_python_formatter/src/other/arguments.rs (hunk 1 above)
Comment (konstin) [reply crates/ruff_python_formatter/src/other/arguments.rs]: sorry i misunderstand what you were aiming at, yes, for functions (but not lambdas) we need to respect the magic trailing comma setting and we previously didn't. I've added this now in this PR because separating these two aspects doesn't make sense

File: crates/ruff_python_formatter/src/other/arguments.rs [hunk 2]
```diff
@@ -149,34 +149,31 @@ impl FormatNodeRule<Arguments> for FormatArguments {
...
+            // a trailing comma but it's just preserved without any magic.
+            // ```python
+            // # Add magic trailing comma if its expands
+            // def f(a): pass
+            // # Expands if magic trailing comma setting is respect, otherwise remove the comma
+            // def g(a,): pass
+            // # Never expands
+            // x1 = lambda y: 1
+            // # Never expands, the comma is always preserved
+            // x2 = lambda y,: 1
```
Comment (konstin) [inline crates/ruff_python_formatter/src/other/arguments.rs:162]: I hope those comments are sufficiently clear
