### PR TITLE
[`pyupgrade`] Handle comments and multiline expressions correctly (`UP037`)

### LINKED ISSUE #7102: Rules UP037 cause autofix error
Ruff 0.0.287 (latest changes from main branch)
```
ruff  *.py --select UP037 --no-cache --fix
```

file content(at least simple cpython script shows that this is valid python file):
```
from __future__ import annotations
class IdentityLinearOperator(ConstantDiagLinearOperator):
    def _mul_matrix(
        other: Union[Float[torch.Tensor, "... #M #N"], Float[LinearOperator, "... #M #N"]],
    ) -> Float[LinearOperator, "... M N"]:
        return other
```

error
```
/home/rafal/test/tmp_folder/2589347.py:4:42: UP037 Remove quotes from type annotation
/home/rafal/test/tmp_folder/2589347.py:4:78: UP037 Remove quotes from type annotation
Found 2 errors.

error: Autofix introduced a syntax error. Reverting all changes.

This indicates a bug in `ruff`. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BAutofix%20error%5D

...quoting the contents of `/home/rafal/test/tmp_folder/2589347.py`, the rule codes UP037, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!


```
        
[python_compressed.zip](https://github.com/astral-sh/ruff/files/12506893/python_compressed.zip)

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
## Summary

Resolves #7102.

## Test Plan

`cargo nextest run` and `cargo insta test`.

### CODE REVIEW

File: crates/ruff_linter/src/rules/pyupgrade/rules/quoted_annotation.rs [hunk 1]
```diff
@@ -73,10 +74,28 @@ impl AlwaysFixableViolation for QuotedAnnotation {
...
-    let mut diagnostic = Diagnostic::new(QuotedAnnotation, range);
-    diagnostic.set_fix(Fix::safe_edit(Edit::range_replacement(
-        annotation.to_string(),
-        range,
-    )));
-    checker.diagnostics.push(diagnostic);
+    let diagnostic = Diagnostic::new(QuotedAnnotation, range);
+
+    let len = TextSize::try_from(annotation.len()).unwrap();
+    let placeholder_range = TextRange::up_to(len);
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pyupgrade/rules/quoted_annotation.rs:80]:
```suggestion
    let placeholder_range = TextRange::up_to(annotation.text_len());
    let spans_multiple_lines = annotation.count_lines(placeholder_range) > 1;
```

File: crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP037_2.pyi.snap [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+   | |_______________________^ UP037
+   |
+   = help: Remove quotes
+
+ℹ Safe fix
+14 14 | ]''']): ...
+15 15 | 
+16 16 | 
+17    |-def f(a: Foo['''Bar[
+   17 |+def f(a: Foo[(Bar[
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP037_2.pyi.snap:87]: Are we adding the parentheses in case the quoted annotation is in an unquoted context (e.g. annotated assignment)? Would it be possible to reduce the cases in which we add the parentheses?

File: crates/ruff_linter/src/rules/pyupgrade/rules/quoted_annotation.rs [hunk 3]
```diff
@@ -73,10 +74,28 @@ impl AlwaysFixableViolation for QuotedAnnotation {
...
+    let spans_multiple_lines = annotation.count_lines(placeholder_range) > 1;
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pyupgrade/rules/quoted_annotation.rs:81]:
```suggestion
    let spans_multiple_lines = annotation.contains_line_break(placeholder_range);
```

**Review by MichaReiser — COMMENTED** [review]
Sweet
