### PR TITLE
[`flake8-comprehensions`] Handle trailing comma in fixes for `unnecessary-generator-list/set` (`C400`,`C401`)

### LINKED ISSUE #15852: C400 and C401 fixes fail when a comma follows the generator
### Description

The fixes for [`unnecessary-generator-list` (C400)](https://docs.astral.sh/ruff/rules/unnecessary-generator-list/) and [`unnecessary-generator-set` (C401)](https://docs.astral.sh/ruff/rules/unnecessary-generator-set/) introduce syntax errors in Ruff 0.9.4 when a parenthesized generator comprehension is followed by a comma and the generator comprehension cannot be simplified to just the iterable.
```console
$ cat >c40.py <<'# EOF'
list((0 for _ in []),)
set((0 for _ in []),)
# EOF

$ ruff --isolated check --preview --select C400 c40.py --unsafe-fixes --diff                        

error: Fix introduced a syntax error. Reverting all changes.

This indicates a bug in Ruff. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BFix%20error%5D

...quoting the contents of `c40.py`, the rule codes C400, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!


$ ruff --isolated check --preview --select C401 c40.py --unsafe-fixes --diff

error: Fix introduced a syntax error. Reverting all changes.

This indicates a bug in Ruff. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BFix%20error%5D

...quoting the contents of `c40.py`, the rule codes C401, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!


```

The syntactically incorrect output is presumably:
```python
[0 for _ in [],]
{0 for _ in [],}
```
(Is there a way to see this output instead of having Ruff revert the changes?)

### PR DESCRIPTION
**Pull request by dylwil3**
The unsafe fixes for the rules [unnecessary-generator-list (C400)](https://docs.astral.sh/ruff/rules/unnecessary-generator-list/#unnecessary-generator-list-c400) and [unnecessary-generator-set (C401)](https://docs.astral.sh/ruff/rules/unnecessary-generator-set/#unnecessary-generator-set-c401) used to introduce syntax errors if the argument to `list` or `set` had a trailing comma, because the fix would retain the comma after transforming the function call to a comprehension. 

This PR accounts for the trailing comma when replacing the end of the call with a `]` or `}`.

Closes #15852

### CODE REVIEW

File: crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_generator_list.rs [hunk 1]
```diff
@@ -123,11 +124,17 @@ pub(crate) fn unnecessary_generator_list(checker: &mut Checker, call: &ast::Expr
...
+        // Place `]` at argument's end or at trailing comma if present
+        let mut tokenizer = SimpleTokenizer::starts_at(
+            argument.end(),
+            checker.locator().slice(TextRange::up_to(call.end())),
         );
+        let right_bracket_loc = tokenizer
+            .find(|token| token.kind == SimpleTokenKind::Comma)
+            .map_or(call.arguments.end() - TextSize::from(1), |comma| {
+                comma.end() - TextSize::from(1)
+            });
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_generator_list.rs:136]:
```suggestion
        let right_bracket_loc = tokenizer
            .find(|token| token.kind == SimpleTokenKind::Comma)
            .map_or(call.arguments.end(), |comma| {
                comma.end()
            }) - TextSize::from(1);
```


or 

```suggestion
        let right_bracket_loc = tokenizer
            .find(|token| token.kind == SimpleTokenKind::Comma)
            .map_or(call.arguments.end() - ')'.text_len(), Ranged::start);
```

File: crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_generator_list.rs [hunk 2]
```diff
@@ -123,11 +124,17 @@ pub(crate) fn unnecessary_generator_list(checker: &mut Checker, call: &ast::Expr
...
         // Replace `)` with `]`.
-        let call_end = Edit::replacement(
-            "]".to_string(),
-            call.arguments.end() - TextSize::from(1),
-            call.end(),
+        // Place `]` at argument's end or at trailing comma if present
+        let mut tokenizer = SimpleTokenizer::starts_at(
+            argument.end(),
+            checker.locator().slice(TextRange::up_to(call.end())),
         );
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_generator_list.rs:131]:
```suggestion
        let mut tokenizer = SimpleTokenizer::new(
        		checker.source(), // Not sure if this method exists :D
        		TextRange::new(argument.end(), call.end())
        );
```

File: crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_generator_set.rs [hunk 3]
```diff
@@ -126,9 +127,19 @@ pub(crate) fn unnecessary_generator_set(checker: &mut Checker, call: &ast::ExprC
         );
 
         // Replace `)` with `}`.
+        // Place `}` at argument's end or at trailing comma if present
+        let mut tokenizer = SimpleTokenizer::starts_at(
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_generator_set.rs:131]: Same as for the other rule

**Review by MichaReiser — APPROVED** [review]
Nice, I've only two nit comments that apply to both rules

File: crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_generator_list.rs [hunk 4]
```diff
@@ -123,11 +124,14 @@ pub(crate) fn unnecessary_generator_list(checker: &mut Checker, call: &ast::Expr
...
-            call.end(),
-        );
+        // Place `]` at argument's end or at trailing comma if present
+        let mut tokenizer =
+            SimpleTokenizer::new(checker.source(), TextRange::new(argument.end(), call.end()));
+        let right_bracket_loc = tokenizer
+            .find(|token| token.kind == SimpleTokenKind::Comma)
+            .map_or(call.arguments.end(), |comma| comma.end())
+            - TextSize::from(1);
+        let call_end = Edit::replacement("]".to_string(), right_bracket_loc, call.end());
```
Comment (dhruvmanila) [inline crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_generator_list.rs:134]: I was wondering if we can use `checker.tokens().in_range(...)` instead here?

File: crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_generator_set.rs [hunk 5]
```diff
@@ -126,9 +127,16 @@ pub(crate) fn unnecessary_generator_set(checker: &mut Checker, call: &ast::ExprC
         );
 
         // Replace `)` with `}`.
+        // Place `}` at argument's end or at trailing comma if present
+        let mut tokenizer =
+            SimpleTokenizer::new(checker.source(), TextRange::new(argument.end(), call.end()));
+        let right_brace_loc = tokenizer
+            .find(|token| token.kind == SimpleTokenKind::Comma)
+            .map_or(call.arguments.end(), |comma| comma.end())
+            - TextSize::from(1);
```
Comment (dhruvmanila) [inline crates/ruff_linter/src/rules/flake8_comprehensions/rules/unnecessary_generator_set.rs:136]: Same as above.
