### PR TITLE
[`flake8-import-conventions`] Improve syntax check for aliases supplied in configuration for `unconventional-import-alias (ICN001)`

### LINKED ISSUE #14662: Import aliases configured for ICN001 can cause syntax errors
Ruff 0.8.0 does not validate the aliases in [`lint.flake8-import-conventions.extend-aliases`](https://docs.astral.sh/ruff/settings/#lint_flake8-import-conventions_extend-aliases) for [`unconventional-import-alias` (ICN001)](https://docs.astral.sh/ruff/rules/unconventional-import-alias/).

```console
$ cat icn001.py
import sys

$ ruff check --select ICN001 --config 'lint.flake8-import-conventions.extend-aliases = {"sys" = "def"}' --isolated --unsafe-fixes --fix icn001.py

error: Fix introduced a syntax error. Reverting all changes.

This indicates a bug in Ruff. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BFix%20error%5D

...quoting the contents of `icn001.py`, the rule codes ICN001, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

icn001.py:1:8: ICN001 `sys` should be imported as `def`
  |
1 | import sys
  |        ^^^ ICN001
  |
  = help: Alias `sys` to `def`

Found 1 error.
[*] 1 fixable with the --fix option.
```

The extra aliases should be validated like the ones in [`lint.flake8-import-conventions.aliases`](https://docs.astral.sh/ruff/settings/#lint_flake8-import-conventions_aliases) (#14477).

```console
$ ruff check --select ICN001 --config 'lint.flake8-import-conventions.aliases = {"sys" = "def"}' --isolated --unsafe-fixes --fix icn001.py
error: invalid value 'lint.flake8-import-conventions.aliases = {"sys" = "def"}' for '--config <CONFIG_OPTION>'

  tip: A `--config` flag must either be a path to a `.toml` configuration file
       or a TOML `<KEY> = <VALUE>` pair overriding a specific configuration
       option

Could not parse the supplied argument as a `ruff.toml` configuration option:

invalid value: string "def", expected a Python identifier
in `lint`

For more information, try '--help'.
```

There is still one problem with `lint.flake8-import-conventions.aliases`, and therefore also `extend-aliases`: they allow `__debug__` as an alias, but that is a syntax error.

```console
$ ruff check --select ICN001 --config 'lint.flake8-import-conventions.aliases = {"sys" = "__debug__"}' --isolated --unsafe-fixes --fix icn001.py
Found 1 error (1 fixed, 0 remaining).

$ cat icn001.py
import sys as __debug__

$ python icn001.py
  File "icn001.py", line 1
    import sys as __debug__
    ^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot assign to __debug__
```

### PR DESCRIPTION
**Pull request by dylwil3**
This PR improves on #14477 by:

- Ensuring user's do not require module aliases which are unassignable Python identifiers
- Validating the linter settings for `lint.flake8-import-conventions.extend-aliases` (whereas previously we only did this for `lint.flake8-import-conventions.aliases`).

Closes #14662

### CODE REVIEW

File: crates/ruff_workspace/src/options.rs [hunk 1]
```diff
@@ -1415,6 +1415,15 @@ impl<'de> Deserialize<'de> for Alias {
         D: Deserializer<'de>,
     {
         let name = String::deserialize(deserializer)?;
+        // Assignments to these names are SyntaxErrors
+        // see the note here:
+        // https://docs.python.org/3/library/constants.html#debug__
+        if matches!(&*name, "__debug__" | "True" | "False" | "None") {
```
Comment (dhruvmanila) [inline crates/ruff_workspace/src/options.rs:1421]: I think we can skip "True", "False" and "None" here as they are already being checked by the `is_identifier` check below:

https://github.com/astral-sh/ruff/blob/5137fcc9c81610f687b6cb45413ef83c2c5eea73/crates/ruff_python_stdlib/src/identifiers.rs#L19-L22

Comment (dylwil3) [reply crates/ruff_workspace/src/options.rs]: Nice catch! 

I guess that's a somewhat confusing function name because keywords _are_ identifiers, see: https://docs.python.org/3/reference/lexical_analysis.html#keywords

and also:

```console
>>> "None".isidentifier()
True
```

Comment (dhruvmanila) [reply crates/ruff_workspace/src/options.rs]: Yes, keywords are identifiers but they cannot be used as an identifier. I think the function is used to test the latter.

**Review by dhruvmanila — APPROVED** [review]
