### PR TITLE
[flake8-markupsafe] Adds Implementation for MS001 via RUF035

### LINKED ISSUE #14124: Add flake8-markupsafe or broaden S308
Improper use of `markupsafe.Markup` is a common source of XSS vulnerabilities and I've seen many people, including myself, make mistakes here regardless of how experienced they are, in part due to f-string's convenience and sometimes due to being API-compatible with regular `str`, so it's easy to write `Markup(''.format(unsafe))` instead of `Markup('').format(safe)`, this particular error can also be quite tricky to spot depending on the formatting.

There is an existing [flake8 plugin](https://github.com/vmagamedov/flake8-markupsafe), however it was never published on pypi and it makes a questionable exception for i18n.

Providing support for additional classes that behave like `Markup` on the other hand, like the `webhelpers` `literal` (which is a subclass of `Markup`) with a user-configurable list of fully qualified names seems sensible, since there's also `flask.Markup` which is an alias for `markupsafe.Markup`.

There's an existing issue to either add a rule or extend the existing `B308` rule in bandit, although it never went anywhere. So it could make sense to extend `S308` in ruff instead, or even just add a new `RUF` rule, rather than use up the `MS` prefix for a single rule.

In any case, the implementation should be quite simple and I'd be happy to provide one if you're open to adding a rule for it or augment the existing bandit rule.

### PR DESCRIPTION
**Pull request by Daverball**
Closes #14124

## Summary

This adds an implementation for [flake8-markupsafe](https://github.com/vmagamedov/flake8-markupsafe), minus the questionable exception for i18n and mako support, but with the ability to specify further aliases/subclasses/functionally equivalent for `markupsafe.Markup`. By default `flask.Markup` is also detected as a commonly used alias.

## Test Plan

`cargo nextest run`

### CODE REVIEW

File: crates/ruff_linter/src/rules/flake8_markupsafe/rules/unsafe_markup_use.rs [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+        let UnsafeMarkupUse { name } = self;
+        format!("Unsafe use of `{name}` detected")
+    }
+}
+
+/// Checks for unsafe calls to `[markupsafe.Markup]`.
+///
+/// [markupsafe.Markup]: https://markupsafe.palletsprojects.com/en/stable/escaping/#markupsafe.Markup
+pub(crate) fn unsafe_markup_call(checker: &mut Checker, call: &ExprCall) {
+    if let Some(name) = checker
```
Comment (sbrugman) [inline crates/ruff_linter/src/rules/flake8_markupsafe/rules/unsafe_markup_use.rs:61]: To only consider this rule if `markupsafe` or `flask` is imported:

```suggestion
     if !(checker.semantic().seen_module(Modules::MARKUPSAFE)
        || checker.semantic().seen_module(Modules::FLASK))
    {
        return;
    }
    if let Some(name) = checker
```

(And add `MARKUPSAFE` and `FLASK` to `Modules`)

File: crates/ruff_linter/src/rules/flake8_markupsafe/rules/unsafe_markup_use.rs [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+/// ```
+///
+/// Use instead:
+/// ```python
+/// from markupsafe import Markup
+///
+/// content = "<script>alert('Hello, world!')</script>"
+/// html = Markup("<b>{}</b>").format(content)  # Safe
+/// ```
+///
```
Comment (sbrugman) [inline crates/ruff_linter/src/rules/flake8_markupsafe/rules/unsafe_markup_use.rs:38]: Consider adding the `## Options` section here, example: https://docs.astral.sh/ruff/rules/ambiguous-unicode-character-comment/#options

File: crates/ruff_linter/src/rules/flake8_markupsafe/rules/unsafe_markup_use.rs (hunk 1 above)
Comment (Daverball) [reply crates/ruff_linter/src/rules/flake8_markupsafe/rules/unsafe_markup_use.rs:61]: This fast-path only works if no additional names have been specified in the options, so at the very least I would have to first check `checker.settings.flake8_markupsafe.extend_markup_names.is_empty()`.

File: crates/ruff_linter/src/rules/flake8_markupsafe/rules/unsafe_markup_use.rs [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+
+/// Checks for unsafe calls to `[markupsafe.Markup]`.
+///
+/// [markupsafe.Markup]: https://markupsafe.palletsprojects.com/en/stable/escaping/#markupsafe.Markup
+pub(crate) fn unsafe_markup_call(checker: &mut Checker, call: &ExprCall) {
+    if let Some(name) = checker
+        .semantic()
+        .resolve_qualified_name(&call.func)
+        .and_then(|qualified_name| {
+            if is_markup_call(&qualified_name, checker.settings) && is_unsafe_call(call) {
```
Comment (sbrugman) [inline crates/ruff_linter/src/rules/flake8_markupsafe/rules/unsafe_markup_use.rs:65]: If the `call` is not unsafe, for instance when the call arguments are empty, then we do not use the qualified name (which I assume requires more computation). We should first check `!is_unsafe_call` and otherwise set `None`, if safe, then resolve the qualified name and check the markup call.

File: crates/ruff_linter/resources/test/fixtures/flake8_markupsafe/MS001.py [hunk 4]
```diff
@@ -0,0 +1,10 @@
+import flask
+from markupsafe import Markup, escape
+
+content = "<script>alert('Hello, world!')</script>"
+Markup(f"unsafe {content}")  # MS001
+flask.Markup("unsafe {}".format(content))  # MS001
+Markup("safe {}").format(content)
+flask.Markup(b"safe {}", encoding='utf-8').format(content)
+escape(content)
+Markup(content)  # MS001
```
Comment (sbrugman) [inline crates/ruff_linter/resources/test/fixtures/flake8_markupsafe/MS001.py:10]: Could you please add a couple of more test cases?

Examples:
- f-string formatting
- old-style formatting, `Markup("<em>%s</em> " % ("foo & bar",))
- Explicit keyword arguments, e.g. `Markup(object="hello world")`

https://markupsafe.palletsprojects.com/en/stable/escaping/#markupsafe.Markup

File: crates/ruff_linter/src/rules/flake8_markupsafe/rules/unsafe_markup_use.rs (hunk 1 above)
Comment (sbrugman) [reply crates/ruff_linter/src/rules/flake8_markupsafe/rules/unsafe_markup_use.rs:63]: That's true. Such a guard would be helpful for users that do not work with `markupsafe` or `flask` but have this rule, but have it enabled.

**Comment by sbrugman** [comment]
Nice contribution, thanks!

File: crates/ruff_linter/resources/test/fixtures/flake8_markupsafe/MS001.py (hunk 4 above)
Comment (Daverball) [reply crates/ruff_linter/resources/test/fixtures/flake8_markupsafe/MS001.py:10]: Detecting keyword arguments would only reliably work for `markupsafe.Markup` and `flask.Markup` but not for equivalent classes, so I'm not sure it's worth adding extra complexity until type inference can easily give us the first positional argument regardless of how the function was called. And even then it's somewhat questionable, since code searching for `Markup(object=` yields zero results, I don't expect anyone to ever call it this way.

On the other hand, it is a security rule, so we could consider emitting an error if there isn't at least one positional argument.

But I knew I forgot about something, and it was old-style formatting, f-strings do already have a test case (the very first one).

File: crates/ruff_linter/src/rules/flake8_markupsafe/rules/unsafe_markup_use.rs [hunk 5]
```diff
@@ -0,0 +1,102 @@
...
+
+/// ## What it does
+/// Checks for non-literal strings being passed to [`markupsafe.Markup`].
+///
+/// ## Why is this bad?
+/// `markupsafe.Markup` does not perform any escaping, so passing dynamic
+/// content, like f-strings, variables or interpolated strings will potentially
+/// lead to XSS vulnerabilities.
+///
+/// Instead you should interpolate the [`markupsafe.Markup`] object.
```
[the remark this answers is not in the document]
Comment (Daverball) [reply crates/ruff_linter/src/rules/flake8_markupsafe/rules/unsafe_markup_use.rs:18]: Not sure it's worth mentioning mako support, since mako support was not part of flake8, but rather had to be invoked manually by directly calling the mako module within the plugin. But mentioning the i18n deviation makes sense to me.

File: crates/ruff_linter/resources/test/fixtures/flake8_markupsafe/MS001.py (hunk 4 above)
Comment (sbrugman) [reply crates/ruff_linter/resources/test/fixtures/flake8_markupsafe/MS001.py:10]: > Detecting keyword arguments would only reliably work for markupsafe.Markup and flask.Markup but not for equivalent classes, so I'm not sure it's worth adding extra complexity until type inference can easily give us the first positional argument regardless of how the function was called. And even then it's somewhat questionable, since code searching for Markup(object= yields zero results, I don't expect anyone to ever call it this way.

I was only suggesting to add them as test cases, and agree that we do not have to support. I think it's a good idea to include known syntactially valid negative test cases ahead of time for posterity.

Comment (Daverball) [reply crates/ruff_linter/resources/test/fixtures/flake8_markupsafe/MS001.py:10]: Yeah, that's fair. I did include corresponding test cases.

Comment (sbrugman) [reply crates/ruff_linter/resources/test/fixtures/flake8_markupsafe/MS001.py:10]: > But I knew I forgot about something, and it was old-style formatting, f-strings do already have a test case (the very first one).

Overlooked the f-string. For completeness we can consider other valid but less frequent cases, e.g. multi-line strings, implicit string concatenation,  with and without comments.

File: crates/ruff_linter/src/rules/flake8_markupsafe/rules/unsafe_markup_use.rs [hunk 6]
```diff
@@ -60,11 +64,24 @@ impl Violation for UnsafeMarkupUse {
...
+        .is_empty()
+        && !(checker.semantic().seen_module(Modules::MARKUPSAFE)
+            || checker.semantic().seen_module(Modules::FLASK))
+    {
+        return;
+    }
+    if !is_unsafe_call(call) {
+        return;
+    }
     if let Some(name) = checker
```
Comment (sbrugman) [inline crates/ruff_linter/src/rules/flake8_markupsafe/rules/unsafe_markup_use.rs:80]: Would something like this work? (equivalent but in the same return-early style for consistency)

```rs

    let Some(qualified_name) = checker
         .semantic()
         .resolve_qualified_name(&call.func) else{
        return;
    };

    if !is_markup_call(&qualified_name, checker.settings) {
        return;
    } 

    checker
        .diagnostics
        .push(Diagnostic::new(UnsafeMarkupUse { qualified_name.to_string() }, call.range()));
```

File: crates/ruff_linter/resources/test/fixtures/flake8_markupsafe/MS001.py [hunk 7]
```diff
@@ -0,0 +1,13 @@
...
+flask.Markup("unsafe %s" % content)  # MS001
+Markup(object="safe")
+Markup(object="unsafe {}".format(content))  # Not currently detected
```
Comment (sbrugman) [inline crates/ruff_linter/resources/test/fixtures/flake8_markupsafe/MS001.py:13]: Found one more example. In the ecosystem results we can find this example:

```python
Markup("*" * 8)
```

There is no user input here - essentially it's just string formatting -, so there is no possibility of tampering and we could allow these cases. 


https://github.com/apache/airflow/blob/340a70bfe7289e01898ddd75f8edfaf7772e9d09/airflow/www/views.py#L4523

Comment (sbrugman) [reply crates/ruff_linter/resources/test/fixtures/flake8_markupsafe/MS001.py:13]: I agree, let's add these cases for when red-knot is available.

File: crates/ruff_linter/src/codes.rs [hunk 8]
```diff
@@ -1081,6 +1081,9 @@ pub fn code_to_rule(linter: Linter, code: &str) -> Option<(RuleGroup, Rule)> {
         (Flake8Logging, "007") => (RuleGroup::Stable, rules::flake8_logging::rules::ExceptionWithoutExcInfo),
         (Flake8Logging, "009") => (RuleGroup::Stable, rules::flake8_logging::rules::UndocumentedWarn),
 
+        // flake8-markupsafe
+        (Flake8MarkupSafe, "001") => (RuleGroup::Preview, rules::flake8_markupsafe::rules::UnsafeMarkupUse),
```
Comment (MichaReiser) [inline crates/ruff_linter/src/codes.rs:1086]: I understand that flake8-markup-safe has only a single rule. If that's indeed the case, then I don't think it's worth for us to introduce a new rule group just for that. Instead, we should add it to the `RUF` group and mentioned it in the documentation that this rule is inherited/inspired by `flake8-markup-safe`

File: crates/ruff_linter/src/rules/flake8_markupsafe/rules/unsafe_markup_use.rs [hunk 9]
```diff
@@ -0,0 +1,120 @@
...
+fn is_unsafe_call(call: &ExprCall) -> bool {
+    // technically this could be circumvented by using a keyword argument
+    // but without type-inference we can't really know which keyword argument
+    // corresponds to the first positional argument and either way it is
+    // unlikely that someone will actually use a keyword argument here
+    // TODO: Eventually we may want to allow dynamic values, as long as they
+    //       have a __html__ attribute, since that is part of the API
+    !(call.arguments.args.is_empty()
+        || call.arguments.args[0].is_string_literal_expr()
+        || call.arguments.args[0].is_bytes_literal_expr())
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_markupsafe/rules/unsafe_markup_use.rs:119]: Nit:
```suggestion
	matches!(&*call.arguments.args, [first] if !first.is_string_literal_expr() && !first.is_bytes_literal_expr())
```

**Review by MichaReiser — APPROVED** [review]
This looks good to me. Thank you. The only change I would make is that I don't think it's worth introducing a new rule group for a single rule. 

I'd also like to hear @AlexWaygood's opinion on the rule itself.

File: crates/ruff_linter/src/codes.rs (hunk 8 above)
Comment (Daverball) [reply crates/ruff_linter/src/codes.rs:1086]: That's fair, I brought this up in the original issue as well. I'm fine with whatever you decide on.

**Review by AlexWaygood — COMMENTED** [review]
I've never used `markupsafe` but it makes sense to me that this would be an important security consideration. I think it's good for linters to catch this.

Long-term, we should be able to improve the accuracy of rules like this when we switch to using red-knot as a backend (the `LiteralString` type is explicitly designed for this use case). But I don't think that should stop us from implementing this rule now!

File: crates/ruff_linter/src/rules/flake8_markupsafe/rules/unsafe_markup_use.rs [hunk 10]
```diff
@@ -0,0 +1,118 @@
...
+///
+/// ## Why is this bad?
+/// `markupsafe.Markup` does not perform any escaping, so passing dynamic
+/// content, like f-strings, variables or interpolated strings will potentially
+/// lead to XSS vulnerabilities.
+///
+/// Instead you should interpolate the [`markupsafe.Markup`] object.
+///
+/// In contrast to the original rule, we do not make an exception for i18n calls
+/// within [`markupsafe.Markup`].
```
[the remark this answers is not in the document]
Comment (Daverball) [reply crates/ruff_linter/src/rules/flake8_markupsafe/rules/unsafe_markup_use.rs:22]: Yeah if we move this to the RUF namespace I don't think we need this sentence at all. Just a new one to give credit to the plugin which originally inspired this rule.

**Review by MichaReiser — APPROVED** [review]
Nice!
