### PR TITLE
[`refurb`] Fix `FURB101` and `FURB103` false positives when I/O variable is used later

### LINKED ISSUE #21483: FURB101 and FURB103 shouldn’t apply when the I/O variable is used later
### Summary

[`read-whole-file` (FURB101)](https://docs.astral.sh/ruff/rules/read-whole-file/) and [`write-whole-file` (FURB103)](https://docs.astral.sh/ruff/rules/write-whole-file/) should be suppressed when the I/O variable is used after the `with` block (unless the variable is unconditionally rebound). There is no straightforward way to get the same behavior by using the suggested `pathlib` methods. [Examples](https://play.ruff.rs/8841cf55-3dfc-4957-9d2c-be3171f3d72d):
```console
$ cat >furb10.py <<'# EOF'
with open("furb10.py", encoding="utf-8") as f1:
    _ = f1.read()
try:
    print(f1.mode)
except NameError as e:
    print(e)

with open("furb10.txt", "w") as f2:
    f2.write("\n")
try:
    print(f2.encoding)
except NameError as e:
    print(e)
# EOF

$ python furb10.py
r
UTF-8

$ ruff --isolated check furb10.py --select FURB101,FURB103 --preview --fix
Found 2 errors (2 fixed, 0 remaining).

$ cat furb10.py
import pathlib
_ = pathlib.Path("furb10.py").read_text(encoding="utf-8")
try:
    print(f1.mode)
except NameError as e:
    print(e)

pathlib.Path("furb10.txt").write_text("\n")
try:
    print(f2.encoding)
except NameError as e:
    print(e)

$ python furb10.py
name 'f1' is not defined
name 'f2' is not defined
```

### Version

ruff 0.14.5 (87dafb878 2025-11-13)

### PR DESCRIPTION
**Pull request by chirizxc**
## Summary

Fix #21483

## Test Plan

```bash
cargo nextest run furb
```

### CODE REVIEW

**Comment by chirizxc** [comment]
I think it's quite difficult not to discard cases from the ruff ecosystem.

File: crates/ruff_linter/src/rules/refurb/rules/write_whole_file.rs [hunk 1]
```diff
@@ -87,7 +89,18 @@ pub(crate) fn write_whole_file(checker: &Checker, with: &ast::StmtWith) {
     }
 
     // First we go through all the items in the statement and find all `open` operations.
-    let candidates = find_file_opens(with, checker.semantic(), false, checker.target_version());
+    let following_statements = following_statements_after_with(
+        with,
+        checker.semantic().current_statement_parent(),
+        checker.python_ast(),
+    );
+    let candidates = find_file_opens(
```
Comment (amyreese) [inline crates/ruff_linter/src/rules/refurb/rules/write_whole_file.rs]: Rather than doing up-front work to find all the statements for every `with` block, even if it has nothing to do with opening a file, this should first see if there are any candidates, and only then fetch the following statements and filter the list of candidates afterwards.

Or at the very least, the call to get following statements should happen further inside of say, `resolve_file_open` where the data will actually be used, at the point that it will actually be needed and no sooner.

File: crates/ruff_linter/src/rules/refurb/helpers.rs [hunk 2]
```diff
@@ -182,25 +183,52 @@ pub(super) fn find_file_opens<'a>(
...
 }
 
-fn resolve_file_open<'a>(
-    item: &'a ast::WithItem,
+struct OpenResolutionContext<'a> {
     with: &'a ast::StmtWith,
     semantic: &'a SemanticModel<'a>,
     read_mode: bool,
+    following_statements: Option<&'a [ast::Stmt]>,
+}
```
Comment (amyreese) [inline crates/ruff_linter/src/rules/refurb/helpers.rs]: not sure why this warranted a new struct rather than continuing to pass these through as arguments.

File: crates/ruff_linter/src/checkers/ast/mod.rs [hunk 3]
```diff
@@ -472,6 +472,11 @@ impl<'a> Checker<'a> {
         self.locator.contents()
     }
 
+    /// The AST body for the current module.
+    pub(crate) fn python_ast(&self) -> &'a [Stmt] {
+        self.parsed.suite()
+    }
```
Comment (amyreese) [inline crates/ruff_linter/src/checkers/ast/mod.rs]:
```suggestion
```

I think it would be preferable to just pass the `Checker` around and access `.parsed.suite()` where needed.

**Comment by amyreese** [comment]
Also, looking at the ecosystem results, it seems we're already pushing towards false negatives here, so I'm not sure how much this is actually benefiting the rule. Were there any false positives in the ecosystem report that should have been resolved with this PR?

**Comment by chirizxc** [comment]
> Also, looking at the ecosystem results, it seems we're already pushing towards false negatives here, so I'm not sure how much this is actually benefiting the rule. Were there any false positives in the ecosystem report that should have been resolved with this PR?

I looked at the changes in the ecosystem from the bot's post, none of these changes are false negatives, since the variables below are used in f.name or f.is_file()

**Comment by amyreese** [comment]
> I looked at the changes in the ecosystem from the bot's post, none of these changes are false negatives, since the variables below are used in f.name or f.is_file()

maybe I'm missing something, but `f` in the airflow ecosystem examples are rebound as part of the comprehensions, so they were legit positives that have been silenced with this PR:

```py
with open(file_path, "w") as f:
    f.write("hello world")

...

files_in_repo = {f.name for f in bundle.path.iterdir() if f.is_file()}
```

note the `for f in ...` part of the comprehension means `f.name` and `f.is_file()` are not referring to the same `f` from the context manager above.

**Comment by chirizxc** [comment]
> > I looked at the changes in the ecosystem from the bot's post, none of these changes are false negatives, since the variables below are used in f.name or f.is_file()
> 
> maybe I'm missing something, but `f` in the airflow ecosystem examples are rebound as part of the comprehensions, so they were legit positives that have been silenced with this PR:
> 
> ```python
> with open(file_path, "w") as f:
>     f.write("hello world")
> 
> ...
> 
> files_in_repo = {f.name for f in bundle.path.iterdir() if f.is_file()}
> ```
> 
> note the `for f in ...` part of the comprehension means `f.name` and `f.is_file()` are not referring to the same `f` from the context manager above.

Yes, you were right, when I looked at these bot ecosystem results, I didn't pay attention

**Comment by amyreese** [comment]
Overall I'm still concerned about the amount of code here, especially when it resolves only a single false positive in the ecosystem report. Would prefer that this is simplified, and lean more on the existing features of the semantic model rather than reimplementing its own version of semantic model and control flow. Brent suggested that [`only_binding`](https://github.com/astral-sh/ruff/blob/1a3f07bec4fdee578d0bb6bd146838c09d82d347/crates/ruff_python_semantic/src/model.rs#L979-L982) might be helpful here, or maybe consider just return early if the binding is used for anything beyond the read call, without trying to map control flow?

**Comment by chirizxc** [comment]
> Overall I'm still concerned about the amount of code here, especially when it resolves only a single false positive in the ecosystem report. Would prefer that this is simplified, and lean more on the existing features of the semantic model rather than reimplementing its own version of semantic model and control flow. Brent suggested that [`only_binding`](https://github.com/astral-sh/ruff/blob/1a3f07bec4fdee578d0bb6bd146838c09d82d347/crates/ruff_python_semantic/src/model.rs#L979-L982) might be helpful here, or maybe consider just return early if the binding is used for anything beyond the read call, without trying to map control flow?

I will try to reduce the amount of code, but ecosystem analysis projects do not involve all Python code, so I think there is more than one case.

**Comment by ntBre** [comment]
I was mostly surprised that we need a new `Visitor` here. Would moving the rule to a different [analysis phase](https://github.com/astral-sh/ruff/blob/313336b61bba043a636084e6047eccaea9a4e773/crates/ruff_linter/src/checkers/ast/mod.rs#L3309-L3314) help? I thought we had pretty nice helpers for checking if a variable is used later without tracking that information in a new visitor.

**Comment by chirizxc** [comment]
> I was mostly surprised that we need a new `Visitor` here. Would moving the rule to a different [analysis phase](https://github.com/astral-sh/ruff/blob/313336b61bba043a636084e6047eccaea9a4e773/crates/ruff_linter/src/checkers/ast/mod.rs#L3309-L3314) help? I thought we had pretty nice helpers for checking if a variable is used later without tracking that information in a new visitor.

Hmm, I didn't even know about that. It seems more logical now. Thank you very much.

**Comment by amyreese** [comment]
Will wait for @ntBre to take a look.

**Review by ntBre — APPROVED** [review]
Thank you! Yes, this makes sense to me. I'm slightly wary of deferring too many checks, especially since I made a similar suggestion twice in quick succession after not using it much before, but this does seem better than trying to restructure the rules to fit into `deferred_scopes`. I also don't see any negative perf effects of the deferral, which makes sense to me given how lightweight the snapshots are.

I think this is fine as-is, but if we defer any more types of statements, it probably makes sense to have a single `deferred_statements` with a `match` on the statement kind instead of adding more `deferred_for_loops`, `deferred_with_statements` type functions and fields.
