### PR TITLE
[B028-doc-update] Update documentation for B028

### LINKED ISSUE #14289: (📚) documentation for `B028` is misleading
> The `warnings.warn` method uses a `stacklevel` of 1 by default, which limits the rendered stack trace to that of the line on which the `warn` method is called.

https://docs.astral.sh/ruff/rules/no-explicit-stacklevel/#no-explicit-stacklevel-b028

reading this, it implies that if a higher number is set, then the stack trace will contain multiple entries

> It's recommended to use a `stacklevel` of 2 or higher, give the caller more context about the warning.

```diff
- give
+ giving
OR
+ to give
```

### maybe

```
The `warnings.warn` method uses a stacklevel of 1 by default, which will output a stack frame of the line on which the `warn` method is called. Setting it to a higher number will output a stack frame from higher up the stack.

It's recommended to use a `stacklevel` of 2 or higher, to give the caller a more appropriate context about the warning.
```

### PR DESCRIPTION
**Pull request by njhearp**
## Summary
Resolves #14289
The documentation for B028 no_explicit_stacklevel is updated to be more clear.

### CODE REVIEW

File: crates/ruff_linter/src/rules/flake8_bugbear/rules/no_explicit_stacklevel.rs [hunk 1]
```diff
@@ -11,11 +11,12 @@ use crate::checkers::ast::Checker;
...
-/// limits the rendered stack trace to that of the line on which the
-/// `warn` method is called.
+/// will output a stack frame of the line on which the "warn" method
+/// is called. Setting it to a higher number will output a stack frame
+/// from higher up the stack.
 ///
-/// It's recommended to use a `stacklevel` of 2 or higher, give the caller
-/// more context about the warning.
+/// It's recommended to use a `stacklevel` of 2 or higher, to give the caller
+/// a more appropriate context about the warning.
```
Comment (dylwil3) [inline crates/ruff_linter/src/rules/flake8_bugbear/rules/no_explicit_stacklevel.rs:19]: Actually I think this line with just "more context about the warning" sounds better as is. (But the "give"--> "to give" looks good)

**Review by dylwil3 — CHANGES_REQUESTED** [review]
One nit, otherwise LGTM!

File: crates/ruff_linter/src/rules/flake8_bugbear/rules/no_explicit_stacklevel.rs (hunk 1 above)
Comment (dylwil3) [reply crates/ruff_linter/src/rules/flake8_bugbear/rules/no_explicit_stacklevel.rs]: Since it was a small nit I just applied it for you 😄 - thank you for the contribution!

**Review by dylwil3 — APPROVED** [review]
Thanks again for contributing @njhearp !
