### PR TITLE
[`flake8-pyi`] Ensure `Literal[None,] | Literal[None,]` is not autofixed to `None | None` (`PYI061`)

### LINKED ISSUE #16177: PYI061 fixes `Literal[None,] | Literal[None,]` to `None | None`
### Description

The fix for [`redundant-none-literal` (PYI061)](https://docs.astral.sh/ruff/rules/redundant-none-literal/) converts `Literal[None,] | Literal[None,]` to `None | None`, which can raise an exception.
```console
$ cat >pyi061.py <<'# EOF'
from typing import Literal
x: Literal[None,] | Literal[None,]
# EOF

$ python pyi061.py

$ ruff --isolated check --preview --select PYI061 pyi061.py --fix
Found 2 errors (2 fixed, 0 remaining).

$ python pyi061.py                               
Traceback (most recent call last):
  File "pyi061.py", line 2, in <module>
    x: None | None
       ~~~~~^~~~~~
TypeError: unsupported operand type(s) for |: 'NoneType' and 'NoneType'
```

### PR DESCRIPTION
**Pull request by LaBatata101**
Handles the case where the `None` literal inside `Literal` is part of a tuple, e.g. `List[None,]`. We don't create the fix for this case.

Fixes #16177.

## Test Plan

Snapshot tests.

### CODE REVIEW

File: crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs [hunk 1]
```diff
@@ -258,3 +258,15 @@ enum UnionKind {
...
 }
+
+fn is_slice_none_literal(slice: &Expr) -> bool {
+    match slice {
+        Expr::NoneLiteral(_) => true,
+        // If the slice contains a tuple, e.g. `Literal[None,]` we are only interested in the first
+        // element.
+        Expr::Tuple(ast::ExprTuple { elts, .. }) if elts.len() == 1 => elts
+            .first()
+            .is_some_and(|expr| matches!(expr, Expr::NoneLiteral(_))),
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs:269]: slightly simpler:

```suggestion
        // If the slice contains a single-element tuple, e.g. `Literal[None,]`,
        // check the first element.
        Expr::Tuple(ast::ExprTuple { elts, .. }) => {
            matches!(&**elts, [Expr::NoneLiteral(_)])
        }
```

**Review by AlexWaygood — COMMENTED** [review]
thanks!

File: crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs (hunk 1 above)
Comment (LaBatata101) [reply crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs]: Nice!

**Comment by AlexWaygood** [comment]
Looking at it again, I think this maybe fixes things the wrong way. If we have a `foo.pyi` file like this:

```py
from typing import Literal

f: Literal[None,] | Literal[None,]
g: Literal[None,] | None
h: None | Literal[None,]
```

and I run `cargo run -- check foo.pyi --select=PYI061 --preview --no-cache --diff` from the `main` branch, Ruff says it would apply these fixes:

```diff
--- foo.pyi
+++ foo.pyi
@@ -1,5 +1,5 @@
 from typing import Literal
 
-f: Literal[None,] | Literal[None,]
+f: None | None
 g: Literal[None,] | None
 h: None | Literal[None,]
```

I.e., the second and third of these are fine, because this rule already knows that converting `Literal[None,] | None` to `None | None` will produce a `TypeError`. The reason why the first expression gets converted into one that will produce a `TypeError` is because there are actually two fixes being applied to the same expression as part of a _single iteration_ of diagnostics-plus-fixes from Ruff. The second autofix isn't aware of the changes that the first autofix made (it isn't aware that the first element in the union has already been converted to `None`) so it thinks it's still safe to convert the second element in the union to `None`.

That indicates to me that the better fix here is to ensure that each element's autofix is forced to happen in a separate iteration of the diagnostics-plus-autofixes loop that Ruff does until there are no more autofixes to apply. I.e., this diff applied to `main` also fixes the issue for me, and feels to me like it more directly addresses the cause of the problem here:

```diff
diff --git a/crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs b/crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs
index 16a48bc5f..e3fafac62 100644
--- a/crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs
+++ b/crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs
@@ -130,6 +130,9 @@ pub(crate) fn redundant_none_literal<'a>(checker: &Checker, literal_expr: &'a Ex
                 literal_elements.clone(),
                 union_kind,
             )
+            .map(|fix| {
+                fix.map(|fix| fix.isolate(Checker::isolation(semantic.current_statement_id())))
+            })
         });
         checker.report_diagnostic(diagnostic);
     }
```

**Comment by LaBatata101** [comment]
> Looking at it again, I think this maybe fixes things the wrong way. If we have a `foo.pyi` file like this:
> 
> ```python
> from typing import Literal
> 
> f: Literal[None,] | Literal[None,]
> g: Literal[None,] | None
> h: None | Literal[None,]
> ```
> 
> and I run `cargo run -- check foo.pyi --select=PYI061 --preview --no-cache --diff` from the `main` branch, Ruff says it would apply these fixes:
> 
> ```diff
> --- foo.pyi
> +++ foo.pyi
> @@ -1,5 +1,5 @@
>  from typing import Literal
>  
> -f: Literal[None,] | Literal[None,]
> +f: None | None
>  g: Literal[None,] | None
>  h: None | Literal[None,]
> ```
> 
> I.e., the second and third of these are fine, because this rule already knows that converting `Literal[None,] | None` to `None | None` will produce a `TypeError`. The reason why the first expression gets converted into one that will produce a `TypeError` is because there are actually two fixes being applied to the same expression as part of a _single iteration_ of diagnostics-plus-fixes from Ruff. The second autofix isn't aware of the changes that the first autofix made (it isn't aware that the first element in the union has already been converted to `None`) so it thinks it's still safe to convert the second element in the union to `None`.
> 
> That indicates to me that the better fix here is to ensure that each element's autofix is forced to happen in a separate iteration of the diagnostics-plus-autofixes loop that Ruff does until there are no more autofixes to apply. I.e., this diff applied to `main` also fixes the issue for me, and feels to me like it more directly addresses the cause of the problem here:
> 
> ```diff
> diff --git a/crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs b/crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs
> index 16a48bc5f..e3fafac62 100644
> --- a/crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs
> +++ b/crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs
> @@ -130,6 +130,9 @@ pub(crate) fn redundant_none_literal<'a>(checker: &Checker, literal_expr: &'a Ex
>                  literal_elements.clone(),
>                  union_kind,
>              )
> +            .map(|fix| {
> +                fix.map(|fix| fix.isolate(Checker::isolation(semantic.current_statement_id())))
> +            })
>          });
>          checker.report_diagnostic(diagnostic);
>      }
> ```

Makes sense, thanks!

File: crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI061.py [hunk 2]
```diff
@@ -79,3 +79,6 @@ def good_func(arg1: Literal[int] | None):
 d: None | (Literal[None] | None)
 e: None | ((None | Literal[None]) | None) | None
 f: Literal[None] | Literal[None]
+
+# https://github.com/astral-sh/ruff/issues/16177
+g: Literal[None,] | Literal[None,]
```
Comment (AlexWaygood) [inline crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI061.py:84]: can you add a comment along the lines of "we offer a fix for one of these, but not both of them, as if both were autofixed it would result in a `TypeError` at runtime"?

(Same for the other fixture file)

File: crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs [hunk 3]
```diff
@@ -130,6 +130,9 @@ pub(crate) fn redundant_none_literal<'a>(checker: &Checker, literal_expr: &'a Ex
                 literal_elements.clone(),
                 union_kind,
             )
+            .map(|fix| {
+                fix.map(|fix| fix.isolate(Checker::isolation(semantic.current_statement_id())))
+            })
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs:135]: can you add a short comment for future readers that explains why we need to ensure isolation here?

File: crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI061.py (hunk 2 above)
Comment (AlexWaygood) [reply crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI061.py:84]: in fact, this should probably be an integration test, since in the unit tests here it looks like both fixes _are_ being offered simultaneously, even though that's not what actually happens on your PR branch when Ruff is actually run on user code

Comment (LaBatata101) [reply crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI061.py:84]: Yep

File: crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs (hunk 3 above)
Comment (LaBatata101) [reply crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs:135]: Yes.

File: crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI061.py (hunk 2 above)
Comment (AlexWaygood) [reply crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI061.py:84]: an integration test could go in https://github.com/astral-sh/ruff/blob/main/crates/ruff/tests/lint.rs

File: crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs (hunk 3 above)
Comment (LaBatata101) [reply crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs:138]: @AlexWaygood I've added the comment, can you check to see if it's good?

**Review by AlexWaygood — APPROVED** [review]

**Comment by AlexWaygood** [comment]
I realised that we could simplify some of the logic added in https://github.com/astral-sh/ruff/pull/14583, because ensuring that the individual autofixes are isolated provides a more general fix! I pushed the change to your branch here

**Comment by AlexWaygood** [comment]
Thank you!
