### PR TITLE
[flake8-async] fix detection for large integer sleep durations in `ASYNC116` rule

### LINKED ISSUE #18762: ASYNC116 does not flag integers above `2^64 - 1`
### Summary

If the sleep time is an integer above `2^64 - 1` (`18446744073709551615`) it will not be caught by ASYNC1116 [playground](https://play.ruff.rs/ef43cd10-fc56-4df1-badb-3aaeceefec77)

```py
import trio


async def func():
    await trio.sleep(9999999999999999999) # ASYNC116

async def func():
    await trio.sleep(10000000000000000000000000000000000e100000000000000000000000000000000) # ASYNC116

async def func():
    await trio.sleep(99999999999999999999999999999999.0) # ASYNC116

async def func():
    await trio.sleep(18446744073709551615) # ASYNC116

async def func():
    await trio.sleep(18446744073709551616) # No error

async def func():
    await trio.sleep(99999999999999999999) # No error
```

I'm not an async user, but this may be worth fixing since my natural amount of `9`s for a really big number is just above the limit this rule will detect.

I think the bug comes from here https://github.com/astral-sh/ruff/blob/cb512ba80b8594efa3543365a7a3374c4415adba/crates/ruff_linter/src/rules/flake8_async/rules/long_sleep_not_forever.rs#L103-L110

If the `as_u64` fails, that should mean the number is bigger than a `u64`, and thus the error should be reported, instead of skipped.

I think floats bypass this issue since they give `inf` if they are too big.

### Version

playground

### PR DESCRIPTION
**Pull request by chirizxc**
## Summary
/closes #18762

### CODE REVIEW

File: crates/ruff_linter/src/rules/flake8_async/rules/long_sleep_not_forever.rs [hunk 1]
```diff
@@ -100,14 +100,10 @@ pub(crate) fn long_sleep_not_forever(checker: &Checker, call: &ExprCall) {
...
-            let Some(int_value) = int_value.as_u64() else {
-                return;
-            };
-            if int_value <= one_day_in_secs {
-                return;
-            }
-        }
+        Number::Int(int_value) => match int_value.as_u64() {
+            Some(int_value) if int_value <= one_day_in_secs => return,
+            _ => {} // The number is too large, or more than 24 hours
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_async/rules/long_sleep_not_forever.rs]:
```suggestion
            _ => {} // The number is too large, and more than 24 hours
```
