### PR TITLE
[`flake8-import-conventions`] Syntax check aliases supplied in configuration for `unconventional-import-alias (ICN001)`

### LINKED ISSUE #14439: Possible error when trying to fix with ICN001
I obtain errors with [ICN001](https://docs.astral.sh/ruff/rules/unconventional-import-alias/) when trying to apply autofix (in 'unsafe' mode) that should ideally convert the import from `from A1.A2.AN import B` to `import A1.A2.AN`.

For example, consider the following simple source file `moo.py`:
```python
from math import sin

sin(42)
```

And then the following configuration for ruff  in `pyproject.toml`
```toml
[project]
name = "moo"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ruff>=0.7.4",
]

[tool.ruff.lint]
select = ["ICN001"]

[tool.ruff.lint.flake8-import-conventions.aliases]
"math.sin" = "math.sin"
```

I get the following error:
```console
> uv run ruff check --fix --unsafe-fixes moo.py
error: Fix introduced a syntax error. Reverting all changes.

This indicates a bug in Ruff. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BFix%20error%5D

...quoting the contents of `moo.py`, the rule codes ICN001, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

moo.py:1:18: ICN001 `math.sin` should be imported as `math.sin`
  |
1 | from math import sin
  |                  ^^^ ICN001
2 |
3 | sin(42)
  |
  = help: Alias `math.sin` to `math.sin`

Found 1 error.
[*] 1 fixable with the --fix option.
```

I'm not 100% sure that I'm not abusing the intention of this rule, since here I'm trying to use the rule to enforce the _absence_ of an alias, rather than a conventional alias :)

### PR DESCRIPTION
**Pull request by dylwil3**
This PR introduces a validation step to the deserialization of the configuration for [unconventional-import-alias (ICN001)](https://docs.astral.sh/ruff/rules/unconventional-import-alias/#unconventional-import-alias-icn001). We verify that the import module and alias supplied have valid syntax in order to avoid a panic if these aliases are added in during a fix.

Closes #14439

### CODE REVIEW

**Comment by dylwil3** [comment]
Two notes:

- Sorry for bloating the workspace crate with serde and especially with serde_json (since I only use the latter for a test)... let me know if you'd like me to work around that
- I don't add a deserialization check for "banned aliases" or "banned from" since a fix would never _add_ those to the source code

File: crates/ruff_workspace/src/options.rs [hunk 1]
```diff
@@ -3406,12 +3433,20 @@ pub struct AnalyzeOptions {
...
     use ruff_python_ast::name::Name;
     use ruff_python_formatter::PythonVersion as FormatterPythonVersion;
 
+    #[test]
+    fn flake8_import_conventions_validate_aliases() {
+        let json_options = r#"{"aliases": {"a.b":"a.b"}}"#;
+        let result: Result<Flake8ImportConventionsOptions, _> = serde_json::from_str(json_options);
+        assert!(result.unwrap_err().to_string().contains("Module must be valid identifier separated by single periods and alias must be valid identifier"));
+    }
+
```
Comment (MichaReiser) [inline crates/ruff_workspace/src/options.rs:3449]: I'm leaning towards making this a ruff cli integration test. It then also demonstrates how the error message is displayed to the users. 

See https://github.com/astral-sh/ruff/blob/c847cad389f202edae868765e690cb7042e88264/crates/ruff/tests/lint.rs#L23

File: crates/ruff_workspace/src/options.rs [hunk 2]
```diff
@@ -1370,6 +1373,30 @@ pub struct Flake8ImportConventionsOptions {
...
+    for (module, alias) in &aliases {
+        if module.is_empty()
+            || module.split('.').any(|part| !is_identifier(part))
+            || !is_identifier(alias)
+        {
+            return Err(de::Error::custom(
+                "Module must be valid identifier separated by single periods and alias must be valid identifier",
+            ));
+        }
```
Comment (MichaReiser) [inline crates/ruff_workspace/src/options.rs:1394]: I suggest that we use two dedicated errors: One for `alias` and one for `module`.

**Comment by AlexWaygood** [comment]
Sorry — I optimistically tried to change the target branch, but it messed up the diff, so swiftly reverted that back 😅

It's probably fine if this goes straight into `main`, though, as long as we merge it before the 0.8 release goes out. I highly doubt we'll be cutting another patch release before 0.8, since everything is roughly on schedule for the minor release

**Comment by MichaReiser** [comment]
I also don't consider this breaking. It doesn't change the intent of the rule.

File: crates/ruff_workspace/src/options.rs (hunk 1 above)
Comment (dylwil3) [reply crates/ruff_workspace/src/options.rs]: Done!

File: crates/ruff_workspace/src/options.rs (hunk 2 above)
Comment (dylwil3) [reply crates/ruff_workspace/src/options.rs]: Done!

**Comment by dylwil3** [comment]
> I agree that it doesn't change the intent of the rule, but clearly _some_ users are not using the rule _as it was intended_: [#14439 (comment)](https://github.com/astral-sh/ruff/issues/14439#issuecomment-2485302976). We will break those users; this is a case of [Hyrum's law](https://www.hyrumslaw.com/).

[Relevant xkcd](https://xkcd.com/1172/)

File: crates/ruff/tests/lint.rs [hunk 3]
```diff
@@ -1966,3 +1966,73 @@ fn nested_implicit_namespace_package() -> Result<()> {
...
+success: false
+exit_code: 2
+----- stdout -----
+
+----- stderr -----
+ruff failed
+  Cause: Failed to parse [TMP]/ruff.toml
+  Cause: TOML parse error at line 2, column 2
+  |
+2 | [lint.flake8-import-conventions.aliases]
```
Comment (MichaReiser) [inline crates/ruff/tests/lint.rs:1999]: Hmm. The errors aren't great. Let's at least include the alias in the error message to help users figure out what's going on. The same for the module name.

File: crates/ruff_workspace/src/options.rs [hunk 4]
```diff
@@ -1327,6 +1329,7 @@ pub struct Flake8ImportConventionsOptions {
             scipy = "sp"
         "#
     )]
+    #[serde(deserialize_with = "deserialize_and_validate_aliases")]
     pub aliases: Option<FxHashMap<String, String>>,
```
Comment (MichaReiser) [inline crates/ruff_workspace/src/options.rs:1333]: We would probably get better error messages if you create a newtype for `ModuleName` and `Alias` and implement `Deserialize` for them. I would expect that serde can then narrow the error message to the specific line rather than the entire table

**Review by MichaReiser — CHANGES_REQUESTED** [review]
Thanks for adding the integration tests. They show that the error messages aren't great. We should either:

* minimal: Include the alias and module name in the error message
* better: Use newtype wrappers for `Module` and `Alias` (`FxHashMap<ModuleName, Alias>`) and implement `Deserialize` on the newtype wrappers. That should allow serde to highlight the relevant line and column in the error message.

File: crates/ruff_workspace/src/options.rs (hunk 4 above)
Comment (AlexWaygood) [reply crates/ruff_workspace/src/options.rs:1333]: This PR does actually already seem to be a small improvement on the status quo when it comes to line numbers. Currently if I make this change to typeshed's pyproject.toml file:

```diff
diff --git a/pyproject.toml b/pyproject.toml
index 46014bcd2..927da6162 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -111,6 +111,9 @@ ignore = [
     "E501", # Line too long
 ]
 
+[tool.ruff.lint.flake8-import-conventions.aliases]
+"pandas" = 42
+
```

Then Ruff gives me this error message:

```
ruff failed
  Cause: Failed to parse /Users/alexw/dev/typeshed/pyproject.toml
  Cause: TOML parse error at line 27, column 1
   |
27 | [tool.ruff.lint]
   | ^^^^^^^^^^^^^^^^
invalid type: integer `42`, expected a string
```

**Comment by MichaReiser** [comment]
I pushed a change that implements `Deserialize` for the key and value. I'm surprised that serde isn't better at handling this.

**Review by MichaReiser — APPROVED** [review]
@AlexWaygood should we merge?

**Review by AlexWaygood — APPROVED** [review]
Thanks @dylwil3!

**Comment by dylwil3** [comment]
@MichaReiser you beat me to it! Much improved error message, thanks!
