### PR TITLE
[`unconventional-import-alias`] Fix infinite loop between ICN001 and I002 (`ICN001`)

### LINKED ISSUE #14389: [Infinite loop] ICN001 conflicts with I002 and F401 if an unused unconventionally aliased import is required
[`unconventional-import-alias` (ICN001)](https://docs.astral.sh/ruff/rules/unconventional-import-alias/) conflicts with [`missing-required-import` (I002)](https://docs.astral.sh/ruff/rules/missing-required-import/) in Ruff 0.7.4 when [`unused-import` (F401)](https://docs.astral.sh/ruff/rules/unused-import/) is also enabled, if an import is required without a conventional alias but is unused. ICN001’s fix should be skipped for required imports, even if the required imports lack conventional aliases. It would still be helpful for ICN001 to report a violation without a fix.

```console
$ echo 1 | ruff check --isolated --select I002,ICN001,F401 --config 'lint.isort.required-imports = ["import pandas"]' - --unsafe-fixes --fix

error: Failed to converge after 100 iterations.

This indicates a bug in Ruff. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BInfinite%20loop%5D

...quoting the contents of `-`, the rule codes ICN001, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

import pandas
1
-:1:8: ICN001 `pandas` should be imported as `pd`
  |
1 | import pandas
  |        ^^^^^^ ICN001
2 | 1
  |
  = help: Alias `pandas` to `pd`

Found 101 errors (100 fixed, 1 remaining).
[*] 1 fixable with the --fix option.
```

In that example, I002 inserts `import pandas`, ICN001 changes it to `import pandas as pd`, I002 inserts `import pandas` again, F401 removes the unused `import pandas as pd`, and then back to ICN001 and so on.

### PR DESCRIPTION
**Pull request by ntBre**
## Summary

This fixes the infinite loop reported in #14389 by raising an error to the user about conflicting ICN001 (`unconventional-import-alias`) and I002 (`missing-required-import`) configuration options.

## Test Plan

Added a CLI integration test reproducing the old behavior and then confirming the fix.

Closes #14389

### CODE REVIEW

**Comment by MichaReiser** [comment]
Can you tell me about what you tried to do in the configuration and why it didn't work?

**Comment by ntBre** [comment]
Well, I didn't really try anything exactly. I looked at #14477 that @AlexWaygood sent me as a similar fix, and then I spent some time looking through how configurations are constructed. But #14477 looked like validation on a single configuration field that could be handled during deserialization, while this issue looks to me like it requires validation between two configuration fields (`LinterSettings.isort.required_imports` and `LinterSettings.flake8_import_conventions.aliases`), so I didn't think I could handle it in the same way.

Then I found `LintConfiguration::as_rule_table`, which looked like a possible place to do this kind of validation. I only noticed warnings being emitted earlier, but now I see that it returns a `Result`. Could I do the validation there and return an `Err` on this conflict? Or if you have another suggestion I'd be happy to hear it. I should have asked before the PR, but this approach was mentioned in the issue, and it seemed reasonable to me too.

**Comment by MichaReiser** [comment]
There are a few places where we verify configurations but they all have their trade-offs:

* Inside `Configuration::from_options`: The main advantage validating options in `from_options` is that Ruff knows the corresponding configuration file, allowing it to point users directly to which file contains the incorrect configuration. However, `from_options` is called before combining different configuration file, meaning, it's an incomplete view. 
* Inside `Configuration::into_settings`: `into_settings` is called after all configuration files were combined. It's where Ruff has a complete view of all settings, but it no longer knows the source of individual setting values.

In your case, `Configuration::into_settings` is probably the better fit because you need the fully resolved configuration.

File: crates/ruff_workspace/src/configuration.rs [hunk 1]
```diff
@@ -1553,6 +1561,30 @@ fn warn_about_deprecated_top_level_lint_options(
...
+        let name = required_import.qualified_name().to_string();
+        if let Some(alias) = flake8_import_conventions.aliases.get(&name) {
+            writeln!(err_body, "    - {name} -> {alias}").unwrap();
+        }
+    }
+
+    if !err_body.is_empty() {
+        return Err(anyhow!(
+            "isort required import (I002) conflicts with unconventional import alias (ICN001):\
+                \n{err_body}"
```
Comment (MichaReiser) [inline crates/ruff_workspace/src/configuration.rs:1581]: Can we add an advise on how to resolve the error

File: crates/ruff_workspace/src/configuration.rs [hunk 2]
```diff
@@ -1553,6 +1561,30 @@ fn warn_about_deprecated_top_level_lint_options(
...
+    for required_import in &isort.required_imports {
+        let name = required_import.qualified_name().to_string();
+        if let Some(alias) = flake8_import_conventions.aliases.get(&name) {
+            writeln!(err_body, "    - {name} -> {alias}").unwrap();
+        }
+    }
+
+    if !err_body.is_empty() {
+        return Err(anyhow!(
+            "isort required import (I002) conflicts with unconventional import alias (ICN001):\
```
Comment (MichaReiser) [inline crates/ruff_workspace/src/configuration.rs:1580]: Should we use the actual setting names here?

**Review by MichaReiser — APPROVED** [review]
Lgtm

Would you mind updating the PR summary to reflect that this is now implemented in the settings

**Comment by ntBre** [comment]
I updated the PR summary and expanded the error message. Is the new message along the lines of what you had in mind?

**Comment by MichaReiser** [comment]
Looks good, thanks

File: crates/ruff_workspace/src/configuration.rs [hunk 3]
```diff
@@ -1553,6 +1561,34 @@ fn warn_about_deprecated_top_level_lint_options(
...
+fn conflicting_import_settings(
+    isort: &isort::settings::Settings,
+    flake8_import_conventions: &flake8_import_conventions::settings::Settings,
+) -> Result<()> {
+    use std::fmt::Write;
+    let mut err_body = String::new();
+    for required_import in &isort.required_imports {
+        let name = required_import.qualified_name().to_string();
+        if let Some(alias) = flake8_import_conventions.aliases.get(&name) {
+            writeln!(err_body, "    - {name} -> {alias}").unwrap();
```
Comment (AlexWaygood) [inline crates/ruff_workspace/src/configuration.rs:1574]: Maybe add backticks? Not sure though

```suggestion
            writeln!(err_body, "    - `{name}` -> `{alias}`").unwrap();
```

**Review by AlexWaygood — APPROVED** [review]
Nice!

File: crates/ruff_workspace/src/configuration.rs [hunk 4]
```diff
@@ -1553,6 +1561,34 @@ fn warn_about_deprecated_top_level_lint_options(
...
+        }
+    }
+
+    if !err_body.is_empty() {
+        return Err(anyhow!(
+            "Required import specified in `lint.isort.required-imports` (I002) \
+            conflicts with the required import alias specified in either \
+            `lint.flake8-import-conventions.aliases` or \
+            `lint.flake8-import-conventions.extend-aliases`(ICN001):\
```
[the remark this answers is not in the document]
Comment (ntBre) [reply crates/ruff_workspace/src/configuration.rs:1583]: Good catches again, thank you!
