### PR TITLE
Handle parenthesized arguments in `remove_argument`

### LINKED ISSUE #18798: RUF056 fix introduces a syntax error for a parenthesized value
### Summary

The fix for [`falsy-dict-get-fallback` (RUF056)](https://docs.astral.sh/ruff/rules/falsy-dict-get-fallback/) introduces a syntax error when the falsy value is parenthesized.

```console
$ cat >ruf056.py <<'# EOF'
d = {}
not d.get("key", (False))
# EOF

$ ruff --isolated check ruf056.py --select RUF056 --preview --diff 2>&1 | grep error:
error: Fix introduced a syntax error. Reverting all changes.
```

### Version

ruff 0.12.0 (87f0feb21 2025-06-17)

### PR DESCRIPTION
**Pull request by LaBatata101**
## Summary
Fix `remove_argument` to handle parenthesized arguments properly. Previously, it would not delete the entire parenthesized argument, leaving the close parenthesis. This caused the autofix of some rules to introduce a syntax error, like in the case of #18798.

 I had to update the function signature to include the `CommentRanges`, that's why there are some many files changed.

Fixes #18798

## Test Plan
Add regression test

### CODE REVIEW

File: crates/ruff_linter/src/fix/edits.rs [hunk 1]
```diff
@@ -240,12 +241,24 @@ pub(crate) fn remove_argument<T: Ranged>(
...
+            .arguments_source_order()
+            .find(|arg| arg.range() == argument.range())
+            .context("Unable to find argument")?;
+        let end = if let Some(range) =
+            parenthesized_range(arg.value().into(), arguments.into(), comment_ranges, source)
+        {
+            range.end()
+        } else {
+            argument.end()
+        };
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/fix/edits.rs]: this looks like the correct fix, but we need to apply the fix more holistically -- the same bug is present in the other branches of this `match`. Your current PR only fixes `remove_argument` if the argument being removed is the _last_ argument.

For example, on your branch:

```
(experiment) ~/dev/ruff (fix-RUF056)⚡ % cat foo.py
range((0), 42)
(experiment) ~/dev/ruff (fix-RUF056)⚡ % cargo run -- check foo.py --no-cache --preview --select=PIE808 --diff
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.36s
     Running `target/debug/ruff check foo.py --no-cache --preview --select=PIE808 --diff`
error: Fix introduced a syntax error in `foo.py` with rule codes PIE808: unexpected EOF while parsing at byte range 11..11
---
range((42)

---
```

**Review by AlexWaygood — CHANGES_REQUESTED** [review]
Thanks!

File: crates/ruff_linter/src/fix/edits.rs (hunk 1 above)
Comment (LaBatata101) [reply crates/ruff_linter/src/fix/edits.rs]: Yeah, I knew that. I was expecting one of the reviewers to point out a rule that would trigger the other branch so that I could test it 🙂

Comment (AlexWaygood) [reply crates/ruff_linter/src/fix/edits.rs]: can you add `range((0), 42)` as a test case to the `PIE808` fixtures?

Comment (LaBatata101) [reply crates/ruff_linter/src/fix/edits.rs]: Done!

**Review by AlexWaygood — APPROVED** [review]
Thanks!
