### PR TITLE
[flake8-return] Only add return None at end of function (RET503)

### LINKED ISSUE #5765: Autofix for RET503 breaks RET505 (in one case)
On the latest version of `ruff` (0.0.278) this fails on the following code:

```sh
ruff --select RET503,RET505 test.py --fix --isolated
# test.py:11:9: RET505 Unnecessary `else` after `return` statement
```

```python
def main(value: str) -> int | None:
    if value == "one":
        return 1

    if value.startswith("do_stuff"):
        print("doing stuff")

        if value.endswith("haha"):
            print("haha")
        else:
            print("Instruction unclear.")
    else:
        print("Doing nothing.")
```

That is because the autofix for RET503 inserts `return None` in all three
branches of the if/else tree:

```diff
--- test.py
+++ test.py
@@ -7,7 +7,10 @@
 
         if value.endswith("haha"):
             print("haha")
+            return None
         else:
             print("Instruction unclear.")
+            return None
     else:
         print("Doing nothing.")
+        return None
```

But that is not compliant with RET505.

The fix in this case is to insert `return None` at the end of the function instead of in each branch in the if/else tree.

```python
def main(value: str) -> int | None:
    if value == "one":
        return 1

    if value.startswith("do_stuff"):
        print("doing stuff")

        if value.endswith("haha"):
            print("haha")
        else:
            print("Instruction unclear.")
    else:
        print("Doing nothing.")
    return None
```

Not sure it is worth the effort to update behavior of the `RET503` autofix for this case. But I thought I should report it.

### PR DESCRIPTION
**Pull request by JonathanPlasse**
## Summary

- Fix #5765

In `RET503` documentation, it is said that it only adds `return None` at the end of functions.
The current behavior can add `return None` in multiple place in the function, but not at the end of the function.
This behavior does not match the documentation and goes against other `flake8-return` rules like `RET505` and caused people to open #5765.
The new behavior only adds `return None` at the end of functions like in the documentation and results in more readable code.
The new behavior is only available in preview mode.
The range of `RET503` is changed to be the entire function, as it will be more clear it concerns the entire function.

Before
```python
def main(value: str) -> int | None:
    if value == "one":
        return 1

    if value.startswith("do_stuff"):
        print("doing stuff")

        if value.endswith("haha"):
            print("haha")
            return None
        else:
            print("Instruction unclear.")
            return None
    else:
        print("Doing nothing.")
        return None
```
After
```python
def main(value: str) -> int | None:
    if value == "one":
        return 1

    if value.startswith("do_stuff"):
        print("doing stuff")

        if value.endswith("haha"):
            print("haha")
        else:
            print("Instruction unclear.")
    else:
        print("Doing nothing.")
    return None
```

## Test Plan

I added a preview snapshot for `RET503`.
I compared the diff between the `RET503` stable and preview snapshot.
I checked the ecosystem reports and fixed one regression.

### CODE REVIEW

File: crates/ruff_linter/src/rules/flake8_return/rules/function.rs [hunk 1]
```diff
@@ -440,20 +440,45 @@ fn is_noreturn_func(func: &Expr, semantic: &SemanticModel) -> bool {
...
             ..
         }) => {
+            let mut result = false;
             if let Some(last_stmt) = body.last() {
-                implicit_return(checker, last_stmt);
+                if has_implicit_return(checker, last_stmt) {
+                    result = true;
+                    if checker.settings.preview.is_enabled() {
+                        return result;
+                    }
```
Comment (JonathanPlasse) [inline crates/ruff_linter/src/rules/flake8_return/rules/function.rs:471]: Early return if in preview mode because we only need to know if the function has at least one implicit return to add a single `return None` at the end of the function.
The stable version can add multiple return so it cannot return early.
The code should be simplified once the preview version become stable.

**Comment by JonathanPlasse** [comment]
A comment should be added that when the preview version becomes stable the code can be simplified with early return everywhere.

**Comment by AlexWaygood** [comment]
> Will it be included in Ruff 0.5.0?

Just seen this -- unfortunately I just set the release workflow in motion, so unfortunately not. Sorry :-(

**Comment by JonathanPlasse** [comment]
No worries.

**Comment by JonathanPlasse** [comment]
Will it be included in Ruff 0.6.0?

**Comment by MichaReiser** [comment]
I don't think this requires a minor release, considering that the change is gated behind preview mode.

File: crates/ruff_linter/src/rules/flake8_return/rules/function.rs [hunk 2]
```diff
@@ -473,76 +498,73 @@ fn implicit_return(checker: &mut Checker, stmt: &Stmt) {
...
             }
-            checker.diagnostics.push(diagnostic);
+            true
         }
     }
 }
 
+/// RET503
+fn implicit_return(checker: &mut Checker, function_def: &ast::StmtFunctionDef, stmt: &Stmt) {
+    if has_implicit_return(checker, stmt) && checker.settings.preview.is_enabled() {
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_return/rules/function.rs:563]: I don't have a great solution but I do find it a bit surprising that `has_implicit_return` adds diagnostics in the non preview mode. 

I'm somewhat inclined to duplicate the logic between preview and non-preview mode. That should also make it much easier when stabilizing the new behavior (and it's not that much code that needs copying). Unless you see a way of how we can avoid the side-effects of `has_implicit_return` in stable (e.g. could it return a `Vec` with all the statements for which diagnostics should be added?)

Comment (MichaReiser) [reply crates/ruff_linter/src/rules/flake8_return/rules/function.rs:563]: I don't mind going ahead with the PR as is but I'm interested to hear what you think of duplicating the logic OR maybe you have another idea to make this a bit clearer

Comment (JonathanPlasse) [reply crates/ruff_linter/src/rules/flake8_return/rules/function.rs]: I use the `Vec` solution to remove the side effects. 
The code is nicer.
Thank you for suggesting it.

Comment (MichaReiser) [reply crates/ruff_linter/src/rules/flake8_return/rules/function.rs]: Thanks. Will merge now :)

Comment (JonathanPlasse) [reply crates/ruff_linter/src/rules/flake8_return/rules/function.rs]: You are welcome
