### PR TITLE
[ty] Expand class bases in per-base lint checks

### LINKED ISSUE #3293: [panic] starred fixed-tuple base unpacked to a `@final` class panics `check_static_class_definitions`
## Summary

While reviewing the fix in https://github.com/astral-sh/ruff/pull/24695 (which closed #3290), I noticed it only replaced `class_node.bases()[i]` indexing in the `try_mro` error-handling arms. The same bug pattern — using an *expanded*-bases index to index into the *AST* bases list — still exists in the [large per-base lint loop](https://github.com/astral-sh/ruff/blob/3834a4f0149dbb9c473331ed754d03b6c5bfcc5d/crates/ty_python_semantic/src/types/infer/builder/post_inference/static_class.rs#L221) in `check_static_class_definitions`. Several per-base diagnostics in that loop (`SUBCLASS_OF_FINAL_CLASS`, `INVALID_NAMED_TUPLE`, `INVALID_BASE`, `INVALID_PROTOCOL`, `INVALID_TYPED_DICT_HEADER`, `INVALID_GENERIC_CLASS`, frozen-dataclass inheritance) are likely to panic on out-of-bounds when a starred fixed-length-tuple base expands the semantic bases list past the AST bases list length.

I reproduce the simplest such case with `SUBCLASS_OF_FINAL_CLASS` below.

## Reproducer

```python
class X(*(int, bool)):
    pass
```

## Output (on `main` at 3834a4f)

```
error[panic]: Panicked at crates/ty_python_semantic/src/types/infer/builder/post_inference/static_class.rs:349:64 when checking `poc_final.py`: `index out of bounds: the len is 1 but the index is 1`
info: This indicates a bug in ty.
...
info: query stacktrace:
   0: infer_scope_types_impl(Id(1000))
             at crates/ty_python_semantic/src/types/infer.rs:263
   1: check_file_impl(Id(c00))
             at crates/ty_project/src/lib.rs:605
```

`static_class.rs:349` is the `SUBCLASS_OF_FINAL_CLASS` report inside the loop at line 221:

```rust
for (i, base_class) in class.explicit_bases(db).iter().enumerate() {
    // ...
    if base_class.is_final(db) {
        if let Some(builder) =
            context.report_lint(&SUBCLASS_OF_FINAL_CLASS, &class_node.bases()[i])
```

`class.explicit_bases(db)` contains the expanded list `[int, bool]` (len 2), but `class_node.bases()` is `[Starred(Tuple(int, bool))]` (len 1), so `class_node.bases()[1]` panics.

The same pattern produces additional panic paths in the same loop; `bool` just happens to be the easiest one to hit because it's `@final` in typeshed. Others cases could be constructed with starred tuples containing e.g. bare `Generic`, `Protocol[...]` subscripted bases mixed with PEP-695 type params, invalid TypedDict bases, etc, but I haven't tested them yet.

## Version

Tested on `main` at 3834a4f.

### PR DESCRIPTION
**Pull request by kc0506**
## Summary

The per-base checks in `check_static_class_definitions` iterate over `class.explicit_bases(db)` (the expanded bases list) but use the loop index to look up the AST node via `&class_node.bases()[i]`. When a starred base unpacks a fixed-length tuple, the expanded list is longer than the AST bases list and the indexing panics -- e.g. `class X(*(int, bool)): ...` panics in the `SUBCLASS_OF_FINAL_CLASS` branch.

Closes astral-sh/ty#3293.

A related panic was reported in astral-sh/ty#3290 and fixed in #24695, but #24695 only addressed the `try_mro` arms. This PR applies the same fix to the per-base lint loop, reusing the `expanded_class_base_entries` abstraction introduced there.

## Test Plan

Two cases are added in `mdtest/mro.md` covering `subclass-of-final-class` via starred unpacking.

### CODE REVIEW

File: crates/ty_python_semantic/src/types/infer/builder/post_inference/static_class.rs [hunk 1]
```diff
@@ -210,46 +210,53 @@ pub(crate) fn check_static_class_definitions<'db>(
...
+        let source_node = entry.source_node();
+        let base_class = entry.ty();
+
         if class_kind == Some(CodeGeneratorKind::NamedTuple)
             && !matches!(
                 base_class,
                 Type::SpecialForm(SpecialFormType::NamedTuple)
                     | Type::KnownInstance(KnownInstanceType::SubscriptedGeneric(_))
             )
+            && let Some(node) = source_node
```
Comment (charliermarsh) [inline crates/ty_python_semantic/src/types/infer/builder/post_inference/static_class.rs:235]: Does this mean that we no longer report some of these diagnostics if they come from a `*foo` variable and thus don't have a source node?

Comment (carljm) [reply crates/ty_python_semantic/src/types/infer/builder/post_inference/static_class.rs:235]: Yeah - I think we should push this check one layer down and use a fallback node (maybe the entire bases?) if we don't have a `source_node`, but ensure we still emit the diagnostic (and add a test for this).

Comment (kc0506) [reply crates/ty_python_semantic/src/types/infer/builder/post_inference/static_class.rs:235]: Did you mean cases like `class A(*foo): ...` ? In those cases `source_node()` still returns `Some(&Expr)`, not `None`. `Synthetic` (the case `source_node()` is `None`) is currently only used for the `sys.version_info` tuple base, which is a different path.

File: crates/ty_python_semantic/src/types/infer/builder/post_inference/static_class.rs [hunk 2]
```diff
@@ -210,46 +210,53 @@ pub(crate) fn check_static_class_definitions<'db>(
...
+                {
                     // Unsubscripted `Generic` can appear in the MRO of many classes,
                     // but it is never valid as an explicit base class in user code.
                     builder.into_diagnostic("Cannot inherit from plain `Generic`");
                 }
                 continue;
             }
             Type::KnownInstance(KnownInstanceType::SubscriptedGeneric(new_context)) => {
-                let Some((previous_index, previous_context)) = protocol_base_with_generic_context
+                let Some((prior_node, previous_context)) = protocol_base_with_generic_context
```
Comment (charliermarsh) [inline crates/ty_python_semantic/src/types/infer/builder/post_inference/static_class.rs]: `previous_node`? (I see this matched the name below, but seems a bit more consistent.)

File: crates/ty_python_semantic/src/types/infer/builder/post_inference/static_class.rs (hunk 1 above)
Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/infer/builder/post_inference/static_class.rs:235]: Ah you're right!

File: crates/ty_python_semantic/src/types/infer/builder/post_inference/static_class.rs (hunk 2 above)
Comment (kc0506) [reply crates/ty_python_semantic/src/types/infer/builder/post_inference/static_class.rs]: fixed!

**Review by charliermarsh — APPROVED** [review]

**Comment by charliermarsh** [comment]
Thanks!
