### PR TITLE
[`ruff`] Fix `B004` to skip invalid `hasattr`/`getattr` calls

### LINKED ISSUE #20440: B004 false positives for invalid or obfuscated `hasattr` and `getattr` calls
### Summary

[`unreliable-callable-check` (B004)](https://docs.astral.sh/ruff/rules/unreliable-callable-check/) doesn’t validate the arguments of `hasattr` or `getattr`.

It should be suppressed when `hasattr` is called with anything another than two positional non-starred arguments, lest it suppress or introduce an exception. [Example](https://play.ruff.rs/f11372d2-11f5-4800-a5ab-5fb7f39f86cb):
```console
$ cat >b004.py <<'# EOF'
try: print(hasattr(0, "__call__", 0, x=0))
except TypeError as e: print(e)

try: print(hasattr(*(), "__call__", "split"))
except TypeError as e: print(e)
# EOF

$ python b004.py
hasattr() takes no keyword arguments
True

$ ruff --isolated check b004.py --select B004 --fix
Found 2 errors (2 fixed, 0 remaining).

$ cat b004.py
try: print(callable(0))
except TypeError as e: print(e)

try: print(callable(*()))
except TypeError as e: print(e)

$ python b004.py
False
callable() takes exactly one argument (0 given)
```

Similarly, B004 should only apply when `getattr` is called with two or three positional non-starred arguments.

### Version

ruff 0.13.0 (a1fdd66f1 2025-09-10)

### PR DESCRIPTION
**Pull request by TaKO8Ki**
## Summary

Fixes #20440

Fix B004 to skip invalid hasattr/getattr calls

- Add argument validation for `hasattr` and `getattr`
- Skip B004 rule when function calls have invalid argument patterns

## Test Plan

Add comprehensive test cases for invalid argument patterns including unpacking to `B004.py`

### CODE REVIEW

File: crates/ruff_linter/src/rules/flake8_bugbear/rules/unreliable_callable_check.rs [hunk 1]
```diff
@@ -103,7 +104,21 @@ pub(crate) fn unreliable_callable_check(
...
+        "hasattr" => {
+            // hasattr should have exactly 2 positional arguments and no keywords
+            args.len() == 2 && keywords.is_empty()
+        }
+        "getattr" => {
+            // getattr should have 2 or 3 positional arguments and no keywords
+            (args.len() == 2 || args.len() == 3) && keywords.is_empty()
+        }
+        _ => return,
+    };
```
Comment (dylwil3) [inline crates/ruff_linter/src/rules/flake8_bugbear/rules/unreliable_callable_check.rs:122]: We may as well move the `keywords` check all the way to the beginning of the function. (You could even leave the original function unmodified and do the `keywords` check at the call site - but it's a little more self-documenting to keep the logic inside the function, I guess).

Comment (TaKO8Ki) [reply crates/ruff_linter/src/rules/flake8_bugbear/rules/unreliable_callable_check.rs:122]: I've moved the keywords count check to the beginning of `unreliable_callable_check`.
