### PR TITLE
Show fixes by default

### LINKED ISSUE #7352: CLI: Show fixes by default in `ruff check`
Requires #7350 for opt-out of display.

`ruff check` should display fixes that Ruff can apply. Currently this is only possible for the whole file with `--diff`.

Some fixes may modify content across a file, e.g. when renaming a binding. We should limit the display of fixes to roughly match the range of source context displayed (#7349). If we do not display the entire fix, we should include a notice of the number of additional lines that will be modified if the fix is applied. Naively, we may be able to implement this by only selecting a portion of the fix. In a more comprehensive implementation, we may need to add a new diagnostic range attribute for this display and address it in each problem case.

> Clippy has a nice example user experience of showing fixes:
> 
> 
> ```
> error[E0308]: mismatched types
> --> crates/ruff_python_semantic/src/model.rs:224:21
>     |
> 224 |             source: &self.stmt_id,
>     |                     ^^^^^^^^^^^^^ expected `Option<NodeId>`, found `&Option<NodeId>`
>     |
>     = note:   expected enum `std::option::Option<node::NodeId>`
>             found reference `&std::option::Option<node::NodeId>`
> help: consider removing the borrow
>     |
> 224 -             source: &self.stmt_id,
> 224 +             source: self.stmt_id,
>     |
> 
> For more information about this error, try `rustc --explain E0308`.
> ```

### PR DESCRIPTION
**Pull request by ntBre**
## Summary

This PR fixes #7352 by exposing the `show_fix_diff` option used in our snapshot tests in the CLI. As the issue suggests, we plan to make this the default output format in the future, so this is added to the `full` output format in preview for now.

This turned out to be pretty straightforward. I just used our existing `Applicability` settings to determine whether or not to print the diff. 

The snapshot differences are because we now set `Applicability::DisplayOnly` for our snapshot tests. This `Applicability` is also used to determine whether or not the fix icon (`[*]`) is rendered, so this is now shown for display-only fixes in our snapshots. This was already the case previously, but we were only setting `Applicability::Unsafe` in these tests and ignoring the `Applicability` when rendering fix diffs. CLI users can't enable display-only fixes, so this is only a test change for now, but this should work smoothly if we decide to expose a `--display-only-fixes` flag or similar in the future.

I also deleted the `PrinterFlags::SHOW_FIX_DIFF` flag. This was completely unused before, and it seemed less confusing just to delete it than to enable it in the right place and check it along with the `OutputFormat` and `preview`.

## Test Plan

I only added one CLI test for now. I'm kind of assuming that we have decent coverage of the cases where this shouldn't be firing, especially the `output_format` CLI test, which shows that this definitely doesn't affect non-preview `full` output. I'm happy to add more tests with different combinations of options, if we're worried about any in particular. I did try `--diff` and `--preview` and a few other combinations manually.

And here's a screenshot using our trusty UP049 example from the design discussion confirming that all the colors and other formatting still look as expected:

image

And one with an unsafe fix to see the footer:

image

## Related issues and PR
- https://github.com/astral-sh/ruff/issues/7352
- https://github.com/astral-sh/ruff/pull/12595
- https://github.com/astral-sh/ruff/issues/12598
- https://github.com/astral-sh/ruff/issues/12599
- https://github.com/astral-sh/ruff/issues/12600

I think we could probably close all of these issues now. I think we've either resolved or avoided most of them, and if we encounter them again with the new output format, it would probably make sense to open new ones anyway.

### CODE REVIEW

**Review by zanieb — APPROVED** [review]

File: crates/ruff_db/src/diagnostic/mod.rs [hunk 1]
```diff
@@ -349,6 +349,13 @@ impl Diagnostic {
         self.fix().is_some()
     }
 
+    /// Returns `true` if the diagnostic is [`fixable`](Diagnostic::fixable) and applies at the
+    /// configured applicability level.
+    pub fn fix_applies(&self, config: &DisplayDiagnosticConfig) -> bool {
```
Comment (dhruvmanila) [inline crates/ruff_db/src/diagnostic/mod.rs]: nit: `fix_applicable` / `is_fix_applicable`

Comment (zanieb) [reply crates/ruff_db/src/diagnostic/mod.rs]: I was also thinking about this but landed on not saying something :) I think my best idea was `has_applicable_fix`

Comment (zanieb) [reply crates/ruff_db/src/diagnostic/mod.rs]: (I think the `is_applicable` verbiage makes more sense on the fix type)

Comment (zanieb) [reply crates/ruff_db/src/diagnostic/mod.rs]: (@ntBre un-resolving because I commented as you were resolving. Just for visibility — I don't have strong feelings)

Comment (ntBre) [reply crates/ruff_db/src/diagnostic/mod.rs]: Ah `diagnostic.has_applicable_fix` does read nicely, thanks!
