### PR TITLE
[`pylint`] Mark `PLC0207` fixes as unsafe when `*args` unpacking is present

### LINKED ISSUE #19660: `*` unpacking should make PLC0207 fix unsafe
### Summary

The fix for [`missing-maxsplit-arg` (PLC0207)](https://docs.astral.sh/ruff/rules/missing-maxsplit-arg/) should be marked unsafe when the call contains a `*` unpacking, as it already is for a `**` unpacking, because it can induce an error. [Example](https://play.ruff.rs/098e6a46-86e7-42f9-b851-0e026d395e20):
```console
$ cat >plc0207.py <<'# EOF'
"www.example.com".split(".", *[-1])[0]
# EOF

$ ruff --isolated check plc0207.py --select PLC0207 --preview --fix
Found 1 error (1 fixed, 0 remaining).

$ cat plc0207.py
"www.example.com".split(".", *[-1], maxsplit=1)[0]

$ python plc0207.py 2>&1 | tail -n 1
TypeError: split() takes at most 2 arguments (3 given)
```

### Version

ruff 0.12.7 (c5ac99889 2025-07-29)

### PR DESCRIPTION
**Pull request by danparizher**
## Summary

Fixes #19660

### CODE REVIEW

File: crates/ruff_linter/src/rules/pylint/rules/missing_maxsplit_arg.rs [hunk 1]
```diff
@@ -38,8 +38,8 @@ use crate::{AlwaysFixableViolation, Applicability, Edit, Fix};
 /// ```
 ///
 /// ## Fix Safety
-/// This rule's fix is marked as unsafe for `split()`/`rsplit()` calls that contain `**kwargs`, as
-/// adding a `maxsplit` keyword to such a call may lead to a duplicate keyword argument error.
+/// This rule's fix is marked as unsafe for `split()`/`rsplit()` calls that contain `*args` or `**kwargs`, as
+/// adding a `maxsplit` keyword to such a call may lead to a duplicate keyword argument error or too many arguments error.
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/pylint/rules/missing_maxsplit_arg.rs]: This sounds slightly awkward to me. What about something like:


```suggestion
/// This rule's fix is marked as unsafe for `split()`/`rsplit()` calls that contain `*args` or `**kwargs` arguments, as
/// adding a `maxsplit` argument to such a call may lead to duplicated arguments.
```

Ideally re-wrapped to 80 or 100 columns. I may have said "arguments" too many times, but this is a little closer to what I want, I think.

I kind of like covering both "duplicate" and "too many" arguments, but I wasn't sure it worked with the rest of it. I think "duplicate(d)" covers both cases well enough, but I'm open to alternatives.

File: crates/ruff_linter/src/rules/pylint/rules/missing_maxsplit_arg.rs [hunk 2]
```diff
@@ -201,11 +201,12 @@ pub(crate) fn missing_maxsplit_arg(checker: &Checker, value: &Expr, slice: &Expr
     diagnostic.set_fix(Fix::applicable_edits(
         maxsplit_argument_edit,
         split_type_edit,
-        // If keyword.arg is `None` (i.e. if the function call contains `**kwargs`), mark the fix as unsafe
-        if arguments
-            .keywords
-            .iter()
-            .any(|keyword| keyword.arg.is_none())
+        // If there are starred expressions (*args) or keyword arguments with None arg (**kwargs), mark the fix as unsafe
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/pylint/rules/missing_maxsplit_arg.rs]: Another docs nit:

```suggestion
        // Mark the fix as unsafe, if there are `*args` or `**kwargs`
```

I didn't mind the `keyword.arg is None` part before, but I guess it's pretty self-explanatory with the code just below it. If you want to try to work the parentheticals back in, it's fine with me.

File: crates/ruff_linter/resources/test/fixtures/pylint/missing_maxsplit_arg.py [hunk 3]
```diff
@@ -182,3 +182,27 @@ def get_string(self) -> str:
...
+"1,2,3".split(",", *args_list)[0]
+args_list = [-1]
+"1,2,3".rsplit(",", *args_list)[-1]
+args_list = [1]
+"1,2,3".rsplit(",", *args_list)[-1]
+
+## Test mixed unpacked args and kwargs
+# Errors
+"1,2,3".split(",", *[-1], **{"maxsplit": 1})[0]
+"1,2,3".split(",", *[1], **{"maxsplit": 1})[0]
```
Comment (ntBre) [inline crates/ruff_linter/resources/test/fixtures/pylint/missing_maxsplit_arg.py]: These last two aren't actually producing errors. We explicitly look for `**{}` (unpacked dict _literal_) in this rule, unlike most cases, so I think you'd need to use a variable here or otherwise modify the test if you want to try both `*args` and `**kwargs`.

However, I'm not sure we really need this many test cases for this. The fix in the Rust code is simple enough I'd probably be fine with just one. Are there interesting edge cases among these that I might be missing here?

**Review by ntBre — APPROVED** [review]
Thanks! The code fix looks perfect to me, just a couple of docs nits and a question/suggestion about tests.

File: crates/ruff_linter/resources/test/fixtures/pylint/missing_maxsplit_arg.py (hunk 3 above)
Comment (danparizher) [reply crates/ruff_linter/resources/test/fixtures/pylint/missing_maxsplit_arg.py]: Unless we want to test for some pathological cases (like multiple unpacked dicts or weird combinations), I think a single test for each of these patterns is enough. I don't see any edge cases we're missing that would meaningfully change the rule's behavior.

**Review by ntBre — APPROVED** [review]
Thanks!
