### PR TITLE
[`refurb`] Mark fix as unsafe when the right-hand side is a string (`FURB171`)

### LINKED ISSUE #15268: FURB171: Potentially unsafe fix
FURB171 auto-fixes
```python
s in " "
```
into
```python
s == " "
```
But the Initial expression is equivalent to `char == "" or char == " "`, not `char == " "`.
It's a valid warning and safe fix for explicit collections like lists or sets, but probably should be disabled or at least moved to unsafe for strings.

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
## Summary

Resolves #15268.

## Test Plan

`cargo nextest run` and `cargo insta test`.

### CODE REVIEW

File: crates/ruff_linter/src/rules/refurb/rules/single_item_membership_test.rs [hunk 1]
```diff
@@ -90,7 +96,16 @@ pub(crate) fn single_item_membership_test(
...
+
+    let applicability = if right.is_string_literal_expr() {
+        Applicability::Unsafe
+    } else {
+        Applicability::Safe
+    };
+
+    diagnostic.set_fix(Fix::applicable_edit(edit, applicability));
+
     checker.diagnostics.push(diagnostic);
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/refurb/rules/single_item_membership_test.rs:109]: nit

```suggestion
    let fix = Fix::applicable_edit(edit, applicability);
    checker.diagnostics.push(diagnostic.with_fix(fix));
```

File: crates/ruff_linter/src/rules/refurb/rules/single_item_membership_test.rs [hunk 2]
```diff
@@ -25,6 +25,11 @@ use crate::fix::edits::pad;
 /// 1 == 1
 /// ```
 ///
+/// ## Fix safety
+///
+/// When the right-hand side is a string, the fix is marked as unsafe.
+/// This is because `c in "a"` is true both when `c` is `"a"` and when `c` is the empty string.
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/refurb/rules/single_item_membership_test.rs:31]:
```suggestion
/// This is because `c in "a"` is true both when `c` is `"a"` and when `c` is the empty string,
/// so the fix can change the behavior of your program in these cases.
```

**Review by AlexWaygood — COMMENTED** [review]
Nice, thanks! My only comment is that I wonder if we should even be emitting this lint if the r.h.s. is a string? It's quite possible that the user is deliberately exploiting the way `in` works with regard to string here, in which case it would be annoying to have to `noqa` the lint away.

That _does_ seem unlikely, though, so maybe it's better to continue emitting the lint and just mark the fix as unsafe. Not sure -- what do you think?

**Review by AlexWaygood — APPROVED** [review]
Thanks!
