### PR TITLE
[`playground`]: Fix non‑BMP code point handling in quick‑fixes and markers

### LINKED ISSUE #16266: Playground counts each non-BMP code point as two code points
### Description

The playground counts each non-BMP code point as two code points when applying fixes, leaving characters there that should have been replaced as part of the fix. [Here is an example.](https://play.ruff.rs/8aef5a51-fa9e-4d87-9634-537659f3c65a) The input is:
```python
dict(𠤪=1)
```
Applying the quick fix for [`unnecessary-collection-call` (C408)](https://docs.astral.sh/ruff/rules/unnecessary-collection-call/) incorrectly produces:
```python
{"𠤪": 1})
```
On the command line, though, Ruff 0.9.6 correctly fixes it to:
```python
{"𠤪": 1}
```

### PR DESCRIPTION
**Pull request by danparizher**
## Summary

Fixes #16266

Updated the playground to convert UTF‑32 (code point) columns from the WASM diagnostics/fixes into Monaco’s UTF‑16 columns when constructing both quick‑fix edit ranges and diagnostic markers in `playground/ruff/src/Editor/SourceEditor.tsx`.

With this change, applying the `C408` quick fix on `dict(𠤪=1)` now correctly yields `{"𠤪": 1}` without leaving a stray `)`.

### CODE REVIEW

File: crates/ruff_wasm/src/lib.rs [hunk 1]
```diff
@@ -228,27 +228,47 @@ impl Workspace {
...
-                            location: source_code.line_column(edit.start()).into(),
-                            end_location: source_code.line_column(edit.end()).into(),
-                            content: edit.content().map(ToString::to_string),
-                        })
-                        .collect(),
-                }),
+            .map(|msg| {
+                let range = msg.range().unwrap_or_default();
+                let start_loc = source_code.source_location(range.start(), PositionEncoding::Utf16);
+                let end_loc = source_code.source_location(range.end(), PositionEncoding::Utf16);
```
Comment (MichaReiser) [inline crates/ruff_wasm/src/lib.rs]: This works but it will break existing clients that assumed UTF8. 

I suggest adding `positionEncoding` a new argument to `new` (similar to ty) and storing it on the `Workspace` and then using it here.

This allows each user to use the encoding that best suits their use case.
