### PR TITLE
[ty] Unwrap `enum.nonmember` values

### LINKED ISSUE #1974: enum.nonmember has the wrong type
### Summary

https://play.ty.dev/2314690d-c925-4cc1-a5cc-418c928628ca

```python
from typing import reveal_type
import enum

class E(enum.Enum):
    A = enum.auto()
    X = enum.nonmember(123)

reveal_type(E.X)  # Revealed type: `Unknown | nonmember[int]`
```

This really should just be `int`.

### Version

ty 0.0.2

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

This PR unwraps the `enum.nonmember` type to match runtime behavior.

Closes https://github.com/astral-sh/ty/issues/1974.

### CODE REVIEW

File: crates/ty_python_semantic/src/types/class.rs [hunk 1]
```diff
@@ -2355,6 +2350,32 @@ impl<'db> ClassLiteral<'db> {
...
+            .inner
+            .place
+            .ignore_possibly_undefined()
+            .is_some_and(|ty| ty.contains_nonmember(db))
+        {
+            let is_enum_class = Type::ClassLiteral(self)
+                .is_subtype_of(db, KnownClass::Enum.to_subclass_of(db))
+                || self
+                    .metaclass(db)
+                    .is_subtype_of(db, KnownClass::EnumType.to_subclass_of(db));
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/class.rs]: This is a pretty subtle pair of conditions that need testing, and it looks like we already have the same check (with sense reversed) inside `enum_metadata`. Can we extract it as a reusable function?

File: crates/ty_python_semantic/src/types.rs [hunk 2]
```diff
@@ -912,6 +912,18 @@ impl<'db> Type<'db> {
...
     }
 
+    /// Returns `true` if this type is or contains an `enum.nonmember` instance.
+    pub(crate) fn contains_nonmember(&self, db: &'db dyn Db) -> bool {
+        match self {
+            Type::NominalInstance(instance) => instance.has_known_class(db, KnownClass::Nonmember),
+            Type::Union(union) => union
+                .elements(db)
+                .iter()
+                .any(|elem| elem.contains_nonmember(db)),
```
Comment (carljm) [inline crates/ty_python_semantic/src/types.rs]: Do we have a test for the case where this union handling is necessary?

File: crates/ty_python_semantic/src/types/class.rs [hunk 3]
```diff
@@ -5981,6 +6002,41 @@ impl SlotsKind {
...
 }
 
+/// Extracts the value type from an `enum.nonmember()` wrapper if present.
+///
+/// This looks up the symbol's bindings directly (bypassing `place_by_id`) to get the
+/// inferred type without the `Unknown` union from declared types. This is consistent
+/// with how `enum.member()` is handled in `enum_metadata`.
+///
+/// Returns `Some(value_type)` if the symbol is bound to a `nonmember[T]`, otherwise `None`.
+fn extract_nonmember_value<'db>(
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/class.rs]: Maybe this belongs better in `types/enums.rs`?

File: crates/ty_python_semantic/src/types/class.rs [hunk 4]
```diff
@@ -2355,6 +2350,32 @@ impl<'db> ClassLiteral<'db> {
...
+            .is_some_and(|ty| ty.contains_nonmember(db))
+        {
+            let is_enum_class = Type::ClassLiteral(self)
+                .is_subtype_of(db, KnownClass::Enum.to_subclass_of(db))
+                || self
+                    .metaclass(db)
+                    .is_subtype_of(db, KnownClass::EnumType.to_subclass_of(db));
+
+            if is_enum_class {
+                if let Some(nonmember_value_ty) = extract_nonmember_value(db, body_scope, name) {
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/class.rs]: The `member` variable above already has the `Nonmember` type. Looking at the implementation of `extract_nonmember_value`, it seems like we go through a lot of work just to get that same `Nonmember` instance type back again, and then we get its `value` attribute. So why can't we just work directly from the type we already have in hand, without going back to the place table etc?

**Comment by AlexWaygood** [comment]
I'll leave this to @carljm (since he's already reviewed) and/or @sharkdp (who originally implemented enums and `member`/`nonmember` for us)

File: crates/ty_python_semantic/resources/mdtest/enums.md [hunk 5]
```diff
@@ -451,6 +451,23 @@ class Answer(Enum):
...
+
+def coinflip() -> bool:
+    return True
+
+class WithConditionalNonmember(Enum):
+    A = 1
+    # Union of nonmember types: the nonmember is still unwrapped.
+    # This tests that `try_unwrap_nonmember_value` correctly handles
+    # unions containing nonmember instances.
+    B = nonmember("foo") if coinflip() else nonmember("bar")
```
Comment (carljm) [inline crates/ty_python_semantic/resources/mdtest/enums.md]: What happens if the wrapped types in the two branches are different? Should we union the wrapped types? Right now it seems we just arbitrarily pick the first one?

And what happens if some branches of the union are `nonmember(...)` and others are not?

I'm actually wondering why you added the union handling for this in the first place? (I should have asked that question originally, instead of just asking if we had a test for it.) It looks like `enum_metadata` currently won't respect this case as a non-member, and we should probably keep this logic in sync with `enum_metadata` -- so maybe we shouldn't handle unions at all in `try_unwrap_nonmember_value`? Unless you saw an important reason somewhere why we need to do so.

File: crates/ty_python_semantic/src/types/enums.rs [hunk 6]
```diff
@@ -294,3 +290,55 @@ pub(crate) fn is_enum_class<'db>(db: &'db dyn Db, ty: Type<'db>) -> bool {
...
+                    if instance.has_known_class(db, KnownClass::Nonmember) {
+                        return Some(
+                            elem.member(db, "value")
+                                .place
+                                .ignore_possibly_undefined()
+                                .unwrap_or(Type::unknown()),
+                        );
+                    }
+                }
+            }
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/enums.rs]: As commented above, I'm wondering if we should even have this branch at all, given I don't think the nonmember handling in `enum_metadata` handles unions. If we do need it, I think it should be more principled than just arbitrarily grabbing the first nonmember type it sees (more like: union all nonmember types found -- and decide what we should do with mixed types, which is really not clear).

**Review by carljm — COMMENTED** [review]
Looks good!

File: crates/ty_python_semantic/src/types/enums.rs (hunk 6 above)
Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/enums.rs]: I was using this as a crutch to avoid `Unknown | int` which is obviously bad (and not entirely intended -- I only just noticed that when I tried to remove). I removed this and changed the non-member inference to use only the inferred type from the binding rather than combining the declaration (which would add `Unknown`), which I _think_ is consistent with `enum_metadata`?

Comment (carljm) [reply crates/ty_python_semantic/src/types/enums.rs]: So I think your latest approach is right in principle, but sadly it looks like a significant regression, because now we're doing a bunch of extra work to re-lookup the attribute, for any attribute lookup on any enum class.

The ideal solution here would be to move the code in `place_by_id` that does the actual "union with Unknown" out into `Place`, so that we'd have a way to get the type of a `Place` without the `Unknown`, without having to reverse-engineer a union type. That seems pretty doable but it won't be trivial, probably better as a separate PR.

To get this landed probably the best approach is to go back to handling unions in `try_unwrap_...`, but maybe in a more targeted way, so we'll ignore `Unknown` and otherwise expect there to be exactly one `nonmember` type in the union, otherwise return `None`. And caption this with a TODO comment that it's a hack and what we should really do is pull the Unknown unioning up into Place instead.

Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/enums.rs]: (Reverted back for now.)

**Review by carljm — APPROVED** [review]
ship it
