### PR TITLE
[ty] Fix overflow with recursive `TypeIs`

### LINKED ISSUE #2983: Stack overflow on recursive `TypeIs`
### Summary

This code:
```py
from typing import TypeIs
type Recursive = TypeIs[Recursive]
```
Causes a stack overflow like this: `thread '<unknown>' (56756) has overflowed its stack` when run through ty, and crashes the playground.

### Version

ty 0.0.21 (c1ad9f281 2026-03-06) playground 735da8b41

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Closes https://github.com/astral-sh/ty/issues/2983.

### CODE REVIEW

**Comment by charliermarsh** [comment]
I don't have super high confidence in this implementation, but I did have Codex do several tries on it and this seemed the most reasonable.

File: crates/ty_python_semantic/src/types/infer/builder/type_expression.rs [hunk 1]
```diff
@@ -1839,8 +1839,14 @@ impl<'db> TypeInferenceBuilder<'db, '_> {
...
                     // fully correct. See <https://github.com/astral-sh/ruff/pull/20591>
                     // for more discussion.
-                    self.infer_type_expression(arguments_slice)
-                        .top_materialization(self.db()),
+                    match self
+                        .infer_type_expression(arguments_slice)
+                        .top_materialization(self.db())
+                    {
+                        Type::TypeIs(type_is) => type_is.return_type(db),
+                        Type::TypeGuard(type_guard) => type_guard.return_type(db),
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/infer/builder/type_expression.rs]: This breaks semantics of a case like this:

```py
from typing import TypeIs, TypeGuard

type Alias = TypeGuard[int]

def f(x: bool) -> TypeIs[Alias]:
    raise NotImplementedError()

def _(x: bool):
    if f(x):
        reveal_type(x)
```

All other type-checkers (and ty before this PR) reveal `TypeGuard[int]` on the last line, after this PR we reveal `int`, and issue a bogus error on the definition of `f` because `int` (as we now see the return type) is not assignable to `bool` (the input type).

File: crates/ty_python_semantic/src/types.rs [hunk 2]
```diff
@@ -5382,6 +5406,13 @@ impl<'db> Type<'db> {
                     }
                 });
 
+                // Materialization is a direct transform of the alias RHS. Don't run the
+                // alias-preservation and recursion-probing heuristic below, as that can
+                // re-enter recursive aliases outside the current visitor.
+                if matches!(type_mapping, TypeMapping::Materialize(_)) {
+                    return mapped;
+                }
```
Comment (carljm) [inline crates/ty_python_semantic/src/types.rs]: Not sure about this either -- maybe it's fine? I don't love the whole `expand_eagerly` mechanic to begin with. Need to think more about this.

**Review by carljm — DISMISSED** [review]

**Comment by charliermarsh** [comment]
This seems a bit less invasive.

File: crates/ty_python_semantic/src/types.rs [hunk 3]
```diff
@@ -849,17 +848,46 @@ impl<'db> Type<'db> {
...
-            // The current type is unioned to the previous type. Unioning in the reverse order can
-            // cause the fixed-point iterations to converge slowly or even fail. Consider the case
-            // where the order of union types is different between the previous and current cycle.
-            // We should use the previous union type as the base and only add new element types in
-            // this cycle, if any.
-            UnionType::from_elements_cycle_recovery(db, [previous, self])
-        }
-        .recursive_type_normalized(db, cycle)
+            match (previous, self) {
+                (Type::TypeIs(previous), Type::TypeIs(current))
```
Comment (ibraheemdev) [inline crates/ty_python_semantic/src/types.rs]: I'm not sure I understand why we have to special case these here. Why exactly does the cycle fail to converge with regular cycle recovery?

**Comment by carljm** [comment]
I think the special handling of `TypeIs` and `TypeGuard` in `cycle_normalized` here wasn't fully correct either -- `TypeIs` is invariant, so in general it's not correct to say that `TypeIs[X] | TypeIs[Y]` is equivalent to `TypeIs[X | Y]`, which is what that code was effectively doing.

I looked into it, and it seems like `TypeGuard` didn't even need that special-casing. It was only needed for `TypeIs` because we top-materialize its argument, and we top-materialize `Divergent` to `object`, which defeats our usual `recursive_type_normalized` handling. So we'd get `TypeIs[object] | TypeIs[TypeIs[object]]`, and that union would grow indefinitely without converging.

I pushed an alternative fix where (before top-materializing) we detect `TypeIs[Divergent]` and normalize it to `Divergent`. That seems to also fix the problem, and adds a (correct I think) diagnostic about a direct-recursive type alias.

**Review by ibraheemdev — APPROVED** [review]
