### PR TITLE
[ty] Fix narrowing of nonlocal variables with conditional assignments

### LINKED ISSUE #2649: Nonlocal `float | None` variable asserted to not be `None` still has `None` in its type
### Summary

When a nonlocal variable of inferred type `float | None` is known (by control flow) not to be an `int` and is known (by assertion) not to be `None`, ty detects its type as `int | float | None`, ignoring the assertion. [Example](https://play.ty.dev/9e9480e1-3313-47ea-a05b-c4de8d5d37bb):
```console
$ cat >bug.py <<'# EOF'
def _(maybe_float: float | None, certain_int: int, flag: bool) -> None:
    if isinstance(maybe_float, int):
        return
    x = maybe_float
    def _() -> None:
        nonlocal x
        if flag:
            x = certain_int
        assert x is not None
        +x
# EOF

$ ty check bug.py
error[unsupported-operator]: Unary operator `+` is not supported for object of type `int | float | None`
  --> bug.py:10:9
   |
 8 |             x = certain_int
 9 |         assert x is not None
10 |         +x
   |         ^^
   |
info: rule `unsupported-operator` is enabled by default

Found 1 diagnostic
```

### Version

ty 0.0.14 (16597f5e2 2026-01-26)

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Given:

```python
def _(maybe_float: float | None, certain_int: int, flag: bool) -> None:
  if isinstance(maybe_float, int):
      return
  x = maybe_float
  def _() -> None:
      nonlocal x
      if flag:
          x = certain_int
      assert x is not None
      +x  # error: Unary operator `+` is not supported for operand of type `int | float | None`
```

With the guard (removed in this PR), `assert x is not None` would have no effect, since `int | (float & ~int)` is not assignable to `(float & ~int) | None`.

Closes https://github.com/astral-sh/ty/issues/2649.

### CODE REVIEW

File: crates/ty_python_semantic/src/types/infer/builder.rs [hunk 1]
```diff
@@ -11621,10 +11621,7 @@ impl<'db, 'ast> TypeInferenceBuilder<'db, 'ast> {
                     // Since an unbound binding is recorded even for an undefined place,
                     // this can only happen if the code is unreachable
                     // and therefore it is correct to set the result to `Never`.
-                    let union = union.build();
-                    if union.is_assignable_to(db, ty) {
```
Comment (charliermarsh) [inline crates/ty_python_semantic/src/types/infer/builder.rs:11625]: This was added in https://github.com/astral-sh/ruff/pull/17643/changes#diff-20b910c6e20faa962bb1642e111db1cbad8e66ace089bdd966ac9d7f9fa99ff2R6047, but I'm not totally sure why.

Comment (AlexWaygood) [reply crates/ty_python_semantic/src/types/infer/builder.rs:11625]: @mtshiba, I don't suppose you can remember the reason why this was added?

Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/infer/builder.rs:11625]: @sharkdp may also know.

**Review by carljm — APPROVED** [review]
The removed guard makes the assumption that a narrowed type in a nested scope should never be wider than the type in the outer scope which binds the name. (Since we have `nonlocal x` in the nested scope, the outer scope here binds `x`.) This assumption seems reasonable, but is violated by the `x = certain_int` assignment in the nested scope here.

There's an open question here about how we should be reflecting the inner `x = certain_int` in the type of `x` in the outer scope. Because of `nonlocal x`, that assignment means that `x` can become `int` again in the outer scope, wherever the nested function is called. (Which in the simplified example in this test, is obviously "never"). I think probably the best balance here would be to consider that the definition of the nested scope itself should "apply" the inner nonlocal bindings in the outer scope, so anywhere in the outer scope after the `def _() -> None:` we treat `x` in the outer scope as could-be-int again. (The rationale here is that before the nested scope is defined, it can't possibly be called; after it is defined, it's not feasible to track every specific place where it might be called.) But all of this is a separate issue, and I don't think it removes the need for the change in this PR.

**Comment by carljm** [comment]
The ecosystem results all look correct here, with the exception of the new diagnostic in xarray -- but there we are triggering a pre-existing (and unrelated) issue where we narrow constrained typevars too eagerly.
