### PR TITLE
[red-knot] Rename *_ty functions

### LINKED ISSUE #15569: [red-knot] Consistent suffixes for function names
We previously had a scheme where functions that had a `_ty` suffix would return a `Type<'db>`. This has been broken in a few places, for example:

- `bindings_ty` which returns a `Symbol<'db>`
- `declaration_ty` which returns a `TypeAndQualifiers<'db>`

We should probably clean this up, i.e. either come up with new suffixes, with entirely new function names, or decide that we don't want to do anything about it.

### PR DESCRIPTION
**Pull request by sharkdp**
## Summary

General rules:

* Change the `_ty` suffix of all functions to `_type`.
* `_type_and_qualifiers` suffixes seem too long, so we ignore the existence of qualifiers and still speak of "types"
* Functions only have a `_type` suffix if they return either `Type`, `Option<Type>`, or `TypeAndQualifiers`

Free functions:

* `binding_ty` => `binding_type`
* `declaration_ty` => `declaration_type`
* `definition_expression_ty` => `definition_expression_type`

Methods:

* `CallDunderResult::return_ty` => `return_type`
* `NotCallableError::return_ty` => `return_type`
* `NotCallableError::called_ty` => `called_type`
* `TypeAndQualifiers::inner_ty` => `inner_type`
* `TypeAliasType::value_ty` => `value_type`
* `TypeInference::expression_ty` => `expression_type`
* `TypeInference::try_expression_ty` => `try_expression_type`
* `TypeInference::binding_ty` => `binding_type`
* `TypeInference::declaration_ty` => `declaration_type` 
* `TypeInferenceBuilder::expression_ty` => `expression_type`
* `TypeInferenceBuilder::file_expression_ty` => `file_expression_type`
* `TypeInferenceBuilder::module_ty_from_name` => `module_type_from_name`
* `ClassBase::try_from_ty` => `try_from_type`
* `Parameter::annotated_ty` => `annotated_type`
* `Parameter::default_ty` => `default_type`
* `CallOutcome::return_ty` => `return_type`
* `CallOutcome::return_ty_result` => `return_type_result`
* `CallBinding::from_return_ty` => `from_return_type`
* `CallBinding::set_return_ty` => `set_return_type`
* `CallBinding::return_ty` => `return_type`
* `CallBinding::parameter_tys` => `parameter_types`
* `CallBinding::one_parameter_ty` => `one_parameter_type`
* `CallBinding::two_parameter_tys` => `two_parameter_types`
* `Unpacker::tuple_ty_elements` => `tuple_type_elements`
* `StringPartsCollector::ty` => `string_type`

Traits

* `HasTy` => `HasType`
* `HasTy::ty` => `inferred_type`

Test functions:

* `assert_public_ty` => `assert_public_type`
* `assert_scope_ty` => `assert_scope_type`

closes #15569

## Test Plan

—

### CODE REVIEW

File: crates/red_knot_project/tests/check.rs [hunk 1]
```diff
@@ -198,10 +198,10 @@ impl SourceOrderVisitor<'_> for PullTypesVisitor<'_> {
     fn visit_stmt(&mut self, stmt: &Stmt) {
         match stmt {
             Stmt::FunctionDef(function) => {
-                let _ty = function.ty(&self.model);
+                let _ty = function.get_type(&self.model);
```
Comment (MichaReiser) [inline crates/red_knot_project/tests/check.rs:201]: Getters are rather unidiomatic in the rust ecosystem. I think I prefer keeping `ty` here (`r#type` is too annoying to type). 

Or possibly `infer_type`?

**Review by MichaReiser — APPROVED** [review]

File: crates/red_knot_project/tests/check.rs [hunk 2]
```diff
@@ -198,10 +198,10 @@ impl SourceOrderVisitor<'_> for PullTypesVisitor<'_> {
     fn visit_stmt(&mut self, stmt: &Stmt) {
         match stmt {
             Stmt::FunctionDef(function) => {
-                let _ty = function.ty(&self.model);
+                let _ty = function.inferred_type(&self.model);
```
Comment (MichaReiser) [inline crates/red_knot_project/tests/check.rs:201]: We may want to wait for @carljm's feedback. I could see how he objects to `inferred_type` because it does return the declared type for classes or when the expression is in an annotation position...

Comment (sharkdp) [reply crates/red_knot_project/tests/check.rs:201]: If so, then we should probably also change the documentation of the trait:
```rs
pub trait HasType {
    /// Returns the inferred type of `self`.
    ///
    /// ## Panics
    /// May panic if `self` is from another file than `model`.
    fn inferred_type<'db>(&self, model: &SemanticModel<'db>) -> Type<'db>;
}
```
I would think that maybe here in `semantic_model.rs`, we may not want to distinguish between declared/inferred type. They're all types that are generated by "Type inference".

But yes, I'll leave this open for further discussion.

Comment (carljm) [reply crates/red_knot_project/tests/check.rs:201]: > I would think that maybe here in `semantic_model.rs`, we may not want to distinguish between declared/inferred type. They're all types that are generated by "Type inference".

Yes, I agree with this and I'm fine with the name changes in this PR.
