### PR TITLE
[`flake8-pytest-style`] Implement pytest.warns diagnostics (`PT029`, `PT030`, `PT031`)

### LINKED ISSUE #14239: Extend `pytest-raises-with-multiple-statements (PT012)` to cover `pytest.warns`
[`pytest-raises-with-multiple-statements`](https://docs.astral.sh/ruff/rules/pytest-raises-with-multiple-statements/) only covers `pytest.raises`. It'd be nice if it covers `pytest.warns` as well.

```python
import pytest


def test_raises():
    with pytest.raises(Exception):  # PT012
        f3()
        f4()


def test_warns():
    with pytest.warns(UserWarning):
        f1()  # does this warn?
        f2()  # or perhaps this one warns?
        # -> Not obvious which line warns.
```

Playground to ensure `pytest.warns` is not covered: https://play.ruff.rs/271e2f8e-751a-4368-971c-322eeeb10b39

References:

- https://docs.pytest.org/en/stable/reference/reference.html#pytest.warns

### PR DESCRIPTION
**Pull request by tjkuson**
## Summary

Implements upstream diagnostics `PT029`, `PT030`, `PT031` that function as pytest.warns corollaries of `PT010`, `PT011`, `PT012` respectively. Most of the implementation and documentation is designed to mirror those existing diagnostics.

Closes #14239

## Test Plan

Tests for `PT029`, `PT030`, `PT031` largely copied from `PT010`, `PT011`, `PT012` respectively.

`cargo nextest run`

### CODE REVIEW

**Review by charliermarsh — APPROVED** [review]
This looks great, thanks.

File: crates/ruff_linter/src/rules/flake8_pytest_style/rules/warns.rs [hunk 1]
```diff
@@ -0,0 +1,254 @@
...
+/// ## Example
+/// ```python
+/// import pytest
+///
+///
+/// def test_foo():
+///     with pytest.warns(MyWarning):
+///         setup()
+///         func_to_test()  # not executed if `setup()` triggers `MyWarning`
+///         assert foo()  # not executed
```
Comment (charliermarsh) [inline crates/ruff_linter/src/rules/flake8_pytest_style/rules/warns.rs:32]: I couldn't figure out from the docs... Is this true? Does the block stop as soon as the warning is triggered? Or is this a copy-paste error from the `raises` variant.

Comment (tjkuson) [reply crates/ruff_linter/src/rules/flake8_pytest_style/rules/warns.rs:32]: That comment was a copy error, apologies!

Comment (charliermarsh) [reply crates/ruff_linter/src/rules/flake8_pytest_style/rules/warns.rs:32]: Are you able to PR a revision to the docs?

Comment (tjkuson) [reply crates/ruff_linter/src/rules/flake8_pytest_style/rules/warns.rs:32]: On it!
