### PR TITLE
[ty] Fix union `*args` binding for optional positional parameters

### LINKED ISSUE #2734: expand unions of fixed-length tuples in unpacking *args
```py
from typing import Literal

def f(x: int | None = None, y: str = ""): ...

def _(flag: bool):
    args = () if flag else (1,)
    f(*args)
```

We error on `f(*args)` because `args` is a union of two fixed-length tuple types, so we give up and just treat it as a variable-length homogeneous iterable. (Pyright and pyrefly do the same.) But mypy allows this call. It would require expanding the union and checking the call twice, similar to how we do in overload matching.

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Closes https://github.com/astral-sh/ty/issues/2734.

### CODE REVIEW

File: crates/ty_python_semantic/src/types/call/bind.rs [hunk 1]
```diff
@@ -2890,13 +2891,77 @@ impl<'a, 'db> ArgumentMatcher<'a, 'db> {
...
+                        let tuple_specs = union
+                            .elements(db)
+                            .iter()
+                            .map(|ty| {
+                                ty.try_iterate(db).unwrap_or_else(|err| {
+                                    Cow::Owned(TupleSpec::homogeneous(
+                                        err.fallback_element_type(db),
+                                    ))
+                                })
+                            })
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/call/bind.rs]:
```suggestion
                            .map(|ty| ty.iterate(db))
```

File: crates/ty_python_semantic/resources/mdtest/call/function.md [hunk 2]
```diff
@@ -786,6 +786,34 @@ for tup in my_other_args:
...
+
+def f13(a: int, b: int, c: str) -> None: ...
+def f14(a: int, b: int, c: str, d: list[float], e: list[float]) -> None: ...
+def f15(profile: bool, line: str) -> None:
+    matcher = f13
+    timings = []
+    if profile:
+        matcher = f14
+        timings = [[0.0], [1.0], [2.0], [3.0]]
+    matcher(1, 2, line, *timings[:2])
```
Comment (carljm) [inline crates/ty_python_semantic/resources/mdtest/call/function.md:814]: It's actually kind of surprising to me that this call would be expected to succeed. We can't do correlated narrowing of multiple variables (and neither does any other type checker that I know of), so we don't know that if `matcher` is `f13` then `timings` must be empty. So given the usual "every element must succeed" behavior of unions, I would expect to get an error here that we might be passing unknown arguments to `f13`.

But no other type checker errors on this, so I guess we shouldn't either?

File: crates/ty_python_semantic/src/types/call/bind.rs [hunk 3]
```diff
@@ -2890,13 +2891,77 @@ impl<'a, 'db> ArgumentMatcher<'a, 'db> {
...
+                    // arities. For signatures where all remaining positional parameters are
+                    // defaulted, map each possible tuple index from the union to the
+                    // corresponding optional positional parameter.
+                    Type::Union(union)
+                        if self.parameters.variadic().is_none()
+                            && self
+                                .parameters
+                                .positional()
+                                .skip(self.next_positional)
+                                .all(|parameter| parameter.default_type().is_some()) =>
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/call/bind.rs:3363]: This requirement is extra conservative. Consider:

```py
def f(a: int, b: int = 0, c: str = ""): ...

def _(x: tuple[int] | tuple[int, int]):
    f(*x)
```

This call should pass, and is an instance of the same issue we are aiming to fix here. But this fix won't apply to it, because `a: int` parameter has no default.

Handling this case would require tracking the number of non-defaulted arguments, and erroring if any iterable element of the union doesn't contain enough items to cover all non-defaulted arguments.

Fine with me to defer this type of case to a future PR (this PR is still a strict improvement over the status quo), but we should add a test for it with TODO comment, and a TODO here in the code, to help preserve context for that future PR.

File: crates/ty_python_semantic/src/types/call/bind.rs [hunk 4]
```diff
@@ -2890,13 +2891,77 @@ impl<'a, 'db> ArgumentMatcher<'a, 'db> {
...
+                            }
+
+                            let argument_type =
+                                UnionType::from_elements_leave_aliases(db, positional_types);
+
+                            self.match_positional(
+                                argument_index,
+                                argument,
+                                Some(argument_type),
+                                false,
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/call/bind.rs]: I _think_ it's OK in practice that we always pass `false` here, even if we do have a variable-length element of the union, because this argument only ends up mattering (in `assign_argument`) if the argument and next parameter are both variadic, and we've already verified above that the next positional parameter is not variadic.

But this is a pretty subtle invariant several layers down to rely on -- is there any harm in being more semantically accurate here?
```suggestion
                                any_variable_length,
```

File: crates/ty_python_semantic/src/types/call/bind.rs [hunk 5]
```diff
@@ -2890,13 +2891,77 @@ impl<'a, 'db> ArgumentMatcher<'a, 'db> {
...
+                            if any_variable_length
+                                && self
+                                    .explicit_keyword_parameters
+                                    .contains(&self.next_positional)
+                            {
+                                break;
+                            }
+
+                            let Ok(tuple_index_i32) = i32::try_from(tuple_index) else {
+                                break;
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/call/bind.rs]: why not make `tuple_index` an i32 from the start, since it's never used other than to convert to i32 here?

File: crates/ty_python_semantic/src/types/call/bind.rs (hunk 1 above)
Comment (carljm) [reply crates/ty_python_semantic/src/types/call/bind.rs]: This is exactly the same logic as `.iterate()` uses to fall back -- so we should just call `.iterate()`.

File: crates/ty_python_semantic/src/types/call/bind.rs
Comment (carljm) [inline crates/ty_python_semantic/src/types/call/bind.rs:3329]: So this entire match and the following one boil down to getting an `argument_types`, a `length`, and a `variable_element`, which the logic in the rest of the method uses.

The current approach in this PR is to implement unions entirely as a special case, effectively trying to re-implement the entire rest of the method specifically for the union case. This feels likely to be bug-prone -- I'm having a lot of trouble even working through for myself what we might be missing.

But it seems to me like it should be possible for us to add a `VariadicArgumentType::Union` variant, and correctly unpack that into an `argument_types` slice (it would contain the union of possible argument types at each index that is possible for any fixed-length union element), a `length` (minimum would be the smallest fixed-length element, maximum would be the largest), and a `variable_element` (`None` if no union element is variable length, or the union of element types for all variable length elements). And it seems like if we do that, then the rest of the logic should just fall out correctly from the existing code here. (Or if it doesn't, those are probably bugs we need to fix anyway.)

File: crates/ty_python_semantic/src/types/call/bind.rs [hunk 6]
```diff
@@ -2890,13 +2891,77 @@ impl<'a, 'db> ArgumentMatcher<'a, 'db> {
...
+                        let any_variable_length =
+                            tuple_specs.iter().any(|spec| spec.len().is_variable());
+                        let mut tuple_index = 0usize;
+
+                        while self
+                            .parameters
+                            .get_positional(self.next_positional)
+                            .is_some()
+                        {
+                            if any_variable_length
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/call/bind.rs]: It's not clear to me why this check should be conditioned on `any_variable_length` -- but I'm going to stop trying to verify the details of the logic in the current PR until/unless we confirm that this can't be implemented according to the less-duplicative strategy I suggested in another comment.

**Review by carljm — CHANGES_REQUESTED** [review]
Thanks! I think there are some thing to look at here.

File: crates/ty_python_semantic/src/types/call/bind.rs (hunk 4 above)
Comment (carljm) [reply crates/ty_python_semantic/src/types/call/bind.rs]: Actually on second thought I changed my mind here but forgot to delete this comment. I think passing `false` is actually better here, since are not matching a variable-length variadic argument; we've unpacked the variadic and are now matching a single index.

File: crates/ty_python_semantic/src/types/call/bind.rs (hunk 3 above)
Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/call/bind.rs:3363]: (Added a TODO.)

File: crates/ty_python_semantic/src/types/call/bind.rs
Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/call/bind.rs:3329]: Gave this a shot!

File: crates/ty_python_semantic/src/types/call/bind.rs [hunk 7]
```diff
@@ -3275,13 +3284,84 @@ impl<'a, 'db> ArgumentMatcher<'a, 'db> {
...
+                    // `Type::iterate` unions tuple specs in a way that can invent additional
+                    // arities. Iterate each union element individually and compute per-position
+                    // union types, length bounds, and variable element so that the rest of the
+                    // matching logic handles unions correctly.
+                    //
+                    // We restrict this to cases where all remaining positional parameters are
+                    // defaulted and there is no variadic parameter, because the per-position
+                    // union loses the correlation between element lengths and per-position types.
+                    // In overloaded contexts, this loss would prevent the expansion step from
+                    // correctly splitting the union into separate argument lists.
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/call/bind.rs]: I assume you tried lifting this restriction, and observed this overload problem.

Did you observe this in the ecosystem, or in an existing test?

If the former, we should add a test.

File: crates/ty_python_semantic/src/types/call/bind.rs [hunk 8]
```diff
@@ -3301,6 +3386,12 @@ impl<'a, 'db> ArgumentMatcher<'a, 'db> {
         let mut argument_types = argument_types.iter().copied();
         let is_variable = length.is_variable();
 
+        // For union types with no variable element, we know the exact set of possible argument
+        // positions. When argument types are exhausted, we should stop matching rather than
+        // continuing with unknown types.
+        let bounded = variable_element.is_none()
+            && matches!(&variadic_type, VariadicArgumentType::Union { .. });
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/call/bind.rs]: Isn't this just as true for `VariadicArgumentType::Other` where the `tuple` has no variadic element? All tests pass if I remove the `matches!(...)` part of the condition here.

But then, all tests also pass if I unconditionally `let bounded = false`, so it seems like we are missing test coverage here.

If this `bounded` variable is needed at all, let's add test(s) showing what breaks without it. And I suspect that if it's needed for `VariadicArgumentType::Union`, it's also needed for `VariadicArgumentType::Other` -- we should have tests for both scenarios.

**Review by carljm — APPROVED** [review]
This looks much better! Just a couple comments on test coverage. It's not clear to me if the new `bounded` variable is actually needed or not -- test coverage would help clarify.

File: crates/ty_python_semantic/src/types/call/bind.rs (hunk 8 above)
Comment (carljm) [reply crates/ty_python_semantic/src/types/call/bind.rs]: Ok, after exploring a bit more here I now understand why this is only needed for `VariadicArgumentType::Union`. It's because our `TupleLength` enum has no way to represent "fixed min length and fixed max length" -- it either represents a single fixed length, or a variadic length where the max is not known. But with the union-of-fixed case here, we have a known min and a known max, and that's what this handles.

Will push some tests covering this, and an update to this code that I think will clarify it a bit.

Comment (carljm) [reply crates/ty_python_semantic/src/types/call/bind.rs]: I don't actually think we need this `bounded` variable at all -- we can safely just always break from the loop below if we've run out of `argument_types` and there is no `variable_element`. That means we're out of possible arguments to unpack. This case just wasn't possible before because prior to this diff `is_variable` always implied `variable_element.is_some()`.

File: crates/ty_python_semantic/src/types/call/bind.rs (hunk 7 above)
Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/call/bind.rs]: Turns out we do have tests for it!
