### PR TITLE
[red-knot] Further optimize `*`-import visibility constraints

### LINKED ISSUE #17322: [red-knot] Consider further optimising visibility constraints applied to `*`-import definitions
https://github.com/astral-sh/ruff/pull/17317 reclaimed much of the performance regression from https://github.com/astral-sh/ruff/pull/17286, but it appears as though we have still lost a fair bit of performance over the last two days, much of it due to work on `*` imports. Here's an annotated graph of how the Codspeed [`red_knot_check_file[cold]`](https://codspeed.io/astral-sh/ruff/benchmarks/crates/ruff_benchmark/benches/red_knot.rs::check_file::benchmark_cold::red_knot_check_file%5Bcold%5D) benchmark has changed over the last two days:

Image

We may still be doing more work than necessary when it comes to applying and resolving visibility constraints for `*` imports. There are some suggestions in this thread for further optimisations that we could make: https://github.com/astral-sh/ruff/pull/17317#discussion_r2035680272

### PR DESCRIPTION
**Pull request by AlexWaygood**
## Summary

Fixes #17322. Remove any need for snapshotting when applying visibility constraints to `*` imports. This also ends up simplifying the code!

## Test Plan

Existing tests all pass. I'd appreciate a careful review, though. Is it definitely safe to remove these calls, as I am doing currently in the PR?

E.g. the `UseDefMapBuilder::negate_star_import_visibility_constraint` method on `main` has this call:

```rs
        self.scope_start_visibility = self
            .visibility_constraints
            .add_and_constraint(self.scope_start_visibility, negated_constraint);
```

and `UseDefMapBuilder::merge` has this call:

```rs
        self.scope_start_visibility = self
            .visibility_constraints
            .add_or_constraint(self.scope_start_visibility, snapshot.scope_start_visibility);
```

Both calls are currently removed in this PR for the "fast path" for newly added `*`-import definitions, since `UseDefMapBuilder::negate_star_import_visibility_constraint` is removed as part of this PR, and `UseDefMapBuilder::merge` is no longer called in the fast path. If it's _not_ safe to remove these calls from the fast path, is there a test I could add that passes on `main`, but fails with them removed?

### CODE REVIEW

**Comment by AlexWaygood** [comment]
3% speedup on the incremental benchmark 🥳 https://codspeed.io/astral-sh/ruff/branches/alex%2Foptimize-star-imports

**Review by sharkdp — APPROVED** [review]
Thank you, this looks correct! Great that we can reclaim even more performance.

`self.scope_start_visibility` tracks the visibility of `x_new = <unbound>` bindings of symbols that are *not yet defined* (symbols that *are* already defined, track visibility of their own `x_defined = <unbound>` binding). This is important when we model something like
```py
if True:
    x = 1
else:
    # At this point in control flow, we have a scope_start_visibility
    # of `~[True]`, which we'll use for the `x = <unbound>` binding
    # that will be implicitly created for this control flow branch
    # when we merge control flow with the `if` branch below.

# a use of `x` here sees `x = 1` with visibility `[True]` and
# `x = <unbound>` with visibility `~[True]`.
```

The important thing is that `scope_start_visibility` returns to `AlwaysTrue` after this `if`-`else` branch. `x` can not be unbound, but *new* symbols would still be unbound. You can basically ask: if I would see a use of `has_not_been_bound_yet` at this point in control flow, would I still be able to see the implicit `has_not_been_bound_yet = <unbound>` binding at the scope start? And the answer for this example is yes. Things could be different if there would be terminal statements inside the branches:
```py
def _():
    if True:
        return

    # scope_start_visibility would be AlwaysFalse here
```

For the star-import construct that we're modeling, the scope-start-visibility should not be affected (after control flow has merged), since there are no terminal statements inside. A use of `has_not_been_bound_yet` after this construct would have the same visibility of the scope start than before:
```py
if <condition>:
    from module import X
else:
    # empty
```

File: crates/red_knot_python_semantic/src/semantic_index/use_def.rs [hunk 1]
```diff
@@ -714,32 +714,32 @@ impl<'db> UseDefMapBuilder<'db> {
             .add_and_constraint(self.scope_start_visibility, constraint);
     }
 
-    #[must_use = "A `*`-import visibility constraint must always be negated after it is added"]
-    pub(super) fn record_star_import_visibility_constraint(
+    pub(super) fn record_and_negate_star_import_visibility_constraint(
```
Comment (carljm) [inline crates/red_knot_python_semantic/src/semantic_index/use_def.rs:717]: I think it would be useful to future-us to add a doc comment to this method explaining what it is doing and why it is safe to do it, in the limited cases where we use this function.

**Review by carljm — APPROVED** [review]
Very nice, thank you!!

File: crates/red_knot_python_semantic/src/semantic_index/use_def.rs (hunk 1 above)
Comment (AlexWaygood) [reply crates/red_knot_python_semantic/src/semantic_index/use_def.rs:753]: Added some docs! Sadly this PR is no longer net-negative in terms of whether it adds or removes lines of code, but so it goes 🥲

Would appreciate a quick review from you or @sharkdp to double-check everything in the doc-comment is accurate!

**Review by sharkdp — APPROVED** [review]
The new comment looks great, thank you
