### PR TITLE
[`flake8-pyi`] Add "replace with `Self`" fix (`PYI034`)

### LINKED ISSUE #14184: Request: Unsafe fix for `non-self-return-type`/`PYI034`
https://docs.astral.sh/ruff/rules/non-self-return-type/

Very similar to https://github.com/astral-sh/ruff/issues/14183
I feel like logically a fix for this rule should be feasible without too much complexity? (at least in pyi files and maybe py files above 3.10, see https://github.com/astral-sh/ruff/issues/9761). The fix should be unsafe as there might be a specific intent, or a stub shows that the runtime returns an instance not actually based on `self/cls`. Marking it unsafe may also simplify the logic to apply the fix (if `Self` already exists in scope).

Maybe it can be restricted to where the return type to replace is the same as the class and not overloaded ?
```py
class ArrayDerivative(Derivative):
    def __new__(cls, expr, *variables, **kwargs) -> ArrayDerivative: ... # unsafe autofix to replace with self
```
```py
class CaptureOutput:
    @overload
    def __new__(
        cls, backend: Literal[CaptureOutputs.PIL] = CaptureOutputs.PIL
    ) -> PILCaptureOutput: ...
    @overload
    def __new__(cls, backend: Literal[CaptureOutputs.NUMPY]) -> NumpyCaptureOutput: ...
    @overload
    def __new__(cls, backend: Literal[CaptureOutputs.NUMPY_FLOAT]) -> NumpyFloatCaptureOutput: ...
    @overload
    def __new__(cls, backend: Literal[CaptureOutputs.PYTORCH]) -> PytorchCaptureOutput: ...
    @overload
    def __new__(
        cls, backend: Literal[CaptureOutputs.PYTORCH_FLOAT]
    ) -> PytorchFloatCaptureOutput: ...
    @overload
    def __new__(cls, backend: Literal[CaptureOutputs.PYTORCH_GPU]) -> PytorchGPUCaptureOutput: ...
    @overload
    def __new__(
        cls, backend: Literal[CaptureOutputs.PYTORCH_FLOAT_GPU]
    ) -> PytorchFloatGPUCaptureOutput: ...
    @overload
    def __new__(cls, backend: CaptureOutputs) -> CaptureOutput: ...
    def __new__(cls, backend: CaptureOutputs = CaptureOutputs.PIL) -> CaptureOutput:  # no autofix
        return cls._initialize_backend(backend)
```

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
## Summary

Resolves #14184.

## Test Plan

`cargo nextest run` and `cargo insta test`.

### CODE REVIEW

File: crates/ruff_linter/src/rules/flake8_pyi/rules/non_self_return_type.rs [hunk 1]
```diff
@@ -93,10 +97,67 @@ impl Violation for NonSelfReturnType {
...
+        Some("Use `Self` as return type".to_string())
     }
 }
 
+fn import_self_edit(checker: &Checker, range: TextRange) -> Option<Edit> {
+    let target_version = checker.settings.target_version.as_tuple();
+    let source_module = if checker.source_type.is_stub() || target_version < (3, 11) {
+        "typing_extensions"
+    } else {
+        "typing"
```
Comment (charliermarsh) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/non_self_return_type.rs:109]:
```suggestion
    let source_module = if checker.source_type.is_stub() || target_version >= (3, 11) {
        "typing"
    } else {
        "typing_extensions"
```

Comment (charliermarsh) [reply crates/ruff_linter/src/rules/flake8_pyi/rules/non_self_return_type.rs:109]: I think we _do_ want to use `typing` in stubs.

**Review by charliermarsh — APPROVED** [review]
Thanks!

File: crates/ruff_linter/src/rules/flake8_pyi/rules/non_self_return_type.rs (hunk 1 above)
Comment (AlexWaygood) [reply crates/ruff_linter/src/rules/flake8_pyi/rules/non_self_return_type.rs]: @InSyncWithFoo is correct -- `Self` cannot be imported from `typing` in a `.py` file or a `.pyi` file if you want the code to support Python 3.10 or lower (see also: https://github.com/astral-sh/ruff/issues/9761).

In typeshed we always import `Self` from `typing_extensions`, because typeshed pretends that `typing_extensions` is part of the stdlib, and we want our stubs to support Python 3.8-3.13.

Comment (charliermarsh) [reply crates/ruff_linter/src/rules/flake8_pyi/rules/non_self_return_type.rs]: Thanks both! I assumed the semantics were similar to PEP 585.
