### PR TITLE
[`ruff`] Fix false positive for `re.split` with empty string pattern (`RUF055`)

### LINKED ISSUE #23629: `[RUF055]` False positive for `re.split` with empty string pattern
### Summary

`re.split("", s)` is flagged by RUF055 and fixed to `s.split("")`, but `str.split` raises `ValueError: empty separator` for empty separators while `re.split` succeeds:

```python
import re

s = "abc"
re.split("", s)   # ['', 'a', 'b', 'c', '']
s.split("")        # ValueError: empty separator
```

### Version

f1a9a703e1992520d7edd3d907d2ed6a019a120b

### Potential fix

Add a guard to skip if the separator is an empty string.

### PR DESCRIPTION
**Pull request by bxff**
## Summary

Fixes #23629.

`re.split("", s)` is flagged by RUF055 and auto-fixed to `s.split("")`, but `str.split("")` raises `ValueError: empty separator` while `re.split("", s)` succeeds (returning `["", "a", "b", "c", ""]`). The same applies to bytes (`rb""`).

This adds a guard to skip the diagnostic when the separator pattern is an empty string or bytes literal specifically for `re.split` calls. Other `re` functions (`sub`, `match`, `search`, `fullmatch`) are not affected — their `str` equivalents all handle empty strings equivalently.

## Test Plan

Added test cases for empty string and bytes patterns in `RUF055_0.py` and `RUF055_3.py`. Verified that no diagnostics are emitted for these cases and all existing RUF055 snapshot tests continue to pass:

```
cargo test -p ruff_linter -- "preview_rules::rule_unnecessaryregularexpression"
test result: ok. 4 passed; 0 failed; 0 ignored
```

### CODE REVIEW

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs [hunk 1]
```diff
@@ -118,6 +118,18 @@ pub(crate) fn unnecessary_regular_expression(checker: &Checker, call: &ExprCall)
         return;
     }
 
+    // `str.split("")` raises `ValueError: empty separator` while `re.split("", s)` succeeds,
+    // so skip the diagnostic for `re.split` with an empty pattern.
+    if matches!(re_func.kind, ReFuncKind::Split) {
+        let is_empty = match &literal {
+            Literal::Str(str_lit) => str_lit.value.to_str().is_empty(),
+            Literal::Bytes(bytes_lit) => bytes_lit.value.iter().all(|part| part.is_empty()),
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs]: I think both of these types have `is_empty` methods:


```suggestion
            Literal::Str(str_lit) => str_lit.value.is_empty(),
            Literal::Bytes(bytes_lit) => bytes_lit.value.is_empty(),
```

This might be a nice method on `Literal`, so that we can just write:

```rust
if matches!(re_func.kind, ReFuncKind::Split) && literal.is_empty() {
	return;
}
```

Comment (bxff) [reply crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs]: Added Literal::is_empty() using the direct .is_empty() methods and simplified the call site, thanks!
