### PR TITLE
[`flake8-pyi`] Also remove `self` and `cls`'s annotation (`PYI034`)

### LINKED ISSUE #14421: Issue with new `PYI034` autofix when first param is annotated
Thanks @InSyncWithFoo for adding an autofix in https://github.com/astral-sh/ruff/pull/14217 .

* A minimal code snippet that reproduces the bug.

I did notice an issue that I think should be possible to handle. This case:
```py
class Container(tuple):
    def __new__(cls: Type[Container], *args, **kwargs) -> Container: ...
```

gets autofixed to
```py
class Container(tuple):
    def __new__(cls: Type[Container], *args, **kwargs) -> Self: ...
```

Which causes type error:
```
error: "Self" cannot be used in a function with a `self` or `cls` parameter that has a type annotation other than "Self" (reportGeneralTypeIssues)
```

I think it should be:
```py
class Container(tuple):
    def __new__(cls, *args, **kwargs) -> Self: ...
```

* The command you invoked (e.g., `ruff /path/to/file.py --fix`), ideally including the `--isolated` flag.

`ruff check --select=PYI034 --fix --preview --unsafe-fixes --isolated`

* The current Ruff settings (any relevant sections from your `pyproject.toml`).

None

* The current Ruff version (`ruff --version`).

ruff 0.7.4

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
## Summary

Resolves #14421.

## Test Plan

`cargo nextest run` and `cargo insta test`.

### CODE REVIEW

File: crates/ruff_python_semantic/src/analyze/class.rs [hunk 1]
```diff
@@ -170,3 +171,51 @@ pub fn is_metaclass(class_def: &ast::StmtClassDef, semantic: &SemanticModel) ->
         (false, _) => IsMetaclass::No,
     }
 }
+
+/// Returns true if a class is generic.
+///
+/// A class is generic if at least one of its direct bases is subscripted with a `TypeVar`-like,
+/// or if it is defined using PEP 695 syntax.
+///
+/// This should only be used in stub context to avoid false positives and negatives.
```
Comment (AlexWaygood) [inline crates/ruff_python_semantic/src/analyze/class.rs:180]: I think even in stub contexts, this could lead to false positives where we say conclude that a class is not generic even though it actually is, and then incorrectly apply an autofix based on that conclusion. That's because the `is_old_style_typevar_like` function doesn't recognise typevars declared in other files as being typevars: I don't think it would understand `typing.AnyStr`, for example. It's pretty rare in typeshed for stubs to use typevars imported from other files (other than `AnyStr`), but I've seen it done much more in other stubs. I definitely don't think we can safely assume that a symbol isn't a typevar just because it's been imported from another module.

Rather than `is_old_style_typevar_like` and `is_generic` functions, I think we actually need `could_be_old_style_typevar_like` and `could_be_generic` functions. `could_be_old_style_typevar_like` would return `true` if it can trace the binding to a TypeVar declaration in the same module, but it would also return `true` if the symbol comes from any other module. `could_be_generic` would have exactly the same implementation you have now, but it would use `could_be_old_style_typevar_like` instead of `is_typevar_like`.

File: crates/ruff_python_semantic/src/analyze/class.rs [hunk 2]
```diff
@@ -170,3 +171,58 @@ pub fn is_metaclass(class_def: &ast::StmtClassDef, semantic: &SemanticModel) ->
...
+            _ => false,
+        },
+
+        _ => false,
+    }
+}
+
+fn might_be_old_style_typevar_like(name: &ExprName, semantic: &SemanticModel) -> bool {
+    let Some(binding) = semantic.only_binding(name).map(|id| semantic.binding(id)) else {
+        return false;
```
Comment (AlexWaygood) [inline crates/ruff_python_semantic/src/analyze/class.rs:224]: this should return `true` because the binding _might_ refer to a TypeVar if there are no bindings (it could be imported via a `*` import) or multiple bindings

File: crates/ruff_python_semantic/src/analyze/class.rs [hunk 3]
```diff
@@ -170,3 +171,58 @@ pub fn is_metaclass(class_def: &ast::StmtClassDef, semantic: &SemanticModel) ->
...
+        Expr::Name(name) => might_be_old_style_typevar_like(name, semantic),
+
+        Expr::Starred(ExprStarred { value, .. }) => match value.as_ref() {
+            Expr::Name(name) => might_be_old_style_typevar_like(name, semantic),
+            _ => false,
+        },
+
+        _ => false,
+    }
+}
```
Comment (AlexWaygood) [inline crates/ruff_python_semantic/src/analyze/class.rs:220]: What about something like this?

```py
# a.pyi
from typing import TypeVar

T = TypeVar("T")
```

```py
# b.pyi
import a

class Foo:
    def __enter__(self: a.T) -> a.T: ...
```

I think you need to handle attribute expressions here as well

File: crates/ruff_python_semantic/src/analyze/class.rs [hunk 4]
```diff
@@ -170,3 +171,58 @@ pub fn is_metaclass(class_def: &ast::StmtClassDef, semantic: &SemanticModel) ->
...
     }
 }
+
+/// Returns true if a class might generic.
+///
+/// A class is considered generic if at least one of its direct bases
+/// is subscripted with a `TypeVar`-like,
+/// or if it is defined using PEP 695 syntax.
+///
+/// This should only be used in stub context to avoid false positives and negatives.
```
Comment (AlexWaygood) [inline crates/ruff_python_semantic/src/analyze/class.rs:181]:
```suggestion
/// A class is considered generic if at least one of its direct bases
/// is subscripted with a `TypeVar`-like,
/// or if it is defined using PEP 695 syntax.
/// Therefore, a class *might* be generic if it uses PEP-695 syntax
/// or at least one of its direct bases is a subscript expression that
/// is subscripted with an object that *might* be a `TypeVar`-like.
```

**Review by AlexWaygood — APPROVED** [review]
