### PR TITLE
[`pyupgrade`]  Apply `UP008` only when the `__class__` cell exists

### LINKED ISSUE #19357: UP008 should only apply when the `__class__` cell exists
### Summary

[`super-call-with-parameters` (UP008)](https://docs.astral.sh/ruff/rules/super-call-with-parameters/) should only apply when `super` is a global variable or `__class__` is a nonlocal variable. Expressions that are merely equal to `super` aren’t good enough. Otherwise, the zero-argument `super` call doesn’t work. One solution is for the autofix to rewrite the `super`-equivalent expression to `super`, although that won’t work in all contexts. [Example](https://play.ruff.rs/852c338a-1d97-4fa4-bbbd-6f768ef373b8):
```console
$ cat >up008.py <<'# EOF'
import builtins
class A:
    def f(self):
        print("!")
class B(A):
    def f(self):
        builtins.super(B, self).f()
B().f()
# EOF

$ python up008.py
!

$ ruff --isolated check up008.py --select UP008 --unsafe-fixes --fix
Found 1 error (1 fixed, 0 remaining).

$ cat up008.py
import builtins
class A:
    def f(self):
        print("!")
class B(A):
    def f(self):
        builtins.super().f()
B().f()

$ python up008.py 2>&1 | tail -n 1
RuntimeError: super(): __class__ cell not found
```

Note that the expression that UP008 rewrites can still use `builtins.super` (or other expressions that equal `super` but are not literally `super`) but `super` or `__class__` just needs to be mentioned somewhere in the method in order for the `__class__` cell, which the zero-argument `super` uses, to be created. [True positive example](https://play.ruff.rs/4a54ab21-24a0-448a-9331-4b416e84ab75) with `super`:
```console
$ cat >up008_super.py <<'# EOF'
import builtins
super = None  # It still works even if `super` is shadowed!
class A:
    def f(self):
        print("!")
class B(A):
    def f(self):
        if False: super
        builtins.super(B, self).f()
B().f()
# EOF

$ ruff --isolated check up008_super.py --select UP008 --unsafe-fixes --fix
Found 1 error (1 fixed, 0 remaining).

$ python up008_super.py
!
```

[True positive example](https://play.ruff.rs/fd2bbb26-b678-46aa-9e2f-0d2e76862eb9) with `__class__`:
```console
$ cat >up008_class.py <<'# EOF'
import builtins
class A:
    def f(self):
        print("!")
class B(A):
    def f(self):
        if False: __class__
        builtins.super(B, self).f()
B().f()
# EOF

$ ruff --isolated check up008_class.py --select UP008 --unsafe-fixes --fix
Found 1 error (1 fixed, 0 remaining).

$ python up008_class.py
!
```

### Version

ruff 0.12.3 (5bc81f26c 2025-07-11)

### PR DESCRIPTION
**Pull request by IDrokin117**
## Summary

Resolves #19357 

Skip UP008 diagnostic for `builtins.super(P, self)` calls when `__class__` is not referenced locally, preventing incorrect fixes.  

**Note:** I haven't found concrete information about which cases `__class__` will be loaded into the scope. Let me know if anyone has references, it would be useful to enhance the implementation. I did a lot of tests to determine when `__class__` is loaded. Considered sources:
1.  [Python doc super](https://docs.python.org/3/library/functions.html#super)
2.  [Python doc classes](https://docs.python.org/3/tutorial/classes.html)
3. [pep-3135](https://peps.python.org/pep-3135/#specification)

As I understand it, Python will inject at runtime into local scope a `__class__` variable if it detects references to `super` or `__class__`. This allows calling `super()` and passing appropriate parameters. However, the compiler doesn't do the same for `builtins.super`, so we need to somehow introduce `__class__` into the local scope.

I figured out `__class__` will be in scope with valid value when two conditions are met:
1. `super` or `__class__` names have been loaded within function scope
4. `__class__` is not overridden.

I think my solution isn't elegant, so I would be appreciate a detailed review.

## Test Plan

Added 19 test cases, updated snapshots.

### CODE REVIEW

**Comment by IDrokin117** [comment]
@ntBre Could you please review a PR?

**Comment by ntBre** [comment]
Will do! Sorry, I'm a bit behind on my review queue, but this has been on the list.

File: crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs [hunk 1]
```diff
@@ -94,14 +97,23 @@ pub(crate) fn super_call_with_parameters(checker: &Checker, call: &ast::ExprCall
     };
 
     // Find the enclosing function definition (if any).
-    let Some(Stmt::FunctionDef(ast::StmtFunctionDef {
+    let Some(func_stmt) = parents.find(|stmt| stmt.is_function_def_stmt()) else {
+        return;
+    };
+    let Stmt::FunctionDef(ast::StmtFunctionDef {
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs]: Oh I see, you need `func_stmt` below. I _think_ you can use something like this:

```rust
let Some(func_stmt @ Stmt::FunctionDef(ast::StmtFunctionDef {
    ...
```

in the old version, but this is fine if not.

File: crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs [hunk 2]
```diff
@@ -193,3 +205,29 @@ pub(crate) fn super_call_with_parameters(checker: &Checker, call: &ast::ExprCall
 fn is_super_call_with_arguments(call: &ast::ExprCall, checker: &Checker) -> bool {
     checker.semantic().match_builtin_expr(&call.func, "super") && !call.arguments.is_empty()
 }
+/// Returns `true` if the function contains load references to `__class__` or `super` without
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs:207]:
```suggestion

/// Returns `true` if the function contains load references to `__class__` or `super` without
```

tiny nit

File: crates/ruff_python_ast/src/helpers.rs
Comment (ntBre) [inline crates/ruff_python_ast/src/helpers.rs:1]: Does this need to be in the `ruff_python_ast` crate? It usually makes sense to define the visitor next to the rule using it, if it's only used by that rule.

File: crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs [hunk 3]
```diff
@@ -193,3 +205,29 @@ pub(crate) fn super_call_with_parameters(checker: &Checker, call: &ast::ExprCall
...
+    let mut finder = FunctionScopeNameFinder::default();
+    finder.visit_stmt(func_stmt);
+    let has_load_super = finder
+        .names
+        .iter()
+        .any(|expr| expr.id.as_str() == "super" && expr.ctx.is_load());
+    let has_load_dunder_class = finder
+        .names
+        .iter()
+        .any(|expr| expr.id.as_str() == "__class__" && expr.ctx.is_load());
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs]: Because these are both `any`, I think we can just check these conditions as the visitor visits and avoid needing to collect a `Vec` of expressions. We may even be able to terminate the visitor early in that case.

File: crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs [hunk 4]
```diff
@@ -193,3 +205,29 @@ pub(crate) fn super_call_with_parameters(checker: &Checker, call: &ast::ExprCall
...
+    let has_dunder_class_binding = semantic.current_scope().has("__class__");
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs]: This looks like a cheaper check than visiting a `Stmt`, so we should probably check this first and return early if it's true (?)

File: crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs [hunk 5]
```diff
@@ -193,3 +205,29 @@ pub(crate) fn super_call_with_parameters(checker: &Checker, call: &ast::ExprCall
...
+    (has_load_super || has_load_dunder_class) && !has_dunder_class_binding
+}
+
+/// Returns `true` if the call is to the built-in `builtins.super` function.
+fn is_builtins_super(semantic: &SemanticModel, call: &ast::ExprCall) -> bool {
+    semantic
+        .resolve_qualified_name(&call.func)
+        .is_some_and(|qualified_name| matches!(qualified_name.segments(), ["builtins", "super"]))
+}
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs:228]: I think you can use `match_builtin_expr` for this:

https://github.com/astral-sh/ruff/blob/96ffd8a134d62f5426c9d94d15adb21100d90f01/crates/ruff_python_semantic/src/model.rs#L319

File: crates/ruff_linter/resources/test/fixtures/pyupgrade/UP008.py [hunk 6]
```diff
@@ -141,3 +141,238 @@ def method2(self):
...
+class ParentD1:
+    def f(self):
+        print("!")
+
+class ChildD1(ParentD1):
+    def f(self):
+        if False: __class__ # Python injects __class__ into scope
+        builtins.super(ChildD1, self).f()
+
+ChildD1().f()
```
Comment (ntBre) [inline crates/ruff_linter/resources/test/fixtures/pyupgrade/UP008.py]: I think we could strip these examples down a little bit, just to make it clearer which parts are important. For example, I don't think the parent class even needs to exist actually, and the same with the following calls. Basically I'd just use this:


```suggestion
class ChildD1:
    def f(self):
        if False: __class__ # Python injects __class__ into scope
        builtins.super(ChildD1, self).f()
```

unless I'm missing some other critical part of the example.

Or we could maybe preserve one of the parent classes and the calls, if it's helpful to be able to run the code. I just don't think we need one parent class per example, if they're all the same, at least.

File: crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs (hunk 1 above)
Comment (IDrokin117) [reply crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs]: Got it. Changed to @ usage

File: crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs (hunk 2 above)
Comment (IDrokin117) [reply crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs:207]: Edited

File: crates/ruff_python_ast/src/helpers.rs
Comment (IDrokin117) [reply crates/ruff_python_ast/src/helpers.rs:1]: I did it just because at least `AwaitVisitor` and `RaiseStatementVisitor` are defined in helpers, but are used only once in rules (`cancel_scope_no_checkpoint` and `raise_without_from_inside_except` respectively) similar to my use case. But yes, it makes sense to move it next to the rule. Done.

File: crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs (hunk 4 above)
Comment (IDrokin117) [reply crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs]: Good point. Moved it to the beginning.

File: crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs (hunk 5 above)
Comment (IDrokin117) [reply crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs:228]: `match_builtin_expr(&call.func, "super")` returns true for both cases: `super()` and `builtins.super()`, but I need to check only the second case.

File: crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs (hunk 3 above)
Comment (IDrokin117) [reply crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs]: My intention was to make it simple and not necessarily optimized.   
I have reworked it, and now it is implemented according to your recommendation, but I think it is more complex to read. I would appreciate any simplification advice.

BTW, it was intentional to pass conditions due to initialization rather than hardcode them in `visit_expr`. In my opinion, it provides more flexibility for future changes.

File: crates/ruff_linter/resources/test/fixtures/pyupgrade/UP008.py (hunk 6 above)
Comment (IDrokin117) [reply crates/ruff_linter/resources/test/fixtures/pyupgrade/UP008.py]: Make sense for me. Removed duplicated parents and instance creation with method calling.

**Comment by ntBre** [comment]
I just came back to this notification right after reviewing https://github.com/astral-sh/ruff/pull/19783. I somehow hadn't connected these two before, but now I'm wondering if they have the same root cause. I think if we're able to work out a neat, general solution for binding the `__class__` cell it might help here too.

**Comment by ntBre** [comment]
We added a new `ScopeKind::DunderClassCell` (and `BindingKind::DunderClassCell`) in https://github.com/astral-sh/ruff/pull/20048. I don't believe that will resolve the issue addressed by this PR, but would you mind seeing if it makes anything easier? I was hoping it might help to avoid the new `Visitor`, but I think we'll still need some rule-specific changes in any case.

Thanks again for your work here :)

**Comment by IDrokin117** [comment]
@ntBre Good news! Here are my thoughts after reviewing the new feature.  
It seems the `__class__` binding is being created in any case now, regardless of whether `__class__` and `super` names are present. Am I right? This is going to be simple and good for some rules, but not for this case. Since the `__class__` binding pretends to always exist within a method, it doesn't provide any new information. I mean, if a `__class__` cell is available, then `builtins.super()` has to work. But that's not true since `__class__` is not always available. I see two options to resolve the issue:
 1. Left the extra visitor to ensure determination of whether `__class__` is really injected at runtime based on specific rules.
 2. Simplify the rule and apply it only if `super()` is encountered, ignoring `builtins.super()`.
 
Since I've already implemented tailored `__class__` determination, I prefer the first option. What do you think?

**Comment by ntBre** [comment]
Thanks for looking into it and rebasing the PR!

> It seems the `__class__` binding is being created in any case now, regardless of whether `__class__` and `super` names are present. Am I right? 

Yes that's right, we didn't try to detect if `__class__` or `super` was used, so it makes sense that it may not help here.

> 1. Left the extra visitor to ensure determination of whether `__class__` is really injected at runtime based on specific rules.
> 2. Simplify the rule and apply it only if `super()` is encountered, ignoring `builtins.super()`.
> 
> Since I've already implemented tailored `__class__` determination, I prefer the first option. What do you think?

Makes sense to me, I'll give this another review soon!

File: crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs [hunk 7]
```diff
@@ -193,3 +203,78 @@ pub(crate) fn super_call_with_parameters(checker: &Checker, call: &ast::ExprCall
...
+
+    let mut finder = AnyExpressionFinder::new(vec![
+        |expr: &Expr| {
+            expr.as_name_expr()
+                .is_some_and(|name| name.id.as_str() == "super" && name.ctx.is_load())
+        },
+        |expr: &Expr| {
+            expr.as_name_expr()
+                .is_some_and(|name| name.id.as_str() == "__class__" && name.ctx.is_load())
+        },
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs]: Would it make sense to combine these conditions in one closure? Maybe something like:


```suggestion
        |expr: &Expr| {
            expr.as_name_expr()
                .is_some_and(|name| matches!(name.id.as_str(), "super" | "__class__") && name.ctx.is_load())
        },
```

I think it could even make sense just to hard-code this check into the visitor since we're not really using it generically, as far as I can tell.

I think you might have been addressing this in [this comment](https://github.com/astral-sh/ruff/pull/19424#discussion_r2261395337), but we can always make it more general in the future if we have to. I'm not really foreseeing that at the moment.

File: crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs [hunk 8]
```diff
@@ -193,3 +203,78 @@ pub(crate) fn super_call_with_parameters(checker: &Checker, call: &ast::ExprCall
...
+    semantic
+        .resolve_qualified_name(&call.func)
+        .is_some_and(|qualified_name| matches!(qualified_name.segments(), ["builtins", "super"]))
+}
+
+/// A [`Visitor`] that searches for [`Expr`] matching any of the provided conditions
+/// , excluding nested class definitions.
+#[derive(Debug)]
+struct AnyExpressionFinder<'a> {
+    result_expression: Vec<&'a Expr>,
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs]: Would an `Option<&'a Expr>` make sense here? It looks like we only ever check if it's empty or not, which could be `is_none` instead (and `Some(expr)` instead of `insert(0)`). Or just a boolean flag since it looks like we just want to record whether we found it.

File: crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs [hunk 9]
```diff
@@ -193,3 +203,78 @@ pub(crate) fn super_call_with_parameters(checker: &Checker, call: &ast::ExprCall
 fn is_super_call_with_arguments(call: &ast::ExprCall, checker: &Checker) -> bool {
     checker.semantic().match_builtin_expr(&call.func, "super") && !call.arguments.is_empty()
 }
+
+/// Returns `true` if the function contains load references to `__class__` or `super` without
+/// local binding.
+///
+/// This indicates that the function relies on the implicit `__class__` cell variable created by
+/// Python when `super()` is called without arguments, making it unsafe to remove `super()` parameters.
+fn has_local_dunder_class_var_ref(semantic: &SemanticModel, func_stmt: &Stmt) -> bool {
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs:212]: Based on my reading of the [docs](https://docs.python.org/3/reference/datamodel.html#creating-the-class-object) we found for the other `__class__` PR, I think we may need to check _all_ of the methods in a class definition:

> `__class__` is an implicit closure reference created by the compiler if **any methods** in a class body refer to either `__class__` or `super`.

(emphasis mine)

This could be quite expensive since we'd have to re-visit the whole class body, so it might still make sense to approximate the behavior by only checking each function separately. But we could still add a test and document the limitation, at least.

**Review by ntBre — COMMENTED** [review]
Thanks! Just a couple of minor simplification suggestions and one corner case from the docs.

File: crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs (hunk 9 above)
Comment (dscorbett) [reply crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs:212]: Each method is considered individually. `__class__` in one method has no effect on another.
```pycon
>>> class C(str):
...     def f1(self):
...         return super().__len__()
...     def f2(self):
...         import builtins
...         return builtins.super().__len__()
... 
>>> C().f1()
0
>>> C().f2()
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    C().f2()
    ~~~~~~^^
  File "<python-input-0>", line 6, in f2
    return builtins.super().__len__()
           ~~~~~~~~~~~~~~^^
RuntimeError: super(): __class__ cell not found
```

Comment (IDrokin117) [reply crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs:212]: At least test case `ChildI2` covers it

Comment (ntBre) [reply crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs:212]: Ah okay, thanks. I should have actually tested it instead of reading so much into the phrasing. And I overlooked the existing test :facepalm: thank you both!

File: crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs (hunk 7 above)
Comment (IDrokin117) [reply crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs]: I simplified the Visitor

File: crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs (hunk 8 above)
Comment (IDrokin117) [reply crates/ruff_linter/src/rules/pyupgrade/rules/super_call_with_parameters.rs]: Made it boolean

**Review by ntBre — APPROVED** [review]
Thanks!
