### PR TITLE
[`flake8-implicit-str-concat`] Avoid invalid fix generated by autofix (`ISC003`)

### LINKED ISSUE #19757: Autofix for ISC003 produces malformed code
### Summary

Autofix fix for ISC003 (Explicitly concatenated string should be implicitly concatenated) produces `TypeError: 'str' object is not callable` in the following situation.
```python
result = "Line1\n" + (
    "Line2\n"
    "Line3"
)
```
`ruff check --fix` produces:
```python
result = "Line1\n" (
    "Line2\n"
    "Line3"
)
```
Which gives a `TypeError: 'str' object is not callable` error obiously.

Link to playground: https://play.ruff.rs/a9d9ac04-ef00-4ddf-a3a6-9e61fa9f8840

### Version

0.12.7

### PR DESCRIPTION
**Pull request by prakhar1144**
## Summary

As reported in #19757:
While attempting ISC003 autofix for an expression with explicit string concatenation, with either operand being a string literal that wraps across multiple lines (in parentheses) - it resulted in generating a fix which caused runtime error.

Example:
```
_ = "abc" + (
    "def"
    "ghi"
)
```
was being auto-fixed to:
```
_ = "abc" (
    "def"
    "ghi"
)
```
which raised `TypeError: 'str' object is not callable`

This commit makes changes to just report diagnostic - no autofix in such cases.

Fixes #19757.

## Test Plan
Added example scenarios in `crates/ruff_linter/resources/test/fixtures/flake8_implicit_str_concat/ISC.py`.

### CODE REVIEW

**Comment by prakhar1144** [comment]
As per suggestion in https://github.com/astral-sh/ruff/pull/19778#discussion_r2257641741:
> I think we can probably just use this helper function to check if left and right are parenthesized and avoid the fix if either of them is

> We can also still report a diagnostic in this case, we just can't autofix it. Another option would be to try to move one of the expressions into the existing parentheses from the other expression, but that might be too involved. I'd be happy with just offering a diagnostic but no fix if one of them is parenthesized to avoid causing the runtime error.

File: crates/ruff_linter/src/rules/flake8_implicit_str_concat/rules/explicit.rs [hunk 1]
```diff
@@ -82,9 +84,25 @@ pub(crate) fn explicit(checker: &Checker, expr: &Expr) {
...
+                    parenthesized_range(
+                        expr.into(),
+                        bin_op.into(),
+                        checker.comment_ranges(),
+                        checker.source(),
+                    )
+                    .is_some()
+                };
+                // If either `left` or `right` is parenthesized, generating
+                // a fix would be too involved. Just report the diagnostic.
```
Comment (amyreese) [inline crates/ruff_linter/src/rules/flake8_implicit_str_concat/rules/explicit.rs:100]: Let's also make it clear that the existing autofix would result in broken code, and maybe include a link to the issue.

File: crates/ruff_linter/src/rules/flake8_implicit_str_concat/rules/explicit.rs [hunk 2]
```diff
@@ -82,9 +84,25 @@ pub(crate) fn explicit(checker: &Checker, expr: &Expr) {
...
+
+                let is_parenthesized = |expr: &Expr| {
+                    parenthesized_range(
+                        expr.into(),
+                        bin_op.into(),
+                        checker.comment_ranges(),
+                        checker.source(),
+                    )
+                    .is_some()
+                };
```
Comment (amyreese) [inline crates/ruff_linter/src/rules/flake8_implicit_str_concat/rules/explicit.rs:98]: I think it's preferred to have this as a separate function that takes appropriate arguments rather than a block.

I think it would also be better to have a function that takes both left and right sides at the same time, and then the code below could be something like:

```rust
if !is_either_side_parenthesized(left, right, ...) {
    diagnostic.set_fix(...);
}
```

**Review by amyreese — CHANGES_REQUESTED** [review]

File: crates/ruff_linter/src/rules/flake8_implicit_str_concat/rules/explicit.rs (hunk 1 above)
Comment (prakhar1144) [reply crates/ruff_linter/src/rules/flake8_implicit_str_concat/rules/explicit.rs:100]: Extended the comment:

```diff
diff --git a/crates/ruff_linter/src/rules/flake8_implicit_str_concat/rules/explicit.rs b/crates/ruff_linter/src/rules/flake8_implicit_str_concat/rules/explicit.rs
index 58f3db33bd..8edb7b46ad 100644
--- a/crates/ruff_linter/src/rules/flake8_implicit_str_concat/rules/explicit.rs
+++ b/crates/ruff_linter/src/rules/flake8_implicit_str_concat/rules/explicit.rs
@@ -98,6 +98,8 @@ pub(crate) fn explicit(checker: &Checker, expr: &Expr) {
                 };
                 // If either `left` or `right` is parenthesized, generating
                 // a fix would be too involved. Just report the diagnostic.
+                // Currently, attempting `generate_fix` would result in
+                // an invalid code. See: #19757
                 if is_parenthesized(left) || is_parenthesized(right) {
                     return;
                 }
```

File: crates/ruff_linter/src/rules/flake8_implicit_str_concat/rules/explicit.rs (hunk 2 above)
Comment (prakhar1144) [reply crates/ruff_linter/src/rules/flake8_implicit_str_concat/rules/explicit.rs:98]: > I think it would also be better to have a function that takes both left and right sides at the same time

That'd result in the new function body being:
```rs
  is_left_parenthesized = parenthesized_range(
      left.into(),
      bin_op.into(),
      checker.comment_ranges(),
      checker.source(),
  )
  .is_some();
  
   is_right_parenthesized = parenthesized_range(
      right.into(),
      bin_op.into(),
      checker.comment_ranges(),
      checker.source(),
  )
  .is_some();
  
  is_left_parenthesized || is_right_parenthesized
 ```
 
 which is a bit verbose... with repeated code ?
 
 I had thought about a separate function while writing this, but preferred this approach because:
 * It's only called twice in adjacent lines, localized scope, so closure felt natural
 * it doesn't have complex logic worth unit testing

**Comment by prakhar1144** [comment]
This is ready to review.

**Review by amyreese — APPROVED** [review]
