### PR TITLE
[ty] Respect mixed positional and keyword arguments in TypedDict constructor

### LINKED ISSUE #3225: TypedDict constructor doesn't respect positional overrides
We currently reject this:
```python
from typing import TypedDict

class Child(TypedDict, total=False):
    count: int

Child({"count": "wrong"}, count=1)
```

Despite the fact that `"count"` will be correctly set to `1`.

https://play.ty.dev/e4266330-3863-4c36-8d3c-0b61b9a9613e

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

This PR ensures that we allow the following by adding a path for mixed positional and keyword arguments:

```python
from typing import TypedDict

class Base(TypedDict):
    name: str

class ChildKwargs(TypedDict):
    name: str
    count: int

def _(base: Base):
    ok_union_mapping = ChildKwargs(base, count=1)
```

Closes https://github.com/astral-sh/ty/issues/3225.

### CODE REVIEW

**Comment by carljm** [comment]
Was there a motivating use case for this in the ecosystem? It seems like technically we are already going beyond the spec by supporting a positional argument in a TypedDict constructor at all (though we aren't alone in doing so). @JelleZijlstra suggested in https://github.com/python/typing/issues/2161 that perhaps these mixed cases should be explicitly disallowed.

**Comment by charliermarsh** [comment]
I can't quite remember, unfortunately. It fell out of work on https://github.com/astral-sh/ruff/pull/23936. If you think it's not important to support, I won't argue strongly for it.

**Comment by carljm** [comment]
@AlexWaygood, what do you think?

On one hand, the code in the OP here looks quite reasonable to me, and it's not really clear how else you'd write it.

On the other hand, the ecosystem diff suggests that supporting this has very little impact.

@JelleZijlstra I'm curious if you had specific unsoundnesses in mind which this is likely to allow. It seems like the key thing is just modeling that keyword arguments take precedence over items in the positional argument?

**Comment by charliermarsh** [comment]
(I _think_ `ChildKwargs(**base, count=1)` would be equivalent, and wouldn't suffer from the same problem?)

**Comment by charliermarsh** [comment]
(Err, if `base` already has `count`, that would error.)

**Comment by carljm** [comment]
> (I _think_ `ChildKwargs(**base, count=1)` would be equivalent, and wouldn't suffer from the same problem?)

Ok, yeah, that's a fine way to write it. I guess I should just say, the OP way seems perfectly reasonable too.

**Comment by JelleZijlstra** [comment]
I was thinking of cases like https://github.com/JelleZijlstra/unsoundness/blob/main/examples/typeddicts/typeddict_double_starargs.py, where a TypedDict smuggles in extra arguments that cause unsoundness. But I later realized that you don't actually need to mix positional and keyword arguments for that category of unsoundness to appear. These things could be fixed by being strict about closed TypedDicts (PEP 728).

So I don't think this is particularly more likely to lead to additional unsoundness.

**Comment by carljm** [comment]
I'm inclined to go ahead with this, unless others are opposed. It permits more valid programs, and the cost of it seems low. Will give it a full review once the PR it's stacked on top of lands and it's rebased.

**Comment by charliermarsh** [comment]
(Will rebase today.)

**Comment by charliermarsh** [comment]
This ended up being quite complex (or, at least, lengthy) to support. I'd understand if we want to draw a line somewhere and call some things unsupported.

File: crates/ty_python_semantic/src/types/infer/builder/typed_dict.rs [hunk 1]
```diff
@@ -15,13 +15,54 @@ use crate::types::diagnostic::{
...
+    KeywordOnly,
+    /// // Ex) `TD({"x": 1})`
+    LiteralOnly(&'expr ast::Expr),
+    /// // Ex) `TD(other)`
+    SinglePositional(&'expr ast::Expr),
+    /// // Ex) `TD({"x": 1}, y=2)`
+    MixedLiteralAndKeywords(&'expr ast::ExprDict),
+    /// // Ex) `TD(other, y=2)`
+    MixedPositionalAndKeywords,
+}
```
Comment (charliermarsh) [inline crates/ty_python_semantic/src/types/infer/builder/typed_dict.rs:41]: This refactor isn't specific to this newly-supported form, but we now support so many forms that I found it much easier to reason about this way.

File: crates/ty_python_semantic/src/types/infer/builder/typed_dict.rs [hunk 2]
```diff
@@ -15,13 +15,54 @@ use crate::types::diagnostic::{
...
+    }
+}
+
+/// How general call binding should treat arguments after `TypedDict`-specific preparation.
+#[derive(Debug, Clone, Copy)]
+pub(super) enum TypedDictConstructorBindingStrategy {
+    /// Reuse the cached results from `TypedDict`-specific preparation.
+    ReusePreparedExpressions,
+    /// Skip re-inferring the outer positional dict literal with this node index.
+    SkipPreparedPositionalDictLiteral(NodeIndex),
```
Comment (charliermarsh) [inline crates/ty_python_semantic/src/types/infer/builder/typed_dict.rs]: This is used exclusively for the `TD({"a": 1}, b=2)` case... Here, we want to give precise diagnostics baed on what's in `{"a": 1}` (e.g., are there extra keys?), but we need to see the keyword arguments before we can do so. So we pre-infer the literal's nested expressions, validate the constructor, then skip re-inferring the _outer_ dict literal as a standalone expression.

File: crates/ty_python_semantic/src/types/infer/builder/typed_dict.rs [hunk 3]
```diff
@@ -15,13 +15,54 @@ use crate::types::diagnostic::{
...
+    /// // Ex) `TD({"x": 1}, y=2)`
+    MixedLiteralAndKeywords(&'expr ast::ExprDict),
+    /// // Ex) `TD(other, y=2)`
+    MixedPositionalAndKeywords,
+}
+
+impl<'expr> TypedDictConstructorForm<'expr> {
+    /// Return the constructor form for `arguments`.
+    pub(super) fn from_arguments(arguments: &'expr ast::Arguments) -> Self {
+        let [argument] = &arguments.args[..] else {
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/infer/builder/typed_dict.rs:46]: It seems like our behavior in case of multiple positional arguments is not ideal; we effectively treat the call the same as if it had no arguments. The worst effect of this is in the edge case of an empty TypedDict, where we'll allow a constructor call to it with 2+ positional arguments, with no diagnostic.

But this also seems to be the case currently on main, so I guess it could be considered a bug orthogonal to this PR? We should file an issue for it, though.

File: crates/ty_python_semantic/src/types/infer/builder/typed_dict.rs [hunk 4]
```diff
@@ -303,31 +344,99 @@ impl<'db> TypeInferenceBuilder<'db, '_> {
...
+                let positional_target =
+                    typed_dict_with_relaxed_keys(self.db(), typed_dict, &keyword_keys);
+                let target_ty = UnionType::from_two_elements(
+                    self.db(),
+                    Type::TypedDict(positional_target),
+                    KnownClass::Dict.to_specialized_instance(
+                        self.db(),
+                        &[KnownClass::Str.to_instance(self.db()), Type::object()],
+                    ),
+                );
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/infer/builder/typed_dict.rs]: I don't understand why we would union with `dict[str, object]` here -- this feels like the wrong workaround for the test that it makes pass. Commented above.

File: crates/ty_python_semantic/resources/mdtest/typed_dict.md [hunk 5]
```diff
@@ -464,6 +464,113 @@ Record({VALUE_KEY: "x"}, count=1)
...
+Conditional plain-dict positional mappings should not be validated as `TypedDict` literals:
+
+```py
+from typing import TypedDict
+
+class ConditionalTarget(TypedDict):
+    a: int
+
+def _(cond: bool):
+    ConditionalTarget({"x": 1} if cond else {}, a=1)
```
Comment (carljm) [inline crates/ty_python_semantic/resources/mdtest/typed_dict.md]: This test feels off (and so does the union with `dict[str, object]` code below that makes it pass). Why does the fact that it's conditional matter here? If we should let this code pass, then we should also let `ConditionalTarget({"x": 1}, a=1)` pass; there's no principled difference between them. But this PR doesn't make the latter pass.

The question of whether `ConditionalTarget({"x": 1}, a=1)` (or any variant of it) should pass is a tricky one. In theory it should, since `ConditionalTarget` is not a `closed=True` typed dict. But type checkers have generally been strict about not allowing extra keys in constructors, even for non-closed typed dicts, as typo prevention.

But I feel like that's a topic for a separate PR. For this PR, I think we should remove this test, and remove the union-with-dict code below.

File: crates/ty_python_semantic/src/types/infer/builder/typed_dict.rs (hunk 2 above)
Comment (carljm) [reply crates/ty_python_semantic/src/types/infer/builder/typed_dict.rs]: If we just pre-emptively stored a type of `Unknown` (or even a better type) for the outer dict literal in this case, when preparing typed dict arguments, would that eliminate the need for this binding-strategy stuff?

File: crates/ty_python_semantic/src/types/typed_dict.rs [hunk 6]
```diff
@@ -917,6 +958,225 @@ fn extract_unpacked_typed_dict_keys<'db>(
...
+        .collect();
+
+    for unpacked_type in unpacked_keyword_types.iter().copied().flatten() {
+        if unpacked_type.is_never() || unpacked_type.is_dynamic() {
+            provided_keys.extend(
+                typed_dict.items(db).iter().filter_map(|(key_name, field)| {
+                    field.is_required().then_some(key_name.clone())
+                }),
+            );
+        } else if let Some(unpacked_keys) = extract_unpacked_typed_dict_keys(db, unpacked_type) {
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/typed_dict.rs:1010]: This only extracts keys from unpacked typed dicts, not from unpacked dict literals. Which means that in this example, the first construction still fails, even though the other two succeed:

```py
from typing import TypedDict

class TD(TypedDict):
    a: int
    
def _(td: TD):
    TD({"a": "foo"}, **{"a": 1})
    TD({"a": "foo"}, a=1)
    TD({"a": "foo"}, **td)
```

This seems inconsistent, but maybe in practice not important. It could be an added test with TODO comment.

File: crates/ty_python_semantic/src/types/typed_dict.rs [hunk 7]
```diff
@@ -917,6 +958,225 @@ fn extract_unpacked_typed_dict_keys<'db>(
...
+    debug_assert_eq!(arguments.keywords.len(), unpacked_keyword_types.len());
+
+    let mut provided_keys: OrderSet<Name> = arguments
+        .keywords
+        .iter()
+        .filter_map(|keyword| keyword.arg.as_ref().map(|arg| arg.id.clone()))
+        .collect();
+
+    for unpacked_type in unpacked_keyword_types.iter().copied().flatten() {
+        if unpacked_type.is_never() || unpacked_type.is_dynamic() {
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/typed_dict.rs:1001]: This is interesting, since it means we will now allow this example to pass with no error:

```py
from typing import TypedDict, Any

class TD(TypedDict):
    a: int
    
def _(x: Any):
    TD({"a": "foo"}, **x)
```

Codex flagged this as a regression, and it is a behavior change in this branch. But I think it is a correct change: `Any` should be assumed to materialize in such a way as to render the code correct, if such a materialization is possible, and this behavior follows that rule. Once I pushed back, Codex agreed that this is actually consistent with our handling of dynamic types elsewhere in TypedDict construction, e.g. allowing `TD(**typed_as_any)`.

**Review by carljm — APPROVED** [review]
It's pretty cool that we can handle all this. I am a bit worried about the additional difficulty this will add to our implementation of PEP 728 -- supporting `closed=True` typed dicts will require adding another case to most of this logic. But on the whole I still favor going ahead with it.

File: crates/ty_python_semantic/src/types/infer/builder/typed_dict.rs (hunk 3 above)
Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/infer/builder/typed_dict.rs:46]: I'm going to add an error for 2+ positional, but leave some TODOs for improving them later (e.g., we may still want to validate the first argument).

File: crates/ty_python_semantic/src/types/typed_dict.rs (hunk 6 above)
Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/typed_dict.rs:1010]: I actually worked on this in a separate PR -- I'll TODO it and continue that work once this merges: https://github.com/astral-sh/ruff/pull/24523

File: crates/ty_python_semantic/src/types/infer/builder/typed_dict.rs (hunk 2 above)
Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/infer/builder/typed_dict.rs]: Thanks, this is way better.
