### PR TITLE
Fix D204 when there's a semicolon after a docstring

### LINKED ISSUE #7088: Rules D204 cause autofix error
Ruff 0.0.287 (latest changes from main branch)
```
ruff  *.py --select D204 --no-cache --fix
```

file content(at least simple cpython script shows that this is valid python file):
```
class ServiceSorter(ABC):
	def sort_services(self,services):0
class DefaultPrioritySorter(ServiceSorter):
	'Default service sorting approach that always give S3 the highest priority.';priorities={'s3':100,'lambda':1}
	def sort_services(A,services):return sorted(services,key=lambda k:A.priorities.get(k,0),reverse=True)
```

error
```
/home/rafal/test/tmp_folder/39521.py:4:2: D204 1 blank line required after class docstring
Found 1 error.

error: Autofix introduced a syntax error. Reverting all changes.

This indicates a bug in `ruff`. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BAutofix%20error%5D

...quoting the contents of `/home/rafal/test/tmp_folder/39521.py`, the rule codes D204, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!


```
    
[python_compressed.zip](https://github.com/astral-sh/ruff/files/12506516/python_compressed.zip)

### PR DESCRIPTION
**Pull request by konstin**
## Summary

Another statement on the same line as the docstring would previous make the D204 (newline after docstring) fix fail:

```python
class StatementOnSameLineAsDocstring:
    "After this docstring there's another statement on the same line separated by a semicolon." ;priorities=1
    def sort_services(self):
        pass
```

The fix handles this case manually:

```python
class StatementOnSameLineAsDocstring:
    "After this docstring there's another statement on the same line separated by a semicolon."

    priorities=1
    def sort_services(self):
        pass
```

Fixes #7088

## Test Plan

Added a new `D` test case

### CODE REVIEW

**Comment by konstin** [comment]
Current dependencies on/for this PR:
* main
  * **PR #7173** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff/7173" target="_blank">Graphite</a> 
    * **PR #7174** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff/7174" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/astral-sh/ruff/7174?utm_source=stack-comment).

File: crates/ruff/src/rules/pydocstyle/rules/blank_before_after_class.rs [hunk 1]
```diff
@@ -228,8 +228,33 @@ pub(crate) fn blank_before_after_class(checker: &mut Checker, docstring: &Docstr
...
         let mut lines = UniversalNewlineIterator::with_offset(after, after_range.start());
+        let first_line = lines.next();
+        let first_line_start = first_line.as_ref().map(|l| l.start()).unwrap_or_default();
+
+        // Edge case: The next statement after the docstring is on the same line separated by a
+        // semicolon.
+        if let Some(first_line) = &first_line {
+            if !first_line.trim().is_empty() {
+                let next_statement = after
+                    .trim_start()
```
Comment (konstin) [inline crates/ruff/src/rules/pydocstyle/rules/blank_before_after_class.rs:239]: @MichaReiser since this is not indentation but whitespace between statement and a following `;` i don't need to use the python whitespace functions, right?

File: crates/ruff/src/rules/pydocstyle/rules/blank_before_after_class.rs [hunk 2]
```diff
@@ -228,8 +228,33 @@ pub(crate) fn blank_before_after_class(checker: &mut Checker, docstring: &Docstr
...
+                    .strip_prefix(';')
+                    .expect("Another statement on the same line must be separated by a semicolon");
```
Comment (charliermarsh) [inline crates/ruff/src/rules/pydocstyle/rules/blank_before_after_class.rs:241]: What if it’s followed by a comment?

File: crates/ruff/src/rules/pydocstyle/rules/blank_before_after_class.rs (hunk 1 above)
Comment (charliermarsh) [reply crates/ruff/src/rules/pydocstyle/rules/blank_before_after_class.rs:239]: It’s best to use the Python whitespace functions unless you’re parsing text within a string or within a comment (is my understanding).

File: crates/ruff/src/rules/pydocstyle/rules/blank_before_after_class.rs [hunk 3]
```diff
@@ -228,8 +228,33 @@ pub(crate) fn blank_before_after_class(checker: &mut Checker, docstring: &Docstr
         }
 
         let mut lines = UniversalNewlineIterator::with_offset(after, after_range.start());
+        let first_line = lines.next();
+        let first_line_start = first_line.as_ref().map(|l| l.start()).unwrap_or_default();
+
+        // Edge case: The next statement after the docstring is on the same line separated by a
+        // semicolon.
+        if let Some(first_line) = &first_line {
```
Comment (charliermarsh) [inline crates/ruff/src/rules/pydocstyle/rules/blank_before_after_class.rs:236]: We have some has_following_content utilities - can we use any of them here?

File: crates/ruff/src/rules/pydocstyle/rules/blank_before_after_class.rs (hunk 1 above)
Comment (MichaReiser) [reply crates/ruff/src/rules/pydocstyle/rules/blank_before_after_class.rs:239]: From the python spec

> Except at the beginning of a logical line or in string literals, the whitespace characters space, tab and formfeed can be used interchangeably to separate tokens. Whitespace is needed between two tokens only if their concatenation could otherwise be interpreted as a different token (e.g., ab is one token, but a b is two tokens).

[source](https://docs.python.org/3/reference/lexical_analysis.html#whitespace-between-tokens)

To me this means that any other whitespace should not be considered whitespace and are a syntax error (because whitespace isn't a valid identifier start). 

I use the python whitespace methods consistently to:

* Avoid having to reason about whether it is guaranteed that the input program is correct and thus, it is safe to accept all whitesapce
* `is_python_whitespace` (or the trim variants) could in theory be faster because they can operate on bytes (no unicode)

File: crates/ruff/src/rules/pydocstyle/rules/blank_before_after_class.rs [hunk 4]
```diff
@@ -228,8 +228,33 @@ pub(crate) fn blank_before_after_class(checker: &mut Checker, docstring: &Docstr
...
+                    diagnostic.set_fix(Fix::automatic(Edit::replacement(
+                        line_ending.to_string() + line_ending + indentation + next_statement,
+                        first_line_start,
+                        first_line.end(),
+                    )));
+                }
+                checker.diagnostics.push(diagnostic);
+                return;
+            }
+        }
```
Comment (MichaReiser) [inline crates/ruff/src/rules/pydocstyle/rules/blank_before_after_class.rs:256]: Could we move this up to line 223 where we intentionally skip the first line? 

We could then improve the perforamnce by cloning the univeral newlines iterator rather than creating a new one from scratch on line 230. That avoids that we scan the first line 2 (actually 3 times, 2 to find the end of the first line, once to trim it.)

**Review by MichaReiser — APPROVED** [review]

File: crates/ruff/src/rules/pydocstyle/rules/blank_before_after_class.rs (hunk 2 above)
Comment (konstin) [reply crates/ruff/src/rules/pydocstyle/rules/blank_before_after_class.rs:241]: Good catch, added a comment test

File: crates/ruff/src/rules/pydocstyle/rules/blank_before_after_class.rs (hunk 3 above)
Comment (konstin) [reply crates/ruff/src/rules/pydocstyle/rules/blank_before_after_class.rs:236]: i tried but i don't think they fit here

File: crates/ruff/src/rules/pydocstyle/rules/blank_before_after_class.rs (hunk 4 above)
Comment (konstin) [reply crates/ruff/src/rules/pydocstyle/rules/blank_before_after_class.rs]: Turns out we do actually have to parse the first line twice
