### PR TITLE
Ignore `NPY201` inside `except` blocks for compatibility with older numpy versions

### LINKED ISSUE #12476: NPY201 triggers on code written to support both numpy 2 and legacy numpy
Considder an example like this which is explicitly written to support both numpy 2 and legacy numpy
```
import warnings

try:
    from numpy.exceptions import VisibleDeprecationWarning
except ImportError:
    # numpy < 1.25.0
    from numpy import VisibleDeprecationWarning


with warnings.catch_warnings():
    warnings.filterwarnings(
        "ignore",
        category=VisibleDeprecationWarning,
        message="Creating an ndarray from ragged nested sequences",
    )
```

Running `ruff check file.py` with NPY201 enabled triggers

```
error: Failed to create fix for Numpy2Deprecation: Unable to insert `VisibleDeprecationWarning` into scope due to name conflict
src\qcodes\utils\numpy_utils.py:13:18: NPY201 `np.VisibleDeprecationWarning` will be removed in NumPy 2.0. Use `numpy.exceptions.VisibleDeprecationWarning` instead.
   |
11 |     warnings.filterwarnings(
12 |         "ignore",
13 |         category=VisibleDeprecationWarning,
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^ NPY201
14 |         message="Creating an ndarray from ragged nested sequences",
15 |     )
   |
   = help: Replace with `numpy.exceptions.VisibleDeprecationWarning`
```
This is a false positive since the deprecated location is only used in legacy numpy versions that do not have a exceptions submodule.

This started happening in 0.5.1 probably as a result of #12065

Keyworkds Numpy, NPY201

Ruff 0.5.1 to 0.5.4

Config:

```
[tool.ruff.lint]
select = ["NPY201"]
```

### PR DESCRIPTION
**Pull request by AlexWaygood**
## Summary

Fixes #12476.

This PR makes it so that deprecated imports and attribute accesses of numpy members are ignored in the following conditions:

- For attribute accesses (e.g. `np.ComplexWarning`), we only ignore the violation if it's inside an `except AttributeError` block, and the member is accessed through its non-deprecated name in the associated `try` block.
- For uses of the `numpy` member where it's simply an `ExprName` node, we check to see how the `numpy` member was bound. If it was bound via a `from numpy import foo` statement, we check to see if that import statement took place inside an `except ImportError` or `except ModuleNotFoundError` block. If so, and if the `numpy` member was imported through its non-deprecated name in the associated try block, we ignore the violation in the same way.

Examples:

```py
import numpy as np

try:
    np.all([True, True])
except AttributError:
    np.alltrue([True, True])  # Okay

try:
    from numpy.exceptions import ComplexWarning
except ImportError:
    from numpy import ComplexWarning

x = ComplexWarning()  # Okay
```

This was more complex than I expected, since we currently track _handled_ exceptions in the semantic model, but we don't track _suspended_ exceptions. I.e., if we're in a lint rule and we're examining a node inside a `try` block, we know which exceptions the enclosing `StmtTry` node handles. But if we're in a lint rule and we're examining a node inside an `except` block, we don't have that information easily to hand.

## Test Plan

Added some fixtures and snapshots.

### CODE REVIEW

**Comment by MichaReiser** [comment]
The lexer benchmark is drunk!

**Comment by AlexWaygood** [comment]
> The lexer benchmark is drunk!

Hey, I'll take it!

File: crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs [hunk 1]
```diff
@@ -701,3 +707,233 @@ pub(crate) fn numpy_2_0_deprecation(checker: &mut Checker, expr: &Expr) {
...
+                return false;
+            }
+            let Some(try_node) = semantic
+                .current_statements()
+                .find_map(|stmt| stmt.as_try_stmt())
+            else {
+                return false;
+            };
+            let suspended_exceptions = Exceptions::from_try_stmt(try_node, semantic);
+            if !suspended_exceptions.contains(Exceptions::ATTRIBUTE_ERROR) {
```
Comment (charliermarsh) [inline crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs:760]: Can we check `semantic.handled_exceptions` instead? Does that work? Then we wouldn't need to find the try statement or anything.

Comment (AlexWaygood) [reply crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs:760]: No, `semantic.handled_exceptions` records the exceptions if we're visiting the `try` block of a `try`/`except` statement. But here we're visiting the `except` block of a `try`/`except` statement. Hence "suspended_exceptions" rather than "handled_exceptions".

File: crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs [hunk 2]
```diff
@@ -701,3 +707,233 @@ pub(crate) fn numpy_2_0_deprecation(checker: &mut Checker, expr: &Expr) {
...
+    false
+}
+
+/// AST visitor that searches an AST tree for [`ast::StmtImportFrom`] nodes
+/// that match a certain [`QualifiedName`].
+struct ImportSearcher<'a> {
+    module: &'a str,
+    name: &'a str,
+    found_import: bool,
+}
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs:910]: I don't think it matters much because we only run this code in the error case, but it is kind of expensive. Do we have no way of resolving the statement in which a binding is declared and then traverse upwards (by using the parent API?)

File: crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs [hunk 3]
```diff
@@ -701,3 +707,233 @@ pub(crate) fn numpy_2_0_deprecation(checker: &mut Checker, expr: &Expr) {
...
+                    .iter()
+                    .any(|ast::Alias { name, .. }| name == self.name)
+            {
+                self.found_import = true;
+                return;
+            }
+        }
+        ast::visitor::walk_stmt(self, stmt);
+    }
+}
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs:939]: Nit: Add an empty `visit_expression` to avoid traversing **into** expressions or implement `StatementVisitor`

File: crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs (hunk 1 above)
Comment (AlexWaygood) [reply crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs:760]: Also we still need to find the node for the `try` statement so that we can check whether it was accessed via the undeprecated call path in the `try` block

File: crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs [hunk 4]
```diff
@@ -701,3 +707,233 @@ pub(crate) fn numpy_2_0_deprecation(checker: &mut Checker, expr: &Expr) {
...
+            found_attribute: false,
+        }
+    }
+}
+
+impl Visitor<'_> for AttributeSearcher<'_> {
+    fn visit_expr(&mut self, expr: &'_ Expr) {
+        if self.found_attribute {
+            return;
+        }
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs:865]: Nit: It could make sense to add a `visit_stmt` implementation that short-circuits visiting when `self.found_attribute` is true (or `visit_body`)

**Review by MichaReiser — APPROVED** [review]
Looks good. Maybe give @charliermarsh a grace period of a day to look at the semantic model changes ;)

File: crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs (hunk 2 above)
Comment (AlexWaygood) [reply crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs:910]: The situation is that we're visiting an `except` block in a `try`/`except` statement. We find a deprecated numpy access in that `except` block. We need to find out if there's an undeprecated access in the `try` block of the `try`/`except` statement. The way I do this is by traversing upwards from the node we're linting in the `except` block (using the parent API) to find the `StmtTry` node, then from the `StmtTry` node I then traverse downwards into the `try` block using the `ImportSearcher` to find if there are any imports using the undeprecated API.

File: crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs (hunk 4 above)
Comment (AlexWaygood) [reply crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs:866]: Thanks, I pushed that change! Wasn't quite sure what best practices were here, since there's a lot of `visit_*` methods on the `Visitor` trait that could potentially be overridden here to short-circuit. I guess most of the other ones generally delegate to `visit_expr` and `visit_stmt`?

File: crates/ruff_linter/src/checkers/ast/mod.rs [hunk 5]
```diff
@@ -1853,6 +1841,10 @@ impl<'a> Checker<'a> {
             self.semantic.scope_id
         };
 
+        if self.semantic.in_exception_handler() {
+            flags |= BindingFlags::IN_EXCEPT_HANDLER;
+        }
```
Comment (charliermarsh) [inline crates/ruff_linter/src/checkers/ast/mod.rs:1846]: Idly wondering if we should just store the semantic model flags on the binding, in theory it's tiny.

File: crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs [hunk 6]
```diff
@@ -701,3 +708,240 @@ pub(crate) fn numpy_2_0_deprecation(checker: &mut Checker, expr: &Expr) {
...
+fn enclosing_try_node<'a>(
+    node_id: NodeId,
+    semantic: &'a SemanticModel,
+) -> Option<&'a ast::StmtTry> {
+    let mut node_id = node_id;
+    loop {
+        node_id = semantic.parent_statement_id(node_id)?;
+        if let ast::Stmt::Try(try_node) = semantic.statement(node_id) {
+            return Some(try_node);
+        }
```
Comment (charliermarsh) [inline crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs:806]: Could you instead add a method `statements` to the semantic model that's identical to the `pub fn expressions(&self, node_id: NodeId) -> impl Iterator<Item = &'a Expr> + '_` variant? Or is this doing something else?

File: crates/ruff_linter/src/checkers/ast/mod.rs (hunk 5 above)
Comment (AlexWaygood) [reply crates/ruff_linter/src/checkers/ast/mod.rs:1846]: As in, get rid of the separate `BindingFlags` struct altogether, and store the semantic-model flags on `Binding` instead? Or store the semantic-model flags in addition to the `BindingFlags`?

File: crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs [hunk 7]
```diff
@@ -701,3 +708,240 @@ pub(crate) fn numpy_2_0_deprecation(checker: &mut Checker, expr: &Expr) {
...
+    let undeprecated_qualified_name = {
+        let mut builder = QualifiedNameBuilder::default();
+        for part in path.split('.') {
+            builder.push(part);
+        }
+        builder.push(name);
+        builder.build()
+    };
+    let mut attribute_searcher = AttributeSearcher::new(undeprecated_qualified_name, semantic);
+    for stmt in &try_node.body {
```
Comment (charliermarsh) [inline crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs:835]: I think you can just call `visit_body`, or is this an optimization?

**Review by charliermarsh — APPROVED** [review]

File: crates/ruff_linter/src/checkers/ast/mod.rs (hunk 5 above)
Comment (charliermarsh) [reply crates/ruff_linter/src/checkers/ast/mod.rs:1846]: Store them in addition (and then remove this flag from `BindingFlags`). But, it's ok, no need to change.

File: crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs (hunk 7 above)
Comment (AlexWaygood) [reply crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs:835]: naw this is a good point

File: crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs (hunk 6 above)
Comment (AlexWaygood) [reply crates/ruff_linter/src/rules/numpy/rules/numpy_2_0_deprecation.rs:806]: Ahh, nice idea
