### PR TITLE
[`flake8-pyi`] Fix more complex cases (`PYI019`)

### LINKED ISSUE #15798: Request: More unsafe fixes for `custom-type-var-return-type`/`PYI019`
### Description

This is a direct follow-up to https://github.com/astral-sh/ruff/issues/14183, which was closed by #14238 but there are still cases that I think can be autofixed. Namely, when other method params than `self`/`cls` are typed.

For example, as of Ruff 0.9.3:

This is currently autofixed
```py
class _BaseHeterogeneousEnsemble(MetaEstimatorMixin, _BaseComposition, metaclass=ABCMeta):
    def set_params(self: _BaseHeterogeneousEnsemble_Self, **params) -> _BaseHeterogeneousEnsemble_Self: ...
```

But these aren't:
```py
class _SigmoidCalibration(RegressorMixin, BaseEstimator):
    def fit(
        self: _SigmoidCalibration_Self,
        X: ArrayLike,
        y: ArrayLike,
        sample_weight: None | ArrayLike = None,
    ) -> _SigmoidCalibration_Self: ...


class _PLS(
    ClassNamePrefixFeaturesOutMixin,
    TransformerMixin,
    RegressorMixin,
    MultiOutputMixin,
    BaseEstimator,
    metaclass=ABCMeta,
):
    def fit(self: _PLS_Self, X: MatrixLike, Y: MatrixLike | ArrayLike) -> _PLS_Self: ...


class _BaseNMF(ClassNamePrefixFeaturesOutMixin, TransformerMixin, BaseEstimator, ABC):
    def fit(self: _BaseNMF_Self, X: MatrixLike | ArrayLike, y: Any = None, **params) -> _BaseNMF_Self: ...


class _BinMapper(TransformerMixin, BaseEstimator):
    def fit(self: _BinMapper_Self, X: MatrixLike, y=None) -> _BinMapper_Self: ...


class _BaseFilter(SelectorMixin, BaseEstimator):
    def fit(self: _BaseFilter_Self, X: MatrixLike, y: ArrayLike) -> _BaseFilter_Self: ...


class _BinaryGaussianProcessClassifierLaplace(BaseEstimator):
    def fit(
        self: _BinaryGaussianProcessClassifierLaplace_Self,
        X: MatrixLike | ArrayLike,
        y: ArrayLike,
    ) -> _BinaryGaussianProcessClassifierLaplace_Self: ...


class _GeneralizedLinearRegressor(RegressorMixin, BaseEstimator):
    def fit(
        self: _GeneralizedLinearRegressor_Self,
        X: MatrixLike | ArrayLike,
        y: ArrayLike,
        sample_weight: None | ArrayLike = None,
    ) -> _GeneralizedLinearRegressor_Self: ...


class _RidgeGCV(LinearModel):
    def fit(
        self: _RidgeGCV_Self,
        X: MatrixLike,
        y: MatrixLike | ArrayLike,
        sample_weight: float | None | ArrayLike = None,
    ) -> _RidgeGCV_Self: ...


class _MultiOutputEstimator(MetaEstimatorMixin, BaseEstimator, metaclass=ABCMeta):
    def partial_fit(
        self: _MultiOutputEstimator_Self,
        X: MatrixLike | ArrayLike,
        y: MatrixLike,
        classes: Sequence[ArrayLike] | None = None,
        sample_weight: None | ArrayLike = None,
    ) -> _MultiOutputEstimator_Self: ...
```
(examples taken from https://github.com/astral-sh/ruff/issues/14183#issuecomment-2481832123 and https://github.com/microsoft/python-type-stubs/pull/340)

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
## Summary

Resolves #15798.

`PYI019` is now a binding-based rule. All references to the type variable will now be replaced correctly. As a result, the fix is now safe in most cases; when that is not possible, its applicability remains display-only. Additionally, for a safe fix, comments within the fix ranges will cause it to be marked as unsafe.

## Test Plan

`cargo nextest run` and `cargo insta test`.

### CODE REVIEW

**Comment by AlexWaygood** [comment]
> I'll rebase this once you give the heads-up.

Okay, I'm done -- rebase at your leisure! Thanks :-)

File: crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs [hunk 1]
```diff
@@ -79,46 +81,49 @@ impl Violation for CustomTypeVarReturnType {
...
+    let self_or_cls_annotation = parameters
         .posonlyargs
         .iter()
         .chain(&parameters.args)
         .next()
-        .and_then(|parameter_with_default| parameter_with_default.parameter.annotation.as_ref())
-    else {
-        return;
-    };
+        .and_then(|parameter_with_default| parameter_with_default.parameter.annotation.as_ref())?;
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs:108]: I would do

```rs
    let self_or_cls_annotation = parameters
        .posonlyargs
        .iter()
        .chain(&parameters.args)
        .next()?
        .parameter
        .annotation
        .as_ref()?;
```

File: crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs [hunk 2]
```diff
@@ -296,33 +295,60 @@ fn replace_custom_typevar_with_self(
...
 
-    let (edits, fix_applicability) =
-        replace_typevar_usages_with_self(&function_def.parameters, typevar_name);
+    if let Some(mut edits) = replace_typevar_usages_with_self(
+        typevar,
+        &self_symbol_binding,
+        replace_references_range,
+        checker.semantic(),
+    ) {
+        other_edits.append(&mut edits);
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs:333]:
```suggestion
    if let Some(edits) = replace_typevar_usages_with_self(
        typevar,
        &self_symbol_binding,
        replace_references_range,
        checker.semantic(),
    ) {
        other_edits.extend(edits);
```

File: crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs [hunk 3]
```diff
@@ -79,46 +81,51 @@ impl Violation for CustomTypeVarReturnType {
...
+) -> Option<Diagnostic> {
+    if !matches!(binding.kind, BindingKind::FunctionDefinition(_)) {
+        return None;
+    }
+
+    let semantic = checker.semantic();
+
+    let current_scope = &semantic.scopes[binding.scope];
+
+    let function_def = binding.statement(semantic)?.as_function_def_stmt()?;
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs:95]: nit: not really sure we need all these blank lines; the code here isn't that complex

```suggestion
    let semantic = checker.semantic();
    let current_scope = &semantic.scopes[binding.scope];
    let function_def = binding.statement(semantic)?.as_function_def_stmt()?;
```

File: crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs [hunk 4]
```diff
@@ -296,33 +297,60 @@ fn replace_custom_typevar_with_self(
...
         return Ok(None);
     };
 
-    let typevar_name = &typevar_name.id;
+    let mut applicability = Applicability::Safe;
+
+    let typevar_name = &typevar.id;
 
-    let (import_edit, self_symbol_binding) = import_self(checker, returns.start())?;
+    let (first_edit, self_symbol_binding) = import_self(checker, returns.start())?;
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs:308]: nit: I prefer the existing variable name `import_edit` here. It's what we generally call this variable in other rules, and it's more descriptive about what the edit does

File: crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs [hunk 5]
```diff
@@ -296,33 +297,60 @@ fn replace_custom_typevar_with_self(
...
+    )];
 
-    all_edits.extend(remove_typevar_declaration(
+    let replace_references_range = {
+        let edit = remove_first_parameter_annotation(&function_def.parameters);
+        let first_parameter_end = edit.end();
+
+        other_edits.push(edit);
+
+        TextRange::new(first_parameter_end, returns.start())
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs:321]:
```suggestion
        let first_parameter_end = edit.end();
        other_edits.push(edit);
        TextRange::new(first_parameter_end, returns.start())
```

**Comment by AlexWaygood** [comment]
> @AlexWaygood This PR now introduces a regression:

I think you can do something like this:

```diff
diff --git a/crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs b/crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs
index 4d30fd3eb..7128fddb1 100644
--- a/crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs
+++ b/crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs
@@ -8,7 +8,7 @@ use ruff_python_ast::{
 };
 use ruff_python_semantic::analyze::function_type::{self, FunctionType};
 use ruff_python_semantic::analyze::visibility::{is_abstract, is_overload};
-use ruff_python_semantic::{Binding, BindingKind, SemanticModel};
+use ruff_python_semantic::{Binding, BindingKind, ScopeId, SemanticModel};
 use ruff_text_size::{Ranged, TextRange, TextSize};
 
 use crate::checkers::ast::Checker;
@@ -138,7 +138,7 @@ pub(crate) fn custom_type_var_return_type(
         }),
     };
 
-    if !method.uses_custom_var(semantic) {
+    if !method.uses_custom_var(semantic, binding.scope) {
         return None;
     }
 
@@ -162,9 +162,9 @@ enum Method<'a> {
 }
 
 impl Method<'_> {
-    fn uses_custom_var(&self, semantic: &SemanticModel) -> bool {
+    fn uses_custom_var(&self, semantic: &SemanticModel, scope: ScopeId) -> bool {
         match self {
-            Self::Class(class_method) => class_method.uses_custom_var(semantic),
+            Self::Class(class_method) => class_method.uses_custom_var(semantic, scope),
             Self::Instance(instance_method) => instance_method.uses_custom_var(),
         }
     }
@@ -180,7 +180,7 @@ struct ClassMethod<'a> {
 impl ClassMethod<'_> {
     /// Returns `true` if the class method is annotated with
     /// a custom `TypeVar` that is likely private.
-    fn uses_custom_var(&self, semantic: &SemanticModel) -> bool {
+    fn uses_custom_var(&self, semantic: &SemanticModel, scope: ScopeId) -> bool {
         let Expr::Subscript(ast::ExprSubscript {
             value: cls_annotation_value,
             slice: cls_annotation_typevar,
@@ -196,7 +196,15 @@ impl ClassMethod<'_> {
 
         let cls_annotation_typevar = &cls_annotation_typevar.id;
 
-        if !semantic.match_builtin_expr(cls_annotation_value, "type") {
+        let Expr::Name(ExprName { id, ..}) = &**cls_annotation_value else {
+            return false;
+        };
+
+        if id != "type" {
+            return false;
+        }
+
+        if !semantic.has_builtin_binding_in_scope("type", scope) {
             return false;
         }
 
@@ -206,7 +214,10 @@ impl ClassMethod<'_> {
                 let Expr::Name(return_annotation_typevar) = &**slice else {
                     return false;
                 };
-                if !semantic.match_builtin_expr(value, "type") {
+                let Expr::Name(ExprName { id, ..}) = &**value else {
+                    return false;
+                };
+                if id != "type" {
                     return false;
                 }
                 &return_annotation_typevar.id
diff --git a/crates/ruff_python_semantic/src/model.rs b/crates/ruff_python_semantic/src/model.rs
index 4ef240e23..825ee3256 100644
--- a/crates/ruff_python_semantic/src/model.rs
+++ b/crates/ruff_python_semantic/src/model.rs
@@ -265,13 +265,22 @@ impl<'a> SemanticModel<'a> {
         self.shadowed_bindings.get(&binding_id).copied()
     }
 
-    /// Return `true` if `member` is bound as a builtin.
+    /// Return `true` if `member` is bound as a builtin *in the scope we are currently visiting*.
     ///
     /// Note that a "builtin binding" does *not* include explicit lookups via the `builtins`
     /// module, e.g. `import builtins; builtins.open`. It *only* includes the bindings
     /// that are pre-populated in Python's global scope before any imports have taken place.
     pub fn has_builtin_binding(&self, member: &str) -> bool {
-        self.lookup_symbol(member)
+        self.has_builtin_binding_in_scope(member, self.scope_id)
+    }
+
+    /// Return `true` if `member` is bound as a builtin *in a given scope*.
+    ///
+    /// Note that a "builtin binding" does *not* include explicit lookups via the `builtins`
+    /// module, e.g. `import builtins; builtins.open`. It *only* includes the bindings
+    /// that are pre-populated in Python's global scope before any imports have taken place.
+    pub fn has_builtin_binding_in_scope(&self, member: &str, scope_id: ScopeId) -> bool {
+        self.lookup_symbol_in_scope(member, scope_id, false)
             .map(|binding_id| &self.bindings[binding_id])
             .is_some_and(|binding| binding.kind.is_builtin())
     }
```

It will still mean that the PR introduces a small regression (new false negatives for annotations like `cls: builtins.type[S]` in classmethods). But false negatives are much better than false positives. And I think the small regression of some edge-case false negatives is hugely outweighed by the improvements you're introducing in this PR!

File: crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs [hunk 6]
```diff
@@ -79,46 +81,51 @@ impl Violation for CustomTypeVarReturnType {
...
 pub(crate) fn custom_type_var_return_type(
-    checker: &mut Checker,
-    function_def: &ast::StmtFunctionDef,
-) {
+    checker: &Checker,
+    binding: &Binding,
+) -> Option<Diagnostic> {
+    if !matches!(binding.kind, BindingKind::FunctionDefinition(_)) {
+        return None;
+    }
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs:89]: I think this is redundant considering you have `let function_def = binding.statement(semantic)?.as_function_def_stmt()?;` a few lines below. That already ensures that we won't emit this diagnostic on a `Binding` unless that binding is associated with a function-definition statement

```suggestion
```

File: crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs [hunk 7]
```diff
@@ -79,46 +81,44 @@ impl Violation for CustomTypeVarReturnType {
...
         .iter()
         .chain(&parameters.args)
-        .next()
-        .and_then(|parameter_with_default| parameter_with_default.annotation())
-    else {
-        return;
-    };
+        .next()?
+        .parameter
+        .annotation()?;
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs:103]:
```suggestion
        .next()?
        .annotation()?;
```

File: crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs [hunk 8]
```diff
@@ -345,39 +375,33 @@ fn remove_first_parameter_annotation(parameters: &Parameters) -> Edit {
     Edit::deletion(first.name().end(), first.end())
 }
 
-fn replace_return_annotation_with_self(self_symbol_binding: String, returns: &Expr) -> Edit {
-    Edit::range_replacement(self_symbol_binding, returns.range())
+fn replace_return_annotation_with_self(self_symbol_binding: &str, returns: &Expr) -> Edit {
+    Edit::range_replacement(self_symbol_binding.to_string(), returns.range())
 }
 
 fn replace_typevar_usages_with_self(
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs:382]: Can you add some docs to this function? It was quite unclear to me at first why it returns an `Option<Vec<Edit>>` rather than just returning an empty `Vec` in the cases where it currently returns `None`. I think it's because if we can't resolve the binding to something in this module, we can't be sure that the binding refers to a private TypeVar. Is that correct?

It would also be good to explain what `editable_range` represents, and why we only replace references to the TypeVar if the references lie within that range

File: crates/ruff_python_semantic/src/model.rs [hunk 9]
```diff
@@ -271,7 +271,16 @@ impl<'a> SemanticModel<'a> {
     /// module, e.g. `import builtins; builtins.open`. It *only* includes the bindings
     /// that are pre-populated in Python's global scope before any imports have taken place.
     pub fn has_builtin_binding(&self, member: &str) -> bool {
-        self.lookup_symbol(member)
+        self.has_builtin_binding_in_scope(member, self.scope_id)
+    }
+
+    /// Return `true` if `member` is bound as a builtin *in the scope we are currently visiting*.
```
Comment (AlexWaygood) [inline crates/ruff_python_semantic/src/model.rs:277]:
```suggestion
    /// Return `true` if `member` is bound as a builtin *in a given scope*.
```

And you need ot change the sentence on line 268 to add `*in the scope we are currently visiting*` to the end of it.

**Comment by AlexWaygood** [comment]
> Very unfortunately, no. This would have problems similar to that of #15862.

You're worried about references inside stringized type expressions? That doesn't seem like a _great_ reason to restrict the rule to stub files, since stringized type expressions are legal in stub files as well as `.py` files (they're just not encouraged). It would be better to detect if any of the references are inside stringized type expressions, and make the fix display-only if so.

But anyway, let's land this as-is for now. It's a big improvement as it is, and the PR is big enough as it is. I have some followup work locally that I can file as PRs to build on this.

File: crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs [hunk 10]
```diff
@@ -345,39 +374,38 @@ fn remove_first_parameter_annotation(parameters: &Parameters) -> Edit {
     Edit::deletion(first.name().end(), first.end())
 }
 
-fn replace_return_annotation_with_self(self_symbol_binding: String, returns: &Expr) -> Edit {
-    Edit::range_replacement(self_symbol_binding, returns.range())
+fn replace_return_annotation_with_self(self_symbol_binding: &str, returns: &Expr) -> Edit {
+    Edit::range_replacement(self_symbol_binding.to_string(), returns.range())
 }
 
+/// Returns a series of [`Edit`]s that modify all references to the given `typevar`,.
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs:381]:
```suggestion
/// Returns a series of [`Edit`]s that modify all references to the given `typevar`,
```

**Review by AlexWaygood — APPROVED** [review]
Thank you!

**Comment by AlexWaygood** [comment]
Sure, but users are fickle, and may only have some of the flake8-pyi rules enabled ;)
