### PR TITLE
[red-knot] Fix panic for `tuple[x[y]]` string annotation

### LINKED ISSUE #17775: [red-knot] Panic: Could not find missing expression ID
A few ecosystem projects currently fail with
```
thread '<unnamed>' panicked at crates/red_knot_python_semantic/src/semantic_index/ast_ids.rs:39:13:
Could not find expression ID for ExpressionNodeKey(NodeKey(131888927259800))
```
(see `bad.txt` => "missing expression ID")

### PR DESCRIPTION
**Pull request by sharkdp**
## Summary

closes #17775

## Test Plan

Added corpus regression test

### CODE REVIEW

**Comment by MichaReiser** [comment]
Nice!

**Comment by sharkdp** [comment]
So this is a bit unfortunate… the `mypy_primer` run fails because I'm adding projects that are still panicking in the old state on `main`. Ideally, we'd only fail that run if we're introducing new panics.

File: crates/red_knot_python_semantic/src/types/infer.rs [hunk 1]
```diff
@@ -7624,10 +7624,15 @@ impl<'db> TypeInferenceBuilder<'db> {
...
-                        builder.expression_type(value),
-                        Type::KnownInstance(KnownInstanceType::Unpack)
-                    )
+                    let value_ty = if builder.deferred_state.in_string_annotation() {
+                        // Using `.expression_type` does not work in string annotations, because
+                        // we do not store types for sub-expressions. Re-infer the type here.
+                        builder.infer_expression(value)
+                    } else {
+                        builder.expression_type(value)
+                    };
```
Comment (AlexWaygood) [inline crates/red_knot_python_semantic/src/types/infer.rs:7633]: oof, that seems a bit unfortunate. Does that mean we should just get rid of the `expression_type()` API altogether? Or have `expression_type()` itself check whether we're in a deferred string annotation (and fallback to `infer_expression()` if so)?

It feels like a bit of a footgun if we have to always make sure we're not in a deferred string annotation before calling `expression_type()`

Comment (sharkdp) [reply crates/red_knot_python_semantic/src/types/infer.rs:7633]: Good questions. It's certainly possible that we have other hidden problems with calling `expression_type` for something that might be inside a string annotation. But note that it's not common to re-enter a sub-AST and match on inner elements (and then use `expression_type`) after the type has already been inferred. Usually, in functions like `infer_expression`, we return types "back up" to the caller, i.e. to outer elements. Admittedly, I did not think too much about this exact callsite because this whole function is basically a large "To do" and will disappear eventually.
