### PR TITLE
Client request sender and inbound response handling for `ruff server`

### LINKED ISSUE #10618: `ruff server` editor integration is broken
Diagnostics weren't showing up when debugging the new Ruff VS Code extension locally. While investigating this issue, I found these logs, which happen immediately following client/server initialization:
```
[info] [Trace - <TIME>] Sending request 'textDocument/codeAction - (2)'.
[info] [Trace - <TIME>] Received request 'client/registerCapability - (1)'.
...
ERROR ruff_server::server Expected request or notification, got response instead: Response { id: RequestId(I32(1)), result: None, error: None }
```

The issue here is that the client fires off a `codeAction` request before responding to the `registerCapability` request from the client. On the server side, we're awaiting and then flushing an incoming response to the `registerCapability` request. Instead, we flush the `codeAction` request by mistake, and this lack of response breaks the LSP integration because the JSON-RPC protocol requires that every request has a response.

This is also why the error log later appears. Because we only flush the first message we receive, the response from the client is handled in the main event loop, which isn't expected.

### PR DESCRIPTION
**Pull request by snowsignal**
## Summary

Fixes #10618.

This PR introduces a proper API for sending requests to the client and handling any response sent back. Dynamic capability registration now uses this new API, fixing an issue where a much more simplistic response handler silently flushes a code action request that needed a response.

## Test Plan

#10618 can no longer be reproduced. No errors about unhandled responses should appear in the extension output, and you should see this new log when the server starts:
```
<DATE> <TIME> [info] <DURATION> INFO ruff_server::server Configuration file watcher successfully registered
```

### CODE REVIEW

File: crates/ruff_server/src/server.rs [hunk 1]
```diff
@@ -146,11 +97,14 @@ impl Server {
...
+        client_capabilities: &ClientCapabilities,
+        mut session: Session,
         worker_threads: NonZeroUsize,
-        _next_request_id: AtomicI32,
     ) -> crate::Result<()> {
-        let mut scheduler = schedule::Scheduler::new(session, worker_threads, &connection.sender);
+        let mut scheduler =
+            schedule::Scheduler::new(&mut session, worker_threads, &connection.sender);
+
+        Self::try_register_capabilities(client_capabilities, &mut scheduler);
```
Comment (charliermarsh) [inline crates/ruff_server/src/server.rs:107]: Is the right way to think of this that:

- We might have some responses on `connection.receiver` already (but they can be buffered).
- We kick off a "blocking" request to register capabilities, and wait for the client to respond.
- Once the client responds, we move to to processing messages on `connection.receiver`.

File: crates/ruff_server/src/server.rs [hunk 2]
```diff
@@ -160,18 +114,69 @@ impl Server {
                     api::request(req)
                 }
                 lsp::Message::Notification(notification) => api::notification(notification),
-                lsp::Message::Response(response) => {
-                    tracing::error!(
-                        "Expected request or notification, got response instead: {response:?}"
-                    );
-                    continue;
-                }
+                lsp::Message::Response(response) => scheduler.response(response),
```
Comment (charliermarsh) [inline crates/ruff_server/src/server.rs:117]: I may not have enough context on this piece. Why is this now not an error?

Comment (snowsignal) [reply crates/ruff_server/src/server.rs:117]: It was an error before because we didn't have any reason to receive a response from the server. Now that we have an interface to send the client requests, we do want to listen for responses.

File: crates/ruff_server/src/server.rs (hunk 1 above)
Comment (charliermarsh) [reply crates/ruff_server/src/server.rs:107]: Ahh ok makes sense. Is it important that the dynamic capabilities response is handled "first", or it's ok if they're out-of-order? (Do we enforce the order in any way?)

**Review by charliermarsh — APPROVED** [review]

File: crates/ruff_server/src/server.rs (hunk 1 above)
Comment (snowsignal) [reply crates/ruff_server/src/server.rs:107]: > (Do we enforce the order in any way?)

We don't enforce the order - we rely on `lsp_server::Connection` to give us messages in the order the client sent them. The LSP specification requires that [requests on both sides are processed in the order that they're received](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#messageOrdering), but it doesn't say that all incoming requests need to be handled before responses, or vice-versa.

> Is it important that the dynamic capabilities response is handled "first", or it's ok if they're out-of-order?

In this specific instance, it's absolutely fine to have this happen out-of-order because the response handler doesn't do anything besides log a success. Technically, the client could wait an arbitrary amount before sending this response if it wanted to (though that would be rude).

I think this scenario would also work in the general case:
```
1. client sends request A to server
2. server sends request B to client
3. server sends response A to client
4. client sends response B response to server
```

The response handler for `response B` would be run with a potentially different state then when `request B` was sent occurred if `request A` was a local task that modified the state, but the response handler shouldn't have any guarantees on execution order to begin with.

File: crates/ruff_server/src/server.rs [hunk 3]
```diff
@@ -160,18 +114,69 @@ impl Server {
...
+            let response_handler = |()| {
+                tracing::info!("Configuration file watcher successfully registered");
+                Task::nothing()
+            };
+
+            if let Err(err) = scheduler
+                .request::<lsp_types::request::RegisterCapability>(params, response_handler)
+            {
+                tracing::error!("An error occurred when trying to register the configuration file watcher: {err}");
+            }
```
Comment (MichaReiser) [inline crates/ruff_server/src/server.rs:174]: Nit: This is not something we need to immediately follow up. It's more an observation and maybe we have ideas on how we could improve it later on. 

What would be nice is if it wouldn't be necessary to specify the `Request` type when calling the function, and instead could let Rust infer it. I think the issue here is that we pass the parameters but there's no way to get to the request from the parameters (only the other way around). 
I don't have a solution to it, but thought it might be worth raising because maybe you have a great idea on how this could be improved.

**Review by MichaReiser — COMMENTED** [review]
Nice! It removes the need for the atomic request counter and we get full request/response support.

File: crates/ruff_server/src/server.rs (hunk 3 above)
Comment (snowsignal) [reply crates/ruff_server/src/server.rs:174]: Unfortunately I think this is just a limitation of Rust's type resolver, and I understand why. It would definitely be nice if the compiler could infer the type from the `Params` + `Result` type, but it would fail in a scenario where multiple requests had the same `Params` and `Result` type.

I'm fine with being explicit about the request type, to be honest. We do something similar when creating tasks for API endpoints. We *could* make the request a function argument and that would remove the need to specify the generic parameter, but I prefer putting it in angle brackets 😄
