### PR TITLE
[`pyupgrade`] Make fix unsafe if it deletes comments (`UP050`)

### LINKED ISSUE #18387: UP050 fix should be unsafe when it deletes a comment
### Summary

When the fix for [`useless-class-metaclass-type` (UP050)](https://docs.astral.sh/ruff/rules/useless-class-metaclass-type/) deletes a comment, it should be marked unsafe.

```console
$ cat >up050.py <<'# EOF'
class C(
    object,  # Explicit is better than implicit.
    metaclass=type,
): ...
# EOF

$ ruff --isolated check up050.py --select UP050 --preview --fix
Found 1 error (1 fixed, 0 remaining).

$ cat up050.py
class C(
    object,
): ...
```

### Version

ruff 0.11.12 (aee3af0f7 2025-05-29)

### PR DESCRIPTION
**Pull request by chirizxc**
## Summary
/closes #18387

## Test Plan
update snapshots

### CODE REVIEW

File: crates/ruff_linter/src/rules/pyupgrade/rules/useless_class_metaclass_type.rs [hunk 1]
```diff
@@ -63,13 +64,25 @@ pub(crate) fn useless_class_metaclass_type(checker: &Checker, class_def: &StmtCl
...
+
+                    let range = edit.range();
+                    let applicability = if checker.comment_ranges().intersects(range) {
+                        Applicability::Unsafe
+                    } else {
+                        Applicability::Safe
+                    };
+
+                    Ok(
+                        Fix::applicable_edit(edit, applicability).isolate(Checker::isolation(
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/pyupgrade/rules/useless_class_metaclass_type.rs]: Do we need this `isolate` call?

**Review by ntBre — APPROVED** [review]
