### PR TITLE
[ty] Treat `__setattr__` as fallback-only

### LINKED ISSUE #1460: treat `__setattr__` as fallback only
### Question

I recently noticed that ty complains about attribute assignment in `torch.nn.Module` subclasses that other type checkers do not complain about. If I run ty on the following MWE:

```python
import torch

class MyModule(torch.nn.Module):
    def __init__(self, param: int = 42) -> None:
        self.some_param = param
```

ty complains with the error:

```
error[unresolved-attribute]: Can not assign object of type `int` to attribute `some_param` on type `Self@__init__` with custom `__setattr__` method.
 --> ty_test.py:6:9
  |
4 | class MyModule(torch.nn.Module):
5 |     def __init__(self, param: int = 42) -> None:
6 |         self.some_param = param
  |         ^^^^^^^^^^^^^^^
  |
info: rule `unresolved-attribute` is enabled by default
```

However, if I instead use `self.some_param: int = param`, ty does not complain. Is this intended behavior? Other type checkers do not complain, since the type seems clear from the method signature.

The root cause seems to be `torch.nn.Module`'s custom `__setattr__` implementation, which claims that it only accepts `Union[Tensor, "Module"]`, but in reality forwards any other types to `super().__setattr__` (see [here](https://github.com/pytorch/pytorch/blob/main/torch/nn/modules/module.py#L2078-L2079)
).

### Version

ty 0.0.1-alpha.25

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Closes https://github.com/astral-sh/ty/issues/1460.

### CODE REVIEW

**Review by carljm — COMMENTED** [review]
Behavior looks good here but I find the implementation surprising. Is it not possible to check for explicit attributes before trying to call `__setattr__` at all?

**Comment by charliermarsh** [comment]
I did it that way initially but it ended up being a fairly large change (by LOC), I'll try it again though.

**Comment by carljm** [comment]
I'm not worried about a big change by LOC, I would care if it ended up being a lot more net code or more confusing code.

It just seems odd to check `__setattr__` at all if we might not care about the result.

**Comment by charliermarsh** [comment]
Okay, reordered the operations.

File: crates/ty_python_semantic/src/types/infer/builder.rs [hunk 1]
```diff
@@ -4578,222 +4578,251 @@ impl<'db, 'ast> TypeInferenceBuilder<'db, 'ast> {
...
-                                                 whose `__setattr__` method returns `Never`/`NoReturn`",
-                                            object_ty.display(db)
-                                        )
-                                    };
-
-                                    builder.into_diagnostic(msg);
-                                }
-                            }
-                            false
+                // Check if `__setattr__` returns `Never` (indicating an immutable class).
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/infer/builder.rs:4687]: Oops, the existence of this special case invalidates my previous comment. If we have to try `__setattr__` first regardless, then we should go back to your previous version where we just do it once. Sorry!

File: crates/ty_python_semantic/resources/mdtest/attributes.md [hunk 2]
```diff
@@ -2002,6 +2002,64 @@ def _(ns: argparse.Namespace):
...
+    x: float
+
+    def __setattr__(self, name: str, value: int) -> NoReturn:
+        raise AttributeError("Immutable")
+
+def _(obj: Immutable) -> None:
+    # Even though `"foo"` doesn't match `__setattr__`'s `value: int` parameter,
+    # we still detect that `__setattr__` returns `Never` and block the assignment.
+    # error: [invalid-assignment] "Cannot assign to attribute `x` on type `Immutable` whose `__setattr__` method returns `Never`/`NoReturn`"
+    obj.x = "foo"
```
Comment (charliermarsh) [inline crates/ty_python_semantic/resources/mdtest/attributes.md:2056]: I _think_ this is the desired behavior.

Comment (carljm) [reply crates/ty_python_semantic/resources/mdtest/attributes.md:2056]: I think it's somewhat arbitrary whether we prefer the "returns NoReturn" or the attribute type error here, but I agree this way is probably a bit better.

**Comment by carljm** [comment]
We are now adding a lot more new diagnostics in the ecosystem than we were on a previous iteration of this PR. Looking into what changed...

**Comment by charliermarsh** [comment]
(I will review.)

**Comment by charliermarsh** [comment]
I think it's because we're now validating against `__set__` instead of `__setattr__`?

**Review by carljm — APPROVED** [review]
Sorry, got midway through a review of this and then lost track of it in my notifications. Looks good to me! I spot-checked a number of the new diagnostics, and they all look correct (at least as far as this PR goes).
