### PR TITLE
Fix false positive in  for mutations in return statements (B909)

### LINKED ISSUE #18399: B909 false positive when directly returning mutation
### Summary

The B909 rule checks for mutations to loop iterables, but permits cases where `return`/`break` would prevent further iterations. However if the `return` and the mutation are the same statement it flags the value.

Example:
```py
def fail_map(mapping):
    for key in mapping:
        return mapping.pop(key)  # false positive

def success_map(mapping):
    for key in mapping:
        ret = mapping.pop(key)  # passes
        return ret

def fail_list(seq):
    for val in seq:
        return seq.pop(4)  # also false positive
```
Used `ruff check --preview --isolated --select B909 iter_mut_bug.py`.

### Version

ruff 0.11.11 (0397682f1 2025-05-22)

### PR DESCRIPTION
**Pull request by K-dash**
## Summary

Fixes false positive in B909 (`loop-iterator-mutation`) where mutations inside return/break statements were incorrectly flagged as violations.
The fix adds tracking for when mutations occur within return/break statements and excludes them from violation detection, as they don't cause the iteration issues B909 is designed to prevent.

## Test Plan

  - Added test cases covering the reported false positive scenarios to `B909.py`
  - Verified existing B909 tests continue to pass (no regressions)
  - Ran `cargo test -p ruff_linter --lib flake8_bugbear` successfully

Fixes #18399

### CODE REVIEW

File: crates/ruff_linter/src/rules/flake8_bugbear/rules/loop_iterator_mutation.rs [hunk 1]
```diff
@@ -280,12 +286,17 @@ impl<'a> Visitor<'a> for LoopMutationsVisitor<'a> {
                 }
             }
 
-            // On break, clear the mutations for the current branch.
+            // On break or return, set flag to ignore mutations within the statement expression
             Stmt::Break(_) | Stmt::Return(_) => {
+                let old_flag = self.in_return_or_break;
+                self.in_return_or_break = true;
+                visitor::walk_stmt(self, stmt);
+                self.in_return_or_break = old_flag;
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/flake8_bugbear/rules/loop_iterator_mutation.rs]: If we're not going to add the mutations anyway, can we simply skip the `walk_stmt` call here?
```suggestion
```

I tried this locally and it seems to work, but maybe there's an edge case I'm missing. I even found the [commit](https://github.com/astral-sh/ruff/pull/9578/commits/8fe10406c5a80c76af2233de533be1847cac9e53) from the initial PR that added the rule, but I didn't see any reasoning for including it, so hopefully we're safe to skip it if all the tests pass.

**Review by ntBre — COMMENTED** [review]
Thanks! The new tests look great, but I think there might be a simpler fix for the issue.

File: crates/ruff_linter/src/rules/flake8_bugbear/rules/loop_iterator_mutation.rs (hunk 1 above)
Comment (K-dash) [reply crates/ruff_linter/src/rules/flake8_bugbear/rules/loop_iterator_mutation.rs]: You're absolutely right. 
Since we're not walking the statement at all, there's no need for the flag-based approach. The mutations simply won't be detected in the first place because we skip traversing the expressions within return/break statements entirely.

I've simplified the implementation to just skip the `walk_stmt` call. Thanks for the review!

File: crates/ruff_linter/src/rules/flake8_bugbear/rules/loop_iterator_mutation.rs [hunk 2]
```diff
@@ -145,6 +145,7 @@ struct LoopMutationsVisitor<'a> {
     mutations: HashMap<u32, Vec<TextRange>>,
     branches: Vec<u32>,
     branch: u32,
+    in_return_or_break: bool,
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/flake8_bugbear/rules/loop_iterator_mutation.rs]: I think we should also revert this field addition. I'm a bit surprised clippy didn't catch it, but I suppose it does look used.

Comment (K-dash) [reply crates/ruff_linter/src/rules/flake8_bugbear/rules/loop_iterator_mutation.rs]: Oh... You're totally right. I've already reverted the field addition and simplified the implementation. The `in_return_or_break` field has been removed along with all its associated logic. Thanks for catching that!

**Comment by K-dash** [comment]
@ntBre 
I was wondering if you've had a chance to review this yet?
I would greatly appreciate your feedback when you have the opportunity.
