### PR TITLE
[`pylint`] Fix `PLW0108` autofix introducing a syntax error when the lambda's body contains an assignment expression

### LINKED ISSUE #18675: PLW0108 fix mishandles assignment expressions
### Summary

The fix for [`unnecessary-lambda` (PLW0108)](https://docs.astral.sh/ruff/rules/unnecessary-lambda/) introduces a syntax error when the callable in the top level of the lambda expression is an assignment expression. It should be parenthesized.

```console
$ cat >plw0108_1.py <<'# EOF'
f = lambda x: (string := str)(x)
print(f(0))
# EOF

$ python plw0108_1.py
0

$ ruff --isolated check plw0108_1.py --select PLW0108 --preview --unsafe-fixes --diff 2>&1 | grep error:
error: Fix introduced a syntax error. Reverting all changes.
```

The fix can also change behavior when a variable bound by an assignment expression is one of the lambda expression’s parameters. The fix is already documented as unsafe because “the lambda body itself could contain an effect”, but in this case, the body is guaranteed to contain an effect, and there is no straightforward way to refactor it, so I recommend the fix be suppressed.

```console
$ cat >plw0108_2.py <<'# EOF'
x = None
f = lambda x: ((x := 1) and str)(x)
print(f(0))
print(x)
# EOF

$ python plw0108_2.py
1
None

$ ruff --isolated check plw0108_2.py --select PLW0108 --preview --unsafe-fixes --fix
Found 1 error (1 fixed, 0 remaining).

$ cat plw0108_2.py
x = None
f = (x := 1) and str
print(f(0))
print(x)

$ python plw0108_2.py
0
1
```

### Version

ruff 0.11.13 (5faf72a4d 2025-06-05)

### PR DESCRIPTION
**Pull request by LaBatata101**
## Summary

This PR also supresses the fix if the assignment expression target shadows one of the lambda's parameters.

Fixes #18675

## Test Plan

Add regression tests.

### CODE REVIEW

File: crates/ruff_linter/src/rules/pylint/rules/unnecessary_lambda.rs [hunk 1]
```diff
@@ -209,9 +211,32 @@ pub(crate) fn unnecessary_lambda(checker: &Checker, lambda: &ExprLambda) {
...
+            {
+                return;
+            }
+        }
+    }
+
     diagnostic.set_fix(Fix::applicable_edit(
         Edit::range_replacement(
-            checker.locator().slice(func.as_ref()).to_string(),
+            if matches!(func.as_ref(), Expr::Named(_)) {
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/pylint/rules/unnecessary_lambda.rs]: Could we use `func.is_named_expr()` here?

File: crates/ruff_linter/src/rules/pylint/rules/unnecessary_lambda.rs [hunk 2]
```diff
@@ -209,9 +211,32 @@ pub(crate) fn unnecessary_lambda(checker: &Checker, lambda: &ExprLambda) {
...
+                format!("({})", checker.locator().slice(func.as_ref()))
+            } else {
+                checker.locator().slice(func.as_ref()).to_string()
+            },
             lambda.range(),
         ),
         Applicability::Unsafe,
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/pylint/rules/unnecessary_lambda.rs]: This isn't actually related to your PR, but we could just use `Fix::unsafe_edit` while we're here and not need `Applicability` at all.

**Review by ntBre — APPROVED** [review]
Thanks! I just had one nit and an unrelated refactor we could do while we're here, but this looks good to me.

**Review by ntBre — APPROVED** [review]
Thanks! I'll merge after the patch release is finished.
