### PR TITLE
[red-knot] Error out when an mdtest code block is unterminated

### LINKED ISSUE #14934: [red-knot] mdtest should fail if you have a triple-backtick block that is unclosed
If you have an [mdtest](https://github.com/astral-sh/ruff/tree/main/crates/red_knot_test) like this at the end of the Markdown file, it doesn't fail:

````
# bytes should be inferred as strings

```py
x = b"42"

reveal_type(x)  # revealed: str
````

That's because the backticks are never closed, so mdtest doesn't even recognise this as a test snippet. I _keep on_ making this mistake locally and wondering why my tests aren't even running! It would be ideal if the framework could detect this and tell me that my test file is invalid because the backticks were never closed.

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
## Summary

Resolves #14934.

## Test Plan

Added a unit test.

### CODE REVIEW

File: crates/red_knot_test/src/parser.rs [hunk 1]
```diff
@@ -328,6 +334,13 @@ impl<'s> Parser<'s> {
         // We never pop the implicit root section.
         let section = self.stack.top();
 
+        if captures.name("end").unwrap().is_empty() {
+            return Err(anyhow::anyhow!(
+                "Unterminated code block at index {}.",
```
Comment (carljm) [inline crates/red_knot_test/src/parser.rs:339]: This will always say "at index 0" no matter where in the file the unterminated code block starts, because of the way we use `Cursor` to advance through the source text; we are always matching this regex at the start of a string. (Checked this experimentally.)

I _think_ (not tested) that `self.cursor.token_len()` will give you the offset into the original source text that we've consumed so far, and still let you easily provide this info in the error. If for some reason that doesn't work, I'm also OK with just not providing this data. In practice, I'm not sure how useful it is, because I _think_ if any code block other than the last one is unterminated, you'll just get a situation where the contents between the unterminated code block and the next will get swallowed, and it'll end up reporting a later code block as unterminated, not the one you actually need to fix?

File: crates/red_knot_test/src/parser.rs [hunk 2]
```diff
@@ -664,6 +677,18 @@ mod tests {
...
+    #[test]
+    fn unterminated_code_block() {
+        let source = dedent(
+            "
+            ```
+            x = 1
+            ",
+        );
+        let err = super::parse("file.md", &source).expect_err("Should fail to parse");
+        assert_eq!(err.to_string(), "Unterminated code block at index 0.");
```
Comment (carljm) [inline crates/red_knot_test/src/parser.rs:689]: Maybe use an example where the code block doesn't start at position 0 in the source text (i.e. preface the source text with some prose or a header) so this test would have caught the issue with the index reporting.

**Comment by carljm** [comment]
Thank you!

File: crates/red_knot_test/src/parser.rs [hunk 3]
```diff
@@ -328,6 +344,16 @@ impl<'s> Parser<'s> {
         // We never pop the implicit root section.
         let section = self.stack.top();
 
+        if captures.name("end").unwrap().is_empty() {
+            let code_block_start = self.cursor.token_len();
+            let row = self.source.count_lines(TextRange::up_to(code_block_start)) + 1;
+
+            return Err(anyhow::anyhow!(
+                "Unterminated code block at: {}:{row}:0",
+                self.source_path
```
Comment (carljm) [inline crates/red_knot_test/src/parser.rs:353]: All errors are already output with the full path as a prefix, so as you have it this ends up rendering as:

```
Error parsing `/Users/carlmeyer/projects/ruff/crates/red_knot_python_semantic/resources/mdtest/scopes/unbound.md`: Unterminated code block at: /Users/carlmeyer/projects/ruff/crates/red_knot_python_semantic/resources/mdtest/scopes/unbound.md:47:0
```

Which seems a bit redundant :)

```suggestion
                "Unterminated code block starting on line {row}",
```

File: crates/red_knot_test/src/lib.rs [hunk 4]
```diff
@@ -28,7 +28,7 @@ const MDTEST_TEST_FILTER: &str = "MDTEST_TEST_FILTER";
 #[allow(clippy::print_stdout)]
 pub fn run(path: &Utf8Path, long_title: &str, short_title: &str, test_name: &str) {
     let source = std::fs::read_to_string(path).unwrap();
-    let suite = match test_parser::parse(short_title, &source) {
+    let suite = match test_parser::parse(short_title, &source, path) {
         Ok(suite) => suite,
         Err(err) => {
             panic!("Error parsing `{path}`: {err:?}")
```
Comment (carljm) [inline crates/red_knot_test/src/lib.rs:34]: Here's where we already show the path in every error.

Comment (carljm) [reply crates/red_knot_test/src/lib.rs]: Looks good, to keep this PR focused. Future PR to further improve error output here is welcome!

**Review by carljm — APPROVED** [review]

**Comment by AlexWaygood** [comment]
Thanks @InSyncWithFoo! :D
