### PR TITLE
[`pyupgrade`] Add spaces between tokens as necessary to avoid syntax errors in `UP018` autofix

### LINKED ISSUE #17606: UP018 fix should add spaces between tokens
### Summary

The fix for [`native-literals` (UP018)](https://docs.astral.sh/ruff/rules/native-literals/) should add spaces between tokens as necessary to avoid syntax errors and other problems.

Reverted syntax error:
```console
$ cat >up018_1.py <<'# EOF'
bool(True)and None
# EOF

$ ruff --isolated check up018_1.py --select UP018 --diff 2>&1 | grep error:
error: Fix introduced a syntax error. Reverting all changes.
```

Runtime `SyntaxWarning`s:
```console
$ cat >up018_2.py <<'# EOF'
int(1)and None
float(1.)and None
# EOF

$ ruff --isolated check up018_2.py --select UP018 --fix
Found 2 errors (2 fixed, 0 remaining).

$ cat up018_2.py
1and None
1.and None

$ python up018_2.py
up018_2.py:1: SyntaxWarning: invalid decimal literal
  1and None
up018_2.py:2: SyntaxWarning: invalid decimal literal
  1.and None
```

Runtime behavior change:
```console
$ cat >up018_3.py <<'# EOF'
bool(True)and()
# EOF

$ ruff --isolated check up018_3.py --select UP018 --fix
Found 1 error (1 fixed, 0 remaining).

$ cat up018_3.py
Trueand()

$ python up018_3.py 
Traceback (most recent call last):
  File "up018_3.py", line 1, in <module>
    Trueand()
    ^^^^^^^
NameError: name 'Trueand' is not defined
```

### Version

ruff 0.11.6 (fcd50a049 2025-04-17)

### PR DESCRIPTION
**Pull request by LaBatata101**
## Summary

Is it better to add another edit in the fix to add the space, or this is fine?
https://github.com/LaBatata101/ruff/blob/032bd2edcb7a3576ac0a69fd193a675639b5ea0e/crates/ruff_linter/src/rules/pyupgrade/rules/native_literals.rs#L284-L286

Fixes #17606

## Test Plan
Snapshot tests.

### CODE REVIEW

File: crates/ruff_linter/src/rules/pyupgrade/rules/native_literals.rs [hunk 1]
```diff
@@ -244,7 +245,22 @@ pub(crate) fn native_literals(
...
             let arg_code = checker.locator().slice(arg);
 
-            let content = match (parent_expr, literal_type, has_unary_op) {
+            let mut needs_space = false;
+            // Look for the `Rpar` token of the call expression and check if there is a keyword token right
+            // next to it without any space separating them. Without this check, the fix for this
+            // rule would create a syntax error.
+            // Ex) `bool(True)and None` no space between `)` and the keyword `and`.
+            if let Ok(token_idx) =
+                tokens.binary_search_by(|token| token.range().end().cmp(&call_range.end()))
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pyupgrade/rules/native_literals.rs:254]: Would it be possible to use `after` or `in_range` here over implementing the binary search manually

File: crates/ruff_linter/src/rules/pyupgrade/rules/native_literals.rs [hunk 2]
```diff
@@ -244,7 +245,22 @@ pub(crate) fn native_literals(
...
+            {
+                let token = tokens.get(token_idx).unwrap();
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pyupgrade/rules/native_literals.rs:256]:
```suggestion
                let token = &tokens[token_idx];
```

**Review by MichaReiser — COMMENTED** [review]
I think what you did is fine. I'm somewhat inclined to instead look at the `parent_expr` but I can see that this might be harder (simply because we already use it in the check)

**Review by MichaReiser — APPROVED** [review]
