### PR TITLE
Ignore TODO tags in `commented-out-code`

### LINKED ISSUE #7031: Eradicate (ERA001) is triggered on well formated TODO
`ruff 0.0.286`

When my TODO is bad (according to the TD rules), it's not reported as unused code
But when I fix TD warnings the code becomes a subject of ERA

Broken TODO
```python
def foo():
    # TODO: implement
    pass
```

```shell
ruff "foo.py"  --select TD002,ERA
TD002 Missing author in TODO; try: `# TODO(<author_name>): ...` or `# TODO @<author_name>: ...`
```

When I fix this warning
```python
def foo():
    # TODO(CJ): implement
    pass

```

```shell
ruff foo.py --select TD002,ERA
ERA001 [*] Found commented-out code
Found 1 error.
[*] 1 potentially fixable with the --fix option.
```

I expect that the TODO comment should not be marked as unused code.  And TD requirements were aligned with other rules.

### PR DESCRIPTION
**Pull request by tjkuson**
## Summary

Extend the `task-tags` checking logic to ignore TODO tags (with or without parentheses). For example,

```python
# TODO(tjkuson): Rewrite in Rust
```

is no longer flagged as commented-out code.

Closes #7031.

I also updated the documentation to inform users that the rule is prone to false positives like this!

EDIT: Accidentally linked to the wrong issue when first opening this PR, now corrected.

## Test Plan

`cargo test`

### CODE REVIEW

File: crates/ruff/src/rules/eradicate/detection.rs [hunk 1]
```diff
@@ -6,7 +6,7 @@ use ruff_python_parser::parse_suite;
 
 static ALLOWLIST_REGEX: Lazy<Regex> = Lazy::new(|| {
     Regex::new(
-        r"^(?i)(?:pylint|pyright|noqa|nosec|region|endregion|type:\s*ignore|fmt:\s*(on|off)|isort:\s*(on|off|skip|skip_file|split|dont-add-imports(:\s*\[.*?])?)|mypy:|SPDX-License-Identifier:)"
+        r"^(?i)(?:pylint|pyright|noqa|nosec|region|endregion|type:\s*ignore|fmt:\s*(on|off)|isort:\s*(on|off|skip|skip_file|split|dont-add-imports(:\s*\[.*?])?)|mypy:|SPDX-License-Identifier:|(?i)TODO(\([^\)]*\)| @\w+)?:)",
```
Comment (charliermarsh) [inline crates/ruff/src/rules/eradicate/detection.rs:9]: Can we find a way to do this generically, for all `task_tags`? Since this wouldn't extend to `FIXME`, etc. I'm wondering if we can instead split on parentheses on line 53, where we iterate over the task tags?

**Review by charliermarsh — CHANGES_REQUESTED** [review]
No rush, just bumping out of my queue :)

File: crates/ruff/src/rules/eradicate/detection.rs (hunk 1 above)
Comment (MichaReiser) [reply crates/ruff/src/rules/eradicate/detection.rs:9]: We should probably also make sure to respect https://docs.astral.sh/ruff/settings/#task-tags

It may also be possible to implement this without using a regex, but could be a bit of a pain.

Comment (charliermarsh) [reply crates/ruff/src/rules/eradicate/detection.rs:9]: We do respect task tags but it's not part of the regex, it's down on line 53.

**Comment by tjkuson** [comment]
Moved the tag checking logic to before the regex matching, as I believe it is less expensive. Also, now checks for lowercase tags (for example, `# todo(tom): Rewrite in Rust`).

**Review by charliermarsh — APPROVED** [review]
Thanks!

File: crates/ruff_linter/src/rules/eradicate/detection.rs [hunk 2]
```diff
@@ -39,6 +39,15 @@ pub(crate) fn comment_contains_code(line: &str, task_tags: &[String]) -> bool {
         return false;
     };
 
+    // Ignore task tag comments (e.g., "# TODO(tom): Refactor").
+    if line
+        .split(&[' ', ':', '('])
+        .next()
+        .is_some_and(|first| task_tags.iter().any(|tag| tag == first))
```
Comment (charliermarsh) [inline crates/ruff_linter/src/rules/eradicate/detection.rs:46]: I ended up removing the uppercase check here because it requires an allocation (would be expensive give how often this runs), and is probably rare.

Comment (tjkuson) [reply crates/ruff_linter/src/rules/eradicate/detection.rs:46]: Makes sense, thanks!
