### PR TITLE
fix(schema): restore limit on line-length

### LINKED ISSUE #7877: Restore minimum and maximum line-length enforcement in JSON schema
According to the struct, the `line-length` property only supports values in (0, 320). We tried to enforce this range in the JSON schema, but ran into issues with validation and had to revert. See: https://github.com/astral-sh/ruff/pull/7875.

As an aside, the 320 limit _also_ isn't enforced statically. I'm not sure where it came from, but (e.g.) Serde will allow you to instantiate a LineLength with a larger limit from your config.

### PR DESCRIPTION
**Pull request by henryiii**
## Summary

Restores functionality of #7875 but in the correct place. Closes #7877.

~~I couldn't figure out how to get cargo fmt to work, so hopefully that's run in CI.~~ Nevermind, figured it out.

## Test Plan

Can see output of json.

### CODE REVIEW

File: crates/ruff_linter/src/line_width.rs [hunk 1]
```diff
@@ -15,7 +15,10 @@ use ruff_text_size::TextSize;
 /// The allowed range of values is 1..=320
 #[derive(Clone, Copy, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
 #[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
-pub struct LineLength(NonZeroU16);
+pub struct LineLength(
+#[cfg_attr(feature = "schemars", schemars(range(min = 1, max = 320)))]
+    NonZeroU16
```
Comment (henryiii) [inline crates/ruff_linter/src/line_width.rs:20]:
```suggestion
#[cfg_attr(feature = "schemars", schemars(range(min = 1, max = 320)))] NonZeroU16
```

**Comment by charliermarsh** [comment]
Ah excellent! Thank you @henryiii!

**Comment by zanieb** [comment]
Thanks!!
