### PR TITLE
Check required-version before parsing rules

### LINKED ISSUE #19922: Validate required_version in config
If you have both a `required-version` and a new rule enabled in your ruff config, but try to run with an older version of ruff, you get something like:
```
ruff failed
  Cause: Failed to parse /.../pyproject.toml
  Cause: TOML parse error at line 23, column 5
   |
23 |     "RUF102",
   |     ^^^^^^^^
Unknown rule selector: `RUF102`
```

It would be better if you got e.g.:
```
ruff failed
  Cause: Required version `>=0.12.8` does not match the running version `0.9.10`
```

### PR DESCRIPTION
**Pull request by jelle-openai**
## Summary

Fixes #19922.

The approach I used is to check the required-version separately before parsing the TOML. This feels a bit ugly because we have to parse the TOML separately, but other approaches I considered seemed worse:

- Put the version validation inside SerDe deserialization for RequiredVersion. But this feels wrong: a required version that doesn't match the current version should still parse. Also, I think this means the user might see more errors than just the one for the version mismatch, when ideally they should only see the version mismatch error.
- Rewrite Options to be much more lenient in parsing everything else (in particular, don't validate rule names). However, this would be a bigger rewrite, and might still cause issues similar to #19922 if e.g. a new field is added.

## Test Plan

New test cases added.

### CODE REVIEW

File: crates/ruff_workspace/src/pyproject.rs [hunk 1]
```diff
@@ -45,6 +45,7 @@ fn parse_ruff_toml<P: AsRef<Path>>(path: P) -> Result<Options> {
     let path = path.as_ref();
     let contents = std::fs::read_to_string(path)
         .with_context(|| format!("Failed to read {}", path.display()))?;
+    check_required_version(&contents, path, &[])?;
```
Comment (MichaReiser) [inline crates/ruff_workspace/src/pyproject.rs]: I think we can avoid the double parsing by doing something like this:

```rust
    let value: toml::Value =
        toml::from_str(&contents).with_context(|| format!("Failed to parse {}", path.display()))?;

    check_required_version(&value, path, &["tool", "ruff"])?;

    value
        .try_into()
        .with_context(|| format!("Failed to parse {}", path.display()))
```

**Comment by MichaReiser** [comment]
Nice

**Comment by MichaReiser** [comment]
Hmm, the ecosystem changes are a bit surprising. Can you try rebasing on main?

**Comment by jelle-openai** [comment]
Hm do those changes mean it found more autofixes? That would be weird.

I'll apply your suggested change and merge in with latest main.

File: crates/ruff_workspace/src/pyproject.rs (hunk 1 above)
Comment (jelle-openai) [reply crates/ruff_workspace/src/pyproject.rs]: That version caused a regression where we no longer showed exact error locations for errors in the TOML. Codex came up with an approach that avoids the double parse while preserving exact error locations.

File: crates/ruff_workspace/src/pyproject.rs [hunk 2]
```diff
@@ -98,6 +117,40 @@ pub fn find_settings_toml<P: AsRef<Path>>(path: P) -> Result<Option<PathBuf>> {
...
+        };
+        let toml::de::DeValue::Table(next) = next.get_ref() else {
+            return Ok(());
+        };
+        current = next;
+    }
+
+    let required_version = current
+        .get("required-version")
+        .or_else(|| current.get("required_version"))
```
Comment (MichaReiser) [inline crates/ruff_workspace/src/pyproject.rs]: What's the reason that we need to check for `required_version` in addition to `required-version`? Can we add a test demonstrating this behavior (assuming it is needed?)

File: crates/ruff_workspace/src/pyproject.rs [hunk 3]
```diff
@@ -40,20 +41,38 @@ impl Pyproject {
...
+        .with_context(|| format!("Failed to parse {}", path.display()))?;
+
+    check_required_version(root.get_ref(), path, table_path)?;
+
+    let deserializer = toml::de::Deserializer::from(root);
+    T::deserialize(deserializer)
+        .map_err(|mut err| {
+            // `Deserializer::from` doesn't have access to the original input, but we do.
+            // Attach it so TOML errors include line/column and a source excerpt.
+            err.set_input(Some(&contents));
```
Comment (MichaReiser) [inline crates/ruff_workspace/src/pyproject.rs:62]: Nice find!

File: crates/ruff_workspace/src/pyproject.rs [hunk 4]
```diff
@@ -98,6 +117,40 @@ pub fn find_settings_toml<P: AsRef<Path>>(path: P) -> Result<Option<PathBuf>> {
...
+            toml::de::DeValue::String(value) => Some(value.as_ref()),
+            _ => None,
+        });
+
+    let Some(required_version) = required_version else {
+        return Ok(());
+    };
+
+    let required_version = RequiredVersion::try_from(required_version.to_string())
+        .with_context(|| format!("Failed to parse {}", path.display()))?;
```
Comment (MichaReiser) [inline crates/ruff_workspace/src/pyproject.rs]: I suspect that we lose the span in the error message compared to when deserializing the value as part of the serde deserialization. I'm inclined to return `Ok` here and defer to the "full" deserialization in that case.

File: crates/ruff_workspace/src/pyproject.rs (hunk 3 above)
Comment (jelle-openai) [reply crates/ruff_workspace/src/pyproject.rs:62]: Codex found it :D

File: crates/ruff_workspace/src/pyproject.rs (hunk 2 above)
Comment (jelle-openai) [reply crates/ruff_workspace/src/pyproject.rs]: Yeah this was the AI's code and I should have validated it's needed. It looks like Ruff only supports the dash version, so we shouldn't look at the underscored one.

File: crates/ruff_workspace/src/pyproject.rs (hunk 4 above)
Comment (jelle-openai) [reply crates/ruff_workspace/src/pyproject.rs]: I'll add a test for this case too.

Comment (jelle-openai) [reply crates/ruff_workspace/src/pyproject.rs]: You were right, changed it as you suggested.

File: crates/ruff_workspace/src/pyproject.rs (hunk 2 above)
Comment (jelle-openai) [reply crates/ruff_workspace/src/pyproject.rs]: Removed the underscore fallback

**Comment by jelle-openai** [comment]
Thanks for the review and merge @MichaReiser!
