### PR TITLE
[`flake8-pytest-style`] Allow `match` and `check` keyword arguments without an expected exception type (`PT010`)

### LINKED ISSUE #18653: PT010 should be updated for pytest 8.4.0
### Summary

The documentation for [`pytest-raises-without-exception` (PT010)](https://docs.astral.sh/ruff/rules/pytest-raises-without-exception/) says:
> `pytest.raises` expects to receive an expected exception as its first argument. If omitted, the `pytest.raises` call will fail at runtime.

As of pytest 8.4.0 (released June 2, 2025) it is also sufficient to pass the keyword argument `match` or `check`. The rule should recognize those arguments too.

```console
$ cat >pt010.py <<'# EOF'
import pytest
with pytest.raises(match=r"!+"):
    raise RuntimeError("!!!")
with pytest.raises(check=lambda _e: True):
    raise RuntimeError("...")
# EOF

$ python pt010.py; echo $?
0

$ ruff --isolated check pt010.py --select PT010 --output-format concise -q
pt010.py:2:6: PT010 Set the expected exception in `pytest.raises()`
pt010.py:4:6: PT010 Set the expected exception in `pytest.raises()`
```

### Version

ruff 0.11.13 (5faf72a4d 2025-06-05)

### PR DESCRIPTION
**Pull request by mahiro72**
## Summary

Updates PT010(`pytest-raises-without-exception`) to recognize `match` and `check` keyword arguments as valid alternatives to specifying an exception class.

As of pytest 8.4.0, `pytest.raises()` can be called with only `match` or `check` keyword arguments without an expected exception.

Fixes #18653

## Test Plan

- Added test cases for `match`-only, `check`-only, and both arguments.
- `cargo test -p ruff_linter -- "pytestraiseswithoutexception"` passes

### CODE REVIEW

File: crates/ruff_linter/src/rules/flake8_pytest_style/rules/raises.rs [hunk 1]
```diff
@@ -126,6 +126,9 @@ impl Violation for PytestRaisesTooBroad {
 /// `pytest.raises` expects to receive an expected exception as its first
 /// argument. If omitted, the `pytest.raises` call will fail at runtime.
 ///
+/// Note: As of pytest 8.4.0, calls with only `match` or `check` keyword
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/flake8_pytest_style/rules/raises.rs]: Let's try to unify this with the rest of the docs rather than a separate note. I think something like:

```
/// The rule will also accept calls without an expected exception but with
/// `match` and/or `check` keyword arguments, which are also valid after
/// pytest version 8.4.0.
```

appended to the preceding paragraph would flow well enough.

It might also be nice to add an example to the `Use instead` section of one of these. But maybe it's okay as-is. Three examples feels like too much to me for sure, so maybe it's better to stay with one.

Comment (mahiro0x00) [reply crates/ruff_linter/src/rules/flake8_pytest_style/rules/raises.rs]: Thanks for the review! I've updated the docs to integrate the note into the preceding paragraph as you suggested.

Regarding the example in the `Use instead` section - I agree that three examples would be too many, so I'll leave it as-is for now.

[docs: unify note format in PT010 documentation](https://github.com/astral-sh/ruff/pull/21964/commits/b28c54dab671b8c75c52bdd5e03ea35d1b0a9bb5)
