### PR TITLE
[`ruff`] skip fix for `RUF059` if dummy name is already bound (unused-unpacked-variable)

### LINKED ISSUE #18507: RUF059 fix renames variables without checking existing variable names
### Summary

The fix for [`unused-unpacked-variable` (RUF059)](https://docs.astral.sh/ruff/rules/unused-unpacked-variable/) can rename a variable to shadow or rebind an existing variable.

```console
$ cat >ruf059.py <<'# EOF'
def f(_x):
    x, = "1"
    print(_x)
f("0")
# EOF

$ python ruf059.py
0

$ ruff --isolated check ruf059.py --select RUF059 --preview --unsafe-fixes --fix
Found 1 error (1 fixed, 0 remaining).

$ cat ruf059.py
def f(_x):
    _x, = "1"
    print(_x)
f("0")

$ python ruf059.py
1
```

### Version

ruff 0.11.13 (5faf72a4d 2025-06-05)

### PR DESCRIPTION
**Pull request by chirizxc**
## Summary
/closes #18507

### CODE REVIEW

File: crates/ruff_linter/src/rules/ruff/rules/unused_unpacked_variable.rs [hunk 1]
```diff
@@ -63,6 +63,16 @@ fn remove_unused_variable(binding: &Binding, checker: &Checker) -> Option<Fix> {
...
     let renamed = format!("_{name}");
+
+    let scope = checker.semantic().scopes.get(binding.scope)?;
+
+    if scope
+        .bindings()
+        .any(|(_, id)| checker.semantic().binding(id).name(checker.source()) == renamed)
+    {
+        return None;
+    }
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/unused_unpacked_variable.rs]: I think we could use the following here (which is what we use in other places to test shadowing)

https://github.com/astral-sh/ruff/blob/9925910a29643ff1f29eafeadc2b1d26812e4993/crates/ruff_linter/src/rules/pyupgrade/rules/pep695/private_type_parameter.rs#L137-L139

**Comment by MichaReiser** [comment]
Thank you
