### PR TITLE
Fix false positive in `PLR6301`

### LINKED ISSUE #6961: `no-self-use` (`PLR6301`) false positive on methods that call `super`
```py
from typing_extensions import override


class A:
    def foo(self):
        ...


class B(A):
    @override
    def foo(self):
        ...

    def bar(self):  # error: PLR6301
        super().foo()
```

in this case the method cannot be converted to a static method, otherwise it would break the `super` call

### PR DESCRIPTION
**Pull request by LaBatata101**
## Summary

Don't report a diagnostic if the method contains a `super()` call.

Closes #6961

## Test Plan

`cargo test`

### CODE REVIEW

File: crates/ruff_linter/src/rules/pylint/rules/no_self_use.rs [hunk 1]
```diff
@@ -119,3 +129,23 @@ pub(crate) fn no_self_use(checker: &Checker, scope: &Scope, diagnostics: &mut Ve
...
+                    self.is_super = expr_name.id == "super";
+                }
+                _ => {
+                    visitor::walk_expr(self, expr);
+                }
+            },
+            _ => visitor::walk_expr(self, expr),
+        }
+    }
+}
```
Comment (LaBatata101) [inline crates/ruff_linter/src/rules/pylint/rules/no_self_use.rs:151]: Ideally, it would be better to use the function scope to check if the method contains a `super()` call in the body, but the function scope only gives me access to its parameters. So when using `scope.get("super")` it would only return `None`.

Comment (charliermarsh) [reply crates/ruff_linter/src/rules/pylint/rules/no_self_use.rs]: It turns out that `super` is actually a global builtin in Python, so the usages we need are on the _global_ scope. I tweaked the logic to use the technique you suggested above. I guess the downside is that we can't ensure that the `super` usage was on a `super()` call, but perhaps that's fine. (We don't store a `NodeId` on `Reference`, though we could in the future.)

File: crates/ruff_linter/src/rules/pylint/rules/no_self_use.rs [hunk 2]
```diff
@@ -105,11 +110,28 @@ pub(crate) fn no_self_use(checker: &Checker, scope: &Scope, diagnostics: &mut Ve
...
+        let binding = checker.semantic().binding(binding_id);
+        if binding.kind.is_builtin() {
+            if binding
+                .references()
+                .any(|id| checker.semantic().reference(id).scope_id() == scope_id)
+            {
+                return;
+            }
+        }
+    }
```
Comment (charliermarsh) [inline crates/ruff_linter/src/rules/pylint/rules/no_self_use.rs:129]: @LaBatata101 - What do you think of this?

Comment (LaBatata101) [reply crates/ruff_linter/src/rules/pylint/rules/no_self_use.rs:129]: LGTM. Didn't know about the `binding.references()` function, will be very helpful when implementing other rules in the future.
