### PR TITLE
[ty] Support `dataclass_transform` as a function call

### LINKED ISSUE #2319: [BUG] Incorrect type inference with `dataclass_transform` and generics / decorators
### Summary

When using `@dataclass_transform()` in combination with generics and overloads, `ty` appears to infer the wrong type for the result of the dataclass-like decorator. This differs from the behavior of the standard `dataclasses.dataclass` function:

#### Example / Minimal Repro:
```python
import dataclasses
from collections.abc import Callable
from typing import dataclass_transform, overload, reveal_type

@dataclass_transform()
@overload
def func[T: type](cls: T) -> T: ...
@dataclass_transform()
@overload
def func[T: type]() -> Callable[[T], T]: ...
def func[T: type](cls: T | None = None) -> T | Callable[[T], T]:
    raise NotImplementedError

class A: ...

B = dataclasses.dataclass(A)
reveal_type(B)  # `<class 'A'>` as expected

C = func(A)
# actual: `<decorator produced by dataclass-like function>`
# expected: `<class 'A'>`
reveal_type(C)
```

#### Expected Behavior

The result of `func(A)` should be inferred as `<class 'A'>`, matching the behavior of the standard `dataclasses.dataclass` application.

#### Actual Behavior

'ty' reports `<decorator produced by dataclass-like function>` instead of `<class 'A'>` for `reveal_type(C)`.

#### Environment

- ty command: ty check main.py
- playground link: <https://play.ty.dev/9cb27674-5bb8-4cb5-abe4-f49ec8cd2fb2>

---

Let me know if further details or logs are needed!

### Version

ty 0.0.8 (aa7559db8 2025-12-29)

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Instead of just as a decorator.

Closes https://github.com/astral-sh/ty/issues/2319.

### CODE REVIEW

**Comment by charliermarsh** [comment]
(The `hydra-zen` diagnostic needs work.)

File: crates/ty_python_semantic/src/types/call/bind.rs [hunk 1]
```diff
@@ -1178,44 +1178,90 @@ impl<'db> Bindings<'db> {
...
-                                overload.set_return_type(return_type);
+                                let dataclass_params = DataclassParams::new(
+                                    db,
+                                    flags,
+                                    dataclass_params.field_specifiers(db),
+                                );
+
+                                // If the return type is class-like and the first argument is a
+                                // class, return it with dataclass params applied. Otherwise,
+                                // return a `DataclassDecorator` for application to a class later.
```
Comment (charliermarsh) [inline crates/ty_python_semantic/src/types/call/bind.rs]: I think this is wrong. It's intended to address cases like:
```python
@dataclass_transform()
def hydrated_dataclass(target: type, *, frozen: bool = False) -> Callable[[type[T]], type[T]]:
    def decorator(cls: type[T]) -> type[T]:
        return cls
    return decorator

@hydrated_dataclass(SomeConfig, frozen=True)
class MyConfig:
    pass
```

If we make this change _without_ this declared return type handling, then `hydrated_dataclass(SomeConfig, frozen=True)` returns `type[SomeConfig]` with dataclass params, and we apply _that_ as a decorator.

File: crates/ty_python_semantic/resources/mdtest/dataclasses/dataclass_transform.md [hunk 2]
```diff
@@ -1032,4 +1032,125 @@ reveal_type(asdict(p))  # revealed: dict[str, Any]
...
+
+class A[T]:
+    x: T
+
+B = my_dataclass(A[int])
+
+reveal_type(B)  # revealed: <class 'A[int]'>
+
+B(1)
+```
```
Comment (carljm) [inline crates/ty_python_semantic/resources/mdtest/dataclasses/dataclass_transform.md:1124]: I'm impressed that you support this, but I'm curious where it came up? Did you see this in the ecosystem?

This won't work at runtime with stdlib dataclass -- it expects to get a class object, not a `typing.GenericAlias`. But I suppose there could be third-party dataclass-transforms that are built to handle `GenericAlias` at runtime?

File: crates/ty_python_semantic/resources/mdtest/dataclasses/dataclass_transform.md [hunk 3]
```diff
@@ -1032,4 +1032,125 @@ reveal_type(asdict(p))  # revealed: dict[str, Any]
...
+@dataclass_transform()
+def hydrated_dataclass[T](target: type[T], *, frozen: bool = False):
+    def decorator[U](cls: type[U]) -> type[U]:
+        return cls
+    return decorator
+
+class Target:
+    pass
+
+decorator = hydrated_dataclass(Target)
```
Comment (carljm) [inline crates/ty_python_semantic/resources/mdtest/dataclasses/dataclass_transform.md:1144]: What about then using this like `MyClass = decorator(SomeClass)`?

Doesn't seem to work, even on this branch:

```py
class M1:
    x: int

M2 = decorator(M1)

reveal_type(M2)  # reveals `type[M1] & Any`
```

And I'm not sure where the `& Any` comes from?

(As noted above, I don't think any other type checker supports this non-decorator use of a dataclass transform at all, so I don't know that we need to support this edge case, just curious why it doesn't work when the base case above does.)

File: crates/ty_python_semantic/resources/mdtest/dataclasses/dataclass_transform.md [hunk 4]
```diff
@@ -1032,4 +1032,125 @@ reveal_type(asdict(p))  # revealed: dict[str, Any]
...
+    return cls
+
+class A:
+    x: int
+
+B = my_dataclass(A)
+
+reveal_type(B)  # revealed: <class 'A'>
+
+B(1)
```
Comment (carljm) [inline crates/ty_python_semantic/resources/mdtest/dataclasses/dataclass_transform.md:1056]: Doesn't seem like any other type checkers support this, but it's cool that we can.

File: crates/ty_python_semantic/src/types/function.rs [hunk 5]
```diff
@@ -747,9 +747,9 @@ impl<'db> FunctionLiteral<'db> {
     fn iter_overloads_and_implementation(
         self,
         db: &'db dyn Db,
-    ) -> impl Iterator<Item = OverloadLiteral<'db>> + 'db {
-        let (implementation, overloads) = self.overloads_and_implementation(db);
-        overloads.into_iter().chain(implementation.iter().copied())
+    ) -> impl DoubleEndedIterator<Item = OverloadLiteral<'db>> + 'db {
+        let (overloads, implementation) = self.overloads_and_implementation(db);
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/function.rs:752]: lol, oops

I guess no other caller cared about the ordering here?

Looking at the usage in `infer_class_definition`, I think we might need a `.rev()` call there also, to make the behavior match the comment?

File: crates/ty_python_semantic/src/types/call/bind.rs (hunk 1 above)
Comment (carljm) [reply crates/ty_python_semantic/src/types/call/bind.rs]: This is an unfortunate ambiguity baked directly into the `dataclass_transform` spec. It doesn't clarify how we are supposed to tell whether the `@dataclass_transform` decorated function is a decorator or a decorator factory (yet it clearly specifies that both should be supported). I think the spec's assumption is that it doesn't matter, because only decorator-syntax usage (with `@`) is supported, and in that case you can tell how it is used (are there parentheses or not). But we are trying to do something more sophisticated here, and I think it means we have to resort to some kind of heuristic.

But I'm not sure the heuristic should depend on the annotated return type like this; there's no real requirement to annotate your dataclass_transform decorator at all. I think a better heuristic might be based solely on the number, kind, and type of arguments. If only one positional argument is given and it's a class type, assume we should decorate that class. Otherwise, assume we are returning the real decorator.

**Review by carljm — APPROVED** [review]
This looks pretty good! We are definitely being more ambitious than other type checkers here (and more ambitious than the spec requires), by supporting non-decorator-syntax usages of `dataclass_transform` at all. Our initial implementation of `dataclass_transform` kind of set us on this path, by implementing the logic generally in function-call-binding and having a "DataclassTransformer" type, rather than doing everything as a special case in decorator application. And this PR seems pretty good, so I don't see much harm in continuing on this path -- it's cool if we can support non-decorator-syntax usage like this.

A few comments inline.

File: crates/ty_python_semantic/src/types/call/bind.rs [hunk 6]
```diff
@@ -1185,44 +1185,92 @@ impl<'db> Bindings<'db> {
...
+                                                db,
+                                                class_literal.name(db),
+                                                class_literal.body_scope(db),
+                                                class_literal.known(db),
+                                                class_literal.deprecated(db),
+                                                class_literal.type_check_only(db),
+                                                Some(dataclass_params),
+                                                class_literal.dataclass_transformer_params(db),
+                                                class_literal.total_ordering(db),
+                                            );
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/call/bind.rs]: Worth adding a `ClassLiteral::with_dataclass_params` to DRY this up a bit? We're mentioning a lot of extraneous field names here.

File: crates/ty_python_semantic/resources/mdtest/dataclasses/dataclass_transform.md (hunk 2 above)
Comment (charliermarsh) [reply crates/ty_python_semantic/resources/mdtest/dataclasses/dataclass_transform.md:1124]: I honestly can't remember -- I may have asked Claude to add something to verify that we preserve specialization after seeing handling for it in the code?!

File: crates/ty_python_semantic/src/types/call/bind.rs (hunk 1 above)
Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/call/bind.rs]: (Okay this is very comforting to hear, haha.)

Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/call/bind.rs]: I think that wouldn't work for this case, since both functions take a single class as its positional arguments:
```python
from typing_extensions import dataclass_transform

@dataclass_transform()
def hydrated_dataclass[T](target: type[T], *, frozen: bool = False):
    def decorator[U](cls: type[U]) -> type[U]:
        return cls
    return decorator
```

For now, I combined the two heuristics.
