### PR TITLE
[red-knot] Use memory address as AST node key

### LINKED ISSUE #14313: [red-knot] Double-store assertions when encountering invalid syntax
During type inference on some invalid syntax examples, we encounter situations where the exact same expression appears in multiple places inside the AST. The smallest example I could find is this:
```py
for
```
When parsing it, we get the following AST. Note that the same `Name(…)` expression (same range) appears both as `target` and as `iter` field on `StmtFor`, once with `Store` context, once with `Invalid` context:
```
Module(
    ModModule {
        range: 0..3,
        body: [
            For(
                StmtFor {
                    range: 0..3,
                    is_async: false,
                    target: Name(
                        ExprName {
                            range: 3..3,
                            id: Name(""),
                            ctx: Store,
                        },
                    ),
                    iter: Name(
                        ExprName {
                            range: 3..3,
                            id: Name(""),
                            ctx: Invalid,
                        },
                    ),
                    body: [],
                    orelse: [],
                },
            ),
        ],
    },
)
```

This leads to a subsequent failing double-store assertion in `store_expression_type` because we infer types for both the `target` and the `iter` expressions:

https://github.com/astral-sh/ruff/blob/f789b12705048a4f75cddeceb843fd4afbe783f1/crates/red_knot_python_semantic/src/types/infer.rs#L2176-L2184

I'm not sure how to fix this.

Skipping storage when encountering expressions with `Invalid` context would work for this example, but there are other cases (`:x=`) where such an invalid expression is not "backed up" by a second valid expression.

Ignoring double-storage for `Invalid` expressions is also not an option, since in this example here, we run inference on `iter` first.

### PR DESCRIPTION
**Pull request by sharkdp**
## Summary

Use the memory address to uniquely identify AST nodes, instead of relying on source range and kind. The latter fails for ASTs resulting from invalid syntax examples. See #14313 for details.

Also results in a 1-2% speedup (https://codspeed.io/astral-sh/ruff/runs/67349cf55f36b36baa211360)

closes #14313 

## Review

Here are the places where we use `NodeKey` directly or indirectly (via `ExpressionNodeKey` or `DefinitionNodeKey`):

```rs
// semantic_index.rs
pub(crate) struct SemanticIndex<'db> { 
    // [...]
    /// Map expressions to their corresponding scope.
    scopes_by_expression: FxHashMap<ExpressionNodeKey, FileScopeId>,

    /// Map from a node creating a definition to its definition.
    definitions_by_node: FxHashMap<DefinitionNodeKey, Definition<'db>>,

    /// Map from a standalone expression to its [`Expression`] ingredient.
    expressions_by_node: FxHashMap<ExpressionNodeKey, Expression<'db>>,
    // [...]
}

// semantic_index/builder.rs
pub(super) struct SemanticIndexBuilder<'db> {
    // [...]
    scopes_by_expression: FxHashMap<ExpressionNodeKey, FileScopeId>,
    definitions_by_node: FxHashMap<ExpressionNodeKey, Definition<'db>>,
    expressions_by_node: FxHashMap<ExpressionNodeKey, Expression<'db>>,
}

// semantic_index/ast_ids.rs
pub(crate) struct AstIds {
    /// Maps expressions to their expression id.
    expressions_map: FxHashMap<ExpressionNodeKey, ScopedExpressionId>,
    /// Maps expressions which "use" a symbol (that is, [`ast::ExprName`]) to a use id.
    uses_map: FxHashMap<ExpressionNodeKey, ScopedUseId>,
}

pub(super) struct AstIdsBuilder {
    expressions_map: FxHashMap<ExpressionNodeKey, ScopedExpressionId>,
    uses_map: FxHashMap<ExpressionNodeKey, ScopedUseId>,
}
```

## Test Plan

Added two failing examples to the corpus.

### CODE REVIEW

File: crates/red_knot_python_semantic/src/node_key.rs [hunk 1]
```diff
@@ -1,24 +1,18 @@
...
 ///
-/// Compares two nodes by their kind and text range.
+/// Stores the memory address of the node, because using the range and node kind
+/// is not enough to uniquely identify them in ASTs resulting from invalid syntax.
 #[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
-pub(super) struct NodeKey {
-    kind: NodeKind,
-    range: TextRange,
-}
+pub(super) struct NodeKey(usize);
```
Comment (sharkdp) [inline crates/red_knot_python_semantic/src/node_key.rs:8]: Thought about renaming it to `NodeAddress`, but that lead to too many downstream renamings and a large diff. Let me know if someone is unhappy with keeping `NodeKey`.

File: crates/red_knot_python_semantic/src/node_key.rs [hunk 2]
```diff
@@ -1,24 +1,18 @@
-use ruff_python_ast::{AnyNodeRef, NodeKind};
-use ruff_text_size::{Ranged, TextRange};
+use ruff_python_ast::AnyNodeRef;
 
 /// Compact key for a node for use in a hash map.
 ///
-/// Compares two nodes by their kind and text range.
+/// Stores the memory address of the node, because using the range and node kind
+/// is not enough to uniquely identify them in ASTs resulting from invalid syntax.
```
Comment (MichaReiser) [inline crates/red_knot_python_semantic/src/node_key.rs:6]: It would be great to add an example here

**Review by MichaReiser — APPROVED** [review]
