### PR TITLE
[`pycodestyle`] Fix `E731` autofix creating a syntax error for expressions spanned across multiple lines

### LINKED ISSUE #18475: [Fix error] unsafe-fixes introduces a syntax error
When running `ruff check --fix --unsafe-fixes` (no extra settings or config) on the following code snippet:

``` python
foo_tooltip = (
    lambda x, data: f"\nfoo: {data['foo'][int(x)]}"
    if data["foo"] is not None
    else ""
)

```

Ruff introduces a syntax error and reverts the fix.
The rule code to fix is E731: 
```
test.py:1:1: E731 Do not assign a `lambda` expression, use a `def`
```

### PR DESCRIPTION
**Pull request by LaBatata101**
## Summary

Fixes #18475

## Test Plan

Add regression test

### CODE REVIEW

File: crates/ruff_linter/src/rules/pycodestyle/rules/lambda_assignment.rs [hunk 1]
```diff
@@ -267,14 +267,21 @@ fn replace_trailing_ellipsis_with_original_expr(
     )
     .unwrap_or(lambda.body.range());
 
-    let original_expr_in_source = checker.locator().slice(original_expr_range);
+    // This prevents the autofix of introducing a syntax error if the lambda's body is an `if`
+    // expression spanning across multiple lines. To avoid the syntax error we wrap the expression
+    // in parenthesis.
+    let original_expr_in_source = if matches!(lambda.body.as_ref(), Expr::If(_)) {
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pycodestyle/rules/lambda_assignment.rs]: I don't think this is specific to if expressions. For example, the input could be


```py
foo_tooltip = (
    lambda x, data: f"\nfoo: {data['foo'][int(x)]}" + 
    more

)
```

I think what we should do instead is to test if the expression is parenthesized (see `is_expression_parenthesized`) and if so, preserve the parentheses around the body.

Comment (LaBatata101) [reply crates/ruff_linter/src/rules/pycodestyle/rules/lambda_assignment.rs]: I think `is_expression_parenthesized` could be moved to `ruff_python_trivia`, so that others could make use of it outside the formatter code.

File: crates/ruff_linter/src/rules/pycodestyle/rules/lambda_assignment.rs [hunk 2]
```diff
@@ -267,14 +270,50 @@ fn replace_trailing_ellipsis_with_original_expr(
...
+                .next(),
+            Some(SimpleToken {
+                kind: SimpleTokenKind::LParen,
+                ..
+            })
+        )
+    } else {
+        false
+    }
+}
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pycodestyle/rules/lambda_assignment.rs]: Oh no, I pointed you to the wrong version it seems. There's one that can be reused. See `parenthesized_range`

Comment (LaBatata101) [reply crates/ruff_linter/src/rules/pycodestyle/rules/lambda_assignment.rs]: fixed
