### PR TITLE
[`perflint`] fix invalid hoist in `perf401`

### LINKED ISSUE #14362: PERF401 new preview fixes invalidly hoists extend to list compre
I tried running the new autofixes on the PyTorch codebase and was mostly impressed, but found one really annoying (and handable edge case).

Here is an example bad fix
```diff
     @dist_init
     def test_wait_all_with_exception(self):
-        futs = []
+        futs = [rpc.rpc_async(dst, raise_func) for _ in range(10)]
         dst = worker_name((self.rank + 1) % self.world_size)
-        for _ in range(10):
-            futs.append(rpc.rpc_async(dst, raise_func))

         with self.assertRaisesRegex(ValueError, "Expected error"):
             torch.futures.wait_all(futs)
```
Here is an example diff generated by ruff. Note that list comprehensions uses `dst` even though dst is first defined on the line underneath the list comprehension. Ruff can already detect this because it immeaditely created a bunch of ruff F821 errors as soon as the fixes were applied. It would be good not to hoist the forloop from an extend to a list comprehensions if there are any variables needed for the list comprehension defined or mutated in anyway. I was kind of surprised given that it did properly not hoist the function if there were any comments in between the list definition and the loop.

```ruff 0.7.4```
```ruff check --select=PERF401 --fix --unsafe-fixes --preview```

FYI @w0nder1ng

### PR DESCRIPTION
**Pull request by w0nder1ng**
This should fix #14362. This new fix currently deletes lines like this:
```python
- tmp = 1; result = []
- for i in range(10):
-   result.append(i+1)
+ result = [i+1 for i in range(10)]
```
Is there a convenient way to get every statement within a given `TextRange` to detect when this is happening?

### CODE REVIEW

**Comment by Skylion007** [comment]
@w0nder1ng Another fun edge case that PR #14369 doesn't currently fix. Scoping rules are different between list comprehensions and for loops:

another example from pytorch
```diff
     if kwargs is None:
         kwargs = {}
-    impl_args = []
-    for a in args:
-        impl_args.append(_helper(a, map_fn))
+    impl_args = [_helper(a, map_fn) for a in args]
     impl_kwargs = {}
     for k in kwargs.keys():
         impl_kwargs[k] = _helper(a, map_fn)
```
the `a` on the line `impl_kwargs[k] = _helper(a, map_fn)` is now undefined (and will error with F821) since the list comprehension was converted from a loop. RUFF immeaditely flags this with an F821 error, and I test and confirm the temporary variable `a` does not leave the listcomp scope, while it does leave the for loop one.

**Comment by Skylion007** [comment]
Also another really minor nit is that it can duplicate comments.
```
-        for dtype in ["f16", "bf16"]:
-            kernels.append(
-                cls(
-                    aligned=True,
-                    dtype=dtype,
-                    sm_range=(80, SM[SM.index(80) + 1]),
-                    apply_dropout=False,
-                    preload_mmas=True,
-                    block_i=128,
-                    block_j=64,
-                    max_k=96,
-                    # Sm80 has a faster kernel for this case
-                    dispatch_cond="cc == 86 || cc == 89",
-                )
+        # Sm80 has a faster kernel for this case
+        kernels.extend(
+            cls(
+                aligned=True,
+                dtype=dtype,
+                sm_range=(80, SM[SM.index(80) + 1]),
+                apply_dropout=False,
+                preload_mmas=True,
+                block_i=128,
+                block_j=64,
+                max_k=96,
+                # Sm80 has a faster kernel for this case
+                dispatch_cond="cc == 86 || cc == 89",
             )
+            for dtype in ["f16", "bf16"]
+        )
```
See here.

**Comment by w0nder1ng** [comment]
> Another fun edge case that PR https://github.com/astral-sh/ruff/pull/14369 doesn't currently fix

I think in this case, the lint shouldn't apply at all. If applying the fix breaks the code, then someone manually doing the same thing also wouldn't work. It should probably check that all references to the loop variable are inside the for loop before reporting the lint. 

I'll also try to fix the duplicate comments. I'm starting to see why this didn't have a fix before :)

**Comment by Skylion007** [comment]
It doesn't break in terms of invalid syntax, it just causes a downstream var to be undefined unfortunately. :(

**Comment by w0nder1ng** [comment]
The comment duplication happened when the comment was inside the append body, it should be fixed now.

File: crates/ruff_linter/src/rules/perflint/rules/manual_list_comprehension.rs [hunk 1]
```diff
@@ -219,6 +218,34 @@ pub(crate) fn manual_list_comprehension(checker: &mut Checker, for_stmt: &ast::S
...
+    //
+    // If this were a comprehension, x would no longer have the correct scope:
+    //
+    // ```python
+    // filtered = [x for x in y]
+    // print(x)
+    // ```
+    let for_loop_target = checker
+        .semantic()
+        .lookup_symbol(id.as_str())
```
Comment (w0nder1ng) [inline crates/ruff_linter/src/rules/perflint/rules/manual_list_comprehension.rs:237]: For some reason, `resolve_name` returns `None` for the for-loop target. Also, references to it outside of the for-loop are not included in its list of references; e.g.
```python
def f():
    result = []
    for val in range(5):
        result.append(val * 2)
    print(val) # this reference is not included in the list of references
```

Comment (MichaReiser) [reply crates/ruff_linter/src/rules/perflint/rules/manual_list_comprehension.rs:237]: I think the problem here is that we build the semantic model lazily and it hasn't reached the point after the for loop yet

**Comment by MichaReiser** [comment]
Could you take a look why https://github.com/apache/superset/blob/e528cb48c44543c14c1ac9a93528b147bcaecfde/scripts/benchmark_migration.py#L128 is no longer reported. I might have missed something obvious but it isn't clear to me why the diagnostic isn't reported anymore.

File: crates/ruff_linter/src/rules/perflint/rules/manual_list_comprehension.rs (hunk 1 above)
Comment (MichaReiser) [reply crates/ruff_linter/src/rules/perflint/rules/manual_list_comprehension.rs:237]: @charliermarsh any suggestions on how to best find all usages of target?

**Comment by w0nder1ng** [comment]
I suspect the regressions are because of the `resolve_name` being a `lookup_symbol`. In the example you gave, I think it's finding a different `foreign_key` binding on line 113 and concluding that the symbol is used outside of the for loop. Once the binding has the right scope, the only regressions should be ones where the lint shouldn't have applied.

**Comment by Skylion007** [comment]
> Could you take a look why https://github.com/apache/superset/blob/e528cb48c44543c14c1ac9a93528b147bcaecfde/scripts/benchmark_migration.py#L128 is no longer reported. I might have missed something obvious but it isn't clear to me why the diagnostic isn't reported anymore.

Because the lambda arg here https://github.com/apache/superset/blob/e528cb48c44543c14c1ac9a93528b147bcaecfde/scripts/benchmark_migration.py#L131C28-L131C33 is shadowing the variable "model" in the for loop. In this specific case, it's probably okay since it's in a lambda arg, but in general it shouldn't apply the fix there. I suppose only references rvalues are problematic outside of the forloop, not lvalues (if all they do is immediately get overwritten after all).

**Comment by Skylion007** [comment]
Okay hopefully last nit:
```diff
     reduction_axes: List[int] = []
-    for i in range(input_rank):
-        if i != axis:
-            reduction_axes.append(i)
+    reduction_axes.extend(i for i in range(input_rank) if i != axis)
```
Doesn't seem to like to hoist if there are any type_hints on the original `[]` instantiation.  Is this intentional?

**Comment by w0nder1ng** [comment]
I'll take a look

**Comment by w0nder1ng** [comment]
Annotated assigns have a different statement type than normal assigns, and I wasn't handling it. It should work now.

**Comment by Skylion007** [comment]
> @w0nder1ng Another fun edge case that PR #14369 doesn't currently fix. Scoping rules are different between list comprehensions and for loops:
> 
> another example from pytorch
> 
> ```diff
>      if kwargs is None:
>          kwargs = {}
> -    impl_args = []
> -    for a in args:
> -        impl_args.append(_helper(a, map_fn))
> +    impl_args = [_helper(a, map_fn) for a in args]
>      impl_kwargs = {}
>      for k in kwargs.keys():
>          impl_kwargs[k] = _helper(a, map_fn)
> ```
> 
> the `a` on the line `impl_kwargs[k] = _helper(a, map_fn)` is now undefined (and will error with F821) since the list comprehension was converted from a loop. RUFF immeaditely flags this with an F821 error, and I test and confirm the temporary variable `a` does not leave the listcomp scope, while it does leave the for loop one.
> 
> @w0nder1ng If you want a good test bed, just run the autofix on PyTorch (or another large codebase) and see after applying the fixes if any other ruff rule violations are immediately detected.

This one is still occurring sadly. Maybe because it references another loop lol?

**Comment by Skylion007** [comment]
Despite this minor false positive, looks like all the other fixes worked well on the PyTorch codebase. 👍

**Comment by w0nder1ng** [comment]
I'm still stuck on two things.

1. How can I determine whether the binding statement has another statement on the line? 
```python
result = []; test = [] # deleting this whole line is wrong, but only deleting the binding statement also is wrong
# since it would leave the comment if there were no other statement
for ...
```

2. How can I get the semantic model to find references after the for loop? 
```python
result = []
for i in range(10):
  result.append(i+1)
print(i) # "fixing" this for loop is invalid because something relies on the loop variable, but the semantic model doesn't see this reference yet
```

**Comment by Skylion007** [comment]
@diceroll123 Any idea how to tackle these edge cases?

**Comment by MichaReiser** [comment]
@Skylion007 no, not from the top of my head and I haven't had time yet to look into it more closely

**Comment by diceroll123** [comment]
I did not look into it any further after my last comment on #14551.

This PR and my PR contain a bunch of overlapping changes, and I don't want to step on any toes or spend more time on it if it's not going to be considered, so if one or the other is merged, or some kind of plan is made, we can go from there I suppose! No strong feelings on my part. 😄

**Comment by Skylion007** [comment]
One other place this autofix breaks (but ruff does appropriately catch it!). Apply it to `sympy/tensor/index_methods.py` in sympy. Fixing this loop breaks: https://github.com/sympy/sympy/blob/ba68537e73dd40fb34fa9c5aaf46c5a6e1ef12c7/sympy/tensor/index_methods.py#L427 . I suspect because it's using unusual python syntax to iterate over an implicit tuple.
```python
for d in dbase, dexp:
```
transforming that to a list comprehension likely breaks

I will say that even it's current form, this autofix is extremely useful, and the encountered edge cases are very rare in real code, and usually caught by other checks.

**Comment by Skylion007** [comment]
This unaccepted rule would likely have to tackle many of the same problems. Did they solve this edge case? https://github.com/astral-sh/ruff/pull/11769

File: crates/ruff_linter/src/rules/perflint/rules/manual_list_comprehension.rs (hunk 1 above)
Comment (w0nder1ng) [reply crates/ruff_linter/src/rules/perflint/rules/manual_list_comprehension.rs:237]: I think a working version would look something like this:

```rust
let for_loop_read = checker.semantic().resolve_load(for_loop_target_name_expr);
let for_loop_binding = match for_loop_read {
    ReadResult::Resolved(id) => checker.semantic().binding(id),
    _ => unreachable!("for loop target must exist"),
};
```

Unfortunately, `resolve_load` requires an `&mut SemanticModel` and I don't see a way to get one from the checker. Am I missing something here?

**Comment by w0nder1ng** [comment]
@Skylion007 the implicit tuple issue should be fixed now

@diceroll123 this should also fix the async generator issue, as well as not duplicating comments inside of the for loop's iterator. It'd be great if you could look over it, since I haven't worked with async python, but I think it accomplishes the same thing as yours

**Comment by MichaReiser** [comment]
I haven't thought this through yet but I wonder if we should convert this rule to a [binding rule instead](https://github.com/astral-sh/ruff/blob/f3d8c023d3baa1d225ef3f2a59f7660f90627003/crates/ruff_linter/src/checkers/ast/analyze/bindings.rs#L26-L27). Binding rules run **after** Ruff visited the entire AST. This has the advantage that the semantic model is complete.

**Comment by w0nder1ng** [comment]
I think that's all of the edge cases, except for the one involving the loop variable. I'd be happy to try to convert the rule into a binding rule, but I think that might be outside of the scope of this PR.

File: crates/ruff_linter/src/rules/perflint/rules/manual_list_comprehension.rs (hunk 1 above)
Comment (charliermarsh) [reply crates/ruff_linter/src/rules/perflint/rules/manual_list_comprehension.rs:237]: Sorry, I didn't look deeply, but often in those cases you need to make it a deferred rule, so it runs _after_ the semantic model has been built (e.g., run it in `deferred_for_loops`).

**Comment by w0nder1ng** [comment]
Even after moving the lint into `deferred_for_loops`, it still doesn't properly find the loop variable:

```python
def f():
    result = []
    for i in range(5):
    #   ^ running checker.semantic().resolve_name() on this ExprName returns None.
        result.append(i * 2)
        #             ^ when I run binding.statement() on this binding, 
        #               it returns the "i = 1" statement, even though that is clearly wrong
    i = 1
  # ^ lookup_symbol returns this i
    print(i) 
```
Am I missing something here, or is this behavior incorrect? See the last commit for the code I used to get this result.

**Comment by dhruvmanila** [comment]
> ```python
>     for i in range(5):
>     #   ^ running checker.semantic().resolve_name() on this ExprName returns None.
> ```

That might be because `i` is itself the definition. What I see in the semantic model is that an entry in the `resolved_names` is created only by the `resolve_load` function which would work on the `ExprName` with the `ExprContext::Load` context. But, here the `i` variable that is the for target would have the `ExprContext::Store` context (https://play.ruff.rs/44c3909e-4f46-4a46-bd6e-36ea78223322) which is why I think you're getting `None` there.

File: crates/ruff_linter/src/rules/perflint/rules/manual_list_comprehension.rs [hunk 2]
```diff
@@ -219,14 +219,58 @@ pub(crate) fn manual_list_comprehension(checker: &mut Checker, for_stmt: &ast::S
...
+    // TODO: this currently does not properly find usages outside the for loop; figure out why
+    if for_loop_target
+        .references()
+        .map(|id| checker.semantic().reference(id))
+        .inspect(|reference| {
+            // println!("{}", checker.locator().slice(reference.range()));
+            let binding_string = checker
+                .locator()
+                .slice(for_loop_target.statement(checker.semantic()).unwrap());
+            dbg!(binding_string);
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/perflint/rules/manual_list_comprehension.rs:250]:
```suggestion

```

**Comment by MichaReiser** [comment]
>   # ^ lookup_symbol returns this i

This is because the semantic model now captures the state after running the entire program. It's complete, and running `lookup_symbol` gives you the most recent binding for `i` after evaluating the entire function scope. That means you now have to do some extra work to get the for-loop target binding: 

```rust
    let last_target_binding = checker
        .semantic()
        .lookup_symbol(id)
        .expect("For loop to exist");

    let mut bindings = [last_target_binding].into_iter().chain(
        checker
            .semantic()
            .shadowed_bindings(checker.semantic().scope_id, last_target_binding)
            .filter_map(|shadowed| shadowed.same_scope().then_some(shadowed.shadowed_id())),
    );

    let target_binding = bindings
        .find_map(|binding_id| {
            let binding = checker.semantic().binding(binding_id);

            if dbg!(binding.statement(checker.semantic())).and_then(Stmt::as_for_stmt)
                == Some(for_stmt)
            {
                Some(binding)
            } else {
                None
            }
        })
        .expect("for target binding must exist");

    drop(bindings);
```

File: crates/ruff_linter/src/rules/perflint/rules/manual_list_comprehension.rs [hunk 3]
```diff
@@ -219,14 +219,73 @@ pub(crate) fn manual_list_comprehension(checker: &mut Checker, for_stmt: &ast::S
...
+        .find(|binding_id| {
+            let binding = checker.semantic().binding(*binding_id);
+            binding
+                .statement(checker.semantic())
+                .and_then(Stmt::as_for_stmt)
+                .is_some_and(|stmt| stmt.range == for_stmt.range)
+        })
+        .expect("for target binding must exist");
+    let target_binding = checker.semantic().binding(target_binding_id);
+    // TODO: should this be a HashMap?
```
Comment (w0nder1ng) [inline crates/ruff_linter/src/rules/perflint/rules/manual_list_comprehension.rs:258]: I made this a vector, but if there's enough references, it might make more sense for it to be a HashMap instead. What do you think?

**Comment by MichaReiser** [comment]
It seems we're now skipping over the two `result.append` usages in https://github.com/bokeh/bokeh/blob/829b2a75c402d0d0abd7e37ff201fbdfd949d857/src/bokeh/plotting/_figure.py#L485

Is this intentional? Should we change the implementation to not provide a fix but still the usage?

File: crates/ruff_linter/src/rules/perflint/rules/manual_list_comprehension.rs [hunk 4]
```diff
@@ -219,14 +219,73 @@ pub(crate) fn manual_list_comprehension(checker: &mut Checker, for_stmt: &ast::S
...
+
+    if target_binding
+        .references()
+        .filter(|r_id| !shadowed_references.contains(r_id))
+        .map(|reference| checker.semantic().reference(reference))
+        .any(|r| !for_stmt.range.contains_range(r.range()))
+    {
+        return;
+    }
+
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/perflint/rules/manual_list_comprehension.rs:278]: I don't understand what this code is doing. Would you mind adding a comment explaining why looking at the `shadowed_references` is necessary?

**Comment by w0nder1ng** [comment]
> It seems we're now skipping over the two `result.append` usages in https://github.com/bokeh/bokeh/blob/829b2a75c402d0d0abd7e37ff201fbdfd949d857/src/bokeh/plotting/_figure.py#L485
> 
> Is this intentional? Should we change the implementation not to provide a fix but still the usage?
> 
> Edit: I think this is intentional because `kw` is shadowed.

It would be shadowed if there weren't a return. A smaller example:
```python
def f(switch):
    i = 1
#   ^ this is the `i` which actually gets returned
    if switch:
        items = [1, 2, 3, 4]
        result = []
        #   v if it weren't for the return, this `i` would be the binding
        for i in items:
            result.append(i + 1)
        # v unconditional return means that the binding is not actually relevant
        return result
    #       v fix thinks this `i` is the loop variable
    return [i]
```

File: crates/ruff_linter/src/rules/perflint/rules/manual_list_comprehension.rs [hunk 5]
```diff
@@ -346,46 +447,76 @@ fn convert_to_list_extend(
...
+                let tokens = parse(binding_text, Mode::Module).map_err(|err| {
+                    anyhow!(
+                        "Failed to tokenize binding statement: {err} {}",
+                        binding_text
+                    )
+                })?;
+                tokens
+                    .tokens()
+                    .iter()
+                    .any(|token| matches!(token.kind(), TokenKind::Semi))
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/perflint/rules/manual_list_comprehension.rs:474]: I'm leaning towards not providing a fix in this case to avoid the extra complexity. 

Either way, we should avoid parsing here. We can use the `SimpleTokenizer` if we need tokenization and can't just use the AST

**Review by MichaReiser — COMMENTED** [review]
Uff, this rule is complicated. Thanks for pushing through it

I made it through the detection logic and pushed a few smaller simplifications. I'm now about to review the fix and noticed the `parse` call. I suggest to either not provide a fix in the multi assignment case (it's not that common) or to use the `SimpleTokenizer` to avoid using the full parser here. It might even simplify some of your code because it allows e.g. searching for the `;`

**Comment by w0nder1ng** [comment]
I've removed the tokenization without changing the rest of the code. Is it worth also removing the code to handle multiple statements to simplify the logic?

**Comment by MichaReiser** [comment]
> The code now iterates over the characters directly because I was having trouble with the SimpleTokenizer not properly tokenizing some lines. 

I pushed a change that uses the `SimpleTokenizer` and `BackwardsTokenizer` instead. That also revealed that we should remove any leading `;`. 

But I think we're good now and can land this change. Thank you for working on this very involved. rule

**Comment by Skylion007** [comment]
Beautiful job landing this rule @w0nder1ng . Any plans on tackling the dict comprehension version since the logic is very similar?

**Comment by w0nder1ng** [comment]
Sure, when I have the opportunity
