### PR TITLE
[`pep8-naming`] Fix `N802` false positives for `CGIHTTPRequestHandler` and `SimpleHTTPRequestHandler`

### LINKED ISSUE #19422: N802 false positives for `CGIHTTPRequestHandler` and `SimpleHTTPRequestHandler`
### Summary

#18907 added an exception to [`invalid-function-name` (N802)](https://docs.astral.sh/ruff/rules/invalid-function-name/) for `http.server.BaseHTTPRequestHandler`. That exception should also apply to its subclasses, `http.server.CGIHTTPRequestHandler` and `http.server.SimpleHTTPRequestHandler`. [Example](https://play.ruff.rs/5f94732e-948d-4404-9530-4e7ffffe8706):
```console
$ cat >n802.py <<'# EOF'
from http.server import CGIHTTPRequestHandler, SimpleHTTPRequestHandler
class C(CGIHTTPRequestHandler):
    def do_OPTIONS(self):
        pass
class S(SimpleHTTPRequestHandler):
    def do_OPTIONS(self):
        pass
# EOF

$ ruff --isolated check n802.py --select N802 --output-format concise -q
n802.py:3:9: N802 Function name `do_OPTIONS` should be lowercase
n802.py:6:9: N802 Function name `do_OPTIONS` should be lowercase
```

### Version

ruff 0.12.4 (ee2759b36 2025-07-17)

### PR DESCRIPTION
**Pull request by danparizher**
## Summary

Fixes #19422

### CODE REVIEW

File: crates/ruff_linter/src/rules/pep8_naming/rules/invalid_function_name.rs [hunk 1]
```diff
@@ -100,16 +100,16 @@ pub(crate) fn invalid_function_name(
...
                 let qualified = semantic.resolve_qualified_name(superclass);
                 qualified.is_some_and(|name| {
-                    matches!(
-                        name.segments(),
-                        ["http", "server", "BaseHTTPRequestHandler"]
-                    )
+                    let segments = name.segments();
+                    segments == ["http", "server", "BaseHTTPRequestHandler"]
+                        || segments == ["http", "server", "CGIHTTPRequestHandler"]
+                        || segments == ["http", "server", "SimpleHTTPRequestHandler"]
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/pep8_naming/rules/invalid_function_name.rs]: I think we can still use `matches!` here:

```suggestion
                    matches!(
                        name.segments(),
                        ["http", "server", "BaseHTTPRequestHandler" | "CGIHTTPRequestHandler" | "SimpleHTTPRequestHandler"]
                        )
```

You probably don't want to accept this through GitHub since it's formatted so poorly 😆

**Review by ntBre — APPROVED** [review]
Looks good, thank you! Just one minor simplification suggestion.
