### PR TITLE
[`ruff`] Support byte strings (`RUF055`)

### LINKED ISSUE #18739: RUF055 could support equivalent cases using byte strings
### Summary

RUF055 does not trigger when the regex contains a byte string [playground](https://play.ruff.rs/75ad86db-b4c0-428f-8538-f9fa3b016799)
```py
re.sub(rb"x", b"y", b"x")
```
This could be replaced with
```py
b"x".replace(rb"x", b"y")
```
I'm unsure if every string replacement would also work for byte string replacement, or if there would be some exceptions.

### Version

playground

### PR DESCRIPTION
**Pull request by danparizher**
## Summary

Closes #18739

### CODE REVIEW

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs [hunk 1]
```diff
@@ -95,17 +95,25 @@ pub(crate) fn unnecessary_regular_expression(checker: &Checker, call: &ExprCall)
...
 
-    // For now, restrict this rule to string literals and variables that can be resolved to literals
-    let Some(string_lit) = resolve_string_literal(re_func.pattern, semantic) else {
+    // Restrict this rule to string or bytes literals (or variables resolved to such literals).
+    let Some(literal) = resolve_literal(re_func.pattern, semantic) else {
         return;
     };
 
-    // For now, reject any regex metacharacters. Compare to the complete list
+    // Reject any regex metacharacters. Compare to the complete list
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs]: nit: I slightly preferred the original phrasing, other than adding `or bytes`, but I'm a bit biased by having written the original comments. The `For now` parts are kind of implicit TODOs. We don't necessarily have to keep these restrictions in the long term, especially in the case of metacharacters.

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs [hunk 2]
```diff
@@ -95,17 +95,25 @@ pub(crate) fn unnecessary_regular_expression(checker: &Checker, call: &ExprCall)
...
-        .contains(['.', '^', '$', '*', '+', '?', '{', '[', '\\', '|', '(', ')']);
+    let has_metacharacters = match &literal {
+        Literal::Str(str_lit) => str_lit
+            .value
+            .to_str()
+            .contains(['.', '^', '$', '*', '+', '?', '{', '[', '\\', '|', '(', ')']),
+        Literal::Bytes(bytes_lit) => bytes_lit.value.bytes().any(|b| {
+            matches!(
+                b,
+                b'.' | b'^' | b'$' | b'*' | b'+' | b'?' | b'{' | b'[' | b'\\' | b'|' | b'(' | b')'
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs]: It feels a bit unfortunate to have to duplicate the list of characters, but I'm not sure if it's bad enough to justify something like this:

```rust
    const METACHARACTERS: [char; 12] =
        ['.', '^', '$', '*', '+', '?', '{', '[', '\\', '|', '(', ')'];

    // Reject any regex metacharacters. Compare to the complete list
    // from https://docs.python.org/3/howto/regex.html#matching-characters
    let has_metacharacters = match &literal {
        Literal::Str(str_lit) => str_lit.value.to_str().contains(METACHARACTERS),
        Literal::Bytes(bytes_lit) => bytes_lit
            .value
            .bytes()
            .any(|b| METACHARACTERS.contains(&(b as char))),
    };
```

Unfortunately `array::map` isn't const, so to get a separate, const byte array you have to use something even wilder with a `while` loop in a const block, as far as I know.

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs [hunk 3]
```diff
@@ -186,25 +194,29 @@ impl<'a> ReFunc<'a> {
...
-                    // that would not raise an exception at runtime. They should be left as-is.
-                    if c == '\\' && next.is_ascii_alphanumeric() {
-                        if "abfnrtv".contains(next) {
-                            fixable = false;
-                        } else {
-                            return None;
+
+                if let Literal::Str(lit_str) = lit {
+                    // Retain existing escape analysis for string replacement literals.
+                    for (c, next) in lit_str.value.chars().tuple_windows() {
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs]: I think this check applies to byte strings too. This is the thread that prompted these changes: https://github.com/astral-sh/ruff/pull/14679#discussion_r1863802187, and it looks like the escape there also works for byte strings:

```pycon
>>> import re
>>> re.sub(b"foo", rb"\g<0>bar", b"foobar")
b'foobarbar'
```

so I don't think we can restrict this to the string literal case.

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs [hunk 4]
```diff
@@ -329,6 +341,43 @@ impl<'a> ReFunc<'a> {
...
 }
 
+/// A literal that can be either a string or a bytes literal.
+enum Literal<'a> {
+    Str(&'a ExprStringLiteral),
+    Bytes(&'a ExprBytesLiteral),
+}
+
+/// Try to resolve `name` to an [`ExprBytesLiteral`] in `semantic`.
+fn resolve_bytes_literal<'a>(
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs:376]: tiny nit: I'd swap the order of `resolve_literal` and `resolve_bytes_literal` to keep the general function closer to the top and closer to the enum it generates.

**Review by ntBre — COMMENTED** [review]
Thanks, this looks pretty good overall. I just had a couple of nits and a larger concern about the escapes in byte strings.

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs (hunk 1 above)
Comment (danparizher) [reply crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs]: That makes sense, I reverted the phrasing.

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs (hunk 4 above)
Comment (danparizher) [reply crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs:376]: Swapped.

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs (hunk 2 above)
Comment (danparizher) [reply crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs]: Implemented.

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs (hunk 3 above)
Comment (danparizher) [reply crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs]: I see what you mean - I updated the logic to handle both `str` and `bytes` literals for the replacement argument by using `match` on the resolved literal.

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs [hunk 5]
```diff
@@ -96,16 +98,20 @@ pub(crate) fn unnecessary_regular_expression(checker: &Checker, call: &ExprCall)
     };
 
     // For now, restrict this rule to string literals and variables that can be resolved to literals
-    let Some(string_lit) = resolve_string_literal(re_func.pattern, semantic) else {
+    let Some(literal) = resolve_literal(re_func.pattern, semantic) else {
         return;
     };
 
-    // For now, reject any regex metacharacters. Compare to the complete list
+    // Reject any regex metacharacters. Compare to the complete list
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs]:
```suggestion
    // For now, reject any regex metacharacters. Compare to the complete list
```

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs [hunk 6]
```diff
@@ -96,16 +98,20 @@ pub(crate) fn unnecessary_regular_expression(checker: &Checker, call: &ExprCall)
...
     // from https://docs.python.org/3/howto/regex.html#matching-characters
-    let has_metacharacters = string_lit
-        .value
-        .to_str()
-        .contains(['.', '^', '$', '*', '+', '?', '{', '[', '\\', '|', '(', ')']);
+
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs]:
```suggestion
```

(just reverting the minor changes in this area)

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs [hunk 7]
```diff
@@ -11,6 +11,8 @@ use ruff_text_size::TextRange;
 use crate::checkers::ast::Checker;
 use crate::{Applicability, Edit, Fix, FixAvailability, Violation};
 
+const METACHARACTERS: [char; 12] = ['.', '^', '$', '*', '+', '?', '{', '[', '\\', '|', '(', ')'];
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs]: nit: I'd probably just put this next to where it's used. It seems kind of confusing to have it up here.

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs [hunk 8]
```diff
@@ -186,28 +192,48 @@ impl<'a> ReFunc<'a> {
...
-                    // that would not raise an exception at runtime. They should be left as-is.
-                    if c == '\\' && next.is_ascii_alphanumeric() {
-                        if "abfnrtv".contains(next) {
-                            fixable = false;
-                        } else {
-                            return None;
+
+                match lit {
+                    Literal::Str(lit_str) => {
+                        // Retain existing escape analysis for string replacement literals.
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs]: I think this comment is slightly outdated now that it doesn't contrast with the behavior for byte literals.

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs [hunk 9]
```diff
@@ -186,28 +192,48 @@ impl<'a> ReFunc<'a> {
...
+                                    return None;
+                                }
+                            }
+                        }
+                    }
+                    Literal::Bytes(lit_bytes) => {
+                        for part in &lit_bytes.value {
+                            for (byte, next) in part.iter().copied().tuple_windows() {
+                                if byte == b'\\' && (next as char).is_ascii_alphanumeric() {
+                                    if "abfnrtv".contains(next as char) {
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs]: This might be a good constant to extract too.

**Review by ntBre — APPROVED** [review]
Thank you! I found a few more very small nits, but this is good to go otherwise.
