### PR TITLE
[`isort`] Handle multiple continuation lines after module docstring (`I002`)

### LINKED ISSUE #19815: `start_of_file` handles at most one backslash, making I002 introduce a syntax error
### Summary

#19505 made `start_of_file` handle a backslash after a docstring, but it only handles _one_ backslash. If the next line has a backslash too, the original bug appears. [Example](https://play.ruff.rs/79771e2f-e2a0-4751-95c6-8e291c925a04):
```console
$ cat >i002.py <<'# EOF'
"docstring"\
\

print(f"{__doc__=}")
# EOF

$ ruff --isolated check i002.py --select I002 --config 'lint.isort.required-imports=["import sys"]' --diff 2>&1 | grep error:
error: Fix introduced a syntax error. Reverting all changes.
```

### Version

ruff 0.12.8 (f51a228f0 2025-08-07)

### PR DESCRIPTION
**Pull request by danparizher**
## Summary

Fixes #19815

### CODE REVIEW

File: crates/ruff_linter/src/importer/insertion.rs [hunk 1]
```diff
@@ -379,6 +380,17 @@ mod tests {
...
+        let contents = r#"
+"""Hello, world!"""\
+\
+
+"#
+        .trim_start();
+        assert_eq!(
+            insert(contents)?,
+            Insertion::own_line("", TextSize::from(24), "\n")
+        );
```
Comment (ntBre) [inline crates/ruff_linter/src/importer/insertion.rs:391]: Would you mind adding an I002 test for this too, like in #19505? That'll give a nice snapshot in addition to this assertion.

File: crates/ruff_linter/src/importer/insertion.rs [hunk 2]
```diff
@@ -63,9 +63,10 @@ impl<'a> Insertion<'a> {
                 return Insertion::inline(" ", location.add(offset).add(TextSize::of(';')), ";");
             }
 
-            // If the first token after the docstring is a continuation character (i.e. "\"), advance
-            // an additional row to prevent inserting in the same logical line.
-            if match_continuation(locator.after(location)).is_some() {
+            // If the first token after the docstring is a continuation character (i.e. "\\"), advance
```
Comment (ntBre) [inline crates/ruff_linter/src/importer/insertion.rs]: Do we need to change this to escape the `\` here? I think it was okay since we're in a comment.

I would probably just change the initial `If` in this comment to `While` instead of adding another sentence, much like the code change 😄

File: crates/ruff_linter/src/importer/insertion.rs [hunk 3]
```diff
@@ -63,9 +63,10 @@ impl<'a> Insertion<'a> {
                 return Insertion::inline(" ", location.add(offset).add(TextSize::of(';')), ";");
             }
 
-            // If the first token after the docstring is a continuation character (i.e. "\"), advance
-            // an additional row to prevent inserting in the same logical line.
-            if match_continuation(locator.after(location)).is_some() {
+            // While the first token after the docstring is a continuation character (i.e. "\"), advance
+            // additional rows to prevent inserting in the same logical line. Continue advancing
+            // while subsequent lines also contain a continuation.
```
Comment (ntBre) [inline crates/ruff_linter/src/importer/insertion.rs]: I think this part is basically redundant now.

```suggestion
            // additional rows to prevent inserting in the same logical line.
```

**Review by ntBre — APPROVED** [review]
Thank you!
