### PR TITLE
[`pydoclint`] Teach rules to understand reraised exceptions as being explicitly raised

### LINKED ISSUE #12630: [pydoclint] DOC502 should detect re-raised exceptions
Consider

```python
# repro_DOC.py

def my_func(arg: int) -> int:
    """Doer of things.

    Args:
        arg (int): The number to be doubled.

    Returns:
        int: The doubled number.

    Raises:
        TypeError: If arg cannot be multiplied by 2.
    """
    try:
        return arg * 2
    except TypeError:
        print("arg should be an integer")
        raise
```

`pydoclint` correctly detects the exception is re-reraised:

```console
$ pydoclint --style=google repro_DOC.py
Loading config from user-specified .toml file: pyproject.toml
No config found in pyproject.toml.
Skipping files that match this pattern: \.git|\.tox
repro_DOC.py
🎉 No violations 🎉
```

Ruff does not

```console
$ ruff check --select DOC repro_DOC.py
repro_DOC.py:12:1: DOC502 Raised exception is not explicitly raised: `TypeError`
   |
 7 |           arg (int): The number to be doubled.
 8 |   
 9 | /     Raises:
10 | |         TypeError: If arg cannot be multiplied by 2.
11 | |     """
   | |____^ DOC502
12 |       try:
13 |           return arg * 2
   |
```

### PR DESCRIPTION
**Pull request by AlexWaygood**
## Summary

Fixes #12630.

DOC501 and DOC502 now understand functions with constructs like this to be explicitly raising `TypeError` (which should be documented in a function's docstring):

```py
try:
    foo():
except TypeError:
    ...
    raise
```

I made an exception for `Exception` and `BaseException`, however. Constructs like this are reasonably common, and I don't think anybody would say that it's worth putting in the docstring that it raises "some kind of generic exception":

```py
try:
    foo()
except BaseException:
    do_some_logging()
    raise
```

## Test Plan

`cargo test -p ruff_linter --lib`

### CODE REVIEW

File: crates/ruff_linter/src/rules/pydoclint/rules/check_docstring.rs [hunk 1]
```diff
@@ -571,17 +606,14 @@ impl<'a> Visitor<'a> for BodyVisitor<'a> {
...
-    semantic: &SemanticModel<'a>,
-    exc: &'a Expr,
-) -> Option<QualifiedName<'a>> {
-    if let Some(qualified_name) = semantic.resolve_qualified_name(exc) {
-        return Some(qualified_name);
-    }
-    if let Expr::Call(ast::ExprCall { func, .. }) = exc {
-        return extract_raised_exception(semantic, func.as_ref());
-    }
-    None
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/pydoclint/rules/check_docstring.rs:584]: I got rid of this helper by using `map_callable()` before passing the node to `resolve_qualified_name` in `visit_stmt`

**Review by charliermarsh — APPROVED** [review]
