### PR TITLE
Fix panic when formatting binary expression with two implicit concatenated string operands

### LINKED ISSUE #7245: Format cause panic 'slice index starts at 4 but ends at 3'
Ruff 0.0.287 (latest changes from main branch)
```
ruff format *.py
```

file content(at least simple cpython script shows that this is valid python file):
```
class EC2REPATH:
        f.write ("Pathway name" + "\t" "Database Identifier" + "\t" "Source database" + "\n")
```

error
```

warning: `ruff format` is a work-in-progress, subject to change at any time, and intended only for experimentation.

error: `ruff` crashed. This indicates a bug in `ruff`. If you could open an issue at:

https://github.com/astral-sh/ruff/issues/new?title=%5BPanic%5D

quoting the executed command, along with the relevant file contents and `pyproject.toml` settings, we'd be very appreciative!

thread 'main' panicked at 'slice index starts at 4 but ends at 3', crates/ruff_python_formatter/src/expression/binary_like.rs:472:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::slice::index::slice_index_order_fail_rt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/slice/index.rs:98:5
   3: core::slice::index::slice_index_order_fail
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/slice/index.rs:91:14
   4: <ruff_python_formatter::expression::binary_like::BinaryLike as ruff_formatter::Format<ruff_python_formatter::context::PyFormatContext>>::fmt
   5: <ruff_python_formatter::expression::FormatExpr as ruff_formatter::FormatRule<ruff_python_ast::nodes::Expr,ruff_python_formatter::context::PyFormatContext>>::fmt::{{closure}}
   6: <ruff_python_formatter::expression::FormatExpr as ruff_formatter::FormatRule<ruff_python_ast::nodes::Expr,ruff_python_formatter::context::PyFormatContext>>::fmt
   7: ruff_formatter::arguments::Argument<Context>::new::formatter
   8: ruff_formatter::arguments::Argument<Context>::new::formatter
   9: ruff_formatter::arguments::Argument<Context>::new::formatter
  10: ruff_formatter::arguments::Argument<Context>::new::formatter
  11: ruff_formatter::arguments::Argument<Context>::new::formatter
  12: <ruff_python_formatter::expression::parentheses::FormatParenthesized as ruff_formatter::Format<ruff_python_formatter::context::PyFormatContext>>::fmt
  13: ruff_python_formatter::FormatNodeRule::fmt
  14: ruff_python_formatter::FormatNodeRule::fmt
  15: <ruff_python_formatter::expression::FormatExpr as ruff_formatter::FormatRule<ruff_python_ast::nodes::Expr,ruff_python_formatter::context::PyFormatContext>>::fmt
  16: <ruff_python_formatter::statement::FormatStmt as ruff_formatter::FormatRule<ruff_python_ast::nodes::Stmt,ruff_python_formatter::context::PyFormatContext>>::fmt
  17: <ruff_python_formatter::statement::suite::FormatSuite as ruff_formatter::FormatRule<alloc::vec::Vec<ruff_python_ast::nodes::Stmt>,ruff_python_formatter::context::PyFormatContext>>::fmt
  18: ruff_formatter::arguments::Argument<Context>::new::formatter
  19: ruff_formatter::arguments::Argument<Context>::new::formatter
  20: <ruff_python_formatter::statement::clause::FormatClauseBody as ruff_formatter::Format<ruff_python_formatter::context::PyFormatContext>>::fmt
  21: <ruff_python_formatter::statement::stmt_class_def::FormatStmtClassDef as ruff_python_formatter::FormatNodeRule<ruff_python_ast::nodes::StmtClassDef>>::fmt_fields
  22: <ruff_python_formatter::statement::FormatStmt as ruff_formatter::FormatRule<ruff_python_ast::nodes::Stmt,ruff_python_formatter::context::PyFormatContext>>::fmt
  23: <ruff_python_formatter::statement::suite::FormatSuite as ruff_formatter::FormatRule<alloc::vec::Vec<ruff_python_ast::nodes::Stmt>,ruff_python_formatter::context::PyFormatContext>>::fmt
  24: ruff_python_formatter::format_module
  25: rayon::iter::plumbing::bridge_producer_consumer::helper
  26: ruff_cli::run
  27: ruff::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

[python_compressed.zip](https://github.com/astral-sh/ruff/files/12561912/python_compressed.zip)

### PR DESCRIPTION
**Pull request by MichaReiser**
## Summary

This PR fixes a panic when formatting a binary like expression where both operands are implicit concatenated strings: `"a" "b" + "c" "d"`

The implementation formats the implicit concatenated string together with the right operator and than continues with the expressions to the right. 
The next iteration then tried to format the expressions between the last formatted right operator (`+`) and the next string concatenation, assuming that it would never be empty. 
This assumption was incorrect as the above example demonstrates. There's no other binary like expression between the `+` and `"c" "d"`. 

This PR fixes this by skipping the formatting of the left side if the last operator is the same as the left operator of this implicit concatenated string. 

Closes #7245

## Test Plan

Added tests

### CODE REVIEW

**Comment by MichaReiser** [comment]
Current dependencies on/for this PR:
* main
  * **PR #7287** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff/7287" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/astral-sh/ruff/7287?utm_source=stack-comment).

**Review by konstin — APPROVED** [review]

File: crates/ruff_python_formatter/src/expression/binary_like.rs [hunk 1]
```diff
@@ -317,46 +317,58 @@ impl Format<PyFormatContext<'_>> for BinaryLike<'_> {
                     //     ^^^^^^ this part or ^^^^^^^ this part
                     // ```
                     if let Some(left_operator_index) = index.left_operator() {
-                        // Everything between the last implicit concatenated string and the left operator
-                        // right before the implicit concatenated string:
+                        // Handles the case where the left and right side of a binary expression are both
+                        // implicit concatenated strings. In this case, the left operator has already been written
+                        // by the preceding implicit concatenated string. It is only necessary to finish the group,
+                        // wrapping the soft line break and operator.
```
Comment (charliermarsh) [inline crates/ruff_python_formatter/src/expression/binary_like.rs:323]: I don't know if it matters, but doesn't this mean that the right side of `"a" "b" + "c" "d"` will be formatted using the right-side formatting logic, which doesn't include the `with_layout(StringLayout::ImplicitConcatenatedStringInBinaryLike)`?

Comment (MichaReiser) [reply crates/ruff_python_formatter/src/expression/binary_like.rs:323]: The implicit string formatting formats `left_operand` (optional) `left_operator` `implicit_concat` `right_operator`. 

So for, `a + "b" "c" * "d" "e"` it formats `a`, `+`, `"b" "c"` and `*`. The right side of `*` gets formatted as part of the next implicit concatenated string.

https://github.com/astral-sh/ruff/blob/1e6df19a351170ded4b1e1a4e068993107bd1047/crates/ruff_python_formatter/src/expression/binary_like.rs#L393-L431

Comment (charliermarsh) [reply crates/ruff_python_formatter/src/expression/binary_like.rs:323]: Ohh it only formats right _operator_, okay, got it, thank you. This is what was blocking me last night :D

Comment (MichaReiser) [reply crates/ruff_python_formatter/src/expression/binary_like.rs:323]: Yes, it only formats the right operator, but starts a group that includes the right operand (without formatting it)
