### PR TITLE
[`pyupgrade`] Prevent infinite loop with `I002` and `UP026`

### LINKED ISSUE #19842: [Infinite loop] I002 and UP026
### Summary

Ruff fails to converge when [`missing-required-import` (I002)](https://docs.astral.sh/ruff/rules/missing-required-import/) and [`deprecated-mock-import` (UP026)](https://docs.astral.sh/ruff/rules/deprecated-mock-import/) are selected and `import mock` is required. [Example](https://play.ruff.rs/5daddb7d-af26-4fa7-9004-09f500553946):
```console
$ echo 1 | ruff --isolated check - --select I002,UP026 --config 'lint.isort.required-imports=["import mock"]' --fix

error: Failed to converge after 100 iterations.

This indicates a bug in Ruff. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BInfinite%20loop%5D

...quoting the contents of `-`, the rule codes I002, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
from unittest import mock
1
-:1:1: I002 Missing required import: `import mock`
Found 101 errors (100 fixed, 1 remaining).
[*] 1 fixable with the `--fix` option.
```

### Version

ruff 0.12.8 (f51a228f0 2025-08-07)

### PR DESCRIPTION
**Pull request by TaKO8Ki**
## Summary

Fixes #19842

Prevent infinite loop with I002 and UP026

- Implement isort-aware handling for UP026 (deprecated mock import):
- Add CLI integration tests in crates/ruff/tests/lint.rs:

## Test Plan

I have added two integration tests `pyupgrade_up026_respects_isort_required_import_fix` and `pyupgrade_up026_respects_isort_required_import_from_fix` in `crates/ruff/tests/lint.rs`.

### CODE REVIEW

File: crates/ruff/tests/lint.rs [hunk 1]
```diff
@@ -5059,6 +5059,60 @@ fn flake8_import_convention_unused_aliased_import_no_conflict() {
...
+            .arg("--no-cache")
+            .arg("--isolated")
+            .arg("--fix")
+            .arg("--config")
+            .arg(r#"lint.isort.required-imports = ["import mock"]"#)
+            .args(["--select", "I002,UP026"])
+            .args(["--stdin-filename", "test.py"])
+            .arg("-")
+            .pass_stdin("import mock\n"),
+        @r"
```
Comment (dylwil3) [inline crates/ruff/tests/lint.rs]: Can you recreate the example from the issue here and pass in an empty file (or I guess a file just containing the literal `1`)?

File: crates/ruff_linter/src/rules/pyupgrade/rules/deprecated_mock_import.rs [hunk 2]
```diff
@@ -299,6 +300,13 @@ pub(crate) fn deprecated_mock_import(checker: &Checker, stmt: &Stmt) {
...
                 // Add a `Diagnostic` for each `mock` import.
                 for name in names {
+                    if is_import_required_by_isort(
+                        &checker.settings().isort.required_imports,
+                        stmt.into(),
+                        name,
+                    ) {
+                        continue;
+                    }
                     if &name.name == "mock" || &name.name == "mock.mock" {
```
Comment (dylwil3) [inline crates/ruff_linter/src/rules/pyupgrade/rules/deprecated_mock_import.rs]: Let's combine these `if` statements and have the name checks come first so that the `is_import_required_by_isort` is executed more rarely.

File: crates/ruff/tests/lint.rs (hunk 1 above)
Comment (TaKO8Ki) [reply crates/ruff/tests/lint.rs]: I've updated it based on the example in the issue.

File: crates/ruff_linter/src/rules/pyupgrade/rules/deprecated_mock_import.rs (hunk 2 above)
Comment (TaKO8Ki) [reply crates/ruff_linter/src/rules/pyupgrade/rules/deprecated_mock_import.rs]: I've combined them into one.
