### PR TITLE
[`playground`] Allow hover quick fixes to appear for overlapping diagnostics

### LINKED ISSUE #19655: ISC002 makes W605 unfixable on playground
### Summary

I'm not sure why this happens, but if both [invalid-escape-sequence (W605)](https://docs.astral.sh/ruff/rules/invalid-escape-sequence/#invalid-escape-sequence-w605) and [multi-line-implicit-string-concatenation (ISC002)](https://docs.astral.sh/ruff/rules/multi-line-implicit-string-concatenation/#multi-line-implicit-string-concatenation-isc002) trigger on the same string on the playground, `W605` will not be fixable using the On Hover context menu -> Quick Fix.

https://play.ruff.rs/83a23eba-a1c5-4394-aab9-dcd20e098a55

Image

This seems to just happen with the playground hover menu, the fix works fine locally in PowerShell with `--fix`, the "Quick Fix" shows up on hover locally in VSC with the VSC extension, and when using the `ctrl+.` shortcut with the cursor over the `W605` error to open the Quick Fix menu directly.

No clue if this is something that is fixable/is a problem on ruff's end, it could also be something in Monaco.

### Version

Playground

### PR DESCRIPTION
**Pull request by danparizher**
## Summary

Fixes #19655

- Switched quick-fix filtering from line-equality to proper range intersection to show all relevant fixes for the hovered range.
- Set `code` on markers with `diagnostic.code ?? undefined` to satisfy Monaco’s `IMarkerData` type and ensure the rule code shows up without type errors.

### CODE REVIEW

File: playground/ruff/src/Editor/SourceEditor.tsx [hunk 1]
```diff
@@ -124,7 +124,50 @@ class RuffCodeActionProvider implements CodeActionProvider {
...
+          diagStartCol,
+          rangeEndLine,
+          rangeEndCol,
+        );
+        const diagEndsAfterOrAtRangeStart = isAfterOrEqual(
+          diagEndLine,
+          diagEndCol,
+          rangeStartLine,
+          rangeStartCol,
+        );
```
Comment (MichaReiser) [inline playground/ruff/src/Editor/SourceEditor.tsx]: Can we use `range.containsRange(other_range)` here instead (or the other way round or any other range method)

**Comment by danparizher** [comment]
I did some digging and found `Range.areIntersecting()` which is perfect for this case.
