### PR TITLE
[`perflint`] Fix `PERF101` autofix creating a syntax error and mark autofix as unsafe if there are comments in the `list` call expr

### LINKED ISSUE #18783: [Perflint] PERF101 fix can cause syntax error
### Summary

If the `list` is next to another item using parenthesis, fixing `PERF101` can cause a syntax error. The fix should make sure there is always padding. [playground](https://play.ruff.rs/3ae00ded-2cad-4739-a0c4-eab55e23746e)
```
PS D:\python_projects> Get-Content issue.py
```
```py
items = (1, 2, 3)
for i in(list)(items):
    print(i)
```
```
PS D:\python_projects> uvx ruff check issue.py --select PERF --fix
```
```

error: Fix introduced a syntax error. Reverting all changes.

This indicates a bug in Ruff. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BFix%20error%5D

...quoting the contents of `issue.py`, the rule codes PERF101, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

issue.py:2:9: PERF101 Do not cast an iterable to `list` before iterating over it
  |
1 | items = (1, 2, 3)
2 | for i in(list)(items):
  |         ^^^^^^^^^^^^^ PERF101
3 |     print(i)
  |
  = help: Remove `list()` cast

Found 1 error.
[*] 1 fixable with the `--fix` option.
```

### Version

ruff 0.12.0 (87f0feb21 2025-06-17) + playground

### PR DESCRIPTION
**Pull request by LaBatata101**
## Summary

Fixes #18783 and #18784

## Test Plan
Add  regression tests

### CODE REVIEW

File: crates/ruff_linter/src/rules/perflint/rules/unnecessary_list_cast.rs [hunk 1]
```diff
@@ -35,6 +37,19 @@ use crate::{AlwaysFixableViolation, Edit, Fix};
 /// for i in items:
 ///     print(i)
 /// ```
+///
+/// ## Fix safety
+/// This rule's fix is marked as unsafe if there's comments in the
+/// `list()` call.
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/perflint/rules/unnecessary_list_cast.rs]:
```suggestion
/// `list()` call, as comments may be removed.
```

**Review by MichaReiser — APPROVED** [review]
Thank you
