### PR TITLE
Handle parentheses when formatting slice expressions

### LINKED ISSUE #5733: Subscript formatting fails when element is parenthesized
```python
def f(x):
    x[(1) :: ]
```
fails to format:
```
$ cargo run --bin ruff_python_formatter -- --emit stdout scratch.py
Error: Failed to format node

Caused by:
    syntax error
```

I passes when removing the parentheses around the 1, so this is somehow caused by incorrect parentheses handling.

```python
def f(x):
    x[1 :: ]
```

### PR DESCRIPTION
**Pull request by konstin**
**Summary** Fix the formatter crash with `x[(1) :: ]` and related code.

**Problem** For assigning comments in slices in subscripts, we need to find the positions of the colons to assign comments before and after the colon to the respective lower/upper/step node (or dangling in that section). Formatting `x[(1) :: ]` was broken because we were looking for a `:` after the `1` but didn't consider that there could be a `)` outside the range of the lower node, which contains just the `1` and no optional parentheses.

**Solution** Use the simple tokenizer directly and skip all closing parentheses.

**Test Plan** I added regression tests.

Closes #5733

### CODE REVIEW

**Comment by konstin** [comment]
Current dependencies on/for this PR:
* main
  * **PR #5881** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff/5881" target="_blank">Graphite</a> 
    * **PR #5882** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff/5882" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/astral-sh/ruff/5882?utm_source=stack-comment).

File: crates/ruff_python_formatter/src/expression/expr_slice.rs [hunk 1]
```diff
@@ -175,17 +177,16 @@ pub(crate) fn find_colons(
...
-        })?;
-    let second_colon = if next_token.kind == TokenKind::Colon {
-        debug_assert!(
-            next_token.range.start() < range.end(),
-            "The next token in a slice must either be a colon or the closing bracket"
-        );
-        Some(next_token)
+    let mut tokens = SimpleTokenizer::new(contents, TextRange::new(after_upper, range.end()))
+        .skip_trivia()
+        .skip_while(|token| token.kind == TokenKind::RParen);
```
Comment (MichaReiser) [inline crates/ruff_python_formatter/src/expression/expr_slice.rs:182]: I wonder if we should create a helper for this. It's not the first time we incorrectly assumed that there are never right parens. But I don't have a good idea of how, and this is cleary out of this PR's scope.

**Review by MichaReiser — APPROVED** [review]

File: crates/ruff_python_formatter/src/expression/expr_slice.rs (hunk 1 above)
Comment (konstin) [reply crates/ruff_python_formatter/src/expression/expr_slice.rs:182]: An after node range search util would be nice. I did some small changes in #5885
