### PR TITLE
Server: Allow `FixAll` action in presence of version-specific syntax errors

### LINKED ISSUE #16841: Organize imports not working due to deeply nested function
### Summary

`Organize imports` code action not working when one of the function in the file is deeply nested.
Checkout the code sample and screen recording.

**models.py**
```py
class LinkedinAccountIdValidationReq:
    pass


class LinkedinAccountIdValidationRes:
    pass


class LinkedinAdsAccount:
    pass


class LinkedinAdsCampaignGroup:
    pass
```

**main.py**
```py
from models import LinkedinAdsAccount, LinkedinAdsCampaignGroup
from models import LinkedinAccountIdValidationReq, LinkedinAccountIdValidationRes

from typing import Any
import polars as pl


async def validate_account_access(
    accounts: list[LinkedinAccountIdValidationReq],
) -> list[LinkedinAccountIdValidationRes]:
    """Validate whether Account IDs has access on Access Token"""
    # Validations
    validations: list[LinkedinAccountIdValidationRes] = []

    print(accounts)

    return validations


async def get_accounts(access_token: str) -> list[LinkedinAdsAccount]:
    """Get Accounts"""
    accounts: list[LinkedinAdsAccount] = []

    print(access_token)

    return accounts


async def get_campaign_groups(
    access_token: str, account_id: int
) -> list[LinkedinAdsCampaignGroup]:
    """Get Campaign Groups"""
    campaign_groups = []
    print(access_token, account_id)
    return campaign_groups


async def transform_response_rows(
    rows: list[dict[str, Any]],
    account_id: str | None,
    access_token: str,
    column_configs: dict[str, dict[str, Any]],
) -> pl.DataFrame:
    """Transform Response rows"""
    # No data found
    if len(rows) == 0:
        return pl.DataFrame(
            schema={
                col: pl.Float64 if config["type"] == "METRIC" else pl.Utf8
                for col, config in column_configs.items()
            }
        )

    # Rows to dataframe first
    df = pl.from_dicts(rows, infer_schema_length=None)

    # Transform Pivot values
    if "pivotValues" in df.columns:
        df = df.with_row_index("row_nr")
        df = df.join(df.pivot("entityType", index="row_nr", values="entityId"), on="row_nr")
        df = df.drop(["pivotValues", "row_nr", "entityType", "entityId"], strict=False)

        # Entity-wise data e.g {sponsoredCampaign: pl.Dataframe, ...}
        entity_data: dict[str, pl.DataFrame] = {}

        # For each column config with pivot
        for col, col_config in column_configs.items():
            # Entity type and key
            entity_type, entity_key = col_config["type"], col_config["key"]

            # ID column already exists in df, for other keys fetch data from API
            if entity_key == "id":
                df = df.with_columns(pl.col(entity_type).alias(col))
            elif account_id:
                entity_df = entity_data.get(entity_type)
                if entity_df is None:
                    entities = []
                    args = [
                        access_token,
                        int(account_id.split(":")[-1]),
                    ]
                    match entity_type:
                        case "sponsoredAccount":
                            entities = await get_accounts(args[0])
                        case "sponsoredCampaign":
                            entities = await get_campaign_groups(*args)

                    entity_df = (
                        pl.from_dicts([{"key": "val"} for _ in entities])
                        .cast(pl.Utf8)
                        .select(pl.all().name.prefix(f"{entity_type}."))
                    )

                # Rename column
                if col_config["res_key"] in entity_df.columns:
                    entity_df = entity_df.rename({col_config["res_key"]: col_config["id"]})

                # Set with dict
                entity_data[entity_type] = entity_df

        # Join dataframes
        for entity_type, entity_df in entity_data.items():
            df = df.join(entity_df, left_on=entity_type, right_on=f"{entity_type}.id")

    return df
```

**pyproject.toml**
```toml
[tool.ruff]
line-length = 99
lint.ignore = ["E722"]

[tool.poetry]
name = "ruffdemo"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
polars = "^1.25.2"


[tool.poetry.group.dev.dependencies]
ruff = "^0.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

___

Screen recording showing code action behaviout with and without deeply nested code.

https://github.com/user-attachments/assets/1498b295-84e6-4508-8311-c07a1f23ef25

### Version

ruff 0.11.0

### PR DESCRIPTION
**Pull request by dylwil3**
The single flag `has_syntax_error` on `LinterResult` is replaced with two (private) flags: `has_valid_syntax` and `has_no_unsupported_syntax_errors`, which record whether there are `ParseError`s or `UnsupportedSyntaxError`s, respectively. Only the former is used to prevent a `FixAll` action.

An attempt has been made to make consistent the usage of the phrases "valid syntax" (which seems to be used to refer only to _parser_ errors) and "syntax error" (which refers to both _parser_ errors and version-specific syntax errors).

Remark for review: `crates/ruff/src/diagnostics.rs` is actually a small diff, not sure what happened there. If you pull it down locally and `git diff --ignore-all-space` it looks better.

Closes #16841

Test:

https://github.com/user-attachments/assets/94f6ed6a-afdc-49f0-8a09-8e2123adb07a

### CODE REVIEW

**Review by ntBre — APPROVED** [review]
Thanks for jumping on this, LGTM! Just need to propagate the changes to the fuzz crate it looks like.

File: crates/ruff_linter/src/linter.rs [hunk 1]
```diff
@@ -593,7 +631,8 @@ pub fn lint_fix<'a>(
         return Ok(FixerResult {
             result: LinterResult {
                 messages,
-                has_syntax_error: !is_valid_syntax,
+                has_valid_syntax: parsed.has_valid_syntax(),
```
Comment (ntBre) [inline crates/ruff_linter/src/linter.rs:634]: I'm working on adding another type of syntax error now, which drew my attention back to this area. I think we actually want to use `has_no_syntax_errors` (from the first iteration) here to preserve the behavior of the old code instead of recomputing it (on the last iteration). Maybe we need two variables outside the loop now to capture them both from the first iteration?

I think the new errors (semantic/compile-time syntax errors) will be merged into the `has_no_unsupported_syntax_errors` variable to avoid blocking these fixes too.

Comment (ntBre) [reply crates/ruff_linter/src/linter.rs]: Yeah I think that looks right. It's unfortunate that we can't use the `Parsed` method now, but I guess we really need to differentiate the two bools later instead of grouping them.

I'm thinking the semantic syntax errors will get grouped with the unsupported syntax errors, so I might tweak that name later, but this is exactly what I had in mind for now. Those don't come from the parser, so they won't affect the `Parsed` interface.

I guess we don't have a test for this behavior. I think it would require an intentionally faulty test rule that causes a syntax error.

File: crates/ruff_linter/src/linter.rs [hunk 2]
```diff
@@ -40,11 +40,48 @@ use crate::{directives, fs, Locator};
...
-    /// If `true`, at least one syntax error was detected in the source file.
+    /// Flag indicating that the parsed source code does not contain any
+    /// [`ParseError`]s
+    has_valid_syntax: bool,
+    /// Flag indicating that the parsed source code does not contain any
+    /// [`UnsupportedSyntaxError`]s
+    has_no_unsupported_syntax_errors: bool,
+}
+
+impl LinterResult {
```
Comment (dhruvmanila) [inline crates/ruff_linter/src/linter.rs:51]: It's a bit unfortunate that these methods need to be repeated on both `Parsed` and `LinterResult`. We could explore another approach to avoid duplication, not necessarily in this PR, that utilizes `bitflags` for these two booleans like `SyntaxFlags` that can then be queried to ask whether there are parse errors or unsupported syntax errors.

**Review by dhruvmanila — APPROVED** [review]
Thanks for the quick fix!

I think we should explore an alternate option to avoid the duplication here as a follow-up.

**Comment by dhruvmanila** [comment]
One minor nit: we mainly use the `[...]` syntax for rule categories so I'd avoid using "[server]" and instead just use "Server: " in the PR title.
