### PR TITLE
[`flake8-use-pathlib`] Fix false negative on direct `Path()` instantiation (`PTH210`)

### LINKED ISSUE #19329: False negative for `invalid-pathlib-with-suffix` (`PTH210`) if method called on direct instantiation
### Summary

False negatives are understandable here if we can't be sure that an object is a `Path` object - but the below false negative seems silly because we are in a situation where we should be even _more_ confident that we have a `Path` object!

```python
from pathlib import Path

path = Path()

path.with_suffix("py") # PTH210

Path().with_suffix("py") # no lint
```

[Playground link](https://play.ruff.rs/17ca1407-505d-4d12-8d87-41d558680c11)

### Version

ruff 0.12.3 (5bc81f26c 2025-07-11)

### PR DESCRIPTION
**Pull request by danparizher**
## Summary

Fixes #19329

### CODE REVIEW

File: crates/ruff_linter/src/rules/flake8_use_pathlib/rules/invalid_pathlib_with_suffix.rs [hunk 1]
```diff
@@ -141,12 +141,31 @@ fn is_path_with_suffix_call(semantic: &SemanticModel, func: &ast::Expr) -> bool
...
+                                | "PosixPath"
+                                | "PurePath"
+                                | "PurePosixPath"
+                                | "PureWindowsPath"
+                                | "WindowsPath"
+                        ]
+                    )
+                })
+        }
+        _ => false,
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/flake8_use_pathlib/rules/invalid_pathlib_with_suffix.rs]: I think we can reuse part of the implementation for `is_pathlib_path` for this:


```suggestion
        expr => PathlibPathChecker::match_initializer(expr, semantic),
```

(with this diff at the top too):

```diff
-use ruff_python_semantic::analyze::typing;
+use ruff_python_semantic::analyze::typing::{self, PathlibPathChecker, TypeChecker};
```
