### PR TITLE
[UP031] When encountering `"%s" % var` offer unsafe fix

### LINKED ISSUE #10187: UP031 not violated for variables, only literal values
UP031 (`printf-string-formatting`, suggests using `str.format` instead of percent formatting) doesn't trigger when using a variable and not a literal value.

Even using the example from the docs - 

```python
value = 1
print("%s" % value)  # seems to be OK

print("%s" % 1)  # violating UP031
```

I've tried this out in the rust playground as well ([here's an example](https://play.ruff.rs/5477131a-fc56-44d7-bbfb-da4b9607428b)) with version 0.3.0, selecting all `UP` rules

### PR DESCRIPTION
**Pull request by plredmond**
Resolves #10187

<details>
<summary>Old PR description; accurate through commit e86dd7d; probably best to leave this fold closed</summary>

## Description of change

In the case of a printf-style format string with only one %-placeholder and a variable at right (e.g.  `"%s" % var`):

* The new behavior attempts to dereference the variable and then match on the bound expression to distinguish between a 1-tuple (fix), n-tuple (bug :bug:), or a non-tuple (fix). Dereferencing is via `analyze::typing::find_binding_value`.
* If the variable cannot be dereferenced, then the type-analysis routine is called to distinguish only tuple (no-fix) or non-tuple (fix). Type analysis is via `analyze::typing::is_tuple`.
* If any of the above fails, the rule still fires, but no fix is offered.

## Alternatives

* If the reviewers think that singling out the 1-tuple case is too complicated, I will remove that.
* The ecosystem results show that no new fixes are detected. So I could probably delete all the variable dereferencing code and code that tries to generate fixes, tbh.

## Changes to existing behavior

**All the previous rule-firings and fixes are unchanged except for** the "false negatives" in `crates/ruff_linter/resources/test/fixtures/pyupgrade/UP031_1.py`. Those previous "false negatives" are now true positives and so I moved them to `crates/ruff_linter/resources/test/fixtures/pyupgrade/UP031_0.py`.

<details>
<summary>Existing false negatives that are now true positives</summary>

```
crates/ruff_linter/resources/test/fixtures/pyupgrade/UP031_0.py:134:1: UP031 Use format specifiers instead of percent format
    |
133 | # UP031 (no longer false negatives)
134 | 'Hello %s' % bar
    | ^^^^^^^^^^^^^^^^ UP031
135 |
136 | 'Hello %s' % bar.baz
    |
    = help: Replace with format specifiers

crates/ruff_linter/resources/test/fixtures/pyupgrade/UP031_0.py:136:1: UP031 Use format specifiers instead of percent format
    |
134 | 'Hello %s' % bar
135 |
136 | 'Hello %s' % bar.baz
    | ^^^^^^^^^^^^^^^^^^^^ UP031
137 |
138 | 'Hello %s' % bar['bop']
    |
    = help: Replace with format specifiers

crates/ruff_linter/resources/test/fixtures/pyupgrade/UP031_0.py:138:1: UP031 Use format specifiers instead of percent format
    |
136 | 'Hello %s' % bar.baz
137 |
138 | 'Hello %s' % bar['bop']
    | ^^^^^^^^^^^^^^^^^^^^^^^ UP031
    |
    = help: Replace with format specifiers
```
One of them newly offers a fix.
```
 # UP031 (no longer false negatives)
-'Hello %s' % bar
+'Hello {}'.format(bar)
```
This fix occurs because the new code dereferences `bar` to where it was defined earlier in the file as a non-tuple:
```python
bar = {"bar": y}
```

---

</details>

## Behavior requiring new tests

Additionally, we now handle a few cases that we didn't previously test. These cases are when a string has a single %-placeholder and the righthand operand to the modulo operator is a variable **which can be dereferenced.** One of those was shown in the previous section (the "dereference non-tuple" case).

<details>
<summary>New cases handled</summary>

```
crates/ruff_linter/resources/test/fixtures/pyupgrade/UP031_0.py:126:1: UP031 [*] Use format specifiers instead of percent format
    |
125 | t1 = (x,)
126 | "%s" % t1
    | ^^^^^^^^^ UP031
127 | # UP031: deref t1 to 1-tuple, offer fix
    |
    = help: Replace with format specifiers

crates/ruff_linter/resources/test/fixtures/pyupgrade/UP031_0.py:130:1: UP031 Use format specifiers instead of percent format
    |
129 | t2 = (x,y)
130 | "%s" % t2
    | ^^^^^^^^^ UP031
131 | # UP031: deref t2 to n-tuple, this is a bug
    |
    = help: Replace with format specifiers
```
One of these offers a fix.
```
 t1 = (x,)
-"%s" % t1
+"{}".format(t1[0])
 # UP031: deref t1 to 1-tuple, offer fix
```
The other doesn't offer a fix because it's a bug.

---

</details>

---

</details>

## Changes to existing behavior

In the case of a string with a single %-placeholder and a single ambiguous righthand argument to the modulo operator, (e.g. `"%s" % var`) the rule now fires and offers a fix. We explain about this in the "fix safety" section of the updated documentation.

## Documentation changes

I swapped the order of the "known problems" and the "examples" sections so that the examples which describe the rule are first, before the exceptions to the rule are described. I also tweaked the language to be more explicit, as I had trouble understanding the documentation at first. The "known problems" section is now "fix safety" but the content is largely similar.

The diff of the documentation changes looks a little difficult unless you look at the individual commits.

### CODE REVIEW

File: crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs [hunk 1]
```diff
@@ -286,6 +291,55 @@ fn clean_params_dictionary(right: &Expr, locator: &Locator, stylist: &Stylist) -
...
+                return Some(Cow::Owned(format!("({rt}[0])")));
+            }
+            // non-tuple
+            _ => {
+                return Some(Cow::Owned(format!("({rt})")));
+            }
+        }
+    }
+    // when find_binding_value doesn't work, fall back to offering a fix only for non-tuples
+    if analyze::typing::is_tuple(binding, semantic) {
```
Comment (charliermarsh) [inline crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs:337]: I think this will only return `true` if the value is definitively a tuple, but if the value can't be determined, it _could_ still be a tuple. Imagine, e .g., a function argument with no annotation.

File: crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs [hunk 2]
```diff
@@ -286,6 +291,55 @@ fn clean_params_dictionary(right: &Expr, locator: &Locator, stylist: &Stylist) -
...
+        return None;
+    };
+    let semantic = checker.semantic();
+    let binding_id = semantic.lookup_symbol(id.as_str())?;
+    let binding = semantic.binding(binding_id);
+    let rt = checker.locator().slice(right);
+    if let Some(expr) = analyze::typing::find_binding_value(binding, semantic) {
+        match expr {
+            // n-tuple
+            Expr::Tuple(ast::ExprTuple { elts, .. }) if 1 < elts.len() => {
```
Comment (charliermarsh) [inline crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs:323]: Nit: By convention I'd prefer the constant on the right-hand side of the operator. At first I misread this.

File: crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs (hunk 1 above)
Comment (charliermarsh) [reply crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs:337]: In other words, couldn't the value still be a tuple, even if `is_tuple` returns `false`? I'm actually not sure why we aren't seeing more fixes in the ecosystem checks given this.

File: crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs [hunk 3]
```diff
@@ -286,6 +291,55 @@ fn clean_params_dictionary(right: &Expr, locator: &Locator, stylist: &Stylist) -
...
+///
+/// If the variable is a 1-tuple, then offer `({}[0])`.
+/// ```python
+/// x = (1,)
+/// print("%s" % x)
+/// print("{}".format(x[0]))
+/// ```
+///
+/// If the variable is an n-tuple, the user has a bug in their code. Offer no fix.
+fn clean_params_variable<'a>(checker: &mut Checker, right: &Expr) -> Option<Cow<'a, str>> {
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs:312]: I probably misread this, but isn't the method always returning `Cow::Owned`?

File: crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs (hunk 1 above)
Comment (plredmond) [reply crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs:337]: Yeah, it seems odd. The code using `find_binding_value` should not be suceeding in all cases, so we should be seeing the behavior fall back to `is_tuple` sometimes, and therefore offer that fix (wrongly) in some of those cases. :thinking:

File: crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs (hunk 3 above)
Comment (plredmond) [reply crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs:312]: The method uses `?` syntax to unwrap optionals in at least one place.

Comment (charliermarsh) [reply crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs:312]: I think the suggestion is that this can be `Option<String>`, since you aren't using the `Cow::Borrowed` variant.

File: crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs (hunk 1 above)
Comment (charliermarsh) [reply crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs:337]: Yeah, the behavior is matching my expectation.

```python
zzz = "abc"
'Hello %s' % zzz
```

Here, `find_binding_value` returns a string, so we hit line 332 and still offer a fix.

For cases in which `find_binding_value` returns `None`, like:

```python
zzz = foo()
'Hello %s' % zzz
```

We're also offering a fix, because `analyze::typing::is_tuple` returns `false` there (we don't know if `foo()` is or isn't a tuple).

File: crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs (hunk 3 above)
Comment (plredmond) [reply crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs:312]: Ok! I was cargo culting the `Cow::Borrowed` constructor. Will fix.

File: crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs (hunk 1 above)
Comment (plredmond) [reply crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs:337]: It seems that dereffing the variable and/or trying to analyze its type is not worth the additional code.

Comment (plredmond) [reply crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs:337]: Code won't exist in the next version that I push.

File: crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs (hunk 3 above)
Comment (plredmond) [reply crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs:312]: Code won't exist in the next version that I push.

File: crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs (hunk 2 above)
Comment (plredmond) [reply crates/ruff_linter/src/rules/pyupgrade/rules/printf_string_formatting.rs:323]: Code won't exist in the next version that I push.

**Review by charliermarsh — APPROVED** [review]

**Comment by ThiefMaster** [comment]
Am I the only one who does not like the fact that this even converts `%` formatting in cases where it introduces escaping of literal `{` in the format string/

I mean cases like this:

```diff
 def friendly_name(cls):
-    return '{%s}' % cls.name
+    return f'{{{cls.name}}}'

 def get_regex(cls, **kwargs):
-    return re.compile(r'\{%s}' % re.escape(cls.name))
+    return re.compile(rf'\{{{re.escape(cls.name)}}}')

```

IMHO this is clearly less readable than the previous version.
