### PR TITLE
[syntax-errors] Duplicate type parameter names

### LINKED ISSUE #11119: Ruff fails to detect duplicate type parameter names
This is a SyntaxError:

```
>>> type X[T, T] = int
  File "<stdin>-0", line 1
SyntaxError: duplicate type parameter 'T'
```

But Ruff is fine with it. Similar to #11118.

### PR DESCRIPTION
**Pull request by ntBre**
Summary
--

Detects duplicate type parameter names in function definitions, class
definitions, and type alias statements.

I also boxed the `type_params` field on `StmtTypeAlias` to make it easier to
`match` with functions and classes. (That's the reason for the red-knot code 
owner review requests, sorry!)

Test Plan
--

New `ruff_python_syntax_errors` unit tests.

Fixes #11119.

### CODE REVIEW

**Comment by carljm** [comment]
> (That's the reason for the red-knot code
> owner review requests, sorry!)

No worries! Please don't ever hesitate to change red-knot code for this reason, it's up to us to manage our CODEOWNERS setup and handle the consequences.

File: crates/ruff_python_syntax_errors/src/lib.rs [hunk 1]
```diff
@@ -105,6 +119,35 @@ impl SyntaxChecker {
...
+        let (Stmt::FunctionDef(ast::StmtFunctionDef { type_params, .. })
+        | Stmt::ClassDef(ast::StmtClassDef { type_params, .. })
+        | Stmt::TypeAlias(ast::StmtTypeAlias { type_params, .. })) = stmt
+        else {
+            return;
+        };
+
+        let Some(type_params) = type_params else {
+            return;
+        };
```
Comment (MichaReiser) [inline crates/ruff_python_syntax_errors/src/lib.rs:136]: Not saying that we shouldn't change the definition but you could have written this as
```suggestion
        let type_params = match stmt {
            Stmt::FunctionDef(ast::StmtFunctionDef {
                type_params: Some(type_params),
                ..
            })
            | Stmt::ClassDef(ast::StmtClassDef {
                type_params: Some(type_params),
                ..
            }) => &**type_params,
            Stmt::TypeAlias(ast::StmtTypeAlias {
                type_params: Some(type_params),
                ..
            }) => type_params,
            _ => return,
        };
```

File: crates/ruff_python_syntax_errors/src/lib.rs [hunk 2]
```diff
@@ -105,6 +119,35 @@ impl SyntaxChecker {
...
+
+        for type_param in type_params
+            .iter()
+            .rev()
+            .sorted_by_key(|t| &t.name().id)
+            .dedup_by_with_count(|t1, t2| t1.name().id == t2.name().id)
```
Comment (MichaReiser) [inline crates/ruff_python_syntax_errors/src/lib.rs:142]: From the documentation, it's not clear to me which element `dedup_by_with_count` keeps if multiple elements map to the same key: Is it the first, the last, or any? 

We would want to flag all except the first, which I believe the implementation currently isn't handling (it only flags one).

In which case we probably can't use `dedup_by_with_count` anymore, in which case I would suggest writing this entire check without using itertools (I don't mind it but I also don't love it because it hides allocations)


```rust
if type_params.len() > 1 {
	let mut sorted = type_params.clone();
	sorted.sort_by_key(|t| &*t.name());

	let last_name = None;

	for type_param in sorted {
		if last_name.is_some_and(|last| last == type_param.name()) {
			// push diagnostic
		}
		last_name = Some(type_param.name());
	}
}
```

File: crates/ruff_python_syntax_errors/src/lib.rs [hunk 3]
```diff
@@ -105,6 +119,35 @@ impl SyntaxChecker {
...
+        };
+
+        let Some(type_params) = type_params else {
+            return;
+        };
+
+        for type_param in type_params
+            .iter()
+            .rev()
+            .sorted_by_key(|t| &t.name().id)
```
Comment (MichaReiser) [inline crates/ruff_python_syntax_errors/src/lib.rs:141]: Should we return early if `type_params.len < 2` to avoid the "hidden" allocation in `sorted_by_key`. That should allow us to skip this check for most type params.

File: crates/ruff_python_syntax_errors/src/lib.rs [hunk 4]
```diff
@@ -258,4 +301,15 @@ mod tests {
     fn rebound_comprehension_variable(contents: &str, name: &str) {
         assert_debug_snapshot!(name, test_snippet(contents, PythonVersion::default()));
     }
+
+    #[test_case("type Alias[T, T] = ...", "alias")]
+    #[test_case("def f[T, T](t: T): ...", "function")]
+    #[test_case("class C[T, T]: ...", "class")]
+    #[test_case(
```
Comment (MichaReiser) [inline crates/ruff_python_syntax_errors/src/lib.rs:308]: Let's add a few examples where:

* With more than two duplicate type params
* With non duplicate type params

**Review by MichaReiser — APPROVED** [review]

File: crates/ruff_python_syntax_errors/src/lib.rs [hunk 5]
```diff
@@ -105,6 +119,35 @@ impl SyntaxChecker {
                 });
             }
         }
+
+        self.duplicate_type_parameter_name(stmt);
+    }
+
+    fn duplicate_type_parameter_name(&mut self, stmt: &ast::Stmt) {
```
Comment (dhruvmanila) [inline crates/ruff_python_syntax_errors/src/lib.rs:126]: We might also want to move the duplicate parameter check to the `SyntaxChecker` as that's also a compiler error. Currently, it's done by the parser and raises `ParseError` but the CPython parser does not raise it while parsing:

https://github.com/astral-sh/ruff/blob/c95ecde61ef2cdb85e86de38963326162d004ada/crates/ruff_python_parser/src/parser/statement.rs#L3622-L3639

Maybe we can just use a similar implementation here to avoid the `itertools` usage?

**Review by dhruvmanila — APPROVED** [review]
Looks good

File: crates/ruff_python_syntax_errors/src/lib.rs (hunk 2 above)
Comment (ntBre) [reply crates/ruff_python_syntax_errors/src/lib.rs:142]: Ah that's a good point. I assumed it was taking the first, which is why I reversed the list, but that doesn't handle the case with more than two duplicates. I also felt like I was going overboard with itertools here, so your implementation makes sense to me.

File: crates/ruff_python_syntax_errors/src/lib.rs (hunk 1 above)
Comment (ntBre) [reply crates/ruff_python_syntax_errors/src/lib.rs:136]: For sure, I'm happy with that too if we'd rather not change the generated code.

File: crates/ruff_python_syntax_errors/src/lib.rs (hunk 5 above)
Comment (ntBre) [reply crates/ruff_python_syntax_errors/src/lib.rs:126]: Added it to #11934!

**Comment by ntBre** [comment]
I rebased this onto #16106, added more test cases (and converted them to inline tests), returned early with <2 parameters, and removed itertools.
