### PR TITLE
[`flake8-pyi`] Extend fix to Python <= 3.9 for `redundant-none-literal` (`PYI061`)

### LINKED ISSUE #15795: `redundant-none-literal (PYI061)`: Unsafe or different autofix for Python 3.9
### Description

In https://github.com/astral-sh/ruff/pull/14872, more autofixes were added for `redundant-none-literal (PYI061)`, but it only applies to Python 3.10+ as the `|` may not be usable in annotations in <=3.9 in all cases, even with `from __future__ import annotations`.

I am requesting to either allow the fix on 3.9 and under as an "unsafe" autofix.
OR to autofix using `typing.Union`. And leave the `Union` --> `|` transformation logic to other (`UP`?) rules.

## Current vs expected

The following code:
```py
def get_rotation(rotation: float | Literal[None, "horizontal", "vertical"]) -> float: ...
```
With the following command:
`ruff check --fix --unsafe-fixes --preview --select=PYI061 --isolated --target-version=py39`

### In Ruff 0.9.3:
```
stubs\matplotlib\text.pyi:16:44: PYI061 `Literal[None, ...]` can be replaced with `Literal[...] | None`
   |
14 | from .transforms import Bbox, Transform
15 |
16 | def get_rotation(rotation: float | Literal[None, "horizontal", "vertical"]) -> float: ...
   |                                            ^^^^ PYI061
17 |
18 | class Text(Artist):
   |
   = help: Replace with `Literal[...] | None`

Found 1 error.
```

### I expect:
```
Found 1 error (1 fixed, 0 remaining).
```

Unsafely autofixed to:
```
def get_rotation(rotation: float | Literal["horizontal", "vertical"] | None) -> float: ...
```
Or safely autofixed to:
```
def get_rotation(rotation: float | Union[Literal["horizontal", "vertical"], None]) -> float: ...
```

### PR DESCRIPTION
**Pull request by dylwil3**
This PR extends the fix offered for [redundant-none-literal (PYI061)](https://docs.astral.sh/ruff/rules/redundant-none-literal/#redundant-none-literal-pyi061) to include Python versions <= 3.9 by using `typing.Optional` instead of the operator `|`. We also offer the fix with `|` for any target version on stub files.

Closes #15795

------

For review: 

- I recommend reading the extended commit message for the second commit (where the fix logic is implemented), which hopefully explains the perhaps larger than expected diff.
- Note that the snapshots can still have bit-or operators `|` since we will not remove them if they are already present, e.g. `Literal[None] | int` simplifies to `None | int` regardless of Python version or source type.

### CODE REVIEW

**Comment by AlexWaygood** [comment]
> + [airflow/models/dag.py:1016:36:](https://github.com/apache/airflow/blob/fd606b1d6e1469ebf977e327c947a1d288b5f0d2/airflow/models/dag.py#L1016) PYI061 [*] `Literal[None, ...]` can be replaced with `Union[Literal[...], None]`

Hmmm... wouldn't it be better to suggest `Optional[Literal[...]]` here rather than `Union[Literal[...], None]`? I think most people would consider that more idiomatic on Python <=3.9

File: crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs [hunk 1]
```diff
@@ -189,40 +197,73 @@ fn create_fix_edit(
...
+    match union_kind {
+        UnionKind::TypingUnion => {
+            let (import_edit, bound_name) = checker
+                .importer()
+                .get_or_import_symbol(
+                    &ImportRequest::import_from("typing", "Union"),
+                    literal_expr.start(),
+                    checker.semantic(),
+                )
+                .ok()?;
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs:241]: nit: it would be better to return `anyhow::Result<Fix>` or `anyhow::Result<Option<Fix>>` from this function, do this here, and use `Diagnostic::try_set_fix` or `Diagnostic::try_set_optional_fix` to add the fix to the diagnostic:

```suggestion
            let (import_edit, bound_name) = checker
                .importer()
                .get_or_import_symbol(
                    &ImportRequest::import_from("typing", "Union"),
                    literal_expr.start(),
                    checker.semantic(),
                )?;
```

The advantage is that if you use `try_set_fix` or `try_set_optional_fix`, Ruff will print an error message to the terminal (if you run it with enough `-v` flags) with information from the `ResolutionError` here when this function returns an error. That makes it easier for users or us to debug why Ruff was unable to create an autofix in a specific situation.

File: crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs [hunk 2]
```diff
@@ -36,35 +40,39 @@ use crate::{checkers::ast::Checker, settings::types::PythonVersion};
...
-            "`Literal[None, ...]` can be replaced with `Literal[...] | None`".to_string()
-        } else {
-            "`Literal[None]` can be replaced with `None`".to_string()
+        match self.union_kind {
+            UnionKind::NoUnion => "`Literal[None]` can be replaced with `None`".to_string(),
+            UnionKind::TypingOptional => {
+                "`Literal[None, ...]` can be replaced with `Optional[Literal[...]]`".to_string()
+            }
+            UnionKind::BitOr => {
+                "`Literal[None, ...]` can be replaced with `Literal[...] | None`".to_string()
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs:66]: While we're here, it might be nice to change these so they're a little more imperative:

```suggestion
            UnionKind::NoUnion => "Use `None` rather than `Literal[None]`".to_string(),
            UnionKind::TypingOptional => {
                "Use `Optional[Literal[...]]` rather than `Literal[None, ...]`".to_string()
            }
            UnionKind::BitOr => {
                "Use `Literal[...] | None` rather than `Literal[None, ...]`".to_string()
```

File: crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs [hunk 3]
```diff
@@ -185,44 +192,74 @@ fn create_fix_edit(
...
+                parenthesized: true,
+            })
+        } else {
+            literal_elements[0].clone()
+        }),
     });
 
-    let content = checker.generator().expr(&bin_or);
-    Some(Edit::range_replacement(content, literal_expr.range()))
+    match union_kind {
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs:228]: ignorable nit (just my stylistic preference!) -- you could reduce some duplication between the branches here:

```diff
diff --git a/crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs b/crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs
index 2f5e892d0..ddaa51ac8 100644
--- a/crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs
+++ b/crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs
@@ -225,7 +225,7 @@ fn create_fix(
         }),
     });
 
-    match union_kind {
+    let fix = match union_kind {
         UnionKind::TypingOptional => {
             let (import_edit, bound_name) = checker.importer().get_or_import_symbol(
                 &ImportRequest::import_from("typing", "Optional"),
@@ -235,11 +235,7 @@ fn create_fix(
             let optional_expr = typing_optional(new_literal_expr, Name::from(bound_name));
             let content = checker.generator().expr(&optional_expr);
             let optional_edit = Edit::range_replacement(content, literal_expr.range());
-            Ok(Some(Fix::applicable_edits(
-                import_edit,
-                [optional_edit],
-                applicability,
-            )))
+            Fix::applicable_edits(import_edit, [optional_edit], applicability)
         }
         UnionKind::BitOr => {
             let none_expr = Expr::NoneLiteral(ExprNoneLiteral {
@@ -248,13 +244,15 @@ fn create_fix(
             let union_expr = pep_604_union(&[new_literal_expr, none_expr]);
             let content = checker.generator().expr(&union_expr);
             let union_edit = Edit::range_replacement(content, literal_expr.range());
-            Ok(Some(Fix::applicable_edit(union_edit, applicability)))
+            Fix::applicable_edit(union_edit, applicability)
         }
         // We dealt with this case earlier to avoid allocating `lhs` and `rhs`
         UnionKind::NoUnion => {
             unreachable!()
         }
-    }
+    };
+
+    Ok(Some(fix))
 }
```

File: crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs [hunk 4]
```diff
@@ -185,44 +192,74 @@ fn create_fix_edit(
...
+            Ok(Some(Fix::applicable_edit(union_edit, applicability)))
+        }
+        // We dealt with this case earlier to avoid allocating `lhs` and `rhs`
+        UnionKind::NoUnion => {
+            unreachable!()
+        }
+    }
+}
+
+#[derive(Copy, Clone)]
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/redundant_none_literal.rs:260]: I tend to add these to simple enums like this, because you never know when they might be useful in tests or debug prints

```suggestion
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
```

**Review by AlexWaygood — APPROVED** [review]
Excellent, thank you!
