### PR TITLE
[`ruff`] Unnecessary rounding (`RUF057`)

### LINKED ISSUE #14793: `RUF046` is doing two things instead of one
I know that 0.8.2 has just been released and that I did say everything looked fine to me before #14697 was merged, but the more I think about it, the more I find it wrong to handle both `round()` and `int()` in one fell swoop. I probably won't be able to sleep well tonight without first sharing my concerns, so here's the big proposal:

`RUF046` should only handle cases where the `int()` call is unnecessary. The logic to detect `round()` calls with unnecessary second argument should be moved to a new rule.

This will also make it easier to extend `RUF046` to handle expressions more complex than a simple call, as it won't need to care about the exact content.

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
## Summary

Resolves #14793.

## Test Plan

`cargo nextest run` and `cargo insta test`.

### CODE REVIEW

**Comment by MichaReiser** [comment]
Thanks for following up on this! 

Would you mind splitting the PR into two if it isn't too much work:

1. Changes the existing rule
2. Adding the new rule

Two separate PRs have the advantage that we can list the two changes separately in the changelog.

**Comment by MichaReiser** [comment]
Yeah, that's a bit annoying. However, I just skimmed over the changes, and there's too much going on in this PR, which makes it difficult for me and future readers to understand what it is about. 

I suggest you split it into:

1. Scope change of `RUF046`
2.. Improving the integer inference of `RUF046`
3. Adding the new `RUF057`

I'd suggest you start with one PR and then submit the next once that is merged. Or you can create stacked PRs, but they can be a bit painful when it comes to rebasing them.

**Comment by MichaReiser** [comment]
Thank you.

Hmm. This is not the rule I expected. From our conversation in #14973 I'd expected a rule that detects unnecessary `round` calls rather than unnecessary `ndigits`. 

E.g. `round(5)` should be converted to just `5`. The same for `round(5, None)`

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_rounding.rs [hunk 1]
```diff
@@ -0,0 +1,186 @@
...
+pub(crate) struct UnnecessaryRounding;
+
+impl AlwaysFixableViolation for UnnecessaryRounding {
+    #[derive_message_formats]
+    fn message(&self) -> String {
+        "Value being rounded is already an integer".to_string()
+    }
+
+    fn fix_title(&self) -> String {
+        "Remove unnecessary rounding".to_string()
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/unnecessary_rounding.rs:36]:
```suggestion
        "Remove unnecessary `round` call".to_string()
```

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_rounding.rs [hunk 2]
```diff
@@ -0,0 +1,186 @@
...
+
+/// The type of the first argument to `round()`
+#[derive(Clone, Copy, Debug, Eq, PartialEq)]
+pub(super) enum RoundedKind {
+    LiteralInt,
+    LiteralFloat,
+    ResolvedInt,
+    ResolvedFloat,
+    InferredInt,
+    InferredFloat,
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/unnecessary_rounding.rs:90]: Can you tell me more about the motivation for distinguishing between `ResolvedInt` and `InferredInt`? I think this is also worth documenting because it's not obvious to readers why the distinction is necessary. 

It might be better to have more semantic names rather than the source  because both `typing::int` and `ResolvedPythonType` are doing type inference, which makes `InferredInt` rather confusing

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_rounding.rs [hunk 3]
```diff
@@ -0,0 +1,186 @@
...
+use ruff_python_ast::{Arguments, Expr, ExprCall, ExprNumberLiteral, Number};
+use ruff_python_semantic::analyze::type_inference::{NumberLike, PythonType, ResolvedPythonType};
+use ruff_python_semantic::analyze::typing;
+use ruff_text_size::Ranged;
+
+/// ## What it does
+/// Checks for `round()` calls that have no effect on the input.
+///
+/// ## Why is this bad?
+/// The unnecessary call may make the code less readable.
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/unnecessary_rounding.rs:13]: Rounding a value that's already an integer is unnecessary. It's more clear to use the value directly.

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_rounding.rs [hunk 4]
```diff
@@ -0,0 +1,186 @@
...
+/// a = round(1, 0)
+/// ```
+///
+/// Use instead:
+///
+/// ```python
+/// a = 1
+/// ```
+#[derive(ViolationMetadata)]
+pub(crate) struct UnnecessaryRounding;
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/unnecessary_rounding.rs:27]: I'm leaning towards naming the method `UnnecessaryRound`

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_rounding.rs (hunk 2 above)
Comment (MichaReiser) [reply crates/ruff_linter/src/rules/ruff/rules/unnecessary_rounding.rs]: As a reader, I still wonder what the difference between `InferredInt` and `ResolvedInt` is. I think we should rename the variants or add documentation (the best option is probably to do both). 

Can you share an example where `InferredInt` returns `true` for something that shouldn't be an `int`? Is it because booleans are assignable to `int`: 

E.g. this is fine according to pyright

```python
def test(a: int) -> int:
    return a

test(True)  # Returns `True`
```

But `round(True)` evaluates to `1`

```
>>> round(True)
1
```

Are there more cases like this? If not, then how about renaming the `InferredInt` variant to `AnnotatedInt` or `Int` vs `LiteralInt` with a comment saying that one is equivalent to an `:int` annotation and the other `Literal[int]`?

Comment (MichaReiser) [reply crates/ruff_linter/src/rules/ruff/rules/unnecessary_rounding.rs]: Thanks for adding some documentation. I did read it, but I'm not sure it's very helpful because it only documents what's already apparent from the code. What's unclear to a reader is why the distinction is important. The names are also somewhat confusing, as you mentioned in your last comment. For example, `LiteralInt` doesn't mean that it's a `Literal`; it could also be a complex expression. 

I still only have a limited understanding but my impression is that the variants for `RoundKind` are all about *how likely the expression is an `int`*. Or possibly whether the value is equivalent to `int` or only assignable to int. How about we introduce a new enum to `InferedType` with the variants `Equivalent` (it's exactly `int`), and `AssignableTo` (5 or `True`). `RoundKind` then has the variants `Int(InferredType)`, `Float(InferredType)`, and `Other` and `NdigitsKind` has `Absent`, `LiteralNone`, `Int(InferredType)`, and `Other`. 

We can then add documentation to where we construct the `InferredType` why e.g. `typing::is_int` is `InferredType::AssignableTo` and why `ResolvedPythonType` is `Equivalent`

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_round.rs [hunk 5]
```diff
@@ -0,0 +1,189 @@
...
+    else {
+        return;
+    };
+
+    if matches!(ndigits_kind, NdigitsKind::Other) {
+        return;
+    }
+
+    let applicability = match (rounded_kind, ndigits_kind) {
+        (RoundedKind::Int(InferredType::Equivalent), _) => Applicability::Safe,
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/unnecessary_round.rs:59]: Some examples will help future readers

```suggestion
				// ```python
        // round(3)
        // round(3, 0)
        // round(3, ..)
        // ```
        (RoundedKind::Int(InferredType::Equivalent), _) => Applicability::Safe,
```

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_round.rs [hunk 6]
```diff
@@ -0,0 +1,189 @@
...
+
+        (
+            RoundedKind::Float(InferredType::Equivalent),
+            NdigitsKind::NotGiven | NdigitsKind::LiteralNone,
+        ) => Applicability::Safe,
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/unnecessary_round.rs:64]: It's not clear to me why the round call should be unnecessary if the value is a float:

```
>>> round(3.0)
3
>>> 3.0
3.0
```

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_round.rs [hunk 7]
```diff
@@ -0,0 +1,189 @@
...
+
+        (RoundedKind::Int(InferredType::AssignableTo), _) => Applicability::Unsafe,
+
+        (
+            RoundedKind::Float(InferredType::AssignableTo),
+            NdigitsKind::NotGiven | NdigitsKind::LiteralNone,
+        ) => Applicability::Unsafe,
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/unnecessary_round.rs:71]: Same here, i don't think we can ever remove round calls if the value is a `float`.

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_round.rs [hunk 8]
```diff
@@ -0,0 +1,189 @@
...
+pub(super) fn rounded_and_ndigits<'a>(
+    checker: &Checker,
+    arguments: &'a Arguments,
+) -> Option<(&'a Rounded, RoundedKind, NdigitsKind)> {
+    if arguments.len() > 2 {
+        return None;
+    }
+
+    let rounded = arguments.find_argument("number", 0)?.value();
+    let ndigits = arguments.find_argument("ndigits", 1).map(|it| it.value());
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/unnecessary_round.rs:122]:
```suggestion
    let rounded = arguments.find_argument_value("number", 0)?;
    let ndigits = arguments.find_argument_value("ndigits", 1);
```

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_round.rs [hunk 9]
```diff
@@ -0,0 +1,189 @@
...
+pub(super) enum InferredType {
+    /// The value is an exact instance of the type in question.
+    Equivalent,
+    /// The value is an instance of the type in question or a subtype thereof.
+    AssignableTo,
+}
+
+/// The type of the first argument to `round()`
+#[derive(Clone, Copy, Debug, Eq, PartialEq)]
+pub(super) enum RoundedKind {
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/unnecessary_round.rs:94]: Nit: Rename to `RoundedValue`

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_round.rs [hunk 10]
```diff
@@ -0,0 +1,189 @@
...
+    Int(InferredType),
+    Float(InferredType),
+    Other,
+}
+
+/// The type of the second argument to `round()`
+#[derive(Clone, Copy, Debug, Eq, PartialEq)]
+pub(super) enum NdigitsKind {
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/unnecessary_round.rs:102]: Rename to `NdigitsValue`. Value is somewhat more specific than `Kind`

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_round.rs [hunk 11]
```diff
@@ -0,0 +1,189 @@
...
+use ruff_python_semantic::analyze::type_inference::{NumberLike, PythonType, ResolvedPythonType};
+use ruff_python_semantic::analyze::typing;
+use ruff_text_size::Ranged;
+
+/// ## What it does
+/// Checks for `round()` calls that have no effect on the input.
+///
+/// ## Why is this bad?
+/// Rounding a value that's already an integer is unnecessary.
+/// It's more clear to use the value directly.
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/unnecessary_round.rs:14]:
```suggestion
/// It's clearer to use the value directly.
```

File: crates/ruff_linter/resources/test/fixtures/ruff/RUF057.py [hunk 12]
```diff
@@ -0,0 +1,59 @@
...
+inferred_float = 1.
+
+
+
+round(42)                                         # Error (safe)
+round(42, None)                                   # Error (safe)
+round(42, 2)                                      # Error (safe)
+round(42, inferred_int)                           # Error (safe)
+round(42, 3 + 4)                                  # Error (safe)
+round(42, foo)                                    # No error
```
Comment (MichaReiser) [inline crates/ruff_linter/resources/test/fixtures/ruff/RUF057.py:11]: Should we make this an error too if the value is known to be equivalent to an int? The only semantic change that I could see is that `round` no longer throws if `foo` isn't an int. But we could make the fix unsafe to account for this.

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_round.rs [hunk 13]
```diff
@@ -0,0 +1,196 @@
...
+/// The type of the second argument to `round()`
+#[derive(Clone, Copy, Debug, Eq, PartialEq)]
+pub(super) enum NdigitsValue {
+    NotGiven,
+    LiteralNone,
+    Int(InferredType),
+    Other,
+}
+
+type Rounded = Expr;
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/unnecessary_round.rs]: I removed the type alias because it wasn't used consistently and I found it more confusing than helpful (I had to lookup what its type is). In this case, I think adding some documentation might be more helpful

**Review by MichaReiser — APPROVED** [review]
Thanks and happy new year. This is looking great. I've one last comment on where I think the rule should flag a `round` call but currently isn't. I'm interested in why you chose to not flag that `round` call site.
