### PR TITLE
[`ruff`] Avoid emitting `assignment-in-assert` when all references to the assigned variable are themselves inside `assert`s (`RUF018`)

### LINKED ISSUE #14658: `RUF018` false positive. Assignment for variables only used in other asserts
`RUF018` flags any asserts which assigns values in them, which is sensible. However, there are two cases where value assignment is actually fine, and even makes the code more readable. This rule is to prevent code breakages when asserts are disabled. I ran it on the sympy code and found two use cases that make sense.

```python
    assert (t:=cancel((F, G))) == (1, P, Q)
    assert isinstance(t, tuple)
```

Here this is using a variable which is ONLY referenced in other assert expressions. There is no clean way to write this compound assert without knowing what assert failed, without storing the variable t in a temporary variable. Furthermore, the`t:=` may be expensive construct, we may only want to assign this variable when asserts are enabled.

The other less useful, but interesting case is using the assert expression in the error message of the assert. See here:
```python
     assert (g:=solve(groebner(eqs, s), dict=True)) == sol, g
```
without this, the value has to be repeated to know what `g` actually is in this context, or it needs to be assigned to a temporary variable which may be constructed when asserts are also disabled. `g` should be cast to a string, but that is a fix for another rule`

### PR DESCRIPTION
**Pull request by AlexWaygood**
## Summary

Fixes #14658.

The stated rationale for RUF018 is that it's unsafe to assign a variable using an assignment expression inside an `assert` statement, because if you run Python in optimised mode the assertion might be stripped out of the program at compilation time, meaning the variable is never actually defined. This concern is irrelevant, however, if the variable is only ever read from inside other `assert` statements: either all `assert` statements will be stripped from the Python program, or none will be. This PR therefore moves the rule to `bindings.rs` and modifies the rule so that it iterates through all references to the binding introduced by the assignment expression to see whether those references take place inside `assert` statements or not.

In order to determine whether a `Binding` or `ResolvedReference` took place inside an `assert` statement, it's necessary to add `SemanticModelFlags::ASSERT_STATEMENT` and `BindingFlags::IN_ASSERT_STATEMENT` to Ruff's semantic model.

## Test Plan

New fixtures added. `cargo test -p ruff_linter --lib`.

### CODE REVIEW

**Comment by AlexWaygood** [comment]
The ecosystem hits all look good to me

File: crates/ruff_linter/src/checkers/ast/analyze/bindings.rs [hunk 1]
```diff
@@ -87,5 +88,10 @@ pub(crate) fn bindings(checker: &mut Checker) {
                 checker.diagnostics.push(diagnostic);
             }
         }
+        if checker.enabled(Rule::AssignmentInAssert) {
+            if let Some(diagnostic) = ruff::rules::assignment_in_assert(checker, binding) {
+                checker.diagnostics.push(diagnostic);
+            }
+        }
```
Comment (dhruvmanila) [inline crates/ruff_linter/src/checkers/ast/analyze/bindings.rs:95]: Should we just update the `diagnostics` vector inside the rule logic to avoid doing this here? We usually do that in other rules.

File: crates/ruff_python_semantic/src/binding.rs [hunk 2]
```diff
@@ -266,6 +275,14 @@ impl<'a> Binding<'a> {
...
     }
 
+    /// Returns the parent of the expression in which the binding was defined.
+    ///
+    /// This is only really applicable for assignment expressions.
+    pub fn parent_expression<'b>(&self, semantic: &SemanticModel<'b>) -> Option<&'b ast::Expr> {
+        self.source
+            .and_then(|expression_id| semantic.parent_expression(expression_id))
+    }
+
```
Comment (dhruvmanila) [inline crates/ruff_python_semantic/src/binding.rs:285]: Should this method be just `expression` instead? Considering `assert (x := 1)`, for the binding `x` this would return the named expression, right? If so, shouldn't that be the "expression in which the binding was defined" (similar to the `statement` method)?

Comment (AlexWaygood) [reply crates/ruff_python_semantic/src/binding.rs:285]: Yeah, that makes sense. I named it like this because the implementation is more similar to `Binding::parent_statement()` than to `Binding::statement()`. That's because `self.source.and_then(|expression_id| semantic.expression(expression_id))` will give you the `ast::Expr::Name()` that represents the symbol `x` rather than the `ast::Expr::Named()` that represents the `x := 1` walrus. But I don't think you ever really want the `ast::Expr::Name` node (you can get the range directly from the `Binding`), so your naming is likely more intuitive for users of the API.

File: crates/ruff_linter/src/checkers/ast/analyze/bindings.rs (hunk 1 above)
Comment (AlexWaygood) [reply crates/ruff_linter/src/checkers/ast/analyze/bindings.rs:95]: We do that for most rules in `expressions.rs` and `statement.rs`, but we don't do that for any rules in `bindings.rs` for some reason. I'm happy to look separately into whether we should change the structure of these rules to make them more consistent with the majority of other AST-based rules, but for now I think local consistency within this file probably wins.

Comment (dhruvmanila) [reply crates/ruff_linter/src/checkers/ast/analyze/bindings.rs:95]: Oh, that's fine then, no need to spend any more time here.

**Review by dhruvmanila — APPROVED** [review]
Thanks!
