### PR TITLE
[`perflint`] Fix false negative in `PERF401`

### LINKED ISSUE #18859: Rule `manual_dict_comprehension` cause panic `for-loop target binding must exist` (probably PERF403 - debug assert)
### Summary

File content(at the bottom should be attached raw, not formatted file - github removes some non-printable characters, so copying from here may not work):
```
for o,(x,)in():v[x,]=o
```

command
```
timeout -v 300 ruff check TEST___FILE.py --select ALL --preview --output-format concise --no-cache --fix --unsafe-fixes --isolated
```

App was compiled with nightly rust compiler to be able to use address sanitizer
(You can ignore this part if there is no address sanitizer error)
On Ubuntu 24.04, the commands to compile were:
```
rustup default nightly
rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
rustup component add llvm-tools-preview --toolchain nightly-x86_64-unknown-linux-gnu

export RUST_BACKTRACE=1 # or full depending on project
export ASAN_SYMBOLIZER_PATH=$(which llvm-symbolizer-18)
export ASAN_OPTIONS=symbolize=1
RUSTFLAGS="-Zsanitizer=address" cargo +nightly build --target x86_64-unknown-linux-gnu
```

cause this
```
All checks passed!

warning: `incorrect-blank-line-before-class` (D203) and `no-blank-line-before-class` (D211) are incompatible. Ignoring `incorrect-blank-line-before-class`.
warning: `multi-line-summary-first-line` (D212) and `multi-line-summary-second-line` (D213) are incompatible. Ignoring `multi-line-summary-second-line`.
error: Panicked while linting /opt/BROKEN_FILES_DIR/926_IDX_0_RAND_553482853979823657879343_minimized_997.py: This indicates a bug in Ruff. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BLinter%20panic%5D

...with the relevant file contents, the `pyproject.toml` settings, and the following stack trace, we'd be very appreciative!

panicked at crates/ruff_linter/src/rules/perflint/rules/manual_dict_comprehension.rs:149:9:
for-loop target binding must exist
Backtrace:    0: ruff_db::panic::install_hook::{{closure}}::{{closure}}
             at ./ruff-main/crates/ruff_db/src/panic.rs:91:34
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/d4e1159b8c97478778b09a4cc1c7adce5653b8bf/library/alloc/src/boxed.rs:1980:9
   2: std::panicking::rust_panic_with_hook
             at /rustc/d4e1159b8c97478778b09a4cc1c7adce5653b8bf/library/std/src/panicking.rs:841:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/d4e1159b8c97478778b09a4cc1c7adce5653b8bf/library/std/src/panicking.rs:699:13
   4: std::sys::backtrace::__rust_end_short_backtrace
             at /rustc/d4e1159b8c97478778b09a4cc1c7adce5653b8bf/library/std/src/sys/backtrace.rs:168:18
   5: __rustc::rust_begin_unwind
             at /rustc/d4e1159b8c97478778b09a4cc1c7adce5653b8bf/library/std/src/panicking.rs:697:5
   6: core::panicking::panic_fmt
             at /rustc/d4e1159b8c97478778b09a4cc1c7adce5653b8bf/library/core/src/panicking.rs:75:14
   7: ruff_linter::rules::perflint::rules::manual_dict_comprehension::manual_dict_comprehension::{{closure}}
             at ./ruff-main/crates/ruff_linter/src/rules/perflint/rules/manual_dict_comprehension.rs:149:9
   8: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::any
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/iter/macros.rs:308:24
   9: ruff_linter::rules::perflint::rules::manual_dict_comprehension::manual_dict_comprehension
             at ./ruff-main/crates/ruff_linter/src/rules/perflint/rules/manual_dict_comprehension.rs:180:29
  10: ruff_linter::checkers::ast::analyze::deferred_for_loops::deferred_for_loops
             at ./ruff-main/crates/ruff_linter/src/checkers/ast/analyze/deferred_for_loops.rs:39:17
  11: ruff_linter::checkers::ast::check_ast
             at ./ruff-main/crates/ruff_linter/src/checkers/ast/mod.rs:3093:5
  12: ruff_linter::linter::check_path
             at ./ruff-main/crates/ruff_linter/src/linter.rs:229:39
  13: ruff_linter::linter::lint_fix
             at ./ruff-main/crates/ruff_linter/src/linter.rs:639:27
  14: ruff::diagnostics::lint_path
             at ./ruff-main/crates/ruff/src/diagnostics.rs:268:18
  15: ruff::commands::check::lint_path::{{closure}}
             at ./ruff-main/crates/ruff/src/commands/check.rs:192:9
  16: std::panicking::catch_unwind::do_call
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:589:40
  17: __rust_try
  18: std::panicking::catch_unwind
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:19
  19: std::panic::catch_unwind
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:359:14
  20: ruff_db::panic::catch_unwind
             at ./ruff-main/crates/ruff_db/src/panic.rs:122:18
  21: ruff::commands::check::lint_path
             at ./ruff-main/crates/ruff/src/commands/check.rs:191:18
  22: ruff::commands::check::check::{{closure}}
             at ./ruff-main/crates/ruff/src/commands/check.rs:94:17
  23: <rayon::iter::filter_map::FilterMapFolder<C,P> as rayon::iter::plumbing::Folder<T>>::consume
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-1.10.0/src/iter/filter_map.rs:123:36
  24: rayon::iter::plumbing::Folder::consume_iter
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-1.10.0/src/iter/plumbing/mod.rs:178:25
  25: rayon::iter::plumbing::Producer::fold_with
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-1.10.0/src/iter/plumbing/mod.rs:109:16
  26: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-1.10.0/src/iter/plumbing/mod.rs:437:22
  27: rayon::iter::plumbing::bridge_producer_consumer
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-1.10.0/src/iter/plumbing/mod.rs:396:12
  28: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-1.10.0/src/iter/plumbing/mod.rs:372:13
  29: <rayon::slice::Iter<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-1.10.0/src/slice/mod.rs:826:18
  30: rayon::iter::plumbing::bridge
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-1.10.0/src/iter/plumbing/mod.rs:356:21
  31: <rayon::slice::Iter<T> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-1.10.0/src/slice/mod.rs:802:9
  32: <rayon::iter::filter_map::FilterMap<I,P> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-1.10.0/src/iter/filter_map.rs:46:19
  33: <rayon::iter::fold::Fold<I,ID,F> as rayon::iter::ParallelIterator>::drive_unindexed
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-1.10.0/src/iter/fold.rs:59:19
  34: rayon::iter::reduce::reduce
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-1.10.0/src/iter/reduce.rs:15:8
  35: rayon::iter::ParallelIterator::reduce
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-1.10.0/src/iter/mod.rs:998:9
  36: ruff::commands::check::check
             at ./ruff-main/crates/ruff/src/commands/check.rs:164:10
  37: ruff::check
             at ./ruff-main/crates/ruff/src/lib.rs:420:13
  38: ruff::run
             at ./ruff-main/crates/ruff/src/lib.rs:198:33
  39: ruff::main
             at ./ruff-main/crates/ruff/src/main.rs:45:11
  40: core::ops::function::FnOnce::call_once
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  41: std::sys::backtrace::__rust_begin_short_backtrace
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:152:18
  42: std::rt::lang_start::{{closure}}
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:206:18
  43: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/d4e1159b8c97478778b09a4cc1c7adce5653b8bf/library/core/src/ops/function.rs:284:21
  44: std::panicking::catch_unwind::do_call
             at /rustc/d4e1159b8c97478778b09a4cc1c7adce5653b8bf/library/std/src/panicking.rs:589:40
  45: std::panicking::catch_unwind
             at /rustc/d4e1159b8c97478778b09a4cc1c7adce5653b8bf/library/std/src/panicking.rs:552:19
  46: std::panic::catch_unwind
             at /rustc/d4e1159b8c97478778b09a4cc1c7adce5653b8bf/library/std/src/panic.rs:359:14
  47: std::rt::lang_start_internal::{{closure}}
             at /rustc/d4e1159b8c97478778b09a4cc1c7adce5653b8bf/library/std/src/rt.rs:175:24
  48: std::panicking::catch_unwind::do_call
             at /rustc/d4e1159b8c97478778b09a4cc1c7adce5653b8bf/library/std/src/panicking.rs:589:40
  49: std::panicking::catch_unwind
             at /rustc/d4e1159b8c97478778b09a4cc1c7adce5653b8bf/library/std/src/panicking.rs:552:19
  50: std::panic::catch_unwind
             at /rustc/d4e1159b8c97478778b09a4cc1c7adce5653b8bf/library/std/src/panic.rs:359:14
  51: std::rt::lang_start_internal
             at /rustc/d4e1159b8c97478778b09a4cc1c7adce5653b8bf/library/std/src/rt.rs:171:5
  52: std::rt::lang_start
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:205:5
  53: <unknown>
  54: __libc_start_main
  55: _start



##### Automatic Fuzzer note, output status "Some(0)", output signal "None"
```

[compressed.zip](https://github.com/user-attachments/files/20852923/compressed.zip)

### Version

90894932634fe58bd26bb7a586a969383bc49b29

### PR DESCRIPTION
**Pull request by LaBatata101**
## Summary
This PR also fixes a false negative for the following case:
```python
for o,(x,)in():
    v[x,]=o
``` 
The code didn't consider the case of inner tuples in the `for` target.

And finally, the autofix would create a invalid syntax if the subscript expression had a tuple in the slice.

Fixes #18859

## Test Plan
Add regression test

### CODE REVIEW

File: crates/ruff_linter/src/rules/perflint/rules/manual_dict_comprehension.rs [hunk 1]
```diff
@@ -177,11 +172,15 @@ pub(crate) fn manual_dict_comprehension(checker: &Checker, for_stmt: &ast::StmtF
                 return;
             }
             // Make sure none of the variables are used outside the for loop
-            if tuple.iter().any(any_references_after_for_loop) {
+            if tuple
+                .iter()
+                .filter_map(|expr| expr.as_name_expr())
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/perflint/rules/manual_dict_comprehension.rs]: I'm not sure this fix is correct. Shouldn't we also skip the rule if any nested name is used after the loop? E.g. when the name is inside a nested tuple or similar. 

That's why I think we either need to apply the check recursively or bail in more cases.

File: crates/ruff_linter/src/rules/perflint/rules/manual_dict_comprehension.rs [hunk 2]
```diff
@@ -140,18 +140,13 @@ pub(crate) fn manual_dict_comprehension(checker: &Checker, for_stmt: &ast::StmtF
...
-            target_binding.is_some(),
-            "for-loop target binding must exist"
-        );
-
-        let Some(target_binding) = target_binding else {
+            .find(|binding| target.range() == binding.range)
+        else {
             // All uses of this function will early-return if this returns true, so this must early-return the rule
             return true;
         };
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/perflint/rules/manual_dict_comprehension.rs]: Nit: I would move this all into `has_post_loop_references`:

```rust
fn has_post_loop_references(checker: &Checker, expr: &Expr, loop_end: TextSize) -> bool {
    match expr {
        Expr::Tuple(ast::ExprTuple { elts, .. }) => elts
            .iter()
            .any(|expr| has_post_loop_references(checker, expr, loop_end)),
        Expr::Name(name) => {
            let target_binding = checker
                .semantic()
                .bindings
                .iter()
                .find(|binding| name.range() == binding.range)
                .expect("for-loop target binding must exist");

            target_binding
                .references()
                .map(|reference| checker.semantic().reference(reference))
                .any(|other_reference| other_reference.start() > loop_end)
        }
        _ => false,
    }
}
```

File: crates/ruff_linter/src/rules/perflint/rules/manual_dict_comprehension.rs [hunk 3]
```diff
@@ -177,11 +172,11 @@ pub(crate) fn manual_dict_comprehension(checker: &Checker, for_stmt: &ast::StmtF
                 return;
             }
             // Make sure none of the variables are used outside the for loop
-            if tuple.iter().any(any_references_after_for_loop) {
+            if has_post_loop_references(target, &any_references_after_for_loop) {
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/perflint/rules/manual_dict_comprehension.rs]: We can now move this check above the match statement because `has_post_loop_references` takes any `Expr`

File: crates/ruff_linter/src/rules/perflint/rules/manual_dict_comprehension.rs [hunk 4]
```diff
@@ -473,3 +477,16 @@ enum DictComprehensionType {
     Update,
     Comprehension,
 }
+
+fn has_post_loop_references<F>(expr: &Expr, any_references_after_for_loop: &F) -> bool
+where
+    F: Fn(&ast::ExprName) -> bool,
+{
+    match expr {
+        Expr::Tuple(ast::ExprTuple { elts, .. }) => elts
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/perflint/rules/manual_dict_comprehension.rs:461]: I think this method is still incorrect because it doesn't traverse into arbitrary expressions. Instead, we should use `any_over_expr` and only check `ExprName` in load contexts.

For example:

```py
a = []
b = [10]
x = 0
 
for (a, b[x]) in [(1, 2)]: pass

x = 10
```

File: crates/ruff_linter/src/rules/perflint/snapshots/ruff_linter__rules__perflint__tests__preview__PERF403_PERF403.py.snap [hunk 5]
```diff
@@ -351,3 +353,24 @@ PERF403.py:166:13: PERF403 [*] Use `dict.update` instead of a for-loop
 165     |-        if lambda: 0:
 166     |-            dst[k] = v
     164 |+    dst.update({k: v for k, v in src if (lambda: 0)})
+167 165 | 
+168 166 | # https://github.com/astral-sh/ruff/issues/18859
+169 167 | def foo():
+
+PERF403.py:172:9: PERF403 [*] Use a dictionary comprehension instead of a for-loop
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/perflint/snapshots/ruff_linter__rules__perflint__tests__preview__PERF403_PERF403.py.snap:360]: This PR does seem to change the rules that get reported because this wasn't a violation before (when building in release build)

File: crates/ruff_linter/src/rules/perflint/rules/manual_dict_comprehension.rs [hunk 6]
```diff
@@ -380,9 +375,18 @@ fn convert_to_dict_comprehension(
     } else {
         "for"
     };
+    // Handles the case where `key` has a trailing comma, e.g, `dict[x,] = y`
+    let key_range = if let Expr::Tuple(ast::ExprTuple { elts, .. }) = key {
+        let [expr] = elts.as_slice() else {
+            return None;
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/perflint/rules/manual_dict_comprehension.rs:359]: Instead of bailing here, should the rule still be triggered but without providing a fix?

**Review by MichaReiser — COMMENTED** [review]
I've a few more questions and a refactor suggestion

File: crates/ruff_linter/src/rules/perflint/rules/manual_dict_comprehension.rs (hunk 6 above)
Comment (LaBatata101) [reply crates/ruff_linter/src/rules/perflint/rules/manual_dict_comprehension.rs:359]: It only bails if the slice has more than one expression. I think the rule doesn't apply for slices with more than one expression.

File: crates/ruff_linter/src/rules/perflint/snapshots/ruff_linter__rules__perflint__tests__preview__PERF403_PERF403.py.snap (hunk 5 above)
Comment (LaBatata101) [reply crates/ruff_linter/src/rules/perflint/snapshots/ruff_linter__rules__perflint__tests__preview__PERF403_PERF403.py.snap:360]: Are you talking about the ecosystem changes? If so, It doesn't make sense for `RUF043` to be triggering here, it doesn't make use of code changed in this PR.

Comment (MichaReiser) [reply crates/ruff_linter/src/rules/perflint/snapshots/ruff_linter__rules__perflint__tests__preview__PERF403_PERF403.py.snap:360]: No, I'm saying that this specific example wasn't a violation on main, see https://play.ruff.rs/7408fd27-bd76-4559-a83c-934959b8e498. That means that this PR does more than just fix a panic, it also extends the scope of the rule to support nested tuples

Comment (LaBatata101) [reply crates/ruff_linter/src/rules/perflint/snapshots/ruff_linter__rules__perflint__tests__preview__PERF403_PERF403.py.snap:360]: Oh right,  now I see what you meant.

**Comment by MichaReiser** [comment]
Thank you
