### PR TITLE
Avoid duplicating linter-formatter compatibility warnings

### LINKED ISSUE #8271: Ruff format conflict warnings are shown twice
Happening since ruff format stable was introduced afaik.

Tested on ruff `0.1.3`:

**Reproduction steps:**

Create a python project with ruff, minimal config:

```python
[tool.ruff]
select = ["ISC001"]
```

Run `ruff format src`

The warning is showing twice in the console:

```
warning: The following rules may cause conflicts when used with the formatter: `ISC001`. To avoid unexpected behavior, we recommend disabling these rules, either by removing them from the `select` or `extend-select` configuration, or adding then to the `ignore` configuration.
warning: The following rules may cause conflicts when used with the formatter: `ISC001`. To avoid unexpected behavior, we recommend disabling these rules, either by removing them from the `select` or `extend-select` configuration, or adding then to the `ignore` configuration.
```

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Uses `warn_user_once!` instead of `warn!` to ensure that every warning is shown exactly once, regardless of whether there are duplicates in the list, or warnings that are raised by multiple configuration files.

Closes #8271.

### CODE REVIEW

File: crates/ruff_cli/src/commands/format.rs [hunk 1]
```diff
@@ -713,41 +714,41 @@ pub(super) fn warn_incompatible_formatter_settings(
...
-            rule_names.sort();
-            warn!("The following rules may cause conflicts when used with the formatter: {}. To avoid unexpected behavior, we recommend disabling these rules, either by removing them from the `select` or `extend-select` configuration, or adding then to the `ignore` configuration.", rule_names.join(", "));
+        // Validate all rules that rely on custom indent widths.
+        if setting.linter.rules.any_enabled(&[
+            Rule::IndentationWithInvalidMultiple,
+            Rule::IndentationWithInvalidMultipleComment,
+        ]) && setting.formatter.indent_width.value() != 4
+        {
+            warn_user_once!("The `format.indent-width` option with a value other than 4 is incompatible with `E111` and `E114`. We recommend disabling these rules when using the formatter, which enforces a consistent indentation width. Alternatively, set the `format.indent-width` option to `4`.");
         }
```
Comment (charliermarsh) [inline crates/ruff_cli/src/commands/format.rs:749]: Gave this a custom warning based on the indent-width.

File: crates/ruff_cli/src/commands/format.rs [hunk 2]
```diff
@@ -713,41 +714,41 @@ pub(super) fn warn_incompatible_formatter_settings(
...
-            }
+    // Next, validate settings-specific incompatibilities.
+    for setting in std::iter::once(&pyproject_config.settings)
+        .chain(resolver.iter().flat_map(|resolver| resolver.settings()))
+    {
+        // Validate all rules that rely on tab styles.
+        if setting.linter.rules.enabled(Rule::TabIndentation)
+            && setting.formatter.indent_style.is_tab()
+        {
+            warn_user_once!("The `format.indent-style=\"tab\"` option is incompatible with `W191`. We recommend disabling these rules when using the formatter, which enforces a consistent indentation style. Alternatively, set the `format.indent-style` option to `\"space\"`.");
```
Comment (charliermarsh) [inline crates/ruff_cli/src/commands/format.rs:739]: Gave this a custom warning based on the indent-style.

File: crates/ruff_cli/src/commands/format.rs [hunk 3]
```diff
@@ -713,41 +714,41 @@ pub(super) fn warn_incompatible_formatter_settings(
...
-                }
-            }
-        }
+    if !incompatible_rules.is_empty() {
+        let mut rule_names: Vec<_> = incompatible_rules
+            .into_iter()
+            .map(|rule| format!("`{}`", rule.noqa_code()))
+            .collect();
+        rule_names.sort();
+        warn_user_once!("The following rules may cause conflicts when used with the formatter: {}. To avoid unexpected behavior, we recommend disabling these rules, either by removing them from the `select` or `extend-select` configuration, or adding then to the `ignore` configuration.", rule_names.join(", "));
```
Comment (zanieb) [inline crates/ruff_cli/src/commands/format.rs:728]: Minor question — since `warn_user_once` works using the call site, does this mean if we find a second set of incompatible rules in a different pyproject file we will not emit a second message with the different set? Probably not common... but not ideal?

Comment (charliermarsh) [reply crates/ruff_cli/src/commands/format.rs:728]: No, for this _specific_ warning, we iterate over all `pyproject.toml` and collect all incompatible rules, so they would all be flagged here.

(All the other warnings are static, this is the only warning with dynamic input.)

Comment (zanieb) [reply crates/ruff_cli/src/commands/format.rs:728]: Sounds good!

**Review by zanieb — APPROVED** [review]

**Comment by MichaReiser** [comment]
I'd like to double check the removal of the on Monday. I verified them all manually  and believe that I was able to come up with a conflict

**Comment by charliermarsh** [comment]
@MichaReiser - Sorry, you're right. I think we don't reformat module-level docstrings which is why I was seeing different results. If we re-indent a function or class docstring, we do indeed change from spaces to tabs. Will restore.

**Comment by charliermarsh** [comment]
@MichaReiser - Restored.

File: crates/ruff_cli/src/commands/format.rs [hunk 4]
```diff
@@ -695,11 +696,11 @@ pub(super) fn warn_incompatible_formatter_settings(
     pyproject_config: &PyprojectConfig,
     resolver: Option<&Resolver>,
 ) {
+    // First, collect all rules that are incompatible regardless of the linter-specific settings.
+    let mut incompatible_rules = BTreeSet::new();
```
Comment (MichaReiser) [inline crates/ruff_cli/src/commands/format.rs:700]: What's the motivation for using a `BTreeSet` when we still need to sort the rules on line 722? Why not use a regular `HashSet` (or create a wrapper around `BTreeSet` with a `insert(Rule)` method that inserts the formatted name)

**Review by MichaReiser — APPROVED** [review]
