### PR TITLE
[red-knot] Fix Stack overflow in Type::bool 

### LINKED ISSUE #15672: [red-knot] Stack overflow in `Type::bool`
### Description

We have an existing code path in `Type::bool` that tries to prevent infinite recursion:

https://github.com/astral-sh/ruff/blob/13e7afca42e1ab4e698412df903e3dd172909caa/crates/red_knot_python_semantic/src/types.rs#L1777-L1786

and a test for it here:

https://github.com/astral-sh/ruff/blob/13e7afca42e1ab4e698412df903e3dd172909caa/crates/red_knot_python_semantic/resources/mdtest/unary/not.md?plain=1#L140-L145

But this only checks the case where `__bool__` has the exact type `Literal[bool]`. It fails if the type is a union that contains `Literal[bool]`, for example:

```py
def flag() -> bool: return True

class Boom:
    if flag():
        __bool__ = bool
    else:
        __bool__ = int

bool(Boom())
```

```
> cargo run --bin red_knot -- --project /path/to/folder/with/example
thread '<unknown>' has overflowed its stack
fatal runtime error: stack overflow
```

### PR DESCRIPTION
**Pull request by mishamsk**
## Summary

This PR adds `Type::call_bound` method for calls that should follow descriptor protocol calling convention. The PR is intentionally shallow in scope and only fixes #15672

Couple of obvious things that weren't done:

* Switch to `call_bound` everywhere it should be used
* Address the fact, that red_knot resolves `__bool__ = bool` as a Union, which includes `Type::Dynamic` and hence fails to infer that the truthiness is always false for such a class (I've added a todo comment in mdtests)
* Doesn't try to invent a new type for descriptors, although I have a gut feeling it may be more convenient in the end, instead of doing method lookup each time like I did in `call_bound`

## Test Plan

* extended mdtests with 2 examples from the issue
* cargo neatest run

### CODE REVIEW

File: crates/red_knot_python_semantic/src/types.rs [hunk 1]
```diff
@@ -2145,6 +2138,83 @@ impl<'db> Type<'db> {
...
+        debug_assert!(receiver_ty.is_instance() || receiver_ty.is_class_literal());
+
+        match self {
+            Type::FunctionLiteral(..) => {
+                // Functions are always descriptors, so this would effectively call
+                // the function with the instance as the first argument
+                self.call(db, &arguments.with_self(*receiver_ty))
+            }
+
+            object_ty @ (Type::Instance(_) | Type::ClassLiteral(_)) => {
```
Comment (carljm) [inline crates/red_knot_python_semantic/src/types.rs:2163]: This should handle `Type::SubclassOf` as well -- but so should `Type::call`, and it doesn't either. So this can probably be left to a separate PR to fix.

File: crates/red_knot_python_semantic/resources/mdtest/type_properties/truthiness.md [hunk 2]
```diff
@@ -45,3 +47,27 @@ def _(
     reveal_type(bool(c))  # revealed: bool
     reveal_type(bool(d))  # revealed: bool
 ```
+
+## Instances
+
+```py
+# We don't get into a cycle if someone sets their `__bool__` method to the `bool` builtin:
```
Comment (carljm) [inline crates/red_knot_python_semantic/resources/mdtest/type_properties/truthiness.md:54]: Nit: prefer Markdown prose paragraph before the code block over comments in the code block, for general commentary like this.

File: crates/red_knot_python_semantic/resources/mdtest/type_properties/truthiness.md [hunk 3]
```diff
@@ -45,3 +47,27 @@ def _(
...
+def flag() -> bool:
+    return True
+
+class Boom:
+    if flag():
+        __bool__ = bool
+    else:
+        __bool__ = int
+
+reveal_type(bool(Boom()))  # revealed: bool
```
Comment (carljm) [inline crates/red_knot_python_semantic/resources/mdtest/type_properties/truthiness.md:72]: Nit: make this and the above two separate test headings (`# __bool__ is bool` and `# conditional __bool__`) with two separate code blocks.

File: crates/red_knot_python_semantic/resources/mdtest/type_properties/truthiness.md [hunk 4]
```diff
@@ -45,3 +47,27 @@ def _(
...
+
+## Instances
+
+```py
+# We don't get into a cycle if someone sets their `__bool__` method to the `bool` builtin:
+class BoolIsBool:
+    __bool__ = bool
+
+# TODO: when bool is used as a method, it is called without arguments and always returns False, but this is not yet implemented
+# see https://github.com/astral-sh/ruff/issues/15672
```
Comment (carljm) [inline crates/red_knot_python_semantic/resources/mdtest/type_properties/truthiness.md:59]: I think this TODO is not quite describing the situation accurately. We already correctly implement that `bool` called with no arguments returns `Literal[False]`. And your PR does correctly implement that calling the `bool` class as a method, since it is not a descriptor, calls `bool` with no arguments, which returns `Literal[False]`.

But since `BoolIsBool.__bool__` has no declared type, we model that it could be reassigned to any type, so we give it the type `Unknown | Literal[bool]` instead of the type `Literal[bool]`. And `Unknown` has ambiguous truthiness, so the result is that we still infer `bool`, rather than `Literal[false]`, here.

Since this result is not wrong, and the reasons we arrive at it are complex to explain (and are already explained in detail in other tests), I would just remove this TODO entirely here. The main point of this test is that we can handle this situation without a panic.

File: crates/red_knot_python_semantic/src/types.rs [hunk 5]
```diff
@@ -2145,6 +2138,83 @@ impl<'db> Type<'db> {
...
+                                binding.return_type().call(db, arguments)
+                            }
+                            _ => descr_result,
+                        }
+                    }
+                    Symbol::Unbound => {
+                        // Not a descriptor, so call without passing the instance
+                        self.call(db, arguments)
+                    }
+                }
```
Comment (carljm) [inline crates/red_knot_python_semantic/src/types.rs:2196]: Since we don't have tests for descriptor protocol (and this PR doesn't add any), and we may want to design our descriptor protocol support a bit more holistically (not just specific to bound calls), I think we should not add support for it here. Instead we should just simplify this code to assume non-descriptor, with a TODO comment for descriptor support.
```suggestion
                // TODO descriptor protocol. For now, assume non-descriptor and call without `self` argument.
                self.call(db, arguments)
```

File: crates/red_knot_python_semantic/src/types.rs [hunk 6]
```diff
@@ -2145,6 +2138,83 @@ impl<'db> Type<'db> {
...
+            }
+
+            // Dynamic types are callable, and the return type is the same dynamic type
+            Type::Dynamic(_) => CallOutcome::callable(CallBinding::from_return_type(self)),
```
Comment (carljm) [inline crates/red_knot_python_semantic/src/types.rs:2200]: Nit: can we group this down with the default not-callable case and explicitly mark them with a comment as "cases that duplicate `Type::call`"?

I think it may be worth duplicating these cases here, rather than deferring to `Type::call`, since they are very simple, and it will be less efficient to defer to `Type::call`. But I'd like to be clear on which cases should be kept in exact sync.

**Review by carljm — CHANGES_REQUESTED** [review]
Thank you for the PR! I think the `call_bound` abstraction makes sense, and is needed to handle this case correctly. Some inline comments.

File: crates/red_knot_python_semantic/resources/mdtest/unary/not.md [hunk 7]
```diff
@@ -139,10 +139,9 @@ reveal_type(not AlwaysFalse())
 
 # We don't get into a cycle if someone sets their `__bool__` method to the `bool` builtin:
 class BoolIsBool:
-    # TODO: The `type[bool]` declaration here is a workaround to avoid running into
-    # https://github.com/astral-sh/ruff/issues/15672
-    __bool__: type[bool] = bool
+    __bool__ = bool
```
[the remark this answers is not in the document]
Comment (mishamsk) [reply crates/red_knot_python_semantic/resources/mdtest/unary/not.md:142]: sure, agree. I erred on the side of caution and didn't want to impose my view on how tests should be structured. At least not with my 4th PR ;-) 

I removed this specific case from `not.md` and left it only in the `truthiness.md` file. I can move the rest in a separate follow-up or as a flyby with other stuff

File: crates/red_knot_python_semantic/src/types.rs (hunk 1 above)
Comment (mishamsk) [reply crates/red_knot_python_semantic/src/types.rs:2163]: Happy to do that in a follow-up. See my comment regarding descriptor protocol below

File: crates/red_knot_python_semantic/resources/mdtest/type_properties/truthiness.md (hunk 2 above)
Comment (mishamsk) [reply crates/red_knot_python_semantic/resources/mdtest/type_properties/truthiness.md:54]: fixed

File: crates/red_knot_python_semantic/resources/mdtest/type_properties/truthiness.md (hunk 4 above)
Comment (mishamsk) [reply crates/red_knot_python_semantic/resources/mdtest/type_properties/truthiness.md:59]: I haven't found the explanation to this phenomenon yet, but assuming I'll continue working on red_knot I will.

Remove the comment for now as you've suggested

File: crates/red_knot_python_semantic/resources/mdtest/type_properties/truthiness.md (hunk 3 above)
Comment (mishamsk) [reply crates/red_knot_python_semantic/resources/mdtest/type_properties/truthiness.md:72]: fixed. I've used 3rd level headings, hopefully this is not forbidden!

File: crates/red_knot_python_semantic/src/types.rs (hunk 5 above)
Comment (mishamsk) [reply crates/red_knot_python_semantic/src/types.rs:2196]: I'd love to work on the descriptor protocol as a whole, would be fun and will allow me to better review more of the red_knot codebase. If you are fine with that, I can open a separate draft PR and outline a plan.

One obvious place to start would be: https://github.com/astral-sh/ruff/blob/0529ad67d76d01c5ca586ad9b3db8b37c1a930dc/crates/red_knot_python_semantic/src/types.rs#L4211-L4219  and implement proper handling of `property` instead of a current "workaround". This would serve as a test. + I can make a special mutest suite for descriptors in general.

As for my code here, I do not think that there is harm in leaving it, as it will work for cases when `__get__` method is defined explicitly already, but since you suggest removing it, I'll just stash it and see if it eventually survives.

File: crates/red_knot_python_semantic/src/types.rs (hunk 6 above)
Comment (mishamsk) [reply crates/red_knot_python_semantic/src/types.rs:2200]: yes, totally makes sense. re-order and added a comment.

File: crates/red_knot_python_semantic/resources/mdtest/type_properties/truthiness.md (hunk 3 above)
Comment (carljm) [reply crates/red_knot_python_semantic/resources/mdtest/type_properties/truthiness.md:76]: nope, that's fine! we definitely do it elsewhere already (even some fourth-level i think)

**Review by carljm — APPROVED** [review]
Looks great, thank you!

File: crates/red_knot_python_semantic/resources/mdtest/unary/not.md (hunk 7 above)
[the remark this answers is not in the document]
Comment (carljm) [reply crates/red_knot_python_semantic/resources/mdtest/unary/not.md]: That would be great if you want to do this! I recommend separate PR, there's no real cost to more smaller PRs, and it can make it a lot easier to review this kind of change if it's not combined with functional changes.

File: crates/red_knot_python_semantic/src/types.rs (hunk 5 above)
Comment (carljm) [reply crates/red_knot_python_semantic/src/types.rs]: Thanks for removing this for now. I agree it's possible that later it may come back in the same or similar form, but I would rather it arrive along with tests exercising it.

I think @sharkdp was planning to tackle descriptors soon, but may be open to you working on that instead, freeing him up to tackle something else? Let's wait for him to respond before you start on it, in case he has already started on it.

It would definitely be good to open an issue with a proposed design first, so we can discuss, before opening a PR; this may save some implementation work.

Comment (mishamsk) [reply crates/red_knot_python_semantic/src/types.rs]: @carljm @sharkdp I can create an outline with items that needs to be tackled in principle, a proposed step-by-step plan and draft design (or at least some thinking around it). Shall I use discussions or an issue?

Comment (carljm) [reply crates/red_knot_python_semantic/src/types.rs]: That sounds like a great approach! We usually use issues, not discussions. I think @sharkdp was planning to create a set of issues tomorrow for various follow-ups to his recent work on instance attributes, including descriptor protocol as one of those.

Comment (sharkdp) [reply crates/red_knot_python_semantic/src/types.rs]: > @carljm @sharkdp I can create an outline with items that needs to be tackled in principle, a proposed step-by-step plan and draft design (or at least some thinking around it). Shall I use discussions or an issue?

@mishamsk If you want to work on descriptors, we would definitely appreciate it! Starting with a separate design step sounds like a good idea. Please feel free to add comments to this issue: https://github.com/astral-sh/ruff/issues/15966

I will also set up an initial draft for a descriptor test suite that we can detail further while we work on the design and the implementation.
