### PR TITLE
Fix `--add-noqa` creating unwanted leading whitespace

### LINKED ISSUE #23751: `--add-noqa` for diagnostics on blank lines results in bad whitespace
### Summary

Rules like `D100` can produce diagnostics on `TextRange::ZERO` even if the line is blank.  In these cases, running ruff with `--add-noqa` produces a line with leading whitespace:

Create an empty file, and run `ruff check --add-noqa`:

```
$ echo "" > test.py

$ ruff check --isolated --select D100 --add-noqa test.py
Added 1 noqa directive.

$ cat test.py
  # noqa: D100
```

### Version

main

### PR DESCRIPTION
**Pull request by amyreese**
When generating a new `#noqa` comment in `--add-noqa`, check to see
if the line is blank or not, and if it's blank, don't write the
leading whitespace.

Fix #23751

### CODE REVIEW

File: crates/ruff_linter/src/noqa.rs [hunk 1]
```diff
@@ -1010,11 +1014,13 @@ fn generate_noqa_edit<'a>(
 
     let edit_range;
     let codes;
+    let blank_line;
 
     // Add codes.
     match directive {
         None => {
             let trimmed_line = locator.slice(line_range).trim_end();
+            blank_line = trimmed_line.trim_start().is_empty();
```
Comment (MichaReiser) [inline crates/ruff_linter/src/noqa.rs]: I'd probably use `trim_whitespace_start` to only trim Python whitespace and not arbitrary Unicode whitespace.
