### PR TITLE
[`ruff`] Handle `attrs`'s `auto_attribs` correctly (`RUF009`)

### LINKED ISSUE #14519: `RUF009` handles `attrs` dataclasses with `auto_attribs = False` incorrectly
From #14327:

> Note that `RUF009` can be a bit misleading when `auto_attribs=False` (or with older `attr.s` codebases):
> 
> ```python
> import attrs
> 
> @attrs.define(auto_attribs=False)
> class X:
>     a_field: int = attrs.field(default=42)
>     not_a_field: list = (lambda: [])()
> #                       ^^^^^^^^^^^^^^ RUF009 Do not perform function call in dataclass defaults
> ```
> 
> Without `auto_attribs`, `not_a_field` can't possibly be a `dataclass` field. In this example, it's an incorrectly typed class variable. Fixing the typing error also fixes the `RUF009` warning:
> 
> ```python
> @attrs.define(auto_attribs=False)
> class X:
>     a_field: int = attrs.field(default=42)
>     not_a_field: typing.ClassVar[list] = (lambda: [])()
> ```
> 
> This is an issue though when using `attrs.field` wrappers:
> 
> ```python
> def my_field():
>     return attrs.field(default=42, metadata={"my_metadata": 42})
> 
> 
> @attrs.define(auto_attribs=False)
> class X:
>     a_field: int = my_field()
> #                  ^^^^^^^^^^ RUF009 Do not perform function call `my_field` in dataclass defaults
> ```
>
> &mdash; @pwuertz

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
## Summary

Resolves #14519.

## Test Plan

`cargo nextest run` and `cargo insta test`.

### CODE REVIEW

File: crates/ruff_linter/src/rules/ruff/rules/helpers.rs [hunk 1]
```diff
@@ -112,7 +129,39 @@ pub(super) fn dataclass_kind(
...
+                    };
+
+                    return Some(DataclassKind::Attrs(auto_attribs));
+                };
+
+                let Some(auto_attribs) = arguments.find_keyword("auto_attribs") else {
+                    return Some(DataclassKind::Attrs(AttrsAutoAttribs::None));
+                };
+
+                let auto_attribs = match &auto_attribs.value {
```
Comment (charliermarsh) [inline crates/ruff_linter/src/rules/ruff/rules/helpers.rs:151]: Can we use `Truthiness` here?

**Review by charliermarsh — APPROVED** [review]
Nicely done, thanks.
