### PR TITLE
Fix cache invalidation for nested pyproject.toml files

### LINKED ISSUE #12264: Mismatched diagnostics with and without cache with hierarchical configs
Consider the following project structure:

```
.
├── baz
│   ├── egg
│   │   └── t3.py
│   ├── pyproject.toml
│   └── t2.py
├── pyproject.toml
└── t1.py
```

> Zipped folder: [foo.zip](https://github.com/user-attachments/files/16155043/foo.zip)

All Python files contain the same code which raises `undefined-name`:
```py
print(name)
```

And both `pyproject.toml` file contain:
```toml
[tool.ruff.lint]
ignore = ["F821"]
```

### Steps:
1. Make sure there's no cache: `ruff clean`
2. Run a fresh `ruff check .` which should give no diagnostics because they're currently ignored
3. Comment the `ignore` line in nested config: `baz/pyproject.toml`
4. Run `ruff check .` and you'll see a single diagnostic for `baz/egg/t3.py`
5. Run `ruff check --no-cache .` and you'll see two diagnostics for `baz/t2.py` and `baz/egg/t3.py`

### LINKED ISSUE #12721: Changes in sub pyproject.toml do not cause a cache bust
When modifying a `pyproject.toml` in a subfolder ruff does correctly handle this as a cache bust. The same modification of the root level `pyproject.toml` causes a cache bust.

The setup can be recreated with this script:

```bash
#!/bin/bash

# Create root pyproject.toml
cat << EOF > pyproject.toml
[tool.ruff.lint]
select = []
EOF

# Create lib directory and its pyproject.toml
mkdir lib
cat << EOF > lib/pyproject.toml
[tool.ruff.lint]
select = []
EOF

# Create a Python file with a hello world function
# It violates ANN rules
cat << EOF > lib/hello.py
def hello_world():
    print("Hello, World!")
EOF

# Run ruff check
echo "Running initial ruff check:"
ruff check

# Modify lib/pyproject.toml
cat << EOF > lib/pyproject.toml
[tool.ruff.lint]
select = ["ANN"]
EOF

# Run ruff check again - it works due to a cache hit
echo "Running ruff check after modification:"
ruff check

# Ruff check without cache will fail
echo "Running ruff check without cache"
ruff check --no-cache
```

Output:
```bash
Running initial ruff check:
All checks passed!
Running ruff check after modification:
All checks passed!
Running ruff check without cache
lib/hello.py:1:5: ANN201 Missing return type annotation for public function `hello_world`
  |
1 | def hello_world():
  |     ^^^^^^^^^^^ ANN201
2 |     print("Hello, World!")
  |
  = help: Add return type annotation: `None`

Found 1 error.
No fixes available (1 hidden fix can be enabled with the `--unsafe-fixes` option).
```

Tested with `ruff 0.5.6`.

Searched for different combinations of these keywords and have not found an existing issue: cache pyproject.toml subfolder --no-cache subproject

### PR DESCRIPTION
**Pull request by MichaReiser**
## Summary

This PR fixes an issue with cache invalidation where changing a nested pyproject.toml didn't invalidate the cache for those files. 

The root cause of the issue was that the `Resolver` returned the wrong configuration when querying the settings by the directory because it only registers a route for `directory/{files}` but a query by directory misses the trailing `/`. 

Fixes #12721 
Fixes #12264

## Test Plan

Played throught the example in #12721

### CODE REVIEW

File: crates/ruff_workspace/src/resolver.rs [hunk 1]
```diff
@@ -156,9 +156,16 @@ impl<'a> Resolver<'a> {
...
+            Err(InsertError::Conflict { .. }) => {
+                return;
+            }
             Err(_) => unreachable!("file paths are escaped before being inserted in the router"),
         }
+
+        // Insert a mapping that matches the directory itself (without a trailing slash).
+        // Inserting should always succeed because conflicts are resolved above and the above insertion guarantees
+        // that the path is correctly escaped.
+        self.router.insert(path, self.settings.len() - 1).unwrap();
```
Comment (MichaReiser) [inline crates/ruff_workspace/src/resolver.rs:168]: @ibraheemdev is there some wild card expression that we could use that I'm not aware of instead of inserting two routes (e.g. `{path}(/{{#filepath}})?`)

**Comment by fellhorn** [comment]
Thank you, Micha! I can confirm it fixes both the test script from #12721 as well as our own original case, where we discovered the bug.

You folks are so fast! The issue is not even 12h old and you already have a fix :)

File: crates/ruff_workspace/src/resolver.rs (hunk 1 above)
Comment (ibraheemdev) [reply crates/ruff_workspace/src/resolver.rs:168]: No, this is the recommended way of doing it.

**Review by ibraheemdev — APPROVED** [review]
