### PR TITLE
Fix dropped union expressions for piped non-types in `PYI055` autofix

### LINKED ISSUE #9156: PYI055's "safe" fix breaks type annotation semantics
Ruff 0.1.8
`ruff check --isolated --select PYI055 --fix`
turns
```py
def convert_union(union: UnionType) -> _T | None:
    converters: tuple[
        type[_T] | type[Converter[_T]] | Converter[_T] | Callable[[str], _T], ...
    ] = union.__args__
    ...
```
into
```py
def convert_union(union: UnionType) -> _T | None:
    converters: tuple[
        type[_T | Converter[_T]], ...
    ] = union.__args__
    ...
```
completely disregarding `Converter[_T] | Callable[[str], _T]`

### PR DESCRIPTION
**Pull request by diceroll123**
## Summary

Fix dropped union expressions for piped non-types in `PYI055` autofix

If you had `type[int] | type[str] | str`, it would have dropped the `str`, which breaks the type!

Closes #9156 

## Test Plan

`cargo test`

### CODE REVIEW

File: crates/ruff_linter/src/rules/flake8_pyi/rules/unnecessary_type_union.rs [hunk 1]
```diff
@@ -144,24 +147,32 @@ pub(crate) fn unnecessary_type_union<'a>(checker: &mut Checker, union: &'a Expr)
                         range: TextRange::default(),
                     }))
```
Comment (charliermarsh) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/unnecessary_type_union.rs:148]: Do we not need to take the `other_exprs` into account in the top part of this `if`-`else`?

Comment (diceroll123) [reply crates/ruff_linter/src/rules/flake8_pyi/rules/unnecessary_type_union.rs:148]: I'll double-check!

**Review by charliermarsh — APPROVED** [review]
Thank you!
