### PR TITLE
[`refurb`] Mark autofix as safe only for number literals in `FURB116`

### LINKED ISSUE #16472: FURB116 has false positives and unsafe fixes
### Summary

The fix for [f-string-number-format (FURB116)](https://docs.astral.sh/ruff/rules/f-string-number-format/) only works on non-negative integers. If the argument isn’t an `int` or `bool` literal (or a variable that was set to one of those, or any other expression that Ruff can prove is a non-negative integer), the rule should be marked unsafe. The fix can also introduce a syntax error for certain complex expressions that the rule was probably not intended to handle.

The fix changes behavior for negative integers.
```console
$ cat >furb116_1.py <<'# EOF'
x = -1
print(bin(x)[2:])
# EOF

$ python furb116_1.py
b1

$ ruff --isolated check --preview --select FURB116 furb116_1.py --fix
Found 1 error (1 fixed, 0 remaining).

$ cat furb116_1.py
x = -1
print(f"{x:b}")

$ python furb116_1.py
-1
```

FURB116 applies to all number literals, but `float` and `complex` literals are false positives which the rule should ignore.
```console
$ cat >furb116_2.py <<'# EOF'
bin(1.0)[2:]
# EOF

$ python furb116_2.py 2>&1 | tail -n 1
TypeError: 'float' object cannot be interpreted as an integer

$ ruff --isolated check --preview --select FURB116 furb116_2.py --fix
Found 1 error (1 fixed, 0 remaining).

$ python furb116_2.py 2>&1 | tail -n 1
ValueError: Unknown format code 'b' for object of type 'float'
```

In general, the fix should be marked unsafe, except when it can be proved to be safe. Otherwise, the fix changes behavior, sometimes by changing the error type as in the previous example, and sometimes by changing behavior in other ways.
```console
$ cat >furb116_3.py <<'# EOF'
import datetime
d = datetime.datetime.now(tz=datetime.UTC)
print(bin(d)[2:])
# EOF

$ python furb116_3.py 2>&1 | tail -n 1
TypeError: 'datetime.datetime' object cannot be interpreted as an integer

$ ruff --isolated check --preview --select FURB116 furb116_3.py --fix
Found 1 error (1 fixed, 0 remaining).

$ cat furb116_3.py
import datetime
d = datetime.datetime.now(tz=datetime.UTC)
print(f"{d:b}")

$ python furb116_3.py
b
```

The fix introduces a syntax error when the argument begins with a brace.
```console
$ cat >furb116_4.py <<'# EOF'
print(bin({0: 1}[0].numerator)[2:])
# EOF

$ python furb116_4.py
1

$ ruff --isolated check --preview --select FURB116 furb116_4.py --diff 2>&1 | grep error:
error: Fix introduced a syntax error. Reverting all changes.
```

The fix introduces a syntax error in Python 3.11 and earlier when the argument contains the same kind of quotation marks as the fix’s f-string.
```console
$ cat >furb116_5.py <<'# EOF'
print(bin(len("xyz").numerator)[2:])
# EOF

$ python3.11 furb116_5.py
11

$ ruff --isolated check --target-version py311 --preview --select FURB116 furb116_5.py --fix
Found 1 error (1 fixed, 0 remaining).

$ cat furb116_5.py
print(f"{len("xyz").numerator:b}")

$ python3.11 furb116_5.py 2>&1 | tail -n 1
SyntaxError: f-string: unmatched '('
```

The fix introduces a syntax error in Python 3.11 and earlier when the argument contains a backslash.
```console
$ cat >furb116_6.py <<'# EOF'
print(bin(ord("\\").numerator)[2:])
# EOF

$ python3.11 furb116_6.py
1011100

$ ruff --isolated check --target-version py311 --preview --select FURB116 furb116_6.py --fix
Found 1 error (1 fixed, 0 remaining).

$ cat furb116_6.py
print(f"{ord("\\").numerator:b}")

$ python3.11 furb116_6.py 2>&1 | tail -n 1
SyntaxError: unexpected character after line continuation character
```

The fix introduces a syntax error in Python 3.11 and earlier when the argument spans multiple lines.
```console
$ cat >furb116_7.py <<'# EOF'
import sys
print(hex(sys
.maxunicode)[2:])
# EOF

$ python3.11 furb116_7.py
10ffff

$ ruff --isolated check --target-version py311 --preview --select FURB116 furb116_7.py --fix
Found 1 error (1 fixed, 0 remaining).

$ cat furb116_7.py
import sys
print(f"{sys
.maxunicode:x}")

$ python3.11 furb116_7.py 2>&1 | tail -n 1
SyntaxError: unterminated string literal (detected at line 2)
```

### Version

ruff 0.9.9 (091d0af2a 2025-02-28)

### PR DESCRIPTION
**Pull request by LaBatata101**
## Summary
We can only guarantee the safety of the autofix for number literals, all other cases may change the runtime behaviour of the program or introduce a syntax error. For the cases reported in the issue that would result in a syntax error,  I disabled the autofix.

Follow-up of #17661. 

Fixes #16472.

## Test Plan

Snapshot tests.

### CODE REVIEW

**Comment by dscorbett** [comment]
For `bin({0: 1}[0].numerator)[2:]`, it would be better to insert a space before the brace in the unsafe fix, as in `f"{ {0: 1}[0].numerator:b}"`, which is how `ruff format` formats it, instead of disabling the fix.

**Comment by LaBatata101** [comment]
> For `bin({0: 1}[0].numerator)[2:]`, it would be better to insert a space before the brace in the unsafe fix, as in `f"{ {0: 1}[0].numerator:b}"`, which is how `ruff format` formats it, instead of disabling the fix.

Good idea, thanks!

File: crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs [hunk 1]
```diff
@@ -134,15 +132,57 @@ pub(crate) fn fstring_number_format(checker: &Checker, subscript: &ast::ExprSubs
...
+
+    // On Python 3.11 and earlier, trying to replace an `arg` that contains a backslash
+    // would create a `SyntaxError` in the f-string.
+    if checker.target_version() <= PythonVersion::PY311 && inner_source.contains('\\') {
+        return None;
+    }
+
+    // On Python 3.11 and earlier, trying to replace an `arg` that spans multiple lines
+    // would create a `SyntaxError` in the f-string.
+    if checker.target_version() <= PythonVersion::PY311 && inner_source.contains('\n') {
```
Comment (dscorbett) [inline crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs:161]: To check for multiple lines, `find_newline` is better because it also detects `'\r'`.

File: crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs [hunk 2]
```diff
@@ -145,15 +144,57 @@ pub(crate) fn fstring_number_format(checker: &Checker, subscript: &ast::ExprSubs
...
+    let shorthand = base.shorthand();
+
+    // If the `arg` contains double quotes we need to create the f-string with single quotes
+    // to avoid a `SyntaxError` in Python 3.11 and earlier.
+    if checker.target_version() <= PythonVersion::PY311
+        && quote.is_double()
+        && inner_source.contains('"')
+    {
+        quote = quote.opposite();
+    }
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs:187]: I can't think of a precise counterexample right now, but this is reminding me of some subtle issue from when I was working on quoting a couple of months ago. Maybe this can cause problems if `arg` also contains a single quote? You could try a test case with something wild like this:

```python
""" ''' " ' x ' " ''' """
```

File: crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs [hunk 3]
```diff
@@ -145,15 +144,57 @@ pub(crate) fn fstring_number_format(checker: &Checker, subscript: &ast::ExprSubs
...
+
+    // If the `arg` contains a brace add an space before it to avoid a `SyntaxError`
+    // in the f-string.
+    if inner_source.contains('{') {
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs:191]: Does this need to be a `contains` check, or is it only a problem if it starts with a `{`? It seems like braces could cause other problems when injected into an f-string, but I guess that issue might already be present in the current rule.

File: crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB116_FURB116.py.snap [hunk 4]
```diff
@@ -1,144 +1,245 @@
...
-
-FURB116.py:7:7: FURB116 [*] Replace `hex` call with `f"{num:x}"`
-  |
-6 | print(oct(num)[2:])  # FURB116
-7 | print(hex(num)[2:])  # FURB116
-  |       ^^^^^^^^^^^^ FURB116
-8 | print(bin(num)[2:])  # FURB116
-  |
-  = help: Replace with `f"{num:x}"`
+ℹ Unsafe fix
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB116_FURB116.py.snap:15]: Yeah I think if we're able to resolve the type, this can still be a safe fix.

File: crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB116_FURB116.py.snap [hunk 5]
```diff
@@ -1,144 +1,245 @@
...
+31 31 | print(bin(d)[2:])
+32    |-print(bin(len("xyz").numerator)[2:])
+   32 |+print(f"{len("xyz").numerator:b}")
+33 33 | 
+34 34 | # no autofix, as it introduces a syntax error
+35 35 | print(bin({0: 1}[0].numerator)[2:])
+
+FURB116.py:35:7: FURB116 [*] Replace `bin` call with `f"{ {0: 1}[0].numerator:b}"`
+   |
+34 | # no autofix, as it introduces a syntax error
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB116_FURB116.py.snap:189]: It looks like this comment is outdated since we get a fix here

File: crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB116_FURB116.py.snap [hunk 6]
```diff
@@ -1,144 +1,245 @@
...
+35    |-print(bin({0: 1}[0].numerator)[2:])
+   35 |+print(f"{ {0: 1}[0].numerator:b}")
+36 36 | # no autofix for Python 3.11 and earlier, as it introduces a syntax error
+37 37 | print(bin(ord("\\").numerator)[2:])
+38 38 | print(hex(sys
+
+FURB116.py:37:7: FURB116 [*] Replace `bin` call with `f"{ord("\\").numerator:b}"`
+   |
+35 | print(bin({0: 1}[0].numerator)[2:])
+36 | # no autofix for Python 3.11 and earlier, as it introduces a syntax error
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB116_FURB116.py.snap:210]: We might want to add a variant of this test with a pre-3.11 version to capture this.

**Review by ntBre — COMMENTED** [review]
Thanks! This looks reasonable to me, just a few fairly minor suggestions.

I think it might be good for @MichaReiser to take a look at the `try_create_replacement` code too, especially the quoting and f-string handling since he helped find a bunch of issues in my handling of those recently.

Do we need to have a check for negative numbers? That seems like the only remaining part of the issue not covered, unless I missed it.

File: crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs (hunk 3 above)
Comment (LaBatata101) [reply crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs:191]: It was supposed to be `starts_with`, thanks!

File: crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs [hunk 7]
```diff
@@ -121,21 +127,14 @@ pub(crate) fn fstring_number_format(checker: &Checker, subscript: &ast::ExprSubs
...
-        arg,
-        Expr::NumberLiteral(_) | Expr::Name(_) | Expr::Attribute(_)
-    ) {
-        let inner_source = checker.locator().slice(arg);
-
-        let quote = checker.stylist().quote();
-        let shorthand = base.shorthand();
-
-        Some(format!("f{quote}{{{inner_source}:{shorthand}}}{quote}"))
+    let applicability = if matches!(arg, Expr::NumberLiteral(_)) {
```
[the remark this answers is not in the document]
Comment (LaBatata101) [reply crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs:130]: `ResolvedPythonType` resolves the type of identifiers to `Unknown`, so comparing against number literals or using `ResolvedPythonType` is the same thing.

File: crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB116_FURB116.py.snap (hunk 6 above)
Comment (LaBatata101) [reply crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB116_FURB116.py.snap:210]: How do I make a test for a specific version?

File: crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs (hunk 2 above)
Comment (LaBatata101) [reply crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs:187]: Yeah, with your example I got a syntax error in Python 3.11.

File: crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (dscorbett) [reply crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs:130]: Also, the fix is only safe for non-negative numbers. Resolving the expression to a `ResolvedPythonType::Atom(PythonType::Number(NumberLike::Integer))` wouldn’t be enough, because the value could be negative. Resolving it to a `ResolvedPythonType::Atom(PythonType::Number(NumberLike::Bool))` _would_ be enough to prove the fix is safe, though that case is so rare it may not be worth handling.

[the remark this answers is not in the document]
Comment (LaBatata101) [reply crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs:130]: Negative numbers are represented by the `UnaryOp` AST node, so we don't need to use `ResolvedPythonType` here. That check is enough to mark the fix as unsafe for negative numbers.  I'll just have to handle numbers with the `+` unary operator.

File: crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs (hunk 2 above)
Comment (ntBre) [reply crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs:197]: That could be one option. I think we could also use the `Generator`, which should handle escaping quotes for us. I'm not sure how difficult it would be to convert  this to use the generator though.

File: crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB116_FURB116.py.snap (hunk 6 above)
Comment (ntBre) [reply crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB116_FURB116.py.snap]: You'd probably have to copy this test and override the `unresolved_target_version` setting in `LinterSettings`:

https://github.com/astral-sh/ruff/blob/981bd70d393fe29324c07c3ffce5ecddd40e6bd6/crates/ruff_linter/src/rules/refurb/mod.rs#L54-L62

File: crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (ntBre) [reply crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs]: I always forget that `ResolvedPythonType` doesn't do the same thing as the helpers in the `typing` module:

https://github.com/astral-sh/ruff/blob/981bd70d393fe29324c07c3ffce5ecddd40e6bd6/crates/ruff_python_semantic/src/analyze/typing.rs#L980-L983

Something like this is closer to what I had in mind.

File: crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs (hunk 2 above)
Comment (LaBatata101) [reply crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs:197]: I tried using `Generator` but it didn't work, still got a `SyntaxError`. I'm going to disable the fix for that case.

File: crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (LaBatata101) [reply crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs]: The only problem is that if we have a variable, and it resolves the type to `int`, we can't know if the integer is positive or negative.

**Review by MichaReiser — COMMENTED** [review]
I skimmed over it and this looks good to me. 

I suspect there might be some edge cases with f-strings if the expression is in a format spec or debug expression but these seem rare enough (and also isn't something we handle in other fixes)

File: crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs [hunk 8]
```diff
@@ -193,7 +193,7 @@ fn try_create_replacement(checker: &Checker, arg: &Expr, base: Base) -> Option<S
         && quote.is_double()
         && inner_source.contains('"')
     {
-        quote = quote.opposite();
+        return None;
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs:196]: Do we need the same check for single  quotes? I think we might be  able to do something like this:

```rust
if checker.target_version() <= PythonVersion::PY311 && inner_source.contains(quote.as_str()) { ... }
```

Comment (ntBre) [reply crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs:196]: I did a similar check here, but I think it's fine to do a simple `contains` check instead:

https://github.com/astral-sh/ruff/blob/43b905bad805e4b6aeaa4fd5e208f9c4e00bbde2/crates/ruff_python_parser/src/parser/expression.rs#L1460-L1468

File: crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB116_FURB116.py.snap [hunk 9]
```diff
@@ -180,108 +181,108 @@ FURB116.py:32:7: FURB116 Replace `bin` call with `f"{d:b}"`
...
 31 31 | # autofix is display-only
 32 32 | print(bin(d)[2:])
-33    |-print(bin(len("xyz").numerator)[2:])
-   33 |+print(f"{len("xyz").numerator:b}")
-34 34 | 
-35 35 | # autofix is display-only
-36 36 | print(bin({0: 1}[0].numerator)[2:])
+33 33 | # no autofix
+34    |-print(bin(len("xyz").numerator)[2:])
+   34 |+print(f"{len("xyz").numerator:b}")
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB116_FURB116.py.snap:204]: Should this comment say display-only too?

Comment (ntBre) [reply crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB116_FURB116.py.snap:204]: Oh, this is one of the 3.11 cases right?

File: crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs [hunk 10]
```diff
@@ -24,6 +25,11 @@ use crate::fix::snippet::SourceCodeSnippet;
 /// ```python
 /// print(f"{1337:b}")
 /// ```
+///
+/// ## Fix safety
+/// The fix is only marked as safe for integer literals, all other cases
+/// are unsafe, as they may change the runtime behaviour of the program
+/// or introduce syntax errors.
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs:32]: Should we update this to say "display-only" instead of "unsafe"? We could probably expand this with some of the examples of display-only cases, but I don't feel strongly about that.

**Review by ntBre — COMMENTED** [review]
Looking good! Just one question about quotes and two about docs/comments.

File: crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs (hunk 8 above)
Comment (LaBatata101) [reply crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs:196]: > Do we need the same check for single quotes? I think we might be able to do something like this:
> 
> ```rust
> if checker.target_version() <= PythonVersion::PY311 && inner_source.contains(quote.as_str()) { ... }
> ```

Yeah, I'll update the check.

File: crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs (hunk 10 above)
Comment (LaBatata101) [reply crates/ruff_linter/src/rules/refurb/rules/fstring_number_format.rs:32]: Forgot to update that.

File: crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB116_FURB116.py.snap (hunk 9 above)
Comment (LaBatata101) [reply crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB116_FURB116.py.snap:204]: This snapshot is for the latest version of Python, I think. The snapshot for python 3.11 is [this one](https://github.com/astral-sh/ruff/pull/17692/files/99b828fd0118a92a6887a28027c7073326ebf9e3..abdb2a9be64207a7bc589ac32086a984335535a4#diff-fef76f77d4f5ad382b778fd2d8b56863a4ad546181ebd0bc2e8c869d9a5c0aef), they share the same source file, so I'll just update the comment to state there's no autofix for versions 3.11 and earlier.

**Review by ntBre — APPROVED** [review]
Thanks!
