### PR TITLE
[`flake8-pytest-style`] Don't recommend `usefixtures` for parametrize values in `PT019`

### LINKED ISSUE #17599: PT019 should not recommend usefixtures for parametrize values
### Summary

Consider the following code:
```python
import pytest

@pytest.mark.parametrize("_foo", [1, 2, 3])
def test_thingy(_foo):
    print("hello")
```

When I run `ruff check --select=PT019` on it, it fails. However, according to a pytest dev replying to my question [here](https://github.com/pytest-dev/pytest/issues/13349), a value injected via `parametrize` is a fixture only due to an implementation detail that should not be relied upon. Therefore, it is inappropriate to use `@pytest.mark.usefixture` on it.

### Version

ruff 0.11.6

### PR DESCRIPTION
**Pull request by LaBatata101**
## Summary
Fixes #17599.

## Test Plan

Snapshot tests.

### CODE REVIEW

File: crates/ruff_linter/src/rules/flake8_pytest_style/rules/helpers.rs [hunk 1]
```diff
@@ -19,6 +19,19 @@ pub(super) fn get_mark_decorators(
...
+    decorators: &[Decorator],
+) -> impl Iterator<Item = &Decorator> {
+    decorators.iter().filter_map(|decorator| {
+        let name = UnqualifiedName::from_expr(map_callable(&decorator.expression))?;
+        let ["pytest", "mark", "parametrize"] = name.segments() else {
+            return None;
+        };
+
+        Some(decorator)
+    })
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/flake8_pytest_style/rules/helpers.rs:32]: We could write this slightly more tersely as

```suggestion
    decorators.iter().filter(|decorator| {
        UnqualifiedName::from_expr(map_callable(&decorator.expression))
            .is_some_and(|name| matches!(name.segments(), ["pytest", "mark", "parametrize"]))
    })
```

At that point, I wouldn't really mind just inlining this into `check_test_function_args` since the helper isn't called anywhere else, but I don't feel strongly about either part of this suggestion.

File: crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs [hunk 2]
```diff
@@ -807,10 +808,39 @@ fn check_fixture_returns(checker: &Checker, name: &str, body: &[Stmt], returns:
...
+            .arguments
+            .arguments_source_order()
+            .next()
+            .and_then(|arg| {
+                if let ArgOrKeyword::Arg(expr) = arg {
+                    expr.as_string_literal_expr()
+                } else {
+                    None
+                }
+            });
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs:827]: I think you could use something like this here:

```suggestion
        let first_arg = call_expr
            .arguments
            .find_argument_value("argnames", 0)
            .and_then(Expr::as_string_literal_expr);
```

However, based on the [docs](https://docs.pytest.org/en/stable/reference/reference.html#pytest.Metafunc.parametrize), I'm not sure the check for a string literal is entirely correct:

> Parameters:
argnames ([str](https://docs.python.org/3/library/stdtypes.html#str) | [Sequence](https://docs.python.org/3/library/typing.html#typing.Sequence)[[str](https://docs.python.org/3/library/stdtypes.html#str)]) – A comma-separated string denoting one or more argument names, or a list/tuple of argument strings.

Based on this, I think it can either be a comma-separated string or a list/tuple of strings. It also works with variables, not just literals, but that might be too rare to worry about much:

```python
import pytest

x = "test_input,expected"

@pytest.mark.parametrize(x, [("3+5", 8), ("2+4", 6), ("6*9", 42)])
def test_eval(test_input, expected):
    assert eval(test_input) == expected
```

File: crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs [hunk 3]
```diff
@@ -807,10 +808,39 @@ fn check_fixture_returns(checker: &Checker, name: &str, body: &[Stmt], returns:
...
+
+        if let Some(arg) = first_arg {
+            for param_name in arg
+                .value
+                .to_str()
+                .split(',')
+                .filter(|param| !param.is_empty() && param.starts_with('_'))
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs:834]: We may need to strip whitespace from these as well. I tried `x = "test_input, expected"` in the example above and it worked fine.

File: crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs [hunk 4]
```diff
@@ -807,10 +808,39 @@ fn check_fixture_returns(checker: &Checker, name: &str, body: &[Stmt], returns:
...
+            {
+                named_parametrize.insert(param_name);
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs:836]: I think we could `extend` with the iterator directly here instead of a loop and `insert`.

**Review by ntBre — CHANGES_REQUESTED** [review]
Thanks!

The logic here looks good. I made a couple of stylistic suggestions and also noted a couple of additional cases we may need to handle for `parameterize` argument types.

File: crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs [hunk 5]
```diff
@@ -807,10 +809,44 @@ fn check_fixture_returns(checker: &Checker, name: &str, body: &[Stmt], returns:
...
+            Some(
+                Expr::List(ast::ExprList { elts, .. }) | Expr::Tuple(ast::ExprTuple { elts, .. }),
+            ) => {
+                named_parametrize.extend(
+                    elts.iter()
+                        .filter_map(Expr::as_string_literal_expr)
+                        .map(|param| param.value.to_str().trim())
+                        .filter(|param| !param.is_empty() && param.starts_with('_')),
+                );
+            }
```
Comment (LaBatata101) [inline crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs:842]: I've used `filter_map` here, so it would ignore stuff that ins't a string literal. Do you think this is fine, or should we skip the check if the user passed something that isn't a string?

File: crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs [hunk 6]
```diff
@@ -810,31 +811,36 @@ fn check_fixture_returns(checker: &Checker, name: &str, body: &[Stmt], returns:
...
+        let first_arg = call_expr.arguments.find_argument_value("argnames", 0);
+
+        match first_arg {
+            Some(Expr::StringLiteral(ast::ExprStringLiteral { value, .. })) => {
+                named_parametrize.extend(
+                    value
+                        .to_str()
+                        .split(',')
+                        .map(str::trim)
+                        .filter(|param| !param.is_empty() && param.starts_with('_')),
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs:830]: I think the `is_empty` check is logically redundant with the `starts_with` check, but maybe it's slightly faster to filter out empty strings first? So it's probably fine to leave it.

File: crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs [hunk 7]
```diff
@@ -810,31 +811,36 @@ fn check_fixture_returns(checker: &Checker, name: &str, body: &[Stmt], returns:
...
-
-        if let Some(arg) = first_arg {
-            for param_name in arg
-                .value
-                .to_str()
-                .split(',')
-                .filter(|param| !param.is_empty() && param.starts_with('_'))
-            {
-                named_parametrize.insert(param_name);
+        let first_arg = call_expr.arguments.find_argument_value("argnames", 0);
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs:821]: Can we do `let ... else { continue }` here? That would remove the need for the `Some` wrapping in the `match` below.

File: crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs [hunk 8]
```diff
@@ -810,31 +811,36 @@ fn check_fixture_returns(checker: &Checker, name: &str, body: &[Stmt], returns:
...
+                Expr::List(ast::ExprList { elts, .. }) | Expr::Tuple(ast::ExprTuple { elts, .. }),
+            ) => {
+                named_parametrize.extend(
+                    elts.iter()
+                        .filter_map(Expr::as_string_literal_expr)
+                        .map(|param| param.value.to_str().trim())
+                        .filter(|param| !param.is_empty() && param.starts_with('_')),
+                );
             }
+            _ => {}
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs:843]: What do you think about returning if we seem an `Expr::Name` either on its own or in a list or tuple? Like I said before, I would guess that's pretty rare, but it would be easy enough to return and avoid the possibility of false positives.

**Review by ntBre — COMMENTED** [review]
Thanks! Just a couple small nits and a question. It might also be good to throw in a test for a string where trimming whitespace matters. If we add special handling for `Expr::Name`, that might deserve a test too.

File: crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs (hunk 7 above)
Comment (LaBatata101) [reply crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs:821]: Sure

File: crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs (hunk 8 above)
Comment (LaBatata101) [reply crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs:843]: Sounds good to me

File: crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs (hunk 5 above)
Comment (ntBre) [reply crates/ruff_linter/src/rules/flake8_pytest_style/rules/fixture.rs]: I think this makes sense, especially with the new `Name` check. I think strings and variables that resolve to strings are the only valid arguments here.

File: crates/ruff_linter/resources/test/fixtures/flake8_pytest_style/PT019.py [hunk 9]
```diff
@@ -38,3 +38,17 @@ def test_thingy3(_foo, _bar):  # OK defined in parametrize
...
+
+x = ["_foo", "_bar"]
+@pytest.mark.parametrize(x, [1, 2, 3])
+def test_thingy5(_foo, _bar):  # OK defined in parametrize
+    pass
+
+x = "_bar"
+@pytest.mark.parametrize(["_foo", x], [1, 2, 3])
+def test_thingy5(_foo, _bar):  # OK defined in parametrize
+    pass
```
[the remark this answers is not in the document]
Comment (LaBatata101) [reply crates/ruff_linter/resources/test/fixtures/flake8_pytest_style/PT019.py:54]: Ah ok, got it!

**Review by ntBre — APPROVED** [review]
Thanks!
