### PR TITLE
[ty] Fix `@staticmethod` combined with other decorators incorrectly binding `self`

### LINKED ISSUE #2114: `contextmanager` decorator has inconsistencies when combined with `staticmethod`
### Summary

More specifically, it does not work only when the context manager is called within the instance itself. As you can see from the snippet below, same calls are valid or not valid depending on where the context manager is called from

```py
from collections.abc import Iterator
from contextlib import contextmanager


class A:
    @staticmethod
    @contextmanager
    def my_context(num: int) -> Iterator[None]:
        yield

    def method(self) -> None:
        with self.my_context(10):  # Too many positional arguments: expected 0, got 1
            pass

with A.my_context(5):  # OK
    ...

with A().my_context(5):  # Too many positional arguments: expected 0, got 1
    ...
```

### Version

0.0.4

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

We already had `CallableTypeKind::ClassMethodLike` to track callables that behave like `classmethods` (always bind the first argument). This PR adds the symmetric `CallableTypeKind::StaticMethodLike` for callables that behave like `staticmethods` (never bind `self`).

Closes https://github.com/astral-sh/ty/issues/2114.

### CODE REVIEW

**Comment by charliermarsh** [comment]
A lot of new diagnostics but AFAICT they are correct based on how we intend to enforce Liskov per `liskov.md`? For example, in SymPy, `class Integer` defines `__abs__` as an instance method:

https://github.com/sympy/sympy/blob/221edeeada0fa2b20e89d093e1f833efec4dce30/sympy/core/numbers.py#L1890

But the subclass `Zero` defines it as a static method:

https://github.com/sympy/sympy/blob/221edeeada0fa2b20e89d093e1f833efec4dce30/sympy/core/numbers.py#L2844C1-L2846C22

**Comment by AlexWaygood** [comment]
You need to update an assertion in the benchmarks:

>   thread 'main' (4942) panicked at crates/ruff_benchmark/benches/ty_walltime.rs:78:5:
>   Expected between 1 and 13100 diagnostics on project 'sympy' but got 13106

**Comment by charliermarsh** [comment]
Thank you!

**Comment by AlexWaygood** [comment]
It would be great if that was a snapshot or something, but I think then it would be hard for it to serve its intended purpose of checking that the benchmark itself was working correctly :/

**Comment by charliermarsh** [comment]
(I think I noticed it last time when I clicked in, but I must not have looked closely enough this time, I thought it was spurious.)

File: crates/ruff_benchmark/benches/ty_walltime.rs [hunk 1]
```diff
@@ -194,7 +194,7 @@ static SYMPY: Benchmark = Benchmark::new(
         max_dep_date: "2025-06-17",
         python_version: PythonVersion::PY312,
     },
-    13100,
```
Comment (MichaReiser) [inline crates/ruff_benchmark/benches/ty_walltime.rs:197]: Feel free to bump them higher next time. E.g. 13200 or similar. The assertions only exist that we don't break the benchmarks accidentially

**Comment by carljm** [comment]
> `class Integer` defines `__abs__` as an instance method

Pyright errors on this, Pyrefly and mypy don't. It's a bit of a gray area -- when called on an instance, that's a perfectly compatible override, but if called on a type, it's not.

The rationale for not erroring on this is that calling normal methods on types is totally Liskov-broken anyway, because `self` is always overridden in a Liskov-incompatible way by default. So arguably we should error on calling normal methods on types (passing in `self` manually), but not error on this override.

But either way, this is something we can handle separately in the Liskov work.

File: crates/ty_python_semantic/resources/mdtest/final.md [hunk 2]
```diff
@@ -119,8 +119,8 @@ class OtherChild(Parent): ...
 
 class Grandchild(OtherChild):
     @staticmethod
-    # TODO: we should emit a Liskov violation here too
     # error: [override-of-final-method]
+    # error: [invalid-method-override]
```
Comment (carljm) [inline crates/ty_python_semantic/resources/mdtest/final.md:127]: I'd actually be inclined to keep a TODO here that maybe this _shouldn't_ be a Liskov violation, but I'd like to hear what @AlexWaygood thinks.

File: crates/ty_python_semantic/resources/mdtest/override.md [hunk 3]
```diff
@@ -185,7 +185,7 @@ class LiskovViolatingButNotOverrideViolating(Parent):
 
     @staticmethod
     @override
-    def class_method1() -> int: ...
+    def class_method1() -> int: ...  # error: [invalid-method-override]
```
Comment (carljm) [inline crates/ty_python_semantic/resources/mdtest/override.md:191]: I'm pretty sure this one should not be an invalid override -- I don't think there is any way you can call this method where this override would cause a problem? Whether called on the type or on an instance, it will behave the same from the caller POV -- the only difference is whether the method body gets access to `cls`, which is not a concern of Liskov.

**Review by carljm — APPROVED** [review]
Nice!

File: crates/ty_python_semantic/resources/mdtest/override.md (hunk 3 above)
Comment (carljm) [reply crates/ty_python_semantic/resources/mdtest/override.md:191]: (But I don't know that we need to do anything more about it in this PR than leave a TODO comment)

Comment (charliermarsh) [reply crates/ty_python_semantic/resources/mdtest/override.md:191]: Done.

File: crates/ty_python_semantic/resources/mdtest/final.md (hunk 2 above)
Comment (charliermarsh) [reply crates/ty_python_semantic/resources/mdtest/final.md:127]: Done.
