### PR TITLE
[`flake8-pyi`] Add "replace with `Self`" fix (`PYI019`)

### LINKED ISSUE #14183: Request: Unsafe fix for `custom-type-var-return-type`/`PYI019`
https://docs.astral.sh/ruff/rules/custom-type-var-return-type/
I feel like logically a fix for this rule should be feasible without too much complexity? (at least in pyi files and maybe py files above 3.10, see https://github.com/astral-sh/ruff/issues/9761). Useful to migrate codebases still using the old `TypeVar` way of typing `Self`. The fix should be unsafe as there's still edge-cases where using a `TypeVar` is needed (typeshed has some of those). Marking it unsafe may also simplify the logic to apply the fix (if `Self` already exists in scope)

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
## Summary

Resolves #14183.

## Test Plan

`cargo nextest run` and `cargo insta test`.

### CODE REVIEW

File: crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs [hunk 1]
```diff
@@ -230,3 +236,167 @@ fn is_likely_private_typevar(type_var_name: &str, type_params: Option<&TypeParam
...
+        "typing_extensions"
+    };
+
+    let (importer, semantic) = (checker.importer(), checker.semantic());
+    let request = ImportRequest::import_from(source_module, "Self");
+
+    let position = return_range.start();
+    let Ok((edit, ..)) = importer.get_or_import_symbol(&request, position, semantic) else {
+        return None;
+    };
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs:324]: Nit:
```suggestion
    let (edit, ..) = importer.get_or_import_symbol(&request, position, semantic).ok()?;
```

File: crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs [hunk 2]
```diff
@@ -230,3 +236,170 @@ fn is_likely_private_typevar(type_var_name: &str, type_params: Option<&TypeParam
...
+        };
+        let Expr::Name(name) = annotation else {
+            continue;
+        };
+
+        if name.id.as_str() == typevar_name {
+            let edit = Edit::range_replacement("Self".to_string(), annotation.range());
+            edits.push(edit);
+        } else {
+            // FIXME: Handle complex annotations.
```
[the remark this answers is not in the document]
Comment (MichaReiser) [reply crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs:361]: I'm not sure if we can fix complex annotations because the annotation, or at least, not all of them. For example, we can't fix: 

```
a: B | "TypeVar[A]"
```

because it would require parsing the string literal. Or at least, I don't think it's worth it. 


You could consider implementing your own `Visitor` but I'm not sure if it's worth the complexity. Maybe just handle the few common cases that you care about?

File: crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs [hunk 3]
```diff
@@ -230,3 +236,167 @@ fn is_likely_private_typevar(type_var_name: &str, type_params: Option<&TypeParam
...
+            return Err(());
+        }
+    }
+
+    Ok(edits)
+}
+
+fn remove_typevar_declaration(type_params: Option<&TypeParams>, name: &str) -> Option<Edit> {
+    let is_declaration_in_question = |type_param: &&TypeParam| -> bool {
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs:370]:
```suggestion
    let is_declaration_in_question = |type_param: &TypeParam| -> bool {
```

File: crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs [hunk 4]
```diff
@@ -230,3 +236,183 @@ fn is_likely_private_typevar(type_var_name: &str, type_params: Option<&TypeParam
...
+
+    match replace_typevar_usages_with_self(parameters, typevar_name) {
+        Ok(mut edits) => all_edits.append(&mut edits),
+        Err(mut edits) => {
+            fix_applicability = Applicability::Unsafe;
+            all_edits.append(&mut edits)
+        }
+    }
+
+    let (first, rest) = (all_edits.remove(0), all_edits);
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs:311]: To avoid relocating the entire vec (although small)

```suggestion
    let (first, rest) = (all_edits.swap_remove(0), all_edits);
```

File: crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs [hunk 5]
```diff
@@ -230,3 +236,183 @@ fn is_likely_private_typevar(type_var_name: &str, type_params: Option<&TypeParam
...
+    let (edit, ..) = importer
+        .get_or_import_symbol(&request, position, semantic)
+        .ok()?;
+
+    Some(edit)
+}
+
+fn remove_first_parameter_annotation(parameters: &Parameters) -> Edit {
+    let mut non_variadic_positional = parameters.posonlyargs.iter().chain(&parameters.args);
+    let first = &non_variadic_positional.next().unwrap().parameter;
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs:342]: The entire fix generation contains a fair amount of `unwrap` calls. Can we add comments explaining why they're "safe" or restructure the code in ways so that they aren't needed?

File: crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs [hunk 6]
```diff
@@ -230,3 +236,183 @@ fn is_likely_private_typevar(type_var_name: &str, type_params: Option<&TypeParam
...
+    if let Some(edit) = remove_typevar_declaration(type_params, typevar_name) {
+        all_edits.push(edit);
+    }
+
+    match replace_typevar_usages_with_self(parameters, typevar_name) {
+        Ok(mut edits) => all_edits.append(&mut edits),
+        Err(mut edits) => {
+            fix_applicability = Applicability::Unsafe;
+            all_edits.append(&mut edits)
+        }
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs:308]: I think we should just not provide a fix in this case or be `DisplayOnly`


```
    /// The fix is unsafe and should only be displayed for manual application by the user.
    /// The fix is likely to be incorrect or the resulting code may have invalid syntax.
    DisplayOnly,

    /// The fix is unsafe and should only be applied with user opt-in.
    /// The fix may be what the user intended, but it is uncertain; the resulting code will have valid syntax.
    Unsafe,
```

File: crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs [hunk 7]
```diff
@@ -230,3 +236,183 @@ fn is_likely_private_typevar(type_var_name: &str, type_params: Option<&TypeParam
...
+    let mut edits = vec![];
+    let mut could_not_handle_all_usages = false;
+
+    for parameter in parameters.iter().skip(1) {
+        let Some(annotation) = parameter.annotation() else {
+            continue;
+        };
+        let Expr::Name(name) = annotation else {
+            continue;
+        };
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs:367]: Shouldn't we bail in this case too?

Can we add some tests demonstrating that this code path works as expected?

File: crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs [hunk 8]
```diff
@@ -230,3 +236,183 @@ fn is_likely_private_typevar(type_var_name: &str, type_params: Option<&TypeParam
...
+    }
+
+    let (index, ..) = parameters
+        .iter()
+        .find_position(is_declaration_in_question)?;
+
+    let typevar_range = parameters[index].as_type_var().unwrap().range();
+    let last_index = parameters.len() - 1;
+
+    let range = if (0..last_index).contains(&index) {
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs:409]:
```suggestion
    let range = if index < last_index {
```

or should this include the last index? 

```
let range = if index <= last_index {

File: crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs [hunk 9]
```diff
@@ -230,3 +236,183 @@ fn is_likely_private_typevar(type_var_name: &str, type_params: Option<&TypeParam
...
+        false
+    };
+
+    let parameter_list = type_params?;
+    let parameters = &parameter_list.type_params;
+    let first = parameters.first()?;
+
+    if parameter_list.len() == 1 && is_declaration_in_question(&first) {
+        return Some(Edit::range_deletion(parameter_list.range));
+    }
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs:400]: What are cases where the function has only one parameter but `first` isn't the parameter in question? Can we remove that check? If not, then add a test case for it and ensure the code below doesn't panic with only one parameter.

File: crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs [hunk 10]
```diff
@@ -230,3 +236,183 @@ fn is_likely_private_typevar(type_var_name: &str, type_params: Option<&TypeParam
...
+
+    let (index, ..) = parameters
+        .iter()
+        .find_position(is_declaration_in_question)?;
+
+    let typevar_range = parameters[index].as_type_var().unwrap().range();
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs:406]:
```suggestion
    let typevar_range = parameters[index].range();
```

File: crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs [hunk 11]
```diff
@@ -230,3 +236,183 @@ fn is_likely_private_typevar(type_var_name: &str, type_params: Option<&TypeParam
...
+    let mut fix_applicability = Applicability::Safe;
+
+    let mut all_edits = vec![
+        replace_return_annotation_with_self(returns),
+        remove_first_parameter_annotation(parameters),
+    ];
+
+    if let Some(edit) = import_self(checker, returns.range()) {
+        all_edits.push(edit);
+    }
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs:297]: We should bail if adding the import failed or we risk generating invalid code.

File: crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs [hunk 12]
```diff
@@ -230,3 +236,183 @@ fn is_likely_private_typevar(type_var_name: &str, type_params: Option<&TypeParam
...
+
+    if let Some(edit) = remove_typevar_declaration(type_params, typevar_name) {
+        all_edits.push(edit);
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs:300]: Are there cases where the parameter isn't guaranteed to be the first parameter?

File: crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs [hunk 13]
```diff
@@ -230,3 +246,187 @@ fn is_likely_private_typevar(type_var_name: &str, type_params: Option<&TypeParam
...
+    let (mut edits, fix_applicability) = replace_typevar_usages_with_self(parameters, typevar_name);
+    all_edits.append(&mut edits);
+
+    let (first, rest) = (all_edits.swap_remove(0), all_edits);
+
+    match fix_applicability {
+        Applicability::DisplayOnly => Some(Fix::display_only_edits(first, rest)),
+        Applicability::Unsafe => Some(Fix::unsafe_edits(first, rest)),
+        Applicability::Safe => Some(Fix::safe_edits(first, rest)),
+    }
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs:325]:
```suggestion
    Fix::applicable_edits(first, rest, fix_applicability)
```

**Review by MichaReiser — APPROVED** [review]
Nice thanks!
