### PR TITLE
`--show-settings` displays active settings in a far more readable format

### LINKED ISSUE #8334: Create `Display` implementation for `Settings`
`ruff check . --show-settings` prints the settings using the `Debug` implementation. The result is that it prints our internal representation, which is hard to read (even impossible)

https://github.com/astral-sh/ruff/blob/fe485d791cc206391103cb44e53d9c77e2ab42fc/crates/ruff_cli/src/commands/show_settings.rs#L38

<details>
<summary>Current output</summary>
<pre>
Resolved settings for: "/Users/micha/astral/ruff/crates/flake8_to_ruff/examples/cryptography/pyproject.toml"
Settings path: "/Users/micha/astral/ruff/pyproject.toml"
Settings {
    cache_dir: "/Users/micha/astral/ruff/.ruff_cache",
    fix: false,
    fix_only: false,
    unsafe_fixes: Disabled,
    output_format: Text,
    show_fixes: false,
    show_source: false,
    file_resolver: FileResolverSettings {
        exclude: FilePatternSet {
            set: GlobSet {
                len: 25,
                strats: [
                    Extension(
                        ExtensionStrategy(
                            {},
                        ),
                    ),
                    BasenameLiteral(
                        BasenameLiteralStrategy(
                            {},
                        ),
                    ),
                    Literal(
                        LiteralStrategy(
                            {
                                [
                                    46,
                                    98,
                                    122,
                                    114,
                                ]: [
                                    0,
                                ],
                                [
                                    46,
                                    100,
                                    105,
                                    114,
                                    101,
                                    110,
                                    118,
                                ]: [
                                    1,
                                ],
                                [
                                    46,
                                    101,
                                    103,
                                    103,
                                    115,
                                ]: [
                                    2,
                                ],
                                [
                                    46,
                                    103,
                                    105,
                                    116,
                                ]: [
                                    3,
                                ],
                                [
                                    46,
                                    103,
                                    105,
                                    116,
                                    45,
                                    114,
                                    101,
                                    119,
                                    114,
                                    105,
                                    116,
                                    101,
                                ]: [
                                    4,
                                ],
                                [
                                    46,
                                    104,
                                    103,
                                ]: [
                                    5,
                                ],
                                [
                                    46,
                                    105,
                                    112,
                                    121,
                                    110,
                                    98,
                                    95,
                                    99,
                                    104,
                                    101,
                                    99,
                                    107,
                                    112,
                                    111,
                                    105,
                                    110,
                                    116,
                                    115,
                                ]: [
                                    6,
                                ],
                                [
                                    46,
                                    109,
                                    121,
                                    112,
                                    121,
                                    95,
                                    99,
                                    97,
                                    99,
                                    104,
                                    101,
                                ]: [
                                    7,
                                ],
                                [
                                    46,
                                    110,
                                    111,
                                    120,
                                ]: [
                                    8,
                                ],
                                [
                                    46,
                                    112,
                                    97,
                                    110,
                                    116,
                                    115,
                                    46,
                                    100,
                                ]: [
                                    9,
                                ],
                                [
                                    46,
                                    112,
                                    121,
                                    101,
                                    110,
                                    118,
                                ]: [
                                    10,
                                ],
                                [
                                    46,
                                    112,
                                    121,
                                    116,
                                    101,
                                    115,
                                    116,
                                    95,
                                    99,
                                    97,
                                    99,
                                    104,
                                    101,
                                ]: [
                                    11,
                                ],
                                [
                                    46,
                                    112,
                                    121,
                                    116,
                                    121,
                                    112,
                                    101,
                                ]: [
                                    12,
                                ],
                                [
                                    46,
                                    114,
                                    117,
                                    102,
                                    102,
                                    95,
                                    99,
                                    97,
                                    99,
                                    104,
                                    101,
                                ]: [
                                    13,
                                ],
                                [
                                    46,
                                    115,
                                    118,
                                    110,
                                ]: [
                                    14,
                                ],
                                [
                                    46,
                                    116,
                                    111,
                                    120,
                                ]: [
                                    15,
                                ],
                                [
                                    46,
                                    118,
                                    101,
                                    110,
                                    118,
                                ]: [
                                    16,
                                ],
                                [
                                    46,
                                    118,
                                    115,
                                    99,
                                    111,
                                    100,
                                    101,
                                ]: [
                                    17,
                                ],
                                [
                                    95,
                                    95,
                                    112,
                                    121,
                                    112,
                                    97,
                                    99,
                                    107,
                                    97,
                                    103,
                                    101,
                                    115,
                                    95,
                                    95,
                                ]: [
                                    18,
                                ],
                                [
                                    95,
                                    98,
                                    117,
                                    105,
                                    108,
                                    100,
                                ]: [
                                    19,
                                ],
                                [
                                    98,
                                    117,
                                    99,
                                    107,
                                    45,
                                    111,
                                    117,
                                    116,
                                ]: [
                                    20,
                                ],
                                [
                                    98,
                                    117,
                                    105,
                                    108,
                                    100,
                                ]: [
                                    21,
                                ],
                                [
                                    100,
                                    105,
                                    115,
                                    116,
                                ]: [
                                    22,
                                ],
                                [
                                    110,
                                    111,
                                    100,
                                    101,
                                    95,
                                    109,
                                    111,
                                    100,
                                    117,
                                    108,
                                    101,
                                    115,
                                ]: [
                                    23,
                                ],
                                [
                                    118,
                                    101,
                                    110,
                                    118,
                                ]: [
                                    24,
                                ],
                            },
                        ),
                    ),
                    Suffix(
                        SuffixStrategy {
                            matcher: AhoCorasick(
                                dfa::DFA(
                                D 000000: \x00 => 0
                                F 000001:
                                 >000002: \x00 => 2
                                  000003: \x00 => 0
                                match kind: Standard
                                prefilter: false
                                state length: 4
                                pattern length: 0
                                shortest pattern length: 18446744073709551615
                                longest pattern length: 0
                                alphabet length: 1
                                stride: 1
                                byte classes: ByteClasses(0 => [0-255])
                                memory usage: 16
                                )
                                ,
                            ),
                            map: [],
                            longest: 0,
                        },
                    ),
                    Prefix(
                        PrefixStrategy {
                            matcher: AhoCorasick(
                                dfa::DFA(
                                D 000000: \x00 => 0
                                F 000001:
                                 >000002: \x00 => 2
                                  000003: \x00 => 0
                                match kind: Standard
                                prefilter: false
                                state length: 4
                                pattern length: 0
                                shortest pattern length: 18446744073709551615
                                longest pattern length: 0
                                alphabet length: 1
                                stride: 1
                                byte classes: ByteClasses(0 => [0-255])
                                memory usage: 16
                                )
                                ,
                            ),
                            map: [],
                            longest: 0,
                        },
                    ),
                    RequiredExtension(
                        RequiredExtensionStrategy(
                            {},
                        ),
                    ),
                    Regex(
                        RegexSetStrategy {
                            matcher: RegexSet([]),
                            map: [],
                        },
                    ),
                ],
            },
            cache_key: 10629084736300657394,
        },
        extend_exclude: FilePatternSet {
            set: GlobSet {
                len: 2,
                strats: [
                    Extension(
                        ExtensionStrategy(
                            {},
                        ),
                    ),
                    BasenameLiteral(
                        BasenameLiteralStrategy(
                            {},
                        ),
                    ),
                    Literal(
                        LiteralStrategy(
                            {
                                [
                                    47,
                                    85,
                                    115,
                                    101,
                                    114,
                                    115,
                                    47,
                                    109,
                                    105,
                                    99,
                                    104,
                                    97,
                                    47,
                                    97,
                                    115,
                                    116,
                                    114,
                                    97,
                                    108,
                                    47,
                                    114,
                                    117,
                                    102,
                                    102,
                                    47,
                                    99,
                                    114,
                                    97,
                                    116,
                                    101,
                                    115,
                                    47,
                                    114,
                                    117,
                                    102,
                                    102,
                                    95,
                                    108,
                                    105,
                                    110,
                                    116,
                                    101,
                                    114,
                                    47,
                                    114,
                                    101,
                                    115,
                                    111,
                                    117,
                                    114,
                                    99,
                                    101,
                                    115,
                                ]: [
                                    0,
                                ],
                                [
                                    47,
                                    85,
                                    115,
                                    101,
                                    114,
                                    115,
                                    47,
                                    109,
                                    105,
                                    99,
                                    104,
                                    97,
                                    47,
                                    97,
                                    115,
                                    116,
                                    114,
                                    97,
                                    108,
                                    47,
                                    114,
                                    117,
                                    102,
                                    102,
                                    47,
                                    99,
                                    114,
                                    97,
                                    116,
                                    101,
                                    115,
                                    47,
                                    114,
                                    117,
                                    102,
                                    102,
                                    95,
                                    112,
                                    121,
                                    116,
                                    104,
                                    111,
                                    110,
                                    95,
                                    102,
                                    111,
                                    114,
                                    109,
                                    97,
                                    116,
                                    116,
                                    101,
                                    114,
                                    47,
                                    114,
                                    101,
                                    115,
                                    111,
                                    117,
                                    114,
                                    99,
                                    101,
                                    115,
                                ]: [
                                    1,
                                ],
                            },
                        ),
                    ),
                    Suffix(
                        SuffixStrategy {
                            matcher: AhoCorasick(
                                dfa::DFA(
                                D 000000: \x00 => 0
                                F 000001:
                                 >000002: \x00 => 2
                                  000003: \x00 => 0
                                match kind: Standard
                                prefilter: false
                                state length: 4
                                pattern length: 0
                                shortest pattern length: 18446744073709551615
                                longest pattern length: 0
                                alphabet length: 1
                                stride: 1
                                byte classes: ByteClasses(0 => [0-255])
                                memory usage: 16
                                )
                                ,
                            ),
                            map: [],
                            longest: 0,
                        },
                    ),
                    Prefix(
                        PrefixStrategy {
                            matcher: AhoCorasick(
                                dfa::DFA(
                                D 000000: \x00 => 0
                                F 000001:
                                 >000002: \x00 => 2
                                  000003: \x00 => 0
                                match kind: Standard
                                prefilter: false
                                state length: 4
                                pattern length: 0
                                shortest pattern length: 18446744073709551615
                                longest pattern length: 0
                                alphabet length: 1
                                stride: 1
                                byte classes: ByteClasses(0 => [0-255])
                                memory usage: 16
                                )
                                ,
                            ),
                            map: [],
                            longest: 0,
                        },
                    ),
                    RequiredExtension(
                        RequiredExtensionStrategy(
                            {},
                        ),
                    ),
                    Regex(
                        RegexSetStrategy {
                            matcher: RegexSet([]),
                            map: [],
                        },
                    ),
                ],
            },
            cache_key: 10840170291812037825,
        },
        force_exclude: false,
        include: FilePatternSet {
            set: GlobSet {
                len: 3,
                strats: [
                    Extension(
                        ExtensionStrategy(
                            {
                                [
                                    46,
                                    112,
                                    121,
                                    105,
                                ]: [
                                    1,
                                ],
                                [
                                    46,
                                    112,
                                    121,
                                ]: [
                                    0,
                                ],
                            },
                        ),
                    ),
                    BasenameLiteral(
                        BasenameLiteralStrategy(
                            {
                                [
                                    112,
                                    121,
                                    112,
                                    114,
                                    111,
                                    106,
                                    101,
                                    99,
                                    116,
                                    46,
                                    116,
                                    111,
                                    109,
                                    108,
                                ]: [
                                    2,
                                ],
                            },
                        ),
                    ),
                    Literal(
                        LiteralStrategy(
                            {},
                        ),
                    ),
                    Suffix(
                        SuffixStrategy {
                            matcher: AhoCorasick(
                                dfa::DFA(
                                D 000000: \x00 => 0
                                F 000001:
                                 >000002: \x00 => 2
                                  000003: \x00 => 0
                                match kind: Standard
                                prefilter: false
                                state length: 4
                                pattern length: 0
                                shortest pattern length: 18446744073709551615
                                longest pattern length: 0
                                alphabet length: 1
                                stride: 1
                                byte classes: ByteClasses(0 => [0-255])
                                memory usage: 16
                                )
                                ,
                            ),
                            map: [],
                            longest: 0,
                        },
                    ),
                    Prefix(
                        PrefixStrategy {
                            matcher: AhoCorasick(
                                dfa::DFA(
                                D 000000: \x00 => 0
                                F 000001:
                                 >000002: \x00 => 2
                                  000003: \x00 => 0
                                match kind: Standard
                                prefilter: false
                                state length: 4
                                pattern length: 0
                                shortest pattern length: 18446744073709551615
                                longest pattern length: 0
                                alphabet length: 1
                                stride: 1
                                byte classes: ByteClasses(0 => [0-255])
                                memory usage: 16
                                )
                                ,
                            ),
                            map: [],
                            longest: 0,
                        },
                    ),
                    RequiredExtension(
                        RequiredExtensionStrategy(
                            {},
                        ),
                    ),
                    Regex(
                        RegexSetStrategy {
                            matcher: RegexSet([]),
                            map: [],
                        },
                    ),
                ],
            },
            cache_key: 787281028166742793,
        },
        extend_include: FilePatternSet {
            set: GlobSet {
                len: 0,
                strats: [],
            },
            cache_key: 14492805990617963705,
        },
        respect_gitignore: true,
        project_root: "/Users/micha/astral/ruff",
    },
    linter: LinterSettings {
        exclude: FilePatternSet {
            set: GlobSet {
                len: 0,
                strats: [],
            },
            cache_key: 14492805990617963705,
        },
        project_root: "/Users/micha/astral/ruff",
        rules: RuleTable {
            enabled: {
                MultipleImportsOnOneLine,
                ModuleImportNotAtTopOfFile,
                MultipleStatementsOnOneLineColon,
                MultipleStatementsOnOneLineSemicolon,
                UselessSemicolon,
                NoneComparison,
                TrueFalseComparison,
                NotInTest,
                NotIsTest,
                TypeComparison,
                BareExcept,
                LambdaAssignment,
                AmbiguousVariableName,
                AmbiguousClassName,
                AmbiguousFunctionName,
                IOError,
                SyntaxError,
                UnusedImport,
                ImportShadowedByLoopVar,
                UndefinedLocalWithImportStar,
                LateFutureImport,
                UndefinedLocalWithImportStarUsage,
                UndefinedLocalWithNestedImportStarUsage,
                FutureFeatureNotDefined,
                PercentFormatInvalidFormat,
                PercentFormatExpectedMapping,
                PercentFormatExpectedSequence,
                PercentFormatExtraNamedArguments,
                PercentFormatMissingArgument,
                PercentFormatMixedPositionalAndNamed,
                PercentFormatPositionalCountMismatch,
                PercentFormatStarRequiresSequence,
                PercentFormatUnsupportedFormatCharacter,
                StringDotFormatInvalidFormat,
                StringDotFormatExtraNamedArguments,
                StringDotFormatExtraPositionalArguments,
                StringDotFormatMissingArguments,
                StringDotFormatMixingAutomatic,
                FStringMissingPlaceholders,
                MultiValueRepeatedKeyLiteral,
                MultiValueRepeatedKeyVariable,
                ExpressionsInStarAssignment,
                MultipleStarredExpressions,
                AssertTuple,
                IsLiteral,
                InvalidPrintSyntax,
                IfTuple,
                BreakOutsideLoop,
                ContinueOutsideLoop,
                YieldOutsideFunction,
                ReturnOutsideFunction,
                DefaultExceptNotLast,
                ForwardAnnotationSyntaxError,
                RedefinedWhileUnused,
                UndefinedName,
                UndefinedExport,
                UndefinedLocal,
                UnusedVariable,
                UnusedAnnotation,
                RaiseNotImplemented,
            },
            should_fix: {
                MultipleImportsOnOneLine,
                ModuleImportNotAtTopOfFile,
                MultipleStatementsOnOneLineColon,
                MultipleStatementsOnOneLineSemicolon,
                UselessSemicolon,
                NoneComparison,
                TrueFalseComparison,
                NotInTest,
                NotIsTest,
                TypeComparison,
                BareExcept,
                LambdaAssignment,
                AmbiguousVariableName,
                AmbiguousClassName,
                AmbiguousFunctionName,
                IOError,
                SyntaxError,
                UnusedImport,
                ImportShadowedByLoopVar,
                UndefinedLocalWithImportStar,
                LateFutureImport,
                UndefinedLocalWithImportStarUsage,
                UndefinedLocalWithNestedImportStarUsage,
                FutureFeatureNotDefined,
                PercentFormatInvalidFormat,
                PercentFormatExpectedMapping,
                PercentFormatExpectedSequence,
                PercentFormatExtraNamedArguments,
                PercentFormatMissingArgument,
                PercentFormatMixedPositionalAndNamed,
                PercentFormatPositionalCountMismatch,
                PercentFormatStarRequiresSequence,
                PercentFormatUnsupportedFormatCharacter,
                StringDotFormatInvalidFormat,
                StringDotFormatExtraNamedArguments,
                StringDotFormatExtraPositionalArguments,
                StringDotFormatMissingArguments,
                StringDotFormatMixingAutomatic,
                FStringMissingPlaceholders,
                MultiValueRepeatedKeyLiteral,
                MultiValueRepeatedKeyVariable,
                ExpressionsInStarAssignment,
                MultipleStarredExpressions,
                AssertTuple,
                IsLiteral,
                InvalidPrintSyntax,
                IfTuple,
                BreakOutsideLoop,
                ContinueOutsideLoop,
                YieldOutsideFunction,
                ReturnOutsideFunction,
                DefaultExceptNotLast,
                ForwardAnnotationSyntaxError,
                RedefinedWhileUnused,
                UndefinedName,
                UndefinedExport,
                UndefinedLocal,
                UnusedVariable,
                UnusedAnnotation,
                RaiseNotImplemented,
            },
        },
        per_file_ignores: [],
        extend_unsafe_fixes: {},
        extend_safe_fixes: {},
        target_version: Py37,
        preview: Disabled,
        explicit_preview_rules: false,
        allowed_confusables: {},
        builtins: [],
        dummy_variable_rgx: Regex(
            "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$",
        ),
        external: [],
        ignore_init_module_imports: false,
        logger_objects: [],
        namespace_packages: [],
        src: [
            "/Users/micha/astral/ruff",
        ],
        tab_size: IndentWidth(
            4,
        ),
        line_length: LineLength(
            88,
        ),
        task_tags: [
            "TODO",
            "FIXME",
            "XXX",
        ],
        typing_modules: [],
        flake8_annotations: Settings {
            mypy_init_return: false,
            suppress_dummy_args: false,
            suppress_none_returning: false,
            allow_star_arg_any: false,
            ignore_fully_untyped: false,
        },
        flake8_bandit: Settings {
            hardcoded_tmp_directory: [
                "/tmp",
                "/var/tmp",
                "/dev/shm",
            ],
            check_typed_exception: false,
        },
        flake8_bugbear: Settings {
            extend_immutable_calls: [],
        },
        flake8_builtins: Settings {
            builtins_ignorelist: [],
        },
        flake8_comprehensions: Settings {
            allow_dict_calls_with_keyword_arguments: false,
        },
        flake8_copyright: Settings {
            notice_rgx: Regex(
                "(?i)Copyright\\s+(\\(C\\)\\s+)?\\d{4}(-\\d{4})*",
            ),
            author: None,
            min_file_size: 0,
        },
        flake8_errmsg: Settings {
            max_string_length: 0,
        },
        flake8_gettext: Settings {
            functions_names: [
                "_",
                "gettext",
                "ngettext",
            ],
        },
        flake8_implicit_str_concat: Settings {
            allow_multiline: true,
        },
        flake8_import_conventions: Settings {
            aliases: {
                "matplotlib": "mpl",
                "matplotlib.pyplot": "plt",
                "pandas": "pd",
                "seaborn": "sns",
                "tensorflow": "tf",
                "networkx": "nx",
                "plotly.express": "px",
                "polars": "pl",
                "numpy": "np",
                "panel": "pn",
                "pyarrow": "pa",
                "altair": "alt",
                "tkinter": "tk",
                "holoviews": "hv",
            },
            banned_aliases: {},
            banned_from: {},
        },
        flake8_pytest_style: Settings {
            fixture_parentheses: true,
            parametrize_names_type: Tuple,
            parametrize_values_type: List,
            parametrize_values_row_type: Tuple,
            raises_require_match_for: [
                Pattern {
                    original: "BaseException",
                    tokens: [
                        Char(
                            'B',
                        ),
                        Char(
                            'a',
                        ),
                        Char(
                            's',
                        ),
                        Char(
                            'e',
                        ),
                        Char(
                            'E',
                        ),
                        Char(
                            'x',
                        ),
                        Char(
                            'c',
                        ),
                        Char(
                            'e',
                        ),
                        Char(
                            'p',
                        ),
                        Char(
                            't',
                        ),
                        Char(
                            'i',
                        ),
                        Char(
                            'o',
                        ),
                        Char(
                            'n',
                        ),
                    ],
                    is_recursive: false,
                },
                Pattern {
                    original: "Exception",
                    tokens: [
                        Char(
                            'E',
                        ),
                        Char(
                            'x',
                        ),
                        Char(
                            'c',
                        ),
                        Char(
                            'e',
                        ),
                        Char(
                            'p',
                        ),
                        Char(
                            't',
                        ),
                        Char(
                            'i',
                        ),
                        Char(
                            'o',
                        ),
                        Char(
                            'n',
                        ),
                    ],
                    is_recursive: false,
                },
                Pattern {
                    original: "ValueError",
                    tokens: [
                        Char(
                            'V',
                        ),
                        Char(
                            'a',
                        ),
                        Char(
                            'l',
                        ),
                        Char(
                            'u',
                        ),
                        Char(
                            'e',
                        ),
                        Char(
                            'E',
                        ),
                        Char(
                            'r',
                        ),
                        Char(
                            'r',
                        ),
                        Char(
                            'o',
                        ),
                        Char(
                            'r',
                        ),
                    ],
                    is_recursive: false,
                },
                Pattern {
                    original: "OSError",
                    tokens: [
                        Char(
                            'O',
                        ),
                        Char(
                            'S',
                        ),
                        Char(
                            'E',
                        ),
                        Char(
                            'r',
                        ),
                        Char(
                            'r',
                        ),
                        Char(
                            'o',
                        ),
                        Char(
                            'r',
                        ),
                    ],
                    is_recursive: false,
                },
                Pattern {
                    original: "IOError",
                    tokens: [
                        Char(
                            'I',
                        ),
                        Char(
                            'O',
                        ),
                        Char(
                            'E',
                        ),
                        Char(
                            'r',
                        ),
                        Char(
                            'r',
                        ),
                        Char(
                            'o',
                        ),
                        Char(
                            'r',
                        ),
                    ],
                    is_recursive: false,
                },
                Pattern {
                    original: "EnvironmentError",
                    tokens: [
                        Char(
                            'E',
                        ),
                        Char(
                            'n',
                        ),
                        Char(
                            'v',
                        ),
                        Char(
                            'i',
                        ),
                        Char(
                            'r',
                        ),
                        Char(
                            'o',
                        ),
                        Char(
                            'n',
                        ),
                        Char(
                            'm',
                        ),
                        Char(
                            'e',
                        ),
                        Char(
                            'n',
                        ),
                        Char(
                            't',
                        ),
                        Char(
                            'E',
                        ),
                        Char(
                            'r',
                        ),
                        Char(
                            'r',
                        ),
                        Char(
                            'o',
                        ),
                        Char(
                            'r',
                        ),
                    ],
                    is_recursive: false,
                },
                Pattern {
                    original: "socket.error",
                    tokens: [
                        Char(
                            's',
                        ),
                        Char(
                            'o',
                        ),
                        Char(
                            'c',
                        ),
                        Char(
                            'k',
                        ),
                        Char(
                            'e',
                        ),
                        Char(
                            't',
                        ),
                        Char(
                            '.',
                        ),
                        Char(
                            'e',
                        ),
                        Char(
                            'r',
                        ),
                        Char(
                            'r',
                        ),
                        Char(
                            'o',
                        ),
                        Char(
                            'r',
                        ),
                    ],
                    is_recursive: false,
                },
            ],
            raises_extend_require_match_for: [],
            mark_parentheses: true,
        },
        flake8_quotes: Settings {
            inline_quotes: Double,
            multiline_quotes: Double,
            docstring_quotes: Double,
            avoid_escape: true,
        },
        flake8_self: Settings {
            ignore_names: [
                "_make",
                "_asdict",
                "_replace",
                "_fields",
                "_field_defaults",
                "_name_",
                "_value_",
            ],
        },
        flake8_tidy_imports: Settings {
            ban_relative_imports: Parents,
            banned_api: {},
            banned_module_level_imports: [],
        },
        flake8_type_checking: Settings {
            strict: false,
            exempt_modules: [
                "typing",
            ],
            runtime_evaluated_base_classes: [],
            runtime_evaluated_decorators: [],
        },
        flake8_unused_arguments: Settings {
            ignore_variadic_names: false,
        },
        isort: Settings {
            required_imports: {},
            combine_as_imports: false,
            force_single_line: false,
            force_sort_within_sections: false,
            case_sensitive: false,
            force_wrap_aliases: false,
            force_to_top: {},
            known_modules: KnownModules {
                known: [],
                has_submodules: false,
            },
            detect_same_package: true,
            order_by_type: true,
            relative_imports_order: FurthestToClosest,
            single_line_exclusions: {},
            split_on_trailing_comma: true,
            classes: {},
            constants: {},
            variables: {},
            no_lines_before: {},
            lines_after_imports: -1,
            lines_between_types: 0,
            forced_separate: [],
            section_order: [
                Known(
                    Future,
                ),
                Known(
                    StandardLibrary,
                ),
                Known(
                    ThirdParty,
                ),
                Known(
                    FirstParty,
                ),
                Known(
                    LocalFolder,
                ),
            ],
        },
        mccabe: Settings {
            max_complexity: 10,
        },
        pep8_naming: Settings {
            ignore_names: [
                Pattern {
                    original: "setUp",
                    tokens: [
                        Char(
                            's',
                        ),
                        Char(
                            'e',
                        ),
                        Char(
                            't',
                        ),
                        Char(
                            'U',
                        ),
                        Char(
                            'p',
                        ),
                    ],
                    is_recursive: false,
                },
                Pattern {
                    original: "tearDown",
                    tokens: [
                        Char(
                            't',
                        ),
                        Char(
                            'e',
                        ),
                        Char(
                            'a',
                        ),
                        Char(
                            'r',
                        ),
                        Char(
                            'D',
                        ),
                        Char(
                            'o',
                        ),
                        Char(
                            'w',
                        ),
                        Char(
                            'n',
                        ),
                    ],
                    is_recursive: false,
                },
                Pattern {
                    original: "setUpClass",
                    tokens: [
                        Char(
                            's',
                        ),
                        Char(
                            'e',
                        ),
                        Char(
                            't',
                        ),
                        Char(
                            'U',
                        ),
                        Char(
                            'p',
                        ),
                        Char(
                            'C',
                        ),
                        Char(
                            'l',
                        ),
                        Char(
                            'a',
                        ),
                        Char(
                            's',
                        ),
                        Char(
                            's',
                        ),
                    ],
                    is_recursive: false,
                },
                Pattern {
                    original: "tearDownClass",
                    tokens: [
                        Char(
                            't',
                        ),
                        Char(
                            'e',
                        ),
                        Char(
                            'a',
                        ),
                        Char(
                            'r',
                        ),
                        Char(
                            'D',
                        ),
                        Char(
                            'o',
                        ),
                        Char(
                            'w',
                        ),
                        Char(
                            'n',
                        ),
                        Char(
                            'C',
                        ),
                        Char(
                            'l',
                        ),
                        Char(
                            'a',
                        ),
                        Char(
                            's',
                        ),
                        Char(
                            's',
                        ),
                    ],
                    is_recursive: false,
                },
                Pattern {
                    original: "setUpModule",
                    tokens: [
                        Char(
                            's',
                        ),
                        Char(
                            'e',
                        ),
                        Char(
                            't',
                        ),
                        Char(
                            'U',
                        ),
                        Char(
                            'p',
                        ),
                        Char(
                            'M',
                        ),
                        Char(
                            'o',
                        ),
                        Char(
                            'd',
                        ),
                        Char(
                            'u',
                        ),
                        Char(
                            'l',
                        ),
                        Char(
                            'e',
                        ),
                    ],
                    is_recursive: false,
                },
                Pattern {
                    original: "tearDownModule",
                    tokens: [
                        Char(
                            't',
                        ),
                        Char(
                            'e',
                        ),
                        Char(
                            'a',
                        ),
                        Char(
                            'r',
                        ),
                        Char(
                            'D',
                        ),
                        Char(
                            'o',
                        ),
                        Char(
                            'w',
                        ),
                        Char(
                            'n',
                        ),
                        Char(
                            'M',
                        ),
                        Char(
                            'o',
                        ),
                        Char(
                            'd',
                        ),
                        Char(
                            'u',
                        ),
                        Char(
                            'l',
                        ),
                        Char(
                            'e',
                        ),
                    ],
                    is_recursive: false,
                },
                Pattern {
                    original: "asyncSetUp",
                    tokens: [
                        Char(
                            'a',
                        ),
                        Char(
                            's',
                        ),
                        Char(
                            'y',
                        ),
                        Char(
                            'n',
                        ),
                        Char(
                            'c',
                        ),
                        Char(
                            'S',
                        ),
                        Char(
                            'e',
                        ),
                        Char(
                            't',
                        ),
                        Char(
                            'U',
                        ),
                        Char(
                            'p',
                        ),
                    ],
                    is_recursive: false,
                },
                Pattern {
                    original: "asyncTearDown",
                    tokens: [
                        Char(
                            'a',
                        ),
                        Char(
                            's',
                        ),
                        Char(
                            'y',
                        ),
                        Char(
                            'n',
                        ),
                        Char(
                            'c',
                        ),
                        Char(
                            'T',
                        ),
                        Char(
                            'e',
                        ),
                        Char(
                            'a',
                        ),
                        Char(
                            'r',
                        ),
                        Char(
                            'D',
                        ),
                        Char(
                            'o',
                        ),
                        Char(
                            'w',
                        ),
                        Char(
                            'n',
                        ),
                    ],
                    is_recursive: false,
                },
                Pattern {
                    original: "setUpTestData",
                    tokens: [
                        Char(
                            's',
                        ),
                        Char(
                            'e',
                        ),
                        Char(
                            't',
                        ),
                        Char(
                            'U',
                        ),
                        Char(
                            'p',
                        ),
                        Char(
                            'T',
                        ),
                        Char(
                            'e',
                        ),
                        Char(
                            's',
                        ),
                        Char(
                            't',
                        ),
                        Char(
                            'D',
                        ),
                        Char(
                            'a',
                        ),
                        Char(
                            't',
                        ),
                        Char(
                            'a',
                        ),
                    ],
                    is_recursive: false,
                },
                Pattern {
                    original: "failureException",
                    tokens: [
                        Char(
                            'f',
                        ),
                        Char(
                            'a',
                        ),
                        Char(
                            'i',
                        ),
                        Char(
                            'l',
                        ),
                        Char(
                            'u',
                        ),
                        Char(
                            'r',
                        ),
                        Char(
                            'e',
                        ),
                        Char(
                            'E',
                        ),
                        Char(
                            'x',
                        ),
                        Char(
                            'c',
                        ),
                        Char(
                            'e',
                        ),
                        Char(
                            'p',
                        ),
                        Char(
                            't',
                        ),
                        Char(
                            'i',
                        ),
                        Char(
                            'o',
                        ),
                        Char(
                            'n',
                        ),
                    ],
                    is_recursive: false,
                },
                Pattern {
                    original: "longMessage",
                    tokens: [
                        Char(
                            'l',
                        ),
                        Char(
                            'o',
                        ),
                        Char(
                            'n',
                        ),
                        Char(
                            'g',
                        ),
                        Char(
                            'M',
                        ),
                        Char(
                            'e',
                        ),
                        Char(
                            's',
                        ),
                        Char(
                            's',
                        ),
                        Char(
                            'a',
                        ),
                        Char(
                            'g',
                        ),
                        Char(
                            'e',
                        ),
                    ],
                    is_recursive: false,
                },
                Pattern {
                    original: "maxDiff",
                    tokens: [
                        Char(
                            'm',
                        ),
                        Char(
                            'a',
                        ),
                        Char(
                            'x',
                        ),
                        Char(
                            'D',
                        ),
                        Char(
                            'i',
                        ),
                        Char(
                            'f',
                        ),
                        Char(
                            'f',
                        ),
                    ],
                    is_recursive: false,
                },
            ],
            classmethod_decorators: [],
            staticmethod_decorators: [],
        },
        pycodestyle: Settings {
            max_line_length: LineLength(
                88,
            ),
            max_doc_length: None,
            ignore_overlong_task_comments: false,
        },
        pydocstyle: Settings {
            convention: None,
            ignore_decorators: {},
            property_decorators: {},
        },
        pyflakes: Settings {
            extend_generics: [],
        },
        pylint: Settings {
            allow_magic_value_types: [
                Str,
                Bytes,
            ],
            max_args: 5,
            max_returns: 6,
            max_bool_expr: 5,
            max_branches: 12,
            max_statements: 50,
            max_public_methods: 20,
        },
        pyupgrade: Settings {
            keep_runtime_typing: false,
        },
    },
    formatter: FormatterSettings {
        exclude: FilePatternSet {
            set: GlobSet {
                len: 0,
                strats: [],
            },
            cache_key: 14492805990617963705,
        },
        preview: Disabled,
        line_width: LineWidth(
            88,
        ),
        indent_style: Space,
        indent_width: IndentWidth(
            4,
        ),
        quote_style: Double,
        magic_trailing_comma: Respect,
        line_ending: Auto,
    },
}
</pre>
</details>

We should instead use the Setting's (not yet existing) `Display` implementation and ensure we print human readable values for each setting.

### PR DESCRIPTION
**Pull request by InquisitivePenguin**
## Summary

Fixes #8334.

`Display` has been implemented for `ruff_workspace::Settings`, which gives a much nicer and more readable output to `--show-settings`. 

Internally, a `display_settings` utility macro has been implemented to reduce the boilerplate of the display code.

### Work to be done

- [x] A lot of formatting for `Vec<_>` and `HashSet<_>` types have been stubbed out, using `Debug` as a fallback. There should be a way to add generic formatting support for these types as a modifier in `display_settings`.
- [x] Several complex types were also stubbed out and need proper `Display` implementations rather than falling back on `Debug`.
- [x] An open question needs to be answered: how important is it that the output be valid TOML? Some types in settings, such as a hash-map from a glob pattern to a multi-variant enum, will be hard to rework into valid _and_ readable TOML.
- [x] Tests need to be implemented.

## Test Plan

Tests consist of a snapshot test for the default `--show-settings` output and a doctest for `display_settings!`.

### CODE REVIEW

File: crates/ruff_linter/src/registry/rule_set.rs [hunk 1]
```diff
@@ -269,6 +270,22 @@ impl Debug for RuleSet {
...
+        } else {
+            write!(
+                f,
+                "[\n\t{}\n]",
+                self.iter()
+                    .map(|rule| format!("\"{rule:?}\""))
+                    .join(",\n\t")
+            )
+        }
+    }
```
Comment (MichaReiser) [inline crates/ruff_linter/src/registry/rule_set.rs:286]: Would `f.debug_list` be useful here? 

Not that this part is performance sensitive but we can avoid allocating a string for each rule by using a for loop

```rust
write!(f, "[\n\t")?;

for rule in self.iter() {
	write!(f, "\"{rule:?}\"")?;
}

write!(f, "\n]")
```

Joking: We could use our formatter infrastructure to print the rules on a single line if they fit into an 80-character line length and split them when they do not :laughing:

File: crates/ruff_linter/src/rules/isort/categorize.rs [hunk 2]
```diff
@@ -378,3 +380,20 @@ impl KnownModules {
         user_defined
     }
 }
+
+impl fmt::Display for KnownModules {
+    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/isort/categorize.rs:385]: Nit: Same as above. A traditional for loop can help to avoid the inner `format!` call (which allocates a string, if Rust isn't clever enough to optimise it away)

File: crates/ruff_linter/src/settings/mod.rs [hunk 3]
```diff
@@ -38,13 +41,34 @@ pub mod flags;
 pub mod rule_table;
 pub mod types;
 
+#[macro_export]
+macro_rules! display_settings {
```
Comment (MichaReiser) [inline crates/ruff_linter/src/settings/mod.rs:45]: I think some documentation would help to demystify the macro :) (what are the supported options)

**Review by MichaReiser — COMMENTED** [review]
Nice work! 

I've left a few nit comments that are up to you if you want to address them. 

My main question (which may help decide whether a macro is a good fit) is what convention we want to use for the field names. 

The option names in the YAML configuration and the CLI use kebab case: `extend-ignore`. The names aren't defined by the field names but by the `option` annotation (macro)

https://github.com/astral-sh/ruff/blob/94727996e8c717287fb2fc73fe2730dc613dc794/crates/ruff_workspace/src/options.rs#L607-L615

I see reasons for using the same as well as for using different names than what we use in the configuration:

* Same names: More familiar to users
* Different names: Makes it clear that these are the resolved settings which doesn't map 1:1 to the YAML or CLI configuration. For example, the resolved settings can have fewer or more fields than the options, the values are merged from different settings (or sections) etc. 

 
Before you publish your PR. Could you expand your test plan with an example output?

File: crates/ruff_formatter/src/lib.rs [hunk 4]
```diff
@@ -113,6 +114,12 @@ impl Default for IndentWidth {
     }
 }
 
+impl fmt::Display for IndentWidth {
+    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
+        std::write!(f, "{}", self.0)
```
Comment (BurntSushi) [inline crates/ruff_formatter/src/lib.rs:119]: For calls to `write!` that just print out the `Display` of a single argument like this, you can just do `Display::fmt(&self.0, f)` directly. (Technically `self.0.fmt(f)` can also work, but IIRC there are cases where that call is ambiguous with `Debug::fmt`. In which case, you'd get a compile error. Not sure if that's the case here though, so I tend to just write it out as `Display::fmt(...)`.)

File: crates/ruff_linter/src/settings/mod.rs [hunk 5]
```diff
@@ -38,13 +41,34 @@ pub mod flags;
...
+    (@field $fmt:ident, $namespace:ident, $settings:ident.$field:ident | debug) => {
+        writeln!($fmt, "{}{} = {:?}", $namespace, stringify!($field), $settings.$field)?;
+    };
+    (@field $fmt:ident, $namespace:ident, $settings:ident.$field:ident | nested) => {
+        write!($fmt, "{}", $settings.$field)?;
+    };
+    (@field $fmt:ident, $namespace:ident, $settings:ident.$field:ident) => {
+        writeln!($fmt, "{}{} = {}", $namespace, stringify!($field), $settings.$field)?;
+    };
+}
```
Comment (BurntSushi) [inline crates/ruff_linter/src/settings/mod.rs:63]: Oh this isn't nearly as bad as I thought it was going to be based on your comments in Discord. :P I'm totally cool with this.

File: crates/ruff_linter/src/settings/mod.rs [hunk 6]
```diff
@@ -38,13 +41,34 @@ pub mod flags;
 pub mod rule_table;
 pub mod types;
 
+#[macro_export]
+macro_rules! display_settings {
+    (formatter = $fmt:ident, namespace = $namespace:literal, fields = [$($settings:ident.$field:ident $(| $modifier:tt)?),* $(,)?]) => {
```
Comment (BurntSushi) [inline crates/ruff_linter/src/settings/mod.rs:46]: I might be tempted to rename `namespace` to `prefix`, since it seems to usually end with a `.`. (This is a small thing.)

Comment (BurntSushi) [reply crates/ruff_linter/src/settings/mod.rs:46]: Or I wonder, could the `.` be inserted unconditionally in this macro?

I would guess maybe not, for cases where the namespace is empty?

File: crates/ruff_linter/src/rules/flake8_import_conventions/settings.rs [hunk 7]
```diff
@@ -44,3 +46,18 @@ impl Default for Settings {
         }
     }
 }
+
+impl Display for Settings {
+    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
+        display_settings! {
+            formatter = f,
+            namespace = "linter.flake8_import_conventions",
```
Comment (BurntSushi) [inline crates/ruff_linter/src/rules/flake8_import_conventions/settings.rs:54]: Should this have a `.` at the end?

**Review by BurntSushi — COMMENTED** [review]
Wow, that's a lot of `Display` impls! I agree that your `display_settings!` macro here is pretty effective.

Very nice work. :)

File: crates/ruff_linter/src/settings/mod.rs (hunk 6 above)
Comment (InquisitivePenguin) [reply crates/ruff_linter/src/settings/mod.rs:46]: Alternatively, we could make the namespace/prefix an optional parameter and then append `.` if a namespace is specified.

File: crates/ruff_linter/src/settings/mod.rs (hunk 5 above)
Comment (InquisitivePenguin) [reply crates/ruff_linter/src/settings/mod.rs:63]: That's probably because you're seeing the revised version :P

Thanks though, I'm glad this is workable and understandable as a solution!

File: crates/ruff_linter/src/rules/flake8_import_conventions/settings.rs (hunk 7 above)
Comment (InquisitivePenguin) [reply crates/ruff_linter/src/rules/flake8_import_conventions/settings.rs:54]: Good catch!

File: crates/ruff_linter/src/registry/rule_set.rs (hunk 1 above)
Comment (InquisitivePenguin) [reply crates/ruff_linter/src/registry/rule_set.rs:286]: > Would `f.debug_list` be useful here?

Not really since it formats everything on one line 😞 

Thanks for the suggestion! I was using an allocating `format!` + `.join` to avoid a trailing comma, but apparently trailing commas are valid toml anyway, so my bad 🤷‍♀️

File: crates/ruff_linter/src/settings/mod.rs (hunk 6 above)
Comment (BurntSushi) [reply crates/ruff_linter/src/settings/mod.rs:46]: I defer to you on what to do here. :)

**Review by charliermarsh — COMMENTED** [review]
This is great work! Big improvement.

>  An open question needs to be answered: how important is it that the output be valid TOML? Some types in settings, such as a hash-map from a glob pattern to a multi-variant enum, will be hard to rework into valid and readable TOML.

In my opinion, this is a nice-to-have but not critical, since the representation isn't going to match the representation that users have in their own `pyproject.toml` or `ruff.toml` file (since `Settings` is an internal representation, rather than the user-facing representation).

File: crates/ruff_linter/src/rules/flake8_copyright/settings.rs [hunk 8]
```diff
@@ -24,3 +26,19 @@ impl Default for Settings {
...
+
+impl Display for Settings {
+    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
+        display_settings! {
+            formatter = f,
+            namespace = "linter.flake8_copyright",
+            fields = [
+                self.notice_rgx,
+                // TODO(jane): remove debug
+                self.author | debug,
```
[the remark this answers is not in the document]
Comment (InquisitivePenguin) [reply crates/ruff_linter/src/rules/flake8_copyright/settings.rs:38]: Right, it would fail to compile with the exact error you mentioned.

File: crates/ruff_linter/src/registry/rule_set.rs [hunk 9]
```diff
@@ -269,6 +270,22 @@ impl Debug for RuleSet {
...
+impl Display for RuleSet {
+    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
+        if self.is_empty() {
+            write!(f, "[]")
+        } else {
+            write!(
+                f,
+                "[\n\t{}\n]",
+                self.iter()
+                    .map(|rule| format!("\"{rule:?}\""))
```
[the remark this answers is not in the document]
Comment (InquisitivePenguin) [reply crates/ruff_linter/src/registry/rule_set.rs]: `Rule` doesn't have a `Display` implementation, and I thought the `Debug` implementation looked good as it was! (though I did add some quotes)

File: crates/ruff_linter/src/settings/types.rs [hunk 10]
```diff
@@ -467,3 +539,28 @@ impl Deref for Version {
...
+
+impl PerFileIgnores {
+    pub fn new(ignores: Vec<(GlobMatcher, GlobMatcher, RuleSet)>) -> Self {
+        Self { ignores }
+    }
+}
+
+impl Display for PerFileIgnores {
+    fn fmt(&self, _: &mut Formatter<'_>) -> std::fmt::Result {
+        Ok(())
```
[the remark this answers is not in the document]
Comment (InquisitivePenguin) [reply crates/ruff_linter/src/settings/types.rs:553]: My bad, that should have a TODO.

**Comment by charliermarsh** [comment]
(Feel free to ignore the perf regression - you may need to merge / rebase on main, or otherwise we may be seeing some flakiness (in other PRs too).)

**Comment by InquisitivePenguin** [comment]
I'll merge from `main` just in case 🙂

File: crates/ruff_cli/tests/snapshots/show_settings__display_default_settings.snap [hunk 11]
```diff
@@ -0,0 +1,361 @@
...
+    - check
+    - "--show-settings"
+    - unformatted.py
+---
+success: true
+exit_code: 0
+----- stdout -----
+Resolved settings for: "[BASEPATH]/crates/ruff_cli/resources/test/fixtures/unformatted.py"
+Settings path: "[BASEPATH]/pyproject.toml"
+cache_dir = "[BASEPATH]/.ruff_cache"
```
Comment (charliermarsh) [inline crates/ruff_cli/tests/snapshots/show_settings__display_default_settings.snap:15]: Nit: might be nice to visually separate the two lines above (which are meta-information about the settings) from the settings themselves. Maybe adding a comment above the `cache_dir` line, like `Top-level Settings` or similar? Just an idea, open to better solutions.

File: crates/ruff_linter/src/settings/mod.rs [hunk 12]
```diff
@@ -38,13 +41,133 @@ pub mod flags;
 pub mod rule_table;
 pub mod types;
 
+/// `display_settings!` is a macro that can display and format struct fields in a readable,
```
Comment (charliermarsh) [inline crates/ruff_linter/src/settings/mod.rs:44]: Very nice.

File: crates/ruff_linter/src/settings/mod.rs [hunk 13]
```diff
@@ -206,10 +390,8 @@ impl Default for LinterSettings {
 }
 
 /// Given a list of patterns, create a `GlobSet`.
-pub fn resolve_per_file_ignores(
-    per_file_ignores: Vec<PerFileIgnore>,
-) -> Result<Vec<(GlobMatcher, GlobMatcher, RuleSet)>> {
-    per_file_ignores
+pub fn resolve_per_file_ignores(per_file_ignores: Vec<PerFileIgnore>) -> Result<PerFileIgnores> {
```
Comment (charliermarsh) [inline crates/ruff_linter/src/settings/mod.rs:393]: Perhaps makes sense as an associated method on `PerFileIgnores`, now that the struct exists? But not blocking feedback.

**Review by charliermarsh — APPROVED** [review]
This is great work!

File: crates/ruff_cli/tests/snapshots/show_settings__display_default_settings.snap (hunk 11 above)
Comment (InquisitivePenguin) [reply crates/ruff_cli/tests/snapshots/show_settings__display_default_settings.snap:15]: Good idea! I might do something like `# General Settings` if that works.

**Review by MichaReiser — APPROVED** [review]
So many display implementations :laughing: 

This is excellent. I prefer to have some empty lines between the sections, but I'll leave the decision up to you. Let me (or anyone else around at the time) know when it is ready to merge.

File: crates/ruff_linter/src/settings/mod.rs [hunk 14]
```diff
@@ -38,13 +37,133 @@ pub mod flags;
...
+    };
+    (@field $fmt:ident, $prefix:ident, $settings:ident.$field:ident | nested) => {
+        write!($fmt, "{}", $settings.$field)?;
+    };
+    (@field $fmt:ident, $prefix:ident, $settings:ident.$field:ident | optional) => {
+        {
+            write!($fmt, "{}{} = ", $prefix, stringify!($field))?;
+            match &$settings.$field {
+                Some(value) => writeln!($fmt, "{}", value)?,
+                None        => writeln!($fmt, "nil")?
```
Comment (konstin) [inline crates/ruff_linter/src/settings/mod.rs:137]: I'd go for `none` or `None` here, it's what rust (`Option::None`) and python (`None`) use.

```suggestion
                None        => writeln!($fmt, "none")?
```

File: crates/ruff_linter/src/settings/types.rs [hunk 15]
```diff
@@ -467,3 +558,54 @@ impl Deref for Version {
 /// [`fnmatch`](https://docs.python.org/3/library/fnmatch.html) for
 /// pattern matching.
 pub type IdentifierPattern = glob::Pattern;
+
+#[derive(Debug, CacheKey, Default)]
+pub struct PerFileIgnores {
+    ignores: Vec<(GlobMatcher, GlobMatcher, RuleSet)>,
```
Comment (konstin) [inline crates/ruff_linter/src/settings/types.rs:564]: This could use a comment what the two glob matchers are

**Review by konstin — APPROVED** [review]
Great work!

**Comment by charliermarsh** [comment]
Rock on
