### PR TITLE
[`flake8-pyi`] Fix several correctness issues with `custom-type-var-return-type` (`PYI019`)

### LINKED ISSUE #15849: Panic in `PYI019` autofix
### Description

Running `ruff check --select=PYI019 --preview foo.pyi` triggers a panic if `foo.pyi` has this contents:

```py
class F:
    @classmethod
    def m[S](cls: type[S], /) -> S[int]: ...
```

The panic occurs at this line here:

https://github.com/astral-sh/ruff/blob/59be5f5278d78e42a46b9e7c9306a93a3892ab29/crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs#L295-L297

And the reason is that, contrary to what the comment says, `uses_custom_typevar` does _not_ guarantee that the return `Expr` will be an `ExprName`, due to the `map_subscript` call here: https://github.com/astral-sh/ruff/blob/59be5f5278d78e42a46b9e7c9306a93a3892ab29/crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs#L187-L189

(The `map_subscript` call also looks buggy, FWIW.)

We should switch to a more type-safe code pattern here. Note that although the panic occurs in autofix logic, the panic occurs even if you run Ruff without `--fix`, since we create fixes for diagnostics even if `--fix` is not specified.

### PR DESCRIPTION
**Pull request by AlexWaygood**
## Summary

This PR fixes several correctness issues in our `PYI019` rule:
- The rule would panic on this snippet. There shouldn't even be a diagnostic on this snippet, since it's not a valid use of the `S` type variable:
  ```py
  class F:
      @classmethod
      def m[S](cls: type[S], /) -> S[int]: ...
  ```
- The rule would panic on this snippet. Again, there shouldn't even be a diagnostic emitted here; it's an invalid use of a type variable:
  ```py
  class F:
      def m[S](self: S) -> S[int]: ...
  ```
- The rule had a false positive on this snippet, where `type` is shadowed locally:
  ```py
  def shadowed_type():
      type = 1
      class A:
          @classmethod
          def m[S](cls: type[S]) -> S: ...
  ```
- The rule had a false negative on this snippet, where the fully qualified version of `builtins.type` rather than the implicit builtin binding:
  ```py
  import builtins

  class UsesFullyQualifiedType:
      @classmethod
      def m[S](cls: builtins.type[S]) -> S: ...  # PYI019
  ```
- The rule had a false negative on this snippet, where the return annotation is `type[S]` rather than simply `S`:
  ```py
  class Foo:
      @classmethod
      def f[S](cls: type[S]) -> type[S]: ...
  ```

Fixes #15849

## Test Plan

I've added new fixtures added that trigger panics and/or incorrect behaviour on `main`.

### CODE REVIEW

File: crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs [hunk 1]
```diff
@@ -3,11 +3,11 @@ use crate::importer::ImportRequest;
 use itertools::Itertools;
 use ruff_diagnostics::{Applicability, Diagnostic, Edit, Fix, FixAvailability, Violation};
 use ruff_macros::{derive_message_formats, ViolationMetadata};
-use ruff_python_ast as ast;
-use ruff_python_ast::helpers::map_subscript;
-use ruff_python_ast::{Expr, Parameters, TypeParam, TypeParams};
+use ruff_python_ast::{self as ast, ExprName};
+use ruff_python_ast::{Expr, ExprSubscript, Parameters, TypeParam, TypeParams};
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs:7]: nit: do you want to combine these?

**Review by ntBre — APPROVED** [review]
This looks great! I had to throw in one nit, but the changes were easy to follow, especially with the new variable names, and the tests made it clear what was going on.

File: crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs (hunk 1 above)
Comment (AlexWaygood) [reply crates/ruff_linter/src/rules/flake8_pyi/rules/custom_type_var_return_type.rs:7]: ohh, thanks!
