### PR TITLE
fix: Use BestFit layout for subscript

### LINKED ISSUE #7407: Formatter causes E501 for long variable and attributes
I'm testing the format option. Found that formatting scripts with long variables and attributes which are indented cases E501.

ruff check, would raise `11:89: E501 Line too long (92 > 88 characters)` for this snippet.

- formatted with black
```py
class Foo:
    some_very_long_attribute_name: str = ""

    def __getitem__(self, val):
        ...


def main() -> None:
    if True:
        some_very_long_variable_name_abcdefghijk = Foo()
        some_very_long_variable_name_abcdefghijk = (
            some_very_long_variable_name_abcdefghijk[
                some_very_long_variable_name_abcdefghijk.some_very_long_attribute_name
                == "This is a very long string abcdefghijk"
            ]
        )


if __name__ == "__main__":
    main()
```
- formatted with ruff
```py
class Foo:
    some_very_long_attribute_name: str = ""

    def __getitem__(self, val):
        ...


def main() -> None:
    if True:
        some_very_long_variable_name_abcdefghijk = Foo()
        some_very_long_variable_name_abcdefghijk = some_very_long_variable_name_abcdefghijk[
            some_very_long_variable_name_abcdefghijk.some_very_long_attribute_name
            == "This is a very long string abcdefghijk"
        ]


if __name__ == "__main__":
    main()
```

- pyproject.toml
```toml
[tool.ruff]
target-version = "py39"
line-length = 88
select = ["B", "C", "E", "F", "I", "W"]
ignore = ["E731"]

[tool.black]
line-length = 88
target-version = ["py39"]
```

- version
`Python 3.9.5`
`ruff 0.0.289`
`OS Ubuntu 22.04.3 LTS(WSL)`

- Additional info
In the original script the class Foo is a pandas dataframe and this pattern is quite common.

### LINKED ISSUE #7422: Formatter incompatibility: parenthesized subscript access
Given:

```python
if True:
    if True:
        if True:
            if True:
                if True:
                    self.intermediator_address = (
                        invoice_recipient_intermediator_address[0].text
                    )
```

Ruff formats as:

```python
if True:
    if True:
        if True:
            if True:
                if True:
                    self.intermediator_address = invoice_recipient_intermediator_address[
                        0
                    ].text
```

Whereas Black formats as:

```python
if True:
    if True:
        if True:
            if True:
                if True:
                    self.intermediator_address = (
                        invoice_recipient_intermediator_address[0].text
                    )
```

(Sorry for all the nesting, easiest way to strip context while preserving the line lengths.)

Sourced from https://github.com/astral-sh/ruff/issues/7394.

### PR DESCRIPTION
**Pull request by MichaReiser**
## Summary

Ruff never parenthesized long attribute chains followed by a subscript:

```python
def main() -> None:
    if True:
        some_very_long_variable_name_abcdefghijk = Foo()
        some_very_long_variable_name_abcdefghijk = some_very_long_variable_name_abcdefghijk[
            some_very_long_variable_name_abcdefghijk.some_very_long_attribute_name
            == "This is a very long string abcdefghijk"
        ]
```

Whereas Black formats this as 

```python
def main() -> None:
    if True:
        some_very_long_variable_name_abcdefghijk = Foo()
        some_very_long_variable_name_abcdefghijk = (
            some_very_long_variable_name_abcdefghijk[
                some_very_long_variable_name_abcdefghijk.some_very_long_attribute_name
                == "This is a very long string abcdefghijk"
            ]
        )
```

This PR changes the `needs_parentheses` function of `ExprSubscript` to use the `BestFit` layout if its value proposes the `BestFit` layout (except when in return type annotations, see inline comments)

Making this change revealed an instability because the formatter incorrectly removed the parentheses from callees or objects. I changed the call chain formatting to preserve parentheses.

Closes #7407.

Closes #7422.

## Test Plan

I added new tests

**Base**

| project      | similarity index  | total files       | changed files     |
|--------------|------------------:|------------------:|------------------:|
| cpython      |           0.76083 |              1789 |              1632 |
| django       |           0.99982 |              2760 |                37 |
| transformers |           0.99957 |              2587 |               399 |
| twine        |           1.00000 |                33 |                 0 |
| typeshed     |           0.99983 |              3496 |                18 |
| warehouse    |           0.99923 |               648 |                18 |
| zulip        |           0.99962 |              1437 |                22 |

**This PR**

| project      | similarity index  | total files       | changed files     |
|--------------|------------------:|------------------:|------------------:|
| cpython      |           0.76083 |              1789 |              1632 |
| django       |           0.99982 |              2760 |                37 |
| transformers |           0.99957 |              2587 |               399 |
| twine        |           1.00000 |                33 |                 0 |
| typeshed     |           0.99983 |              3496 |                18 |
| **warehouse**    |           0.99929 |               648 |                16 | <--
| zulip        |           0.99962 |              1437 |                22 |

### CODE REVIEW

**Comment by MichaReiser** [comment]
Current dependencies on/for this PR:
* main
  * **PR #7409** <a href="https://app.graphite.dev/github/pr/astral-sh/ruff/7409" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/astral-sh/ruff/7409?utm_source=stack-comment).

File: crates/ruff_python_formatter/src/expression/expr_subscript.rs [hunk 1]
```diff
@@ -97,7 +101,21 @@ impl NeedsParentheses for ExprSubscript {
...
             } else {
                 match self.value.needs_parentheses(self.into(), context) {
-                    OptionalParentheses::BestFit => OptionalParentheses::Never,
+                    OptionalParentheses::BestFit => {
+                        if parent.as_stmt_function_def().is_some_and(|function_def| {
+                            function_def
+                                .returns
+                                .as_deref()
+                                .and_then(Expr::as_subscript_expr)
+                                == Some(self)
```
Comment (charliermarsh) [inline crates/ruff_python_formatter/src/expression/expr_subscript.rs:110]: Can you use `is_some_and` here?

**Review by charliermarsh — APPROVED** [review]

File: crates/ruff_python_formatter/src/expression/expr_subscript.rs (hunk 1 above)
Comment (MichaReiser) [reply crates/ruff_python_formatter/src/expression/expr_subscript.rs:110]: I already use `is_some_and` on line 105. Do you mean for the equality comparison? I prefer avoiding lambdas when possible because it leads to very nested code.
