### PR TITLE
Handled dict and set inside f-string (#4249)

### LINKED ISSUE #4249: [Autofix error] C408 - unnecessary-collection-call - syntax error when fixing within f-string
Presumably replacing `dict()` with `{}` gets confused when inside an f-string when it comes to using `"` vs `'` (or maybe it's the nested `{`)

```python
# test.py
f"{dict(x='y')}"  # should turn into f"{{'x': 'y'}}"
```

```
$ ruff --select=C408 test.py  --fix

error: Autofix introduced a syntax error. Reverting all changes.

This indicates a bug in `ruff`. If you could open an issue at:

    https://github.com/charliermarsh/ruff/issues/new?title=%5BAutofix%20error%5D

...quoting the contents of `test.py`, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

test.py:1:4: C408 Unnecessary `dict` call (rewrite as a literal)
```

Using ruff 0.0.264

### PR DESCRIPTION
**Pull request by DavideCanton**
This fixes some C40* rules by adding spaces around dict and set literals inside f-string, and quotes correctly string literals inside f-string, since dict kwargs must be converted into string literals.

Closes #4249.

### CODE REVIEW

**Review by charliermarsh — COMMENTED** [review]
How would this handle a case like `f"{set(['a', 'b']) - set(['a'])}"`, where the second `set` needs to be converted, but doesn't require any padding?

**Comment by DavideCanton** [comment]
> How would this handle a case like `f"{set(['a', 'b']) - set(['a'])}"`, where the second `set` needs to be converted, but doesn't require any padding?

You are right, I missed that case.

I reworked a bit the fix part by checking where the current expression is related to the f-string boundaries

File: crates/ruff/src/rules/flake8_comprehensions/fixes.rs [hunk 1]
```diff
@@ -552,7 +573,51 @@ pub(crate) fn fix_unnecessary_collection_call(
...
+    let code = if wrap_in_spaces {
+        wrap_code_in_spaces(&state, checker, expr.range())
+    } else {
+        state.to_string()
+    };
+
+    Ok(Edit::range_replacement(code, expr.range()))
+}
+
+/// Adds spaces around the code generated from `state` if `wrap_in_spaces` is true.
```
Comment (charliermarsh) [inline crates/ruff/src/rules/flake8_comprehensions/fixes.rs:585]: Nit: I'd probably rather parenthesize than add whitespace.

File: crates/ruff/src/rules/flake8_comprehensions/fixes.rs [hunk 2]
```diff
@@ -552,7 +573,51 @@ pub(crate) fn fix_unnecessary_collection_call(
...
+    if checker.model.in_f_string() {
+        if let Some(f_string_range) = checker.indexer.f_string_range(expr_range.start()) {
+            let f_string = checker.locator.slice(f_string_range);
+
+            // find the braces that delimit the f-string
+            let f_string_start = f_string_range.start();
+            let f_string_sbrace =
+                f_string_start + TextSize::try_from(f_string.find('{').unwrap()).unwrap();
+            let f_string_ebrace =
+                f_string_start + TextSize::try_from(f_string.rfind('}').unwrap()).unwrap();
```
[the remark this answers is not in the document]
Comment (charliermarsh) [reply crates/ruff/src/rules/flake8_comprehensions/fixes.rs:596]: (I'm being a bit vague because I don't know how exactly to solve this problem. We need to track additional state to detect the parent formatted expression.)

[the remark this answers is not in the document]
Comment (DavideCanton) [reply crates/ruff/src/rules/flake8_comprehensions/fixes.rs:596]: oh, ok, guess I'll have to study the f-string literal syntax a bit more

File: crates/ruff/src/rules/flake8_comprehensions/fixes.rs (hunk 1 above)
Comment (DavideCanton) [reply crates/ruff/src/rules/flake8_comprehensions/fixes.rs:585]: probably it's more robust, but I think it renders uglier expressions in many simple cases, what do you think?

File: crates/ruff/src/rules/flake8_comprehensions/fixes.rs [hunk 3]
```diff
@@ -552,7 +573,51 @@ pub(crate) fn fix_unnecessary_collection_call(
...
+
+            let mut buf = Vec::with_capacity(3);
```
Comment (MichaReiser) [inline crates/ruff/src/rules/flake8_comprehensions/fixes.rs:598]: Nit: Can we directly push to the string instead of building a vec and then joining at the end?

File: crates/ruff/src/rules/flake8_comprehensions/fixes.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (DavideCanton) [reply crates/ruff/src/rules/flake8_comprehensions/fixes.rs:596]: Ok, I see.

It seems I assumed (wrongly) that an expression wrapped in braces is always being formatted, but that's not the case.

[the remark this answers is not in the document]
Comment (DavideCanton) [reply crates/ruff/src/rules/flake8_comprehensions/fixes.rs:596]: ok now I see your point, the code is wrong

**Comment by DavideCanton** [comment]
Hi, it's quite a while this is around, I'm still keeping it updated with the main branch. Is there any interest in merging this?

**Comment by charliermarsh** [comment]
Apologies and thank you for the ping. I'll re-review this tonight.

File: crates/ruff/src/rules/flake8_comprehensions/fixes.rs [hunk 4]
```diff
@@ -462,10 +477,56 @@ pub(crate) fn fix_unnecessary_collection_call(
...
+}
+
+/// Adds spaces around the code generated from `state` if `wrap_in_spaces` is true.
+fn wrap_code_in_spaces(code: String, checker: &Checker, expr_range: TextRange) -> String {
+    if checker.semantic_model().in_f_string() {
+        let str = checker.locator.contents().chars().collect_vec();
+
+        // find the braces that delimit the f-string token
+        let mut si: usize = expr_range.start().into();
+        while str[si] != '{' {
```
Comment (charliermarsh) [inline crates/ruff/src/rules/flake8_comprehensions/fixes.rs:496]: Would this not detect the wrong braces given that the expression is `a` in: `f"{ {a} }"`?

That would be: an f-string with a single expression, which is a set literal that contains the element `a`.

Comment (charliermarsh) [reply crates/ruff/src/rules/flake8_comprehensions/fixes.rs:496]: Hmm, yeah it does get this wrong:

```diff
        249 │+23    |-print(f"{ {set(a for a in 'abc')} }")
        250 │+   23 |+print(f"{ { {a for a in 'abc'} } }")
```

But, it might be solvable. Will play around with it.

Comment (charliermarsh) [reply crates/ruff/src/rules/flake8_comprehensions/fixes.rs:496]: Hmm, it's probably not solvable without a better f-string parser and representation.

**Comment by DavideCanton** [comment]
thanks for the update!
