### PR TITLE
Fix f-string middle panic when parsing t-strings

### LINKED ISSUE #23198: Panic: `entered unreachable code: t-string: unexpected token FStringMiddle`
### Summary

Running

```rs
let s = "A1[A\u{c}\0:+,>1t'{:f\0:{f\"f\0:\0{fm\0:{f:\u{10}\0\0\0:bb\0{@f>f\u{1}'\0f";
let _ = ruff_python_parser::parse_module(s);
```

is panicking with:

```
thread 'ruff_error' (266784) panicked at /Users/samuel/.cargo/git/checkouts/ruff-b18f69e2b025fac7/ce5f7b6/crates/ruff_python_parser/src/parser/expression.rs:1635:25:
internal error: entered unreachable code: t-string: unexpected token `FStringMiddle` at 31..41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I'm using the latest release `0.15.0`.

Found by fuzzing in https://github.com/pydantic/monty/pull/119

Another similar failure [here](https://github.com/pydantic/monty/actions/runs/21856378172/job/63074095747?pr=131)

### Version

using tag 0.15.0

### PR DESCRIPTION
**Pull request by ntBre**
Summary
--

This PR fixes #23198 by copying Dylan's changes from #19183 to the other
`InterpolatedStringElementsKind` variant, in line with Micha's prophetic comment (https://github.com/astral-sh/ruff/pull/19183/changes#r2217325217).

Test Plan
--

Two new tests derived from the issue

### CODE REVIEW

**Comment by ntBre** [comment]
Not really sure what happened with the benchmarks, but it cleared up after rebasing on main. There are some ~2% regressions but also some improvements, so I think it's pretty neutral overall, as I would expect.

**Comment by dylwil3** [comment]
> in line with Micha's prophetic comment

truly a red flag that I casually asserted Micha was wrong. we should add a CI check for that.

File: crates/ruff_python_parser/src/parser/mod.rs [hunk 1]
```diff
@@ -1348,7 +1340,8 @@ bitflags! {
         const WITH_ITEMS_UNPARENTHESIZED = 1 << 28;
         const F_STRING_ELEMENTS = 1 << 29;
         const T_STRING_ELEMENTS = 1 << 30;
-        const FT_STRING_ELEMENTS_IN_FORMAT_SPEC = 1 << 31;
+        const F_STRING_ELEMENTS_IN_FORMAT_SPEC = 1 << 27;
+        const T_STRING_ELEMENTS_IN_FORMAT_SPEC = 1 << 31;
```
Comment (dylwil3) [inline crates/ruff_python_parser/src/parser/mod.rs]: weird that we skipped 27 (did I do that??)
should we just renumber them sequentially or does that break something?

**Review by dylwil3 — APPROVED** [review]
This looks great to me! I'm glad it wasn't _too_ painful.

**Comment by ntBre** [comment]
It wasn't painful at all! You had already done the hard work for me :smile:

File: crates/ruff_python_parser/src/parser/mod.rs (hunk 1 above)
Comment (ntBre) [reply crates/ruff_python_parser/src/parser/mod.rs]: It was weird, but it wasn't you! It was like that before your PR. I'm assuming one of them got removed at some point?

I vaguely remember trying to reorder a different set of `bitflags` previously and someone suggested leaving them alone, but I'm happy to do it if you prefer. Maybe @dhruvmanila will have an opinion too.

Comment (dhruvmanila) [reply crates/ruff_python_parser/src/parser/mod.rs]: I think it's fine to change the values, I'm assuming that we should avoid doing that mainly to make the reviewing easier but I guess you could do it before merging. Anyways, this doesn't look like a big change 🤷‍♂️

**Review by dhruvmanila — APPROVED** [review]

**Comment by samuelcolvin** [comment]
Thanks so much for this.
