### PR TITLE
[`pyupgrade`] Improve diagnostic range for tuples (`UP024`)

### LINKED ISSUE #19696: UP024 error message is confusing when `except` clause has multiple exceptions
### Summary

[UP024](https://docs.astral.sh/ruff/rules/os-error-alias/) highlights specific aliased exceptions which might be removed in the future. When the `except` clause contains multiple exceptions, the error message can be a bit misleading. Simple Example:

```py
try:
    pass
except (IOError, ValueError):
    pass
```

In this example, `IOError` is an alias of `OSError`, that should be replaced, while `ValueError` is just a regular exception. Ruff correctly understands this (see `uv tool run ruff@0.12.7 check --select UP024 --fix --diff`), but its output does not distinguish between exceptions targeted by this rule and ones that aren't:

```
example.py:3:8: UP024 [*] Replace aliased errors with `OSError`
  |
1 | try:
2 |     pass
3 | except (ValueError, IOError):
  |        ^^^^^^^^^^^^^^^^^^^^^ UP024
4 |     pass
  |
  = help: Replace with builtin `OSError`
```

The error message "Replace aliased errors with `OSError`" in connection with the highlighted section makes it seem as if *both* exceptions were aliases of `OSError` and should be replaced.

If this is possible, specifically highlighting the aliased exceptions would probably be sufficient to avoid this misinterpretation:

```
example.py:3:8: UP024 [*] Replace aliased errors with `OSError`
  |
1 | try:
2 |     pass
3 | except (ValueError, IOError):
  |                     ^^^^^^^ UP024
4 |     pass
  |
  = help: Replace with builtin `OSError`
```

### Version

ruff 0.12.7 (c5ac99889 2025-07-29)

### PR DESCRIPTION
**Pull request by Jkhall81**
## Summary
This PR refines the diagnostic highlighting for **UP024**. Previously, when multiple exceptions were in a tuple, the linter would underline the entire tuple. Now specific aliases within a tuple with be highlighted.

Fixes #19696

### CODE REVIEW

File: crates/ruff_linter/src/rules/pyupgrade/rules/os_error_alias.rs [hunk 1]
```diff
@@ -93,7 +93,11 @@ fn atom_diagnostic(checker: &Checker, target: &Expr) {
 
 /// Create a [`Diagnostic`] for a tuple of expressions.
 fn tuple_diagnostic(checker: &Checker, tuple: &ast::ExprTuple, aliases: &[&Expr]) {
-    let mut diagnostic = checker.report_diagnostic(OSErrorAlias { name: None }, tuple.range());
+    let Some(first_alias) = aliases.first() else {
+        return;
+    };
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/pyupgrade/rules/os_error_alias.rs:99]: I think this fix is too simple, unfortunately. If you look at the test case below with a diagnostic emitted on line 51 of the input file (`EnvironmentError, IOError, OSError, select.error`), all of these should actually be underlined because they are all `OSError` aliases.

Comment (Jkhall81) [reply crates/ruff_linter/src/rules/pyupgrade/rules/os_error_alias.rs:99]: Thank you for taking the time to point this stuff out.

First_alias is still in there and I added secondary_annotation to pick up any additional OSError aliases.  It's now gated behind preview.  The original .snap file changes have been reverted.  I added a test to show the rule changes when preview is used, with the secondary_annotation underlining.

File: crates/ruff_linter/src/rules/pyupgrade/rules/os_error_alias.rs [hunk 2]
```diff
@@ -93,7 +93,20 @@ fn atom_diagnostic(checker: &Checker, target: &Expr) {
...
+    let diagnostic_range = if checker.settings().preview.is_enabled() {
```
Comment (amyreese) [inline crates/ruff_linter/src/rules/pyupgrade/rules/os_error_alias.rs]: We prefer to add a new `is_<feature_name>_enabled()` helper to `ruff_linter/src/preview.rs` rather than simply checking if preview is enabled.

https://github.com/astral-sh/ruff/blob/main/crates/ruff_linter/src/preview.rs

File: crates/ruff_linter/src/rules/pyupgrade/rules/os_error_alias.rs [hunk 3]
```diff
@@ -93,7 +93,20 @@ fn atom_diagnostic(checker: &Checker, target: &Expr) {
...
+        first_alias.range()
+    } else {
+        tuple.range()
+    };
+    let mut diagnostic = checker.report_diagnostic(OSErrorAlias { name: None }, diagnostic_range);
+    if checker.settings().preview.is_enabled() {
```
Comment (amyreese) [inline crates/ruff_linter/src/rules/pyupgrade/rules/os_error_alias.rs]: Same here

Comment (Jkhall81) [reply crates/ruff_linter/src/rules/pyupgrade/rules/os_error_alias.rs]: My bad.  Thank you for pointing this out.  Added a preview wrapper function to preview.rs and then updated these two spots.

File: crates/ruff_linter/src/rules/pyupgrade/mod.rs [hunk 4]
```diff
@@ -464,4 +466,17 @@ mod tests {
         assert_diagnostics!(diagnostics);
         Ok(())
     }
+
+    #[test]
+    fn preview_up024() -> Result<()> {
+        let diagnostics = test_path(
+            Path::new("pyupgrade/UP024_0.py"),
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/pyupgrade/mod.rs]: I think we could just add this as a `test_case` in the `rules_preview` function on line 148 of this file. Alternatively, we could use the `assert_diagnostics_diff!` macro like on line 182 to give a nicer preview diff.

File: crates/ruff_linter/src/rules/pyupgrade/rules/os_error_alias.rs [hunk 5]
```diff
@@ -93,7 +94,20 @@ fn atom_diagnostic(checker: &Checker, target: &Expr) {
...
+    };
+    let diagnostic_range = if is_up024_precise_highlighting_enabled(checker.settings()) {
+        first_alias.range()
+    } else {
+        tuple.range()
+    };
+    let mut diagnostic = checker.report_diagnostic(OSErrorAlias { name: None }, diagnostic_range);
+    if is_up024_precise_highlighting_enabled(checker.settings()) {
+        for alias in aliases.iter().skip(1) {
+            diagnostic.secondary_annotation("Also an OSError alias".to_string(), alias.range());
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/pyupgrade/rules/os_error_alias.rs]: This seems a bit noisy to me, but maybe I'm over-indexing on our contrived test cases. I'd be okay with an empty message here:


```suggestion
            diagnostic.secondary_annotation("", alias.range());
```

But I'm curious what you and Amy think!

(Either way I think we can drop `to_string` because the argument just needs to implement `Display`)

File: crates/ruff_linter/src/rules/pyupgrade/mod.rs (hunk 4 above)
Comment (Jkhall81) [reply crates/ruff_linter/src/rules/pyupgrade/mod.rs]: I added an attribute, `#[test_case(Rule::OSErrorAlias, Path::new("UP024_0.py"))]`, to the `rules_preview` function.

File: crates/ruff_linter/src/rules/pyupgrade/rules/os_error_alias.rs (hunk 5 above)
Comment (Jkhall81) [reply crates/ruff_linter/src/rules/pyupgrade/rules/os_error_alias.rs]: It looks cleaner without the message.

**Review by ntBre — APPROVED** [review]
Thank you!
