### PR TITLE
Fix PLC2701 for type parameter scopes

### LINKED ISSUE #24563: PLC2701 false positive for a private name import used in a type parameter list
### Summary

The documentation of [`import-private-name` (PLC2701)](https://docs.astral.sh/ruff/rules/import-private-name/) says it “ignores private name imports that are exclusively used in type annotations”, but that doesn’t include imports used in type parameter lists. Those are type annotations too, so it should ignore them too. [Example](https://play.ruff.rs/2d6e9b6d-c99e-4801-a9fb-5a9077cd601c):
```console
$ cat >plc2701.py <<'# EOF'
from __future__ import annotations
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from _typeshed import SupportsRichComparison
def f[T: SupportsRichComparison](x: T, y: T):
    return x < y or x > y
# EOF

$ ruff --isolated check --select PLC2701 --preview plc2701.py --output-format concise
plc2701.py:4:10: error[PLC2701] Private name import `_typeshed`
Found 1 error.
```

### Version

ruff 0.15.10 (252f76102 2026-04-09)

### PR DESCRIPTION
**Pull request by ShipItAndPray**
Fixes #24563.

Ruff was treating private-name usage in PEP 695 type parameter lists as runtime code, which triggered PLC2701 false positives. This patch extends the typing-context check so private imports used only in type parameter scopes are exempt, and adds a regression case for a generic function with a private type parameter bound.

### CODE REVIEW

File: crates/ruff_linter/src/rules/pylint/rules/import_private_name.rs [hunk 1]
```diff
@@ -166,10 +166,7 @@ pub(crate) fn import_private_name(checker: &Checker, scope: &Scope) {
 
 /// Returns `true` if the [`ResolvedReference`] is in a typing context.
 fn is_typing(reference: &ResolvedReference) -> bool {
-    reference.in_type_checking_block()
-        || reference.in_typing_only_annotation()
-        || reference.in_string_type_definition()
-        || reference.in_runtime_evaluated_annotation()
+    reference.in_typing_context() || reference.in_runtime_evaluated_annotation()
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/pylint/rules/import_private_name.rs:169]: For posterity, the new checks expand to these `SemanticModelFlags`:

```
TYPE_CHECKING_BLOCK | TYPING_ONLY_ANNOTATION | STRING_TYPE_DEFINITION | TYPE_PARAM_DEFINITION | RUNTIME_EVALUATED_ANNOTATION
```

while the old checks were:

```
TYPE_CHECKING_BLOCK | TYPING_ONLY_ANNOTATION | STRING_TYPE_DEFINITION | RUNTIME_EVALUATED_ANNOTATION
```

so the diff is just adding `TYPE_PARAM_DEFINITION`:

```diff
-TYPE_CHECKING_BLOCK | TYPING_ONLY_ANNOTATION | STRING_TYPE_DEFINITION | RUNTIME_EVALUATED_ANNOTATION
+TYPE_CHECKING_BLOCK | TYPING_ONLY_ANNOTATION | STRING_TYPE_DEFINITION | TYPE_PARAM_DEFINITION | RUNTIME_EVALUATED_ANNOTATION
```

**Review by ntBre — APPROVED** [review]
Looks good to me, thank you! I also verified locally that the example from the issue succeeds on this branch.
