### PR TITLE
[red-knot] Report classes inheriting from bases with incompatible `__slots__`

### LINKED ISSUE #14931: [red-knot] Detect classes with incompatible `__slots__` being used in multiple inheritance
This isn't necessarily a priority for red-knot, but it's something that we'll want to do at some point and it could be easily done now.

Two classes that both have nonempty `__slots__` cannot be used in multiple inheritance. We should detect this and emit a diagnostic for it.

```pycon
>>> class Foo:
...     __slots__ = ("a",)
...     
>>> class Bar:
...     __slots__ = ("b",)
...     
>>> class Baz(Foo, Bar): ...
... 
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    class Baz(Foo, Bar): ...
TypeError: multiple bases have instance lay-out conflict
```

We'll probably want to check for this as part of this method here: https://github.com/astral-sh/ruff/blob/82faa9bb62e66a562f8a7ad81a645162ca558a08/crates/red_knot_python_semantic/src/types/infer.rs#L510-L520

Notes on the semantics:

### (1) A class with no `__slots__` can be used in multiple inheritance with a class that has `__slots__`

```pycon
>>> class A: ...
... 
>>> class B:
...     __slots__ = ("a",)
...     
>>> class C(A, B): ...
... 
>>> 
```

### (2) Empty `__slots__` are fine in combination with multiple inheritance:

```pycon
>>> class A:
...     __slots__ = ()
...     
>>> class B:
...     __slots__ = ("a",)
...     
>>> class C(A, B): ...
... 
>>> 
```

### (3) But even two classes with equal `__slots__` will fail in multiple inheritance if they are both non-empty:

```pycon
>>> class A:
...     __slots__ = ("a",)
...     
>>> class B:
...     __slots__ = ("a",)
...     
>>> class C(A, B): ...
... 
Traceback (most recent call last):
  File "<python-input-11>", line 1, in <module>
    class C(A, B): ...
TypeError: multiple bases have instance lay-out conflict
```

### (5) And `__slots__` are inherited by subclasses:

```pycon
>>> class A:
...     __slots__ = ("a",)
...     
>>> class B(A): ...
... 
>>> class C:
...     __slots__ = ("c",)
...     
>>> class D(C): ...
... 
>>> class E(B, D): ...
... 
Traceback (most recent call last):
  File "<python-input-16>", line 1, in <module>
    class E(B, D): ...
TypeError: multiple bases have instance lay-out conflict
```

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
## Summary

Resolves #14931.

## Test Plan

Markdown tests.

### CODE REVIEW

File: crates/red_knot_python_semantic/src/types/mro.rs [hunk 1]
```diff
@@ -328,3 +329,45 @@ fn c3_merge(mut sequences: Vec<VecDeque<ClassBase>>) -> Option<Mro> {
         }
     }
 }
+
+#[derive(Copy, Clone, Debug, Eq, PartialEq)]
+pub(super) enum SlotsKind {
+    /// `__slots__` is not found in the class nor any of its bases.
```
Comment (carljm) [inline crates/red_knot_python_semantic/src/types/mro.rs:335]:
```suggestion
    /// `__slots__` is not found in the class.
```

**Review by carljm — APPROVED** [review]
LGTM (modulo comment) but will leave for @AlexWaygood review.

**Review by AlexWaygood — APPROVED** [review]
Thanks! Nicely done
