### PR TITLE
[red-knot] Report line numbers in mdtest relative to the markdown file, not the test snippet

### LINKED ISSUE #13798: [red-knot] Report line numbers in mdtest relative to the markdown file, not the test snippet
Currently if an assertion in `mdtest` fails, it gives you a message as follows:

```
---- mdtest::path_06_resources_mdtest_binary_integers_md stdout ----

binary/integers.md - Division by Zero

/src/test.py
    line 13: unexpected error: [division-by-zero] "Cannot divide object of type `int` by zero"

--------------------------------------------------
```

The line number here isn't particularly helpful if it's the third or fourth snippet in a Markdown test suite, because it gives you the line number relative to the specific test snippet rather than the Markdown file. Nobody wants to manually count thirteen lines in a Python code block to figure out where the assertion failed!

It would be great if these line numbers could be reported relative to the enclosing Markdown file rather than just the specific code block that contained the failing assertion.

### PR DESCRIPTION
**Pull request by pilleye**
Summary: Adds absolute line numbers to mdtest (fixes #13798)

Test Plan: 

https://github.com/user-attachments/assets/63f84e34-da00-4146-a22b-e17322d5d687

### CODE REVIEW

File: crates/red_knot_test/src/lib.rs [hunk 1]
```diff
@@ -4,10 +4,11 @@ use red_knot_python_semantic::types::check_types;
 use ruff_db::files::system_path_to_file;
 use ruff_db::parsed::parsed_module;
 use ruff_db::system::{DbWithTestSystem, SystemPathBuf};
+use ruff_source_file::OneIndexed;
 use std::collections::BTreeMap;
 use std::path::PathBuf;
 
-type Failures = BTreeMap<SystemPathBuf, matcher::FailuresByLine>;
+type Failures = BTreeMap<AbsoluteLineNumberPath, matcher::FailuresByLine>;
```
Comment (MichaReiser) [inline crates/red_knot_test/src/lib.rs:11]: Nit: I'm inclined to use a regular `Vec` here and instead sort it before returning it in `run_test`. Vec's are just overall simpler data structure (e.g. for iterating). I then would add the `md_offset` to the `FailuresByLine` data structure (do we still need `line_number` or can we replace it with the `md_offset`?)

**Comment by MichaReiser** [comment]
Thanks, this is great. I suspect that the line numbers may get out of sync during parsing if the error isn't in the file's first code block.

File: crates/red_knot_test/src/lib.rs [hunk 2]
```diff
@@ -34,12 +35,24 @@ pub fn run(path: &PathBuf, title: &str) {
...
                 for (line_number, failures) in by_line.iter() {
                     for failure in failures {
+                        let absolute_line_info = format!(
+                            "{}:{}",
+                            title,
+                            absolute_line_number.saturating_add(line_number.get())
+                        );
                         let line_info = format!("line {line_number}:").cyan();
-                        println!("    {line_info} {failure}");
+                        println!("{absolute_line_info}    {line_info} {failure}");
```
Comment (AlexWaygood) [inline crates/red_knot_test/src/lib.rs:55]: The indentation should come before `absolute_line_info` here, so that the per-line diagnostics are indented below the "heading", which is the name of the embedded file

```suggestion
                        println!("    {absolute_line_info} {line_info} {failure}");
```

This means that the output in the terminal looks is beautifully organised like this if you have a test which has multiple Python snippets in the same Markdown test, and failures in more than one of those code blocks:

image

I checked, and I'm still able to double-click on the `exception_control_flow.md:157` if I run the test in VSCode, and it takes me straight to the line, even if it's indented.

---

Separately, I'm wondering if we need the relative line number to be reported at all, or if we could just make do with the relative line number? It feels like it just adds noise. Maybe we could just do this (diff relative to your PR branch):

```diff
diff --git a/crates/red_knot_test/src/lib.rs b/crates/red_knot_test/src/lib.rs
index 691a71528..e31fad615 100644
--- a/crates/red_knot_test/src/lib.rs
+++ b/crates/red_knot_test/src/lib.rs
@@ -50,9 +50,9 @@ pub fn run(path: &PathBuf, title: &str) {
                             "{}:{}",
                             title,
                             absolute_line_number.saturating_add(line_number.get())
-                        );
-                        let line_info = format!("line {line_number}:").cyan();
-                        println!("{absolute_line_info}    {line_info} {failure}");
+                        )
+                        .cyan();
+                        println!("    {absolute_line_info} {failure}");
                     }
                 }
```

**Review by AlexWaygood — COMMENTED** [review]
Thanks, this is fantastic! A couple more comments on top of Micha's :-)

File: crates/red_knot_test/src/lib.rs (hunk 2 above)
Comment (MichaReiser) [reply crates/red_knot_test/src/lib.rs:55]: I find the many line numbers and file names slightly confusing... Especially because they're next to each other. 

But it's hard to come up with a sane grouping. The grouping by file seems reasonable but is also somewhat confusing with diagnostics that then have line numbers absolute to the entire file.

And do we still need to show both line numbers? Aren't the md file line numbers sufficient?

```
/src/single_except.py
	exception/control_flow.md:157 unmatched assertion: revealed: list[int]
	exception/control_flow.md:159 unmatched assertion: revealed: list[int]
```

Comment (AlexWaygood) [reply crates/red_knot_test/src/lib.rs:55]: > And do we still need to show both line numbers? Aren't the md file line numbers sufficient?

I already asked that; I agree with you. Take a look at the final suggested diff in my comment above :-)

Comment (MichaReiser) [reply crates/red_knot_test/src/lib.rs:55]: Oh shoot. Reading is hard.

Comment (carljm) [reply crates/red_knot_test/src/lib.rs:55]: I also agree with removing the old embedded-relative line number entirely, in favor of just the new absolute line number.

I would favor removing the grouping by embedded-file altogether in the output, and just having flat output of one failure per line, per test. It's weird to me to have it grouped by embedded file but then the line numbers be relative to the markdown file. If you find the given line in the markdown file, it'll be obvious what embedded file you are in. And so many of the embedded file names are just `/src/test.py` anyway, it feels like mostly noise.

Comment (AlexWaygood) [reply crates/red_knot_test/src/lib.rs:55]: > I would favor removing the grouping by embedded-file altogether in the output, and just having flat output of one failure per line, per test. It's weird to me to have it grouped by embedded file but then the line numbers be relative to the markdown file. If you find the given line in the markdown file, it'll be obvious what embedded file you are in. And so many of the embedded file names are just `/src/test.py` anyway, it feels like mostly noise.

That rationale makes sense to me!

File: crates/red_knot_test/src/lib.rs (hunk 1 above)
Comment (carljm) [reply crates/red_knot_test/src/lib.rs:11]: If we remove the grouping by embedded-file path from the output altogether, as I suggested below, that also suggests simplifying this data structure.

File: crates/red_knot_test/src/parser.rs [hunk 3]
```diff
@@ -235,6 +247,7 @@ impl<'s> Parser<'s> {
                 // ignore other Markdown syntax (paragraphs, etc) used as comments in the test
                 if let Some(next_newline) = self.unparsed.find('\n') {
                     (_, self.unparsed) = self.unparsed.split_at(next_newline + 1);
+                    self.current_line_number = self.current_line_number.saturating_add(1);
```
[the remark this answers is not in the document]
Comment (pilleye) [reply crates/red_knot_test/src/parser.rs:250]: Used a mix of the two, using offset within the entire Markdown file to find the line that the backticks of a code block start on. Then, we just add the line onto the line number reported from the linter itself.

**Comment by pilleye** [comment]
Think I mostly cleaned up the comments, would appreciate another review. I'm now returning a `Vec<FailuresByLine>`, where the paths that are checked are sorted by their starting position, so errors should occur from top-to-bottom.

**Comment by pilleye** [comment]
https://github.com/user-attachments/assets/9cd21d21-f4e2-4f0d-8212-5375a312b7fd

File: crates/red_knot_test/src/lib.rs [hunk 4]
```diff
@@ -32,13 +32,13 @@ pub fn run(path: &Path, title: &str) {
     for test in suite.tests() {
         if let Err(failures) = run_test(&test) {
             any_failures = true;
-            println!("\n{}\n", test.name().bold().underline());
+            println!("\n{}", test.name().bold().underline());
```
Comment (AlexWaygood) [inline crates/red_knot_test/src/lib.rs:35]: nit: I think the blank line in between the title and the line-by-line details really helps readability here; I'd keep it, personally 😄

```suggestion
            println!("\n{}\n", test.name().bold().underline());
```

File: crates/red_knot_test/src/parser.rs [hunk 5]
```diff
@@ -270,6 +292,13 @@ impl<'s> Parser<'s> {
 
         self.current_section_files = None;
 
+        self.increment_offset(
+            captures
+                .get(0)
+                .ok_or_else(|| anyhow::anyhow!("No captures found"))?
+                .len(),
+        )?;
+
```
Comment (MichaReiser) [inline crates/red_knot_test/src/parser.rs:301]: We should move this into `scan` to avoid repeating the same code

File: crates/red_knot_test/src/parser.rs [hunk 6]
```diff
@@ -303,6 +332,8 @@ impl<'s> Parser<'s> {
             // CODE_RE can't match without matches for 'lang' and 'code'.
             lang: captures.name("lang").unwrap().into(),
             code: captures.name("code").unwrap().into(),
+
+            starting_line_number: self.line_index.line_index(self.md_offset),
```
Comment (MichaReiser) [inline crates/red_knot_test/src/parser.rs:336]: I suggest just storing the embedded file and compute the line number when needed. It has the advantage that the test framework doesn't need to compute the `LineIndex` if there are no errors. Ccomputing the `LineIndex` isn't expensive, but it can add up. Quering the line index is `O(log(n))`, so that's not entirely free as well.

File: crates/red_knot_test/src/lib.rs [hunk 7]
```diff
@@ -65,31 +72,40 @@ fn run_test(test: &parser::MarkdownTest) -> Result<(), Failures> {
...
+            Err(line_failures) => {
+                failures.push(line_failures.offset_errors(contextual_path.starting_line_number));
+            }
+        }
     }
+
     if failures.is_empty() {
         Ok(())
     } else {
+        failures.shrink_to_fit();
```
Comment (MichaReiser) [inline crates/red_knot_test/src/lib.rs:108]: I don't think calling `shrink_to_fit` gives us much here. `shrink_to_fit` is mainly useful if you have a long-living `Vec` to avoid wasting memory. The failures are consumed right away (and if not, let the caller handle it) and then dropped.

**Review by MichaReiser — COMMENTED** [review]
I would still suggest to store offsets to avoid computing the markdown `LineIndex` unnecessarily. 

We also discussed removing the grouping by test file and I see that you kept it. What's your motivation for keeping the grouping?

**Comment by AlexWaygood** [comment]
> We also discussed removing the grouping by test file and I see that you kept it. What's your motivation for keeping the grouping?

@MichaReiser I think this feedback was mostly addressed. The errors are no longer grouped according to the _embedded Python file inside a single Markdown test_. Here's what it currently looks like on this PR branch if some tests fail:

<details>
<summary>Screenshot</summary>

image

</details>

And here's what the same failures looked like on this PR branch prior to https://github.com/astral-sh/ruff/pull/13804/commits/5d20b5c3cca2e56a866301204884e3c71aae81f8

<details>
<summary>Screenshot</summary>

image

</details>

So the `/src/test.py`, `/src/branches_unify_to_non_union_type.py`, `/src/union_type_inferred.py` and `/src/test.py` headings are gone. (These all told you the name of the _embedded Python file_ inside a specific Markdown test.) However, there's still an unnecessary line break in between ```/exception/control_flow.md:53 unexpected error: [revealed-type] "Revealed type is `Literal[2]`"``` and ```/exception/control_flow.md:74 unmatched assertion: revealed: bytes```: the errors before the line break occur in one embedded Python code block, and the errors after the line break occur in a different Python code block. I think this line break is unnecessary; @pilleye could you possibly get rid of it?

For the record, this is the diff I made to `crates/red_knot_python_semantic` in order to get these screenshots:

<details>
<summary>Diff to trigger test failures</summary>

```diff
diff --git a/crates/red_knot_python_semantic/resources/mdtest/exception/control_flow.md b/crates/red_knot_python_semantic/resources/mdtest/exception/control_flow.md
index f7cf500d0..792d9ed69 100644
--- a/crates/red_knot_python_semantic/resources/mdtest/exception/control_flow.md
+++ b/crates/red_knot_python_semantic/resources/mdtest/exception/control_flow.md
@@ -46,11 +46,11 @@ x = 1
 try:
     reveal_type(x)  # revealed: Literal[1]
     x = could_raise_returns_str()
-    reveal_type(x)  # revealed: str
+    reveal_type(x)  # revealed: int
 except:
     reveal_type(x)  # revealed: Literal[1] | str
     x = 2
-    reveal_type(x)  # revealed: Literal[2]
+    reveal_type(x)
 
 reveal_type(x)  # revealed: str | Literal[2]
 ```
@@ -71,7 +71,7 @@ try:
 except:
     x = could_raise_returns_str()
 
-reveal_type(x)  # revealed: str
+reveal_type(x)  # revealed: bytes
 ```
 
 ## A non-bare `except`
@@ -92,7 +92,7 @@ def could_raise_returns_str() -> str:
 x = 1
 
 try:
-    reveal_type(x)  # revealed: Literal[1]
+    reveal_type(x)  # revealed: str
     x = could_raise_returns_str()
     reveal_type(x)  # revealed: str
 except TypeError:
diff --git a/crates/red_knot_python_semantic/resources/mdtest/exception/except_star.md b/crates/red_knot_python_semantic/resources/mdtest/exception/except_star.md
index 44d701d1f..b44572c43 100644
--- a/crates/red_knot_python_semantic/resources/mdtest/exception/except_star.md
+++ b/crates/red_knot_python_semantic/resources/mdtest/exception/except_star.md
@@ -6,7 +6,7 @@
 try:
     x
 except* BaseException as e:
-    reveal_type(e)  # revealed: BaseExceptionGroup
+    reveal_type(e)  # revealed: int
 ```
```

</details>

The failures are still grouped according to the name of the Markdown test inside the Markdown file, but I find that very helpful: it means you can have some idea of what kinds of tests are failing without even having to jump and look at the specific assertions that are failing.

**Comment by pilleye** [comment]
> The errors before the line break occur in one embedded Python code block, and the errors after the line break occur in a different Python code block. I think this line break is unnecessary; @pilleye could you possibly get rid of it?

Screenshot 2024-10-21 at 9 46 50 AM

**Review by AlexWaygood — APPROVED** [review]
This LGTM now. Thanks again! @MichaReiser, anything more to you?

**Comment by MichaReiser** [comment]
I'll re-review tomorrow morning

File: crates/red_knot_test/src/lib.rs [hunk 8]
```diff
@@ -30,33 +31,38 @@ pub fn run(path: &Path, title: &str) {
...
     }
 
-    println!("{}\n", "-".repeat(50));
+    println!("\n{}\n", "-".repeat(50));
 
     assert!(!any_failures, "Some tests failed.");
 }
 
-fn run_test(test: &parser::MarkdownTest) -> Result<(), Failures> {
+struct AbsoluteLineNumberPath {
```
Comment (carljm) [inline crates/red_knot_test/src/lib.rs:54]: nit: this doesn't store a line number anymore, maybe `PathWithOffset`?

File: crates/red_knot_test/src/lib.rs [hunk 9]
```diff
@@ -65,28 +71,43 @@ fn run_test(test: &parser::MarkdownTest) -> Result<(), Failures> {
...
         db.write_file(&full_path, file.code).unwrap();
-        system_paths.push(full_path);
+        paths.push(AbsoluteLineNumberPath {
+            path: full_path,
+            md_offset: file.md_offset,
+        });
     }
 
-    let mut failures = BTreeMap::default();
+    let mut failures = Vec::with_capacity(paths.len());
```
Comment (carljm) [inline crates/red_knot_test/src/lib.rs:80]: This may be a holdover from a previous version of the PR, but I don't think this `with_capacity` really makes sense anymore. This vector isn't going to have a number of entries based on the number of embedded files, it'll have a number of entries based on the number of lines with failures on them. In the ideal scenario (where arguably we care the most about speed) it'll be an empty vec. So I think it would be better to optimistically not allocate:
```suggestion
    let mut failures = Vec::default();
```

File: crates/red_knot_test/src/lib.rs [hunk 10]
```diff
@@ -65,28 +71,43 @@ fn run_test(test: &parser::MarkdownTest) -> Result<(), Failures> {
...
 
-    for path in system_paths {
-        let file = system_path_to_file(&db, path.clone()).unwrap();
+    for contextual_path in paths {
```
Comment (carljm) [inline crates/red_knot_test/src/lib.rs:82]: naming nit: I don't think `contextual_path` is very clear, I'd name the struct `PathWithOffset` (as mentioned above) and name this `path_with_offset`.

File: crates/red_knot_test/src/matcher.rs [hunk 11]
```diff
@@ -41,6 +41,23 @@ impl FailuresByLine {
...
+                .map(|line_failures| LineFailures {
+                    line_number: line_failures
+                        .line_number
+                        .checked_add(offset)
+                        .expect("The number of lines in a test file should fit into a `usize`"),
+                    range: line_failures.range,
+                })
+                .collect(),
+        }
+    }
```
Comment (carljm) [inline crates/red_knot_test/src/matcher.rs:60]: I think we could avoid eagerly copying the entire `lines` vec by instead just adding a `starting_line_number` or `line_offset` field to `FailuresByLine`, and adding the offset to each line number in `FailuresByLine::iter` instead.

File: crates/red_knot_test/src/parser.rs [hunk 12]
```diff
@@ -131,6 +140,9 @@ pub(crate) struct EmbeddedFile<'s> {
     pub(crate) path: &'s str,
     pub(crate) lang: &'s str,
     pub(crate) code: &'s str,
+
+    /// The offset of the backticks in the markdown file
```
Comment (carljm) [inline crates/red_knot_test/src/parser.rs:144]:
```suggestion
    /// The offset of the backticks beginning the code block within the markdown file
```

**Review by carljm — APPROVED** [review]
The behavior here looks good to me; thanks @pilleye!!

Some comments on the code; maybe wait to implement them until @MichaReiser has a look, in case he has a different idea on any of this, since he's done some recent work on mdtest perf.

**Comment by MichaReiser** [comment]
I can help tomorrow morning with merging my latest changes into this PR.

**Review by MichaReiser — APPROVED** [review]
