### PR TITLE
[`pep8-naming`] Suppress fix for `N804` and `N805` if the recommend name is already used

### LINKED ISSUE #18459: N805 fix should be suppressed when another variable is using the recommended name
### Summary

The fix for [`invalid-first-argument-name-for-method` (N805)](https://docs.astral.sh/ruff/rules/invalid-first-argument-name-for-method/) should be suppressed when the recommended parameter name is already taken by another variable used within that scope.

```console
$ cat >n805.py <<'# EOF'
class C:
    def f(this):
        self = type(this).__name__
        print(self, this.__sizeof__())
C().f()
# EOF

$ python n805.py
C 16

$ ruff --isolated check n805.py  --select N805 --unsafe-fixes --fix
Found 1 error (1 fixed, 0 remaining).

$ cat n805.py
class C:
    def f(self):
        self = type(self).__name__
        print(self, self.__sizeof__())
C().f()

$ python n805.py
C 42
```

### Version

ruff 0.11.12 (aee3af0f7 2025-05-29)

### PR DESCRIPTION
**Pull request by LaBatata101**
## Summary

Fixes #18459.

Wasn't mentioned in the issue but the `N804` rule is also affected.

## Test Plan

Add regression tests.

### CODE REVIEW

File: crates/ruff_linter/src/rules/pep8_naming/rules/invalid_first_argument_name.rs [hunk 1]
```diff
@@ -300,6 +300,14 @@ fn rename_parameter(
         return Ok(None);
     }
 
+    // Don't fix if `self` or `cls` is already defined in the scope.
+    if scope
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pep8_naming/rules/invalid_first_argument_name.rs]: We may want to use https://github.com/astral-sh/ruff/blob/ff6f0b6ab8fef4df5a14651cf9ef86f016ec0367/crates/ruff_linter/src/rules/pyupgrade/rules/pep695/private_type_parameter.rs#L137-L139 to also avoid shadowing other variables

**Comment by MichaReiser** [comment]
Thank you
