### PR TITLE
Skip serializing cell ID if it's None

### LINKED ISSUE #6834: Ruff inserts `"id": null` to notebook cells and breaks GitHub notebook viewer
## Summary

https://github.com/harupy/mlflow/blob/3f1650db853d2c61ac0cdb0035be91b10f131859/examples/h2o/random_forest.ipynb

image

https://github.com/harupy/mlflow/commit/3f1650db853d2c61ac0cdb0035be91b10f131859: a commit that replicates what ruff does:

Without `"id": null`, the notebook renders fine:
https://github.com/harupy/mlflow/blob/dab36dc4fd6ac6e442bb78c016e7813ced8c0a21/examples/h2o/random_forest.ipynb

image

## How to reproduce

```sh
# Notebook without id
> cat a.ipynb
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import math\n",
    "import os\n",
    "\n",
    "math.pi"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (ruff)",
   "language": "python",
   "name": "ruff"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

# Run ruff
> cargo run -p ruff_cli -- check --fix --no-cache a.ipynb
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/ruff check --fix --no-cache a.ipynb`
Found 1 error (1 fixed, 0 remaining).

# Check
> cat a.ipynb
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import math\n",
    "\n",
    "math.pi"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (ruff)",
   "language": "python",
   "name": "ruff"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
```

### PR DESCRIPTION
**Pull request by harupy**
## Summary

Fix #6834 

## Test Plan

Need tests?

### CODE REVIEW

**Review by konstin — COMMENTED** [review]
Could you please add either a <4.5 notebook or reuse crates/ruff/resources/test/fixtures/jupyter/valid.ipynb to add a test in notebook.rs? I think the easiest is to serialize it to a string and check that the string doesn't contain `"id"`. (validating against the jupyter notebook schema would also be possible but it feels like an overkill)

**Comment by harupy** [comment]
@konstin Added a test!

File: crates/ruff/src/jupyter/schema.rs [hunk 1]
```diff
@@ -150,6 +152,7 @@ pub struct CodeCell {
     /// Technically, id isn't required (it's not even present) in schema v4.0 through v4.4, but
     /// it's required in v4.5. Main issue is that pycharm creates notebooks without an id
     /// <https://youtrack.jetbrains.com/issue/PY-59438/Jupyter-notebooks-created-with-PyCharm-are-missing-the-id-field-in-cells-in-the-.ipynb-json>
+    #[serde(skip_serializing_if = "Option::is_none")]
```
Comment (dhruvmanila) [inline crates/ruff/src/jupyter/schema.rs:155]: Wait, we already have `#[skip_serializing_none]` for other cell types, it's not added to `CodeCell` because the field `execution_count` is [required](https://github.com/jupyter/nbformat/blob/a3e787dccbf629c8cbae46f79e74d53ded8b53a9/nbformat/v4/nbformat.v4.5.schema.json#L197). The solution is to use `serialize_always` _only_ on `id` field of `CodeCell`.

```suggestion
    #[serialize_always]
```

File: crates/ruff/src/jupyter/schema.rs [hunk 2]
```diff
@@ -120,6 +120,7 @@ pub struct RawCell {
...
```
Comment (dhruvmanila) [inline crates/ruff/src/jupyter/schema.rs:123]: We already use `#[skip_serializing_none]` on the struct

```suggestion
```

File: crates/ruff/src/jupyter/schema.rs [hunk 3]
```diff
@@ -135,6 +136,7 @@ pub struct MarkdownCell {
...
```
Comment (dhruvmanila) [inline crates/ruff/src/jupyter/schema.rs:139]: We already use `#[skip_serializing_none]` on the struct

```suggestion
```

**Review by dhruvmanila — APPROVED** [review]
Thanks! Can you make the suggested changes and then it should be good to go!

**Review by konstin — APPROVED** [review]
thanks
