### PR TITLE
[ruff] Skip tuples with slice expressions in `incorrectly-parenthesized-tuple-in-subscript (RUF031)`

### LINKED ISSUE #12766: RUF031 fix introduces a syntax error when the tuple contains a slice
The fix for RUF031 introduces a syntax error when `lint.ruff.parenthesize-tuple-in-subscript = true` and the subscripted tuple contains a slice.

```console
$ ruff --version
ruff 0.5.7
$ cat ruf031.py
x[:,]
$ ruff check --isolated --preview --select RUF031 --config 'lint.ruff.parenthesize-tuple-in-subscript = true' ruf031.py --fix

error: Fix introduced a syntax error. Reverting all changes.

This indicates a bug in Ruff. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BFix%20error%5D

...quoting the contents of `ruf031.py`, the rule codes RUF031, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

ruf031.py:1:3: RUF031 Use parentheses for tuples in subscripts.
  |
1 | x[:,]
  |   ^^ RUF031
  |
  = help: Parenthesize the tuple.

Found 1 error.
[*] 1 fixable with the `--fix` option.
```

### PR DESCRIPTION
**Pull request by dylwil3**
## Summary

Adding parentheses to a tuple in a subscript with elements that include slice expressions causes a syntax error.  For example, `d[(1,2,:)]` is a syntax error.

So, when `lint.ruff.parenthesize-tuple-in-subscript = true` and the tuple includes a slice expression, we skip this check and fix.

Closes #12766.

### CODE REVIEW

**Comment by dylwil3** [comment]
Probably should wait until #12762 is merged in and the subsequent merge conflicts have been resolved.

**Comment by charliermarsh** [comment]
Thanks @dylwil3!

**Review by MichaReiser — APPROVED** [review]

File: crates/ruff_linter/src/rules/ruff/rules/incorrectly_parenthesized_tuple_in_subscript.rs [hunk 1]
```diff
@@ -64,6 +64,10 @@ pub(crate) fn subscript_with_parenthesized_tuple(checker: &mut Checker, subscrip
     if tuple_subscript.parenthesized == prefer_parentheses || tuple_subscript.elts.is_empty() {
         return;
     }
+    // Adding parentheses in the presence of a slice leads to a syntax error.
+    if prefer_parentheses & tuple_subscript.elts.iter().any(Expr::is_slice_expr) {
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/ruff/rules/incorrectly_parenthesized_tuple_in_subscript.rs:68]: This is a bitwise `&` but I think we want a boolean `&`

```suggestion
    if prefer_parentheses && tuple_subscript.elts.iter().any(Expr::is_slice_expr) {
```

**Review by AlexWaygood — APPROVED** [review]
Thanks!

**Comment by AlexWaygood** [comment]
The fix being applied in this PR is very specific. But I think that's okay, because I think this syntax error can only occur due to the very specific details of literal slices inside subscripts. So I don't think the bug report reveals a deeper underlying issue that we need to fix.
