### PR TITLE
[ty] Defer base inference for functional `type(...)` classes

### LINKED ISSUE #2564: Panic if a self-referential base is passed to a three-argument `type()` call
ty currently panics on this:

```py
X = type("X", (tuple["X | None"],), {})
```

```
error[panic]: Panicked at /Users/alexw/.cargo/git/checkouts/salsa-e6f3bb7c2a062968/9860ff6/src/function/execute.rs:743:9 when checking `/Users/alexw/dev/ruff/foo.py`: `infer_definition_types(Id(1400)): execute: too many cycle iterations`
info: This indicates a bug in ty.
info: If you could open an issue at https://github.com/astral-sh/ty/issues/new?title=%5Bpanic%5D, we'd be very appreciative!
info: Platform: macos aarch64
info: Version: ruff/0.14.13+65 (bffc95873 2026-01-19)
info: Args: ["target/debug/ty", "check", "foo.py", "--python-version=3.14", "--ignore=undefined-reveal"]
info: run with `RUST_BACKTRACE=1` environment variable to show the full backtrace information
info: query stacktrace:
   0: infer_scope_types(Id(1000))
             at crates/ty_python_semantic/src/types/infer.rs:70
   1: check_file_impl(Id(c00))
             at crates/ty_project/src/lib.rs:554
```

After https://github.com/astral-sh/ruff/pull/22718 has landed, things like this will also panic:

```py
from typing import NamedTuple

X = type("X", (NamedTuple("NT", [("field", "X | int")]),), {})
```

The fix is probably to defer inference of the `bases` argument in "non-dangling" three-argument `type()` calls, the same way as we defer inference of the bases list in regular `class` statements. "Non-dangling" means three-argument `type()` calls where the call is immediately assigned to a value, such as the above assignment to `X`.

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Closes https://github.com/astral-sh/ty/issues/2564.

### CODE REVIEW

File: crates/ty_python_semantic/src/types/infer/builder.rs [hunk 1]
```diff
@@ -6340,6 +6340,15 @@ impl<'db, 'ast> TypeInferenceBuilder<'db, 'ast> {
...
         }
+        if known_class == Some(KnownClass::Type) {
+            // Infer the `bases` argument for three-argument `type()` calls.
+            // This is deferred to break cycles for self-referential definitions
+            // like `X = type("X", (tuple["X | None"],), {})`.
+            if arguments.args.len() >= 2 {
+                self.infer_expression(&arguments.args[1], TypeContext::default());
+            }
+            return;
+        }
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/infer/builder.rs]: nit: make this a match?

File: crates/ty_python_semantic/resources/mdtest/call/type.md
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/call/type.md:1]: Can you also add the `X = type("X", (tuple["X | None"],), {})` example I had in https://github.com/astral-sh/ty/issues/2564 as a test case? The issue was not limited to `NamedTuple` dangling calls nested inside of `type()` calls, it was broader (which is why we're fixing it in the more general way)

`X = type("X", (tuple["X | None"],), {})` fails at runtime, but that's not really relevant to what the test would be demonstrating -- we shouldn't panic on the code, whether it succeeds at runtime or not 😆

File: crates/ty_python_semantic/src/types/class.rs [hunk 2]
```diff
@@ -81,6 +84,14 @@ use ruff_text_size::{Ranged, TextRange};
 use rustc_hash::FxHashSet;
 use ty_module_resolver::{KnownModule, file_to_module};
 
+fn static_class_explicit_bases_cycle_initial<'db>(
+    _db: &'db dyn Db,
+    _id: salsa::Id,
+    _self: StaticClassLiteral<'db>,
+) -> Box<[Type<'db>]> {
+    Box::default()
+}
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]: the latest version of Salsa that we're on now supports inlined recovery functions (e.g. see https://github.com/astral-sh/ruff/pull/22814) -- could you inline this (and the other new recovery functions) as a closure?

File: crates/ty_python_semantic/src/types/class.rs [hunk 3]
```diff
@@ -5051,6 +5080,75 @@ impl<'db> DynamicClassLiteral<'db> {
...
+        // Infer the `bases` type.
+        let bases_type = match self.anchor(db) {
+            DynamicClassAnchor::Definition(definition) => {
+                // Use `definition_expression_type` for deferred inference support.
+                definition_expression_type(db, definition, bases_arg)
+            }
+            DynamicClassAnchor::ScopeOffset { .. } => {
+                // For dangling calls, the bases were already inferred as part of the scope.
+                infer_complete_scope_types(db, scope).expression_type(bases_arg)
+            }
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]: `infer_complete_scope_types` is somewhat expensive, and more likely to lead to cycles than `definition_expression_type`. I also don't think it's necessary to lazily infer the bases for a dangling `type()` call, as it's impossible for a dangling `type()` call to refer recursively back to the class that the dangling call creates -- I think it's only necessary to defer inference of bases when the `type()` call is immediately assigned to a variable. So for `DynamicClassAnchor::ScopeOffset{}`, I would be inclined to store the inferred types of the bases directly on the enum variant, in the same way that store the `NamedTupleSpec` directly on the `DynamicNamedTupleAnchor::ScopeOffset{}` variant

File: crates/ty_python_semantic/resources/mdtest/call/type.md [hunk 4]
```diff
@@ -753,6 +753,35 @@ in the bases tuple before it's available:
...
+Forward references also work when a static class inherits from a dynamic class that references it:
+
+```py
+from typing import NamedTuple
+
+# Static class inheriting from dynamic class with forward ref back to static class
+class Y(type("X", (NamedTuple("NT", [("field", "Y | int")]),), {})): ...
+
+reveal_type(Y)  # revealed: <class 'Y'>
+```
```
Comment (carljm) [inline crates/ty_python_semantic/resources/mdtest/call/type.md:842]: One of the subtle gotchas of mdtest is the way multiple unnamed snippets in the same test header are implicitly concatenated into a single file. I think this is a case where it's somewhat dangerous to rely on this, because we are reusing the same names (e.g. `X`) in these snippets, and we are testing forward-reference behavior.

I don't think there's an actual problem with these tests right now, but I do think they'd be more robust to future changes and easier to reason about if we separated them with headers, e.g.:

````diff
diff --git a/crates/ty_python_semantic/resources/mdtest/call/type.md b/crates/ty_python_semantic/resources/mdtest/call/type.md
index a5fe82a0f8..9bedc267e7 100644
--- a/crates/ty_python_semantic/resources/mdtest/call/type.md
+++ b/crates/ty_python_semantic/resources/mdtest/call/type.md
@@ -745,6 +745,8 @@ Y = type("Y", bases, {})

 ## Cyclic functional class definitions

+### Self-referential
+
 Self-referential class definitions using `type()` are detected. The name being defined is referenced
 in the bases tuple before it's available:

@@ -753,13 +755,17 @@ in the bases tuple before it's available:
 X = type("X", (X,), {})
 ```
-String literals in the bases tuple are not valid class bases:
+### No string literal bases
+
+String literals directly in the bases tuple are not valid class bases:

 ```py
 # error: [invalid-base] "Invalid class base with type `Literal["X"]`"
 X = type("X", ("X",), {})
 ```

+### Forward references via string annotations
+
 However, forward references via string annotations are supported, similar to regular class
 definitions. This works with `NamedTuple` where field annotations can be forward references:

@@ -771,6 +777,8 @@ X = type("X", (NamedTuple("NT", [("field", "X | int")]),), {})
 reveal_type(X)  # revealed: <class 'X'>
 ```

+### Static class inheriting from dynamic class with forward ref
+
 Forward references also work when a static class inherits from a dynamic class that references it:

 ```py
````

File: crates/ty_python_semantic/src/types/infer/builder.rs [hunk 5]
```diff
@@ -6633,17 +6646,81 @@ impl<'db, 'ast> TypeInferenceBuilder<'db, 'ast> {
...
             members,
             has_dynamic_namespace,
             None,
         );
 
+        // For assigned `type()` calls, the bases are inferred via deferred inference after the
+        // class is created. For dangling calls, `bases_type` is already available from immediate
+        // inference.
+        let bases_type =
+            bases_type.unwrap_or_else(|| self.infer_expression(bases_arg, TypeContext::default()));
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/infer/builder.rs]: As discussed above, I think this addition is a plausible-looking no-op. We've only "deferred" anything from a few lines above in the same method, which doesn't actually do anything.

File: crates/ty_python_semantic/src/types/mro.rs [hunk 6]
```diff
@@ -327,69 +327,90 @@ impl<'db> Mro<'db> {
...
-        let mut seen = FxHashSet::default();
-        let mut duplicates = Vec::new();
-        for base in bases {
-            if matches!(base, ClassBase::Dynamic(_)) {
-                continue;
-            }
-            if !seen.insert(*base) {
-                duplicates.push(*base);
+        // Use a placeholder class literal for try_from_type (the subclass parameter is only
+        // used for Protocol/TypedDict detection which doesn't apply here).
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/mro.rs]: almost :P

```suggestion
        // Use a placeholder class literal for try_from_type (the subclass parameter is only
        // used for NamedTuple subclasses, which doesn't apply here).
```

File: crates/ty_python_semantic/src/types/mro.rs [hunk 7]
```diff
@@ -702,6 +731,15 @@ impl<'db> DynamicMroError<'db> {
...
+    ///
+    /// Similar to `StaticMroErrorKind::InvalidBases`, this records the indices
+    /// and types of bases that could not be converted to valid class bases.
+    InvalidBases(Box<[(usize, Type<'db>)]>),
+
+    /// A cycle was encountered resolving the class' bases.
+    InheritanceCycle,
+
     /// The class has duplicate bases in its bases tuple.
     DuplicateBases(Box<[ClassBase<'db>]>),
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/mro.rs:814]: it seems like the _only_ variant that exists on `StaticMroErrorKind` but not this one is now `Pep695ClassWithGenericInheritance`. Which makes me wonder if it's really still worth having two enums, or if they could be combined?

Hmm, but maybe there's still enough annoying differences in the wrapped data that it's worth having the two enums stay different ☹️ we could always look at combining them as a followup, I guess

File: crates/ty_python_semantic/src/types/infer/builder.rs [hunk 8]
```diff
@@ -6507,7 +6516,14 @@ impl<'db, 'ast> TypeInferenceBuilder<'db, 'ast> {
...
         let name_type = self.infer_expression(name_arg, TypeContext::default());
-        let bases_type = self.infer_expression(bases_arg, TypeContext::default());
+        // For assigned `type()` calls, defer bases inference to break cycles for self-referential
+        // definitions like `X = type("X", (tuple["X | None"],), {})`. The bases will be inferred
+        // later via `DynamicClassLiteral::explicit_bases()`.
+        let bases_type = if definition.is_some() {
+            None
+        } else {
+            Some(self.infer_expression(bases_arg, TypeContext::default()))
+        };
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/infer/builder.rs]: I found this change pretty confusing -- it looks reasonable on the surface, but it's actually just a no-op? The `infer_expression` call is only "deferred" until a bit later in this method (line 6660 below), which doesn't actually make any difference. Tests all pass on this PR with this diff:

<summary>

<details>

```diff
diff --git a/crates/ty_python_semantic/src/types/infer/builder.rs b/crates/ty_python_semantic/src/types/infer/builder.rs
index 80c27342a9..335af6f361 100644
--- a/crates/ty_python_semantic/src/types/infer/builder.rs
+++ b/crates/ty_python_semantic/src/types/infer/builder.rs
@@ -6519,11 +6519,7 @@ impl<'db, 'ast> TypeInferenceBuilder<'db, 'ast> {
         // For assigned `type()` calls, defer bases inference to break cycles for self-referential
         // definitions like `X = type("X", (tuple["X | None"],), {})`. The bases will be inferred
         // later via `DynamicClassLiteral::explicit_bases()`.
-        let bases_type = if definition.is_some() {
-            None
-        } else {
-            Some(self.infer_expression(bases_arg, TypeContext::default()))
-        };
+        let bases_type = self.infer_expression(bases_arg, TypeContext::default());
         let namespace_type = self.infer_expression(namespace_arg, TypeContext::default());

         // TODO: validate other keywords against `__init_subclass__` methods of superclasses
@@ -6653,12 +6649,6 @@ impl<'db, 'ast> TypeInferenceBuilder<'db, 'ast> {
             None,
         );

-        // For assigned `type()` calls, the bases are inferred via deferred inference after the
-        // class is created. For dangling calls, `bases_type` is already available from immediate
-        // inference.
-        let bases_type =
-            bases_type.unwrap_or_else(|| self.infer_expression(bases_arg, TypeContext::default()));
-
         // Validate bases and collect disjoint bases for diagnostics.
         let mut disjoint_bases = self.validate_dynamic_type_bases(bases_arg, bases_type, &name);
```

</details>

</summary>

I'm still working on getting a full understanding of _why_ this `infer_expression` doesn't actually need to be deferred.

File: crates/ty_python_semantic/src/types/infer/builder.rs [hunk 9]
```diff
@@ -6633,17 +6646,81 @@ impl<'db, 'ast> TypeInferenceBuilder<'db, 'ast> {
...
+        // inference.
+        let bases_type =
+            bases_type.unwrap_or_else(|| self.infer_expression(bases_arg, TypeContext::default()));
+
+        // Validate bases and collect disjoint bases for diagnostics.
+        let mut disjoint_bases = self.validate_dynamic_type_bases(bases_arg, bases_type, &name);
+
         // Check for MRO errors.
         match dynamic_class.try_mro(db) {
             Err(error) => match error.reason() {
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/infer/builder.rs]: same comment as https://github.com/astral-sh/ruff/pull/22586#discussion_r2716645173 -- immediately asking the types of the bases to be resolved like this seems like it will immediately trigger Salsa's cycle handling if we _are_ inferring the type of a `type()` call where the bases refer recursively to the type being defined. For non-dangling `type()` calls, we should postpone these checks until we've inferred types for the rest of the scope, in the same way that we do for static classes in `check_class_definitions()`

**Review by AlexWaygood — COMMENTED** [review]
Looks to be along the right lines! A few comments

File: crates/ty_python_semantic/src/types/infer/builder.rs (hunk 1 above)
Comment (carljm) [inline crates/ty_python_semantic/src/types/infer/builder.rs]: This new clause doesn't seem to do anything. Tests all pass if it is removed.

As far as I can tell, this PR doesn't actually use the "deferred inference" infrastructure at all -- using that requires at some point skipping inference of some expression and inserting a definition into `self.deferred`, and I don't see anywhere we do that.

I think this is related to the comments below about how we are never actually deferring inference of the bases arg. (And it seems like we don't need to? Which I don't yet fully understand.)

**Review by carljm — COMMENTED** [review]
Was partway through a review, but since Alex just submitted a review, I'll submit what I have to avoid multiple rounds of revision. Still some things I don't quite understand here.

File: crates/ty_python_semantic/src/types/infer/builder.rs (hunk 8 above)
Comment (AlexWaygood) [reply crates/ty_python_semantic/src/types/infer/builder.rs]: it's because he's added Salsa-tracked methods in `class.rs`. Salsa's cycle handling saves him. But that's much more expensive than it _needs_ to be.

Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/infer/builder.rs]: Hmm, I assume I should be following `typing.NamedTuple`, i.e., actually defer these? But I'm confused why all tests pass as-is.

Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/infer/builder.rs]: Oh, maybe this is sufficient because we don't have to support deferred type evaluation (like string annotations), unlike `NamedTuple` fields?

Comment (AlexWaygood) [reply crates/ty_python_semantic/src/types/infer/builder.rs]: > Hmm, I assume I should be following `typing.NamedTuple`, i.e., actually defer these?

Yes!

> But I'm confused why all tests pass in that case.

Salsa's able to resolve the cycle via fixpoint iteration, because of the fact that you added `#[salsa::tracked]` to several methods in `class.rs`. But that can be really expensive, even if it means that no tests are failing. Avoiding eager resolution of bases and MROs will be much better for performance.

Now, admittedly, recursive `type()` calls are likely to be exceedingly rare. But it still seems better here to follow the pattern we've already established for dynamic `NamedTuple`s and static classes, and which we will continue to employ elsewhere in the future for functional `TypedDict`s and `make_dataclass()` calls.

Comment (AlexWaygood) [reply crates/ty_python_semantic/src/types/infer/builder.rs]: > Oh, maybe this is sufficient because we don't have to support deferred type evaluation (like string annotations), unlike `NamedTuple` fields?

We sort-of _do_, because we'll call `self.infer_type_expression` on the string `"X | None` in a `t = type("t", (tuple["X | None"],), {})` call.

Using `tuple["X | None"]` as a base in a `type()` call is invalid. But we can't _figure out_ that it's invalid until we've determined what the type of `tuple["X | None"]` is. And in order to infer that type we call `self.infer_type_expression()` on the string, which immediately triggers a cycle

File: crates/ty_python_semantic/src/types/class.rs [hunk 10]
```diff
@@ -5018,6 +5034,63 @@ impl<'db> DynamicClassLiteral<'db> {
...
+    pub(crate) fn explicit_bases(self, db: &'db dyn Db) -> Box<[Type<'db>]> {
+        // For dangling calls, bases are stored directly on the anchor.
+        if let DynamicClassAnchor::ScopeOffset { explicit_bases, .. } = self.anchor(db) {
+            return explicit_bases;
+        }
+
+        // For assigned calls, we need to use deferred inference.
+        let DynamicClassAnchor::Definition(definition) = self.anchor(db) else {
+            unreachable!("handled above")
+        };
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]: The pattern I used in the `NamedTuple` PR was to use an inner cached function inside `NamedTuple::spec()`. The advantage of that is that we only call the cached function in the case where we actually deferred inference of the class's bases (if `DynamicNamedTupleAnchor` is `DynamicNamedTupleAnchor::TypingDefinition()`).

https://github.com/astral-sh/ruff/blob/73399e53dab9d0fefd98b75b68017e5880a4635d/crates/ty_python_semantic/src/types/class.rs#L5730-L5759

If `self.anchor()` is `DynamicClassAnchor::ScopeOffset`, there should be no need to call a cached function, which is bad for our memory usage. The explicit bases are already store directly on the enum variant.

**Comment by charliermarsh** [comment]
(I pushed some improvements but need to spend a little more time with the PR before I take it out of draft.)

**Comment by charliermarsh** [comment]
I'll open this back up for review.

File: crates/ty_python_semantic/src/types/class.rs [hunk 11]
```diff
@@ -131,6 +132,20 @@ fn try_metaclass_cycle_initial<'db>(
...
+    db: &'db dyn Db,
+    _id: salsa::Id,
+    self_: DynamicClassLiteral<'db>,
+) -> Result<Mro<'db>, DynamicMroError<'db>> {
+    // When there's a cycle, return a minimal MRO with just the class itself and object.
+    // This breaks the cycle and allows type checking to continue.
+    Ok(Mro::from([
+        ClassBase::Class(ClassType::NonGeneric(self_.into())),
+        ClassBase::object(db),
+    ]))
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/class.rs:144]: This seems reasonable in general -- are there bad effects if we do this for static class cycle initial also?

File: crates/ty_python_semantic/src/types/mro.rs [hunk 12]
```diff
@@ -327,69 +327,90 @@ impl<'db> Mro<'db> {
...
-        for base in bases {
-            if matches!(base, ClassBase::Dynamic(_)) {
-                continue;
-            }
-            if !seen.insert(*base) {
-                duplicates.push(*base);
+        // Use a placeholder class literal for try_from_type (the subclass parameter is only
+        // used for NamedTuple subclasses, which doesn't apply here).
+        let placeholder_class: ClassLiteral<'db> =
+            KnownClass::Object.try_to_class_literal(db).unwrap().into();
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/mro.rs]: We do this three different places in this diff, and even with the comment it's pretty opaque what's going on here unless you actually go read `try_from_type`.

I think there are a couple things here:

1) The comment says `NamedTuple` "doesn't apply here", but why not? We should add a test for what happens when you try to create a dynamic class inheriting from `typing.NamedTuple`. Would be fine if we just error on it, since an error is what you get at runtime -- but since its a weird edge case, we should test it to make sure it doesn't panic.

2) If we have multiple places where we need "`ClassBase.try_from_type` but without a concrete subclass, error if you try to inherit `NamedTuple`" (which seems like probably the right answer here), then we should just support that directly in the `try_from_type` API, even if just by making the `subclass` arg optional.

File: crates/ty_python_semantic/src/types/mro.rs [hunk 13]
```diff
@@ -327,69 +327,90 @@ impl<'db> Mro<'db> {
...
+        }
 
-            // Add each base's MRO.
-            for base in bases {
-                seqs.push(base.mro(db, None).collect());
+        // Build MRO sequences and check for inheritance cycles.
+        let mut seqs = vec![VecDeque::from([self_base])];
+        for base in &resolved_bases {
+            if base.has_cyclic_mro(db) {
+                return Err(DynamicMroErrorKind::InheritanceCycle.into_error(db, dynamic));
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/mro.rs:378]: Do we have any test exercising this case? It might require a static class with cyclic MRO and then a dynamic class inheriting it?

File: crates/ty_python_semantic/src/types/infer/builder.rs [hunk 14]
```diff
@@ -6434,6 +6412,12 @@ impl<'db, 'ast> TypeInferenceBuilder<'db, 'ast> {
             self.infer_newtype_assignment_deferred(arguments);
             return;
         }
+        if let Some(KnownClass::Type) = known_class
+            && let InferenceRegion::Deferred(definition) = self.region
+        {
+            self.infer_builtins_type_deferred(definition, value);
+            return;
+        }
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/infer/builder.rs]: Seems like these two cases should just be a match?

File: crates/ty_python_semantic/src/types/infer/builder.rs [hunk 15]
```diff
@@ -6601,7 +6823,19 @@ impl<'db, 'ast> TypeInferenceBuilder<'db, 'ast> {
         };
 
         let name_type = self.infer_expression(name_arg, TypeContext::default());
-        let bases_type = self.infer_expression(bases_arg, TypeContext::default());
+
+        // For assigned `type()` calls, bases inference is deferred to handle forward references
+        // and recursive references (e.g., `X = type("X", (tuple["X | None"],), {})`).
+        // This avoids expensive Salsa fixpoint iteration by deferring inference until the
+        // class type is already bound.
+        let bases_type = if definition.is_some() {
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/infer/builder.rs]: It seems like the only use of `bases_type` variable is in one place, 20 lines later, where we set `explicit_bases`. Why not bring those two things together in the code? Do we even need `bases_type` as a variable?

File: crates/ty_python_semantic/src/types/infer/builder.rs [hunk 16]
```diff
@@ -7522,226 +7744,180 @@ impl<'db, 'ast> TypeInferenceBuilder<'db, 'ast> {
...
+            let Some(class_base) = ClassBase::try_from_type(db, *base, placeholder_class) else {
+                // Can't convert; will be handled by `InvalidBases` error from `try_mro`.
+                continue;
+            };
 
-                                    return class_base;
-                                }
-                                ClassBase::Dynamic(_) => return class_base,
+            // Check for special bases that are not allowed for dynamic classes.
+            // Dynamic classes can't be generic, protocols, TypedDicts, or enums.
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/infer/builder.rs:8719]: Does `NamedTuple` also belong in this list?

File: crates/ty_python_semantic/src/types/class.rs
Comment (carljm) [inline crates/ty_python_semantic/src/types/class.rs]: I think this entire match arm is dead code? With the way calls to `KnownClass::Type` are handled now in `TypeInferenceBuilder`, I don't see any path where this could be reached -- we never enter normal call inference for these calls anymore. And replacing this arm with `unreachable!()` doesn't cause any test failures. So I think we should do that.

File: crates/ty_python_semantic/src/types.rs [hunk 17]
```diff
@@ -1143,6 +1142,15 @@ impl<'db> Type<'db> {
             .and_then(|instance| instance.own_tuple_spec(db))
     }
 
+    /// If this type is a fixed-length tuple instance, returns a boxed slice of its element types.
+    ///
+    /// Returns `None` if this is not a tuple instance, or if it's a variable-length tuple.
+    fn fixed_tuple_elements(&self, db: &'db dyn Db) -> Option<Box<[Type<'db>]>> {
```
Comment (carljm) [inline crates/ty_python_semantic/src/types.rs]: Do we have to allocate a new Box on every call to this method, or can we return a slice instead? Seems like a bit of a perf footgun to leave laying around.

File: crates/ty_python_semantic/src/types/class.rs
Comment (carljm) [inline crates/ty_python_semantic/src/types/class.rs]: This field no longer exists.

File: crates/ty_python_semantic/src/types/class.rs [hunk 18]
```diff
@@ -5094,6 +5165,20 @@ impl<'db> DynamicClassLiteral<'db> {
             return Ok(SubclassOfType::subclass_of_unknown());
         }
 
+        // Convert Types to ClassBases for metaclass computation.
+        let placeholder_class: ClassLiteral<'db> =
+            KnownClass::Object.try_to_class_literal(db).unwrap().into();
+
+        let bases: Vec<ClassBase<'db>> = original_bases
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/class.rs:5258]: Worth a comment here that we can silently drop invalid bases because they will be reported elsewhere (but actually say where)?

**Review by carljm — APPROVED** [review]
Looks good, thank you! Just nits.

File: crates/ty_python_semantic/src/types/infer/builder.rs (hunk 16 above)
Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/infer/builder.rs:8719]: This code was actually just moved (from above) so I'll make a note to look into it separately.

Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/infer/builder.rs:8719]: Actually did end up supporting this.

File: crates/ty_python_semantic/src/types/class.rs
Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/class.rs]: Removing this caused a panic, looking into it...
