### PR TITLE
[`refurb`] Make the fix for `FURB163` unsafe for `log2`, `log10`, `*args`, and deleted comments

### LINKED ISSUE #18639: FURB163 fix should be unsafe when it changes behavior or deletes comments
### Summary

The fix for [`redundant-log-base` (FURB163)](https://docs.astral.sh/ruff/rules/redundant-log-base/) should be marked unsafe when it switches the function to `log2` or `log10`, because that can change behavior. It can also change behavior when the first argument is starred. It should also be marked unsafe when it deletes comments.

Floating-point vagaries:
```console
$ cat >furb163_1.py <<'# EOF'
import math
print(math.log(4.13e223, 2))
print(math.log(4.14e223, 10))
# EOF

$ python furb163_1.py
742.8361069415266
223.61700034112087

$ ruff --isolated check furb163_1.py --select FURB163 --fix
Found 2 errors (2 fixed, 0 remaining).

$ python furb163_1.py
742.8361069415265
223.6170003411209
```

Starred arguments:
```console
$ cat >furb163_2.py <<'# EOF'
import math
def print_log(*args):
    try:
        print(math.log(*args, math.e))
    except TypeError as e:
        print(repr(e))
print_log()
print_log(100, 10)
# EOF

$ python furb163_2.py
1.0
TypeError('log expected at most 2 arguments, got 3')

$ ruff --isolated check furb163_2.py --select FURB163 --fix
Found 1 error (1 fixed, 0 remaining).

$ python furb163_2.py
TypeError('log expected at least 1 argument, got 0')
2.0
```

Deleted comments:
```console
$ cat >furb163_3.py <<'# EOF'
import math
print(math.log(
    3,  # This is the argument...
    math.e,  # ... and this is the base.
))
# EOF

$ ruff --isolated check furb163_3.py --select FURB163 --fix
Found 1 error (1 fixed, 0 remaining).

$ cat furb163_3.py
import math
print(math.log(3))
```

### Version

ruff 0.11.13 (5faf72a4d 2025-06-05)

### PR DESCRIPTION
**Pull request by chirizxc**
## Summary
/closes #18639

## Test Plan
update snapshots

### CODE REVIEW

**Comment by chirizxc** [comment]
do we have to update doc as well? because examples from the [ussie](https://github.com/astral-sh/ruff/issues/18639#issue-3138599071) and the doc are different

i mean 
изображение
изображение

**Comment by chirizxc** [comment]
although it should only work for float

File: crates/ruff_linter/src/rules/refurb/rules/redundant_log_base.rs [hunk 1]
```diff
@@ -136,6 +136,10 @@ fn is_number_literal(expr: &Expr, value: i8) -> bool {
     false
 }
 
+fn is_float(expr: &Expr) -> bool {
```
Comment (chirizxc) [inline crates/ruff_linter/src/rules/refurb/rules/redundant_log_base.rs]: i'm not sure, but maybe such a `is_float` already exists somewhere in the helper or something like that

**Comment by chirizxc** [comment]
there's also a question about [ruff_python_ast/src/generated.rs](https://github.com/astral-sh/ruff/blob/main/crates/ruff_python_ast/src/generated.rs) file
изображение

rustrover writes that `crate::` is not needed in 834 places, should the `crates/ruff_python_ast/generate.py` itself be corrected?

File: crates/ruff_linter/src/rules/refurb/rules/redundant_log_base.rs (hunk 1 above)
Comment (ntBre) [reply crates/ruff_linter/src/rules/refurb/rules/redundant_log_base.rs]: There's this:

https://github.com/astral-sh/ruff/blob/4cfaa39412ab33825c834f7da4bca3f96e550ba1/crates/ruff_python_semantic/src/analyze/typing.rs#L981-L984

which would work on a `Binding` if you wanted to resolve variables too, but do we need to check if the argument is a float? You can see the same floating point behavior with less exotic arguments:

```pycon
>>> math.log2(10)
3.321928094887362
>>> math.log(10, 2)
3.3219280948873626
```

and I think we're already checking for number literals.

File: crates/ruff_linter/src/rules/refurb/rules/redundant_log_base.rs [hunk 2]
```diff
@@ -135,15 +136,29 @@ fn is_number_literal(expr: &Expr, value: i8) -> bool {
...
     )?;
+
     let number = checker.locator().slice(arg);
-    Ok(Fix::safe_edits(
+
+    Ok(Fix::applicable_edits(
         Edit::range_replacement(format!("{binding}({number})"), call.range()),
         [edit],
+        if (matches!(base, Base::Two | Base::Ten) && is_float(arg))
+            || matches!(arg, Expr::Starred(_))
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/redundant_log_base.rs]: nit: I think you can use `arg.is_starred_expr` here.

**Comment by ntBre** [comment]
> there's also a question about [ruff_python_ast/src/generated.rs](https://github.com/astral-sh/ruff/blob/main/crates/ruff_python_ast/src/generated.rs) file изображение
> 
> rustrover writes that `crate::` is not needed in 834 places, should the `crates/ruff_python_ast/generate.py` itself be corrected?

This is interesting, I guess clippy doesn't warn about this. We could probably open a separate issue or PR for this, if you wanted!

File: crates/ruff_linter/src/rules/refurb/rules/redundant_log_base.rs [hunk 3]
```diff
@@ -37,6 +37,15 @@ use crate::{Edit, Fix, FixAvailability, Violation};
 /// math.log10(4)
 /// ```
 ///
+/// ## Fix safety
+/// This rule's fix is marked as unsafe when the argument is a starred expression
+/// or if there are comments within the function call range,
+/// as either can affect semantics or readability.
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/redundant_log_base.rs]: I think I would treat these two cases separately. My understanding is that the fix is unsafe when comments are in the replacement range because they will be deleted, which seems a bit separate from either semantics or readability.

And I don't think the `*args` case has any effect on readability, it "just" changes the semantics of the code by raising an error when a different number of arguments are passed.

Comment (chirizxc) [reply crates/ruff_linter/src/rules/refurb/rules/redundant_log_base.rs]: if write it like this, i think it would make more sense:

This fix is marked unsafe when the argument is a starred expression, as this changes the call semantics and may raise runtime errors. It is also unsafe if comments are present within the call, as they will be removed. Additionally, `math.log(x, base)` and `math.log2(x)` / `math.log10(x)` may differ due to floating-point rounding.

File: crates/ruff_linter/src/rules/refurb/rules/redundant_log_base.rs [hunk 4]
```diff
@@ -38,13 +38,10 @@ use crate::{Edit, Fix, FixAvailability, Violation};
...
-/// or if there are comments within the function call range,
-/// as either can affect semantics or readability.
-///
-/// Additionally, for base 2 or 10, `math.log(x, base)` and `math.log2(x)` /
-/// `math.log10(x)` are not strictly equivalent for floating-point values
-/// due to rounding differences. Use caution when applying fixes in numerical code.
+/// This fix is marked unsafe when the argument is a starred expression, as this changes
+/// the call semantics and may raise runtime errors. It is also unsafe if comments are
+/// present within the call, as they will be removed. Additionally, `math.log(x, base)`
+/// and `math.log2(x)` / `math.log10(x)` may differ due to floating-point rounding.
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/redundant_log_base.rs]:
```suggestion
/// and `math.log2(x)` / `math.log10(x)` may differ due to floating-point rounding, so 
/// the fix is also unsafe when making this transformation.
```

**Review by ntBre — APPROVED** [review]
Thanks!
