### PR TITLE
[ty] Increase worker-thread stack size

### LINKED ISSUE #17472: [ty] stack overflow checking 'sympy'
Repro:

```
➜ uvx --from "git+https://github.com/astral-sh/mypy_primer.git@add-red-knot-support-v2" mypy_primer \
    --type-checker knot \
    --old origin/main \
    --new origin/main \
    --debug \
    --project-selector '/sympy$' \
    --output full \
    --debug
git fetch	 in /tmp/mypy_primer/new_knot/src/ruff
git fetch	 in /tmp/mypy_primer/old_knot/src/ruff
git clean -ffxd	 in /tmp/mypy_primer/old_knot/src/ruff
git clean -ffxd	 in /tmp/mypy_primer/new_knot/src/ruff
git reset --hard origin/HEAD --recurse-submodules	 in /tmp/mypy_primer/old_knot/src/ruff
git reset --hard origin/HEAD --recurse-submodules	 in /tmp/mypy_primer/new_knot/src/ruff
git checkout --force --recurse-submodules origin/HEAD	 in /tmp/mypy_primer/old_knot/src/ruff
git checkout --force --recurse-submodules origin/HEAD	 in /tmp/mypy_primer/new_knot/src/ruff
git branch -D origin/main	 in /tmp/mypy_primer/old_knot/src/ruff
git branch -D origin/main	 in /tmp/mypy_primer/new_knot/src/ruff
git checkout --force --recurse-submodules origin/main	 in /tmp/mypy_primer/new_knot/src/ruff
git checkout --force --recurse-submodules origin/main	 in /tmp/mypy_primer/old_knot/src/ruff
cargo build --bin red_knot	 in /tmp/mypy_primer/new_knot/src/ruff
cargo build --bin red_knot	 in /tmp/mypy_primer/old_knot/src/ruff
/tmp/mypy_primer/new_knot/target/debug/red_knot version
/tmp/mypy_primer/old_knot/target/debug/red_knot version
new knot version: red knot 0.0.0+3053 (454ad15ae 2025-04-18)
old knot version: red knot 0.0.0+3053 (454ad15ae 2025-04-18)
git fetch	 in /tmp/mypy_primer/projects/sympy
git clean -ffxd	 in /tmp/mypy_primer/projects/sympy
git reset --hard origin/HEAD --recurse-submodules	 in /tmp/mypy_primer/projects/sympy
uv venv /tmp/mypy_primer/projects/_sympy_venv --python /Users/carlmeyer/Library/Caches/uv/archive-v0/q5jKL-T0kbdtFcrS4Nuqv/bin/python --seed
/tmp/mypy_primer/new_knot/target/debug/red_knot check --python /tmp/mypy_primer/projects/_sympy_venv --python-version 3.13 --output-format concise	 in /tmp/mypy_primer/projects/sympy
/tmp/mypy_primer/old_knot/target/debug/red_knot check --python /tmp/mypy_primer/projects/_sympy_venv --python-version 3.13 --output-format concise	 in /tmp/mypy_primer/projects/sympy
/tmp/mypy_primer/new_knot/target/debug/red_knot on sympy took 0.54s
/tmp/mypy_primer/old_knot/target/debug/red_knot on sympy took 2.93s

sympy
https://github.com/sympy/sympy
----------

old
> /tmp/mypy_primer/old_knot/target/debug/red_knot check --python /tmp/mypy_primer/projects/_sympy_venv --python-version 3.13 --output-format concise (2.9s)

	thread '<unknown>' has overflowed its stack
	fatal runtime error: stack overflow
----------

new
> /tmp/mypy_primer/new_knot/target/debug/red_knot check --python /tmp/mypy_primer/projects/_sympy_venv --python-version 3.13 --output-format concise (0.5s)

	thread '<unknown>' has overflowed its stack
	fatal runtime error: stack overflow
==========
```

### PR DESCRIPTION
**Pull request by sharkdp**
## Summary

closes #17472 

This is obviously just a band-aid solution to this problem (in that you can always make your [pathological inputs](https://github.com/sympy/sympy/blob/28994edd82a18c22a98a52245c173f3c836dcad3/sympy/polys/numberfields/resolvent_lookup.py) bigger and it will still crash), but I think this is not an unreasonable change — even if we add more sophisticated solutions later. I tried using `stacker` as suggested by @MichaReiser, and it works. But it's unclear where exactly would be the right place to put it, and even for the `sympy` problem, we would need to add it both in the semantic index builder AST traversal and in type inference. Increasing the default stack size for worker threads, as proposed here, doesn't solve the underlying problem (that there is a hard limit), but it is more universal in the sense that it is not specific to large binary-operator expression chains.

To determine a reasonable stack size, I created files that look like

*right associative*:
```py
from typing import reveal_type
total = (1 + (1 + (1 + (1 + (… + 1)))))
reveal_type(total)
```

*left associative*
```py
from typing import reveal_type
total = 1 + 1 + 1 + 1 + … + 1
reveal_type(total)
```

with a variable amount of operands (`N`). I then chose the stack size large enough to still be able to handle cases that existing type checkers can not:

```
right

  N = 20: mypy takes ~ 1min
  N = 350: pyright crashes with a stack overflow (mypy fails with "too many nested parentheses")
  N = 800: ty(main) infers Literal[800] instantly
  N = 1000: ty(main) crashes with "thread '<unknown>' has overflowed its stack"

  N = 7000: ty(this branch) infers Literal[7000] instantly
  N = 8000+: ty(this branch) crashes


left

  N = 300: pyright emits "Maximum parse depth exceeded; break expression into smaller sub-expressions"
           total is inferred as Unknown
  N = 5500: mypy crashes with "INTERNAL ERROR"
  N = 2500: ty(main) infers Literal[2500] instantly
  N = 3000: ty(main) crashes with "thread '<unknown>' has overflowed its stack"

  N = 22000: ty(this branch) infers Literal[22000] instantly
  N = 23000+: ty(this branch) crashes
```

## Test Plan

New regression test.

### CODE REVIEW

File: crates/ty/src/main.rs [hunk 1]
```diff
@@ -401,6 +401,12 @@ fn set_colored_override(color: Option<TerminalColor>) {
 fn setup_rayon() {
     ThreadPoolBuilder::default()
         .num_threads(max_parallelism().get())
+        // Use a reasonably large stack size to avoid running into stack overflows too easily. The
+        // size was chosen in such a way as to still be able to handle large expressions involving
+        // binary operators (x + x + … + x) both during the AST walk in semantic index building as
+        // well as during type checking. Using this stack size, we can handle handle expressions
+        // that are several times larger than the corresponding limits in existing type checkers.
+        .stack_size(16 * 1024 * 1024)
```
Comment (sharkdp) [inline crates/ty/src/main.rs:409]: It's probably worth noting that this does not generally increase memory usage by 16 MiB × num_threads. It's just the max. available stack space that a single thread can use.

Comment (carljm) [reply crates/ty/src/main.rs:409]: And 16MiB/thread is not even detectable, relative to the memory we need for source texts and AST, for any project large enough to care about memory usage.

**Review by carljm — APPROVED** [review]
This looks great, thank you

File: crates/ty/tests/cli.rs [hunk 2]
```diff
@@ -1195,6 +1196,42 @@ fn concise_revealed_type() -> anyhow::Result<()> {
...
+fn can_handle_large_binop_expressions() -> anyhow::Result<()> {
+    let mut content = String::new();
+    writeln!(
+        &mut content,
+        "
+        from typing_extensions import reveal_type
+        total = 1{plus_one_repeated}
+        reveal_type(total)
+        ",
+        plus_one_repeated = " + 1".repeat(2000 - 1)
```
Comment (sharkdp) [inline crates/ty/tests/cli.rs:1209]: I chose a *much* smaller limit than what we can handle (but still bigger than what we can handle on `main`) for two reasons:

* Debug builds take up more stack space and crash at smaller input sizes
* We don't want minor increases of stack frame sizes to lead to a test failure here.

**Comment by MichaReiser** [comment]
I think the long term solution here would be to implement binary expression traversal in a loop rather than with recursion. But this is fine for now
