### PR TITLE
Recognize all symbols named `TYPE_CHECKING` for `in_type_checking_block`

### LINKED ISSUE #15681: TC003/TC002/TC001 False positive on manual `TYPE_CHECKING` with `__future__.annotations`
### Description

If you manually set `TYPE_CHECKING` to `False` and use it with `__future__.annotations`, ruff will raise TC003/TC002/TC001 falsepositives on the imports in your `TYPE_CHECKING` block as it seems to only check for `typing.TYPE_CHECKING`.

Command: `ruff check test.py --isolated --fix --select TC`
Version: `0.9.2`
Keywords: "TYPE_CHECKING", "TC003", "__future__.annotations", "TC002", "TC001"

# Sample Code
`test.py`
```py
from __future__ import annotations

TYPE_CHECKING = False
if TYPE_CHECKING:
    from types import TracebackType

def foo(tb: TracebackType):...
```
```sh
$ ruff check test.py --isolated --fix --select TC
test.py:5:23: TC003 Move standard library import `types.TracebackType` into a type-checking block
  |
3 | TYPE_CHECKING = False
4 | if TYPE_CHECKING:
5 |     from types import TracebackType
  |                       ^^^^^^^^^^^^^ TC003
6 |
7 | def foo(tb: TracebackType):...
  |
  = help: Move into type-checking block

Found 1 error.
```

### PR DESCRIPTION
**Pull request by Daverball**
Closes #15681

## Summary

This changes `analyze::typing::is_type_checking_block` to recognize all symbols named "TYPE_CHECKING".
This matches the current behavior of mypy and pyright as well as `flake8-type-checking`.

It also drops support for detecting `if False:` and `if 0:` as type checking blocks. This used to be an option for
providing backwards compatibility with Python versions that did not have a `typing` module, but has since
been removed from the typing spec and is no longer supported by any of the mainstream type checkers.

## Test Plan

`cargo nextest run`

### CODE REVIEW

**Comment by Daverball** [comment]
Not sure if red knot reuses this check or needs its own changes, in order to work.

I will add more test cases, since I'm worried some of the TC fixes will not be able to deal with these new kinds of type checking blocks without additional changes.

**Comment by MichaReiser** [comment]
That was quick, thanks. I'm leaning towards making this a preview change because it's technically breaking.

**Comment by Daverball** [comment]
> I'm a little confused by the scikit ecosystem change. If anything I would've expected a previous TC003 error to disappear, not a new TC004 to appear, especially since there is no runtime use of `importlib.machinery` in that file...
> 
> So it seems like there's a different bug at play here, that was previously obscured by not recognizing the `TYPE_CHECKING` block in that file.

Looks like references to bindings don't really try to find their matching import beyond the first level, so since there are multiple `importlib` bindings, the references to `importlib.abc` and `importlib.util` will bind to the most recent `importlib` import, which happens to be `importlib.machinery` in the type checking block.

So it looks like `TC001-004` will need to do something more sophisticated than simply looking at import bindings and their references, when that import binding came from a dotted import and it's shadowing another import. I will open a separate issue for this problem.

**Comment by Daverball** [comment]
@MichaReiser I wonder if it would be alright to copy the preview flag to the `SemanticModel`. `in_type_checking_block` is used in quite a few places, so adding a new argument for the preview behavior only to remove it again later when we stabilize this, would end up introducing quite a bit of churn. Adding the flag to the `SemanticModel` would be a much smaller change and I would've found it quite useful in the past, just like `checker.source_type` is duplicated into a semantic flag for stub files.

I will also need to make some structural changes to `Importer::typing_import_edit` so it can still emit a fix for these new type checking blocks, since it currently always assumes it will need an import of `TYPE_CHECKING` from one of the typing modules, but we know for sure it will not need that if we have a preceding type checking block. If we want to gate this change behind a preview flag as well, that would be another place where having the preview flag on the `SemanticModel` would be useful.

File: crates/ruff_linter/src/importer/mod.rs [hunk 1]
```diff
@@ -135,71 +135,76 @@ impl<'a> Importer<'a> {
...
+                    //
+                    // Const: Final[dict] = {}
+                    // ```
+                    let edit = if type_checking.statement(semantic) == import.statement {
+                        None
+                    } else {
+                        Some(Edit::range_replacement(
+                            self.locator.slice(type_checking.range()).to_string(),
+                            type_checking.range(),
+                        ))
```
Comment (Daverball) [inline crates/ruff_linter/src/importer/mod.rs:170]: By restructuring the logic, this no-op edit would now only happen if we don't have an existing type checking block. I'm not sure whether this is problematic or why we're adding a no-op edit anyways (maybe to ensure no other edit is allowed to remove the import?).

If this no-op edit indeed accomplishes something useful, we may need a more sophisticated change, which allows `find_type_checking` to return a name based on an assignment target in addition to an import. This would allow us to write separate fix logic for when it's imported and when it's defined in the same file.

File: crates/ruff_python_semantic/src/analyze/typing.rs [hunk 2]
```diff
@@ -328,28 +328,31 @@ pub fn is_mutable_expr(expr: &Expr, semantic: &SemanticModel) -> bool {
...
+        // As long as the symbol's name is "TYPE_CHECKING" we will treat it like `typing.TYPE_CHECKING`
+        // for this specific check even if it's defined somewhere else, like the current module.
+        // Ex) `if TYPE_CHECKING:`
+        Expr::Name(ast::ExprName { id, .. }) => {
+            id.as_str() == "TYPE_CHECKING"
+            // Ex) `if TC:` with `from typing import TYPE_CHECKING as TC`
+            || semantic.match_typing_expr(test, "TYPE_CHECKING")
+        }
+        // Ex) `if typing.TYPE_CHECKING:`
+        Expr::Attribute(ast::ExprAttribute { attr, .. }) => attr.as_str() == "TYPE_CHECKING",
```
Comment (MichaReiser) [inline crates/ruff_python_semantic/src/analyze/typing.rs:353]: Nit:
```suggestion
            id == "TYPE_CHECKING"
            // Ex) `if TC:` with `from typing import TYPE_CHECKING as TC`
            || semantic.match_typing_expr(test, "TYPE_CHECKING")
        }
        // Ex) `if typing.TYPE_CHECKING:`
        Expr::Attribute(ast::ExprAttribute { attr, .. }) => attr == "TYPE_CHECKING",
```

File: crates/ruff_linter/src/importer/mod.rs [hunk 3]
```diff
@@ -135,7 +135,20 @@ impl<'a> Importer<'a> {
...
+                type_checking_edit: None,
+                add_import_edit: self.add_to_type_checking_block(&content, block.start()),
+            });
+        }
+
         // Import the `TYPE_CHECKING` symbol from the typing module.
+        // TODO: Should we provide an option to avoid this import?
+        //       E.g. either through an explicit setting, or implicitly
+        //       when `typing` isn't part of the exempt modules and there
+        //       are no other existing runtime imports of `typing`.
```
Comment (MichaReiser) [inline crates/ruff_linter/src/importer/mod.rs:151]: Hmm, yeah this is interesting. Not having an option seems fine to me for now, we can introduce one later if it is being asked for.

**Review by MichaReiser — APPROVED** [review]
This looks great. However, this is a somewhat significant change. I think i'd feel better if we gate this behind the preview mode and release it as part of 0.10.

**Comment by Daverball** [comment]
> This looks great. However, this is a somewhat significant change. I think i'd feel better if we gate this behind the preview mode and release it as part of 0.10.

The only problematic part of that is adding a preview flag check will add quite the rat tail to the diff, since the function is used in so many places. One way to get around this would be to add the preview flag to the semantic model. Which I would've found useful in the past anyways. (Either as a `SemanticModelFlag` or its own thing)

**Comment by MichaReiser** [comment]
Ah right, sorry. I forgot about our previous conversation while I was on PTO. Let me have a quick look

**Comment by MichaReiser** [comment]
Adding a preview option to `SemanticModel` or to `SemanticModelFlag` sounds reasonable to me. The alternative is to add a flag specific for this feature to `SemanticModelFlag`. The advantage of a feature-specific flag is that it's easier to promote all changes because we can simply remove the flag and then fix all compile errors.

**Comment by Daverball** [comment]
@MichaReiser Since we're now gating the change I also removed special casing for `if False:` and `if 0:` in preview mode.
I think support for this compatibility shim has been dropped 4+ years ago.

File: crates/ruff_python_semantic/src/analyze/typing.rs [hunk 4]
```diff
@@ -382,6 +382,22 @@ pub fn is_mutable_expr(expr: &Expr, semantic: &SemanticModel) -> bool {
 pub fn is_type_checking_block(stmt: &ast::StmtIf, semantic: &SemanticModel) -> bool {
     let ast::StmtIf { test, .. } = stmt;
 
+    if semantic.use_new_type_checking_block_detection_semantics() {
```
Comment (MichaReiser) [inline crates/ruff_python_semantic/src/analyze/typing.rs:385]: I think this version is now slightly different to what you had before as it removes support for `if False:` and `if 0:`.

File: crates/ruff_linter/src/importer/mod.rs [hunk 5]
```diff
@@ -135,6 +135,17 @@ impl<'a> Importer<'a> {
             self.stylist,
         )?;
 
+        if semantic.use_new_type_checking_block_detection_semantics() {
```
Comment (MichaReiser) [inline crates/ruff_linter/src/importer/mod.rs:138]: Do we need to cate this behind preview? I understood that this was mainly a refactor that moved the `preceding_type_checking_block` to the top to avoid unnecessarily going through the `Import the TYPE_CHECKING symbol` when it isn't necessary

**Comment by MichaReiser** [comment]
> @MichaReiser Since we're now gating the change I also removed special casing for `if False:` and `if 0:` in preview mode. I think support for this compatibility shim has been dropped 4+ years ago.

Sounds reasonable. Can you update your PR summary to reflect this change?

File: crates/ruff_linter/src/importer/mod.rs (hunk 5 above)
Comment (Daverball) [reply crates/ruff_linter/src/importer/mod.rs:138]: Look at my previous comment here: https://github.com/astral-sh/ruff/pull/15719#discussion_r1929786168

Refactoring has the side effect of never emitting a no-op fix. So I feel more safe doing it this way, until I know what the purpose of the no-op fix was.

File: crates/ruff_linter/src/importer/mod.rs (hunk 1 above)
Comment (Daverball) [reply crates/ruff_linter/src/importer/mod.rs]: The other thing that bothered me, is that this hack does not seem very reliable, since the type checking block we're moving the imports to might not correspond to the `typing`/`TYPE_CHECKING` import we find in the first step...

Maybe we revert it back to my earlier refactored version, but when we have an existing type checking block we lookup the relevant statement from the binding and emit a no-op edit for that specific statement if it doesn't overlap with one of the import edits. That seems a lot more robust to me.

Comment (Daverball) [reply crates/ruff_linter/src/importer/mod.rs]: I had another little think about this. I don't think we have to worry about the no-op edit when we find a preceding type checking block. If another edit would remove the binding we're referencing, it would necessarily also have to remove the type checking block itself (otherwise there would still be a reference to the binding), but then the edit that removes the type checking block would overlap with our edit to add new import to it, so we don't need to artificially create another overlap.

In the case where there isn't a type checking block, but there is a unused `TYPE_CHECKING` import, it makes sense, since we don't want to let F401 remove the import when our edit adds a new reference to it.

Comment (charliermarsh) [reply crates/ruff_linter/src/importer/mod.rs]: Yeah, I believe this is to prevent things like:

```python
from typing import TYPE_CHECKING

from foo import Bar

def func() -> Bar: ...
```

If we don't add the no-op edit, `TYPE_CHECKING` might be removed, leaving us with:

```python
if TYPE_CHECKING:
  from foo import Bar

def func() -> "Bar": ...
```

File: crates/ruff_linter/src/importer/mod.rs [hunk 6]
```diff
@@ -135,6 +135,39 @@ impl<'a> Importer<'a> {
...
+                        None
+                    } else {
+                        Some(Edit::range_replacement(
+                            self.locator.slice(statement.range()).to_string(),
+                            statement.range(),
+                        ))
+                    }
+                } else {
+                    None
+                };
```
Comment (Daverball) [inline crates/ruff_linter/src/importer/mod.rs:164]: This should retain the no-op edit in the most common case (the top-most `TYPE_CHECKING` block is defined in global scope). Although this brought up a question about the implementation of `Importer`:

Why are we adding both the if statement and the body AST node in global scope but only the body AST node to `type_checking_blocks`? I don't really see an obvious reason. Shouldn't we just always pass the body or always the entire if statement? Or at least either one or the other, but never both. Either way it is pretty confusing and it would seem more consistent to pass in something like a struct that contains the condition, the body and the scope. That would also make it flexible enough to support a non-idiomatic `if not TYPE_CHECKING` with an `else` clause.

**Review by MichaReiser — APPROVED** [review]
This is great. Thank you. Also thanks for reviewing the ecosytem checks so carefully.
