### PR TITLE
[`refurb`] Mark `int` and `bool` cases for `Decimal.from_float` as safe fixes in `FURB164` tests

### LINKED ISSUE #19460: FURB164 fix has two problems related to `Decimal.from_float`
### Summary

The fix for [unnecessary-from-float (FURB164)](https://docs.astral.sh/ruff/rules/unnecessary-from-float/) has two problems related to `Decimal.from_float`.

Fixing `Decimal.from_float` should be marked unsafe by default because `FloatOperation` could be trapped. It should only be marked safe when the argument to `Decimal.from_float` is known to be an `int` or `bool`, which never raise a signal. [Example](https://play.ruff.rs/fef2743d-cbf8-4960-8174-aca6c283ce65):
```console
$ cat >furb164_1.py <<'# EOF'
from decimal import Decimal, FloatOperation, getcontext
getcontext().traps[FloatOperation] = True
print(Decimal.from_float(0.1))
# EOF

$ python furb164_1.py
0.1000000000000000055511151231257827021181583404541015625

$ ruff --isolated check furb164_1.py --select FURB164 --preview --fix
Found 1 error (1 fixed, 0 remaining).

$ cat furb164_1.py
from decimal import Decimal, FloatOperation, getcontext
getcontext().traps[FloatOperation] = True
print(Decimal(0.1))

$ python furb164_1.py 2>&1 | tail -n 1
decimal.FloatOperation: [<class 'decimal.FloatOperation'>]
```

When the argument to `Decimal.from_float` is negative NaN, the fix should replace it with positive NaN to preserve the program’s behavior. [Example](https://play.ruff.rs/9ac93a35-6395-4766-be06-26af9938879d):
```console
$ cat >furb164_2.py <<'# EOF'
from decimal import Decimal
print(Decimal.from_float(float(" -Nan\n")))
# EOF

$ python furb164_2.py
NaN

$ ruff --isolated check furb164_2.py --select FURB164 --preview --fix
Found 1 error (1 fixed, 0 remaining).

$ cat furb164_2.py
from decimal import Decimal
print(Decimal(" -Nan\n"))
# EOF

$ python furb164_2.py
-NaN
```

### Version

ruff 0.12.4 (ee2759b36 2025-07-17)

### PR DESCRIPTION
**Pull request by danparizher**
## Summary

Fixes #19460

### CODE REVIEW

File: crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs [hunk 1]
```diff
@@ -288,7 +288,22 @@ fn handle_non_finite_float_special_case(
...
+            while i < nan_idx {
+                if chars[i] == '-' {
+                    chars.remove(i);
+                    continue;
+                }
+                i += 1;
+            }
+            replacement_arg = chars.into_iter().collect();
+        }
+    }
```
Comment (dscorbett) [inline crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs]: Does this work for `float("\x2dnan")` or `float("\N{HYPHEN-MINUS}nan")`? Cf. #16771.

Comment (danparizher) [reply crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs]: Yes, it covers both of those cases

File: crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs [hunk 2]
```diff
@@ -180,18 +180,18 @@ fn is_valid_argument_type(
                     typing::is_float(binding, semantic),
                 )
             })
-            .unwrap_or_default()
+            .unwrap_or((false, false))
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs:183]: I think this should be equivalent, but it's probably more readable, even though I think I suggested the old version 😆

File: crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs (hunk 1 above)
Comment (ntBre) [reply crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs]: Could we add tests for those cases? I also think we could use the return value of `as_non_finite_float_string_literal` just above this instead of doing some of the manual manipulation ourselves. That should normalize the result so that we can just compare against "-nan" directly.

File: crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs [hunk 3]
```diff
@@ -180,18 +180,18 @@ fn is_valid_argument_type(
...
     } else {
         (false, false)
     };
 
     match (method_name, constructor) {
-        // Decimal.from_float accepts int, bool, float
+        // Decimal.from_float: Only int or bool are safe (float is unsafe due to FloatOperation trap)
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs:189]: We might want to update the name of this function and also the comment where it's called. `is_valid` made me think we would bail out without a diagnostic or without a fix if the result is invalid, but it's really just checking the fix safety.

File: crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs [hunk 4]
```diff
@@ -286,24 +286,8 @@ fn handle_non_finite_float_special_case(
...
-                    continue;
-                }
-                i += 1;
-            }
-            replacement_arg = chars.into_iter().collect();
-        }
-    }
+    let normalized = as_non_finite_float_string_literal(float_arg)?;
+    let replacement_arg = format!("\"{normalized}\"");
     let replacement_text = format!("{constructor_name}({replacement_arg})");
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs]:
```suggestion
    let replacement_text = format!(r#"{constructor_name}("{normalized}")"#);
```

I'm not sure GitHub is showing the suggestion properly because one of the lines wasn't changed, but I think we can inline the quote addition and avoid two `format!` calls. We can also use a raw string to avoid needing to escape the quotes.
