### PR TITLE
Ignore directories when collecting files to lint

### LINKED ISSUE #5739: Ruff fails when a directory ends with .py
Ruff gets confused when a directory is named like a python file (ends with `.py`):

```shell
$ mkdir repro
$ mkdir repro/some_folder.py
$ cargo run --bin ruff -- --no-cache repro
error: Failed to lint repro/some_folder.py: Is a directory (os error 21)
  Caused by: Is a directory (os error 21)
repro/some_folder.py:1:1: E902 Is a directory (os error 21)
  Caused by: Is a directory (os error 21)
Found 1 error.
```

### PR DESCRIPTION
**Pull request by harupy**
## Summary

Fixes #5739

## Test Plan

Manually tested:

```sh
$ tree dir
dir
├── dir.py
│   └── file.py
└── file.py

1 directory, 2 files

$ cargo run -p ruff_cli -- check dir --no-cache
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/ruff check dir --no-cache`
dir/dir.py/file.py:1:7: F821 Undefined name `a`
dir/file.py:1:7: F821 Undefined name `a`
Found 2 errors.
```

Is a unit test needed?

### CODE REVIEW

File: crates/ruff/src/resolver.rs [hunk 1]
```diff
@@ -329,10 +329,14 @@ pub fn python_files_in_path(
                 }
             }
 
-            if result.as_ref().map_or(true, |entry| {
+            let should_include = result.as_ref().map_or(true, |entry| {
```
Comment (harupy) [inline crates/ruff/src/resolver.rs:332]: Used a variable to avoid https://github.com/astral-sh/ruff/actions/runs/5561952462/jobs/10159951956

**Comment by zanieb** [comment]
Thanks for contributing @harupy!

Do you think you could write a unit test for this?

File: crates/ruff/src/resolver.rs (hunk 1 above)
Comment (zanieb) [reply crates/ruff/src/resolver.rs:332]: I believe you can also avoid the clippy lint and retain the old pattern by not using `return` in your statement, see https://github.com/astral-sh/ruff/commit/c9b305e9cadbcc9af465643ba84ce13b460fc48d

Comment (harupy) [reply crates/ruff/src/resolver.rs]: @zanieb Thanks! Updated

**Comment by charliermarsh** [comment]
Unfortunately we don’t have any unit tests for the file discovery behavior right now, so we’d need to establish some new patterns. 

We have some “manual” tests that are document expected behavior here: https://github.com/astral-sh/ruff/blob/main/crates/ruff/resources/test/project/README.md.

Alternatively we could add an integration test? Those can rely on the binary which would make the test itself easier to write (but the output harder to introspect).

I’m comfortable with any outcome including just doing some manual testing since it’s “no worse than before”.

**Comment by charliermarsh** [comment]
(The logic looks correct to me.)

**Comment by harupy** [comment]
@charliermarsh Thanks for the comment. I'm trying to write a unit test. My local diff looks like this:

```diff
diff --git a/Cargo.lock b/Cargo.lock
index f3ce5f85e..428d00996 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -1893,6 +1893,7 @@ dependencies = [
  "smallvec",
  "strum",
  "strum_macros",
+ "tempfile",
  "test-case",
  "thiserror",
  "toml",
diff --git a/crates/ruff/Cargo.toml b/crates/ruff/Cargo.toml
index b659730d8..8d22661c1 100644
--- a/crates/ruff/Cargo.toml
+++ b/crates/ruff/Cargo.toml
@@ -83,6 +83,7 @@ wsl = { version = "0.1.0" }
 [dev-dependencies]
 insta = { workspace = true }
 pretty_assertions = "1.3.0"
+tempfile = "3.6.0"
 test-case = { workspace = true }
 # Disable colored output in tests
 colored = { workspace = true, features = ["no-color"] }
diff --git a/crates/ruff/src/resolver.rs b/crates/ruff/src/resolver.rs
index ccbd7ecc3..3f3cc39c5 100644
--- a/crates/ruff/src/resolver.rs
+++ b/crates/ruff/src/resolver.rs
@@ -435,10 +435,12 @@ mod tests {
     use anyhow::Result;
     use globset::GlobSet;
     use path_absolutize::Absolutize;
+    use tempfile::TempDir;
+    use test_case::test_case;
 
     use crate::resolver::{
-        is_file_excluded, match_exclusion, resolve_settings_with_processor, NoOpProcessor,
-        PyprojectConfig, PyprojectDiscoveryStrategy, Relativity, Resolver,
+        is_file_excluded, match_exclusion, python_files_in_path, resolve_settings_with_processor,
+        NoOpProcessor, PyprojectConfig, PyprojectDiscoveryStrategy, Relativity, Resolver,
     };
     use crate::settings::pyproject::find_settings_toml;
     use crate::settings::types::FilePattern;
@@ -605,4 +607,37 @@ mod tests {
         ));
         Ok(())
     }
+
+    #[test_case("py")]
+    #[test_case("pyi")]
+    #[test_case("ipynb")]
+    fn python_files_in_path_excludes_directories_that_look_like_python_files(
+        ext: &str,
+    ) -> Result<()> {
+        let tmp_dir = TempDir::new().unwrap();
+        let tmp_dir = tmp_dir.path();
+        let file = tmp_dir.join(format!("file.{}", ext));
+        let dir = tmp_dir.join(format!("dir.{}", ext));
+        let another_dir = tmp_dir.join(format!("another_dir.{}", ext));
+        let another_file = dir.join(format!("another_file.{}", ext));
+        std::fs::create_dir(&dir).unwrap();
+        std::fs::create_dir(&another_dir).unwrap();
+        std::fs::File::create(&file).unwrap();
+        std::fs::File::create(&another_file).unwrap();
+        let files = python_files_in_path(
+            &[tmp_dir.to_path_buf()],
+            &PyprojectConfig::new(
+                PyprojectDiscoveryStrategy::Hierarchical,
+                Default::default(),
+                None,
+            ),
+            &NoOpProcessor,
+        )
+        .unwrap()
+        .0;
+        assert_eq!(files.len(), 2);
+        assert_eq!(files[0].as_ref().unwrap().path(), another_file);
+        assert_eq!(files[1].as_ref().unwrap().path(), file);
+        Ok(())
+    }
 }
```

**Comment by harupy** [comment]
@charliermarsh I manually ran the commands in https://github.com/astral-sh/ruff/blob/main/crates/ruff/resources/test/project/README.md. Here are the results.

```
> cargo run -p ruff_cli -- check crates/ruff/resources/test/project/
   Compiling ruff_python_semantic v0.0.0 (/home/haru/Desktop/repositories/ruff/crates/ruff_python_semantic)
   Compiling ruff_python_formatter v0.0.0 (/home/haru/Desktop/repositories/ruff/crates/ruff_python_formatter)
   Compiling ruff v0.0.278 (/home/haru/Desktop/repositories/ruff/crates/ruff)
   Compiling ruff_cli v0.0.278 (/home/haru/Desktop/repositories/ruff/crates/ruff_cli)
    Finished dev [unoptimized + debuginfo] target(s) in 11.34s
     Running `target/debug/ruff check crates/ruff/resources/test/project/`
warning: Detected debug build without --no-cache.
crates/ruff/resources/test/project/examples/.dotfiles/script.py:1:1: I001 [*] Import block is un-sorted or un-formatted
crates/ruff/resources/test/project/examples/.dotfiles/script.py:1:17: F401 [*] `numpy` imported but unused
crates/ruff/resources/test/project/examples/.dotfiles/script.py:2:17: F401 [*] `app.app_file` imported but unused
crates/ruff/resources/test/project/examples/docs/docs/file.py:1:1: I001 [*] Import block is un-sorted or un-formatted
crates/ruff/resources/test/project/examples/docs/docs/file.py:8:5: F841 [*] Local variable `x` is assigned to but never used
crates/ruff/resources/test/project/project/file.py:1:8: F401 [*] `os` imported but unused
crates/ruff/resources/test/project/project/import_file.py:1:1: I001 [*] Import block is un-sorted or un-formatted
Found 7 errors.
[*] 7 potentially fixable with the --fix option.

> (cd crates/ruff/resources/test/project/ && cargo run -p ruff_cli -- check .)
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `/home/haru/Desktop/repositories/ruff/target/debug/ruff check .`
warning: Detected debug build without --no-cache.
examples/.dotfiles/script.py:1:1: I001 [*] Import block is un-sorted or un-formatted
examples/.dotfiles/script.py:1:17: F401 [*] `numpy` imported but unused
examples/.dotfiles/script.py:2:17: F401 [*] `app.app_file` imported but unused
examples/docs/docs/file.py:1:1: I001 [*] Import block is un-sorted or un-formatted
examples/docs/docs/file.py:8:5: F841 [*] Local variable `x` is assigned to but never used
project/file.py:1:8: F401 [*] `os` imported but unused
project/import_file.py:1:1: I001 [*] Import block is un-sorted or un-formatted
Found 7 errors.
[*] 7 potentially fixable with the --fix option.

> (cd crates/ruff/resources/test/project/examples/docs && cargo run -p ruff_cli -- check .)
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `/home/haru/Desktop/repositories/ruff/target/debug/ruff check .`
warning: Detected debug build without --no-cache.
docs/file.py:1:1: I001 [*] Import block is un-sorted or un-formatted
docs/file.py:8:5: F841 [*] Local variable `x` is assigned to but never used
Found 2 errors.
[*] 2 potentially fixable with the --fix option.

> (cargo run -p ruff_cli -- check --config=crates/ruff/resources/test/project/pyproject.toml crates/ruff/resources/test/project/)
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/ruff check --config=crates/ruff/resources/test/project/pyproject.toml crates/ruff/resources/test/project/`
warning: Detected debug build without --no-cache.
crates/ruff/resources/test/project/examples/.dotfiles/script.py:1:17: F401 [*] `numpy` imported but unused
crates/ruff/resources/test/project/examples/.dotfiles/script.py:2:17: F401 [*] `app.app_file` imported but unused
crates/ruff/resources/test/project/examples/docs/docs/concepts/file.py:1:8: F401 [*] `os` imported but unused
crates/ruff/resources/test/project/examples/docs/docs/file.py:1:1: I001 [*] Import block is un-sorted or un-formatted
crates/ruff/resources/test/project/examples/docs/docs/file.py:1:8: F401 [*] `os` imported but unused
crates/ruff/resources/test/project/examples/docs/docs/file.py:3:17: F401 [*] `numpy` imported but unused
crates/ruff/resources/test/project/examples/docs/docs/file.py:4:27: F401 [*] `docs.concepts.file` imported but unused
crates/ruff/resources/test/project/examples/excluded/script.py:1:8: F401 [*] `os` imported but unused
crates/ruff/resources/test/project/project/file.py:1:8: F401 [*] `os` imported but unused
Found 9 errors.
[*] 9 potentially fixable with the --fix option.

> (cd crates/ruff/resources/test/project/examples && cargo run -p ruff_cli -- check --config=docs/ruff.toml .)
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `/home/haru/Desktop/repositories/ruff/target/debug/ruff check --config=docs/ruff.toml .`
warning: Detected debug build without --no-cache.
docs/docs/concepts/file.py:5:5: F841 [*] Local variable `x` is assigned to but never used
docs/docs/file.py:1:1: I001 [*] Import block is un-sorted or un-formatted
docs/docs/file.py:8:5: F841 [*] Local variable `x` is assigned to but never used
excluded/script.py:5:5: F841 [*] Local variable `x` is assigned to but never used
Found 4 errors.
[*] 4 potentially fixable with the --fix option.

> cargo run -p ruff_cli -- check crates/ruff/resources/test/project/examples/excluded/
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/ruff check crates/ruff/resources/test/project/examples/excluded/`
warning: Detected debug build without --no-cache.
crates/ruff/resources/test/project/examples/excluded/script.py:1:8: F401 [*] `os` imported but unused
Found 1 error.
[*] 1 potentially fixable with the --fix option.

> cargo run -p ruff_cli -- check crates/ruff/resources/test/project/examples/excluded/ --force-exclude
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/ruff check crates/ruff/resources/test/project/examples/excluded/ --force-exclude`
warning: Detected debug build without --no-cache.
warning: No Python files found under the given path(s)

> cargo run -p ruff_cli -- check crates/ruff/resources/test/project/examples/excluded/ --force-exclude
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/ruff check crates/ruff/resources/test/project/examples/excluded/ --force-exclude`
warning: Detected debug build without --no-cache.
warning: No Python files found under the given path(s)
```

**Comment by charliermarsh** [comment]
I like where you're headed with that test, but I'd also be fine to add tests in a future PR for all of this behavior holistically rather than trying to figure out the right pattern for this bug fix. I defer to @zanieb as first reviewer :)

**Comment by harupy** [comment]
> I'd also be fine to add tests in a future PR for all of this behavior holistically rather than trying to figure out the right pattern for this bug fix.

+1

File: crates/ruff/src/resolver.rs [hunk 2]
```diff
@@ -330,9 +330,12 @@ pub fn python_files_in_path(
             }
 
             if result.as_ref().map_or(true, |entry| {
```
Comment (harupy) [inline crates/ruff/src/resolver.rs:332]: Unrelated to this PR, but is it safe to default to `true` when `result` is Err?

**Comment by harupy** [comment]
@zanieb Can you take another look?

**Review by zanieb — APPROVED** [review]
Thank you!
