### PR TITLE
[`flake8-pyi`] Avoid syntax error from conflict with `PIE790` (`PYI021`)

### LINKED ISSUE #19982: Fix introduced a syntax error
### Summary

`pin.pyi`:
```
"""Type stubs for micro:bit pin module."""

from typing import overload, Literal

class MicroBitDigitalPin:
    """A digital pin on the micro:bit."""

    NO_PULL: int = 0
    PULL_UP: int = 1
    PULL_DOWN: int = 2

    def read_digital(self) -> int:
        """Read digital value (0 or 1)."""
        ...

    def write_digital(self, value: int) -> None:
        """Write digital value (0 or 1)."""
        ...

    @overload
    def set_pull(self, value: int) -> None:
        """Set pull resistor mode."""
        ...

    @overload
    def set_pull(self, value: Literal[0, 1, 2]) -> None:
        """Set pull resistor mode."""
        ...

    def get_pull(self) -> int:
        """Get current pull mode."""
        ...

    def get_mode(self) -> str:
        """Get current pin mode."""
        ...

    def write_analog(self, value: int) -> None:
        """Write analog value (0-1023) for PWM."""
        ...

    def set_analog_period(self, period: int) -> None:
        """Set PWM period in milliseconds."""
        ...

    def set_analog_period_microseconds(self, period: int) -> None:
        """Set PWM period in microseconds."""
        ...

    def get_analog_period_microseconds(self) -> int:
        """Get PWM period in microseconds."""
        ...

class MicroBitAnalogDigitalPin(MicroBitDigitalPin):
    """An analog/digital pin on the micro:bit."""

    def read_analog(self) -> int:
        """Read analog value (0-1023)."""
        ...

class MicroBitTouchPin(MicroBitAnalogDigitalPin):
    """A touch-sensitive pin on the micro:bit."""

    CAPACITIVE: int = 0
    RESISTIVE: int = 1

    def is_touched(self) -> bool:
        """Check if pin is being touched."""
        ...

    def was_touched(self) -> bool:
        """Check if pin was touched since last check."""
        ...

    def get_touches(self) -> int:
        """Get number of touches since last check."""
        ...

    def set_touch_mode(self, mode: int) -> None:
        """Set touch detection mode."""
        ...
```
`ruff check pin.pyi --fix`:
```
[2025-08-19][13:15:22][ruff::resolve][DEBUG] Using configuration file (via cwd) at: /root/.config/ruff/ruff.toml
[2025-08-19][13:15:22][ruff_workspace::resolver][DEBUG] Included path via `include`: "/Data/micropython-microbit/stubs/microbit/pin.pyi"
[2025-08-19][13:15:22][ignore::gitignore][DEBUG] opened gitignore file: /Data/micropython-microbit/stubs/microbit/.ruff_cache/.gitignore
[2025-08-19][13:15:22][ruff_workspace::resolver][DEBUG] Ignored path via `exclude`: "/Data/micropython-microbit/stubs/microbit/.ruff_cache"
[2025-08-19][13:15:22][ruff::commands::check][DEBUG] Identified files to lint in: 3.219548ms
[2025-08-19][13:15:22][ruff::diagnostics][DEBUG] Checking: /Data/micropython-microbit/stubs/microbit/pin.pyi
[2025-08-19][13:15:22][ruff_linter::rules::isort::categorize][DEBUG] Categorized 'typing' as Known(StandardLibrary) (KnownStandardLibrary)

error: Fix introduced a syntax error. Reverting all changes.

This indicates a bug in Ruff. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BFix%20error%5D

...quoting the contents of `pin.pyi`, the rule codes I001, PIE790, PYI021, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

[2025-08-19][13:15:22][ruff_linter::rules::isort::categorize][DEBUG] Categorized 'typing' as Known(StandardLibrary) (KnownStandardLibrary)
[2025-08-19][13:15:22][ruff::commands::check][DEBUG] Checked 1 files in: 916.395µs
PYI021 [*] Docstrings should not be included in stubs
 --> pin.pyi:1:1
  |
1 | """Type stubs for micro:bit pin module."""
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2 |
3 | from typing import overload, Literal
  |
help: Remove docstring

CPY001 Missing copyright notice at top of file
--> pin.pyi:1:1

I001 [*] Import block is un-sorted or un-formatted
 --> pin.pyi:3:1
  |
1 | """Type stubs for micro:bit pin module."""
2 |
3 | from typing import overload, Literal
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
4 |
5 | class MicroBitDigitalPin:
  |
help: Organize imports

PYI021 [*] Docstrings should not be included in stubs
 --> pin.pyi:6:5
  |
5 | class MicroBitDigitalPin:
6 |     """A digital pin on the micro:bit."""
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
7 |
8 |     NO_PULL: int = 0
  |
help: Remove docstring

PYI048 Function body must contain exactly one statement
  --> pin.pyi:12:9
   |
10 |     PULL_DOWN: int = 2
11 |
12 |     def read_digital(self) -> int:
   |         ^^^^^^^^^^^^
13 |         """Read digital value (0 or 1)."""
14 |         ...
   |

PYI021 [*] Docstrings should not be included in stubs
  --> pin.pyi:13:9
   |
12 |     def read_digital(self) -> int:
13 |         """Read digital value (0 or 1)."""
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14 |         ...
   |
help: Remove docstring

PIE790 [*] Unnecessary `...` literal
  --> pin.pyi:14:9
   |
12 |     def read_digital(self) -> int:
13 |         """Read digital value (0 or 1)."""
14 |         ...
   |         ^^^
15 |
16 |     def write_digital(self, value: int) -> None:
   |
help: Remove unnecessary `...`

PYI048 Function body must contain exactly one statement
  --> pin.pyi:16:9
   |
14 |         ...
15 |
16 |     def write_digital(self, value: int) -> None:
   |         ^^^^^^^^^^^^^
17 |         """Write digital value (0 or 1)."""
18 |         ...
   |

PYI021 [*] Docstrings should not be included in stubs
  --> pin.pyi:17:9
   |
16 |     def write_digital(self, value: int) -> None:
17 |         """Write digital value (0 or 1)."""
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
18 |         ...
   |
help: Remove docstring

PIE790 [*] Unnecessary `...` literal
  --> pin.pyi:18:9
   |
16 |     def write_digital(self, value: int) -> None:
17 |         """Write digital value (0 or 1)."""
18 |         ...
   |         ^^^
19 |
20 |     @overload
   |
help: Remove unnecessary `...`

PYI048 Function body must contain exactly one statement
  --> pin.pyi:21:9
   |
20 |     @overload
21 |     def set_pull(self, value: int) -> None:
   |         ^^^^^^^^
22 |         """Set pull resistor mode."""
23 |         ...
   |

D418 Function decorated with `@overload` shouldn't contain a docstring
  --> pin.pyi:21:9
   |
20 |     @overload
21 |     def set_pull(self, value: int) -> None:
   |         ^^^^^^^^
22 |         """Set pull resistor mode."""
23 |         ...
   |

PYI021 [*] Docstrings should not be included in stubs
  --> pin.pyi:22:9
   |
20 |     @overload
21 |     def set_pull(self, value: int) -> None:
22 |         """Set pull resistor mode."""
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
23 |         ...
   |
help: Remove docstring

PIE790 [*] Unnecessary `...` literal
  --> pin.pyi:23:9
   |
21 |     def set_pull(self, value: int) -> None:
22 |         """Set pull resistor mode."""
23 |         ...
   |         ^^^
24 |
25 |     @overload
   |
help: Remove unnecessary `...`

PYI048 Function body must contain exactly one statement
  --> pin.pyi:26:9
   |
25 |     @overload
26 |     def set_pull(self, value: Literal[0, 1, 2]) -> None:
   |         ^^^^^^^^
27 |         """Set pull resistor mode."""
28 |         ...
   |

D418 Function decorated with `@overload` shouldn't contain a docstring
  --> pin.pyi:26:9
   |
25 |     @overload
26 |     def set_pull(self, value: Literal[0, 1, 2]) -> None:
   |         ^^^^^^^^
27 |         """Set pull resistor mode."""
28 |         ...
   |

PYI021 [*] Docstrings should not be included in stubs
  --> pin.pyi:27:9
   |
25 |     @overload
26 |     def set_pull(self, value: Literal[0, 1, 2]) -> None:
27 |         """Set pull resistor mode."""
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
28 |         ...
   |
help: Remove docstring

PIE790 [*] Unnecessary `...` literal
  --> pin.pyi:28:9
   |
26 |     def set_pull(self, value: Literal[0, 1, 2]) -> None:
27 |         """Set pull resistor mode."""
28 |         ...
   |         ^^^
29 |
30 |     def get_pull(self) -> int:
   |
help: Remove unnecessary `...`

PYI048 Function body must contain exactly one statement
  --> pin.pyi:30:9
   |
28 |         ...
29 |
30 |     def get_pull(self) -> int:
   |         ^^^^^^^^
31 |         """Get current pull mode."""
32 |         ...
   |

PYI021 [*] Docstrings should not be included in stubs
  --> pin.pyi:31:9
   |
30 |     def get_pull(self) -> int:
31 |         """Get current pull mode."""
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
32 |         ...
   |
help: Remove docstring

PIE790 [*] Unnecessary `...` literal
  --> pin.pyi:32:9
   |
30 |     def get_pull(self) -> int:
31 |         """Get current pull mode."""
32 |         ...
   |         ^^^
33 |
34 |     def get_mode(self) -> str:
   |
help: Remove unnecessary `...`

PYI048 Function body must contain exactly one statement
  --> pin.pyi:34:9
   |
32 |         ...
33 |
34 |     def get_mode(self) -> str:
   |         ^^^^^^^^
35 |         """Get current pin mode."""
36 |         ...
   |

PYI021 [*] Docstrings should not be included in stubs
  --> pin.pyi:35:9
   |
34 |     def get_mode(self) -> str:
35 |         """Get current pin mode."""
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
36 |         ...
   |
help: Remove docstring

PIE790 [*] Unnecessary `...` literal
  --> pin.pyi:36:9
   |
34 |     def get_mode(self) -> str:
35 |         """Get current pin mode."""
36 |         ...
   |         ^^^
37 |
38 |     def write_analog(self, value: int) -> None:
   |
help: Remove unnecessary `...`

PYI048 Function body must contain exactly one statement
  --> pin.pyi:38:9
   |
36 |         ...
37 |
38 |     def write_analog(self, value: int) -> None:
   |         ^^^^^^^^^^^^
39 |         """Write analog value (0-1023) for PWM."""
40 |         ...
   |

PYI021 [*] Docstrings should not be included in stubs
  --> pin.pyi:39:9
   |
38 |     def write_analog(self, value: int) -> None:
39 |         """Write analog value (0-1023) for PWM."""
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
40 |         ...
   |
help: Remove docstring

PIE790 [*] Unnecessary `...` literal
  --> pin.pyi:40:9
   |
38 |     def write_analog(self, value: int) -> None:
39 |         """Write analog value (0-1023) for PWM."""
40 |         ...
   |         ^^^
41 |
42 |     def set_analog_period(self, period: int) -> None:
   |
help: Remove unnecessary `...`

PYI048 Function body must contain exactly one statement
  --> pin.pyi:42:9
   |
40 |         ...
41 |
42 |     def set_analog_period(self, period: int) -> None:
   |         ^^^^^^^^^^^^^^^^^
43 |         """Set PWM period in milliseconds."""
44 |         ...
   |

PYI021 [*] Docstrings should not be included in stubs
  --> pin.pyi:43:9
   |
42 |     def set_analog_period(self, period: int) -> None:
43 |         """Set PWM period in milliseconds."""
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
44 |         ...
   |
help: Remove docstring

PIE790 [*] Unnecessary `...` literal
  --> pin.pyi:44:9
   |
42 |     def set_analog_period(self, period: int) -> None:
43 |         """Set PWM period in milliseconds."""
44 |         ...
   |         ^^^
45 |
46 |     def set_analog_period_microseconds(self, period: int) -> None:
   |
help: Remove unnecessary `...`

PYI048 Function body must contain exactly one statement
  --> pin.pyi:46:9
   |
44 |         ...
45 |
46 |     def set_analog_period_microseconds(self, period: int) -> None:
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
47 |         """Set PWM period in microseconds."""
48 |         ...
   |

PYI021 [*] Docstrings should not be included in stubs
  --> pin.pyi:47:9
   |
46 |     def set_analog_period_microseconds(self, period: int) -> None:
47 |         """Set PWM period in microseconds."""
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
48 |         ...
   |
help: Remove docstring

PIE790 [*] Unnecessary `...` literal
  --> pin.pyi:48:9
   |
46 |     def set_analog_period_microseconds(self, period: int) -> None:
47 |         """Set PWM period in microseconds."""
48 |         ...
   |         ^^^
49 |
50 |     def get_analog_period_microseconds(self) -> int:
   |
help: Remove unnecessary `...`

PYI048 Function body must contain exactly one statement
  --> pin.pyi:50:9
   |
48 |         ...
49 |
50 |     def get_analog_period_microseconds(self) -> int:
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
51 |         """Get PWM period in microseconds."""
52 |         ...
   |

PYI021 [*] Docstrings should not be included in stubs
  --> pin.pyi:51:9
   |
50 |     def get_analog_period_microseconds(self) -> int:
51 |         """Get PWM period in microseconds."""
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
52 |         ...
   |
help: Remove docstring

PIE790 [*] Unnecessary `...` literal
  --> pin.pyi:52:9
   |
50 |     def get_analog_period_microseconds(self) -> int:
51 |         """Get PWM period in microseconds."""
52 |         ...
   |         ^^^
53 |
54 | class MicroBitAnalogDigitalPin(MicroBitDigitalPin):
   |
help: Remove unnecessary `...`

PYI021 [*] Docstrings should not be included in stubs
  --> pin.pyi:55:5
   |
54 | class MicroBitAnalogDigitalPin(MicroBitDigitalPin):
55 |     """An analog/digital pin on the micro:bit."""
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
56 |
57 |     def read_analog(self) -> int:
   |
help: Remove docstring

PYI048 Function body must contain exactly one statement
  --> pin.pyi:57:9
   |
55 |     """An analog/digital pin on the micro:bit."""
56 |
57 |     def read_analog(self) -> int:
   |         ^^^^^^^^^^^
58 |         """Read analog value (0-1023)."""
59 |         ...
   |

PYI021 [*] Docstrings should not be included in stubs
  --> pin.pyi:58:9
   |
57 |     def read_analog(self) -> int:
58 |         """Read analog value (0-1023)."""
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
59 |         ...
   |
help: Remove docstring

PIE790 [*] Unnecessary `...` literal
  --> pin.pyi:59:9
   |
57 |     def read_analog(self) -> int:
58 |         """Read analog value (0-1023)."""
59 |         ...
   |         ^^^
60 |
61 | class MicroBitTouchPin(MicroBitAnalogDigitalPin):
   |
help: Remove unnecessary `...`

PYI021 [*] Docstrings should not be included in stubs
  --> pin.pyi:62:5
   |
61 | class MicroBitTouchPin(MicroBitAnalogDigitalPin):
62 |     """A touch-sensitive pin on the micro:bit."""
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
63 |
64 |     CAPACITIVE: int = 0
   |
help: Remove docstring

PYI048 Function body must contain exactly one statement
  --> pin.pyi:67:9
   |
65 |     RESISTIVE: int = 1
66 |
67 |     def is_touched(self) -> bool:
   |         ^^^^^^^^^^
68 |         """Check if pin is being touched."""
69 |         ...
   |

PYI021 [*] Docstrings should not be included in stubs
  --> pin.pyi:68:9
   |
67 |     def is_touched(self) -> bool:
68 |         """Check if pin is being touched."""
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
69 |         ...
   |
help: Remove docstring

PIE790 [*] Unnecessary `...` literal
  --> pin.pyi:69:9
   |
67 |     def is_touched(self) -> bool:
68 |         """Check if pin is being touched."""
69 |         ...
   |         ^^^
70 |
71 |     def was_touched(self) -> bool:
   |
help: Remove unnecessary `...`

PYI048 Function body must contain exactly one statement
  --> pin.pyi:71:9
   |
69 |         ...
70 |
71 |     def was_touched(self) -> bool:
   |         ^^^^^^^^^^^
72 |         """Check if pin was touched since last check."""
73 |         ...
   |

PYI021 [*] Docstrings should not be included in stubs
  --> pin.pyi:72:9
   |
71 |     def was_touched(self) -> bool:
72 |         """Check if pin was touched since last check."""
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
73 |         ...
   |
help: Remove docstring

PIE790 [*] Unnecessary `...` literal
  --> pin.pyi:73:9
   |
71 |     def was_touched(self) -> bool:
72 |         """Check if pin was touched since last check."""
73 |         ...
   |         ^^^
74 |
75 |     def get_touches(self) -> int:
   |
help: Remove unnecessary `...`

PYI048 Function body must contain exactly one statement
  --> pin.pyi:75:9
   |
73 |         ...
74 |
75 |     def get_touches(self) -> int:
   |         ^^^^^^^^^^^
76 |         """Get number of touches since last check."""
77 |         ...
   |

PYI021 [*] Docstrings should not be included in stubs
  --> pin.pyi:76:9
   |
75 |     def get_touches(self) -> int:
76 |         """Get number of touches since last check."""
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
77 |         ...
   |
help: Remove docstring

PIE790 [*] Unnecessary `...` literal
  --> pin.pyi:77:9
   |
75 |     def get_touches(self) -> int:
76 |         """Get number of touches since last check."""
77 |         ...
   |         ^^^
78 |
79 |     def set_touch_mode(self, mode: int) -> None:
   |
help: Remove unnecessary `...`

PYI048 Function body must contain exactly one statement
  --> pin.pyi:79:9
   |
77 |         ...
78 |
79 |     def set_touch_mode(self, mode: int) -> None:
   |         ^^^^^^^^^^^^^^
80 |         """Set touch detection mode."""
81 |         ...
   |

PYI021 [*] Docstrings should not be included in stubs
  --> pin.pyi:80:9
   |
79 |     def set_touch_mode(self, mode: int) -> None:
80 |         """Set touch detection mode."""
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
81 |         ...
   |
help: Remove docstring

PIE790 [*] Unnecessary `...` literal
  --> pin.pyi:81:9
   |
79 |     def set_touch_mode(self, mode: int) -> None:
80 |         """Set touch detection mode."""
81 |         ...
   |         ^^^
   |
help: Remove unnecessary `...`

Found 53 errors.
[*] 35 fixable with the --fix option.
```
`ruff.toml`:
```
preview = true
unsafe-fixes = true
target-version = "py313"
line-length = 79
builtins = ["_"]

[analyze]
preview = true

[format]
preview = true
docstring-code-format = true
line-ending = "lf"
skip-magic-trailing-comma = true

[lint]
future-annotations = true
select = ["ALL"]
typing-extensions = false
unfixable = ["T201"]
ignore = [
    "D206",
    "E114",
    "E111",
    "W191",
    "Q003",
    "Q002",
    "Q000",
    "Q001",
    "COM812",
    "D208",
    "E117",
    "COM819",
    "D300",
    "D207",
    "Q004",
    "S404",
    "S602",
    "S603",
    "D203",
    "D212",
]

[lint.isort]
split-on-trailing-comma = false

[lint.extend-per-file-ignores]
"**/__init__.py*" = ["F403", "F401"]
"tests/**/*.py" = [
    # at least this three should be fine in tests:
    "S101", # asserts allowed in tests...
    "ARG",  # Unused function args -> fixtures nevertheless are functionally relevant...
    "FBT",  # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
    # The below are debateable
    "PLR2004", # Magic value used in comparison, ...
    "S311",    # Standard pseudo-random generators are not suitable for cryptographic purposes
]
```

### Version

0.12.9

### PR DESCRIPTION
**Pull request by second-ed**
## Summary

First contribution so please let me know if I've made a mistake anywhere. This was aimed to fix #19982, it adds the isolation level to PYI021 to in the same style as the PIE790 rule.

fixes: #19982

## Test Plan

I added a case to the PYI021.pyi file where the two rules are present as there wasn't a case with them both interacting, using the minimal reproducible example that @ntBre created on the issue (I think I got the `# ERROR` markings wrong, so please let me know how to fix that if I did).

### CODE REVIEW

**Comment by ntBre** [comment]
Awesome, thanks for working on this! One note, I believe the `# ERROR` comments in that file are just to make reviewing snapshots a little easier and don't actually activate the rules. The file `PYI021.pyi` is used as one of the `test_case`s in this test:

https://github.com/astral-sh/ruff/blob/39f7a876d6aceedc3db4e3d63250d78bbb830fc2/crates/ruff_linter/src/rules/flake8_pyi/mod.rs#L130-L139

so only PYI021 is active still:

https://github.com/astral-sh/ruff/blob/39f7a876d6aceedc3db4e3d63250d78bbb830fc2/crates/ruff_linter/src/rules/flake8_pyi/mod.rs#L39

I think you'll probably want to create a copy of this test function and enable both the rules. Something like this:

```rust
    #[test_case(Path::new("PYI021.pyi"))]
    fn pyi021_pie790_empty_function(path: &Path) -> Result<()> {
        let diagnostics = test_path(
            Path::new("flake8_pyi").join(path).as_path(),
            &settings::LinterSettings::for_rules([Rule::DocstringInStub, Rule::UnnecessaryPlaceholder]),
        )?;
        assert_diagnostics!(diagnostics);
        Ok(())
    }
```

Or you could just hard-code the path in this case since I doubt we'll need multiple `test_case`s :) It might also make sense to use a separate `pyi` file from the main `PYI021.pyi` case, but I don't think that's a big deal either way, up to you.

I think your fix is likely still correct, but this will make sure we're testing the right thing!

**Comment by second-ed** [comment]
Perfect, thanks for the suggestions. I'll make those changes tomorrow!

**Comment by second-ed** [comment]
Hey, I added the changes you suggested but I wasn't getting a pass on the test locally (as it was panicking after applying both fixes), I think there's something wrong with my isolation level check in the actual implementation. I've pushed up the code so you can see, but will have a play with it after work tomorrow and try to work out the issue

**Comment by ntBre** [comment]
I'll take a look. `Isolation` may not be enough. We may need to check explicitly (in one or both rules) that we're not leaving an empty function body. That might be a good separate test to try, or check if we already have some. Do the rules individually suggest deleting the last statement in a function?

**Comment by ntBre** [comment]
Ah sorry, this might actually be trickier than I expected. PYI021 only looks at the deferred definitions after the AST has been traversed, so `checker.semantic().current_statement_id()` is returning `None`. That explains why `Isolation` isn't working. But both rules try to check that they aren't deleting the last statement in a definition, so `Isolation` also still seems like the right fix. I'm just not seeing a way to get a real `NodeId` to pass to `Checker::isolation` from a `Definition` or docstring literal.

We may have to move PYI021's check into the same phase of analysis as PIE790, which would be a bit more involved.

https://github.com/astral-sh/ruff/blob/a50b389d626528d55c22979dac50c48387a5e1e0/crates/ruff_linter/src/checkers/ast/analyze/suite.rs#L8-L12

**Comment by second-ed** [comment]
Hey, having a look through now, will give my best guess but I'm sure you'll have a better idea! I'll commit as far as I get

**Comment by second-ed** [comment]
My initial plan is:
add both rules to a `IsolationLevel::Group` then look instead of getting the `current_statement_id` get something like the `current_scope` or something like that, does that sound reasonable?

**Comment by ntBre** [comment]
Sorry, I don't mean to leave you hanging on this, I'm just not quite sure the best approach yet either. I don't think I mentioned this above, but I even tried something like this method added to our `SemanticModel`:

```rust
    pub fn statement_id(&self, stmt: &ast::Stmt) -> Option<NodeId> {
        self.nodes.iter().find(|node| self.statement(*node) == stmt)
    }
```

without much luck. Basically your idea sounds right to me, and is what I expected the fix to be too, but I'm not sure if it works with the way we're traversing the AST or calling this rule.

Don't feel any pressure to keep working on this, I'll try to take another look at some point too.

**Comment by second-ed** [comment]
Hey no worries - I can see you're pretty busy on a load of other PRs! 

I'm happy to keep tweaking and chipping away at ideas, it's a good opportunity for me to get familiar with more of the codebase.

Out of interest what `Stmt` are you passing into this method?
```rust
    pub fn statement_id(&self, stmt: &ast::Stmt) -> Option<NodeId> {
        self.nodes.iter().find(|node| self.statement(*node) == stmt)
    }
```

Maybe passing the statement that holds the ellipsis expression could work?

**Comment by second-ed** [comment]
I've had a play, I added the method you shared. After running `dbg!` on all of the statements in the `docstring_in_stubs`, they all seem to be returning None. 

The fact that the `self.node_id` is None makes me agree with you that we should move the rule itself to the same point where the other rule is triggered, but that causes issues in that the function signature will need to change because the function that calls `unnecessary_placeholder` uses `suite: &[Stmt]` whereas the other one uses `definition: &Definition`

I think that the self.node_id is always None because it's being called after the ast has finished traversing?

```rust
[crates/ruff_python_semantic/src/model.rs:1414:9] &self.node_id = None
[crates/ruff_linter/src/rules/flake8_pyi/rules/docstring_in_stubs.rs:65:5] checker.semantic().statement_id(&statements[0]) = None
[crates/ruff_python_semantic/src/model.rs:1414:9] &self.node_id = None
[crates/ruff_linter/src/rules/flake8_pyi/rules/docstring_in_stubs.rs:66:5] checker.semantic().statement_id(&statements[1]) = None
[crates/ruff_python_semantic/src/model.rs:1414:9] &self.node_id = None
```

**Comment by ntBre** [comment]
That all sounds right to me. I think the best course of action is to move it to the earlier analysis phase, while we're still traversing the AST, like `PIE790`. I was quite hesitant to do that earlier, but I think it won't be too bad after looking again today. We should still be able to call `docstring_from` on just a `&[Stmt]`, which we have access to in that phase:

https://github.com/astral-sh/ruff/blob/bbfcf6e111648052783bdb68ec71706fc69b714f/crates/ruff_linter/src/docstrings/extraction.rs#L6-L8

and the only reason we pass a `Definition` to `PYI021` is also to extract its `&[Stmt]`.

So this rule actually seems to fit nicely into `analyze::suite` next to `PIE790`:

https://github.com/astral-sh/ruff/blob/bbfcf6e111648052783bdb68ec71706fc69b714f/crates/ruff_linter/src/checkers/ast/analyze/suite.rs#L9-L12

unless there's some additional subtlety I'm missing.

**Comment by second-ed** [comment]
Awesome sounds good, cheers for the hint I'll give it a go!

**Comment by second-ed** [comment]
I think I've got it there now, all tests pass without any hardcoding.

I moved `in_protocol_or_abstract_method` to the semantic model itself because I thought I might need to check it in PYI021 but didn't need it in the end so can move it back if you want although I think it makes more sense as a method than a free function

I know you're busy so no rush to review, but let me know what you think

**Comment by second-ed** [comment]
Hey @ntBre just realised I forgot to tag you in my last message, just to let you know I think this one is ready for review whenever you get a chance, cheers!

**Comment by second-ed** [comment]
Sorry! forgot to update the snapshot tests, will do now

**Comment by second-ed** [comment]
Hmmm I'm not getting the same fail when I run the tests locally I've run the following commands:

```shell
cargo insta test --review
```

and this which I copied from the git action
```shell
cargo insta test --all-features --unreferenced reject --test-runner nextest
```

the tests all pass when I run the code locally, not sure if I've missed something 🤔 

no rush at all @ntBre , but please let me know if theres something I've overlooked! cheers

**Comment by ntBre** [comment]
You may need to rebase/merge main and then accept the snapshots again. It looks like an artifact from our recent diagnostic refactor, which changed the output format a bit.

(Sorry for the delayed review. The code changes look good from a quick skim, just trying to finish the 0.13 release before doing a proper review)

**Comment by second-ed** [comment]
Might be a good candidate to squash when merging 😅 sorry!

**Comment by ntBre** [comment]
No worries, we always squash merge! It does look like something went slightly awry with the merge. At least on GitHub, it's showing 201 commits. I think it should still be okay, though. Only the relevant changes are showing up.

**Comment by second-ed** [comment]
Yeah sorry, I think I botched the rebase (thats what I get for rebasing when I'm firmly in camp merge!). I had a look at the changes too and they only are the ones I introduced so should be ok 🤞

File: crates/ruff_python_semantic/src/model.rs [hunk 1]
```diff
@@ -1406,6 +1407,17 @@ impl<'a> SemanticModel<'a> {
             .expect("No statement found")
     }
 
+    /// Return the [`NodeId`] for the given [`Stmt`].
+    pub fn statement_id(&self, stmt: &ast::Stmt) -> Option<NodeId> {
```
Comment (ntBre) [inline crates/ruff_python_semantic/src/model.rs]: Is this called anywhere now? I think we can revert this.

File: crates/ruff_python_semantic/src/model.rs [hunk 2]
```diff
@@ -1654,6 +1666,21 @@ impl<'a> SemanticModel<'a> {
         }
     }
 
+    /// Return `true` if the model is in a `typing.Protocol` subclass or an abstract
+    /// method.
+    pub fn in_protocol_or_abstract_method(&self) -> bool {
```
Comment (ntBre) [inline crates/ruff_python_semantic/src/model.rs]: I'd probably lean toward leaving this in the same file as before, unless there's a specific reason to move it out.

File: crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI021_1.pyi [hunk 3]
```diff
@@ -0,0 +1,3 @@
+def check_isolation_level(mode: int) -> None:
+    """Shouldn't try to fix either."""  # ERROR PYI021
```
Comment (ntBre) [inline crates/ruff_linter/resources/test/fixtures/flake8_pyi/PYI021_1.pyi]: This docstring seems slightly misleading since the snapshot shows it trying to fix both diagnostics 😄 

In testing this locally in the CLI, the net effect is that we still emit both diagnostics when checking, but the isolation level means only the first diagnostic actually gets fixed. Since we sort by diagnostic range, that means PYI021 gets fixed and PIE790 does not. You don't need to write all of that in the docstring, to be clear, just recording my observations!

File: crates/ruff_linter/src/checkers/ast/analyze/suite.rs [hunk 4]
```diff
@@ -2,14 +2,17 @@ use ruff_python_ast::Stmt;
...
-use crate::rules::flake8_pie;
 use crate::rules::refurb;
+use crate::rules::{flake8_pie, flake8_pyi};
 
 /// Run lint rules over a suite of [`Stmt`] syntax nodes.
 pub(crate) fn suite(suite: &[Stmt], checker: &Checker) {
     if checker.is_rule_enabled(Rule::UnnecessaryPlaceholder) {
         flake8_pie::rules::unnecessary_placeholder(checker, suite);
     }
+    if checker.source_type.is_stub() && checker.is_rule_enabled(Rule::DocstringInStub) {
```
Comment (ntBre) [inline crates/ruff_linter/src/checkers/ast/analyze/suite.rs:13]: One thing I didn't realize about moving this here is that it now gets called for non-function (or -class or -module) suites, such as context managers or `if` statements:

```py
with foo():
    """docstring"""
    pass

if True:
    """docstring"""
    pass
```

I tested these locally, and we flag both of these. Fortunately, it looks like we already track a [`docstring_state`](https://github.com/astral-sh/ruff/blob/main/crates/ruff_linter/src/checkers/ast/mod.rs#L235) field on `Checker`. We'd have to add a `pub(crate)` getter function for this and make the `DocstringState` and `ExpectedDocstringKind` enums `pub(crate)` too, but I think we can use that to check that we're in an actual docstring.

There's an existing [`SemanticModel::in_pep_257_docstring`](https://github.com/astral-sh/ruff/blob/main/crates/ruff_python_semantic/src/model.rs#L1997) method, but unfortunately that flag only gets set on the `SemanticModel` once we're actually visiting the docstring.

Comment (second-ed) [reply crates/ruff_linter/src/checkers/ast/analyze/suite.rs:13]: Hey thanks for this, I think I've addressed all of the comments from the review, please let me know if I've missed anything!

**Review by ntBre — APPROVED** [review]
Thank you, this is great!

I pushed one small commit fixing a few nits:
* revert changes to `unnecessary_placeholder.rs`
* `current_docstring_state` -> `docstring_state`
* exclude `ExpectedDocstringKind::Attribute`

The last one was probably the biggest, but I also think it wasn't possible to reach based on how we're calling `analyze::suite`. It just seemed better to be explicit in case that changed in the future.

**Comment by second-ed** [comment]
Awesome, nice one - I didn't realise that we didn't have to worry about docstring_state clashing being both an attribute and a method of the struct that's good to know. Yeah checking explicitly for the expected docstring kind makes sense too, I'll have a closer read of the changes you made to see if there are any tricks to steal! 

Cheers for your help and guidance on this PR btw, I'll keep an eye out for any others that I think are my level of difficulty!
