### PR TITLE
[`pylint`] Fix missing parens in unsafe fix for `unnecessary-dunder-call` (`PLC2801`)

### LINKED ISSUE #15745: PLC2801 fix needs parentheses before subscript or attribute access
### Description

The fix for [`unnecessary-dunder-call` (PLC2801)](https://docs.astral.sh/ruff/rules/unnecessary-dunder-call/) in Ruff 0.9.3 can change the program’s behavior when the rewritten expression is followed by an attribute access or a subscript access. The fix should wrap the rewritten expression in parentheses in those contexts.
```console
$ cat >plc2801.py <<'#EOF'
print(1j.__add__(1.0).real)
print("x".__add__("y")[0])
#EOF

$ python plc2801.py
1.0
x

$ ruff --isolated check --preview --select PLC2801 plc2801.py --unsafe-fixes --fix
Found 2 errors (2 fixed, 0 remaining).

$ cat plc2801.py
print(1j + 1.0.real)
print("x" + "y"[0])

$ python plc2801.py
(1+1j)
xy
```

### PR DESCRIPTION
**Pull request by mishamsk**
## Summary

This fixes #15745

Also, I haven't found a trait/helper to get expression precedence. Even though at least 3 rules check precedence when generating fixes. Generally speaking, unless/until fixes are done via AST generation - many (all?) fixes involving expression rewrites would need to consult precedence to handle parens. Unless I am mistaken.

Thus, I've implemented an enum and a trait. But I didn't dare doing that in semantic/AST crates, although I believe it would be helpful to move them there.

@AlexWaygood @dylwil3 you'll know the codebase better, let me know if you think it should be elevated to some core base crate. If you do, I am happy to implement this, but will need your guidance on where you'd like it to reside.

## Test Plan

* Updated test case with 2 examples from the issue + a couple of mine, including one that would generate invalid python program before this fix
* cargo nextest run (check updated snapshot)

### CODE REVIEW

File: crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs [hunk 1]
```diff
@@ -391,23 +573,134 @@ fn in_dunder_method_definition(semantic: &SemanticModel) -> bool {
...
+    BitwiseXorOr = 55,
+    BitwiseAnd = 60,
+    BitwiseShifts = 65,
+    AddSub = 70,
+    MultDiv = 75,
+    Unary = 80,
+    Power = 85,
+    Await = 90,
+    CallAttr = 95,
+    Atomic = 100,
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs:599]: What's the motivation for assigning fixed numbers to the different precedence values? I don't this is necessary because `ExprPrecedence` is an internal enum -- changing the values isn't user visible.

File: crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs [hunk 2]
```diff
@@ -391,23 +573,134 @@ fn in_dunder_method_definition(semantic: &SemanticModel) -> bool {
...
+
+/// A trait to determine the Python precedence of an expression.
+///
+/// Higher numeric values correspond to higher precedence.
+pub(crate) trait Precedence {
+    /// Returns the precedence level of the expression.
+    ///
+    /// Higher values indicate higher precedence.
+    fn precedence(&self) -> ExprPrecedence;
+}
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs:610]: I'd avoid a custom trait here and instead implement `From<&Expr>` for ExprPrecedence`, as well as `From<Operator>`, `From<UnaryOp>` and `From<BoolOp>`

File: crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs (hunk 1 above)
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs:599]: Could we align the names (enum and variants) with what we have in the [formatter](https://github.com/astral-sh/ruff/blob/ef85c682bdd76ed63457bdfbec72e09424ac20ab/crates/ruff_python_formatter/src/expression/mod.rs#L1141-L1155) and [parser](https://github.com/astral-sh/ruff/blob/138e70bd5c01d61061247c43b1bbb33d0290a18f/crates/ruff_python_parser/src/parser/expression.rs#L2366-L2397). It should simplify unifying the enums long-term

**Review by MichaReiser — APPROVED** [review]
Thanks. This overall looks good. Extracting a common `OperatorPrecedence` enum into the `ast` crate seems like a good idea because this PR now adds the third version of `OperatorPrecedence` enum but I suggest that we do this as a follow up PR. For now, I recommend aligning the enum and variant names with the other `OperatorPrecedence` enums

File: crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs (hunk 1 above)
Comment (mishamsk) [reply crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs:599]: Prefer being explicit (value) over implicit (position) when it doesn't have major downsides. THe thinking was - since Python precedence levels aren't likely to change these numbers would hold, and on the upside - reordering variants would break anything.

But that's speculative. I removed the values and repr, added a comment similar to the parser code too.

File: crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs (hunk 2 above)
Comment (mishamsk) [reply crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs:610]: I thought about it. The reason I went a custom trait route is that `From` either encourages to either use `into()` which is less readable outside of IDE (when types are not apparent), or would force writing `ExprPrecedence::from(some_node)` which is readable but longer. I expect compiler to emit exact same code for both.

Interestingly enough, both parser and formatter code include the same method for one specific expression too

https://github.com/astral-sh/ruff/blob/138e70bd5c01d61061247c43b1bbb33d0290a18f/crates/ruff_python_parser/src/parser/expression.rs#L2427-L2435

but rely on `OperatorPrecedence::from(some_node)` in all other cases.

I am not married to the custom trait idea, if you have a strong opinion here - I can easily change that. Either in this PR, or as a follow-up while moving the whole thing to AST module.

File: crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs (hunk 1 above)
Comment (mishamsk) [reply crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs:599]: First of all, I do not think that having even 3 enums is necessary bad. At least two separate ones make sense:

* Formatter enum is indeed an operator precedence one, as it is purpose is to split operators
* The one I've created and the parser one are both expression precedence and I would keep that naming. 
  * But unifying the parser one would go against @dhruvmanila comment, that explicitly excludes some expressions. I didn't investigate why, but I trust there were good reasons to do so

As for variant names - tbh. I like the shorter naming that aligns with Python docs better (formatter & mine), but since my enum logically closer to parser I changed names to mostly match parser version, where possible.

Comment (dhruvmanila) [reply crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs]: For the parser, the enum only contains precedence levels for the operators and not for all expressions. The main reason is that the parser utilizes the Pratt parsing algorithm to parse binary expressions which is the main use case for this enum. While, the other expressions are parsed normally and implemented as separate methods. But, that doesn't necessarily mean that it can't be unified to include other variants as well. We'll just have to be careful that the parser starts the binary expression parsing from the correct precedence level.

File: crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs (hunk 2 above)
Comment (MichaReiser) [reply crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs:635]: I removed the trait for now as it isn't needed when we move to the `ruff_python_ast` crate (because we can directly implement it on `Expr`). 

I also renamed the enum to `OperatorPrecedence` to better match what we have in other crates.

**Review by MichaReiser — APPROVED** [review]
