### PR TITLE
[`ruff`] Add `os-path-commonprefix` (`RUF071`)

### LINKED ISSUE #22981: Rule to advise `os.path.commonprefix` is wrong and you should use `os.path.commonpath`
### Summary

`commonprefix` is a string comparison, not a path comparison:

`commonprefix(['/usr/lib', '/usr/local/lib'])` → `'/usr/l'` (string prefix; not a valid directory)
`commonpath(['/usr/lib', '/usr/local/lib'])` → `'/usr'` (valid path)

If a user is importing from `os.path` there is a 99.99% chance they want a path function not a string function.

`commonpath` was added in Python 3.5 to fix this odd `commonprefix` behavior: https://github.com/python/cpython/issues/54604

### PR DESCRIPTION
**Pull request by anishgirianish**
## Summary

Adds a new rule os-path-commonprefix (RUF071) that detects calls to os.path.commonprefix(), which performs character-by-character string comparison instead of path-component comparison — a well-known footgun. os.path.commonpath() is the correct alternative.
               
## Test Plan

cargo nextest run -p ruff_linter -- rule_ospathcommonprefix

Closes #22981

### CODE REVIEW

File: crates/ruff_linter/src/rules/ruff/rules/os_path_commonprefix.rs [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+/// - [CPython deprecation issue](https://github.com/python/cpython/issues/144347)
+#[derive(ViolationMetadata)]
+#[violation_metadata(preview_since = "NEXT_RUFF_VERSION")]
+pub(crate) struct OsPathCommonprefix;
+
+impl Violation for OsPathCommonprefix {
+    #[derive_message_formats]
+    fn message(&self) -> String {
+        "`os.path.commonprefix()` compares strings character-by-character; use `os.path.commonpath()` to compare path components".to_string()
+    }
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/ruff/rules/os_path_commonprefix.rs:54]: I think the second part of this would look nice as the `fix_title`, which will display even without a fix:


```suggestion
    fn message(&self) -> String {
        "`os.path.commonprefix()` compares strings character-by-character".to_string()
    }
    
    fn fix_title(&self) -> Option<String> {
        Some("Use `os.path.commonpath()` to compare path components".to_string())
    }
```

**Comment by anishgirianish** [comment]
> Thanks, this looks great to me! I just had one suggestion on the diagnostic structure.
> 
> Would you be interested in adding a fix too? We could leave that for a follow-up PR, but I think it should be straightforward to autofix this, although I think it will have to be an unsafe fix.

Fo sure will do. thank you so much for the review
