### PR TITLE
[`pylint`] Fix `PLC1802` autofix creating a syntax error and mark autofix as unsafe if there's comments in the `len` call

### LINKED ISSUE #18811: [`Pylint`] `PLC1802` fix can cause syntax errors from lack of padding
### Summary

The fix for [len-test (PLC1802)](https://docs.astral.sh/ruff/rules/len-test/#len-test-plc1802) can cause a syntax error if the `len` is wrapped in parenthesis so it is next to the `if`. This should be fixable by adding padding. [playground](https://play.ruff.rs/e78f03d1-6817-499d-834d-0f99273cd015)
```
PS D:\python_projects> Get-Content issue.py
```
```py
fruits = []
if(len)(fruits):
    ...
```
```
PS D:\python_projects> uvx ruff check issue.py --select PLC --fix
```
```snap

error: Fix introduced a syntax error. Reverting all changes.

This indicates a bug in Ruff. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BFix%20error%5D

...quoting the contents of `issue.py`, the rule codes PLC1802, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

issue.py:2:3: PLC1802 `len(fruits)` used as condition without comparison
  |
1 | fruits = []
2 | if(len)(fruits):
  |   ^^^^^^^^^^^^^ PLC1802
3 |     ...
  |
  = help: Remove `len`

Found 1 error.
[*] 1 fixable with the `--fix` option.
```

### Version

ruff 0.12.0 (87f0feb21 2025-06-17) + playground

### LINKED ISSUE #18812: [`Pylint`] `PLC1802` fix can delete comments
### Summary

The fix for [len-test (PLC1802)](https://docs.astral.sh/ruff/rules/len-test/#len-test-plc1802) can delete comments. It should instead either be an unsafe fix in that case, not apply, or move the comments. [playground](https://play.ruff.rs/98d97f92-bcbe-4c18-846f-6874610a82a7)
```
PS D:\python_projects> Get-Content issue.py
```
```py
fruits = []
if (  # 1
    len  # 2
    )(  # 3
        fruits  # 4
    ):
    ...
```
```
PS D:\python_projects> uvx ruff check issue.py --select PLC
```
```snap
issue.py:2:4: PLC1802 [*] `len(fruits)` used as condition without comparison
  |
1 |   fruits = []
2 |   if (  # 1
  |  ____^
3 | |     len  # 2
4 | |     )(  # 3
5 | |         fruits  # 4
6 | |     ):
  | |_____^ PLC1802
7 |       ...
  |
  = help: Remove `len`

Found 1 error.
[*] 1 fixable with the `--fix` option.
```
```
PS D:\python_projects> uvx ruff check issue.py --select PLC --fix --diff
```
```diff
--- issue.py
+++ issue.py
@@ -1,7 +1,3 @@
 fruits = []
-if (  # 1
-    len  # 2
-    )(  # 3
-        fruits  # 4
-    ):
+if fruits:
     ...

Would fix 1 error.
```

### Version

ruff 0.12.0 (87f0feb 2025-06-17) + playground

### PR DESCRIPTION
**Pull request by LaBatata101**
## Summary
I've also found another bug while fixing this, where the diagnostic would not trigger if the `len` call argument variable was shadowed. This fixed a few false negatives in the test cases.
Example:
```python
fruits = []
fruits = []
if len(fruits):  # comment
    ...
```

Fixes #18811
Fixes #18812

## Test Plan
Add regression test

### CODE REVIEW

**Review by charliermarsh — APPROVED** [review]
Thanks!

File: crates/ruff_linter/src/rules/pylint/rules/len_test.rs [hunk 1]
```diff
@@ -41,6 +43,19 @@ use crate::{AlwaysFixableViolation, Edit, Fix};
 ///     print(vegetables)
 /// ```
 ///
+/// ## Fix safety
+/// This rule's fix is marked as unsafe if there's comments in the
```
Comment (charliermarsh) [inline crates/ruff_linter/src/rules/pylint/rules/len_test.rs]:
```suggestion
/// This rule's fix is marked as unsafe when the `len` call includes a comment,
/// as the comment would be removed.
```

File: crates/ruff_linter/src/rules/pylint/rules/len_test.rs [hunk 2]
```diff
@@ -41,6 +43,20 @@ use crate::{AlwaysFixableViolation, Edit, Fix};
 ///     print(vegetables)
 /// ```
 ///
+/// ## Fix safety
+/// This rule's fix is marked as unsafe when the `len` call includes a comment,
+/// as the comment would be removed.
+/// `len` call.
```
Comment (charliermarsh) [inline crates/ruff_linter/src/rules/pylint/rules/len_test.rs]:
```suggestion
```
