### PR TITLE
[`refurb`] Mark the `FURB161` fix unsafe except for integers and booleans

### LINKED ISSUE #16457: FURB161 fix should be marked unsafe in some contexts
### Summary

The fix for [bit-count (FURB161)](https://docs.astral.sh/ruff/rules/bit-count/) has a few problems.

When the argument to `bin` is a starred expression, the fix introduces a syntax error.
```console
$ cat >furb161_1.py <<'# EOF'
print(bin(*[123]).count("1"))
# EOF

$ python furb161_1.py
6

$ ruff --isolated check --target-version py310 --preview --select FURB161 furb161_1.py --diff 2>&1 | grep error:
error: Fix introduced a syntax error. Reverting all changes.
```

The fix is marked safe, but it is only safe when the argument to `bin` is an instance of certain types, including `int` and `bool`, that have `__index__` and `bit_count` methods. If Ruff can’t determine that the argument is of one of those types, it should mark the fix unsafe. Otherwise, the fix can introduce a runtime error.
```console
$ cat >furb161_2.py <<'# EOF'
from plistlib import UID
print(bin(UID(123)).count("1"))
# EOF

$ python furb161_2.py
6

$ ruff --isolated check --target-version py310 --preview --select FURB161 furb161_2.py --fix
Found 1 error (1 fixed, 0 remaining).

$ cat furb161_2.py
from plistlib import UID
print(UID(123).bit_count())

$ python furb161_2.py
Traceback (most recent call last):
  File "furb161_2.py", line 2, in <module>
    print(UID(123).bit_count())
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'UID' object has no attribute 'bit_count'
```

Another way the fix can be unsafe is by changing which exception is raised.
```console
$ cat >furb161_3.py <<'# EOF'
try:
    bin("123").count("1")
except Exception as e:
    print(repr(e))
# EOF

$ python furb161_3.py
TypeError("'str' object cannot be interpreted as an integer")

$ ruff --isolated check --target-version py310 --preview --select FURB161 furb161_3.py --fix
Found 1 error (1 fixed, 0 remaining).

$ cat furb161_3.py
try:
    "123".bit_count()
except Exception as e:
    print(repr(e))

$ python furb161_3.py
AttributeError("'str' object has no attribute 'bit_count'")
```

### Version

ruff 0.9.9 (091d0af2a 2025-02-28)

### PR DESCRIPTION
**Pull request by VascoSch92**
The PR fixes #16457 .

Specifically, `FURB161` is marked safe, but the rule generates safe fixes only in specific cases. Therefore, we attempt to mark the fix as unsafe when we are not in one of these cases. 

For instances, the fix is marked as aunsafe just in case of strings (as pointed out in the issue). Let me know if I should change something.

### CODE REVIEW

**Review by MichaReiser — COMMENTED** [review]
Thanks for looking into this. Could you update the rule's documentation with a `## Fif safety` header and explain when the fix is safe (or isn't).

**Comment by VascoSch92** [comment]
> This PR doesn’t fully fix #16457. The point of that issue is that FURB161 should be unsafe by default, with a few exceptions. This PR keeps it safe by default, the only exception being string literals.

Thanks for the explanation. I approved the modification to make the rule unsafe if we can not determine if the argument of the `bin` method is of type `int` or `bool`

**Comment by dscorbett** [comment]
Using `ResolvedPythonType::from` would help catch more expressions than literals, like `-1` or `1 + 2`.

File: crates/ruff_linter/src/rules/refurb/rules/bit_count.rs [hunk 1]
```diff
@@ -27,6 +27,10 @@ use crate::fix::snippet::SourceCodeSnippet;
 /// y = 0b1111011.bit_count()
 /// ```
 ///
+/// ## Fix safety
+/// This rule's fix is marked as unsafe, as the `bit_count()` method can be used when the argument
+/// to the `bin()` is an instance of a type that implements the `__index__` and `bit_count` methods.
+///
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/bit_count.rs:33]: We also want to say explicitly when it is safe, since it's not always unsafe. Maybe something like this?

```suggestion
/// ## Fix safety
/// This rule's fix is marked as unsafe unless the argument to `bin` can be inferred as
/// an instance of a type that implements the `__index__` and `bit_count` methods.
///
```

I think we could also possibly drop the mention of `__index__` since we're always just calling `bit_count` right? Based on my reading of the `__index__` [docs](https://docs.python.org/3/reference/datamodel.html#object.__index__), it's actually a requirement for calling `bin` itself rather than a requirement to call `bit_count` as seems more relevant here.

File: crates/ruff_linter/src/rules/refurb/rules/bit_count.rs [hunk 2]
```diff
@@ -116,21 +120,23 @@ pub(crate) fn bit_count(checker: &Checker, call: &ExprCall) {
     }
     // Extract, e.g., `x` in `bin(x)`.
     let literal_text = checker.locator().slice(arg);
-
     // If we're calling a method on an integer, or an expression with lower precedence, parenthesize
-    // it.
-    let parenthesize = match arg {
+    // it. Moreover, we check if the fix is safe.
+    let (parenthesize, fix_is_safe): (bool, bool) = match arg {
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/bit_count.rs:125]: I think instead of returning a second `bool` here, you can just return an `Applicability` and use that with `Fix::applicable_edit` instead of branching on `fix_is_safe` down below.

File: crates/ruff_linter/src/rules/refurb/rules/bit_count.rs [hunk 3]
```diff
@@ -160,7 +166,7 @@ pub(crate) fn bit_count(checker: &Checker, call: &ExprCall) {
         | Expr::NoneLiteral(_)
         | Expr::EllipsisLiteral(_)
         | Expr::Attribute(_)
-        | Expr::Subscript(_) => false,
+        | Expr::Subscript(_) => (false, false),
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/bit_count.rs:169]: I can't highlight the line directly, but I think `Expr::BooleanLiteral` should also allow a safe edit, at least that's what it sounds like from the issue.

File: crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB161_FURB161.py.snap [hunk 4]
```diff
@@ -12,7 +12,7 @@ FURB161.py:6:9: FURB161 [*] Use of `bin(x).count('1')`
   |
   = help: Replace with `(x).bit_count()`
 
-ℹ Safe fix
+ℹ Unsafe fix
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB161_FURB161.py.snap:15]: This is a separate issue from the changes here, but I don't think `Expr::Name`s need to be parenthesized. Let's not modify this here, but I'm surprised to see `(x).bit_count` instead of `x.bit_count`.

File: crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB161_FURB161.py.snap [hunk 5]
```diff
@@ -116,7 +116,7 @@ FURB161.py:11:9: FURB161 [*] Use of `bin(0x10 + 0x1000).count('1')`
    |
    = help: Replace with `(0x10 + 0x1000).bit_count()`
 
-ℹ Safe fix
+ℹ Unsafe fix
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/snapshots/ruff_linter__rules__refurb__tests__FURB161_FURB161.py.snap:119]: This one is also a bit unfortunate because this is obviously an integer. I think this would be helped by `ResolvedPythonType::from` as @dscorbett suggested.

**Review by ntBre — CHANGES_REQUESTED** [review]
Thanks for working on this! Overall I think this is good, but we can simplify things a bit by using a fix `Applicability`, and then I think we can do a better job with type inference with `ResolvedPythonType::from`, specifically for `Expr::BinOp` (cases like `1 + 2`) and for `Expr::UnOp` (cases like `-1`).

If we extend the safe handling to `bool`, we may also be able to resolve expressions like `True or False`.

File: crates/ruff_linter/src/rules/refurb/rules/bit_count.rs (hunk 2 above)
Comment (VascoSch92) [reply crates/ruff_linter/src/rules/refurb/rules/bit_count.rs:125]: Done

**Comment by VascoSch92** [comment]
> Thanks for working on this! Overall I think this is good, but we can simplify things a bit by using a fix `Applicability`, and then I think we can do a better job with type inference with `ResolvedPythonType::from`, specifically for `Expr::BinOp` (cases like `1 + 2`) and for `Expr::UnOp` (cases like `-1`).
> 
> If we extend the safe handling to `bool`, we may also be able to resolve expressions like `True or False`.

Hey @ntBre 
I changed to use `ResolvedPythonType`. Let me know if I used it in the correct way ;-)

**Comment by ntBre** [comment]
Thanks, it looks good to me! 

Let's save this for a follow-up PR like the `Expr::Name` idea I mentioned above, but I think we can even do better than `ResolvedPythonType` to handle variable assignments too, like the `x = 10` case in the existing tests. There doesn't seem to be an existing `is_bool` function in our `typing` module, but we could easily add one similar to `is_int`:

https://github.com/astral-sh/ruff/blob/27a315b74095fa0d4dd83749b8a5ff567e06a38b/crates/ruff_python_semantic/src/analyze/typing.rs#L968-L971

You definitely don't have to work on this, just a couple of ideas if you're interested :)

I pushed two tiny tweaks:
- reverting a couple of lines that just moved around throughout the PR
- adding a little more context to the fix safety docs

I'll merge as soon as CI passes!

**Review by ntBre — APPROVED** [review]
