### PR TITLE
[`pylint`] - add fix for unary expressions in `PLC2801`

### LINKED ISSUE #9572: Bug in order of operations (PLC2801)
Hi all!

While updating from Ruff 0.1.11 to 0.1.13 I found a small bug in the newly created rule `PLC2801`.

I had the code:

```py
a = 2
b = -a.__sub__(1)
# b == -1
```

With the auto linter Ruff fixed this to:

```py
a = 2
b = -a - 1
# b == -3
```

The order of operations is changed, to fix this Ruff needs to add some parenthesis (`b = -(a-1)`). 

I have no experience with Rust, so I am not able to help, but I wanted to let you know of the issue. Thank you for making Rust! It's an absolutely amazing tool!!

### PR DESCRIPTION
**Pull request by diceroll123**
## Summary

Closes #9572

Don't go easy on this review!

## Test Plan

`cargo test`

### CODE REVIEW

**Comment by diceroll123** [comment]
I see now that the `set_fix` in both sides of the unary if statement can be moved out, but I won't touch it until after you've reviewed @charliermarsh

**Comment by charliermarsh** [comment]
@diceroll123 - Feel free to change, I won't get to this until tomorrow.

File: crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs [hunk 1]
```diff
@@ -156,8 +157,45 @@ pub(crate) fn unnecessary_dunder_call(checker: &mut Checker, call: &ast::ExprCal
         call.range(),
     );
 
-    if let Some(fixed) = fixed {
-        diagnostic.set_fix(Fix::safe_edit(Edit::range_replacement(fixed, call.range())));
+    if let Some(mut fixed) = fixed {
+        let is_in_unary = checker
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs:161]: The section here could use a comment explaining on why we're doing what we're doing below because it's not immediately obvious what it is about.

File: crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs [hunk 2]
```diff
@@ -156,8 +157,45 @@ pub(crate) fn unnecessary_dunder_call(checker: &mut Checker, call: &ast::ExprCal
...
+            .is_some_and(|parent| matches!(parent, Expr::UnaryOp(ast::ExprUnaryOp { .. })));
+
+        if is_in_unary {
+            // find the first ")" before our dunder method
+            let rparen =
+                SimpleTokenizer::starts_at(value.as_ref().end(), checker.locator().contents())
+                    .find(|token| {
+                        token.kind == SimpleTokenKind::RParen && token.start() < call.end()
+                    });
+
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs:173]: What happens if we have `a.__sub__(((((b)))))`?


You can use `call.arguments.start` (or `end`) to get the parentheses offsets of the call expression and retain those.

File: crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs [hunk 3]
```diff
@@ -156,8 +157,45 @@ pub(crate) fn unnecessary_dunder_call(checker: &mut Checker, call: &ast::ExprCal
         call.range(),
     );
 
-    if let Some(fixed) = fixed {
-        diagnostic.set_fix(Fix::safe_edit(Edit::range_replacement(fixed, call.range())));
+    if let Some(mut fixed) = fixed {
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs:160]: I wonder if the fix produces invalid code if you have

```python
4.__sub__(
    3 
    + 
    4
)
```

What i understand is that we fix this to

```python
a -
    3
    +
    4
```

which Python doesn't like very much

File: crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs [hunk 4]
```diff
@@ -156,8 +157,45 @@ pub(crate) fn unnecessary_dunder_call(checker: &mut Checker, call: &ast::ExprCal
...
+        let is_in_unary = checker
+            .semantic()
+            .current_expression_parent()
+            .is_some_and(|parent| matches!(parent, Expr::UnaryOp(ast::ExprUnaryOp { .. })));
+
+        if is_in_unary {
+            // find the first ")" before our dunder method
+            let rparen =
+                SimpleTokenizer::starts_at(value.as_ref().end(), checker.locator().contents())
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs:169]: Can we start after the `attribute` to reduce the text that need to be searched?

**Review by MichaReiser — COMMENTED** [review]
Would it be possible to generalize the fix to correctly handle operator precedence in general. There are some more cases mentioned on the linked Issue that this PR doesn't address.

File: crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs (hunk 4 above)
Comment (diceroll123) [reply crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs:169]: Can't start after the value in this case.

We're looking for this,

```
(-a).__sub__(1)
###^
```

and the difference between

`(-a).__sub__(1)` and `-a.__sub__(1)`

It could possibly be optimized another way though, perhaps by checking the tokens between `value` and the first `Dot` 🤔

**Comment by diceroll123** [comment]
Made some tweaks!

First and foremost: the fix is marked as unsafe. This could be conditional with more type logic in a future iteration, for sure.

The arguments within the dunder method call will now stay in parentheses if it's anything more complex than a literal/name/attribute. I'm sure that logic may be fine to expand into other expression types.

So, this example:

```python
print(a.__sub__(
    3
    +
    4
))
```

now turns into 
```python
print(a - (3
    +
    4
))
```

Looking forward to opinions on improving it further! 😄

File: crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs [hunk 5]
```diff
@@ -124,21 +124,30 @@ pub(crate) fn unnecessary_dunder_call(checker: &mut Checker, call: &ast::ExprCal
...
-                fixed = Some(format!(
-                    "{} {} {}",
-                    checker.locator().slice(value.as_ref()),
-                    replacement,
-                    checker.locator().slice(arg),
-                ));
+                let value_slice = checker.locator().slice(value.as_ref());
+                let arg_slice = checker.locator().slice(arg);
+
+                if arg.is_attribute_expr() || arg.is_name_expr() || arg.is_literal_expr() {
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs:130]: I think we can exclude some more expressions here

* Calls
* Unary expressions 
* Lambda
* If expressions (I think)? 
* Dict / Set / List / Tuple and all comprehension variants (everything with parentheses)
* Generators
* Subscripts
* Starred (I think)
* Slices?

**Review by MichaReiser — APPROVED** [review]
Sorry for the late review.  The `uv` release took a lot of attention recently. 

This is an excellent improvement. I think there are a few more situations where adding the parentheses isn't strictly necessary. You might want to move the logic into its own function to avoid coding it twice.

File: crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs (hunk 5 above)
Comment (diceroll123) [reply crates/ruff_linter/src/rules/pylint/rules/unnecessary_dunder_call.rs]: Reworked it, added all of the above except Unary (because that's what got us this PR in the first place hah)
