### PR TITLE
[red-knot] Empty tuple is always-falsy

### LINKED ISSUE #17202: [red-knot] `is_subtype_of` no longer implies `is_assignable_to` for all `Type::Tuple` types
Failing property-test run listed here: https://github.com/astral-sh/ruff/actions/runs/14265011645

### PR DESCRIPTION
**Pull request by sharkdp**
## Summary

Fix assignability of `tuple[()]` to `AlwaysFalsy`.

closes #17202 

## Test Plan

Ran the property tests for a while

### CODE REVIEW

File: crates/red_knot_python_semantic/src/types.rs [hunk 1]
```diff
@@ -1071,9 +1071,13 @@ impl<'db> Type<'db> {
...
-            (Type::Tuple(_), _) => KnownClass::Tuple
-                .to_instance(db)
-                .is_assignable_to(db, target),
+            (Type::Tuple(_), _)
+                if KnownClass::Tuple
+                    .to_instance(db)
+                    .is_assignable_to(db, target) =>
+            {
+                true
+            }
```
Comment (sharkdp) [inline crates/red_knot_python_semantic/src/types.rs:1080]: The difference is that we now allow a fall-through to the catch-all "self is subtype of target" branch.

**Comment by carljm** [comment]
I have a vague memory of intentionally making the opposite decision here.

I think the key question we need to ensure we are answering consistently is, do instances of subtypes of the built-in `tuple` type also inhabit our `Type::Tuple` types? My memory is that in other places we assume they can, but I would have to double-check. If they do, then we cannot say that the empty `Type::Tuple` is falsy, since a subclass of `tuple` could change this.

**Review by AlexWaygood — APPROVED** [review]

**Comment by AlexWaygood** [comment]
> I have a vague memory of intentionally making the opposite decision here.

Ah yes, https://github.com/astral-sh/ruff/issues/15528 is still unresolved... I have a long reply in my head I've been meaning to write up there for a while :-) maybe I should set an explicit goal for myself to do that on Monday...

Anyway, I think the change to the code here is correct even if we disagree on the assertion being made in the mdtest!

**Comment by carljm** [comment]
Yes, I think the code change is correct, but we should add a TODO comment above the assertions (and maybe also above similar assertions for subtyping, if we have those already?) that we either need to special-case enforcement of Liskov on `__bool__` and `__len__` for tuple subclasses, or stop assuming that empty tuples are falsy and non-empty tuples are truthy.
