### PR TITLE
[red-knot] Resolve function annotations before adding function symbol

### LINKED ISSUE #13069: Red Knot panics when function return type and function name are the same
Minimal Repro

```python
def x(self) -> x:
    ...
```

The original code from the pandas project

```python
    # https://github.com/python/mypy/issues/4125
    # error: Signature of "type" incompatible with supertype "BaseMaskedDtype"
    # @property
    def type(self) -> type:  # type: ignore[override]
        return np.bool_
```

https://github.com/pandas-dev/pandas/blob/0c24b20bd9cd743bd5f5afceb1a6fef54a2dbdc1/pandas/core/arrays/boolean.py#L76-L78

### PR DESCRIPTION
**Pull request by dylwil3**
This PR has the `SemanticIndexBuilder` visit function definition annotations before adding the function symbol/name to the builder.

For example, the following snippet no longer causes a panic:

```python
def bool(x) -> bool:
    Return True
```

Note: This fix changes the ordering of the global symbol table.

Closes #13069

### CODE REVIEW

**Comment by dylwil3** [comment]
I also changed the order that the `TypeInferenceBuilder` resolves function definitions in the same way, but I'm not sure if that was relevant.

**Comment by AlexWaygood** [comment]
I believe this means that we'd understand the return annotation as referring to `builtins.bool` rather than referring to the first-party function `bool`. That mimics the evaluation order at runtime:

```pycon
>>> def bool() -> bool:
...   ...
...   
>>> bool.__annotations__
{'return': <class 'bool'>}
>>> bool.__annotations__['return'] is bool
False
```

And it also seems to be what pyright does: https://pyright-play.net/?code=CYUwZgBARg9jA2AKAlBAtAPmneAuAUBEQHSn74BOIAbiAIbwD6ALgJ4AOIisCylN9Jm07ccKPvgAeEALwQAKhQCuIKbOwIU-WgxYcuk5EA

But interestingly, mypy just understands the return annotation as being a forward reference to the function that the return annotation is part of: https://mypy-play.net/?mypy=latest&python=3.12&gist=6dd88ac3463dc662ab1a50ed0456685c

**Comment by dylwil3** [comment]
>I believe this means that we'd understand the return annotation as referring to `builtins.bool` rather than referring to the first-party function `bool`. That mimics the evaluation order at runtime

That feels right to me - it was the same experiment as yours that motivated the reordering.

P.S. Not sure what the deal is with CodSpeed? I don't think I touched anything linter-related... I hope!

**Comment by AlexWaygood** [comment]
Nah, codspeed has been very unreliable recently :(

Best not to worry about it — sorry for the bother!

**Comment by MichaReiser** [comment]
Wow nice, thank you. Could we add a test where the function and the return type name aren't a built in (e.g x as in the linked issue). Just to make sure the fix doesn't rely on any built in behavior

**Comment by dylwil3** [comment]
> Wow nice, thank you. Could we add a test where the function and the return type name aren't a built in (e.g x as in the linked issue). Just to make sure the fix doesn't rely on any built in behavior

Done!

File: crates/red_knot_python_semantic/src/semantic_index/builder.rs [hunk 1]
```diff
@@ -426,6 +412,20 @@ where
...
+
+                // The default value of the parameters needs to be evaluated in the
+                // enclosing scope.
+                for default in function_def
+                    .parameters
+                    .iter_non_variadic_params()
+                    .filter_map(|param| param.default.as_deref())
+                {
+                    self.visit_expr(default);
+                }
```
Comment (carljm) [inline crates/red_knot_python_semantic/src/semantic_index/builder.rs:428]: While we're fixing the order of things here, I think this also belongs above the definition of the function name:

```
>>> def bool(x = bool):
...     return x
...
>>> bool()
<class 'bool'>
```

Would you be open to also adding a test for this and fixing the ordering?

File: crates/red_knot_workspace/resources/test/corpus/25_func_annotations_same_name.py [hunk 2]
```diff
@@ -0,0 +1,11 @@
...
+    return True
+
+
+class MyClass: ...
+
+
+def MyClass() -> MyClass: ...
+
+
+def x(self) -> x: ...
```
Comment (carljm) [inline crates/red_knot_workspace/resources/test/corpus/25_func_annotations_same_name.py:11]: In an ideal world, I'd prefer to have inference tests that validate we get the semantics right, rather than just corpus tests that validate we don't panic.

But at the moment it'd be a pain to write those inference tests; we don't have `Call` support yet, so you can't easily get access to the return type of a function by e.g. doing `y = x()` and then checking the type of the `y` symbol, you'd have to instead scrabble through the AST to find the return annotation expression node, and then assert on its type. So this is more just a note for future, not something that needs to be changed in this PR.

**Review by carljm — APPROVED** [review]
This looks like a clear improvement as-is, though if you're willing to also fix up the default-value issue as well, that'd be great!

Thank you!!

File: crates/red_knot_python_semantic/src/semantic_index/builder.rs (hunk 1 above)
Comment (dylwil3) [reply crates/red_knot_python_semantic/src/semantic_index/builder.rs:423]: Done! Added another "no panic" test and then a mostly copy-pasted unit test that doesn't really check for much but is a baby step towards the sort of thing you mentioned in your other comment.

File: crates/red_knot_python_semantic/src/semantic_index.rs [hunk 3]
```diff
@@ -616,6 +616,44 @@ def f(a: str, /, b: str, c: int = 1, *args, d: int = 2, **kwargs):
         }
     }
 
+    #[test]
+    fn function_parameter_same_name_default() {
```
Comment (carljm) [inline crates/red_knot_python_semantic/src/semantic_index.rs:620]: Does this test fail before this PR? Just looking at the test, it doesn't seem to me that this test would be impacted by the bug we are fixing in this PR.

The test I was thinking of would go in `types/infer.rs`, not here, and would assert on the inferred type for the return (or default) expression. The test `local_inference` in that file is an example of an existing test that finds an AST node and then asserts on its type. But like I said, I wasn't necessarily expecting we'd add such a test in this PR.

Unless I'm missing something and this test does actually check for this bug, I would say let's remove this test. If you want to try your hand at adding the above style of test, that's great but not required!

File: crates/red_knot_python_semantic/src/semantic_index/builder.rs (hunk 1 above)
Comment (carljm) [reply crates/red_knot_python_semantic/src/semantic_index/builder.rs:423]: Thank you! As I mentioned in my other comment, I think the new copy-pasted test doesn't add enough value to be worth adding right now, so we can remove it. The inference test we eventually want would be at the type-inference level, not the semantic level. Everything else looks great!

**Comment by carljm** [comment]
Awesome work, thank you!!
