### PR TITLE
[`flake8-use-pathlib`] Fix `PTH123` false positive when `open` is passed a file descriptor from a function call

### LINKED ISSUE #17691: `PTH123` wrongly suggests `Path.open()` for file descriptors, only sometimes
### Summary

```python
fp = open(1)
def f() -> int:
    return 1
fp = open(f())
def g(x: int) -> None:
    open(x)
r = 1
fp = open(r)
```
```zsh
$ ruff --version
ruff 0.11.7
$ ruff check --isolated --select PTH123 t.py
t.py:4:6: PTH123 `open()` should be replaced by `Path.open()`
  |
2 | def f() -> int:
3 |     return 1
4 | fp = open(f())
  |      ^^^^ PTH123
5 | def g(x: int) -> None:
6 |     open(x)
  |

Found 1 error.
```

This doesn't look like a regression of #12871. But I guess the fix (#13616) somehow didn't cover the case where the argument of `open()` is an `int` return value?

### Version

0.11.7

### PR DESCRIPTION
**Pull request by LaBatata101**
## Summary
Includes minor changes to the semantic type inference to help detect the return type of function call.

Fixes #17691

## Test Plan

Snapshot tests

### CODE REVIEW

**Comment by LaBatata101** [comment]
Why the CI failed here?

**Comment by AlexWaygood** [comment]
> Why the CI failed here?

I re-ran it and it passed. I assume it's just a fluke :-)

File: crates/ruff_linter/src/rules/flake8_use_pathlib/rules/replaceable_by_pathlib.rs [hunk 1]
```diff
@@ -190,3 +193,28 @@ fn is_file_descriptor(expr: &Expr, semantic: &SemanticModel) -> bool {
...
+    let Some(name) = get_name_expr(expr) else {
+        return false;
+    };
+
+    let Some(binding) = semantic.only_binding(name).map(|id| semantic.binding(id)) else {
+        return false;
+    };
+
+    typing::is_bytes(binding, semantic)
+}
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/flake8_use_pathlib/rules/replaceable_by_pathlib.rs:212]: Can we add a few test cases with byte strings? This looks right to me, but I don't think we have any tests exercising it.

**Review by ntBre — APPROVED** [review]
Thanks, this looks great to me! Let's just add a few test cases for bytestrings, but otherwise this is good to go.

File: crates/ruff_linter/src/rules/flake8_use_pathlib/rules/replaceable_by_pathlib.rs (hunk 1 above)
Comment (LaBatata101) [reply crates/ruff_linter/src/rules/flake8_use_pathlib/rules/replaceable_by_pathlib.rs:212]: I've added the test cases

Comment (ntBre) [reply crates/ruff_linter/src/rules/flake8_use_pathlib/rules/replaceable_by_pathlib.rs:212]: Looks great, thanks!
