### PR TITLE
`[flake8-bandit]` Don't flag `BaseLoader`/`CBaseLoader` as unsafe in preview (`S506`)

### LINKED ISSUE #13604: [flake8-bandit/S506] Dont report violation when using BaseLoader
From https://pyyaml.org/wiki/PyYAMLDocumentation
- Loader supports all predefined tags and may construct an arbitrary Python object. Therefore it is not safe to use Loader to load a document received from an untrusted source. By default, the functions scan, parse, compose, construct, and others use Loader.
- SafeLoader(stream) supports only standard YAML tags and thus it does not construct class instances and probably safe to use with documents received from an untrusted source. The functions safe_load and safe_load_all use SafeLoader to parse a stream.
- BaseLoader(stream) does not resolve or support any tags and construct only basic Python objects: lists, dictionaries and Unicode strings.

For our project we are using the Baseloader, and do not want to use safeLoader, as this would not leave integer values as strings.  The baseloader is not the unsafe FullLoader, and should not be flagged as an exception to S506.

Code to reproduce:
```python
with open('testfile.yaml') as fhandle:
  loader_yaml = yaml.load(fhandle, Loader=yaml.Baseloader)
```

Ruff setting: [select = ""]
Ruff version: 0.6.8

### PR DESCRIPTION
**Pull request by o1x3**
## Summary

`yaml.BaseLoader` and `yaml.CBaseLoader` use `BaseConstructor` + `BaseResolver`, which do not resolve tags or construct arbitrary Python objects — they only produce basic types (lists, dicts, strings). They are strictly *less capable* than `SafeLoader`, not less safe.

Currently, S506 flags `yaml.load(..., Loader=yaml.BaseLoader)` as unsafe. This is a false positive.

This PR adds `BaseLoader` and `CBaseLoader` (the C-accelerated variant from `yaml.cyaml`) to the list of recognized safe loaders, gated behind preview mode per maintainer guidance.

Closes #13604

## Test Plan

- Added test fixtures covering `BaseLoader`/`CBaseLoader` via all import paths (`yaml.*`, `yaml.loader.*`, `yaml.cyaml.*`, aliased imports)
- Added preview diff test case using `assert_diagnostics_diff!` to verify BaseLoader diagnostics are suppressed only in preview mode
- Verified with `cargo test -p ruff_linter`, `cargo clippy`, and `uvx prek run -a`

### CODE REVIEW

File: crates/ruff_linter/src/preview.rs [hunk 1]
```diff
@@ -292,3 +292,8 @@ pub(crate) const fn is_plural_ngettext_check_enabled(settings: &LinterSettings)
 pub(crate) const fn is_resolve_string_annotation_pyi041_enabled(settings: &LinterSettings) -> bool {
     settings.preview.is_enabled()
 }
+
+// https://github.com/astral-sh/ruff/issues/13604
```
Comment (ntBre) [inline crates/ruff_linter/src/preview.rs]: We usually put the PR link here:


```suggestion
// https://github.com/astral-sh/ruff/pull/23510
```
