### PR TITLE
Fix F811 false positive for class methods

### LINKED ISSUE #24915: `redefined-while-unused` (`F811`) - false positive on method with the same name as an unused import
## [Playground](https://play.ruff.rs/d24d7803-ab82-4945-90ef-485da3d8712c)

```py
from foo import bar # error: F401 (correct)

class Foo:
    def bar(self): ... # error: F811 (false positive)

def bar(): ... # error: F811 (correct)
```
```
Redefinition of unused `bar` from line 1: `bar` redefined here (F811) [Ln 4, Col 9]
Redefinition of unused `bar` from line 1: `bar` redefined here (F811) [Ln 6, Col 5]
```

`Foo.bar` is not shadowning the top-level `bar` so the error should not be reported

### Version

v0.15.12

### PR DESCRIPTION
**Pull request by denyszhak**
Fixes #24915 

## Summary

Avoid reporting F811 when a class scope method or attribute has the same name as an unused import.

## Test Plan

Regression test added.

### CODE REVIEW

**Comment by denyszhak** [comment]
Ecosystem results are expected. The two removed F811 diagnostics match the fix. The added RUF100 is a stale `noqa: F811` that became unused after the false positive removed.

File: crates/ruff_linter/src/rules/pyflakes/rules/redefined_while_unused.rs [hunk 1]
```diff
@@ -132,6 +132,12 @@ pub(crate) fn redefined_while_unused(checker: &Checker, scope_id: ScopeId, scope
                     }
                 }
             } else {
+                // A binding in a class body creates a class attribute; it doesn't rebind names
+                // in an enclosing module or function scope.
+                if scope.kind.is_class() {
+                    continue;
+                }
+
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pyflakes/rules/redefined_while_unused.rs:140]: Ideally, we'd still flag redefinitions within the class:


```py
"""Regression test for: https://github.com/astral-sh/ruff/issues/24915"""

from foo import bar


class Foo:
    def bar(self): ...
    def bar(self): ... # error


def bar(): ...
```

Comment (denyszhak) [reply crates/ruff_linter/src/rules/pyflakes/rules/redefined_while_unused.rs:140]: This is current behaviour, the check was only missing from the test.

**Review by MichaReiser — APPROVED** [review]
Thank you
