### PR TITLE
Apply NFKC normalization to unicode identifiers in the lexer

### LINKED ISSUE #5003: F821 False Positive when using equivalent script characters
Bug: Ruff incorrectly treats characters from other scripts as different, resulting in a F821 undefined name.
This is possibly related to #942.

```python
𝒞 = 500
print(𝒞)
print(C + 𝒞)  # ruff says `C` isn't defined
print(C / 𝒞)
print(C == 𝑪 == 𝒞 == 𝓒 == 𝕮)  # ruff says `C`, `𝑪`, ... isn't defined
```
The above code, albeit somewhat funky, is actually perfectly valid python code and runs successfully, due to how Python handles different script characters (it treats equivalent characters from different scripts as the same at runtime).

However, it appears that ruff (somewhat understandably) doesn't like this, and errors stating that `C`, etc. isn't defined.

Ruff should realise that these characters are equivalent at runtime, and not error stating that they're undefined.

### PR DESCRIPTION
**Pull request by AlexWaygood**
## Summary

A second attempt to fix #5003, _hopefully_ without the performance problems that https://github.com/astral-sh/ruff/pull/10381 suffered from.

Python [applies NFKC normalization to identifiers that use unicode characters](https://docs.python.org/3/reference/lexical_analysis.html#identifiers). That means that F821 should not be emitted if ruff encounters the following snippet (but on `main`, it is), as from Python's perspective, these are all the same identifier:

```py
𝒞 = 500
print(𝒞)
print(C + 𝒞)  # ruff says `C` isn't defined
print(C / 𝒞)
print(C == 𝑪 == 𝒞 == 𝓒 == 𝕮)  # ruff says `C`, `𝑪`, ... isn't defined
```

This PR fixes that false positive by NFKC-normalizing identifers as they are encountered in the lexer.

## Test Plan

`cargo test`

### CODE REVIEW

File: crates/ruff_python_formatter/src/expression/expr_name.rs [hunk 1]
```diff
@@ -11,16 +11,11 @@ pub struct FormatExprName;
...
     fn fmt_fields(&self, item: &ExprName, f: &mut PyFormatter) -> FormatResult<()> {
-        let ExprName { id, range, ctx: _ } = item;
-
-        debug_assert_eq!(
-            id.as_str(),
-            f.context()
-                .source_code()
-                .slice(*range)
-                .text(f.context().source_code())
-        );
```
Comment (AlexWaygood) [inline crates/ruff_python_formatter/src/expression/expr_name.rs:22]: This debug assertion no longer passes as-is, since the AST node holds the NFKC-normalized identifier, whereas the source code gives us the original identifier.

If we think this assertion is valuable, we could put it in a `#[cfg(test)]` block, make the `unicode-normalization` crate a test-dependency of the formatter, and assert that the NFKC-normalized source code is equal to the AST `id`. I don't know if that's really worth it, though?

File: crates/ruff_python_parser/src/lexer.rs [hunk 2]
```diff
@@ -169,7 +170,7 @@ impl<'source> Lexer<'source> {
     }
 
     /// Lex an identifier. Also used for keywords and string/bytes literals with a prefix.
-    fn lex_identifier(&mut self, first: char) -> Result<Tok, LexicalError> {
+    fn lex_identifier(&mut self, first: char, ascii_first_char: bool) -> Result<Tok, LexicalError> {
```
Comment (dhruvmanila) [inline crates/ruff_python_parser/src/lexer.rs:173]: nit: maybe `is_first_char_ascii` / `is_first_ascii`?

File: crates/ruff_python_parser/src/lexer.rs [hunk 3]
```diff
@@ -1585,12 +1591,13 @@ fn is_unicode_identifier_start(c: char) -> bool {
 
 // Checks if the character c is a valid continuation character as described
 // in https://docs.python.org/3/reference/lexical_analysis.html#identifiers
-fn is_identifier_continuation(c: char) -> bool {
+fn is_identifier_continuation(c: char, ascii_only_identifier: &mut bool) -> bool {
```
Comment (dhruvmanila) [inline crates/ruff_python_parser/src/lexer.rs:1594]: nit: sorry for name recommendations but maybe `is_identifier_ascii_only`?

**Review by dhruvmanila — COMMENTED** [review]
This is great with such a minimal change. Can you please write / update documentation around this change? Maybe the `lex_identifier` or the `Name` token?

It's good to go from my side but I'll let @MichaReiser give the final approval.

File: crates/ruff_python_parser/src/lexer.rs (hunk 2 above)
Comment (AlexWaygood) [reply crates/ruff_python_parser/src/lexer.rs]: I went for `first_char_is_ascii` in https://github.com/astral-sh/ruff/pull/10412/commits/d785be50606df110d848606165e2f7a9aa406835

File: crates/ruff_python_parser/src/lexer.rs (hunk 3 above)
Comment (AlexWaygood) [reply crates/ruff_python_parser/src/lexer.rs]: I went for `identifier_is_ascii_only` in https://github.com/astral-sh/ruff/pull/10412/commits/d785be50606df110d848606165e2f7a9aa406835

**Comment by AlexWaygood** [comment]
> Can you please write / update documentation around this change? Maybe the `lex_identifier` or the `Name` token?

Thanks! I had a go at writing some docs in https://github.com/astral-sh/ruff/pull/10412/commits/d785be50606df110d848606165e2f7a9aa406835 -- how does that look to you?

**Comment by dhruvmanila** [comment]
> Thanks! I had a go at writing some docs in [d785be5](https://github.com/astral-sh/ruff/commit/d785be50606df110d848606165e2f7a9aa406835) -- how does that look to you?

Looks good. Thank you!

File: crates/ruff_python_parser/src/token.rs [hunk 4]
```diff
@@ -16,6 +16,9 @@ pub enum Tok {
     /// Token value for a name, commonly known as an identifier.
     Name {
         /// The name value.
+        ///
+        /// Unicode names are NFKC-normalized by the lexer,
+        /// matching [the behaviour of Python's lexer](https://docs.python.org/3/reference/lexical_analysis.html#identifiers)
         name: Box<str>,
```
Comment (charliermarsh) [inline crates/ruff_python_parser/src/token.rs:22]: I was eventually hoping to remove all owned data from the lexer tokens (e.g., prior to this change, we could've conceivably removed this field altogether; if we remove more similar fields from other tokens, we can eventually reduce the size of the `Tok` enum, which could be great for performance). This now precludes us from doing so. But I don't have enough context on the future design of the lexer-parser to know if it matters.

**Review by charliermarsh — COMMENTED** [review]
Looks reasonable to me, I'll defer to Micha and Dhruv to approve.

File: crates/ruff_linter/resources/test/fixtures/pyflakes/F821_28.py
Comment (MichaReiser) [inline crates/ruff_linter/resources/test/fixtures/pyflakes/F821_28.py:1]: Nice. Could you add a trimmed down version of this as a lexer or parser test?

File: crates/ruff_python_formatter/src/expression/expr_name.rs (hunk 1 above)
Comment (MichaReiser) [reply crates/ruff_python_formatter/src/expression/expr_name.rs:22]: I think it's fine to remove it.

File: crates/ruff_python_parser/src/token.rs (hunk 4 above)
Comment (MichaReiser) [reply crates/ruff_python_parser/src/token.rs:22]: I think we can still accomplish this and `Name` isn't the only token that must return the parsed value (e.g. FStrings etc).

What I have in mind is to:

* Replace `Tok` with `TokenKind` (that holds no data)
* Add a `take_value()` method on `Lexer` that "takes" the current value (`enum` over `Name`, `Int` etc.). 

This design also fits better into our new parser that already does exactly this internally (except that it "takes" the value from `Tok`). The advantage of this is that we only pay the overhead of reading or writting a value if it is a value token (and we're interested in the value).

File: crates/ruff_python_parser/src/lexer.rs [hunk 5]
```diff
@@ -169,7 +170,11 @@ impl<'source> Lexer<'source> {
     }
 
     /// Lex an identifier. Also used for keywords and string/bytes literals with a prefix.
-    fn lex_identifier(&mut self, first: char) -> Result<Tok, LexicalError> {
+    fn lex_identifier(
+        &mut self,
+        first: char,
+        first_char_is_ascii: bool,
```
Comment (MichaReiser) [inline crates/ruff_python_parser/src/lexer.rs:176]: Nit: I would call `first.is_ascii()` inside of the method. It avoids leaking the abstraction and the cost of determining if a character is ascii is a simple range comparision that might as well be cheaper than passing a value to a function call (requires pushing and poping from the stack).

File: crates/ruff_python_parser/src/lexer.rs [hunk 6]
```diff
@@ -197,11 +202,18 @@ impl<'source> Lexer<'source> {
...
+        // This is important because Python applies NFKC normalization to
+        // identifiers: https://docs.python.org/3/reference/lexical_analysis.html#identifiers.
+        // We need to therefore do the same in our lexer, but applying NFKC normalization
+        // unconditionally is extremely expensive. If we know an identifier is ASCII-only,
+        // (by far the most common case), we can skip NFKC normalization of the identifier.
+        let mut is_ascii = first_char_is_ascii;
+        self.cursor
+            .eat_while(|c| is_identifier_continuation(c, &mut is_ascii));
+
+        let keyword = match self.token_text() {
```
Comment (MichaReiser) [inline crates/ruff_python_parser/src/lexer.rs:216]: Nit: We can skip the entire `match` for `non-ascii` text. The old code didn't do this to avoid branching but we might as well do it now, where we branch on the flag anyway.

**Review by MichaReiser — APPROVED** [review]

**Comment by AlexWaygood** [comment]
Thanks all!
