### PR TITLE
[`pyflakes`] Fix infinite loop with unused local import in `__init__.py` (`F401`)

### LINKED ISSUE #12897: [Infinite loop] Package-relative import issue with module `__all__` when using F401 and F822 with the preview option
This took a while to minimise, hopefully it is indicative of a real issue!

There's some setup involved, so you can use the following ``reproducer.py`` in an empty directory.

```python
# reproducer.py
from pathlib import Path


def write(path, text):
    path.write_text(text, encoding="utf-8")


BUG = """\
__all__ = ('Spam',)


class Spam:
    def __init__(self) -> None:
        from bug.lobster_thermidor import Ham
"""

MOD_INIT = Path('bug/__init__.py')
MOD_LOBSTER = Path('bug/lobster_thermidor.py')
MOD_INIT.parent.mkdir(exist_ok=True)
BUG_FILE = Path('bug.py')
write(MOD_INIT, BUG)
write(BUG_FILE, BUG)
write(MOD_LOBSTER, 'Ham = 1\n')
```

This is the same as the following structure:

```
bug.py
bug/
  -> __init__.py
  -> lobster_thermidor.py
```

In both ``bug.py`` and ``bug/__init__.py`` we have:

```python
__all__ = ('Spam',)


class Spam:
    def __init__(self) -> None:
        from bug.lobster_thermidor import Ham
```

In ``lobster_thermidor.py`` we have:

```python
Ham = 1
```

The issue is then straightforwards to reproduce:

```ps1con
PS> ruff -V
ruff 0.5.7
PS> ruff check --isolated --select F401,F822 --preview --fix bug.py
Found 1 error (1 fixed, 0 remaining).
PS> ruff check --isolated --select F401,F822 --preview --fix bug/

error: Failed to converge after 100 iterations.

This indicates a bug in Ruff. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BInfinite%20loop%5D

...quoting the contents of `bug\__init__.py`, the rule codes F401, F822, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

bug\__init__.py:1:20: F822 Undefined name `Ham` in `__all__`
  |
1 | __all__ = ('Spam', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham
', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ha
m', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'Ham', 'H
am', 'Ham', 'Ham', 'Ham', 'Ham',)
  |                    ^^^^^ F822
  |
[ ... 1023(!!!) lines of output elided ... ]

Found 201 errors (100 fixed, 101 remaining).
[*] 1 fixable with the `--fix` option.
```

This only reproduces with the ``--preview`` option. Clearly there is a bad recursion or loop bug somewhere. If it is an topic for discussion though, I don't think an auto-fix should add an import to ``__all__`` -- the correct solution (as observed in ``bug.py``) is to remove the import.

Thanks, and please let me know if any further information is needed,
Adam

### PR DESCRIPTION
**Pull request by ntBre**
## Summary

This fixes the infinite loop reported in #12897, where an `unused-import` that is undefined at the scope of `__all__` is "fixed" by adding it to `__all__` repeatedly. These changes make it so that only imports in the global scope will be suggested to add to `__all__` and the unused local import is simply removed.

## Test Plan

Added a CLI integration test that sets up the same module structure as the original report

Closes #12897

### CODE REVIEW

File: crates/ruff_linter/src/rules/pyflakes/rules/unused_import.rs [hunk 1]
```diff
@@ -329,6 +336,7 @@ pub(crate) fn unused_import(checker: &Checker, scope: &Scope, diagnostics: &mut
             import,
             range: binding.range(),
             parent_range: binding.parent_range(checker.semantic()),
+            in_global_scope,
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pyflakes/rules/unused_import.rs:339]: I'm inclined to store the `ScopeId` instead. It seems more generally useful and is cheap as well

**Review by MichaReiser — COMMENTED** [review]
I'd prefer if we can move the test closer to the rule rather than making it a CLI tests. We only use CLI tests for features that can't be tested otherwise but we prefer unit tests or tool specific integration tests for everything else because they're faster to run, easier to find, and there's less code "between" the test and the implementation if something goes wrong. 

I'm requesting review from @AlexWaygood to review the rule behavior change.

File: crates/ruff_linter/src/rules/pyflakes/rules/unused_import.rs (hunk 1 above)
Comment (AlexWaygood) [reply crates/ruff_linter/src/rules/pyflakes/rules/unused_import.rs:339]: And it is more strongly typed/more readable than passing around a boolean value

**Comment by AlexWaygood** [comment]
Nice diagnosis! The change to the rule's semantics look correct to me.

It's nice that this is a targeted fix as well. I think I tried to fix this a while back, but made the mistake of trying to untangle some of the more spaghetti-code-like parts of this rule at the same time, and got bogged down in a tricky refactor that was hard to pull off.

I agree that I think it should be possible to test this fix using fixtures rather than a CLI integration test. We already have several mock packages setup here that we use for testing F401; can we create another mock package for this scenario? <https://github.com/astral-sh/ruff/tree/main/crates/ruff_linter/resources/test/fixtures/pyflakes>. The actual tests that use the fixtures are here: https://github.com/astral-sh/ruff/blob/main/crates/ruff_linter/src/rules/pyflakes/mod.rs

File: crates/ruff_linter/resources/test/fixtures/pyflakes/F401_33/__init__.py [hunk 2]
```diff
@@ -0,0 +1,6 @@
+__all__ = ('Spam',)
```
Comment (AlexWaygood) [inline crates/ruff_linter/resources/test/fixtures/pyflakes/F401_33/__init__.py:1]: (you'll have to update the snapshots if you accept this change)

```suggestion
"""Regression test for https://github.com/astral-sh/ruff/issues/12897"""

__all__ = ('Spam',)
```

**Comment by ntBre** [comment]
Thank you both for the suggestions! For some reason I immediately assumed that multiple files meant I needed an integration test, but these examples were very helpful. I first made the unit test changes on `main` to make sure they triggered the original error before applying them here. And using the `ScopeId` is much nicer, thank you!

File: crates/ruff_linter/src/rules/pyflakes/mod.rs [hunk 3]
```diff
@@ -286,6 +286,34 @@ mod tests {
         assert_messages!(snapshot, diagnostics);
     }
 
+    #[test_case(Rule::UnusedImport, Path::new("F401_33/__init__.py"))]
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/pyflakes/mod.rs:289]:
```suggestion
    // Regression test for https://github.com/astral-sh/ruff/issues/12897
    #[test_case(Rule::UnusedImport, Path::new("F401_33/__init__.py"))]
```

**Review by AlexWaygood — APPROVED** [review]
Very nice!

File: crates/ruff_linter/resources/test/fixtures/pyflakes/F401_33/__init__.py (hunk 2 above)
Comment (ntBre) [reply crates/ruff_linter/resources/test/fixtures/pyflakes/F401_33/__init__.py:1]: Oops, good call. I'll accept these and rerun.

**Review by MichaReiser — APPROVED** [review]
