### PR TITLE
[red-knot] Fix assertion for invalid match pattern

### LINKED ISSUE #14305: [red-knot] Asserts on invalid match pattern
Red knot currently runs into a failing debug assertion on the following invalid match pattern:
```py
match some_int:
    case x:=2:
        pass
```

The [way this is parsed](https://play.ruff.rs/cc7622ca-7608-4112-b92e-15628c397c1a) is interesting. The first part
```py
match some_int:
    case x:
```
is parsed as a `Match`. So far, so good. But then the next part (`=2:`) is parsed as an assignment statement with a type annotation (`AnnAssign`). Strangely, it contains `2` as the *target* of the assignment. And an empty `Name` for the assignment (with `ExprContext::Invalid`, which is what triggers the assertion).

### PR DESCRIPTION
**Pull request by sharkdp**
## Summary

Fixes a failing debug assertion that triggers for the following code:
```py
match some_int:
    case x:=2:
        pass
```

closes #14305

## Test Plan

Added problematic code example to corpus.

### CODE REVIEW

File: crates/red_knot_python_semantic/src/types/infer.rs [hunk 1]
```diff
@@ -4084,16 +4084,19 @@ impl<'db> TypeInferenceBuilder<'db> {
...
 
         match expression {
-            ast::Expr::Name(name) => {
-                debug_assert_eq!(name.ctx, ast::ExprContext::Load);
-                self.infer_name_expression(name).to_instance(self.db)
-            }
+            ast::Expr::Name(name) => match name.ctx {
+                ast::ExprContext::Load => self.infer_name_expression(name).to_instance(self.db),
+                ast::ExprContext::Invalid => Type::Unknown,
+                ast::ExprContext::Store | ast::ExprContext::Del => Type::Todo,
```
Comment (sharkdp) [inline crates/red_knot_python_semantic/src/types/infer.rs:4090]: We could also go with
```suggestion
                ast::ExprContext::Store | ast::ExprContext::Del => todo!(),
```
here (and below) for now, if we want to be more explicit about the fact that we can't handle this yet.

**Review by MichaReiser — APPROVED** [review]

File: crates/red_knot_python_semantic/src/types/infer.rs (hunk 1 above)
Comment (AlexWaygood) [reply crates/red_knot_python_semantic/src/types/infer.rs:4090]: I prefer your current version — I think we want to be able to check as much code as possible without false positives right now... And you can think of a panic as just an exceptionally dramatic false positive 😆

**Comment by carljm** [comment]
We should probably be emitting diagnostics on invalid type expressions here, but that's a bigger scope project, so this looks good for now.

The more strange thing here is that we are using `infer_type_expression` for match patterns. I think that is probably not right, but fixing up match pattern type inference is also a bigger-scope project.

**Comment by sharkdp** [comment]
> The more strange thing here is that we are using `infer_type_expression` for match patterns. I think that is probably not right, but fixing up match pattern type inference is also a bigger-scope project.

Did you see the comment in the related issue (https://github.com/astral-sh/ruff/issues/14305#issue-2654609039) on how that example is parsed? The problematic AST element is an annotated assignment statement, and not related to the match. We call `infer_type_expression` on the annotation expression, and that caused the problem.

**Comment by sharkdp** [comment]
And to be clear, we emit lots of `invalid-syntax` diagnostics here:
```
error[invalid-syntax] /home/shark/playground/test.py:2:11 Expected ':', found ':='
error[invalid-syntax] /home/shark/playground/test.py:2:13 Invalid annotated assignment target
error[invalid-syntax] /home/shark/playground/test.py:2:15 Expected an expression
error[invalid-syntax] /home/shark/playground/test.py:3:1 Unexpected indentation
error[invalid-syntax] /home/shark/playground/test.py:4:1 Expected a statement
```

**Comment by carljm** [comment]
No, I hadn't seen the issue yet, sorry. (I don't see new issues labeled red-knot automatically in my notifications, whereas CODEOWNERS means I always see PRs. I'd love to get notified on all issues tagged red-knot, but it seems like that is currently only possible with a third-party GH Action.) Now I understand what's happening here, thanks!

My comment about "invalid type annotation" diagnostics that we should emit was not related to the specific triggering example here, but to the code change in general. There are valid-syntax cases (`x: (y := 2) = 3`, for example) where we could end up with a Store-context Name node in a type expression, and we should have a diagnostic for that. (Not saying that it's a priority to do it now.)
