### PR TITLE
Escape template filenames in glob patterns

### LINKED ISSUE #9381: `ruff format` or `ruff check` returns "nested alternate groups are not allowed" error
I am attempting to exclude this dir from inspection:

```
extend-exclude = [
    "__pycache__",
]
```

but I am getting:

```sh
$ python3 -m ruff format .
ruff failed
  Cause: error parsing glob '/Users/me/project/{{cookiecutter.project_dirname}}/__pycache__': nested alternate groups are not allowed
```

Any ideas?

On a side note, according to [this](https://regex101.com/r/I8WJGr/1) experiment, this syntax should be valid

```
extend-exclude = [
    "[{][{]cookiecutter[.]project_dirname[}][}]/__pycache__",
]
```

but it still gets me the error above.

### PR DESCRIPTION
**Pull request by ntBre**
## Summary

Fixes #9381. This PR fixes errors like 

```
Cause: error parsing glob '/Users/me/project/{{cookiecutter.project_dirname}}/__pycache__': nested alternate groups are not allowed
```

caused by glob special characters in filenames like `{{cookiecutter.project_dirname}}`. When the user is matching that directory exactly, they can use the workaround given by https://github.com/astral-sh/ruff/issues/7959#issuecomment-1764751734, but that doesn't work for a nested config file with relative paths. For example, the directory tree in the reproduction repo linked [here](https://github.com/astral-sh/ruff/issues/9381#issuecomment-2677696408):

```
.
├── README.md
├── hello.py
├── pyproject.toml
├── uv.lock
└── {{cookiecutter.repo_name}}
    ├── main.py
    ├── pyproject.toml
    └── tests
        └── maintest.py
```

where the inner `pyproject.toml` contains a relative glob:

```toml
[tool.ruff.lint.per-file-ignores]
"tests/*" = ["F811"]
```

## Test Plan

A new CLI test in both the linter and formatter. The formatter test may not be necessary because I didn't have to modify any additional code to pass it, but the original report mentioned both `check` and `format`, so I wanted to be sure both were fixed.

### CODE REVIEW

**Comment by ntBre** [comment]
I'm not sure what's going wrong on Windows. It looks like the `tempdir_filter` isn't working. I force pushed back over it, but I even tried removing my second filter [here](https://github.com/astral-sh/ruff/actions/runs/13554843187/job/37886774376) and the temp path is still wrong.

**Comment by MichaReiser** [comment]
> I'm not sure what's going wrong on Windows. It looks like the `tempdir_filter` isn't working. I force pushed back over it, but I even tried removing my second filter [here](https://github.com/astral-sh/ruff/actions/runs/13554843187/job/37886774376) and the temp path is still wrong.

Yeah, the filters are brutal on windows. Can you try what we have in 

https://github.com/astral-sh/ruff/blob/3e840ca839e40d875e28ff7f15c94d88c4d6e7ae/crates/red_knot/tests/cli.rs#L863-L865

File: crates/ruff_linter/src/settings/types.rs [hunk 1]
```diff
@@ -647,6 +647,25 @@ where
...
+pub fn try_glob_new(s: &str) -> Result<Glob> {
+    match Glob::new(s) {
+        Err(e) if *e.kind() == globset::ErrorKind::NestedAlternates => {
+            let new = s.replace("{{", "[{][{]").replace("}}", "[}][}]");
+            log::warn!(
+                "Error parsing original glob: `{s:?}`, trying with escaped braces: `{new:?}`"
+            );
+            Ok(Glob::new(&new)?)
+        }
+        glob => Ok(glob?),
```
Comment (MichaReiser) [inline crates/ruff_linter/src/settings/types.rs:665]: This, indeed, feels somewhat hacky :D 

I think my main concern with this is that it replaces nested alternates anywhere in the glob -- even in the part that the user provided. 

What I understand is that the problem is mainly about `{{` and `}}` in the base path up to the project. Could we escape the `{{` and `}}` in the project's base-path only instead of applying this fix to the entire glob?

Comment (ntBre) [reply crates/ruff_linter/src/settings/types.rs:665]: That's true, although the nested alternates will always cause an error even if the user provided them. I thought it might be nice to allow them to avoid manual escaping in that case, but at least they *can* control that directly, unlike the base paths.

We could also add the escapes to the whole path just before creating the glob. I think that version would also look less hacky than catching this error and retrying, but then we also do the work of trying to replace each time. That was the main reason I tried to keep the replacement in the error case, but we're still only compiling the globs once, so it's probably not a big deal.

**Comment by ntBre** [comment]
It looks like the regex escapes in `tempdir_filter` are causing problems, but it works for all of the other tests using this...

```
C:\/Users\/RUNNER~1\/AppData\/Local\/Temp\/.tmpCazbkF\\{{cookiecutter.repo_name}}\/tests\\*
```

OH, maybe it's the cookiecutter causing problems again. The escapes for the braces might be getting in the way of the tempdir replacement. Let me try nesting it one level deeper.

**Comment by MichaReiser** [comment]
You can try to use `regex::escape` to avoid regex problems

**Comment by ntBre** [comment]
`tempdir_filter` uses `regex::escape` already, unless I'm misunderstanding. My current guess is that the escapes added by `regex::escape` are disrupting the TMP replacement because they end up right next to the tempdir.

```
C:\/Users\/RUNNER~1\/AppData\/Local\/Temp\/.tmpCazbkF\\{{cookiecutter.repo_name}}\/tests\\*
                                                     ^^^ this looks suspicious to me
```

File: crates/ruff_linter/src/settings/types.rs [hunk 2]
```diff
@@ -647,6 +647,25 @@ where
...
+/// Call [`Glob::new`] but peek at the [`globset::ErrorKind`] and try the glob again with any nested
+/// alternates escaped.
+///
+/// For example, the `cookiecutter` package generates paths like `{{cookiecutter.repo_name}}`, which
+/// look like nested glob alternate expressions like `{foo,bar}`. The nested version is not
+/// supported by `globset`, causing an error.
+pub fn try_glob_new(s: &str) -> Result<Glob> {
+    match Glob::new(s) {
+        Err(e) if *e.kind() == globset::ErrorKind::NestedAlternates => {
+            let new = s.replace("{{", "[{][{]").replace("}}", "[}][}]");
```
Comment (BurntSushi) [inline crates/ruff_linter/src/settings/types.rs:659]: This is also not _technically_ right in all cases I think, e.g., `[{{]`, although that's pretty pathological.

**Review by BurntSushi — COMMENTED** [review]
Thanks for taking a look at this!

I think the thing I'm not understanding here is why nested alternates are the only problem here? Isn't the problem that we're using arbitrary input to build a glob? And shouldn't that imply the input (in this case, a file path) should always be escaped? Like, the nested alternates is just _one_ way for this problem to manifest. But what if a file path had a `*` or a `[` in it? We would want to escape it there too.

So I guess, can we fix this by just always escaping the literal inputs to a glob?

**Comment by ntBre** [comment]
Thanks for the review! I failed to notice the `globset::escape` function. I think we can just use that on the base part of the path that we're adding to the glob pattern. That will be much more robust than my manual escaping here and also leave the user's glob alone in case that's what they intended.

**Comment by ntBre** [comment]
I was checking for the other uses of `Glob::new`, and I think this could also be a problem for the `FilePath::User` variant.

https://github.com/astral-sh/ruff/blob/cf83584abb130574059064ad5f0dd806c22e45d5/crates/ruff_linter/src/settings/types.rs#L162-L166

I'll start adding the `escape` calls for it too.

File: crates/ruff_linter/src/settings/types.rs [hunk 3]
```diff
@@ -202,9 +234,10 @@ impl FromStr for FilePattern {
     type Err = anyhow::Error;
 
     fn from_str(s: &str) -> Result<Self, Self::Err> {
-        let pattern = s.to_string();
-        let absolute = fs::normalize_path(&pattern);
-        Ok(Self::User(pattern, absolute))
+        Ok(Self::User(
+            s.to_string(),
+            GlobPath::normalize(s, &*path_dedot::CWD),
```
Comment (MichaReiser) [inline crates/ruff_linter/src/settings/types.rs:239]: Can we introduce a `cwd` helper function in `fs`. WASM doesn't like `path_dedot::CWD` 

https://github.com/astral-sh/ruff/blob/e7a6c19e3a2c88d2eaad88a311c60fbd4e733c14/crates/ruff_linter/src/fs.rs#L36-L48

File: crates/ruff_linter/src/settings/types.rs [hunk 4]
```diff
@@ -298,15 +331,12 @@ impl<T> PerFile<T> {
         if negated {
             pattern.drain(..1);
         }
-        let path = Path::new(&pattern);
-        let absolute = match project_root {
-            Some(project_root) => fs::normalize_path_to(path, project_root),
-            None => fs::normalize_path(path),
-        };
+
+        let project_root = project_root.unwrap_or(&path_dedot::CWD);
```
Comment (MichaReiser) [inline crates/ruff_linter/src/settings/types.rs:335]: Same here, let's avoid spreading `path_dedot::CWD` over our code base and instead use a helper to maximize WASM compatibility

**Review by MichaReiser — APPROVED** [review]
Nice, this looks great

**Review by BurntSushi — APPROVED** [review]
LGTM

File: crates/ruff_linter/src/settings/types.rs (hunk 3 above)
Comment (ntBre) [reply crates/ruff_linter/src/settings/types.rs]: Oh good idea, I factored this out into a `get_cwd` function and call it everywhere in the linter. I left the calls in the `ruff` and `ruff_workspace` crates alone for now. Should I replace those too?
