### PR TITLE
[`pylint`] Demote `PLW1510` fix to display-only

### LINKED ISSUE #17091: `PLW1510`: `subprocess.run` without explicit `check` argument: Mark fix as manual
### Summary

Remove the PLW1510 autofix, as it can be misleading/blindsiding the user

_Based on the discussion https://github.com/astral-sh/ruff/discussions/17087_

### PR DESCRIPTION
**Pull request by ntBre**
Summary
--

Closes #17091. `PLW1510` checks for `subprocess.run` calls without a `check`
keyword argument and previously had a safe fix to add `check=False`. That's the
default value, so technically it preserved the code's behavior, but as discussed
in #17091 and #17087, Ruff can't actually know what the author intended.

I don't think it hurts to keep this as a display-only fix instead of removing it
entirely, but it definitely shouldn't be safe at the very least.

Test Plan
--

Existing tests

### CODE REVIEW

File: crates/ruff_linter/src/rules/pylint/rules/subprocess_run_without_check.rs [hunk 1]
```diff
@@ -39,24 +39,31 @@ use crate::{AlwaysFixableViolation, Applicability, Fix};
...
 /// - [Python documentation: `subprocess.run`](https://docs.python.org/3/library/subprocess.html#subprocess.run)
 #[derive(ViolationMetadata)]
 #[violation_metadata(stable_since = "v0.0.285")]
 pub(crate) struct SubprocessRunWithoutCheck;
 
-impl AlwaysFixableViolation for SubprocessRunWithoutCheck {
+impl Violation for SubprocessRunWithoutCheck {
+    // The fix is always set on the diagnostic, but display-only fixes aren't
+    // considered "fixable" in the tests.
+    const FIX_AVAILABILITY: FixAvailability = FixAvailability::Sometimes;
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/pylint/rules/subprocess_run_without_check.rs:58]: This felt worth a comment here, but I think this is pretty reasonable in general. These fixes aren't usually shown to users. We could of course update the test code instead:

https://github.com/astral-sh/ruff/blob/8cd04df49d15869e9c1ce82ecc882ece0c7eb0d7/crates/ruff_linter/src/test.rs#L354-L359
