### PR TITLE
[flake8-pyi] Fix PYI016 false positive for f-string debug specifier

### LINKED ISSUE #19914: PYI016 treats distinct interpolations as duplicates
### Summary

[`duplicate-union-member` (PYI016)](https://docs.astral.sh/ruff/rules/duplicate-union-member/) treats f-strings’ and t-strings’ interpolations as duplicates whose values are duplicates but whose expressions are not. This applies to f-strings’ interpolations with `=` and to all t-strings’ interpolations. Either the fix should be marked unsafe in this case, or the rule should be suppressed in this case. [Example](https://play.ruff.rs/a0f3f060-9cd0-451e-9842-6f68e63c28cb):
```console
$ cat >pyi016.py <<'# EOF'
from typing import Annotated, get_args, get_origin

f: Annotated[int, f"{00=}"] | Annotated[int, f"{000=}"] | None = None
print([get_args(a)[1] for a in get_args(__annotate__(1)["f"]) if get_origin(a) is Annotated])

t: Annotated[int, t"{00}"] | Annotated[int, t"{000}"] | None = None
print([get_args(a)[1].interpolations[0].expression for a in get_args(__annotate__(1)["t"]) if get_origin(a) is Annotated])
# EOF

$ python3.14 pyi016.py
['00=0', '000=0']
['00', '000']

$ ruff --isolated check pyi016.py --select PYI016 --target-version py314 --preview --fix
Found 2 errors (2 fixed, 0 remaining).

$ cat pyi016.py
from typing import Annotated, get_args, get_origin

f: Annotated[int, f"{0=}"] | None = None
print([get_args(a)[1] for a in get_args(__annotate__(1)["f"]) if get_origin(a) is Annotated])

t: Annotated[int, t"{0}"] | None = None
print([get_args(a)[1].interpolations[0].expression for a in get_args(__annotate__(1)["t"]) if get_origin(a) is Annotated])

$ python3.14 pyi016.py
['0=0']
['0']
```

### Version

ruff 0.12.8 (f51a228f0 2025-08-07)

### PR DESCRIPTION
**Pull request by eyupcanakman**
## Summary

PYI016 incorrectly flags `f"{0x0=}"` and `f"{0o0=}"` as duplicate union members. Both parse to the same AST (`IntLiteral(0)`), but produce different output at runtime (`"0x0=0"` vs `"0o0=0"`) because the `=` specifier embeds the original source text.

Add a `source` field to `DebugText` that captures the expression source text at parse time. Comparisons now normalize line endings in the comparable debug-text wrapper, so multiline debug expressions match the way Python renders them on CRLF and LF input.

I looked at merging `leading`, `source`, and `trailing` into a single field, but the formatter and codegen consume `leading` and `trailing` separately (formatter wraps them in `NormalizedDebugText`, codegen outputs them around the regenerated expression), so three fields is still the practical split.

Fixes #19914

## Test Plan

Added 7 test cases (field50-field56) covering:
- Different-length debug expressions (`f"{00=}"` vs `f"{000=}"`)
- Debug vs non-debug (`f"{x=}"` vs `f"{x}"`)
- True duplicates with and without debug specifier
- Different format specs (`f"{x:.2f}"` vs `f"{x:.3f}"`)
- Different debug text from whitespace (`f"{x =}"` vs `f"{x=}"`)
- The reported case (`f"{0x0=}"` vs `f"{0o0=}"`)

Added a regression test for multiline self-documenting f-strings with mixed CRLF and LF line endings.

- `cargo test -p ruff_linter pyi016`
- `cargo test -p ruff_linter pyi016_multiline_debug_fstring_mixed_newlines`
- `cargo test -p ruff_python_parser fstring`

### CODE REVIEW

File: crates/ruff_python_ast/src/comparable.rs [hunk 1]
```diff
@@ -552,6 +560,7 @@ impl<'a> From<&'a ast::InterpolatedElement> for InterpolatedElement<'a> {
 
         Self {
             expression: (expression).into(),
+            expression_text_len: debug_text.as_ref().map(|_| expression.range().len()),
```
[the remark this answers is not in the document]
Comment (MichaReiser) [reply crates/ruff_python_ast/src/comparable.rs]: I think the comment here is right. Although not sure how to fix it without having access to the source code.

**Comment by MichaReiser** [comment]
Thanks for working on this. I think we should explore changing our `DebugText` representation. E.g. what would it mean to capture the entire text between `{` and `}`?

**Comment by eyupcanakman** [comment]
@MichaReiser Thanks for the suggestion. That's a much better place for it. I actually started reworking things before your earlier comment too. The force-push already compares by source text instead of just byte length. But putting it in `DebugText` makes more sense. The parser already has the expression source right where it builds `DebugText`, so adding a field there keeps everything simple. No need to thread source through `ComparableExpr` at all.

I'll update the PR with that approach.

**Comment by eyupcanakman** [comment]
Reworked the PR. `DebugText` now has a `source` field that captures the expression source text at parse time. Since `DebugText` derives `PartialEq`/`Eq`/`Hash`, comparisons pick it up without any `ComparableExpr` changes.

I looked at merging `leading`, `source`, and `trailing` into a single field, but the formatter and codegen use `leading`/`trailing` separately (formatter wraps them in `NormalizedDebugText`, codegen outputs them around the regenerated expression), so three fields is the practical split.

The original issue also mentions t-strings without `=` (`t"{00}"` vs `t"{000}"`), where the interpolation objects differ at runtime but there is no `DebugText`. This fix does not cover that case since `DebugText` is only present with `=`. `typing.Literal[t"..."]` is not valid Python and t-strings in stubs are unlikely in practice. Happy to open a follow-up if needed.

**Comment by MichaReiser** [comment]
Thank you. 

> I looked at merging leading, source, and trailing into a single field, but the formatter and codegen use leading/trailing separately (formatter wraps them in NormalizedDebugText, codegen outputs them around the regenerated expression), so three fields is the practical split.

Do you have a sense for how involved it would be if we rewrote those usages use the raw expression?

Another alternative is to change `DebugText` to store:

* The entire `expression` string 
* Store offsets leading end and trailing start into `expression`
* Provide methods on `DebugText` to extract `leading` and `trailing`

However, Ideally we'd just store a single `String` if that's sufficient.

**Comment by eyupcanakman** [comment]
The offset approach works. Formatter, codegen, and newline checks just switch from field access to method calls. The test normalizer needs to rebuild the string after replacements but that's a few extra lines. A bare single string without offsets wouldn't be enough since the parts are used separately. Want me to update the PR with the offset version?

**Comment by MichaReiser** [comment]
It's weird to say it but your last comment makes me feel as if I'm interacting with an AI agent (I don't mean to offend) 😅. If you happen to use AI, please read our [AI policy](https://github.com/astral-sh/.github/blob/main/AI_POLICY.md)

I don't think we should store three Strings, that's wasteful and using offset sounds reasonable from your response. But I can't say for sure without seeing the changes myself (or making them myself).

**Comment by eyupcanakman** [comment]
@MichaReiser No offense taken😅 English isn't my native language, so I tend to over-edit my sentences to avoid grammar mistakes. I guess that makes it read a bit too static. 

About the PR, agreed on the code. Three strings is probably too much anyway. Offsets sound good. I'll push an update with that.

**Comment by eyupcanakman** [comment]
Pushed. I ended up adding a normalize_newlines method since the formatter tests were writing straight to the old fields.

File: crates/ruff_python_ast/src/comparable.rs [hunk 2]
```diff
@@ -517,10 +517,35 @@ pub enum ComparableInterpolatedStringElement<'a> {
     InterpolatedElement(InterpolatedElement<'a>),
 }
 
+#[derive(Debug, PartialEq, Eq, Hash)]
+pub struct ComparableDebugText<'a> {
+    leading: Cow<'a, str>,
+    source: Cow<'a, str>,
+    trailing: Cow<'a, str>,
```
Comment (MichaReiser) [inline crates/ruff_python_ast/src/comparable.rs]: Can you say more why it isn't sufficient to only store `source` in `ComparableDebugText`?

File: crates/ruff_python_ast/src/nodes.rs [hunk 3]
```diff
@@ -387,13 +387,67 @@ impl ConversionFlag {
...
+    leading_end: u32,
+    /// Byte offset where the expression source ends and the trailing portion begins.
+    trailing_start: u32,
+}
+
+impl std::fmt::Debug for DebugText {
+    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
+        f.debug_struct("DebugText")
+            .field("leading", &self.leading())
+            .field("source", &self.source())
```
Comment (MichaReiser) [inline crates/ruff_python_ast/src/nodes.rs]: Let's rename the field to `expression`.

File: crates/ruff_python_ast/src/nodes.rs [hunk 4]
```diff
@@ -387,13 +387,67 @@ impl ConversionFlag {
     }
 }
 
-#[derive(Clone, Debug, PartialEq, Eq, Hash)]
+#[derive(Clone, PartialEq, Eq, Hash)]
 #[cfg_attr(feature = "get-size", derive(get_size2::GetSize))]
 pub struct DebugText {
+    /// The full text between the `{` and the conversion / `format_spec` / `}`.
+    /// Contains leading whitespace, the expression source, and trailing whitespace + `=`.
+    expression: String,
```
Comment (MichaReiser) [inline crates/ruff_python_ast/src/nodes.rs]: Can we use a `CompactString` here, given that most of these should be short.

File: crates/ruff_python_ast/src/nodes.rs [hunk 5]
```diff
@@ -387,13 +387,67 @@ impl ConversionFlag {
...
+    /// Byte offset where the leading portion ends and the expression source begins.
+    leading_end: u32,
```
Comment (MichaReiser) [inline crates/ruff_python_ast/src/nodes.rs]: Looking at this again. I think we don't even need to store `leading_start` and `leading_end`. Instead, we can change `DebugText` to be a thin wrapper around a `CompactString`: `DebugText(CompactString)` and we can compute the individual parts when necessary:

* The `leading_end` is the offset of the first character that doesn't satisfy `is_python_whitespace.` 
* The `trailing_start` is the last character from the back that satisfies `is_python_whitespace` 


With this, it's trivial to slice the string where necessary. 

Regarding naming:

* `expression` (the part between leading and trailing)
* `leading`: The whitespace before the expression
* `trailing`: The whitespace after the expression

File: crates/ruff_python_ast/src/comparable.rs [hunk 6]
```diff
@@ -517,10 +517,35 @@ pub enum ComparableInterpolatedStringElement<'a> {
...
+}
+
+impl<'a> From<&'a ast::DebugText> for ComparableDebugText<'a> {
+    fn from(debug_text: &'a ast::DebugText) -> Self {
+        Self {
+            leading: normalize_newlines(debug_text.leading()),
```
Comment (MichaReiser) [inline crates/ruff_python_ast/src/comparable.rs]: Let's add a comment saying why it's okay to normalize newlines here

**Review by MichaReiser — COMMENTED** [review]
This is close. I've a few more smaller comments.

File: crates/ruff_python_ast/src/nodes.rs (hunk 4 above)
Comment (eyupcanakman) [reply crates/ruff_python_ast/src/nodes.rs]: Done.

File: crates/ruff_python_ast/src/nodes.rs (hunk 3 above)
Comment (eyupcanakman) [reply crates/ruff_python_ast/src/nodes.rs]: Done.

File: crates/ruff_python_ast/src/comparable.rs (hunk 2 above)
Comment (eyupcanakman) [reply crates/ruff_python_ast/src/comparable.rs]: Whitespace in leading/trailing affects runtime output (`f"{x =}"` gives `"x =1"` vs `"x=1"`), so source alone would miss those differences. Simplified to a single `Cow` for the full text.

File: crates/ruff_python_ast/src/nodes.rs (hunk 5 above)
Comment (eyupcanakman) [reply crates/ruff_python_ast/src/nodes.rs:404]: Leading and trailing can hold grouping parens (`f"{  ( chr(65)  ) = }"`) or comments in triple quoted strings, so scanning for whitespace alone gives wrong boundaries. Switched to `CompactString` but kept the offsets.

File: crates/ruff_python_ast/src/comparable.rs (hunk 6 above)
Comment (eyupcanakman) [reply crates/ruff_python_ast/src/comparable.rs]: Added.

File: crates/ruff_python_ast/src/nodes.rs [hunk 7]
```diff
@@ -387,13 +387,85 @@ impl ConversionFlag {
...
+    pub fn trailing(&self) -> &str {
+        &self.expression[self.trailing_start as usize..]
+    }
+
+    /// Replace `\r\n` and `\r` with `\n` in the leading and trailing portions,
+    /// preserving the expression source text as-is.
+    pub fn normalize_newlines(&mut self) {
+        if self.expression.contains('\r') {
+            let leading = self.leading().replace("\r\n", "\n").replace('\r', "\n");
+            let expr = self.expression().to_string();
```
Comment (MichaReiser) [inline crates/ruff_python_ast/src/nodes.rs]: What's the reason for replacing new lines in all parts except the expression? I'm asking because `ComparableDebugText` normalizes all newlines. 

What I understand is that this is to match the formatter's semantics. If that's the case, I suggest moving this code into the formatter tests, to make this more explicit.

File: crates/ruff_python_ast/src/nodes.rs (hunk 5 above)
Comment (MichaReiser) [reply crates/ruff_python_ast/src/nodes.rs]: Ah, that's too bad. 

A few more naming nits:

Given that `expression` contains the whole text and not just the expression, maybe just call it `text`? 

I would rename `leading_end` to `expression_start` and `trailing_start` to `expression_end`. To me, it's the most clear where the expression starts and ends, and it clarifies that `leading` is the part before that and trailing is the part after the expression.

File: crates/ruff_python_ast/src/nodes.rs [hunk 8]
```diff
@@ -387,13 +387,85 @@ impl ConversionFlag {
...
+            u32::try_from(leading.len()).expect("DebugText leading exceeds u32::MAX bytes");
+        let trailing_start = leading_end
+            + u32::try_from(expression.len())
+                .expect("DebugText expression exceeds u32::MAX bytes");
+        let mut buf = compact_str::CompactString::with_capacity(
+            leading.len() + expression.len() + trailing.len(),
+        );
+        buf.push_str(leading);
+        buf.push_str(expression);
+        buf.push_str(trailing);
```
Comment (MichaReiser) [inline crates/ruff_python_ast/src/nodes.rs]: You could simplify this by using `text_len().as_u32()` to avoid the `try_from` and explicit `excpect`

**Review by MichaReiser — APPROVED** [review]
Sorry for the long delay. This looks good to me. I only have a few nits.
