### PR TITLE
Fix playground Share button showing "Copied!" before clipboard copy completes

### LINKED ISSUE #21691: playground: Share button says Copied! before actually copying, then fails if you tab away too fast
### Summary

The Share button shows "Copied!" before it actually copies.

If you press Share, then tab away as soon as you see "Copied!", it will not copy. The console shows this error:

```
Failed to share playground: NotAllowedError: Failed to execute 'writeText' on 'Clipboard': Document is not focused.
(anonymous) @ index-BGT7xqC_.js:1033
Promise.catch
(anonymous) @ index-BGT7xqC_.js:1033
onClick @ index-BGT7xqC_.js:54
kX @ index-BGT7xqC_.js:49
(anonymous) @ index-BGT7xqC_.js:49
AK @ index-BGT7xqC_.js:49
q3 @ index-BGT7xqC_.js:49
o9 @ index-BGT7xqC_.js:50
kbe @ index-BGT7xqC_.js:50
```

### Version

_No response_

### PR DESCRIPTION
**Pull request by mahiro72**
## Summary

Fix the playground Share button to only show "Copied!" after the clipboard copy operation actually completes.

Previously, the Share button would immediately show "Copied!" when clicked, before the async `persist` and `clipboard.writeText` operations finished. This caused a confusing UX where users would see "Copied!" but if they tabbed away quickly, the copy would fail with a `NotAllowedError: Document is not focused` error.

Now the button waits for `onShare()` to complete before updating the UI state.

Fixes #21691

## Test Plan

Tested locally with `npm start --workspace ruff-playground`

## Demo
Kapture 2025-12-12 at 20 47 51

### CODE REVIEW

**Comment by dhruvmanila** [comment]
Ohh, this is what was happening! I noticed this multiple times but didn't dig into it. Thanks for opening a fix for this issue, it would be useful to add a short video to demo this in the PR description when you make it ready for review.

File: playground/ruff/src/Editor/Chrome.tsx [hunk 1]
```diff
@@ -16,12 +16,12 @@ export default function Chrome() {
...
+  const handleShare = useCallback(async () => {
     if (settings == null || pythonSource == null) {
       return;
     }
 
-    persist(settings, pythonSource).catch((error) =>
+    await persist(settings, pythonSource).catch((error) =>
       // eslint-disable-next-line no-console
       console.error(`Failed to share playground: ${error}`),
     );
```
Comment (MichaReiser) [inline playground/ruff/src/Editor/Chrome.tsx]:
```suggestion
			try {
        await persist(serialized);
      } catch (error) {
        // eslint-disable-next-line no-console
        console.error("Failed to share playground", error);
      }
```

File: playground/shared/src/ShareButton.tsx [hunk 2]
```diff
@@ -29,9 +33,9 @@ export default function ShareButton({ onShare }: { onShare: () => void }) {
       type="button"
       className="relative flex-none leading-6 py-1.5 px-3 shadow-xs disabled:opacity-50"
       disabled={copied}
-      onClick={() => {
+      onClick={async () => {
+        await onShare();
```
Comment (MichaReiser) [inline playground/shared/src/ShareButton.tsx]: I think we want to distinguish between three states

* `initial`: Button is clickable, label is `Share`
* `copying`: Button is disabled, label is `Share`
* `copied`: Button is disabled, label is `Copied`

We should ensure that we reset the state to `Share` if `onShare` throws (maybe by moving the try catch handling from `onShare` to here, we could even consider having a 4th state `failed`)

**Comment by mahiro0x00** [comment]
Thank you for the review @MichaReiser ! 

I’ve addressed your feedback:
- Moved error handling from `handleShare` to `ShareButton`
- Added three states: `initial`, `copying`, and `copied`

Please take another look when you have a chance.
