### PR TITLE
[ty] stop unioning Unknown into types of un-annotated attributes

### LINKED ISSUE #1240: add an option to disable `Unknown` type from from being added where there is no type annotation
the current default behavior is unsafe, see https://play.ty.dev/b92b01eb-09da-48ea-8e4b-02812d27a803
```py
a = [1] # inferred as list[Unknown | int]
a.append("i'm not an int") # no error
a.pop() + 1 # runtime crash
```

as mentioned in https://github.com/astral-sh/ty/issues/1211#issuecomment-3322024482:

> I do think we will likely add an option to, or even default to, inferring the type of un-annotated generic container literals without the union with `Unknown`.

### PR DESCRIPTION
**Pull request by carljm**
## Summary

Fixes https://github.com/astral-sh/ty/issues/1240.

After this PR, the only cases where we union in `Unknown` to an un-annotated attribute type are if the inferred type is `None` or another non-literal singleton type. We now literal-promote inferred attribute types instead.

This caused some conditional-implicit-attribute cases to oscillate between "defined" and "undefined", which required a cycle-normalization fix to make definedness monotone.

## Test Plan

Adjusted many mdtest expectations.

Conformance suite results are positive, and add one newly-passing file. (The tool shows a reduction in true positives, but these are diagnostics going away on `assert_type` lines where diagnostics are optionally permitted, not required, or even desirable.)

Ecosystem diff looks expected/positive. A number of the new errors come from projects which declare types via type comments, which we don't support, so we infer types for those attributes instead. There are of course some cases where the inferred type is not the intended type, but that's expected for this PR, and the overall scale of new diagnostics looks very reasonable.

Codspeed shows performance improvements from 0-3%, and we also see a small reduction in memory usage.

### CODE REVIEW

File: crates/ruff_benchmark/benches/ty.rs [hunk 1]
```diff
@@ -534,6 +534,7 @@ fn benchmark_complex_constrained_attributes_3(criterion: &mut Criterion) {
                     class GridOut:
                         def __init__(self: "GridOut") -> None:
                             self._buffer = b""
+                            self._position = 0
```
Comment (carljm) [inline crates/ruff_benchmark/benches/ty.rs:537]: This PR caused us to start emitting 3 (true positive) diagnostics on this snippet about `self._position` attribute not existing -- other type checkers also emit those diagnostics.

File: crates/ty_python_semantic/resources/mdtest/doc/public_type_undeclared_symbols.md [hunk 2]
```diff
@@ -42,84 +50,57 @@ def f(w: Wrapper) -> None:
...
-We do not catch this mistake either, but we accurately reflect our lack of knowledge about
-`o.value`. Together with a possible future type-checker mode that would detect the prevalence of
-dynamic types, this could help developers catch such mistakes.
-
-## Stricter behavior
+## Declaring a wider type
 
-Users can always opt in to stricter behavior by adding type annotations. For the `OptionalInt`
-class, this would probably be:
+Users can always opt in to a wider public type by adding annotations. For the `Wrapper` class, this
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/doc/public_type_undeclared_symbols.md:70]: (Or a narrower public type that avoids Literal promotion)

File: crates/ty_python_semantic/resources/mdtest/snapshots/invalid_await.md_-_Invalid_await_diagno…_-_Non-callable_`__awai…_(d78580fb6720e4ea).snap [hunk 3]
```diff
@@ -24,12 +24,20 @@ mdtest path: crates/ty_python_semantic/resources/mdtest/diagnostics/invalid_awai
...
+    |
+  4 | async def main() -> None:
+  5 |     await NonCallableAwait()  # error: [invalid-await]
+    |           ^^^^^^^^^^^^^^^^^^
+    |
+   ::: stdlib/builtins.pyi:348:7
+    |
+347 | @disjoint_base
+348 | class int:
+    |       --- attribute defined here
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/snapshots/invalid_await.md_-_Invalid_await_diagno…_-_Non-callable_`__awai…_(d78580fb6720e4ea).snap:37]: I assume this is a pre-existing issue, but it's a bit weird that this diagnostic jumps to the definition of `int` in typeshed without ever explicitly showing or telling you that `__await__` was set to an `int` value

File: crates/ty_python_semantic/src/types/call/bind.rs [hunk 4]
```diff
@@ -3784,14 +3784,6 @@ impl<'a, 'db> ArgumentMatcher<'a, 'db> {
...
 
         let variadic_type = match argument_type {
-            // When accessing an instance attribute that is a `P.args`, the type we infer is
-            // `Unknown | P.args`. This needs to be special cased here to avoid calling
-            // `iterate` on it which will lose the `ParamSpec` information as it will return
-            // `object` that comes from the upper bound of `P.args`. What we want is to always
-            // use the `P.args` type to perform type checking against the parameter type. This
-            // will allow us to error when `*args: P.args` is matched against, for example,
-            // `n: int` and correctly type check when `*args: P.args` is matched against
-            // `*args: P.args` (another ParamSpec).
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/call/bind.rs:3799]: presumably we still want some sort of comment here explaining why there is still a special case below where we avoid calling `.iterate()` if the argument is annotated with `P.args`? We should just adjust the comment so that it no longer mentions `| Unknown` rather than removing it entirely

File: crates/ty_python_semantic/src/place.rs [hunk 5]
```diff
@@ -1020,25 +1038,19 @@ pub(crate) fn place_by_id<'db>(
...
-            // However, external modifications (or modifications through `global` statements) that
-            // would require a wider type are relatively rare. From a practical perspective, we can
-            // therefore achieve a better user experience by trusting the inferred type. Users who
-            // need the external mutation to work can always annotate the global with the wider
-            // type. And everyone else benefits from more precise type inference.
+            // Module-level globals can be mutated externally, and strict application of the
+            // gradual guarantee would suggest that if not annotated, all such external mutations
+            // should be valid. However, external modifications (or modifications through `global`
+            // statements) that would require a different public type are relatively rare. From a
+            // practical perspective, we get a better user experience by trusting the (promoted)
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/place.rs]: On `main`, we already do not union module-global types with `Unknown`. However, we don't currently promote module-global types; we just keep the precisely inferred `Literal` types.

I'm open to trying out a change where we promote module-global types, similar to what this PR does with other public types, but this PR does not (and should not) do that -- it should be done in a separate PR so that we can evaluate the ecosystem impact of that as an isolated change.

In fact, the whole reason why the variable immediately beneath this comment still exists on this PR branch is so that module-global public types can still be treated differently (not promoted) to other public types

```suggestion
            // practical perspective, we get a better user experience by trusting the
```

**Review by AlexWaygood — APPROVED** [review]
Awesome!!

On this PR branch, we still union with `Unknown` here -- perhaps we should infer `str` there?

```py
def f(x="foo"):
    reveal_type(x)  # Literal["foo"] | Unknown
```

I'm okay postponing that to a follow-up PR, though.

**Comment by AlexWaygood** [comment]
> Conformance suite results are positive, and add one newly-passing file.

(FWIW I believe we're already scored as passing that file on the upstream repo — we use the `ignore_errors` field upstream).)

**Comment by carljm** [comment]
> On this PR branch, we still union with Unknown here -- perhaps we should infer str there?

```py
def f(x="foo"):
    reveal_type(x)  # Literal["foo"] | Unknown
```

No, I think the union with `Unknown` is necessary and correct there, it's not just gradual-guarantee conservatism. The parameter is un-annotated (in other words its declared type is `Unknown`), so it can be called with an argument of any type. The default being `"foo"` only means that it definitely _could_ be `"foo"`, so our type considers that -- but it could also be literally anything else.

File: crates/ty_python_semantic/resources/mdtest/doc/public_type_undeclared_symbols.md (hunk 2 above)
Comment (carljm) [reply crates/ty_python_semantic/resources/mdtest/doc/public_type_undeclared_symbols.md:70]: Good call; I actually added a couple full tests with examples of this (both for preventing literal promotion and preventing singleton widening with `Unknown`).

File: crates/ty_python_semantic/resources/mdtest/snapshots/invalid_await.md_-_Invalid_await_diagno…_-_Non-callable_`__awai…_(d78580fb6720e4ea).snap (hunk 3 above)
Comment (carljm) [reply crates/ty_python_semantic/resources/mdtest/snapshots/invalid_await.md_-_Invalid_await_diagno…_-_Non-callable_`__awai…_(d78580fb6720e4ea).snap:37]: Yeah, this is a pre-existing / separate issue, so I think it should be addressed separately. The change happening in this PR is just that before we had a union with `Unknown` for the type of `__await__`, and now we don't.

**Comment by AlexWaygood** [comment]
> No, I think the union with `Unknown` is necessary and correct there, it's not just gradual-guarantee conservatism. The parameter is un-annotated (in other words its declared type is `Unknown`), so it can be called with an argument of any type. The default being `"foo"` only means that it definitely _could_ be `"foo"`, so our type considers that -- but it could also be literally anything else.

There's some interesting disagreement among type checkers on that point. Pyrefly and pycroscope agree with you here, and reveal `Literal["foo"] | Unknown`. Mypy and Zuban basically agree with you too, revealing `Any`. Pyright goes ahead and reveals `str`.

I agree with your analysis, though; `Literal["foo"] | Unknown` really does seem better in this case.

File: crates/ty_python_semantic/src/types/call/bind.rs (hunk 4 above)
Comment (carljm) [reply crates/ty_python_semantic/src/types/call/bind.rs:3799]: Good call, didn't read this full comment carefully enough. Restored a version of it with `Unknown` mention removed.

**Comment by carljm** [comment]
I had to think through briefly in what cases it would actually make a difference, since this is an inferred type, not a declared type, so it's generally not being used as an "upper bound" type (it's generally being assigned-from, not assigned-to). The fact that it often won't matter is probably why pyright gets away with being wrong here. But there definitely are cases where it matters: probably the worst would be considering `if not isinstance(x, str):` to be unreachable. It would also change the way we'd phrase some diagnostics, e.g. "might not be callable" vs "definitely is not callable".

File: crates/ty_python_semantic/src/place.rs (hunk 5 above)
Comment (carljm) [reply crates/ty_python_semantic/src/place.rs]: Great call, I'd actually missed the fact that we don't promote there. I think we probably should, for anything non-final? Agree it should be a separate PR.

**Comment by carljm** [comment]
Oh, pyright's behavior is more correct here than I realized. It doesn't just infer `str` as the type of `x` internal to the function, it also infers the "declared" parameter type as being `str`, based on the signal from the default value. So it will error if you try to pass a non-str.

That's actually pretty reasonable behavior IMO, and does parallel the (non-gradual-guarantee) way we treat un-annotated attributes after this PR. And gives better LSP experience for un-annotated code. So I wouldn't necessarily be opposed to exploring that as a follow-up. But I'd kind of want to wait for an actual user request.

**Review by AlexWaygood — APPROVED** [review]

File: crates/ty_python_semantic/resources/mdtest/snapshots/invalid_await.md_-_Invalid_await_diagno…_-_Non-callable_`__awai…_(d78580fb6720e4ea).snap (hunk 3 above)
Comment (carljm) [reply crates/ty_python_semantic/resources/mdtest/snapshots/invalid_await.md_-_Invalid_await_diagno…_-_Non-callable_`__awai…_(d78580fb6720e4ea).snap:37]: https://github.com/astral-sh/ty/issues/3250 so we don't lose it -- though I'm not making it a stable blocker.

**Comment by carljm** [comment]
https://github.com/astral-sh/ty/issues/3251 to consider the pyright approach to un-annotated arguments with defaults.

File: crates/ty_python_semantic/src/place.rs (hunk 5 above)
Comment (carljm) [reply crates/ty_python_semantic/src/place.rs]: https://github.com/astral-sh/ty/issues/3253 -- already working on this.
