### PR TITLE
[`refurb`] `FURB164` fix should validate arguments and should usually be marked unsafe

### LINKED ISSUE #19076: FURB164 fix should validate arguments and should usually be marked unsafe
### Summary

The fix for [`unnecessary-from-float` (FURB164)](https://docs.astral.sh/ruff/rules/unnecessary-from-float/) does not validate argument lists, so it can change the program’s behavior. It should be considered unsafe by default with a few exceptions based on type inference. When the original code is invalid, the fix should be suppressed. When the fixed code is invalid, the fix should be suppressed. When both are valid and the original uses keyword arguments, the fix should remove the keywords, because the recommended constructors do not use the same keywords. [`Decimal.from_float`](https://docs.python.org/3/library/decimal.html#decimal.Decimal.from_float) has exactly one positional-only parameter. [`Fraction.from_decimal`](https://docs.python.org/3/library/fractions.html#fractions.Fraction.from_decimal) has exactly one positional-or-keyword parameter, `dec`. [`Fraction.from_float`](https://docs.python.org/3/library/fractions.html#fractions.Fraction.from_float) has exactly one positional-or-keyword parameter, `f`.

[Behavior changes](https://play.ruff.rs/553ed43a-9747-4e1f-89fc-9e6f38cfee01):
```console
$ cat >furb164_1.py <<'# EOF'
from decimal import Decimal
from fractions import Fraction

try: print(Fraction.from_decimal(dec=Decimal("4.2")))
except Exception as e: print(f"{type(e).__name__}: {e}")

try: print(Fraction.from_decimal(Decimal("4.2"), 1))
except Exception as e: print(f"{type(e).__name__}: {e}")

try: print(Decimal.from_float(4.2, None))
except Exception as e: print(f"{type(e).__name__}: {e}")

try: print(Fraction.from_decimal(numerator=Decimal("4.2")))
except Exception as e: print(f"{type(e).__name__}: {e}")
# EOF

$ python furb164_1.py
21/5
TypeError: Fraction.from_decimal() takes 2 positional arguments but 3 were given
TypeError: Decimal.from_float() takes exactly one argument (2 given)
TypeError: Fraction.from_decimal() got an unexpected keyword argument 'numerator'

$ ruff --isolated check furb164_1.py --select FURB164 --preview --fix
Found 4 errors (4 fixed, 0 remaining).

$ python furb164_1.py
TypeError: Fraction.__new__() got an unexpected keyword argument 'dec'
TypeError: both arguments should be Rational instances
4.20000000000000017763568394002504646778106689453125
21/5
```

If the original expression raises a `TypeError`, the fix can make it raise a different `TypeError`. Although that is safe, there is probably a bug in the original code, so it is not clear what the user intended and it would be better to suppress the fix. It is still useful for the rule to raise a diagnostic. [Examples](https://play.ruff.rs/c4b89bfe-819c-4864-a2ba-acd668327a5d):
```console
$ cat >furb164_2.py <<'# EOF'
from decimal import Decimal
from fractions import Fraction

try: print(Decimal.from_float(f=4.2))
except Exception as e: print(f"{type(e).__name__}: {e}")

try: print(Fraction.from_decimal(Decimal("4.2"), 1))
except Exception as e: print(f"{type(e).__name__}: {e}")
# EOF

$ python furb164_2.py
TypeError: Decimal.from_float() takes no keyword arguments
TypeError: Fraction.from_decimal() takes 2 positional arguments but 3 were given

$ ruff --isolated check furb164_2.py --select FURB164 --preview --fix
Found 2 errors (2 fixed, 0 remaining).

$ python furb164_2.py
TypeError: 'f' is an invalid keyword argument for this function
TypeError: both arguments should be Rational instances
```

`from_float` and `from_decimal` are not redundant with the constructors: they validate the types of their inputs. The fix removes that validation, which can change behavior. [Examples](https://play.ruff.rs/28474b29-12dc-46b4-9811-fcdc52aff528):
```console
$ cat >furb164_3.py <<'# EOF'
from decimal import Decimal
from fractions import Fraction

try: print(Decimal.from_float("4.2"))
except Exception as e: print(f"{type(e).__name__}: {e}")

try: print(Fraction.from_decimal(4.2))
except Exception as e: print(f"{type(e).__name__}: {e}")

try: print(Fraction.from_float("4.2"))
except Exception as e: print(f"{type(e).__name__}: {e}")
# EOF

$ python furb164_3.py
TypeError: argument must be int or float
TypeError: Fraction.from_decimal() only takes Decimals, not 4.2 (float)
TypeError: Fraction.from_float() only takes floats, not '4.2' (str)

$ ruff --isolated check furb164_3.py --select FURB164 --preview --fix
Found 3 errors (3 fixed, 0 remaining).

$ python furb164_3.py
4.2
4728779608739021/1125899906842624
21/5
```
The fix should be marked unsafe except when the argument is known to be of a valid type. `Decimal.from_float` and `Fraction.from_float` accept `int`, `bool`, and `float`. `Fraction.from_decimal` accepts `int`, `bool`, and `Decimal`. The fix is also safe when it simplifies a non-finite float as in `Decimal.from_float(float("inf"))` to `Decimal("inf")`. Ruff’s `ResolvedPythonType`, `typing::is_float`, and `typing::is_int` may be useful here.

### Version

ruff 0.12.1 (32c54189c 2025-06-26)

### PR DESCRIPTION
**Pull request by danparizher**
## Summary

Fixes #19076

An attempt at fixing #19076 where the rule could change program behavior by incorrectly converting from_float/from_decimal method calls to constructor calls.

The fix implements argument validation using Ruff's existing type inference system (`ResolvedPythonType`, `typing::is_int`, `typing::is_float`) to determine when conversions are actually safe, adds logic to detect invalid method calls (wrong argument counts, incorrect keyword names) and suppress fixes for them, and changes the default fix applicability from `Safe` to `Unsafe` with safe fixes only offered when the argument type is known to be compatible and no problematic keywords are used.

One uncertainty is whether the type inference catches all possible edge cases in complex codebases, but the new approach is significantly more conservative and safer than the previous implementation.

## Test Plan

I updated the existing test fixtures with edge cases from the issue and manually verified behavior with temporary test files for valid/unsafe/invalid scenarios.

### CODE REVIEW

File: crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs [hunk 1]
```diff
@@ -59,6 +77,131 @@ impl Violation for UnnecessaryFromFloat {
     }
 }
 
+/// Check if the argument would be valid for the target constructor
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs]: nit: we tend to keep the main rule function at the top of the file, followed by any helpers.

File: crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs [hunk 2]
```diff
@@ -59,6 +77,131 @@ impl Violation for UnnecessaryFromFloat {
...
+                            semantic.only_binding(name).map(|id| semantic.binding(id))
+                        {
+                            typing::is_int(binding, semantic)
+                        } else {
+                            false
+                        }
+                    } else {
+                        false
+                    }
+                }
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs]: The nested `match`es look very similar in all three branches here. Could we possibly do the `resolve_type` match first and then the method and constructor match? It looks like we might need to save `is_int` and `is_float` variables to check later.

File: crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs [hunk 3]
```diff
@@ -59,6 +77,131 @@ impl Violation for UnnecessaryFromFloat {
...
+            if call.arguments.args.len() == 1 && call.arguments.keywords.is_empty() {
+                true
+            } else if call.arguments.args.is_empty() && call.arguments.keywords.len() == 1 {
+                call.arguments.keywords[0]
+                    .arg
+                    .as_ref()
+                    .is_some_and(|name| name.as_str() == "f")
+            } else {
+                false
+            }
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs]: I _think_ this could be simplified by checking `call.arguments.len()` which should account for both `args` and `keywords` and then using `find_argument` to locate it by name or position:


```suggestion
            // from_float(f) - should have exactly one positional argument or 'f' keyword
            if call.arguments.len() != 1 {
                false
            } else {
                call.arguments.find_argument("f", 0).is_some()
            }
```

File: crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs [hunk 4]
```diff
@@ -59,6 +77,131 @@ impl Violation for UnnecessaryFromFloat {
...
+        }
+        MethodName::FromDecimal => {
+            // from_decimal(dec) - should have exactly one positional argument or 'dec' keyword
+            if call.arguments.args.len() == 1 && call.arguments.keywords.is_empty() {
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs]: Same as above, if it works above.

File: crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs (hunk 3 above)
Comment (ntBre) [reply crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs]: We may also need to match on the constructor here. `Decimal.from_float` is positional-only, unless that's checked somewhere else:

```pycon
>>> from decimal import Decimal
>>> Decimal.from_float(f=123)
Traceback (most recent call last):
  File "<python-input-7>", line 1, in <module>
    Decimal.from_float(f=123)
    ~~~~~~~~~~~~~~~~~~^^^^^^^
TypeError: Decimal.from_float() takes no keyword arguments
```

File: crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs [hunk 5]
```diff
@@ -93,6 +236,19 @@ pub(crate) fn unnecessary_from_float(checker: &Checker, call: &ExprCall) {
...
+        // Don't suggest a fix for invalid calls
+        checker.report_diagnostic(
+            UnnecessaryFromFloat {
+                method_name,
+                constructor,
+            },
+            call.range(),
+        );
+        return;
+    }
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs]: We should just move this check after the other `report_diagnostic` call instead of duplicating the construction.

```suggestion
    // Validate that the method call has correct arguments
    if !has_valid_method_arguments(call, method_name) {
        // Don't suggest a fix for invalid calls
        return;
    }
```

This would have made more sense when we used to have to create a diagnostic and later push it to the `Checker`, but merely creating the diagnostic now will set it up to be pushed on `Drop` so we can just return after creating it.

File: crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs [hunk 6]
```diff
@@ -101,62 +257,92 @@ pub(crate) fn unnecessary_from_float(checker: &Checker, call: &ExprCall) {
...
 
-    let edit = Edit::range_replacement(
-        checker.locator().slice(&**value).to_string(),
-        call.func.range(),
-    );
+    // Get the argument value
+    let arg_value = match method_name {
+        MethodName::FromFloat => call.arguments.find_argument_value("f", 0),
+        MethodName::FromDecimal => call.arguments.find_argument_value("dec", 0),
+    };
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs]: It might make sense to return an `Option` from `has_valid_method_arguments` instead of finding the argument values again here.

File: crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs [hunk 7]
```diff
@@ -101,62 +257,92 @@ pub(crate) fn unnecessary_from_float(checker: &Checker, call: &ExprCall) {
...
+        return None;
+    }
+    let [float_arg] = arguments.args.as_ref() else {
+        return None;
+    };
+    as_non_finite_float_string_literal(float_arg)?;
+
+    // Must be a call to the `float` builtin.
+    if !checker.semantic().match_builtin_expr(func, "float") {
+        return None;
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs]: nit: I'd probably put this right after the `let-else` checking that it's a `Call`. I'm not sure which of these checks is most expensive, but that makes sense logically at least.

**Review by ntBre — COMMENTED** [review]
Thanks, this looks good to me. I just had some suggestions for simplifying the code a bit.

File: crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs [hunk 8]
```diff
@@ -302,6 +160,109 @@ pub(crate) fn unnecessary_from_float(checker: &Checker, call: &ExprCall) {
...
+                (
+                    typing::is_int(binding, semantic),
+                    typing::is_float(binding, semantic),
+                )
+            } else {
+                (false, false)
+            }
+        } else {
+            (false, false)
+        }
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs]:
```suggestion
        arg_expr
            .as_name_expr()
            .and_then(|name| semantic.only_binding(name).map(|id| semantic.binding(id)))
            .map(|binding| {
                (
                    typing::is_int(binding, semantic),
                    typing::is_float(binding, semantic),
                )
            })
            .unwrap_or_default()
```

File: crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs [hunk 9]
```diff
@@ -302,6 +160,109 @@ pub(crate) fn unnecessary_from_float(checker: &Checker, call: &ExprCall) {
...
+                // Check if it's a Decimal instance
+                if let Expr::Call(call) = arg_expr {
+                    if let Some(qualified_name) = semantic.resolve_qualified_name(&call.func) {
+                        matches!(qualified_name.segments(), ["decimal", "Decimal"])
+                    } else {
+                        false
+                    }
+                } else {
+                    false
+                }
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs]:
```suggestion
                arg_expr
                    .as_call_expr()
                    .and_then(|call| semantic.resolve_qualified_name(&call.func))
                    .is_some_and(|qualified_name| {
                        matches!(qualified_name.segments(), ["decimal", "Decimal"])
                    })
```

File: crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs [hunk 10]
```diff
@@ -302,6 +160,109 @@ pub(crate) fn unnecessary_from_float(checker: &Checker, call: &ExprCall) {
...
+                None
+            } else if constructor == Constructor::Decimal {
+                // Only allow positional argument for Decimal.from_float
+                if call.arguments.find_argument("f", 0).is_some()
+                    && call.arguments.keywords.is_empty()
+                {
+                    call.arguments.find_argument_value("f", 0)
+                } else {
+                    None
+                }
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs]:
```suggestion
                call.arguments.find_positional(0)
```

File: crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs [hunk 11]
```diff
@@ -302,6 +160,109 @@ pub(crate) fn unnecessary_from_float(checker: &Checker, call: &ExprCall) {
...
+    call: &ExprCall,
+    method_name: MethodName,
+    constructor: Constructor,
+) -> Option<&Expr> {
+    match method_name {
+        MethodName::FromFloat => {
+            // Decimal.from_float is positional-only; Fraction.from_float allows keyword 'f'.
+            if call.arguments.len() != 1 {
+                None
+            } else if constructor == Constructor::Decimal {
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs]: I see now that we could actually convert the `len` check to an early return since it's shared by both branches:


```suggestion
    if call.arguments.len() != 1 {
        return None;
    }
    
    match method_name {
        MethodName::FromFloat => {
            // Decimal.from_float is positional-only; Fraction.from_float allows keyword 'f'.
            if constructor == Constructor::Decimal {
```

File: crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs [hunk 12]
```diff
@@ -302,6 +160,109 @@ pub(crate) fn unnecessary_from_float(checker: &Checker, call: &ExprCall) {
...
+                call.arguments.find_argument_value("f", 0)
+            }
+        }
+        MethodName::FromDecimal => {
+            // from_decimal(dec) - should have exactly one positional argument or 'dec' keyword
+            if call.arguments.len() == 1 {
+                call.arguments.find_argument_value("dec", 0)
+            } else {
+                None
+            }
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/refurb/rules/unnecessary_from_float.rs]:
```suggestion
            call.arguments.find_argument_value("dec", 0)
```

after the early return above.

**Review by ntBre — APPROVED** [review]
Thanks! Just a few more slight simplifications.
