### PR TITLE
Make `ARG002` compatible with `EM101` when raising `NotImplementedError`

### LINKED ISSUE #12427: When raising `NotImplementedError `, ARG002 and EM101 are incompatible.
[ARG002](https://docs.astral.sh/ruff/rules/unused-method-argument/) is usually not raised in methods that immediately raise a `NotImplementedError`, but does if there is some other code in the method. However, [EM101](https://docs.astral.sh/ruff/rules/raw-string-in-exception/) enforces adding the error message into a separate variable, which is then seen as "code".

The result of this is that there is no way to write such a method without raising one or the other issue. See example below.

```python
class EM101_found:
    def test_method(self, **kwargs):
        raise NotImplementedError("error message.")


class ARG002_found:
    def test_method(self, **kwargs):
        msg = "error message"
        raise NotImplementedError(msg)
```

running `ruff check test_file.py --select ARG002 --select EM101` on the code snippet above results in
> test_file.py:3:35: EM101 Exception must not use a string literal, assign to variable first
> test_file.py:7:29: ARG002 Unused method argument: `kwargs`
> Found 2 errors.

### PR DESCRIPTION
**Pull request by Watercycle**
## Summary

This pull request resolves some rule thrashing identified in #12427 by allowing for unused arguments when using `NotImplementedError` with a variable per [this comment](https://github.com/astral-sh/ruff/issues/12427#issuecomment-2384727468).

**Note**

This feels a little heavy-handed / edge-case-prone. So, to be clear, I'm happy to scrap this code and just update the docs to communicate that `abstractmethod` and friends should be used in this scenario (or similar). Just let me know what you'd like done!

fixes: #12427 

## Test Plan

I added a test-case to the existing `ARG.py` file and ran...

```sh
cargo run -p ruff -- check crates/ruff_linter/resources/test/fixtures/flake8_unused_arguments/ARG.py --no-cache --preview --select ARG002
```

### CODE REVIEW

File: crates/ruff_linter/src/rules/flake8_unused_arguments/rules/unused_arguments.rs [hunk 1]
```diff
@@ -311,6 +311,71 @@ fn call<'a>(
...
+/// See also [`is_stub`]. We're a bit more generous in what is considered a
+/// stub in this rule to avoid clashing with [`EM101`].
+///
+/// [`is_stub`]: function_type::is_stub
+/// [`EM101`]: https://docs.astral.sh/ruff/rules/raw-string-in-exception/
+fn is_not_implemented_stub_with_variable(function_def: &StmtFunctionDef) -> bool {
+    // Ignore doc-strings.
+    let statements = match function_def.body.as_slice() {
+        [Stmt::Expr(StmtExpr { value, .. }), rest @ ..]
+            if matches!(value.as_ref(), ast::Expr::StringLiteral(_)) =>
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_unused_arguments/rules/unused_arguments.rs:331]: Nit:

```suggestion
            if matches!(**value, ast::Expr::StringLiteral(_)) =>
```

File: crates/ruff_linter/src/rules/flake8_unused_arguments/rules/unused_arguments.rs [hunk 2]
```diff
@@ -311,6 +311,71 @@ fn call<'a>(
...
+    let [first_stmt, second_stmt] = statements else {
+        return false;
+    };
+
+    let Stmt::Assign(ast::StmtAssign { value, .. }) = first_stmt else {
+        return false;
+    };
+
+    if !matches!(
+        value.as_ref(),
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_unused_arguments/rules/unused_arguments.rs:347]: Nit:
```suggestion
        **value,
```

File: crates/ruff_linter/src/rules/flake8_unused_arguments/rules/unused_arguments.rs [hunk 3]
```diff
@@ -311,6 +311,71 @@ fn call<'a>(
...
+        return false;
+    }
+
+    let Stmt::Raise(StmtRaise {
+        exc: Some(exception),
+        ..
+    }) = second_stmt
+    else {
+        return false;
+    };
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_unused_arguments/rules/unused_arguments.rs:359]: Nit:
```suggestion
    let [Stmt::Assign(ast::StmtAssign { value, .. }), Stmt::Raise(StmtRaise {
        exc: Some(exception),
        ..
    })] = statements
    else {
        return false;
    };
    
    if !matches!(
        value.as_ref(),
        ast::Expr::StringLiteral(_) | ast::Expr::FString(_)
    ) {
        return false;
    }
```

File: crates/ruff_linter/src/rules/flake8_unused_arguments/rules/unused_arguments.rs [hunk 4]
```diff
@@ -311,6 +311,71 @@ fn call<'a>(
...
+
+    let ast::Expr::Call(ast::ExprCall {
+        func, arguments, ..
+    }) = exception.as_ref()
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_unused_arguments/rules/unused_arguments.rs:363]: Nit:
```suggestion
    }) = &**exception
```

File: crates/ruff_linter/src/rules/flake8_unused_arguments/rules/unused_arguments.rs [hunk 5]
```diff
@@ -311,6 +311,71 @@ fn call<'a>(
...
+    else {
+        return false;
+    };
+
+    if !matches!(func.as_ref(), ast::Expr::Name(name) if name.id == "NotImplementedError") {
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_unused_arguments/rules/unused_arguments.rs:368]:
```suggestion
    if !matches!(**func, ast::Expr::Name(name) if name.id == "NotImplementedError") {
```

**Review by MichaReiser — APPROVED** [review]
This looks good to me. Would you mind adding a test string with an f-string message?

File: crates/ruff_linter/src/rules/flake8_unused_arguments/rules/unused_arguments.rs (hunk 4 above)
Comment (Watercycle) [reply crates/ruff_linter/src/rules/flake8_unused_arguments/rules/unused_arguments.rs]: I see mixed usages of `&**` and `as_ref` throughout the code base. Out of curiosity, when is one used over the other? The general heuristic I've seen is `*` and `&` are recommended for simple stuff; and, once you start de-referencing and re-borrowing, that `as_ref` is recommended if just to avoid needing to think about whatever container the variable is in.

File: crates/ruff_linter/src/rules/flake8_unused_arguments/rules/unused_arguments.rs [hunk 6]
```diff
@@ -311,6 +311,63 @@ fn call<'a>(
...
+/// [`is_stub`]: function_type::is_stub
+/// [`EM101`]: https://docs.astral.sh/ruff/rules/raw-string-in-exception/
+fn is_not_implemented_stub_with_variable(function_def: &StmtFunctionDef) -> bool {
+    // Ignore doc-strings.
+    let statements = match function_def.body.as_slice() {
+        [Stmt::Expr(StmtExpr { value, .. }), rest @ ..]
+            if matches!(**value, ast::Expr::StringLiteral(_)) =>
+        {
+            rest
+        }
```
Comment (dhruvmanila) [inline crates/ruff_linter/src/rules/flake8_unused_arguments/rules/unused_arguments.rs:334]: nit: we could directly use the `is_string_literal_expr` method here
```suggestion
        [Stmt::Expr(StmtExpr { value, .. }), rest @ ..] if value.is_string_literal_expr() => rest,
```

File: crates/ruff_linter/src/rules/flake8_unused_arguments/rules/unused_arguments.rs [hunk 7]
```diff
@@ -311,6 +311,63 @@ fn call<'a>(
...
+        return false;
+    };
+
+    if !matches!(&**func, ast::Expr::Name(name) if name.id == "NotImplementedError") {
+        return false;
+    }
+
+    if arguments.len() != 1 {
+        return false;
+    }
```
Comment (dhruvmanila) [inline crates/ruff_linter/src/rules/flake8_unused_arguments/rules/unused_arguments.rs:366]: I think we'd also need to make sure that the variable that is being referenced in the call to `NotImplementedError` is the same as the one in the assignment. I think there must be some method in the `SemanticModel` to get the binding for the `ExprName` node (possibly `resolve_name`?).

Or, actually we can get away with just comparing the string i.e., whether the name of the variable that is being assigned is the same as the one used in the `NotImplementedError` call because we make sure that there are only two statements in the function body above.

**Review by dhruvmanila — APPROVED** [review]
Thanks for the PR!

I made a few final changes:
* We should match the assignment target and argument node exactly. Previously, if either of them isn't a name node, the function would return true.
* Added some more test cases where `ARG002` should be raised

**Comment by dhruvmanila** [comment]
Going to wait for ecosystem checks and then merge.

File: crates/ruff_linter/src/rules/flake8_unused_arguments/rules/unused_arguments.rs (hunk 4 above)
Comment (MichaReiser) [reply crates/ruff_linter/src/rules/flake8_unused_arguments/rules/unused_arguments.rs]: We used to use `as_ref` but started to prefer dereferencing (except for `Option` where you still need `as_ref` and `as_deref`) because it's possible that `as_ref` becomes ambiguous if a new `AsRef` implementation is added to a type. For example, `String` has many `as_ref` methods:

```
  = note: multiple `impl`s satisfying `String: AsRef<_>` found in the following crates: `alloc`, `std`:
          - impl AsRef<OsStr> for String;
          - impl AsRef<Path> for String;
          - impl AsRef<[u8]> for String;
          - impl AsRef<str> for String;
```

File: crates/ruff_linter/src/rules/flake8_unused_arguments/rules/unused_arguments.rs [hunk 8]
```diff
@@ -311,6 +311,60 @@ fn call<'a>(
...
+    let ast::Expr::Call(ast::ExprCall {
+        func, arguments, ..
+    }) = &**exception
+    else {
+        return false;
+    };
+
+    if !matches!(&**func, ast::Expr::Name(name) if name.id == "NotImplementedError") {
+        return false;
+    }
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_unused_arguments/rules/unused_arguments.rs:355]: We should probably use the semantic model to verify that `NotImplementedError` is the built-in `NotImplementedError`

Comment (dhruvmanila) [reply crates/ruff_linter/src/rules/flake8_unused_arguments/rules/unused_arguments.rs:355]: Oh, good catch.

File: crates/ruff_linter/src/rules/flake8_unused_arguments/rules/unused_arguments.rs (hunk 4 above)
Comment (Watercycle) [reply crates/ruff_linter/src/rules/flake8_unused_arguments/rules/unused_arguments.rs]: Oh interesting, that makes sense! Thank you!

**Comment by Watercycle** [comment]
> I made a few final changes:

Thank you for fixing it up! I noticed the snapshot test didn't get updated after committing and thought "this can be Sunday's problem" 😅
