### PR TITLE
[flake8-bandit] Fix S103 false positives and negatives in mask analysis

### LINKED ISSUE #18863: `bad-file-permissions` (S103) has false negatives and false positives
### Summary

[`bad-file-permissions` (S103)](https://docs.astral.sh/ruff/rules/bad-file-permissions/) has false negatives and false positives.

[The upstream rule checks `0o33`](https://github.com/PyCQA/bandit/blob/1.8.5/bandit/plugins/general_bad_file_permissions.py#L63-L69) but Ruff’s S103 only checks `0o12`.
```console
$ cat >s103_1.py <<'# EOF'
import os
os.chmod("/etc/secrets.txt", 0o21)
# EOF

$ flake8 ./s103_1.py
./s103_1.py:2:1: S103 Chmod setting a permissive mask 0o21 on file (/etc/secrets.txt).

$ ruff --isolated check s103_1.py --select S103
All checks passed!
```

Only the bits of `0o33` matter for the permissiveness check. S103 should not be suppressed when those bits can statically be determined in the result of a bitwise OR, even when the full result can’t.
```python
import os
def f(path, mode):
    os.chmod(path, mode | 0o777)
```

There is a false positive when the result of a bitwise AND can statically be determined to be valid, even when a subexpression has an invalid value.
```python
$ cat >s103_2.py <<'# EOF'
import os
os.chmod("/etc/secrets.txt", 0o777777 & 0o700)
os.chmod("/etc/secrets.txt", 0o777777 & 0o777)  # This is a true positive for the wrong reason.
# EOF

$ ruff --isolated check s103_2.py --select S103 --output-format concise -q
s103_2.py:2:30: S103 `os.chmod` setting an invalid mask on file or directory
s103_2.py:3:30: S103 `os.chmod` setting an invalid mask on file or directory
```

### Version

ruff 0.12.0 (87f0feb21 2025-06-17)

### PR DESCRIPTION
**Pull request by anishgirianish**
## Summary

 Fixes #18863 

Rewrites `parse_mask` as a known-bits abstract domain over `u64`, so partial bitwise expressions (`|`,`&`, `^`) are tracked through unknown operands. This fixes:

- `mode | 0o777` — previously unflagged, now reports the statically-known dangerous bits.
- `0o777777 & 0o700` — previously a false positive (u16 overflow), now correctly silent.
- `0o777777 & 0o777` — now flagged as permissive, not "invalid mask".

"Invalid mask" now triggers when a bit outside `0o7777` is statically set, keeping `0o1000` (sticky) valid per  RUF064 note.

Under preview, the dangerous-bit set matches upstream Bandit (`0o33`) instead of the current `0o12`. 

## Test Plan

- New fixture cases for each repro + partial `|`/`&` edges; stable snapshot updated, preview diff snapshot added.
- `cargo nextest run -p ruff_linter -- flake8_bandit` .
- Ecosystem checks ran locally

### CODE REVIEW

File: crates/ruff_linter/src/rules/flake8_bandit/rules/bad_file_permissions.rs [hunk 1]
```diff
@@ -147,41 +178,51 @@ fn py_stat(qualified_name: &QualifiedName) -> Option<u16> {
...
-        },
-        Expr::Attribute(_) => Ok(semantic
+        }) => int.as_u64().map(KnownBits::exact).unwrap_or_else(|| {
+            // Python ints can be arbitrarily large; anything that
+            // doesn't fit in `u64` has at least one bit set above
+            // `VALID_BITS`, so treat it as definitely invalid.
+            KnownBits {
+                ones: !VALID_BITS,
+                zeros: 0,
+            }
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_bandit/rules/bad_file_permissions.rs]: Nit: Maybe consider adding an `KnownBits::invalid` helper to make the code here a little more expressive.

File: crates/ruff_linter/src/rules/flake8_bandit/rules/bad_file_permissions.rs [hunk 2]
```diff
@@ -147,41 +178,51 @@ fn py_stat(qualified_name: &QualifiedName) -> Option<u16> {
...
+                Operator::BitXor => KnownBits {
+                    ones: (left_bits.ones & right_bits.zeros) | (left_bits.zeros & right_bits.ones),
+                    zeros: (left_bits.ones & right_bits.ones)
+                        | (left_bits.zeros & right_bits.zeros),
+                },
+                _ => KnownBits::default(),
+            }
         }
-        _ => Ok(None),
+        _ => KnownBits::default(),
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_bandit/rules/bad_file_permissions.rs]: I suggest adding an `unknown` method to make the semantics here clearer.

File: crates/ruff_linter/src/rules/flake8_bandit/rules/bad_file_permissions.rs [hunk 3]
```diff
@@ -147,41 +178,51 @@ fn py_stat(qualified_name: &QualifiedName) -> Option<u16> {
...
-            };
-            Ok(match op {
-                Operator::BitAnd => Some(left_value & right_value),
-                Operator::BitOr => Some(left_value | right_value),
-                Operator::BitXor => Some(left_value ^ right_value),
-                _ => None,
-            })
+            let left_bits = parse_mask(left, semantic);
+            let right_bits = parse_mask(right, semantic);
+            match op {
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_bandit/rules/bad_file_permissions.rs:226]: We'll have to be a bit more careful here when combining `parse_mask` when either value is larger than a `u64`. 

> Example: `1208925819614629174706176` & `0o200000` (which evaluates to 0) is reported as invalid.

I think it's fine if the rule has a few false negatives for permissions larger than a u64, but we should avoid false positives.

File: crates/ruff_linter/src/rules/flake8_bandit/rules/bad_file_permissions.rs (hunk 1 above)
Comment (anishgirianish) [reply crates/ruff_linter/src/rules/flake8_bandit/rules/bad_file_permissions.rs]: Added KnownBits::invalid(). thanks

File: crates/ruff_linter/src/rules/flake8_bandit/rules/bad_file_permissions.rs (hunk 2 above)
Comment (anishgirianish) [reply crates/ruff_linter/src/rules/flake8_bandit/rules/bad_file_permissions.rs]: Done, replaced all default() calls with unknown(). Thank you

File: crates/ruff_linter/src/rules/flake8_bandit/rules/bad_file_permissions.rs (hunk 3 above)
Comment (anishgirianish) [reply crates/ruff_linter/src/rules/flake8_bandit/rules/bad_file_permissions.rs:226]: Added an oversized: bool field to KnownBits, ints > u64, no longer claims specific bits. AND clears the flag, OR/XOR preserves it. Your example now correctly produces no diagnostic. Also guarded the Permissive check with is_fully_known() to fix the ecosystem FP. Thank you

**Comment by anishgirianish** [comment]
@MichaReiser  Thank you so much for the review. Addressed all three comments:                                                                                      

1. Added KnownBits::invalid() helper                                                                                                      
2. Added KnownBits::unknown(), replaced all default() calls                                                                               
3. Fixed the large-int false positive with an oversized flag on KnownBits, also resolved the ecosystem FP by guarding the Permissive check with is_fully_known()                                                                                                               
   
Would like to request you for another look whenever you get a chance.

Thank you

File: crates/ruff_linter/src/rules/flake8_bandit/rules/bad_file_permissions.rs [hunk 4]
```diff
@@ -71,40 +77,91 @@ pub(crate) fn bad_file_permissions(checker: &Checker, call: &ast::ExprCall) {
...
+const DANGEROUS_BITS_PREVIEW: u64 = 0o33;
+/// The 12 bits that make up a valid Unix permission mask: the rwx-triplets
+/// for user/group/other plus setuid, setgid, and the sticky bit.
+const VALID_BITS: u64 = 0o7777;
+
+/// Known-bits abstract value for a `u64`: `ones` are the bits that are
+/// statically known to be 1, `zeros` are the bits that are statically known
+/// to be 0. An expression whose value is fully known satisfies
+/// `ones | zeros == u64::MAX`; an expression whose value is entirely unknown
+/// has `ones == 0 && zeros == 0`.
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_bandit/rules/bad_file_permissions.rs]: This section needs updating now that you added `oversized`

File: crates/ruff_linter/src/rules/flake8_bandit/rules/bad_file_permissions.rs [hunk 5]
```diff
@@ -147,41 +204,49 @@ fn py_stat(qualified_name: &QualifiedName) -> Option<u16> {
...
+                Operator::BitAnd => KnownBits {
+                    ones: left_bits.ones & right_bits.ones,
+                    zeros: left_bits.zeros | right_bits.zeros,
+                    oversized: left_bits.oversized && right_bits.oversized,
+                },
+                Operator::BitXor => KnownBits {
+                    ones: (left_bits.ones & right_bits.zeros) | (left_bits.zeros & right_bits.ones),
+                    zeros: (left_bits.ones & right_bits.ones)
+                        | (left_bits.zeros & right_bits.zeros),
+                    oversized: left_bits.oversized || right_bits.oversized,
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_bandit/rules/bad_file_permissions.rs]: There's one remaining false positive when both are oversized:

```py
os.chmod("/tmp/x", 18446744073709551616 ^ 18446744073709551616)
```

I think it's fine to have this as a false positive, but let's add it as a test and document that this is a known false positive (as it should be very unlikely). 

Or you could use `ComparableExpr` and compare the left and right if their `KnownBits` are equal.

File: crates/ruff_linter/src/rules/flake8_bandit/rules/bad_file_permissions.rs (hunk 4 above)
Comment (anishgirianish) [reply crates/ruff_linter/src/rules/flake8_bandit/rules/bad_file_permissions.rs]: Updated both invariants in the doc comment to mention oversized. Thanks

File: crates/ruff_linter/src/rules/flake8_bandit/rules/bad_file_permissions.rs (hunk 5 above)
Comment (anishgirianish) [reply crates/ruff_linter/src/rules/flake8_bandit/rules/bad_file_permissions.rs]: Thank you so much for the suggestion! Went with the ComparableExpr approach and added a test case.

**Comment by anishgirianish** [comment]
@MichaReiser  Thank you so much for the re-review. Addressed both comments, would appreciate another look whenever you get a chance.

Thank you

**Comment by MichaReiser** [comment]
Perfect, thank you

File: crates/ruff_linter/resources/test/fixtures/flake8_bandit/S103.py [hunk 6]
```diff
@@ -18,6 +18,27 @@
...
 os.chmod("/etc/passwd", stat.S_IWOTH)  # Error
 os.chmod("/etc/passwd", 0o100000000)  # Error
+
+# https://github.com/astral-sh/ruff/issues/18863
+os.chmod("/etc/secrets.txt", 0o21)  # OK (stable); Error (preview, S_IWGRP)
+os.chmod("/etc/secrets.txt", 0o11)  # Error (S_IXGRP)
+
+
+def f(path, mode):
+    os.chmod(path, mode | 0o777)  # OK (not fully known)
```
Comment (MichaReiser) [inline crates/ruff_linter/resources/test/fixtures/flake8_bandit/S103.py]: This doesn't seem to match your PR description and what was discussed on the issue

> `mode | 0o777` — previously unflagged, now reports the statically-known dangerous bits.

Comment (anishgirianish) [reply crates/ruff_linter/resources/test/fixtures/flake8_bandit/S103.py]: Apologies, my mistake while addressing the earlier u64 feedback. I also added an is_fully_known() gate to silence what I thought was an FP, but it was actually a true positive (current_permissions | 0o111 in airflow), and it defeated the partial-bit detection.                                                                              
                                                                                                                                                                            Fixed: removed the gate, pinned mode | 0o777 as # Error. Thanks for catching this!
