### PR TITLE
[`pyflakes`] Ignore errors in `@no_type_check` string annotations (`F722`, `F821`)

### LINKED ISSUE #13824: F821 (Undefined name) and F722 (bad forward annotation) can trigger on `@no_type_check`-ed annotations
Hi! I found that F821 ("Undefined name") and F722 ("Syntax error in forward annotation") can erroneously trigger on functions that marked `@no_type_check`, if they happen to either use names that aren't in scope, or aren't even valid Python.

Consider the following example file:

```python
from typing import no_type_check

@no_type_check
def f821(arg: "A") -> "R":
    pass

@no_type_check
def f722(arg: "this isn't python") -> "this isn't python either":
    pass
```

Save it as "demo.py" and run ruff with:

    ruff check --isolated --select=F722,F821 demo.py --output-format concise

This will emit the following errors, which are all false-positives:

```
demo.py:4:16: F821 Undefined name `A`
demo.py:4:24: F821 Undefined name `R`
demo.py:8:15: F722 Syntax error in forward annotation: `this isn't python`
demo.py:8:39: F722 Syntax error in forward annotation: `this isn't python either`
Found 4 errors.
```

I'm presuming (but haven't tested) that this could apply to other rules that inspect annotations as well. Ruff should treat these annotations as opaque strings without any meaning. As per [PEP-484](https://peps.python.org/pep-0484/#the-meaning-of-annotations):

>  Functions with the `@no_type_check` decorator should be treated as having no annotations.

---

**ruff --version**: 0.7.0
**settings**: no config file exists

### LINKED ISSUE #14698: regression: ruff deletes imports; successive checks fail due to missing import
Running `ruff check --force-exclude --fix --exit-non-zero-on-fix` on my repository deletes some imports that are actually used. The following `ruff check .` fails because of missing imports. The missing imports are the ones deleted by ruff.

## Reproduction steps

- git clone https://github.com/WhyNotHugo/django-afip/
- cd django-afip
- ruff check --force-exclude --fix --exit-non-zero-on-fix

## Observed result

`ruff` deletes imports which are in the `if TYPE_CHECKING` block:

```diff
diff --git a/django_afip/serializers.py b/django_afip/serializers.py
index 34fa8b4..bc2eb57 100644
--- a/django_afip/serializers.py
+++ b/django_afip/serializers.py
@@ -11,13 +11,6 @@ if TYPE_CHECKING:
     from datetime import date
     from datetime import datetime
 
-    from django.db.models import QuerySet
-
-    from django_afip.models import AuthTicket
-    from django_afip.models import Optional
-    from django_afip.models import Receipt
-    from django_afip.models import Tax
-    from django_afip.models import Vat
 
 
```

Running `ruff check` now fails:

```sh
> ruff check
django_afip/serializers.py:43:30: F821 Undefined name `AuthTicket`
   |
42 | @typing.no_type_check  # zeep's dynamic types cannot be type-checked
43 | def serialize_ticket(ticket: AuthTicket):  # noqa: ANN201
   |                              ^^^^^^^^^^ F821
44 |     return f.FEAuthRequest(
45 |         Token=ticket.token,
   |

django_afip/serializers.py:52:43: F821 Undefined name `QuerySet`
   |
51 | @typing.no_type_check  # zeep's dynamic types cannot be type-checked
52 | def serialize_multiple_receipts(receipts: QuerySet[Receipt]):  # noqa: ANN201
   |                                           ^^^^^^^^ F821
53 |     receipts = receipts.all().order_by("receipt_number")
   |

django_afip/serializers.py:52:52: F821 Undefined name `Receipt`
   |
51 | @typing.no_type_check  # zeep's dynamic types cannot be type-checked
52 | def serialize_multiple_receipts(receipts: QuerySet[Receipt]):  # noqa: ANN201
   |                                                    ^^^^^^^ F821
53 |     receipts = receipts.all().order_by("receipt_number")
   |

django_afip/serializers.py:69:32: F821 Undefined name `Receipt`
   |
68 | @typing.no_type_check  # zeep's dynamic types cannot be type-checked
69 | def serialize_receipt(receipt: Receipt):  # noqa: ANN201
   |                                ^^^^^^^ F821
70 |     taxes = receipt.taxes.all()
71 |     vats = receipt.vat.all()
   |

django_afip/serializers.py:128:24: F821 Undefined name `Tax`
    |
127 | @typing.no_type_check  # zeep's dynamic types cannot be type-checked
128 | def serialize_tax(tax: Tax):  # noqa: ANN201
    |                        ^^^ F821
129 |     return f.Tributo(
130 |         Id=tax.tax_type.code,
    |

django_afip/serializers.py:139:24: F821 Undefined name `Vat`
    |
138 | @typing.no_type_check  # zeep's dynamic types cannot be type-checked
139 | def serialize_vat(vat: Vat):  # noqa: ANN201
    |                        ^^^ F821
140 |     return f.AlicIva(
141 |         Id=vat.vat_type.code,
    |

django_afip/serializers.py:148:34: F821 Undefined name `Optional`
    |
147 | @typing.no_type_check  # zeep's dynamic types cannot be type-checked
148 | def serialize_optional(optional: Optional):  # noqa: ANN201
    |                                  ^^^^^^^^ F821
149 |     return f.Opcional(
150 |         Id=optional.optional_type.code,
    |

Found 7 errors.
```

## Expected results

No change; ruff should not delete imports which are being used.

## Additional details

- Using `ruff 0.8.1` from PyPI
- The issue is not reproducible with ruff 0.7.3

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
## Summary

Resolves #13824, resolves #14698. Part of this PR was taken from #14615.

## Test Plan

`cargo nextest run` and `cargo insta test`.

### CODE REVIEW

File: crates/ruff_linter/src/checkers/ast/mod.rs [hunk 1]
```diff
@@ -2348,13 +2355,17 @@ impl<'a> Checker<'a> {
...
+                    self.semantic.restore(snapshot);
+
+                    if !self.semantic.in_no_type_check() {
+                        if self.enabled(Rule::ForwardAnnotationSyntaxError) {
+                            self.diagnostics.push(Diagnostic::new(
+                                pyflakes::rules::ForwardAnnotationSyntaxError {
+                                    body: string_expr.value.to_string(),
+                                },
+                                string_expr.range(),
+                            ));
```
Comment (MichaReiser) [inline crates/ruff_linter/src/checkers/ast/mod.rs:2367]: Should we instead add a `push_type_diagnostic` method to `Checker` so that we don't need to repeat the `!self.semantic.in_no_type_check` check. This would also be closer to how this works in Red Knot.

File: crates/ruff_linter/src/checkers/ast/mod.rs [hunk 2]
```diff
@@ -723,6 +723,13 @@ impl<'a> Visitor<'a> for Checker<'a> {
...
                 // deferred.
                 for decorator in decorator_list {
+                    if self
+                        .semantic
+                        .match_typing_expr(&decorator.expression, "no_type_check")
+                    {
+                        self.semantic.flags |= SemanticModelFlags::NO_TYPE_CHECK;
+                    }
+
                     self.visit_decorator(decorator);
```
Comment (MichaReiser) [inline crates/ruff_linter/src/checkers/ast/mod.rs:733]: I'd flip the order here so that Ruff's and Red Knot's behavior is identical. 


```suggestion
                    self.visit_decorator(decorator);
                    if self
                        .semantic
                        .match_typing_expr(&decorator.expression, "no_type_check")
                    {
                        self.semantic.flags |= SemanticModelFlags::NO_TYPE_CHECK;
                    }
```

File: crates/ruff_linter/src/checkers/ast/mod.rs (hunk 1 above)
Comment (MichaReiser) [reply crates/ruff_linter/src/checkers/ast/mod.rs:2367]: That's fair. But having the method would prepare us to add `type: ignore` support because it would provide a centralized place to where such a check could be added (vs changing all call sites)
