### PR TITLE
Skip partial duplicates when applying multi-edit fixes

### LINKED ISSUE #5800: Autofix is unable to skip identical import edits
There are 22 violations in this [test file](https://github.com/astral-sh/ruff/blob/d692ed08961cbdc56a9f254fba906bd6d3b711d8/crates/ruff/resources/test/fixtures/ruff/RUF013_0.py) for `RUF013`. The autofix for the same contains an edit created using `get_or_import_symbol`. This creates a [no-op edit](https://github.com/astral-sh/ruff/blob/d692ed08961cbdc56a9f254fba906bd6d3b711d8/crates/ruff/src/importer/mod.rs#L205-L220) for every violation. The autofix module is unable to detect that this was already applied and thus not skipping it. This means that there are multiple edits on the same line, thus it skips applying the other fix for the current iteration. This means it applies fix one at a time for each iteration from the 22 violations, meaning it requires 22 iterations to apply all of the fixes.

### How to reproduce?

1. Update the `MAX_ITERATIONS` to 21 (1 less than the total violations reported) here:

https://github.com/astral-sh/ruff/blob/d692ed08961cbdc56a9f254fba906bd6d3b711d8/crates/ruff/src/linter.rs#L250

2. Run the following command:

	```console
    cargo run --bin ruff -- check --select=RUF013 --no-cache --isolated crates/ruff/resources/test/fixtures/ruff/RUF013_0.py --target-version=py39 --fix --diff
	```

Output:
```
debug error: Failed to converge after 21 iterations in `crates/ruff/resources/test/fixtures/ruff/RUF013_0.py` with rule codes RUF013:---
```

Or, for the test case:

1. Update the `MAX_ITERATIONS` to 21 here:

https://github.com/astral-sh/ruff/blob/d692ed08961cbdc56a9f254fba906bd6d3b711d8/crates/ruff/src/test.rs#L86

2. Run the following command:

	```console
	cargo test --package ruff --lib --all-features -- rules::ruff::tests::implicit_optional_py39 --nocapture
	```

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Right now, if we have two fixes that have an overlapping edit, but not an _identical_ set of edits, they'll conflict, causing us to do another linter traversal. Here, I've enabled the fixer to support partially overlapping edits, which (as an example) let's us greatly reduce the number of iterations required in the test suite.

The most common case here is that in which a bunch of edits need to import some symbol, and then use that symbol, but in different ways. In that case, all edits will have a common fix (to import the symbol), but deviate in some way. With this change, we can do all of those edits in one pass.

Note that the simplest way to enable this was to store sorted edits on `Fix`. We don't allow modifying the edits on `Fix` once it's constructed, so this is an easy change, and allows us to avoid a bunch of clones and traversals later on.

Closes #5800.

### CODE REVIEW

File: crates/ruff_diagnostics/src/fix.rs [hunk 1]
```diff
@@ -157,3 +159,43 @@ impl Fix {
         self
     }
 }
+
+/// A collection of [`Edit`] elements to be applied to a source file.
+#[derive(Debug, Clone)]
+pub struct Edits<'a>(Cow<'a, [Edit]>);
+
+impl<'a> Edits<'a> {
```
Comment (charliermarsh) [inline crates/ruff_diagnostics/src/fix.rs:167]: I'm disappointed with what's happening here. The ergonomics of it are fine, but it's so inefficient. `inorder` does a full clone, `retain` does a full clone, etc.

File: crates/ruff/src/test.rs [hunk 2]
```diff
@@ -85,7 +85,7 @@ pub fn test_snippet(contents: &str, settings: &Settings) -> Vec<Message> {
 }
 
 thread_local! {
-    static MAX_ITERATIONS: std::cell::Cell<usize> = std::cell::Cell::new(30);
+    static MAX_ITERATIONS: std::cell::Cell<usize> = std::cell::Cell::new(8);
```
Comment (charliermarsh) [inline crates/ruff/src/test.rs:88]: Some payoff.

File: crates/ruff/src/message/diff.rs [hunk 3]
```diff
@@ -38,12 +38,7 @@ impl Display for Diff<'_> {
         let mut output = String::with_capacity(self.source_code.source_text().len());
         let mut last_end = TextSize::default();
 
-        for edit in self
-            .fix
-            .edits()
-            .iter()
-            .sorted_unstable_by_key(|edit| edit.start())
```
Comment (charliermarsh) [inline crates/ruff/src/message/diff.rs:45]: It does feel good to DRY this up though -- this is now a method on `Edits`.

File: crates/ruff/src/autofix/mod.rs [hunk 4]
```diff
@@ -59,17 +59,21 @@ fn apply_fixes<'a>(
         })
         .sorted_by(|(rule1, fix1), (rule2, fix2)| cmp_fix(*rule1, *rule2, fix1, fix2))
     {
-        // If we already applied an identical fix as part of another correction, skip
-        // any re-application.
-        if fix.edits().iter().all(|edit| applied.contains(edit)) {
+        // Remove any edits that were applied as part of a previous fix.
+        let mut edits = fix.edits();
+        edits.retain(|edit| !applied.contains(edit));
```
Comment (dhruvmanila) [inline crates/ruff/src/autofix/mod.rs:64]: Do you think it's feasible to create a `Vec<&Edit>` which needs to be applied? i.e., filtering out the `Edit` which has been applied but not in place. This would avoid cloning the `Edit`.

**Review by dhruvmanila — APPROVED** [review]
I like the `Edits` interface! :)

**Review by MichaReiser — CHANGES_REQUESTED** [review]
This is an excellent observation. 

I think we can implement this in a way that significantly reduces the time we iterate over edits and removes the in place mutation by

1. Sort the edits of a fix
2. Skip over all edits of that fix that have already been applied
3. Take the start position of the first edit, this is the `min_start` and test if the fix doesn't overlap with another fix
4. Apply the fix(es)

I think this should simplify the implementation

File: crates/ruff_diagnostics/src/fix.rs [hunk 5]
```diff
@@ -157,3 +159,43 @@ impl Fix {
...
+    pub fn min_start(&self) -> Option<TextSize> {
+        self.0.iter().map(Edit::start).min()
+    }
+
+    /// Return an iterator over the [`Edit`] elements in the [`Fix`], sorted by their start
+    /// position.
+    pub fn inorder(&self) -> impl IntoIterator<Item = Edit> {
+        let mut edits = self.to_vec();
+        edits.sort_by_key(Edit::start);
+        edits.into_iter()
```
[the remark this answers is not in the document]
Comment (charliermarsh) [reply crates/ruff_diagnostics/src/fix.rs:183]: Are you referring to the methods on `itertools`?

File: crates/ruff_diagnostics/src/fix.rs [hunk 6]
```diff
@@ -132,8 +134,8 @@ impl Fix {
     }
 
     /// Return a slice of the [`Edit`] elements in the [`Fix`].
-    pub fn edits(&self) -> &[Edit] {
-        &self.edits
+    pub fn edits(&self) -> Edits {
```
[the remark this answers is not in the document]
Comment (charliermarsh) [reply crates/ruff_diagnostics/src/fix.rs:137]: Ah I actually ended to remove that entirely.

File: crates/ruff_diagnostics/src/fix.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (MichaReiser) [reply crates/ruff_diagnostics/src/fix.rs:183]: Yes, I think that's where they're defined. I should have marked this as a Nit.

File: crates/ruff_diagnostics/src/fix.rs [hunk 7]
```diff
@@ -157,3 +159,43 @@ impl Fix {
...
+    /// Return an iterator over the [`Edit`] elements in the [`Fix`], sorted by their start
+    /// position.
+    pub fn inorder(&self) -> impl IntoIterator<Item = Edit> {
+        let mut edits = self.to_vec();
+        edits.sort_by_key(Edit::start);
+        edits.into_iter()
+    }
+
+    /// Filter the [`Edit`] elements in the [`Fix`] by the given predicate.
+    pub fn retain<F>(&mut self, f: F)
```
[the remark this answers is not in the document]
Comment (charliermarsh) [reply crates/ruff_diagnostics/src/fix.rs:187]: I think this is doable... but note that we want the `min` to be the position of the first non-filtered edit. We may still be able to check it ad hoc though.

File: crates/ruff_diagnostics/src/fix.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (charliermarsh) [reply crates/ruff_diagnostics/src/fix.rs:183]: Just confirming, I had the same instinct but this crate doesn't depend on `itertools` right now and I thought I'd get more heat for adding the dependency :joy:

File: crates/ruff_diagnostics/src/fix.rs [hunk 8]
```diff
@@ -157,3 +159,43 @@ impl Fix {
...
+    where
+        F: FnMut(&Edit) -> bool,
+    {
+        self.0.to_mut().retain(f);
```
[the remark this answers is not in the document]
Comment (charliermarsh) [reply crates/ruff_diagnostics/src/fix.rs:191]: Part of what I meant when I commented that "I'm disappointed with what's happening here." :joy:

**Comment by charliermarsh** [comment]
This is a bit better could likely be better still.

File: crates/ruff/src/autofix/mod.rs [hunk 9]
```diff
@@ -59,47 +59,49 @@ fn apply_fixes<'a>(
...
+                if last_pos.map_or(false, |last_pos| last_pos >= edit.start()) {
+                    continue 'outer;
+                }
 
-        // If this fix requires isolation, and we've already applied another fix in the
-        // same isolation group, skip it.
-        if let IsolationLevel::Group(id) = fix.isolation() {
-            if !isolated.insert(id) {
-                continue;
+                first = false;
```
Comment (charliermarsh) [inline crates/ruff/src/autofix/mod.rs:90]: This is kind of confusing (definitely easier to read locally than as a diff), but in short: we want to apply these constraints at the fix level, but if all of the fix's edits were already applied, we don't need to enforce them at all. So we do so lazily, only checking if the location is acceptable when we reach the first edit-to-apply.

**Comment by charliermarsh** [comment]
Okay, the latest version stores sorted edits rather than sorting on the fly. I think this is a lot more efficient as we sort once (and iterate through the edits exactly once) and no longer need to do any clones anywhere. `min_start` also becomes O(1).

File: crates/ruff_diagnostics/src/fix.rs [hunk 10]
```diff
@@ -42,8 +43,11 @@ pub enum IsolationLevel {
 #[derive(Debug, PartialEq, Eq, Clone)]
 #[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
 pub struct Fix {
+    /// The [`Edit`] elements to be applied, sorted by [`TextSize`].
```
Comment (MichaReiser) [inline crates/ruff_diagnostics/src/fix.rs:46]: Nit: sorted by [`Edit::start`] in ascending order

File: crates/ruff_diagnostics/src/fix.rs [hunk 11]
```diff
@@ -119,27 +127,25 @@ impl Fix {
...
     }
 
     /// Return the [`TextSize`] of the first [`Edit`] in the [`Fix`].
     pub fn min_start(&self) -> Option<TextSize> {
-        self.edits.iter().map(Edit::start).min()
+        self.edits.first().map(Edit::start)
     }
 
-    /// Return a slice of the [`Edit`] elements in the [`Fix`].
+    /// Return a slice of the [`Edit`] elements in the [`Fix`], sorted by their [`TextSize`].
```
Comment (MichaReiser) [inline crates/ruff_diagnostics/src/fix.rs:144]: Nit: sorted by [`Edit::start`] in ascending order

File: crates/ruff/src/autofix/mod.rs [hunk 12]
```diff
@@ -50,7 +50,7 @@ fn apply_fixes<'a>(
     let mut fixed = FxHashMap::default();
     let mut source_map = SourceMap::default();
 
-    for (rule, fix) in diagnostics
+    'outer: for (rule, fix) in diagnostics
```
Comment (MichaReiser) [inline crates/ruff/src/autofix/mod.rs:53]: Nit: If you want to avoid the labels, but it requires an additional vector: 

```rust
        let mut edits = fix
            .edits()
            .iter()
            .filter(|edit| !applied.contains(edit))
            .peekable();

        // Lazily enforce any isolation and positional requirements (e.g., avoid applying
        // overlapping fixes, but avoid applying this requirement if all fixes in the edit were
        // already applied).
        if let Some(first) = edits.peek() {
            // If this fix requires isolation, and we've already applied another fix in the
            // same isolation group, skip it.
            if let IsolationLevel::Group(id) = fix.isolation() {
                if !isolated.insert(id) {
                    continue;
                }
            }

            // Best-effort approach: if this fix overlaps with a fix we've already applied,
            // skip it.
            if last_pos.map_or(false, |last_pos| last_pos >= first.start()) {
                continue;
            }
        }

        for edit in edits {
            // Add all contents from `last_pos` to `fix.location`.
            let slice = locator.slice(TextRange::new(last_pos.unwrap_or_default(), edit.start()));
            output.push_str(slice);

            // Add the start source marker for the patch.
            source_map.push_start_marker(edit, output.text_len());

            // Add the patch itself.
            output.push_str(edit.content().unwrap_or_default());

            // Add the end source marker for the added patch.
            source_map.push_end_marker(edit, output.text_len());

            // Track that the edit was applied.
            last_pos = Some(edit.end());
            applied_edits.push(edit);
        }

        applied.extend(applied_edits.drain(..));
        *fixed.entry(rule).or_default() += 1;
    }
```

I don't have a preference to be honest. I just thought this is complicated, and then noticed that it is because we read from and write to `applied` at the same time.

**Review by MichaReiser — APPROVED** [review]

File: crates/ruff/src/autofix/mod.rs (hunk 12 above)
Comment (charliermarsh) [reply crates/ruff/src/autofix/mod.rs:53]: I think what you have here is a big clarity improvement, worth the allocation.
