### PR TITLE
[`pyupgrade`] Fix false negative for `TypeVar` with default argument in `non-pep695-generic-class` (`UP046`)

### LINKED ISSUE #20656: `non-pep695-generic-class` (`UP046`) - false negative on old `TypeVar` with `default` argument
### Summary

```py
from typing import TypeVar, Generic

T = TypeVar("T", default=int)
U = TypeVar("U")


class Foo(Generic[T]): ... # no error
class Bar(Generic[U]): ... # error
```

https://play.ruff.rs/31611e2c-077c-4291-bdeb-dd663a0f43f7

this behavior is mentioned in the [known problems section](https://docs.astral.sh/ruff/rules/non-pep695-generic-class/#known-problems) but i assume this was written before this feature was widely supported by type checkers, and i couldn't find an existing issue for this.

### Version

0.13.2

### PR DESCRIPTION
**Pull request by danparizher**
## Summary

Fixes #20656

### CODE REVIEW

File: crates/ruff_linter/src/rules/pyupgrade/rules/pep695/mod.rs [hunk 1]
```diff
@@ -133,66 +137,62 @@ impl<'a> From<&'a TypeVar<'a>> for TypeParam {
...
+                                    ctx: ast::ExprContext::Load,
+                                }),
+                            ],
+                            ctx: ast::ExprContext::Load,
+                            parenthesized: true,
+                        })))
+                    }
+                    None => None,
+                },
+                default: default.map(|expr| Box::new((*expr).clone())),
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/pyupgrade/rules/pep695/mod.rs]: tiny nit: Is this shared by all the match arms? If so we could factor it out into a shared `default` variable. I also think we can do without the explicit deref but maybe clippy complains.


```suggestion
                default: default.map(|expr| Box::new(expr.clone())),
```

File: crates/ruff_linter/src/rules/pyupgrade/rules/pep695/mod.rs [hunk 2]
```diff
@@ -373,15 +373,8 @@ fn check_type_vars(vars: Vec<TypeVar<'_>>) -> Option<Vec<TypeVar<'_>>> {
...
-    // found on the type parameters
-    (vars
-        .iter()
-        .unique_by(|tvar| tvar.name)
-        .filter(|tvar| tvar.default.is_none())
-        .count()
-        == vars.len())
-    .then_some(vars)
+    // can't predict what the user wanted.
+    (vars.iter().unique_by(|tvar| tvar.name).count() == vars.len()).then_some(vars)
```
Comment (ntBre) [inline crates/ruff_linter/src/rules/pyupgrade/rules/pep695/mod.rs:387]: We need to preview gate this as I mentioned on the issue. I think this might be the easiest place to do that, assuming every usage goes through this code path.

File: crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP047.py.snap
Comment (ntBre) [inline crates/ruff_linter/src/rules/pyupgrade/snapshots/ruff_linter__rules__pyupgrade__tests__UP047.py.snap:1]: As demonstrated here, this change also affects UP047. I think it should also affect UP040, so we should make sure we have test coverage for that as well.
