### PR TITLE
[red-knot] add fixpoint iteration for Type::member_lookup_with_policy

### LINKED ISSUE #17457: [red-knot] dependency graph cycle panic during member lookup
### Summary

Running `red_knot check main.py` on [dvc](https://github.com/iterative/dvc) codebase triggered the following error:

```console
thread '<unnamed>' panicked at /Users/user/.local/share/cargo/git/checkouts/salsa-e6f3bb7c2a062968/87bf6b6/src/function/fetch.rs:167:25:
dependency graph cycle querying member_lookup_with_policy_(Id(19c42)); set cycle_fn/cycle_initial to fixpoint iterate
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread '<unnamed>' panicked at /Users/user/.local/share/cargo/git/checkouts/salsa-e6f3bb7c2a062968/87bf6b6/src/function/fetch.rs:167:25:
dependency graph cycle querying member_lookup_with_policy_(Id(2a96b)); set cycle_fn/cycle_initial to fixpoint iterate
Rayon: detected unexpected panic; aborting
```

<details><summary>Full traceback</summary>
<p>

```console
thread '<unnamed>' panicked at /Users/user/.local/share/cargo/git/checkouts/salsa-e6f3bb7c2a062968/87bf6b6/src/function/fetch.rs:167:25:
dependency graph cycle querying member_lookup_with_policy_(Id(149ac)); set cycle_fn/cycle_initial to fixpoint iterate
stack backtrace:
   0:        0x10d850d0c - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h17237c63d1a69dcb
   1:        0x10d0cdcf3 - core::fmt::write::h30aaf9daa2b08429
   2:        0x10d84cae2 - std::io::Write::write_fmt::hb170de60ea76b27f
   3:        0x10d850b62 - std::sys::backtrace::BacktraceLock::print::h987b7f42d6b8a667
   4:        0x10d851b3d - std::panicking::default_hook::{{closure}}::h054f8024970871a1
   5:        0x10d8519ca - std::panicking::default_hook::h6b7909227071dd78
   6:        0x10d8527e9 - std::panicking::rust_panic_with_hook::hc6bfd990e349125f
   7:        0x10d852398 - std::panicking::begin_panic_handler::{{closure}}::hc31bc6dc768176f9
   8:        0x10d8511c9 - std::sys::backtrace::__rust_end_short_backtrace::hef21f4a0cd77e47f
   9:        0x10d851fdc - _rust_begin_unwind
  10:        0x10d90abaf - core::panicking::panic_fmt::h7b5799c67973413f
  11:        0x10d2fd537 - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::refresh_memo::h3be05dd0ce4cdec4
  12:        0x10d3170ac - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::fetch::hb2c6c7976676529d
  13:        0x10d494f02 - salsa::attach::Attached::attach::h9a712f936f66fba3
  14:        0x10d4178fb - red_knot_python_semantic::types::infer::TypeInferenceBuilder::infer_attribute_load::h53b2560f2966b253
  15:        0x10d413a76 - red_knot_python_semantic::types::infer::TypeInferenceBuilder::infer_expression_impl::ha2c6ad132c6e2295
  16:        0x10d420c82 - red_knot_python_semantic::types::infer::TypeInferenceBuilder::finish::h3f45554e9df93f2c
  17:        0x10d42bc91 - <red_knot_python_semantic::types::infer::infer_expression_types::Configuration_ as salsa::function::Configuration>::execute::h29ddda4b33edabeb
  18:        0x10d318751 - salsa::function::execute::<impl salsa::function::IngredientImpl<C>>::execute::h110c8320bc6bdc9e
  19:        0x10d307d77 - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::refresh_memo::h9e8218eb99a15bf8
  20:        0x10d315cec - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::fetch::h2bddc8520999fadf
  21:        0x10d42c1ad - <red_knot_python_semantic::types::infer::infer_expression_type::Configuration_ as salsa::function::Configuration>::execute::ha9228377e666474a
  22:        0x10d31b0f9 - salsa::function::execute::<impl salsa::function::IngredientImpl<C>>::execute::h1d8113cf9a53e4df
  23:        0x10d2f6ba7 - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::refresh_memo::h1a9c0d2745fe7e02
  24:        0x10d31748c - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::fetch::hd01996e51adcf2a6
  25:        0x10d49284f - salsa::attach::Attached::attach::h04562d4423a9493e
  26:        0x10d3ca594 - std::thread::local::LocalKey<T>::with::hfe0142ad820f789d
  27:        0x10d4ef525 - red_knot_python_semantic::types::class::ClassLiteralType::implicit_instance_attribute::h57e00f065253ad11
  28:        0x10d4ee477 - red_knot_python_semantic::types::class::ClassLiteralType::instance_member::h6b1e53e08b28b851
  29:        0x10d4e990c - red_knot_python_semantic::types::class::ClassType::instance_member::hd1dc3acae93bf0f6
  30:        0x10d50cc10 - red_knot_python_semantic::types::Type::instance_member::hfdfa03a043548806
  31:        0x10d51fee5 - <red_knot_python_semantic::types::Type as red_knot_python_semantic::types::Type::member_lookup_with_policy::InnerTrait_>::member_lookup_with_policy_::h52e546c368b50131
  32:        0x10d353b75 - salsa::function::execute::<impl salsa::function::IngredientImpl<C>>::execute::hee6f47b2cd568d20
  33:        0x10d2fcff1 - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::refresh_memo::h3be05dd0ce4cdec4
  34:        0x10d3170ac - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::fetch::hb2c6c7976676529d
  35:        0x10d494f02 - salsa::attach::Attached::attach::h9a712f936f66fba3
  36:        0x10d4178fb - red_knot_python_semantic::types::infer::TypeInferenceBuilder::infer_attribute_load::h53b2560f2966b253
  37:        0x10d413a76 - red_knot_python_semantic::types::infer::TypeInferenceBuilder::infer_expression_impl::ha2c6ad132c6e2295
  38:        0x10d417a20 - red_knot_python_semantic::types::infer::TypeInferenceBuilder::infer_unary_expression::h8c900e24684ba552
  39:        0x10d4132ba - red_knot_python_semantic::types::infer::TypeInferenceBuilder::infer_expression_impl::ha2c6ad132c6e2295
  40:        0x10d3b8dee - core::iter::adapters::map::map_fold::{{closure}}::he78be4770d4cc745
  41:        0x10d3b6388 - <itertools::with_position::WithPosition<I> as core::iter::traits::iterator::Iterator>::fold::h134e5ad008d0c015
  42:        0x10d413429 - red_knot_python_semantic::types::infer::TypeInferenceBuilder::infer_expression_impl::ha2c6ad132c6e2295
  43:        0x10d420c82 - red_knot_python_semantic::types::infer::TypeInferenceBuilder::finish::h3f45554e9df93f2c
  44:        0x10d42bc91 - <red_knot_python_semantic::types::infer::infer_expression_types::Configuration_ as salsa::function::Configuration>::execute::h29ddda4b33edabeb
  45:        0x10d318751 - salsa::function::execute::<impl salsa::function::IngredientImpl<C>>::execute::h110c8320bc6bdc9e
  46:        0x10d307d77 - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::refresh_memo::h9e8218eb99a15bf8
  47:        0x10d315cec - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::fetch::h2bddc8520999fadf
  48:        0x10d412a4d - red_knot_python_semantic::types::infer::TypeInferenceBuilder::infer_standalone_expression::h786c68a95ee3f02f
  49:        0x10d409cf6 - red_knot_python_semantic::types::infer::TypeInferenceBuilder::infer_body::h6a8403fac5bfe817
  50:        0x10d421efb - red_knot_python_semantic::types::infer::TypeInferenceBuilder::finish::h3f45554e9df93f2c
  51:        0x10d429ee2 - <red_knot_python_semantic::types::infer::infer_scope_types::Configuration_ as salsa::function::Configuration>::execute::h52478205543d7c00
  52:        0x10d3400d1 - salsa::function::execute::<impl salsa::function::IngredientImpl<C>>::execute::ha1171462925cf3c0
  53:        0x10d310bb7 - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::refresh_memo::he370e9ba7863d181
  54:        0x10d315e4c - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::fetch::h348c53b6dec439e6
  55:        0x10d505310 - <red_knot_python_semantic::types::check_types::Configuration_ as salsa::function::Configuration>::execute::h8a2f72d10d2f81b7
  56:        0x10d342a3f - salsa::function::execute::<impl salsa::function::IngredientImpl<C>>::execute::ha9553f055a702ffe
  57:        0x10d2fb4a1 - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::refresh_memo::h30e7f09e52fcd9cc
  58:        0x10d3168ec - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::fetch::h9db73d19aa8a703a
  59:        0x10d5048bf - red_knot_python_semantic::types::check_types::h75017eb85728acde
  60:        0x10d2657ae - red_knot_project::check_file_impl::h62f17068d527e9b1
  61:        0x10d27313a - <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute::hab819adbfae49a69
  62:        0x10d9192bf - rayon_core::registry::WorkerThread::wait_until_cold::hba1258861fea3e1d
  63:        0x10d1a7724 - rayon_core::registry::ThreadBuilder::run::hace3d225f81c1b7b
  64:        0x10d1ad642 - std::sys::backtrace::__rust_begin_short_backtrace::h68655ef3b16b3ef0
  65:        0x10d1aa922 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h81da77f08d9e747f
  66:        0x10d854fcb - std::sys::pal::unix::thread::Thread::new::thread_start::h55e4d2e18c10096d
  67:     0x7ff81ad86df1 - __pthread_start

thread '<unnamed>' panicked at /Users/user/.local/share/cargo/git/checkouts/salsa-e6f3bb7c2a062968/87bf6b6/src/function/fetch.rs:167:25:
dependency graph cycle querying member_lookup_with_policy_(Id(18782)); set cycle_fn/cycle_initial to fixpoint iterate
stack backtrace:
   0:        0x10d850d0c - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h17237c63d1a69dcb
   1:        0x10d0cdcf3 - core::fmt::write::h30aaf9daa2b08429
   2:        0x10d84cae2 - std::io::Write::write_fmt::hb170de60ea76b27f
   3:        0x10d850b62 - std::sys::backtrace::BacktraceLock::print::h987b7f42d6b8a667
   4:        0x10d851b3d - std::panicking::default_hook::{{closure}}::h054f8024970871a1
   5:        0x10d8519ca - std::panicking::default_hook::h6b7909227071dd78
   6:        0x10d8527e9 - std::panicking::rust_panic_with_hook::hc6bfd990e349125f
   7:        0x10d852398 - std::panicking::begin_panic_handler::{{closure}}::hc31bc6dc768176f9
   8:        0x10d8511c9 - std::sys::backtrace::__rust_end_short_backtrace::hef21f4a0cd77e47f
   9:        0x10d851fdc - _rust_begin_unwind
  10:        0x10d90abaf - core::panicking::panic_fmt::h7b5799c67973413f
  11:        0x10d2fd537 - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::refresh_memo::h3be05dd0ce4cdec4
  12:        0x10d3170ac - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::fetch::hb2c6c7976676529d
  13:        0x10d494f02 - salsa::attach::Attached::attach::h9a712f936f66fba3
  14:        0x10d4178fb - red_knot_python_semantic::types::infer::TypeInferenceBuilder::infer_attribute_load::h53b2560f2966b253
  15:        0x10d413a76 - red_knot_python_semantic::types::infer::TypeInferenceBuilder::infer_expression_impl::ha2c6ad132c6e2295
  16:        0x10d420c82 - red_knot_python_semantic::types::infer::TypeInferenceBuilder::finish::h3f45554e9df93f2c
  17:        0x10d42bc91 - <red_knot_python_semantic::types::infer::infer_expression_types::Configuration_ as salsa::function::Configuration>::execute::h29ddda4b33edabeb
  18:        0x10d318751 - salsa::function::execute::<impl salsa::function::IngredientImpl<C>>::execute::h110c8320bc6bdc9e
  19:        0x10d307d77 - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::refresh_memo::h9e8218eb99a15bf8
  20:        0x10d315cec - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::fetch::h2bddc8520999fadf
  21:        0x10d42c1ad - <red_knot_python_semantic::types::infer::infer_expression_type::Configuration_ as salsa::function::Configuration>::execute::ha9228377e666474a
  22:        0x10d31b0f9 - salsa::function::execute::<impl salsa::function::IngredientImpl<C>>::execute::h1d8113cf9a53e4df
  23:        0x10d2f6ba7 - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::refresh_memo::h1a9c0d2745fe7e02
  24:        0x10d31748c - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::fetch::hd01996e51adcf2a6
  25:        0x10d49284f - salsa::attach::Attached::attach::h04562d4423a9493e
  26:        0x10d3ca594 - std::thread::local::LocalKey<T>::with::hfe0142ad820f789d
  27:        0x10d4ef525 - red_knot_python_semantic::types::class::ClassLiteralType::implicit_instance_attribute::h57e00f065253ad11
  28:        0x10d4ee477 - red_knot_python_semantic::types::class::ClassLiteralType::instance_member::h6b1e53e08b28b851
  29:        0x10d4e990c - red_knot_python_semantic::types::class::ClassType::instance_member::hd1dc3acae93bf0f6
  30:        0x10d50cc10 - red_knot_python_semantic::types::Type::instance_member::hfdfa03a043548806
  31:        0x10d51fee5 - <red_knot_python_semantic::types::Type as red_knot_python_semantic::types::Type::member_lookup_with_policy::InnerTrait_>::member_lookup_with_policy_::h52e546c368b50131
  32:        0x10d353b75 - salsa::function::execute::<impl salsa::function::IngredientImpl<C>>::execute::hee6f47b2cd568d20
  33:        0x10d2fcff1 - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::refresh_memo::h3be05dd0ce4cdec4
  34:        0x10d3170ac - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::fetch::hb2c6c7976676529d
  35:        0x10d494f02 - salsa::attach::Attached::attach::h9a712f936f66fba3
  36:        0x10d4178fb - red_knot_python_semantic::types::infer::TypeInferenceBuilder::infer_attribute_load::h53b2560f2966b253
  37:        0x10d413a76 - red_knot_python_semantic::types::infer::TypeInferenceBuilder::infer_expression_impl::ha2c6ad132c6e2295
  38:        0x10d413514 - red_knot_python_semantic::types::infer::TypeInferenceBuilder::infer_expression_impl::ha2c6ad132c6e2295
  39:        0x10d420c82 - red_knot_python_semantic::types::infer::TypeInferenceBuilder::finish::h3f45554e9df93f2c
  40:        0x10d42bc91 - <red_knot_python_semantic::types::infer::infer_expression_types::Configuration_ as salsa::function::Configuration>::execute::h29ddda4b33edabeb
  41:        0x10d318751 - salsa::function::execute::<impl salsa::function::IngredientImpl<C>>::execute::h110c8320bc6bdc9e
  42:        0x10d307d77 - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::refresh_memo::h9e8218eb99a15bf8
  43:        0x10d315cec - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::fetch::h2bddc8520999fadf
  44:        0x10d412a4d - red_knot_python_semantic::types::infer::TypeInferenceBuilder::infer_standalone_expression::h786c68a95ee3f02f
  45:        0x10d409cf6 - red_knot_python_semantic::types::infer::TypeInferenceBuilder::infer_body::h6a8403fac5bfe817
  46:        0x10d421efb - red_knot_python_semantic::types::infer::TypeInferenceBuilder::finish::h3f45554e9df93f2c
  47:        0x10d429ee2 - <red_knot_python_semantic::types::infer::infer_scope_types::Configuration_ as salsa::function::Configuration>::execute::h52478205543d7c00
  48:        0x10d3400d1 - salsa::function::execute::<impl salsa::function::IngredientImpl<C>>::execute::ha1171462925cf3c0
  49:        0x10d310bb7 - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::refresh_memo::he370e9ba7863d181
  50:        0x10d315e4c - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::fetch::h348c53b6dec439e6
  51:        0x10d505310 - <red_knot_python_semantic::types::check_types::Configuration_ as salsa::function::Configuration>::execute::h8a2f72d10d2f81b7
  52:        0x10d342a3f - salsa::function::execute::<impl salsa::function::IngredientImpl<C>>::execute::ha9553f055a702ffe
  53:        0x10d2fb4a1 - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::refresh_memo::h30e7f09e52fcd9cc
  54:        0x10d3168ec - salsa::function::fetch::<impl salsa::function::IngredientImpl<C>>::fetch::h9db73d19aa8a703a
  55:        0x10d5048bf - red_knot_python_semantic::types::check_types::h75017eb85728acde
  56:        0x10d2657ae - red_knot_project::check_file_impl::h62f17068d527e9b1
  57:        0x10d27313a - <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute::hab819adbfae49a69
  58:        0x10d9192bf - rayon_core::registry::WorkerThread::wait_until_cold::hba1258861fea3e1d
  59:        0x10d1a7724 - rayon_core::registry::ThreadBuilder::run::hace3d225f81c1b7b
  60:        0x10d1ad642 - std::sys::backtrace::__rust_begin_short_backtrace::h68655ef3b16b3ef0
  61:        0x10d1aa922 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h81da77f08d9e747f
  62:        0x10d854fcb - std::sys::pal::unix::thread::Thread::new::thread_start::h55e4d2e18c10096d
  63:     0x7ff81ad86df1 - __pthread_start
Rayon: detected unexpected panic; aborting

```

</p>
</details> 

I was able to reduce it to the following minimal example.

**Reproduction Steps:**
1. Create `main.py` with the following contents:
    ```python
    from module import Klass

    Klass().attr
    ```

2. Create `module.py` with the following contents:
    ```python
    class Klass:
        def __init__(self):
            self.attr = 1

        def copy(self, other: "Klass"):
            self.attr = other.attr
    ```
3. Run with `red_knot check main.py`

Here's a link to a git repo if that's easier: https://gist.github.com/skshetry/7f5946e6e8a66e4cce185c454a02a431.

### Version

_No response_

### PR DESCRIPTION
**Pull request by carljm**
## Summary

Member lookup can be cyclic, with type inference of implicit members. A sample case is shown in the added mdtest.

There's no clear way to handle such cases other than to fixpoint-iterate the cycle.

Fixes #17457.

## Test Plan

Added test.

### CODE REVIEW

File: crates/red_knot_python_semantic/src/types.rs [hunk 1]
```diff
@@ -147,6 +147,12 @@ enum AttributeKind {
     NormalOrNonDataDescriptor,
 }
 
+impl AttributeKind {
```
Comment (carljm) [inline crates/red_knot_python_semantic/src/types.rs:150]: This is a drive-by change, just moving the `impl` for `AttributeKind` next to the struct definition.

**Review by AlexWaygood — COMMENTED** [review]
Could we maybe add a few more test cases? I'd be interested in what happens for some variations of the test you've added, e.g.

```py
class C:
    def __init__(self):
        self.x = 1

    def copy(self, other: "C"):
        self.x: int = other.x

reveal_type(C().x)
```

and


```py
class C:
    def __init__(self):
        self.x: int = 1

    def copy(self, other: "C"):
        self.x = other.x

reveal_type(C().x)
```

and


```py
class C:
    def copy(self, other: "C"):
        self.x = other.x

reveal_type(C().x)
```

**Comment by carljm** [comment]
Sure. Three out of those four (numbers 1, 2, and 4) are pretty straightforward: if there's a declaration, we don't attempt to infer anything from the RHS, even of other assignments to the same name. So all of those work fine already on `main`, don't hit any cycle, and reveal `int` as you'd expect. I can still add them.

Number three is interesting, definitely worth adding. It has the result I'd expect from fixpoint iteration: we converge on `Unknown`.

**Review by AlexWaygood — APPROVED** [review]
Nice. If the new panic MRE in https://github.com/astral-sh/ruff/issues/17457#issuecomment-2815848955 is the same bug, it might be worth adding that as a test case as well. But if it's a separate issue, it seems fine to defer that for now.
