### PR TITLE
[red-knot] fix scope inference with deferred types

### LINKED ISSUE #13160: [red_knot] Crash on analysing stub file with explicitly derived class
Found just while playing around with `red_knot` ( b4d9d2602 )

test.py

```python
class Foo(object):
    pass
```

works fine

Renaming it to test.pyi results in:
```
 $ ./../target/debug/red_knot && echo $?
0
 $ mv test.py test.pyi
 $ ./../target/debug/red_knot && echo $?
thread '<unnamed>' panicked at crates/red_knot_python_semantic/src/types/infer.rs:177:25:
no entry found for key
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Rayon: detected unexpected panic; aborting
Aborted (core dumped)
```

Seems to crash with anything as the parent.

relevant part of `RUST_BACKTRACE=full`:

```
  19:     0x561605928fe5 - core::option::Option<T>::expect::hffc771cc74f800e9
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/option.rs:894:21
  20:     0x561605928fe5 - <std::collections::hash::map::HashMap<K,V,S> as core::ops::index::Index<&Q>>::index::hf84fbd63e8ba27dd
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/collections/hash/map.rs:1341:23
  21:     0x56160595a8e4 - red_knot_python_semantic::types::infer::TypeInference::expression_ty::h45e30f4ed3623f78
                               at /home/cpigott/dev/ruff/crates/red_knot_python_semantic/src/types/infer.rs:177:25
  22:     0x56160579d5e4 - <ruff_python_ast::expression::ExpressionRef as red_knot_python_semantic::semantic_model::HasTy>::ty::h7574fdc81220df66
                               at /home/cpigott/dev/ruff/crates/red_knot_python_semantic/src/semantic_model.rs:62:9
  23:     0x5616056603b5 - <ruff_python_ast::nodes::ExprName as red_knot_python_semantic::semantic_model::HasTy>::ty::h0bf9800421b11df7
                               at /home/cpigott/dev/ruff/crates/red_knot_python_semantic/src/semantic_model.rs:72:17
  24:     0x561605600139 - red_knot_workspace::lint::lint_maybe_undefined::hbf56527a89120b0f
                               at /home/cpigott/dev/ruff/crates/red_knot_workspace/src/lint.rs:117:11
  25:     0x561605600d9e - <red_knot_workspace::lint::SemanticVisitor as ruff_python_ast::visitor::Visitor>::visit_expr::h4e5d2046d4543b66
                               at /home/cpigott/dev/ruff/crates/red_knot_workspace/src/lint.rs:244:17
  26:     0x56160561fbfd - ruff_python_ast::visitor::walk_arguments::hcf8638d59de7f088
                               at /home/cpigott/dev/ruff/crates/ruff_python_ast/src/visitor.rs:597:9
  27:     0x5616055f9674 - ruff_python_ast::visitor::Visitor::visit_arguments::he4e1af453a0b6b0f
                               at /home/cpigott/dev/ruff/crates/ruff_python_ast/src/visitor.rs:58:9
  28:     0x5616056238bc - ruff_python_ast::visitor::walk_stmt::h8c2b40d349b01a24
                               at /home/cpigott/dev/ruff/crates/ruff_python_ast/src/visitor.rs:165:17
  29:     0x561605600d2a - <red_knot_workspace::lint::SemanticVisitor as ruff_python_ast::visitor::Visitor>::visit_stmt::h2cea15d01c9fd284
                               at /home/cpigott/dev/ruff/crates/red_knot_workspace/src/lint.rs:238:9
  30:     0x561605620f36 - ruff_python_ast::visitor::walk_body::hd1184b90f5a26118
                               at /home/cpigott/dev/ruff/crates/ruff_python_ast/src/visitor.rs:115:9
  31:     0x5616055f93f8 - ruff_python_ast::visitor::Visitor::visit_body::h1b0a1fbe97acb4d0
                               at /home/cpigott/dev/ruff/crates/ruff_python_ast/src/visitor.rs:94:9
  32:     0x561605602c32 - <red_knot_workspace::lint::lint_semantic::Configuration_ as salsa::function::Configuration>::execute::inner_::h18d04db1014d8c80
                               at /home/cpigott/dev/ruff/crates/red_knot_workspace/src/lint.rs:93:5
```

Looking forward to seeing where this goes!

### PR DESCRIPTION
**Pull request by carljm**
Test coverage for #13131 wasn't as good as I thought it was, because although we infer a lot of types in stubs in typeshed, we don't check typeshed, and therefore we don't do scope-level inference and pull all types for a scope. So we didn't really have good test coverage for scope-level inference in a stub. And because of this, I got the code for supporting that wrong, meaning that if we did scope-level inference with deferred types, we'd end up never populating the deferred types in the scope's `TypeInference`, which causes panics like #13160.

Here I both add test coverage by running the corpus tests both as `.py` and as `.pyi` (which reveals the panic), and I fix the code to support deferred types in scope inference.

This also revealed a problem with deferred types in generic functions, which effectively span two scopes. That problem will require a bit more thought, and I don't want to block this PR on it, so for now I just don't defer annotations on generic functions.

Fixes #13160.

### CODE REVIEW

File: crates/red_knot_workspace/tests/check.rs [hunk 1]
```diff
@@ -24,16 +24,26 @@ fn corpus_no_panic() -> anyhow::Result<()> {
...
+        pull_types(&db, file);
 
+        // try the file as a stub also
+        let stub_path = stub_dir
+            .path()
+            .join(format!("{}i", path.file_name().unwrap().to_str().unwrap()));
+        std::fs::copy(path, stub_path.clone())?;
+        println!("checking {stub_path:?}");
+        let syspath = SystemPathBuf::from_path_buf(stub_path).unwrap();
+        let file = system_path_to_file(&db, syspath).unwrap();
```
Comment (MichaReiser) [inline crates/red_knot_workspace/tests/check.rs:46]: `SystemPath` has a `as_std_path()` method. You may be able to avoid some path -> sys path conversion by using it.

File: crates/red_knot_workspace/tests/check.rs [hunk 2]
```diff
@@ -24,16 +24,26 @@ fn corpus_no_panic() -> anyhow::Result<()> {
     let corpus = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("resources/test/corpus");
     let system_corpus =
         SystemPathBuf::from_path_buf(corpus.clone()).expect("corpus path to be UTF8");
+    let stub_dir = tempfile::TempDir::new()?;
```
Comment (MichaReiser) [inline crates/red_knot_workspace/tests/check.rs:27]: I see the value in extending all corpus tests to `pyi` files and it kind of works but I could see this break in the future because the `stub_dir` isn't part of the workspace. This might cause problems in the future when we try to resolve settings because we won't have any settings available for files outside the workspace. 

I don't have a good suggestion on how to solve this differently other than copying a handful of tests and manually rename the files to `.pyi` files.

**Review by MichaReiser — APPROVED** [review]

File: crates/red_knot_workspace/tests/check.rs (hunk 2 above)
Comment (carljm) [reply crates/red_knot_workspace/tests/check.rs:27]: I assume we will always need to support someone opening an out-of-workspace file? We just won't be able to resolve relative imports from such files. Which shouldn't be an issue for corpus tests. It might actually be useful to have a check that this doesn't break?

But if you'd rather, I can change the test so that it copies all the `.py` files to the tempdir also, and sets the tempdir as the workspace root?

File: crates/red_knot_workspace/tests/check.rs (hunk 1 above)
Comment (carljm) [reply crates/red_knot_workspace/tests/check.rs:46]: I don't think I'm currently doing any path -> sys path conversions -- I have a std Path, and I convert it to a SystemPath, but I keep the original std Path around as well. I guess I could not keep the original std Path around, and instead use `as_std_path` to convert back? But that's doing more conversions, not less. It just allows using fewer variable names (I wouldn't need both `path` and `syspath`, I could shadow instead.)

File: crates/red_knot_workspace/tests/check.rs (hunk 2 above)
Comment (MichaReiser) [reply crates/red_knot_workspace/tests/check.rs:27]: > I assume we will always need to support someone opening an out-of-workspace file? 

Yes, but it still needs to be clarified how we want to support this in the editor. One option is to create an ad-hoc workspace for all detached files. Another option is to list the detached files in the workspace explicitly. The issue with just using the workspace is that any detached file would automatically inherit the workspace setting. That might or might not be what we want. I don't see this use case in the CLI. 


> But if you'd rather, I can change the test so that it copies all the .py files to the tempdir also, and sets the tempdir as the workspace root?

That's a good idea. I would prefer this.
