### PR TITLE
Fix NFKC normalization bug when removing unused imports

### LINKED ISSUE #12570: Fixing file with rule F401 cause infinite loop
ruff 0.5.5+353 (2f54d05d9 2024-07-29)
```
ruff check *.py --select F401 --no-cache --fix --unsafe-fixes --preview --output-format concise --isolated
```

file content(at the bottom should be attached raw, not formatted file - github removes some non-printable characters, so copying from here may not work):
```
from .main import MaµToMan
```

error
```
/tmp/tmp_folder/data/5737962126122819962.py:1:8: F401 `tima` imported but unused
Found 501 errors (500 fixed, 1 remaining).
[*] 1 fixable with the --fix option.

debug error: Failed to converge after 500 iterations in `/tmp/tmp_folder/data/5737962126122819962.py` with rule codes F401:---
import timª
---
```

Ruff build, that was used to reproduce problem(compiled on Ubuntu 22.04 with release mode + debug symbols + debug assertions + overflow checks) - https://github.com/qarmin/Automated-Fuzzer/releases/download/Nightly/ruff.7z

[python_compressed.zip](https://github.com/user-attachments/files/16416924/python_compressed.zip)

### PR DESCRIPTION
**Pull request by AlexWaygood**
Fixes #12570.

## Summary

Our lexer eagerly applies NFKC normalization to NKFC-confusable unicode characters; this is done to match Python's semantics at runtime, where the interpreter views these characters as the same. When removing unused imports, however, we use `libCST`, which doesn't apply the same normalization (it would be incorrect for `libCST` to do so, since it's a CST rather than an AST). This can lead to a `QualifiedName` constructed from a `libCST` node not comparing equal to a `QualifiedName` constructed from a `ruff_python_ast` node that represents the same sapn of source code as the `libCST` node. The difference here between the two parsers is the root cause of #12570.

This PR therefore takes care to apply NFKC normalization when constructing `QualifiedName`s from `libCST` nodes, so that these `QualifiedName`s are always comparable to `QualifiedName`s constructed from `ruff_python_ast` nodes.

## Test plan

`cargo test`

### CODE REVIEW

**Comment by MichaReiser** [comment]
Would you mind updating the summary and explaining why this fixes the issue?

**Comment by AlexWaygood** [comment]
> Thanks for looking into this bug. This looks interesting.
> 
> It would help me review if you could update the summary and include a short summary of what the issue was/how this PR fixes the issue.

Sorry, my bad. I provided an analysis of the bug in the issue, but forgot to copy it over in the PR summary. I'll do so first thing tomorrow.

File: crates/ruff_linter/src/fix/codemods.rs [hunk 1]
```diff
@@ -167,39 +170,46 @@ pub(crate) fn retain_imports(
...
+    ) -> Option<UnqualifiedName<'a>> {
+        let mut segments = smallvec![];
+        collect_segments(expr, &mut segments);
+        if segments.is_empty() {
+            None
+        } else {
+            Some(segments.into_iter().collect())
+        }
     }
-}
```
Comment (MichaReiser) [inline crates/ruff_linter/src/fix/codemods.rs:201]: What's the motivation for nesting these functions? Seems a fairly unrelated change and it took me quiet a bit to figure out **what** changed.

**Review by MichaReiser — APPROVED** [review]
If I understand the change correctly, the issue is that libCST doesn't perform nfkc normalization. Is that correct?

File: crates/ruff_linter/src/fix/codemods.rs (hunk 1 above)
Comment (AlexWaygood) [reply crates/ruff_linter/src/fix/codemods.rs:201]: Sorry again for taking this out of review mode before I had written a PR summary. The motivation here is that the `UnqualifiedName` produced by `unqualified_name_from_expression` should also strictly-speaking be NFKC-normalized before it's safe to be used elsewhere and potentially compared to other `UnqualifiedName`s; the same applies for the segments collected by `collect_segments()`. Currently we only use these functions from the `qualified_name_from_name_or_attribute()`, so I think it's okay (and _probably_ more efficient? it allocates...) to just do a single NKFC normalization pass at the end of `qualified_name_from_name_or_attribute()`, _as long as_ we enforce that `unqualified_name_from_expression()` and `collect_segments()` can't be called from other functions.

Does that make sense? I suppose I should probably add a comment.

Comment (MichaReiser) [reply crates/ruff_linter/src/fix/codemods.rs:201]: Kind of. I'm not that concerned because the functions are private anyway. But I don't feel strongly about it.

Comment (AlexWaygood) [reply crates/ruff_linter/src/fix/codemods.rs:201]: Yeah, I was mostly concerned that other functions in this file might start using them.
