### PR TITLE
[`configuration`] Fix unclear error messages for line-length values exceeding `u16::MAX`

### LINKED ISSUE #21328: Unclear error if line-length goes beyond u16 boundaries
### Summary
Refs https://github.com/astral-sh/ruff/issues/20823

ruff.toml:
```toml
line-length = 99_999
```
```
❯ ruff check
ruff failed                                                                                                                                           
  Cause: Failed to load configuration `...`
  Cause: Failed to parse ...
  Cause: TOML parse error at line 3, column 15
  |
3 | line-length = 99_999
  |               ^^^^^^
invalid value: integer `99999`, expected u16
```

From [TOML spec](https://toml.io/en/v1.0.0#integer):
> Arbitrary 64-bit signed integers (from −2^63 to 2^63−1) should be accepted and handled losslessly. If an integer cannot be represented losslessly, an error must be thrown.

```shell
❯ bat ruff.toml                                                                                                                                       
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: ruff.toml
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ target-version = "py310"
   2   │ 
   3 ~ │ line-length = 65535
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
❯ ruff check
ruff failed                                                                                                                                           
  Cause: Failed to load configuration `...`
  Cause: Failed to parse ...
  Cause: TOML parse error at line 3, column 15
  |
3 | line-length = 65535
  |               ^^^^^
line-length must be between 1 and 320 (got 65535)
```
and
```shell
❯ bat ruff.toml                                                                                                                                       
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: ruff.toml
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ target-version = "py310"
   2   │ 
   3 ~ │ line-length = 65536
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
❯ ruff check
ruff failed                                                                                                                                           
  Cause: Failed to load configuration `...`
  Cause: Failed to parse ...
  Cause: TOML parse error at line 3, column 15
  |
3 | line-length = 65536
  |               ^^^^^
invalid value: integer `65536`, expected u16
```
### Version

`ruff 0.14.4 (c7ff9826d 2025-11-06)`

### PR DESCRIPTION
**Pull request by danparizher**
## Summary

Fixed unclear error messages when `line-length` configuration values exceed `u16::MAX` (65535). Previously, values > 65535 would produce a cryptic TOML parsing error "expected u16" instead of a clear validation message. Now all invalid values produce consistent, user-friendly error messages.

Fixes #21328

## Problem Analysis

The `LineLength` type's `Deserialize` implementation attempted to deserialize directly as `u16`. When TOML contained values exceeding `u16::MAX` (65535), the TOML deserializer would fail before reaching the validation logic, resulting in unclear error messages:

- Values > 65535: `"invalid value: integer `65536`, expected u16"` (unclear)
- Values 321-65535: `"line-length must be between 1 and 320 (got 500)"` (clear)

This inconsistency violated the TOML spec's requirement to accept arbitrary 64-bit signed integers and handle validation errors gracefully.

## Approach

Modified the `Deserialize` implementation for `LineLength` in `crates/ruff_linter/src/line_width.rs` to:

1. **Deserialize as `u64` first**: Accept any valid TOML integer value
2. **Validate u16 bounds**: Check if the value exceeds `u16::MAX` before conversion
3. **Provide consistent errors**: All out-of-range values now produce the same clear error message format: `"line-length must be between 1 and 320 (got {value})"`

Added test cases covering:
- Boundary case: `line-length = 65535` (at u16::MAX)
- Exceeds u16::MAX: `line-length = 65536`
- Far exceeds u16::MAX: `line-length = 99_999`

All tests verify that the error messages are clear and consistent regardless of whether the value exceeds u16::MAX or just exceeds the valid range (1-320).

### CODE REVIEW

File: crates/ruff_linter/src/line_width.rs [hunk 1]
```diff
@@ -51,7 +51,19 @@ impl<'de> serde::Deserialize<'de> for LineLength {
...
+        if value > u64::from(u16::MAX) {
+            return Err(serde::de::Error::custom(format!(
+                "line-length must be between 1 and {} (got {value})",
+                Self::MAX,
+            )));
+        }
+
+        // Convert to u16 and validate range
+        // Safe to unwrap since we've already checked value <= u16::MAX
+        let value = u16::try_from(value).expect("value should fit in u16");
```
Comment (MichaReiser) [inline crates/ruff_linter/src/line_width.rs]:
```suggestion
        // Convert to u16 and validate range
        // Safe to unwrap since we've already checked value <= u16::MAX
        let value = u16::try_from(value).map_err(|_| serde::de::Error::custom(format!(
            "line-length must be between 1 and {} (got {value})",
            Self::MAX,
        )))?;
```

Comment (MichaReiser) [reply crates/ruff_linter/src/line_width.rs]: But I suspect we can even merge this with the next branch by doing something like this
```suggestion
				u16::try_from(value)
					.and_then(|value| Self::try_from(value))
					.map_err(|_| serde::de::Error::custom(format!(
                "line-length must be between 1 and {} (got {value})",
                Self::MAX,
          )))
```

File: crates/ruff_linter/src/line_width.rs [hunk 2]
```diff
@@ -51,7 +51,19 @@ impl<'de> serde::Deserialize<'de> for LineLength {
     where
         D: serde::Deserializer<'de>,
     {
-        let value = u16::deserialize(deserializer)?;
+        let value = u64::deserialize(deserializer)?;
```
Comment (MichaReiser) [inline crates/ruff_linter/src/line_width.rs]: Should we use an `i64` here to also handle `-5`

**Review by MichaReiser — APPROVED** [review]

**Comment by MichaReiser** [comment]
Thank you. 

For us reviewers, it's very helpful to get feedback when suggestions don't work (I obviously didn't realize that Rust won't like `and_then` over different error types) and/or resolve suggestions. It helps us understand which comments were addressed and, if not, why not (without having to clone the PR and applying the changes manually).
