### PR TITLE
[`ruff`] Ambiguous pattern passed to `pytest.raises()` (`RUF043`)

### LINKED ISSUE #13705: detect if a regex escape is needed in a pytest match statement
Sometimes `re.escape` are needed in pytest for `match=...` arguments.
Then the string is modified and the regex escape is no longer needed.
It would be great if ruff could detect this and remove the unneeded `re.escape`.

M~WE:

```python
import pytest, re

with pytest.raises(Exception, match=re.escape("regexnotneeded"):
    ...
```

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
## Summary

Resolves #13705.

## Test Plan

`cargo nextest run` and `cargo insta test`.

### CODE REVIEW

File: crates/ruff_linter/src/rules/flake8_pytest_style/rules/raises.rs [hunk 1]
```diff
@@ -151,6 +151,52 @@ impl Violation for PytestRaisesWithoutException {
     }
 }
 
+/// ## What it does
+/// Checks for non-raw literal string arguments passed to the `match` parameter
+/// of `pytest.raises()` that does not contain any regex metacharacters.
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/flake8_pytest_style/rules/raises.rs:156]: This is different to the rule I suggested in https://github.com/astral-sh/ruff/issues/13705#issuecomment-2532259079. I suggested having a rule that only emits a diagnostic if the string _contains_ a metacharacter. But your implementation only emits a diagnostic if the string _does not contain_ a metacharacter.

The reason I think it would be better to emit the error if the string _contains_ a metacharacter is that I think it's quite a common footgun to do things like this:

```py
import pytest

def do_thing_that_raises():
    raise Exception('foobar')

def test_error_message_contains_foo_at_end_of_sentence():
    with pytest.raises(Exception, match="foo."):
        do_thing_that_raises()
```

Where that `.` will match any character at all (since the string is interpreted as a regex, and `.` is a regex metacharacter). So the test would erroneously pass, when it should have failed. I think it's reasonable to say that the user should either make it explicit that they intend the character to be a regex metacharacter (by using a raw string -- `r"foo."`), or double-escape the metacharacter (`"foo\\."`), or wrap the call in `re.escape()` (`re.escape("foo.")`).

I think if you implement the rule I suggested, it will be much less noisy

**Comment by AlexWaygood** [comment]
This looks much better now, thank you! I feel like I'd prefer to have an example in the docs that uses a `.` character in the string, though. Some of these ecosystem hits are great examples of cases where they're almost certainly not testing _exactly_ what they wanted to test:
- https://github.com/DisnakeDev/disnake/blob/a95ddafdb5c8edd58f3907ad6c839c5bc07687b0/tests/test_flags.py#L167
- https://github.com/apache/superset/blob/092faa019b91b2da7b81de9b04446c34ce254f04/tests/integration_tests/db_engine_specs/hive_tests.py#L256
- https://github.com/apache/airflow/blob/5f13d0d416caa88f13bb061401088c44f6c0f2c6/providers/tests/amazon/aws/auth_manager/avp/test_facade.py#L288
- https://github.com/pypa/pip/blob/8936feef3bc181d04c16ee5ade9731d745ee4200/tests/unit/test_direct_url.py#L107

And I think using an unescaped `.` in the string is almost certainly the most common way in which people hit this bug-waiting-to-happen

File: crates/ruff_linter/src/rules/flake8_pytest_style/rules/raises.rs [hunk 2]
```diff
@@ -151,6 +151,53 @@ impl Violation for PytestRaisesWithoutException {
     }
 }
 
+/// ## What it does
+/// Checks for non-raw literal string arguments passed to the `match` parameter
+/// of `pytest.raises()` that contains at least one regex metacharacters.
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/flake8_pytest_style/rules/raises.rs:156]:
```suggestion
/// of `pytest.raises()` where the string contains at least one unescaped
/// regex metacharacter.
```

File: crates/ruff_linter/src/rules/flake8_pytest_style/rules/raises.rs [hunk 3]
```diff
@@ -151,6 +151,53 @@ impl Violation for PytestRaisesWithoutException {
...
+///
+/// ## Why is this bad?
+/// The `match` argument is implicitly converted to a regex under the hood.
+/// It should be made explicit whether the string is meant to be a regex or a "plain" pattern
+/// by either prefixing the string with the `r` suffix or wrapping it in `re.escape()`.
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/flake8_pytest_style/rules/raises.rs:161]:
```suggestion
/// by prefixing the string with the `r` suffix, escaping the metacharacter(s)
/// in the string using backslashes, or wrapping the entire string in a call to
/// `re.escape()`.
```

File: crates/ruff_linter/src/rules/flake8_pytest_style/rules/raises.rs [hunk 4]
```diff
@@ -151,6 +151,53 @@ impl Violation for PytestRaisesWithoutException {
...
+///
+/// Alternatively:
+///
+/// ```python
+/// import re
+///
+///
+/// with pytest.raises(Exception, match=re.escape("foo.")):
+///     do_thing_that_raises()
+/// ```
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/flake8_pytest_style/rules/raises.rs:185]:
````suggestion
/// ```python
/// import pytest
///
///
/// with pytest.raises(Exception, match="A full sentence."):
///     do_thing_that_raises()
/// ```
///
/// Use instead:
///
/// ```python
/// import pytest
///
///
/// with pytest.raises(Exception, match=r"A full sentence."):
///     do_thing_that_raises()
/// ```
///
/// Alternatively:
///
/// ```python
/// import pytest
/// import re
///
///
/// with pytest.raises(Exception, match=re.escape("A full sentence.")):
///     do_thing_that_raises()
/// ```
///
/// or:
///
/// ```python
/// import pytest
/// import re
///
///
/// with pytest.raises(Exception, "A full sentence\\."):
///     do_thing_that_raises()
/// ```
````

Comment (AlexWaygood) [reply crates/ruff_linter/src/rules/flake8_pytest_style/rules/raises.rs:185]: It would also be great to add a `## References` section at the bottom, with links to the docs for `pytest.raises()` and `re.escape()`

File: crates/ruff_linter/resources/test/fixtures/flake8_pytest_style/PT201.py
Comment (AlexWaygood) [inline crates/ruff_linter/resources/test/fixtures/flake8_pytest_style/PT201.py:1]: Can you add some tests that use strings where the metacharacters are "manually" escaped, such as

```py
with pytest.raises("A full sentence\\."):
    do_thing_that_raises()
```

We need to make sure we don't emit a diagnostic on things like that

**Comment by AlexWaygood** [comment]
> Done. Should we suggest an unsafe fix to go with it?

I'm not sure it's a good idea. Lots of the time it's pretty easy as a human to tell from looking at the string whether they intended the string to be a regex or a "plain" string. But I think it would be hard for Ruff to provide an accurate fix.

E.g. [here](https://github.com/pypa/setuptools/blob/cc43212ffcc2b3e9830fe4f95d465a17f9f04116/setuptools/tests/test_dist.py#L158) it's obvious that they _did_ want the string to be a regex, so the correct fix would be to add the `r` prefix to the string. But in [other](https://github.com/pypa/setuptools/blob/cc43212ffcc2b3e9830fe4f95d465a17f9f04116/setuptools/tests/config/test_apply_pyprojecttoml.py#L201) [hits](https://github.com/pypa/setuptools/blob/cc43212ffcc2b3e9830fe4f95d465a17f9f04116/setuptools/tests/config/test_pyprojecttoml_dynamic_deps.py#L87) in the same repo, it's pretty obvious that the correct fix would be to escape the character, either using backslashes or `re.escape()`. Whichever fix we provide, it might be more annoying than helpful to have Ruff suggest the autofix if it's going to be wrong ~50% of the time, even if it's an unsafe fix.

File: crates/ruff_linter/resources/test/fixtures/flake8_pytest_style/PT201.py
Comment (AlexWaygood) [reply crates/ruff_linter/resources/test/fixtures/flake8_pytest_style/PT201.py:1]: Couldn't we just use a similar approach to what `unnecessary-regular-expression` does for the `repl` argument of `re.sub()`? It just iterates through the characters using `tuple_windows()` method (which is from the `Itertools` crate):

https://github.com/astral-sh/ruff/blob/ac31b26a0ebc0f6070225eb1bde3bc81c65cf12a/crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs#L186-L198

So for each length-2 tuple, if you see `('\\', <metacharacter>)`, you know it's been escaped, so it won't cause a violation. But if you see `(<anything except for '\\'>, <metacharacter>)`, it's enough to trigger a violation. You iterate through the string using `tuple_windows()` until you find an `(<anything that's not '\\'>, <metacharacter>)` pair, then you can break and report a diagnostic. If you iterate through the whole string without finding a pair like that, you don't emit a diagnostic.

Comment (AlexWaygood) [reply crates/ruff_linter/resources/test/fixtures/flake8_pytest_style/PT201.py:1]: Hehe, looking forward to it! 😃

**Review by AlexWaygood — COMMENTED** [review]
I'm not sure this should be a `PT` rule. We generally don't add a rule to a category corresponding to a pre-existing linter unless:
- the pre-existing linter also has the rule
- _or_ the linter has been publicly declared to be deprecated/ummaintained
- _or_ the linter has not seen any activity for >=2 years

Could you move this to the `RUF` category? (The other option would be to open an issue with flake8-pytest-style asking if they would be willing to add the rule)

File: crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs [hunk 5]
```diff
@@ -140,6 +136,14 @@ pub(crate) fn unnecessary_regular_expression(checker: &mut Checker, call: &ExprC
     checker.diagnostics.push(diagnostic);
 }
 
+pub(crate) fn string_has_metacharacters(value: &StringLiteralValue) -> bool {
+    // Compare to the complete list from
+    // https://docs.python.org/3/howto/regex.html#matching-characters
+    value
+        .to_str()
+        .contains(['.', '^', '$', '*', '+', '?', '{', '[', '\\', '|', '('])
+}
```
Comment (AlexWaygood) [inline crates/ruff_linter/src/rules/ruff/rules/unnecessary_regular_expression.rs:145]: it seems like you're no longer using this function from the other rule, so I think all changes to this file are unnecessary for this PR. Could you revert them?

File: crates/ruff_linter/resources/test/fixtures/flake8_pytest_style/PT201.py
Comment (AlexWaygood) [inline crates/ruff_linter/resources/test/fixtures/flake8_pytest_style/PT201.py:1]: Could you possibly add one or two tests that involve an escaped metacharacter followed by a metacharacter? I think your logic handles them correctly, I'd just like to be completist about things, e.g.

```py
pytest.raises(x, "foo\\.*bar")
```

and

```py
pytest.raises(x, "foo*\\.bar")
```

They should obviously both trigger the rule

**Review by AlexWaygood — COMMENTED** [review]
Looks fantastic other than the comments I've just left. I think this is going to be a really useful rule!

File: crates/ruff_linter/src/rules/ruff/rules/pytest_raises_ambiguous_pattern.rs [hunk 6]
```diff
@@ -0,0 +1,161 @@
...
+    }
+
+    let diagnostic = Diagnostic::new(PytestRaisesAmbiguousPattern, string.range);
+
+    checker.diagnostics.push(diagnostic);
+}
+
+fn string_has_unescaped_metacharacters(value: &StringLiteralValue) -> bool {
+    let mut escaped = false;
+    let mut last = '\x00';
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/pytest_raises_ambiguous_pattern.rs:107]: This can be simplified to 
```suggestion
    let last = value.chars().next_back().unwrap_or('\x00');
```

It's probably cheaper than assigning in every single iteration

File: crates/ruff_linter/src/rules/ruff/rules/pytest_raises_ambiguous_pattern.rs [hunk 7]
```diff
@@ -0,0 +1,161 @@
...
+        if char_is_regex_metacharacter(current) {
+            return true;
+        }
+    }
+
+    if escaped {
+        escaped_char_is_regex_metasequence(last)
+    } else {
+        char_is_regex_metacharacter(last)
+    }
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/ruff/rules/pytest_raises_ambiguous_pattern.rs:135]: It's not clear to me why this can't be handled in the for-loop directly. What's special about the last character?

Comment (AlexWaygood) [reply crates/ruff_linter/src/rules/ruff/rules/pytest_raises_ambiguous_pattern.rs:135]: it's because we iterate through the `chars` in overlapping pairs using `tuple_windows()`. The final tuple yielded by `tuple_windows()` will be `(<penultimate character>, <final character>)`, i.e., the `current` variable in the `for` loop will never hold the value of the final character of the string

**Review by AlexWaygood — APPROVED** [review]
LGTM, thanks!
