### PR TITLE
Consider match-case stmts for `C901`, `PLR0912`, and `PLR0915`

### LINKED ISSUE #11421: C901, PLR0912 and PLR0915 treat match/case as one statement
Using ruff 0.4.4 the following code triggers `C901`, `PLR0912` and `PLR0915`:

```python
def grades_to_average(grades):
    numbers = []
    for grade in grades:
        if grade in {"F-", "F", "F+", "E-", "E"}:
            numbers.append(0)
        elif grade == "E+":
            numbers.append(.3)
        elif grade == "D-":
            numbers.append(.7)
        elif grade == "D":
            numbers.append(1.0)
        elif grade == "D+":
            numbers.append(1.3)
        elif grade == "C-":
            numbers.append(1.7)
        elif grade == "C":
            numbers.append(2.0)
        elif grade == "C+":
            numbers.append(2.3)
        elif grade == "B-":
            numbers.append(2.7)
        elif grade == "B":
            numbers.append(3.0)
        elif grade == "B+":
            numbers.append(3.3)
        elif grade == "A-":
            numbers.append(3.7)
        elif grade in {"A", "A+"}:
            numbers.append(4.0)
        else:
            raise ValueError(f"Unknown grade: {grade}")

    try:
        avg = sum(numbers) / len(numbers)
    except ZeroDivisionError:
        avg = 0

    if avg < 0.3:
        avg_grade = "F"
    elif avg < .7:
        avg_grade = "E+"
    elif avg < 1.0:
        avg_grade = "D-"
    elif avg < 1.3:
        avg_grade = "D"
    elif avg < 1.7:
        avg_grade = "D+"
    elif avg < 2.0:
        avg_grade = "C-"
    elif avg < 2.3:
        avg_grade = "C"
    elif avg < 2.7:
        avg_grade = "C+"
    elif avg < 3.0:
        avg_grade = "B-"
    elif avg < 3.3:
        avg_grade = "B"
    elif avg < 3.7:
        avg_grade = "B+"
    elif avg < 4.0:
        avg_grade = "A-"
    elif avg >= 4.0:
        avg_grade = "A"
    else:
        raise ValueError(f"Unexpected average: {avg}")
    return avg_grade
```

The equivalent code that uses `match`/`case` however does not:

```python
def grades_to_average(grades):
    numbers = []
    for grade in grades:
        match grade:
            case "F-" | "F" | "F+" | "E-" | "E":
                numbers.append(0)
            case "E+":
                numbers.append(.3)
            case "D-":
                numbers.append(.7)
            case "D":
                numbers.append(1.0)
            case "D+":
                numbers.append(1.3)
            case "C-":
                numbers.append(1.7)
            case "C":
                numbers.append(2.0)
            case "C+":
                numbers.append(2.3)
            case "B-":
                numbers.append(2.7)
            case "B":
                numbers.append(3.0)
            case "B+":
                numbers.append(3.3)
            case "A-":
                numbers.append(3.7)
            case "A" | "A+":
                numbers.append(4.0)
            case _:
                raise ValueError(f"Unknown grade: {grade}")

    try:
        avg = sum(numbers) / len(numbers)
    except ZeroDivisionError:
        avg = 0

    match avg:
        case avg if avg < .3:
            avg_grade = "F"
        case avg if avg < .7:
            avg_grade = "E+"
        case avg if avg < 1.0:
            avg_grade = "D-"
        case avg if avg < 1.3:
            avg_grade = "D"
        case avg if avg < 1.7:
            avg_grade = "D+"
        case avg if avg < 2.0:
            avg_grade = "C-"
        case avg if avg < 2.3:
            avg_grade = "C"
        case avg if avg < 2.7:
            avg_grade = "C+"
        case avg if avg < 3.0:
            avg_grade = "B-"
        case avg if avg < 3.3:
            avg_grade = "B"
        case avg if avg < 3.7:
            avg_grade = "B+"
        case avg if avg < 4.0:
            avg_grade = "A-"
        case avg if avg >= 4.0:
            avg_grade = "A"
        case _:
            raise ValueError(f"Unexpected average: {avg}")
    return avg_grade
```

Is this intentional? Should each `case` count as a conditional?

### PR DESCRIPTION
**Pull request by blueraft**
Resolves #11421

## Summary

Instead of counting match/case as one statement, consider each `case` as a conditional. 

## Test Plan

`cargo test`

### CODE REVIEW

File: crates/ruff_linter/src/rules/mccabe/rules/function_is_too_complex.rs [hunk 1]
```diff
@@ -429,4 +430,19 @@ def with_lock():
...
     }
+
+    #[test]
+    fn match_case() -> Result<()> {
+        let source = r"
+def f():
+    match a:
+        case 30:
+            print('foo')
+        case _:
```
Comment (blueraft) [inline crates/ruff_linter/src/rules/mccabe/rules/function_is_too_complex.rs:441]: I'm not so sure about this, the equivalent `else statement` has the following check: 

```rust
                   if clause.test.is_some() {
                        complexity += 1;
                    }
```

File: crates/ruff_linter/src/rules/pylint/rules/too_many_branches.rs [hunk 2]
```diff
@@ -176,10 +176,11 @@ fn num_branches(stmts: &[Stmt]) -> usize {
...
             Stmt::Match(ast::StmtMatch { cases, .. }) => {
-                1 + cases
-                    .iter()
-                    .map(|case| num_branches(&case.body))
-                    .sum::<usize>()
+                1 + cases.len()
+                    + cases
+                        .iter()
+                        .map(|case| num_branches(&case.body))
+                        .sum::<usize>()
```
Comment (dhruvmanila) [inline crates/ruff_linter/src/rules/pylint/rules/too_many_branches.rs:183]: I don't think we should count the `match` statement itself as a branch because it's the case blocks which does the branching.


```suggestion
                cases.len()
                    + cases
                        .iter()
                        .map(|case| num_branches(&case.body))
                        .sum::<usize>()
```

File: crates/ruff_linter/src/rules/mccabe/rules/function_is_too_complex.rs [hunk 3]
```diff
@@ -98,6 +98,7 @@ fn get_complexity_number(stmts: &[Stmt]) -> usize {
             Stmt::Match(ast::StmtMatch { cases, .. }) => {
                 complexity += 1;
                 for case in cases {
+                    complexity += 1;
                     complexity += get_complexity_number(&case.body);
                 }
```
Comment (dhruvmanila) [inline crates/ruff_linter/src/rules/mccabe/rules/function_is_too_complex.rs:103]: Similar to the `too-many-branches`, the `match` statement itself doesn't add the complexity but it's the `case` blocks which does.
```suggestion
                for case in cases {
                    complexity += 1;
                    complexity += get_complexity_number(&case.body);
                }
```

File: crates/ruff_linter/src/rules/pylint/rules/too_many_statements.rs [hunk 4]
```diff
@@ -90,6 +90,7 @@ fn num_statements(stmts: &[Stmt]) -> usize {
             Stmt::Match(ast::StmtMatch { cases, .. }) => {
                 count += 1;
                 for case in cases {
+                    count += 1;
                     count += num_statements(&case.body);
                 }
```
Comment (dhruvmanila) [inline crates/ruff_linter/src/rules/pylint/rules/too_many_statements.rs:95]: I'm unsure of whether `case` should be counted here but looking at the logic for other statements, I think it should.

**Review by dhruvmanila — CHANGES_REQUESTED** [review]
Thank you for working on this!

File: crates/ruff_linter/src/rules/mccabe/rules/function_is_too_complex.rs (hunk 1 above)
Comment (dhruvmanila) [reply crates/ruff_linter/src/rules/mccabe/rules/function_is_too_complex.rs:441]: Can you clarify what you're not sure about? Is it that the catch-all case (`_`) acts as an `else` block of an `if` statement?

Comment (blueraft) [reply crates/ruff_linter/src/rules/mccabe/rules/function_is_too_complex.rs:441]: > Is it that the catch-all case (_) acts as an else block of an if statement?

Yep, complexity wise to me it's equivalent to the following `if else` statement.

```python
if x == 30:
    print("foo")
else:
    print("bar")
```

File: crates/ruff_linter/src/rules/pylint/rules/too_many_branches.rs (hunk 2 above)
Comment (blueraft) [reply crates/ruff_linter/src/rules/pylint/rules/too_many_branches.rs]: Makes sense, done.

File: crates/ruff_linter/src/rules/pylint/rules/too_many_statements.rs (hunk 4 above)
Comment (blueraft) [reply crates/ruff_linter/src/rules/pylint/rules/too_many_statements.rs:95]: Hm, feel like we should count it yeah.

File: crates/ruff_linter/src/rules/mccabe/rules/function_is_too_complex.rs (hunk 1 above)
Comment (dhruvmanila) [reply crates/ruff_linter/src/rules/mccabe/rules/function_is_too_complex.rs:440]: Aren't they equivalent? We'd consider the above `if else` statement with complexity 2 and similarly for the following match statement:

```py
match subject:
	case foo: ...
	case _: ...
```

File: crates/ruff_linter/src/rules/pylint/rules/too_many_statements.rs (hunk 4 above)
Comment (dhruvmanila) [reply crates/ruff_linter/src/rules/pylint/rules/too_many_statements.rs:95]: Yeah, I was just thinking out loud :)

**Review by dhruvmanila — APPROVED** [review]
Thank you!

File: crates/ruff_linter/src/rules/mccabe/rules/function_is_too_complex.rs (hunk 1 above)
Comment (blueraft) [reply crates/ruff_linter/src/rules/mccabe/rules/function_is_too_complex.rs:440]: The `if else` statement has a complexity of 1, the ` &clause.test.is_some()` evaluates to false for the `else`.

```sh
[crates/ruff_linter/src/rules/mccabe/rules/function_is_too_complex.rs:413:9] &source = "\nif x == 3:\n    print(\"foo\")\nelse:\n    print(\"bar\")\n "
[crates/ruff_linter/src/rules/mccabe/rules/function_is_too_complex.rs:79:21] &clause.test.is_some() = false
[crates/ruff_linter/src/rules/mccabe/rules/function_is_too_complex.rs:415:9] &get_complexity_number(&stmts) = 1
```

Comment (dhruvmanila) [reply crates/ruff_linter/src/rules/mccabe/rules/function_is_too_complex.rs:440]: Oh I see. Hmm, that's interesting. Yeah, I think we could do that i.e., check if the last `case` pattern is either a `_` or any variable as both act as a catch-all pattern.

Comment (blueraft) [reply crates/ruff_linter/src/rules/mccabe/rules/function_is_too_complex.rs:440]: I think only `_` acts as a wild card pattern if my understanding of the [documentation](https://docs.python.org/3/reference/compound_stmts.html#wildcard-patterns) is correct. In any case, I can make a follow up PR to handle this. :)

Comment (dhruvmanila) [reply crates/ruff_linter/src/rules/mccabe/rules/function_is_too_complex.rs:440]: > I think only `_` acts as a wild card pattern if my understanding of the [documentation](https://docs.python.org/3/reference/compound_stmts.html#wildcard-patterns) is correct.

Yes, although a name pattern would also _act_ in a similar way except that it also binds the value to the variable. So, in the following example `foo` will be same as `subject`. It's like doing `foo = subject`.

```py
match subject:
	case 2: ...
	case foo: ...
```

You can even see that in CPython where it raises a syntax error similar to `_` if the name pattern is not the last pattern:

```py
match 1:
    case x:
        print(x)
    case 2:
        ...
```

Running `python test.py`:

```console
$ python3.13 parser/_.py
  File "/Users/dhruv/playground/ruff/parser/_.py", line 2
    case x:
         ^
SyntaxError: name capture 'x' makes remaining patterns unreachable
```

> In any case, I can make a follow up PR to handle this. :)

Sounds good.
