### PR TITLE
`ruff server` respects `per-file-ignores` configuration

### LINKED ISSUE #11185: `ruff server` does not respect `per-file-ignores`
See: https://github.com/astral-sh/ruff/issues/11138#issuecomment-2081478587

### LINKED ISSUE #11214: `ruff server` first-party libraries get categorized as third-party
Keywords: I001, Organize imports, first-party

Ruff version : 0.4.2

If I'm not mistaken, `ruff server` currently treats first-party libraries like they're third-party libraries, which is not the case for `ruff-lsp`.

Here is a minimal setup to reproduce this:
- Create a new project with the following layout:
```shell
.
├── pyproject.toml
└── src
     └── hello_world
         ├── __init__.py
         ├── module.py
         └── other_module.py
```
with these contents:
<details><summary>pyproject.toml</summary>
<p>

```toml
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hello-world"
version = "0.0.1"
dependencies = [
  "numpy"
]

[tool.ruff]
lint.extend-select = ["I"]
```

</p>
</details> 

<details><summary>module.py</summary>
<p>

```python
hello = "hello world"
```

</p>
</details> 

<details><summary>other_module.py</summary>
<p>

```python
from pathlib import Path

from numpy.linalg import norm

from hello_world.module import hello
```

</p>
</details> 

- Then run `ruff-lsp` in an editor => this should not lint the import order, just like doing `ruff check .` doesn't say anything about import order
- Then run `ruff server` in an editor => now there should be an `Organize import` lint, and if you apply it, it should bring the `hello_world` import just above the `numpy` import, which is not the expected behavior

### PR DESCRIPTION
**Pull request by snowsignal**
## Summary

Fixes #11185
Fixes #11214 

Document path and package information is now forwarded to the Ruff linter, which allows `per-file-ignores` to correctly match against the file name. This also fixes an issue where the import sorting rule didn't distinguish between third-party and first-party packages since we didn't pass in the package root.

## Test Plan

`per-file-ignores` should ignore files as expected. One quick way to check is by adding this to your `pyproject.toml`:
```toml
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["ALL"]
```

Then, confirm that no diagnostics appear when you add code to an `__init__.py` file (besides syntax errors).

The import sorting fix can be verified by failing to reproduce the original issue - an `I001` diagnostic should not appear in `other_module.py`.

### CODE REVIEW

**Review by charliermarsh — APPROVED** [review]

File: crates/ruff_server/src/fix.rs [hunk 1]
```diff
@@ -14,11 +15,23 @@ use crate::{
...
     document: &crate::edit::Document,
+    document_url: &lsp_types::Url,
     linter_settings: &LinterSettings,
     encoding: PositionEncoding,
 ) -> crate::Result<Vec<lsp_types::TextEdit>> {
     let source = document.contents();
 
+    let document_path = document_url
+        .to_file_path()
+        .expect("document URL should be a valid file path");
```
Comment (MichaReiser) [inline crates/ruff_server/src/fix.rs:26]: Can you try what happens if you run `fix_all` on a new, unnamed and unsaved file. Does the new file already have a valid path?

**Review by MichaReiser — APPROVED** [review]

File: crates/ruff_server/src/fix.rs (hunk 1 above)
Comment (snowsignal) [reply crates/ruff_server/src/fix.rs:26]: It does, although the workspace edit seems to fail in certain cases, for some reason? I'll investigate the issue in a follow-up, since it seems to be unrelated to this change.
