### PR TITLE
[ty] Add support for dynamic `type()` classes

### LINKED ISSUE #740: Support `type()`'s functional syntax
(First raised [on Discord](https://discord.com/channels/1039017663004942429/1279201882337705994/1389547211150331974).)

Currently ty doesn't understand `type()`'s functional syntax very well (playground):

```python
# error: Object of type `type` is not assignable to `type[int]`
U32: type[int] = type('U32', (int,), {})
```

It understands `type(...)` returns a new type, but fails to take the bases into account.

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

This PR adds support for dynamic classes created via `type()`. The core of the change is that `ClassLiteral` is now an enum:

```rust
pub enum ClassLiteral<'db> {
    /// A class defined via a `class` statement.
    Stmt(StmtClassLiteral<'db>),
    /// A class created via the functional form `type(name, bases, dict)`.
    Functional(FunctionalClassLiteral<'db>),
}
```

And, in turn, various methods on `ClassLiteral` like `body_scope` now return `Option` or similar (and callers must adjust to that change in signature).

Over time, we can expand the enum to include functional namedtuples, etc. (I already have this working in a separate branch, and I believe it slots in well.)

(I'd love help with the names -- I think `StmtClassLiteral` is kind of lame. Maybe `DeclarativeClassLiteral`?)

Closes https://github.com/astral-sh/ty/issues/740.

### CODE REVIEW

**Comment by charliermarsh** [comment]
(Not ready for review.)

**Comment by charliermarsh** [comment]
I think the scrapy, black, and aiohttp-devtools changes are true positives.

File: crates/ty_python_semantic/src/types/functional_class.rs [hunk 1]
```diff
@@ -0,0 +1,280 @@
...
+    /// This is stored as a boxed slice for efficiency.
+    #[returns(ref)]
+    pub bases: Box<[ClassType<'db>]>,
+}
+
+impl get_size2::GetSize for FunctionalClassType<'_> {}
+
+impl<'db> FunctionalClassType<'db> {
+    /// Returns the first base class, or `object` if there are no bases.
+    pub(crate) fn primary_base(self, db: &'db dyn Db) -> ClassType<'db> {
```
Comment (charliermarsh) [inline crates/ty_python_semantic/src/types/functional_class.rs]: (Need to remove this.)

**Comment by AlexWaygood** [comment]
I haven't looked too hard at this yet, but is adding a new `Type` variant definitely the best way of doing this? We've talked in the past about making `ClassLiteral` (the wrapped data inside the `Type::ClassLiteral` variant) an enum. In almost all respects, types created using three-argument `type()` calls should be treated the same way as classes created using `class` statements (the only difference is that its definition in the AST will be an `ExprCall` rather than a `StmtClassDef`), and that design would better reflect that, I think.

We should also try to make our design here extensible for other classes-created-by-function-calls: functional namedtuples, functional typeddicts, and functional enums.

**Comment by AlexWaygood** [comment]
For a previous attempt to make `ClassLiteral` an enum, you can see https://github.com/astral-sh/ruff/pull/19998. We eventually realised that that wasn't the correct way to go to implement `NewType`, but it still might be for three-argument `type()`, functional typeddicts, functional namedtuples and functional enums.

**Comment by charliermarsh** [comment]
I can give that a try. I initially tried to add another variant to `ClassType`, but there was so much coupling to the class AST node that it ended up not being worth it in my assessment.

**Comment by charliermarsh** [comment]
(The context around functional namedtuples, functional typeddicts, and functional enums is also very useful, thank you.)

**Comment by carljm** [comment]
This needs a rebase.

**Comment by charliermarsh** [comment]
Should be rebased now. It was a little gnarly, sorry for any fragments...

File: crates/ty_python_semantic/src/types/class.rs [hunk 2]
```diff
@@ -1500,10 +2105,10 @@ impl<'db> Field<'db> {
 /// The id may change between runs, or when the class literal was garbage collected and recreated.
 #[salsa::interned(debug, heap_size=ruff_memory_usage::heap_size)]
 #[derive(PartialOrd, Ord)]
-pub struct ClassLiteral<'db> {
+pub struct StmtClassLiteral<'db> {
```
Comment (charliermarsh) [inline crates/ty_python_semantic/src/types/class.rs]: I'm not a huge fan of `Stmt` vs. `Functional`. I would almost prefer `Declarative` vs. `Functional`.

**Comment by carljm** [comment]
Ecosystem report looks like mostly good news, a few quick notes:

1. It looks like this PR now allows inheritance from `type[...]` (SubclassOf) types. Is that intentional? I think it might be OK -- we've intentionally not done it so far, but I'm not sure it can actually cause unsoundness. Mypy and Pyrefly seem to allow it, Pyright does not.
2. The new diagnostics in `src/prefect/flow_engine.py` look a bit concerning. I don't think those are non-determinism, and it looks like we are now failing to specialize away a type variable from a method call. I think we need to understand what's happening here.

**Comment by charliermarsh** [comment]
Which new diagnostics are you referring to? I only see these removed diagnostics: https://dee97dfa.ty-ecosystem-ext.pages.dev/diff

Screenshot 2026-01-07 at 8 47 00 PM

**Comment by charliermarsh** [comment]
I assume I'm looking in the wrong place.

**Comment by carljm** [comment]
Oh interesting! I was still looking at the pre rebase ecosystem report. And it was exactly those same diagnostics now showing as removed that were showing as new in that report. So maybe they are non deterministic. In any case, no need to worry about them.

**Comment by MichaReiser** [comment]
> . In any case, no need to worry about them.

Shouldn't we worry about any new non-deterministic diagnostics to avoid making ty even more non-deterministic? It's obviously possible that the they're non-deterministic because of an existing issue but it might be worth to scan through the code to see if there's anything that might introduce new non-determinism (are we iterating over a `FxHashMap`, any non-deterministic cycle handling...)

File: crates/ty_python_semantic/src/types.rs [hunk 3]
```diff
@@ -977,7 +978,8 @@ impl<'db> Type<'db> {
 
     fn is_enum(&self, db: &'db dyn Db) -> bool {
         self.as_nominal_instance()
-            .and_then(|instance| crate::types::enums::enum_metadata(db, instance.class_literal(db)))
+            .and_then(|instance| instance.class_literal(db))
+            .and_then(|class| crate::types::enums::enum_metadata(db, class))
```
Comment (MichaReiser) [inline crates/ty_python_semantic/src/types.rs]: Nit: You could write this as:


```suggestion
            .and_then(|class| crate::types::enums::enum_metadata(db, instance.class_literal(db)?))
```

File: crates/ty_python_semantic/src/types.rs [hunk 4]
```diff
@@ -1271,9 +1269,11 @@ impl<'db> Type<'db> {
     }
 
     #[track_caller]
-    pub(crate) const fn expect_class_literal(self) -> ClassLiteral<'db> {
+    pub(crate) fn expect_class_literal(self) -> StmtClassLiteral<'db> {
         self.as_class_literal()
             .expect("Expected a Type::ClassLiteral variant")
+            .as_stmt()
```
Comment (MichaReiser) [inline crates/ty_python_semantic/src/types.rs]: I find `as_stmt` somewhat confusing because I immediately associate it with `ast::Stmt`. 

I think I would go with:

* `ClassDefinition` which is the terminology used in the [Python documentation](https://docs.python.org/3/reference/compound_stmts.html#class)
* `Static` and `Dynamic`, `dynamic` is the terminology used in the [`type` documentation](https://docs.python.org/3/library/functions.html#type) *This is essentially a dynamic form of the [class](https://docs.python.org/3/reference/compound_stmts.html#class) statement.*

File: crates/ty_python_semantic/src/types.rs [hunk 5]
```diff
@@ -3248,9 +3250,14 @@ impl<'db> Type<'db> {
...
+                        |(class_literal, _)| is_single_member_enum(db, class_literal),
+                    ) =>
             {
-                enum_metadata(db, instance.class(db).class_literal(db).0)
+                instance
+                    .class(db)
+                    .stmt_class_literal(db)
+                    .and_then(|(class_literal, _)| enum_metadata(db, class_literal))
                     .and_then(|metadata| metadata.members.get_index(0).map(|(_, v)| *v))
                     .map_or(Place::Undefined, Place::bound)
```
Comment (MichaReiser) [inline crates/ty_python_semantic/src/types.rs]:
```suggestion
                    .and_then(|(class_literal, _)| {
                    	let metadata = enum_metadata(db, class_literal)?;
                    	let index = *metadata.members.get_index(0)?;
                    	Some(Place::bound(index))
                  	})
                  	.unwrap_or(Place::Undefined)
```

File: crates/ty_python_semantic/src/types.rs [hunk 6]
```diff
@@ -3357,11 +3364,11 @@ impl<'db> Type<'db> {
 
             Type::ClassLiteral(..) | Type::GenericAlias(..) | Type::SubclassOf(..) => {
                 if let Some(enum_class) = match self {
-                    Type::ClassLiteral(literal) => Some(literal),
+                    Type::ClassLiteral(literal) => literal.as_stmt(),
                     Type::SubclassOf(subclass_of) => subclass_of
                         .subclass_of()
                         .into_class(db)
-                        .map(|class| class.class_literal(db).0),
+                        .and_then(|class| class.stmt_class_literal(db).map(|(lit, _)| lit)),
```
Comment (MichaReiser) [inline crates/ty_python_semantic/src/types.rs]:
```suggestion
                        .and_then(|class| Some(class.stmt_class_literal(db)?.0)),
```

File: crates/ty_python_semantic/src/types.rs [hunk 7]
```diff
@@ -8985,7 +9005,12 @@ impl<'db> UnionTypeInstance<'db> {
     ) -> Result<impl Iterator<Item = Type<'db>> + 'db, InvalidTypeExpressionError<'db>> {
         let to_class_literal = |ty: Type<'db>| {
             ty.as_nominal_instance()
-                .map(|instance| Type::ClassLiteral(instance.class(db).class_literal(db).0))
+                .and_then(|instance| {
+                    instance
+                        .class(db)
+                        .stmt_class_literal(db)
+                        .map(|(lit, _)| Type::ClassLiteral(lit.into()))
```
Comment (MichaReiser) [inline crates/ty_python_semantic/src/types.rs:8996]:
```suggestion
                    Some(Type::ClassLiteral(
                    	instance
                        .class(db)
                        .stmt_class_literal(db)?
                        .0
                        .into()
                    ))
```

File: crates/ty_python_semantic/src/types/call/arguments.rs [hunk 8]
```diff
@@ -403,8 +405,10 @@ fn expand_type<'db>(db: &'db dyn Db, ty: Type<'db>) -> Option<Vec<Type<'db>>> {
                 };
             }
 
-            if let Some(enum_members) = enum_member_literals(db, class.class_literal(db).0, None) {
-                return Some(enum_members.collect());
+            if let Some((class_literal, _)) = class.stmt_class_literal(db) {
+                if let Some(enum_members) = enum_member_literals(db, class_literal, None) {
```
Comment (MichaReiser) [inline crates/ty_python_semantic/src/types/call/arguments.rs]:
```suggestion
            if let Some((class_literal, _)) = class.stmt_class_literal(db) &&
            	let Some(enum_members) = enum_member_literals(db, class_literal, None) {
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 9]
```diff
@@ -74,18 +78,260 @@ use ruff_text_size::{Ranged, TextRange};
...
+///
+/// This struct encapsulates the shared logic for looking up class and instance
+/// members by iterating through an MRO. Both `StmtClassLiteral` and `FunctionalClassLiteral`
+/// use this to avoid duplicating the MRO traversal logic.
+pub(super) struct MroLookup<'db, I> {
+    db: &'db dyn Db,
+    mro_iter: I,
+}
+
+impl<'db, I: Iterator<Item = ClassBase<'db>>> MroLookup<'db, I> {
```
Comment (MichaReiser) [inline crates/ty_python_semantic/src/types/class.rs]: That's a lot of monomorphized code. Does the code need to be generic over `I`? Are there parts that we can move into non-generic functions?

I also think this should come after the `ClassLiteral` definition as it seems more an implementation detail

File: crates/ty_python_semantic/src/types/class.rs [hunk 10]
```diff
@@ -399,6 +647,284 @@ impl<'db> VarianceInferable<'db> for GenericAlias<'db> {
...
+    pub(crate) fn name(self, db: &'db dyn Db) -> &'db ast::name::Name {
+        match self {
+            Self::Stmt(stmt) => stmt.name(db),
+            Self::Functional(functional) => functional.name(db),
+        }
+    }
+
+    /// Returns the known class, if any.
+    pub(crate) fn known(self, db: &'db dyn Db) -> Option<KnownClass> {
+        self.as_stmt().and_then(|stmt| stmt.known(db))
```
Comment (MichaReiser) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
        self.as_stmt()?.known(db)
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 11]
```diff
@@ -4202,14 +4683,236 @@ impl<'db> VarianceInferable<'db> for ClassLiteral<'db> {
...
+/// ```
+#[salsa::interned(debug, heap_size = ruff_memory_usage::heap_size)]
+#[derive(PartialOrd, Ord)]
+pub struct FunctionalClassLiteral<'db> {
+    /// The name of the class (from the first argument to `type()`).
+    #[returns(ref)]
+    pub name: Name,
+
+    /// The base classes (from the second argument to `type()`).
+    #[returns(ref)]
```
Comment (MichaReiser) [inline crates/ty_python_semantic/src/types/class.rs]: Could we use `deref` here? (so that salsa returns `&[ClassBase]`) or are there cases where we need to know that it's a boxed slice?

File: crates/ty_python_semantic/src/types/class.rs [hunk 12]
```diff
@@ -4202,14 +4683,236 @@ impl<'db> VarianceInferable<'db> for ClassLiteral<'db> {
...
+            return Ok(SubclassOfType::subclass_of_unknown());
+        }
+
+        // Start with the first base's metaclass as the candidate.
+        // Track which base the candidate metaclass came from.
+        let mut candidate = bases[0].metaclass(db);
+        let mut candidate_base = bases[0];
+
+        // Reconcile with other bases' metaclasses.
+        for base in &bases[1..] {
```
Comment (MichaReiser) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
        let (mut candidate_base, rest) = bases.split_first().unwrap();

        // Reconcile with other bases' metaclasses.
        for base in rest {
```

File: crates/ty_python_semantic/src/types.rs (hunk 4 above)
Comment (charliermarsh) [reply crates/ty_python_semantic/src/types.rs]: Yeah I like this too. @carljm -- does that seem reasonable? (Just want to avoid multiple rounds of renaming if possible.)

File: crates/ty_python_semantic/src/types.rs [hunk 13]
```diff
@@ -977,7 +978,8 @@ impl<'db> Type<'db> {
 
     fn is_enum(&self, db: &'db dyn Db) -> bool {
         self.as_nominal_instance()
-            .and_then(|instance| crate::types::enums::enum_metadata(db, instance.class_literal(db)))
+            .and_then(|instance| instance.class_literal(db))
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types.rs]: we'll probably have to use a `match` here in the future when we add support for functional enums, so is it worth switching to use a `match` here now? It might lead to less code churn in the future

File: crates/ty_python_semantic/src/types.rs (hunk 4 above)
Comment (AlexWaygood) [reply crates/ty_python_semantic/src/types.rs]: > I find `as_stmt` somewhat confusing because I immediately associate it with `ast::Stmt`.

I think that's sort of the point? One kind of class is created using a `class` statement, and the other is created using a call expression.

But I also like your proposed terminology!

File: crates/ty_python_semantic/src/types.rs [hunk 14]
```diff
@@ -5472,8 +5481,14 @@ impl<'db> Type<'db> {
...
             Type::GenericAlias(alias) => Ok(Type::instance(db, ClassType::from(*alias))),
 
-            Type::SubclassOf(_)
-            | Type::BooleanLiteral(_)
+            Type::SubclassOf(_) => Err(InvalidTypeExpressionError {
+                invalid_expressions: smallvec::smallvec_inline![
+                    InvalidTypeExpression::InvalidType(*self, scope_id)
+                ],
+                fallback_type: Type::unknown(),
+            }),
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types.rs]: what's the motivation for making this a separate branch in the `match`? It still looks like the branch arm does the same thing as the following one to me

File: crates/ty_python_semantic/src/types.rs [hunk 15]
```diff
@@ -6522,12 +6539,13 @@ impl<'db> Type<'db> {
             }
             Self::ModuleLiteral(module) => Some(TypeDefinition::Module(module.module(db))),
             Self::ClassLiteral(class_literal) => {
-                Some(TypeDefinition::Class(class_literal.definition(db)))
+                class_literal.definition(db).map(TypeDefinition::Class)
             }
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types.rs]: we should be able to provide a `TypeDefinition` for dynamic `type()` classes too -- you might have to add a new variant to the `TypeDefinition` enum, but that shouldn't be too hard

File: crates/ty_python_semantic/src/types.rs [hunk 16]
```diff
@@ -12697,7 +12722,7 @@ impl<'db> BytesLiteralType<'db> {
 #[derive(PartialOrd, Ord)]
 pub struct EnumLiteralType<'db> {
     /// A reference to the enum class this literal belongs to
-    enum_class: ClassLiteral<'db>,
+    enum_class: StmtClassLiteral<'db>,
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types.rs]: in the long term we won't be able to count on all `enum_class`es having `StmtClassDef` nodes in the AST, due to the functional syntax for creating enum classes. (But no change requested; this seems fine for now.)

File: crates/ty_python_semantic/src/types.rs [hunk 17]
```diff
@@ -12925,7 +12950,7 @@ impl<'db> TypeGuardLike<'db> for TypeGuardType<'db> {
 /// being added to the given class.
 pub(super) fn determine_upper_bound<'db>(
     db: &'db dyn Db,
-    class_literal: ClassLiteral<'db>,
+    class_literal: StmtClassLiteral<'db>,
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types.rs]: why is this taking a `StmtClassLiteral` rather than a `ClassLiteral`? All kinds of class-literals have MROs, right?

File: crates/ty_python_semantic/src/types/bound_super.rs
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/bound_super.rs:1]: most of the changes to this file *look* unnecessary -- but I think that's just because you need to fix some merge conflicts, and they'll probably go away from the diff after a rebase?

File: crates/ty_python_semantic/src/types/call/bind.rs [hunk 18]
```diff
@@ -1380,6 +1385,54 @@ impl<'db> Bindings<'db> {
...
 
+                        Some(KnownClass::Type) if overload_index == 1 => {
+                            // Three-argument call: type(name, bases, dict)
+                            if let [Some(name_type), Some(bases), Some(_namespace), ..] =
+                                overload.parameter_types()
+                            {
+                                // Extract the name from the first argument (if it's a string literal).
+                                let name = name_type
+                                    .as_string_literal()
+                                    .map(|s| ruff_python_ast::name::Name::new(s.value(db)));
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/call/bind.rs]:
```suggestion
                                    .map(|s| Name::new(s.value(db)));
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 19]
```diff
@@ -399,6 +647,284 @@ impl<'db> VarianceInferable<'db> for GenericAlias<'db> {
...
+    }
+
+    /// Returns the default specialization for this class.
+    ///
+    /// For statement-based classes, this applies default type arguments.
+    /// For functional classes, this returns a non-generic class type.
+    pub(crate) fn default_specialization(self, db: &'db dyn Db) -> ClassType<'db> {
+        match self {
+            Self::Stmt(stmt) => stmt.default_specialization(db),
+            Self::Functional(functional) => ClassType::NonGeneric(functional.into()),
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
            Self::Functional(_) => ClassType::NonGeneric(self),
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 20]
```diff
@@ -399,6 +647,284 @@ impl<'db> VarianceInferable<'db> for GenericAlias<'db> {
...
+        }
+    }
+
+    /// Returns the identity specialization for this class (same as default for non-generic).
+    pub(crate) fn identity_specialization(self, db: &'db dyn Db) -> ClassType<'db> {
+        match self {
+            Self::Stmt(stmt) => stmt.identity_specialization(db),
+            Self::Functional(functional) => ClassType::NonGeneric(functional.into()),
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
            Self::Functional(_) => ClassType::NonGeneric(self),
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 21]
```diff
@@ -399,6 +647,284 @@ impl<'db> VarianceInferable<'db> for GenericAlias<'db> {
...
+
+    /// Returns the generic context if this is a generic class.
+    pub(crate) fn generic_context(self, db: &'db dyn Db) -> Option<GenericContext<'db>> {
+        self.as_stmt().and_then(|stmt| stmt.generic_context(db))
+    }
+
+    /// Returns whether this class is a protocol.
+    pub(crate) fn is_protocol(self, db: &'db dyn Db) -> bool {
+        self.as_stmt().is_some_and(|stmt| stmt.is_protocol(db))
+    }
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs:578]: is this correct? Couldn't you create a protocol class using the `type()` function?

```py
from typing import Protocol

X = type("X", (Protocol,), {})
```

though I don't know why you would, since you wouldn't be able to define any protocol members. Maybe we should just explicitly ban that, and emit a diagnostic for that? (Fine to defer that to a followup.)

There are lots of assumptions everywhere that you can't define a generic class using the `type()` function, so we should probably try to emit a diagnostic for

```py
from typing import Generic, TypeVar

T = TypeVar("T")

X = type("X", (Generic[T],), {})
```

Interestingly, all type checkers reject "dynamic generic classes" like the one above, but mypy _does_ support defining generic functional namedtuples/typeddicts:

```py
from typing import Generic, NamedTuple, TypeVar, TypedDict

T = TypeVar("T")

X = NamedTuple("X", [("a", T)])
Y = TypedDict("Y", {"some-key": T})

def _(obj: X[int], obj2: Y[int]):
    reveal_type(obj)  # revealed: tuple[builtins.int, fallback=__main__.X[builtins.int]]
    reveal_type(obj2)  # revealed: TypedDict('__main__.Y', {'some-key': builtins.int})
```

the second case here is important, actually, because it's the only way to define a generic `TypedDict` with invalid-identifier keys.

https://mypy-play.net/?mypy=latest&python=3.12&gist=5f45711ace3174d8a87b2c4d14920f57

File: crates/ty_python_semantic/src/types/class.rs [hunk 22]
```diff
@@ -399,6 +647,284 @@ impl<'db> VarianceInferable<'db> for GenericAlias<'db> {
...
+            Self::Stmt(stmt) => Some(stmt),
+            Self::Functional(_) => None,
+        }
+    }
+
+    /// Returns an unknown specialization for this class.
+    pub(crate) fn unknown_specialization(self, db: &'db dyn Db) -> ClassType<'db> {
+        match self {
+            Self::Stmt(stmt) => stmt.unknown_specialization(db),
+            Self::Functional(functional) => ClassType::NonGeneric(functional.into()),
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
            Self::Functional(_) => ClassType::NonGeneric(self),
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 23]
```diff
@@ -399,6 +647,284 @@ impl<'db> VarianceInferable<'db> for GenericAlias<'db> {
...
+
+    /// Returns the body scope of this class, if it's a statement class.
+    pub(crate) fn body_scope(self, db: &'db dyn Db) -> Option<ScopeId<'db>> {
+        self.as_stmt().map(|stmt| stmt.body_scope(db))
+    }
+
+    /// Returns the definition of this class, if it's a statement class.
+    pub(crate) fn definition(self, db: &'db dyn Db) -> Option<Definition<'db>> {
+        self.as_stmt().map(|stmt| stmt.definition(db))
+    }
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]: Ideally, functional classes would store a reference to the `ExprCall` `Definition` that was used to define them, and return that `Definition` here

File: crates/ty_python_semantic/src/types/class.rs [hunk 24]
```diff
@@ -399,6 +647,284 @@ impl<'db> VarianceInferable<'db> for GenericAlias<'db> {
...
+        self.as_stmt().and_then(|stmt| stmt.as_disjoint_base(db))
+    }
+
+    /// Returns a non-generic instance of this class.
+    pub(crate) fn to_non_generic_instance(self, db: &'db dyn Db) -> Type<'db> {
+        match self {
+            Self::Stmt(stmt) => stmt.to_non_generic_instance(db),
+            Self::Functional(functional) => {
+                Type::instance(db, ClassType::NonGeneric(functional.into()))
+            }
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
            Self::Functional(_) => {
                Type::instance(db, ClassType::NonGeneric(self))
            }
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 25]
```diff
@@ -399,6 +647,284 @@ impl<'db> VarianceInferable<'db> for GenericAlias<'db> {
...
+
+    /// Apply a specialization to this class.
+    pub(crate) fn apply_specialization(
+        self,
+        db: &'db dyn Db,
+        f: impl FnOnce(GenericContext<'db>) -> Specialization<'db>,
+    ) -> ClassType<'db> {
+        match self {
+            Self::Stmt(stmt) => stmt.apply_specialization(db, f),
+            Self::Functional(functional) => ClassType::NonGeneric(functional.into()),
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
            Self::Functional(_) => ClassType::NonGeneric(self),
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 26]
```diff
@@ -399,6 +647,284 @@ impl<'db> VarianceInferable<'db> for GenericAlias<'db> {
...
+            Self::Stmt(stmt) => stmt.instance_member(db, specialization, name),
+            Self::Functional(functional) => functional.instance_member(db, name),
+        }
+    }
+
+    /// Returns the top materialization for this class.
+    pub(crate) fn top_materialization(self, db: &'db dyn Db) -> ClassType<'db> {
+        match self {
+            Self::Stmt(stmt) => stmt.top_materialization(db),
+            Self::Functional(functional) => ClassType::NonGeneric(functional.into()),
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
            Self::Functional(_) => ClassType::NonGeneric(self),
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 27]
```diff
@@ -4202,14 +4683,236 @@ impl<'db> VarianceInferable<'db> for ClassLiteral<'db> {
...
+///
+/// # Salsa interning
+///
+/// Two `type()` calls with the same name and bases produce the same `FunctionalClassLiteral`
+/// instance. This matches Pyright's behavior where:
+/// ```python
+/// Foo1 = type("Foo", (Base,), {})
+/// Foo2 = type("Foo", (Base,), {})
+/// # Foo1 and Foo2 have the same type: type[Foo]
+/// ```
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs:4694]: Hmm, but pyright's behaviour seems incorrect here? Ideally we would treat these as distinct types, the same as we do for different class-literals that have the same name. Storing the `Definition` on the `FunctionalClassLiteral` struct, as I suggested above, might help with that.

File: crates/ty_python_semantic/src/types/class.rs [hunk 28]
```diff
@@ -4202,14 +4683,236 @@ impl<'db> VarianceInferable<'db> for ClassLiteral<'db> {
...
+    /// Compute and cache the MRO for this functional class.
+    ///
+    /// Uses C3 linearization when possible, falling back to sequential iteration
+    /// with deduplication when there's an error (duplicate bases or C3 merge failure).
+    #[salsa::tracked(heap_size = ruff_memory_usage::heap_size)]
+    pub(crate) fn mro(self, db: &'db dyn Db) -> Mro<'db> {
+        self.try_mro(db)
+            .unwrap_or_else(|_| Mro::functional_fallback(db, self))
+    }
+}
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]: I would add `#[salsa::tracked]` to the `impl` block above and then put this method in that `impl` block. Just because `#[salsa::tracked]` is added to an `impl` block doesn't mean that all methods in that `impl` block need to be themselves decorated with `#[salsa::tracked]`.

File: crates/ty_python_semantic/src/types/class.rs [hunk 29]
```diff
@@ -4202,14 +4683,236 @@ impl<'db> VarianceInferable<'db> for ClassLiteral<'db> {
...
+    /// (i.e., two base classes have metaclasses that are not in a subclass relationship).
+    ///
+    /// See <https://docs.python.org/3/reference/datamodel.html#determining-the-appropriate-metaclass>
+    pub(crate) fn try_metaclass(
+        self,
+        db: &'db dyn Db,
+    ) -> Result<Type<'db>, FunctionalMetaclassConflict<'db>> {
+        let bases = self.bases(db);
+
+        // If no bases, metaclass is `type`.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs:4774]:
```suggestion
        // If no bases, metaclass is `type`.
        // To dynamically create a class with no bases that has a custom metaclass,
        // you have to invoke that metaclass rather than `type()`.
```

File: crates/ty_python_semantic/src/types/class_base.rs [hunk 30]
```diff
@@ -309,6 +307,15 @@ impl<'db> ClassBase<'db> {
         }
     }
 
+    /// Return the metaclass of this class base.
+    pub(crate) fn metaclass(self, db: &'db dyn Db) -> Type<'db> {
+        match self {
+            Self::Class(class) => class.metaclass(db),
+            Self::Dynamic(dynamic) => Type::Dynamic(dynamic),
+            Self::Protocol | Self::Generic | Self::TypedDict => KnownClass::Type.to_instance(db),
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class_base.rs:321]: At some point we need to add support for the fact that all `Protocol` classes actually have `_ProtocolMeta` as their metaclass (https://github.com/astral-sh/ty/issues/1204); you could possibly add a TODO here about that

File: crates/ty_python_semantic/src/types/class_base.rs [hunk 31]
```diff
@@ -359,7 +366,11 @@ impl<'db> ClassBase<'db> {
     pub(super) fn has_cyclic_mro(self, db: &'db dyn Db) -> bool {
         match self {
             ClassBase::Class(class) => {
-                let (class_literal, specialization) = class.class_literal(db);
+                let Some((class_literal, specialization)) = class.stmt_class_literal(db) else {
+                    // Functional classes can't have cyclic MRO since their bases must
+                    // already exist at creation time.
+                    return false;
+                };
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class_base.rs]:
```suggestion
                let Some((class_literal, specialization)) = class.stmt_class_literal(db) else {
                    // Functional classes can't have cyclic MRO since their bases must
                    // already exist at creation time. Unlike statement classes, we do not
                    // permit functional classes to have forward references in their
                    // bases list.
                    return false;
                };
```

Do you have any tests for attempts to create cyclic MROs using `type()` in stub files? If not, you could add this as a test (make sure you make the mdtest a `.pyi` file!):

```py
X = type("X", (X,), {})
```

(you don't panic on it, which is good 😄)

**Review by AlexWaygood — COMMENTED** [review]
Wow, thanks for taking this on!!

**Comment by jelle-openai** [comment]
> but I'm not sure it can actually cause unsoundness

```python
def func(x: int) -> str:
    class Base1:
        pass
    
    class Base2:
        def meth(self, x: int) -> str:
            return str(x)
    
    class Sneaky(Base1):
        def meth(self, x: int) -> int:
            return x
            
    t: type[Base1] = Sneaky
    
    class Child(t, Base2):
        pass
    
    c = Child()
    return c.meth(x)
```

Pyrefly seems to allow this and it is unsound. Mypy rejects the inheritance from `t`, not sure what you were doing that made it accept it.

**Comment by carljm** [comment]
Thanks @jelle-openai ! I didn't spend very long thinking about it, and knew I was probably missing something. I was thinking that Liskov checking should make it safe, but of course that doesn't apply when subclasses introduce new methods/attributes.

I agree this means we shouldn't allow this, so whatever is changing in this PR to allow it, let's not make that change (even if it shows up in the ecosystem as a thing people try to do.)

> Mypy rejects the inheritance from `t`, not sure what you were doing that made it accept it.

Don't have the playground I used anymore, but probably it was the usual -- forgetting that mypy doesn't check all code by default.

**Comment by carljm** [comment]
(This PR needs conflict resolution again, with the bound-super PR that landed.)

**Comment by charliermarsh** [comment]
Sounds good -- I will rebase and address some of the initial feedback tonight.

**Comment by carljm** [comment]
> Shouldn't we worry about any new non-deterministic diagnostics to avoid making ty even more non-deterministic?

Yes, I guess I was thinking "the non-determinism in prefect isn't new", but if these particular diagnostics are really new (not totally sure, but I don't think I remember this block of added/removed diagnostics) we should try to avoid adding them.

File: crates/ty_python_semantic/src/types.rs (hunk 4 above)
Comment (carljm) [reply crates/ty_python_semantic/src/types.rs]: I also like @MichaReiser 's proposed terminology!

**Comment by AlexWaygood** [comment]
> > Shouldn't we worry about any new non-deterministic diagnostics to avoid making ty even more non-deterministic?
> 
> Yes, I guess I was thinking "the non-determinism in prefect isn't new", but if these particular diagnostics are really new (not totally sure, but I don't think I remember this block of added/removed diagnostics) we should try to avoid adding them.

I've seen the diagnostics in `src/prefect/flow_engine.py` come and go on quite a few other PRs; there's nothing new about those flakes in particular

**Comment by AlexWaygood** [comment]
I agree with Carl and Jelle that we definitely shouldn't allow this (we don't on `main`, and that's deliberate):

```py
class Foo: ...

def f(x: type[Foo]):
    class Y(x): ...
```

File: crates/ty_python_semantic/src/types/mro.rs [hunk 32]
```diff
@@ -176,6 +257,11 @@ impl<'db> Mro<'db> {
             // what MRO Python will give this class at runtime
             // (if an MRO is indeed resolvable at all!)
             _ => {
+                let Some((class_literal, _)) = class.stmt_class_literal(db) else {
+                    // Functional classes don't have explicit bases to resolve.
+                    return Ok(std::iter::once(ClassBase::Class(class)).collect());
+                };
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/mro.rs]: huh? Not sure I understand this comment. For a class defined as `X = type("X", (A, B), {})`, surely the explicit bases of `X` are `[A, B]`?

**Comment by charliermarsh** [comment]
Reducing the diff quite a bit here (hopefully) by using `ClassLiteral` in more places (i.e., pushing the match on `ClassLiteral` lower).

File: crates/ty_python_semantic/src/types/mro.rs (hunk 32 above)
Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/mro.rs]: Sorry, this comment is clearly wrong. (But we only ever call this particular method with a statement-based class.) I will clean up.

**Comment by charliermarsh** [comment]
Converting to draft while I work through the feedback.

File: crates/ruff_benchmark/benches/ty_walltime.rs [hunk 33]
```diff
@@ -163,7 +163,7 @@ static PANDAS: Benchmark = Benchmark::new(
         max_dep_date: "2025-06-17",
         python_version: PythonVersion::PY312,
     },
-    4000,
+    4057,
```
Comment (carljm) [inline crates/ruff_benchmark/benches/ty_walltime.rs]: You can stick to round numbers here and give us a buffer, so we don't have to bump this on every small change.

File: crates/ty_python_semantic/resources/mdtest/call/builtins.md [hunk 34]
```diff
@@ -23,14 +23,288 @@ tests for the `__class__` attribute.)
...
+
+```py
+class Base: ...
+
+Foo = type("Foo", (Base,), {"custom_attr": 42})
+foo = Foo()
+
+# error: [unresolved-attribute] "Object of type `Foo` has no attribute `custom_attr`"
+reveal_type(foo.custom_attr)  # revealed: Unknown
+```
```
Comment (carljm) [inline crates/ty_python_semantic/resources/mdtest/call/builtins.md]: I kinda think this behavior isn't great, and I'd rather have mypy/pyrefly's behavior (where all attributes are allowed, with type `Unknown`), or better, just attributes named in the namespace dict are allowed, with type `Unknown`. (Or we could even infer types from the assigned elements in the namespace dict?)

Not saying we should do it in this PR, though. And we probably don't even need a TODO for it here, we can wait for someone to file an issue.

File: crates/ty_python_semantic/resources/mdtest/call/builtins.md [hunk 35]
```diff
@@ -23,14 +23,288 @@ tests for the `__class__` attribute.)
...
+class Base: ...
+
+Foo = type("Foo", (Base,), {})
+
+def check_disjointness(x: Foo | int) -> None:
+    if isinstance(x, int):
+        reveal_type(x)  # revealed: int
+    else:
+        # Foo and int are not considered disjoint because `class C(Foo, int)` could exist.
+        reveal_type(x)  # revealed: Foo & ~int
```
Comment (carljm) [inline crates/ty_python_semantic/resources/mdtest/call/builtins.md]: This test demonstrates (and the comment in it explains) the opposite of what the prose above it claims.

File: crates/ty_python_semantic/resources/mdtest/call/builtins.md [hunk 36]
```diff
@@ -23,14 +23,288 @@ tests for the `__class__` attribute.)
...
+
+# Functional class inheriting from int is NOT disjoint from int
+IntSubclass = type("IntSubclass", (int,), {})
+
+def check_int_subclass(x: IntSubclass | str) -> None:
+    if isinstance(x, int):
+        # IntSubclass inherits from int, so it's included in the narrowed type
```
Comment (carljm) [inline crates/ty_python_semantic/resources/mdtest/call/builtins.md]: And this test isn't really about disjointness at all, just subtyping

File: crates/ty_python_semantic/src/types/infer/builder.rs [hunk 37]
```diff
@@ -599,6 +602,7 @@ impl<'db, 'ast> TypeInferenceBuilder<'db, 'ast> {
             if let DefinitionKind::Class(class) = definition.kind(self.db()) {
                 ty.inner_type()
                     .as_class_literal()
+                    .and_then(ClassLiteral::as_static)
                     .map(|class_literal| (class_literal, class.node(self.module())))
```
Comment (charliermarsh) [inline crates/ty_python_semantic/src/types/infer/builder.rs:612]: I _think_ we want to omit dynamic classes here.

**Review by carljm — COMMENTED** [review]
Holding off on more code review since this is currently in draft and getting revisions, but I did take a look at the tests quick.

File: crates/ty_python_semantic/src/types/infer/builder.rs
Comment (charliermarsh) [inline crates/ty_python_semantic/src/types/infer/builder.rs:1]: I'm not very confident in what's in here.

**Comment by charliermarsh** [comment]
Okay, remarking as ready for review:

- I renamed to `StaticClassLiteral` and `DynamicClassLiteral`.
- I removed a variety of special-casings (like for display, etc.) that were unnecessary and wrong. (Likely Claude fragments from iterating on this a few times.)
- I implemented `Definition` and span tracking for dynamic class literals. This enabled me to remove a lot of special-casing that was no longer necessary as it further unified the `ClassLiteral` interface.

The pieces in which I have lowest confidence:

- The actual call parsing and inference in `builder.rs`, and the fall-through handling.
- The MRO handling for dynamic classes.

File: crates/ty_python_semantic/resources/mdtest/call/builtins.md (hunk 34 above)
Comment (charliermarsh) [reply crates/ty_python_semantic/resources/mdtest/call/builtins.md]: Doing this in https://github.com/astral-sh/ruff/pull/22480 (in part because it actually helps the code generalize a bit more).

File: crates/ty_python_semantic/src/types.rs (hunk 4 above)
Comment (AlexWaygood) [reply crates/ty_python_semantic/src/types.rs]: Okay this was a great call @MichaReiser -- I find the code so much more readable now we've switched to this terminology!

File: crates/ty_python_semantic/resources/mdtest/call/builtins.md
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/call/builtins.md:1]: There are so many new tests here that it might be worth moving all `type()`-related assertions in this file to a new, standalone, `type.md` mdtest suite

File: crates/ty_python_semantic/src/types.rs [hunk 38]
```diff
@@ -12708,7 +12717,7 @@ impl get_size2::GetSize for EnumLiteralType<'_> {}
 
 impl<'db> EnumLiteralType<'db> {
     pub(crate) fn enum_class_instance(self, db: &'db dyn Db) -> Type<'db> {
-        self.enum_class(db).to_non_generic_instance(db)
+        Type::instance(db, self.enum_class(db).default_specialization(db))
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types.rs]: looks like a spurious change

```suggestion
        self.enum_class(db).to_non_generic_instance(db)
```

File: crates/ty_python_semantic/src/types.rs [hunk 39]
```diff
@@ -3248,11 +3248,14 @@ impl<'db> Type<'db> {
...
             {
-                enum_metadata(db, instance.class(db).class_literal(db).0)
-                    .and_then(|metadata| metadata.members.get_index(0).map(|(_, v)| *v))
-                    .map_or(Place::Undefined, Place::bound)
+                enum_metadata(db, instance.class_literal(db))
+                    .and_then(|metadata| {
+                        let (_, ty) = metadata.members.get_index(0)?;
+                        Some(Place::bound(*ty))
+                    })
+                    .unwrap_or(Place::Undefined)
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types.rs]: can be this if you rebase on `main`

```suggestion
                    .unwrap_or_default()
```

though idk if that's actually any clearer at the end of the day 😆

File: crates/ty_python_semantic/src/types/call/bind.rs [hunk 40]
```diff
@@ -1115,11 +1115,11 @@ impl<'db> Bindings<'db> {
                             }
 
                             // `dataclass` being used as a non-decorator
-                            if let [Some(Type::ClassLiteral(class_literal))] =
+                            if let [Some(Type::ClassLiteral(ClassLiteral::Static(class_literal)))] =
                                 overload.parameter_types()
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/call/bind.rs:1138]: Why must this specifically be a static class-literal? In theory we could support this, right? (We don't have to do it in this PR, but you could add a test and/or a TODO comment)

```py
from dataclasses import dataclass

T = type("T", (), {})
T = dataclass(T)
```

If we made this change, `CodeGeneratorKind::from_class` would need to be updated so that it accepted a `ClassLiteral` rather than a `StaticClassLiteral`

File: crates/ty_python_semantic/src/types/class.rs [hunk 41]
```diff
@@ -399,6 +405,346 @@ impl<'db> VarianceInferable<'db> for GenericAlias<'db> {
...
+
+    /// Returns whether this class is a protocol.
+    ///
+    // TODO: We should emit a diagnostic if a functional class (created via `type()`) attempts
+    // to inherit from `Protocol`, since functional classes can't be protocols. See also: `generic_context`.
+    pub(crate) fn is_protocol(self, db: &'db dyn Db) -> bool {
+        self.as_static().is_some_and(|class| class.is_protocol(db))
+    }
+
+    /// Returns whether this class is a `TypedDict`.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs:580]:
```suggestion
    /// Returns whether this class is a `TypedDict`.
    ///
    // TODO: We should emit a diagnostic if a functional class (created via `type()`) attempts
    // to inherit from `TypedDict`. To create a functional TypedDict, you should invoke
    // `TypedDict` as a function, not `type`. See also: `generic_context`, `is_protocol`.
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 42]
```diff
@@ -399,6 +405,346 @@ impl<'db> VarianceInferable<'db> for GenericAlias<'db> {
...
+        }
+    }
+
+    /// Returns whether this class is a tuple subclass.
+    pub(crate) fn is_tuple(self, db: &'db dyn Db) -> bool {
+        match self {
+            Self::Static(class) => class.is_tuple(db),
+            Self::Dynamic(_) => false, // Functional classes are never tuple subclasses
+        }
+    }
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]: The code here is correct but the comments are wrong:
- Functional types _can_ be tuple subclasses: your branch gets this right!

  ```py
  from ty_extensions import reveal_mro

  X = type("X", (tuple[int, str],), {})
  reveal_mro(X)  # Revealed MRO: (<class 'X'>, <class 'tuple[int, str]'>, <class 'Sequence[int | str]'>, <class 'Reversible[int | str]'>, <class 'Collection[int | str]'>, <class 'Iterable[int | str]'>, <class 'Container[int | str]'>, typing.Protocol, typing.Generic, <class 'object'>)
  ```

- But this method isn't actually asking "Is this class a tuple subclass?", it's asking "Is this the tuple class exactly?"

```suggestion
    /// Returns whether this class is `builtins.tuple` exactly
    pub(crate) fn is_tuple(self, db: &'db dyn Db) -> bool {
        match self {
            Self::Static(class) => class.is_tuple(db),
            Self::Dynamic(_) => false,
        }
    }
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 43]
```diff
@@ -399,6 +405,346 @@ impl<'db> VarianceInferable<'db> for GenericAlias<'db> {
...
+        self.as_static().is_some_and(|class| class.is_final(db))
+    }
+
+    /// Returns `true` if this class defines any ordering method (`__lt__`, `__le__`, `__gt__`,
+    /// `__ge__`) in its own body (not inherited). Used by `@total_ordering` to determine if
+    /// synthesis is valid.
+    pub(crate) fn has_own_ordering_method(self, db: &'db dyn Db) -> bool {
+        self.as_static()
+            .is_some_and(|class| class.has_own_ordering_method(db))
+    }
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs:653]: this will need to be revised in https://github.com/astral-sh/ruff/pull/22480, when we start adding support for dynamic classes to define attributes via the namespace parameter

File: crates/ty_python_semantic/src/types/class.rs [hunk 44]
```diff
@@ -399,6 +405,346 @@ impl<'db> VarianceInferable<'db> for GenericAlias<'db> {
...
+        match self {
+            Self::Static(class) => class.unknown_specialization(db),
+            Self::Dynamic(_) => ClassType::NonGeneric(self),
+        }
+    }
+
+    /// Returns the body scope of this class, if it's a statement class.
+    pub(crate) fn body_scope(self, db: &'db dyn Db) -> Option<ScopeId<'db>> {
+        self.as_static().map(|class| class.body_scope(db))
+    }
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]: this API now feels like a bit of a footgun, because I think you usually want to go via higher-level APIs for attribute access, etc. (which will work for both static classes and dynamic classes) rather than asking for the body scope. Considering that it is only used in one place, I'd be inclined to get rid of it:

```diff
diff --git a/crates/ty_python_semantic/src/place.rs b/crates/ty_python_semantic/src/place.rs
index 1eb7e0b511..6b44f328af 100644
--- a/crates/ty_python_semantic/src/place.rs
+++ b/crates/ty_python_semantic/src/place.rs
@@ -1606,7 +1606,9 @@ mod implicit_globals {
     use crate::place::{Definedness, PlaceAndQualifiers};
     use crate::semantic_index::symbol::Symbol;
     use crate::semantic_index::{place_table, use_def_map};
-    use crate::types::{KnownClass, MemberLookupPolicy, Parameter, Parameters, Signature, Type};
+    use crate::types::{
+        ClassLiteral, KnownClass, MemberLookupPolicy, Parameter, Parameters, Signature, Type,
+    };
     use ruff_python_ast::PythonVersion;
 
     use super::{DefinedPlace, Place, place_from_declarations};
@@ -1756,10 +1758,11 @@ mod implicit_globals {
             return smallvec::SmallVec::default();
         };
 
-        let Some(module_type_scope) = module_type.body_scope(db) else {
+        let ClassLiteral::Static(module_type) = module_type else {
             return smallvec::SmallVec::default();
         };
-        let module_type_symbol_table = place_table(db, module_type_scope);
+
+        let module_type_symbol_table = place_table(db, module_type.body_scope(db));
 
         module_type_symbol_table
             .symbols()
diff --git a/crates/ty_python_semantic/src/types/class.rs b/crates/ty_python_semantic/src/types/class.rs
index d67e927f39..5cf85f120c 100644
--- a/crates/ty_python_semantic/src/types/class.rs
+++ b/crates/ty_python_semantic/src/types/class.rs
@@ -621,11 +621,6 @@ impl<'db> ClassLiteral<'db> {
         }
     }
 
-    /// Returns the body scope of this class, if it's a statement class.
-    pub(crate) fn body_scope(self, db: &'db dyn Db) -> Option<ScopeId<'db>> {
-        self.as_static().map(|class| class.body_scope(db))
-    }
-
     /// Returns the definition of this class, if available.
     pub(crate) fn definition(self, db: &'db dyn Db) -> Option<Definition<'db>> {
         match self {
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 45]
```diff
@@ -399,6 +405,346 @@ impl<'db> VarianceInferable<'db> for GenericAlias<'db> {
...
+            Self::Static(class) => class.header_span(db),
+            Self::Dynamic(class) => class.header_span(db),
+        }
+    }
+
+    /// Returns whether this class is a disjoint base.
+    pub(super) fn as_disjoint_base(self, db: &'db dyn Db) -> Option<DisjointBase<'db>> {
+        self.as_static()
+            .and_then(|class| class.as_disjoint_base(db))
+    }
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs:721]: we may want to revise this in https://github.com/astral-sh/ruff/pull/22480, because a dynamic class could provide `__slots__` in the namespace dictionary, which would make it a disjoint base:

```pycon
>>> X = type("X", (), {"__slots__": ("a",)})
>>> class Foo(int, X): ...
... 
Traceback (most recent call last):
  File "<python-input-4>", line 1, in <module>
    class Foo(int, X): ...
TypeError: multiple bases have instance lay-out conflict
```

File: crates/ty_python_semantic/resources/mdtest/call/builtins.md [hunk 46]
```diff
@@ -61,6 +336,64 @@ type("Foo", (1, 2), {})
...
+`type[...]` (SubclassOf) types cannot be used as base classes. When a `type[...]` is used in the
+bases tuple, we can't synthesize a proper class type, so the fallback `type` is returned:
+
+```py
+class Base: ...
+
+def f(x: type[Base]):
+    # `type[Base]` is not allowed as a base class in type() calls.
+    # This prevents unsound code where the actual class could have incompatible methods.
+    reveal_type(type("Child", (x,), {}))  # revealed: type
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/call/builtins.md]: when we hit this situation for static class literals, we still infer the class as a class-literal, but (after emitting a diagnostic to tell the user off about it) we insert `Unknown` into the MRO. This has the nice property that we will allow arbitrary attributes to be accessed on instances of the class: the user gets one (and exactly one) diagnostic about the bad class definition, rather than getting many other diagnostics about unresolved attributes on instances of the class:

```py
from ty_extensions import reveal_mro

def f(x: type[int]):
    class Foo(x): ...  # error: [unsupported-base]

    reveal_mro(Foo)  # revealed: (<class 'Foo'>, Unknown, <class 'object'>)
```

Should we just do the same for dynamic class-literals?

File: crates/ty_python_semantic/resources/mdtest/call/builtins.md
Comment (AlexWaygood) [reply crates/ty_python_semantic/resources/mdtest/call/builtins.md:1]: Can you also add a test that attributes defined on `builtins.type` are accessible on dynamic classes? It looks like you get this behaviour correct on your branch, which is great:

```py
T = type("T", (), {})

# inherited from `builtins.type`:
reveal_type(T.__dictoffset__)  # revealed: int
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 47]
```diff
@@ -4025,183 +4332,672 @@ impl<'db> ClassLiteral<'db> {
...
+}
+
+/// A class created via the functional form: a three-argument `type()` call.
+///
+/// For example:
+/// ```python
+/// Foo = type("Foo", (Base,), {"attr": 1})
+/// ```
+///
+/// The type of `Foo` would be `type[Foo]` where `Foo` is a `DynamicClassLiteral` with:
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]: `type[]` types are different from class-literal types: `type[Foo]` means "the class object `Foo` or any subclass of `Foo`"; `<class 'Foo'>` means "the class object `Foo`, and only that exact class object (no subclasses)"

```suggestion
/// The type of `Foo` would be `<class 'Foo'>` where `Foo` is a `DynamicClassLiteral` with:
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 48]
```diff
@@ -4025,183 +4332,672 @@ impl<'db> ClassLiteral<'db> {
...
+///
+/// # Limitations
+///
+/// TODO: Attributes from the namespace dict (third argument to `type()`) are not tracked.
+/// This matches Pyright's behavior. For example:
+/// ```python
+/// Foo = type("Foo", (), {"attr": 42})
+/// Foo().attr  # Error: no attribute 'attr'
+/// ```
+/// Supporting namespace dict attributes would require parsing dict literals and tracking
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs:4678]: nit

```suggestion
/// This matches Pyright's behavior. For example:
///
/// ```python
/// Foo = type("Foo", (), {"attr": 42})
/// Foo().attr  # Error: no attribute 'attr'
/// ```
///
/// Supporting namespace dict attributes would require parsing dict literals and tracking
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 49]
```diff
@@ -4025,183 +4332,672 @@ impl<'db> ClassLiteral<'db> {
...
+/// the attribute types, similar to how TypedDict handles its fields.
+///
+/// # Salsa interning
+///
+/// Each `type()` call is uniquely identified by its location in the source code
+/// (`file`, `file_scope`, `node_index`), so two different `type()` calls always
+/// produce distinct `DynamicClassLiteral` instances, even if they have the
+/// same name and bases:
+/// ```python
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
/// same name and bases:
///
/// ```python
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 50]
```diff
@@ -4025,183 +4332,672 @@ impl<'db> ClassLiteral<'db> {
...
+
+    /// The file containing the `type()` call.
+    pub file: File,
+
+    /// The scope containing the `type()` call.
+    pub file_scope: FileScopeId,
+
+    /// The node index of the `type()` call expression, used to uniquely identify
+    /// the call site within the file.
+    pub node_index: NodeIndex,
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]: We may need to put some warnings in the doc-comments for some of these fields that they shouldn't be accessed when we're inferring types for a different module to the one the class was defined in? I think doing so would lead to overly aggressive cache invalidation. @MichaReiser will be able to say whether I'm spouting nonsense here or not

File: crates/ty_python_semantic/src/types/class.rs [hunk 51]
```diff
@@ -4025,183 +4332,672 @@ impl<'db> ClassLiteral<'db> {
...
+    /// Returns the range of the `type()` call expression that created this class.
+    pub(super) fn header_range(self, db: &'db dyn Db) -> TextRange {
+        let module = parsed_module(db, self.file(db)).load(db);
+        let node = module.get_by_index(self.node_index(db));
+        node.range()
+    }
+}
+
+#[salsa::tracked]
+impl<'db> DynamicClassLiteral<'db> {
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
#[salsa::tracked]
impl<'db> DynamicClassLiteral<'db> {
    /// Returns a [`Span`] with the range of the `type()` call expression.
    ///
    /// See [`Self::header_range`] for more details.
    pub(super) fn header_span(self, db: &'db dyn Db) -> Span {
        Span::from(self.file(db)).with_range(self.header_range(db))
    }

    /// Returns the range of the `type()` call expression that created this class.
    pub(super) fn header_range(self, db: &'db dyn Db) -> TextRange {
        let module = parsed_module(db, self.file(db)).load(db);
        let node = module.get_by_index(self.node_index(db));
        node.range()
    }

```

File: crates/ty_python_semantic/src/types/class.rs [hunk 52]
```diff
@@ -4025,183 +4332,672 @@ impl<'db> ClassLiteral<'db> {
...
+        self,
+        db: &'db dyn Db,
+    ) -> Result<Type<'db>, FunctionalMetaclassConflict<'db>> {
+        let bases = self.bases(db);
+
+        // If no bases, metaclass is `type`.
+        // To dynamically create a class with no bases that has a custom metaclass,
+        // you have to invoke that metaclass rather than `type()`.
+        if bases.is_empty() {
+            return Ok(KnownClass::Type.to_instance(db));
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]: this isn't quite correct: we have this behaviour on your branch:

```py
class Foo: ...
Bar = type("Bar", (), {})

reveal_type(Foo.__class__)  # <class 'type'>
reveal_type(Bar.__class__)  # type
```

so whereas for the static class, we return "the class `type` itself", for the functional class we return "instance of `type`". We should be consistent here and return "the class `type` itself" in both cases:

```suggestion
            return Ok(KnownClass::Type.to_class_literal(db));
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 53]
```diff
@@ -4025,183 +4332,672 @@ impl<'db> ClassLiteral<'db> {
...
+    pub(crate) fn class_member(
+        self,
+        db: &'db dyn Db,
+        name: &str,
+        policy: MemberLookupPolicy,
+    ) -> PlaceAndQualifiers<'db> {
+        let result = MroLookup::new(db, self.iter_mro(db)).class_member(
+            name, policy, None,  // No inherited generic context.
+            false, // Functional classes are never `object`.
+        );
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs:4889]: nit: I'd find this more readable

```suggestion
        let result = MroLookup::new(db, self.iter_mro(db)).class_member(
            name,
            policy,
            None,  // No inherited generic context.
            false,  // Functional classes are never `object`.
        );
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 54]
```diff
@@ -4025,183 +4332,672 @@ impl<'db> ClassLiteral<'db> {
...
-            })
-            .dedup();
+impl<'db> ClassMemberResult<'db> {
+    /// Finalize the lookup result by handling dynamic type intersection.
+    pub(super) fn finalize(self, db: &'db dyn Db) -> PlaceAndQualifiers<'db> {
+        match self {
+            ClassMemberResult::TypedDict => {
+                // Caller should handle TypedDict case before calling finalize
+                unreachable!("finalize called on TypedDict result")
+            }
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]: you can do this without the `unreachable!()` if you add another intermediate type:

```diff
diff --git a/crates/ty_python_semantic/src/types/class.rs b/crates/ty_python_semantic/src/types/class.rs
index d67e927f39..d773c7daef 100644
--- a/crates/ty_python_semantic/src/types/class.rs
+++ b/crates/ty_python_semantic/src/types/class.rs
@@ -488,7 +488,7 @@ impl<'db> ClassLiteral<'db> {
                 // Functional classes don't have inherited generic context and are never `object`.
                 let result = MroLookup::new(db, mro_iter).class_member(name, policy, None, false);
                 match result {
-                    ClassMemberResult::Done { .. } => result.finalize(db),
+                    ClassMemberResult::Done(result) => result.finalize(db),
                     ClassMemberResult::TypedDict => KnownClass::TypedDictFallback
                         .to_class_literal(db)
                         .find_name_in_mro_with_policy(db, name, policy)
@@ -2634,7 +2634,7 @@ impl<'db> StaticClassLiteral<'db> {
         );
 
         match result {
-            ClassMemberResult::Done { .. } => result.finalize(db),
+            ClassMemberResult::Done(result) => result.finalize(db),
 
             ClassMemberResult::TypedDict => KnownClass::TypedDictFallback
                 .to_class_literal(db)
@@ -4713,7 +4713,7 @@ impl<'db> DynamicClassLiteral<'db> {
         );
 
         match result {
-            ClassMemberResult::Done { .. } => result.finalize(db),
+            ClassMemberResult::Done(result) => result.finalize(db),
             ClassMemberResult::TypedDict => {
                 // Simplified `TypedDict` handling without type mapping.
                 KnownClass::TypedDictFallback
@@ -4848,10 +4848,10 @@ impl<'db, I: Iterator<Item = ClassBase<'db>>> MroLookup<'db, I> {
             }
         }
 
-        ClassMemberResult::Done {
+        ClassMemberResult::Done(CompletedMemberLookup {
             lookup_result,
             dynamic_type,
-        }
+        })
     }
 
     /// Look up an instance member by iterating through the MRO.
@@ -4942,50 +4942,46 @@ impl<'db, I: Iterator<Item = ClassBase<'db>>> MroLookup<'db, I> {
 /// Result of class member lookup from MRO iteration.
 pub(super) enum ClassMemberResult<'db> {
     /// Found the member or exhausted the MRO.
-    Done {
-        lookup_result: LookupResult<'db>,
-        dynamic_type: Option<Type<'db>>,
-    },
+    Done(CompletedMemberLookup<'db>),
     /// Encountered a `TypedDict` base.
     TypedDict,
 }
 
-impl<'db> ClassMemberResult<'db> {
+pub(super) struct CompletedMemberLookup<'db> {
+    lookup_result: LookupResult<'db>,
+    dynamic_type: Option<Type<'db>>,
+}
+
+impl<'db> CompletedMemberLookup<'db> {
     /// Finalize the lookup result by handling dynamic type intersection.
     pub(super) fn finalize(self, db: &'db dyn Db) -> PlaceAndQualifiers<'db> {
-        match self {
-            ClassMemberResult::TypedDict => {
-                // Caller should handle TypedDict case before calling finalize
-                unreachable!("finalize called on TypedDict result")
-            }
-            ClassMemberResult::Done {
-                lookup_result,
-                dynamic_type,
-            } => match (PlaceAndQualifiers::from(lookup_result), dynamic_type) {
-                (symbol_and_qualifiers, None) => symbol_and_qualifiers,
+        match (
+            PlaceAndQualifiers::from(self.lookup_result),
+            self.dynamic_type,
+        ) {
+            (symbol_and_qualifiers, None) => symbol_and_qualifiers,
 
-                (
-                    PlaceAndQualifiers {
-                        place: Place::Defined(DefinedPlace { ty, .. }),
-                        qualifiers,
-                    },
-                    Some(dynamic),
-                ) => Place::bound(
-                    IntersectionBuilder::new(db)
-                        .add_positive(ty)
-                        .add_positive(dynamic)
-                        .build(),
-                )
-                .with_qualifiers(qualifiers),
+            (
+                PlaceAndQualifiers {
+                    place: Place::Defined(DefinedPlace { ty, .. }),
+                    qualifiers,
+                },
+                Some(dynamic),
+            ) => Place::bound(
+                IntersectionBuilder::new(db)
+                    .add_positive(ty)
+                    .add_positive(dynamic)
+                    .build(),
+            )
+            .with_qualifiers(qualifiers),
 
-                (
-                    PlaceAndQualifiers {
-                        place: Place::Undefined,
-                        qualifiers,
-                    },
-                    Some(dynamic),
-                ) => Place::bound(dynamic).with_qualifiers(qualifiers),
-            },
+            (
+                PlaceAndQualifiers {
+                    place: Place::Undefined,
+                    qualifiers,
+                },
+                Some(dynamic),
+            ) => Place::bound(dynamic).with_qualifiers(qualifiers),
         }
     }
 }
```

**Review by AlexWaygood — COMMENTED** [review]
Sorry, just a partial review but I gotta go!

File: crates/ty_python_semantic/src/types/class.rs (hunk 44 above)
Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/class.rs]: Smart!

File: crates/ty_python_semantic/src/types/class.rs (hunk 53 above)
Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/class.rs:4889]: Rust un-formats that away sadly :(

File: crates/ruff_benchmark/benches/ty_walltime.rs [hunk 55]
```diff
@@ -171,7 +171,7 @@ static PANDAS: Benchmark = Benchmark::new(
         max_dep_date: "2025-06-17",
         python_version: PythonVersion::PY312,
     },
-    3800,
+    4200,
```
Comment (carljm) [inline crates/ruff_benchmark/benches/ty_walltime.rs]: I suspect we don't need this? No significant number of new diagnostics on pandas in the current iteration of the PR.

File: crates/ty_python_semantic/resources/mdtest/call/type.md [hunk 56]
```diff
@@ -0,0 +1,489 @@
...
+
+# error: [invalid-argument-type] "Argument to function `takes_foo1` is incorrect: Expected `mdtest_snippet.Foo @ src/mdtest_snippet.py:5`, found `mdtest_snippet.Foo @ src/mdtest_snippet.py:6`"
+takes_foo1(foo2)
+# error: [invalid-argument-type] "Argument to function `takes_foo2` is incorrect: Expected `mdtest_snippet.Foo @ src/mdtest_snippet.py:6`, found `mdtest_snippet.Foo @ src/mdtest_snippet.py:5`"
+takes_foo2(foo1)
+```
+
+## Instances and attribute access
+
+Instances of functional classes are typed with the synthesized class name. Attributes from all base
```
Comment (carljm) [inline crates/ty_python_semantic/resources/mdtest/call/type.md]: nit: should we match the code and call these "dynamic classes" throughout the tests? It seems clearer to me than "functional classes".

File: crates/ty_python_semantic/resources/mdtest/call/type.md [hunk 57]
```diff
@@ -0,0 +1,489 @@
...
+## MRO errors
+
+MRO errors are detected and reported:
+
+```py
+class A: ...
+
+# Duplicate bases are detected
+# error: [duplicate-base] "Duplicate base class <class 'A'> in class `Dup`"
+Dup = type("Dup", (A, A), {})
```
Comment (carljm) [inline crates/ty_python_semantic/resources/mdtest/call/type.md:474]: There's an issue here that shows up in pywin32 in the ecosystem:

```py
from not_found import Bar, Baz  # import from unknown module to get values of type Unknown

class Child(Bar, Baz):  # no diagnostic here, on main or this PR
    pass

X = type("X", (Bar, Baz), {})  # duplicate-bases diagnostic here on this PR
```

We don't emit a duplicate-bases diagnostic on `Child`, but in this PR we do on `X`. There shouldn't be a diagnostic on either one -- as far as we know (and should assume), `Bar` and `Baz` are separate types and it's perfectly valid to inherit from both; we just don't know what types they are.

The way this is handled in the static-class MRO logic is that we don't emit duplicate-base errors until after we've tried and failed to linearize an MRO -- and multiple `Unknown` or `Any` bases doesn't fail linearization. Might be ideal to see if we can use the same approach for dynamic classes?

If not, the other approach would be to manually avoid emitting this diagnostic if the "dupes" are `Type::Dynamic`.

File: crates/ty_python_semantic/resources/mdtest/call/type.md [hunk 58]
```diff
@@ -0,0 +1,489 @@
...
+```
+
+## Cyclic functional class definitions
+
+Self-referential class definitions using `type()` are detected. The name being defined is referenced
+in the bases tuple before it's available:
+
+```pyi
+# error: [unresolved-reference] "Name `X` used when not defined"
+X = type("X", (X,), {})
```
Comment (carljm) [inline crates/ty_python_semantic/resources/mdtest/call/type.md:523]: This means we aren't treating the bases of a dynamic class as forward references (deferred evaluation) in a stub file?

I think that's fine -- nobody should be using `type(...)` in a stub file anyway.

File: crates/ty_python_semantic/src/types/call/bind.rs [hunk 59]
```diff
@@ -1115,11 +1115,11 @@ impl<'db> Bindings<'db> {
...
                             {
                                 let params = DataclassParams::default_params(db);
-                                overload.set_return_type(Type::from(ClassLiteral::new(
+                                overload.set_return_type(Type::from(StaticClassLiteral::new(
```
Comment (carljm) [inline crates/ty_python_semantic/src/types/call/bind.rs]: Should there be a TODO here that this should also work for dynamic class literal types?

**Review by carljm — COMMENTED** [review]
I also didn't make it through a complete review before needing to head out, but I left what I've got so far.

File: crates/ty_python_semantic/resources/mdtest/call/type.md (hunk 58 above)
Comment (AlexWaygood) [reply crates/ty_python_semantic/resources/mdtest/call/type.md:523]: Yeah, I specifically asked Charlie to add this test to demonstrate that we wouldn't panic on cyclic definitions in stub files 😄

File: crates/ty_python_semantic/resources/mdtest/call/type.md [hunk 60]
```diff
@@ -0,0 +1,489 @@
...
+## Invalid calls
+
+Other numbers of arguments are invalid:
+
+```py
+# error: [no-matching-overload] "No overload of class `type` matches arguments"
+type("Foo", ())
+
+# error: [no-matching-overload] "No overload of class `type` matches arguments"
+type("Foo", (), {}, weird_other_arg=42)
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/call/type.md]: but note that that `weird_other_arg` would actually be _mandatory_ if you created a dynamic class that had `Base` as a superclass, and `Base.__init_subclass__` required a `weird_other_arg` argument to be passed to it:

```pycon
>>> class Base:
...     def __init_subclass__(cls, weird_other_arg: int): ...
...     
>>> X = type("X", (Base,), {}, weird_other_arg=42)
>>> Y = type("X", (Base,), {})
Traceback (most recent call last):
  File "<python-input-3>", line 1, in <module>
    Y = type("X", (Base,), {})
TypeError: Base.__init_subclass__() missing 1 required positional argument: 'weird_other_arg'
```

We don't handle this properly yet for static classes (https://github.com/astral-sh/ty/issues/1541), though we have an open PR to fix that (https://github.com/astral-sh/ruff/pull/22185). Maybe we should just land that PR and then rebase this on top of that...

File: crates/ty_python_semantic/resources/mdtest/call/type.md
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/call/type.md:1]: What happens if you create a type with a dynamic name?

```py
def f(x: str):
    X = type(x, (), {})
    reveal_type(X)]
```

I think our ideal behaviour there would maybe be that we'd still infer it as a class-literal type, but in our display we'd show something like `<class '<unknown>'> @ main.py:42`...?

---

What happens if you create a type with dynamic bases?

```py
from ty_extensions import reveal_mro

def f(bases: tuple[type, ...]):
    X = type("X", bases, {})
    reveal_type(X)
    reveal_mro(X)
```

I think our ideal behaviour there would maybe be that we'd still infer it as a class-literal type, but the revealed MRO would be `(<class 'X'>, Unknown, <class 'object'>)`, which would lead us to treat instances of the class highly dynamically (they would have all possible attributes available on them)

---

What happens for things like this?

```py
def f(*args, **kwargs):
    A = type(*args, **kwargs)
    reveal_type(A)

    B = type("B", *args, **kwargs)
    reveal_type(B)

    C = type("C", (), *args, **kwargs)
    reveal_type(C)

    D = type("D", (), {}, **kwargs)
    reveal_type(D)
```

For `A` and `B`, `type[Any]` might lead to the fewest false-positive errors. For `C` and `D`, it feels like we could infer class-literal types...?

File: crates/ty_python_semantic/resources/mdtest/call/type.md [hunk 61]
```diff
@@ -0,0 +1,489 @@
...
+
+```py
+T = type("T", (), {})
+
+# Inherited from `builtins.type`:
+# TODO: these should work but currently don't resolve
+# reveal_type(T.__dictoffset__)  # revealed: int
+# reveal_type(T.__name__)  # revealed: str
+# reveal_type(T.__bases__)  # revealed: tuple[type, ...]
+# reveal_type(T.__mro__)  # revealed: tuple[type, ...]
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/call/type.md]: Why are these commented out? They all pass for me locally 😆

```suggestion
# Inherited from `builtins.type`:
reveal_type(T.__dictoffset__)  # revealed: int
reveal_type(T.__name__)  # revealed: str
reveal_type(T.__bases__)  # revealed: tuple[type, ...]
reveal_type(T.__mro__)  # revealed: tuple[type, ...]
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 62]
```diff
@@ -5243,17 +6118,28 @@ impl KnownClass {
...
-            )
+            class_literal
+                .apply_specialization(db, |_| generic_context.specialize(db, specialization))
         }
 
+        let Type::ClassLiteral(ClassLiteral::Static(class_literal)) = self.to_class_literal(db)
+        else {
+            return None;
+        };
+
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
        let class_literal = self.to_class_literal(db).as_class_literal()?.as_static()?;
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 63]
```diff
@@ -6065,6 +6955,73 @@ impl KnownClass {
...
+                                     and `{metaclass2}` (metaclass of base class `{base2}`) \
+                                     have no subclass relationship",
+                                class = dynamic_class.name(db),
+                                metaclass1 = metaclass1.name(db),
+                                base1 = base1.display(db),
+                                metaclass2 = metaclass2.name(db),
+                                base2 = base2.display(db),
+                            ));
+                        }
+                    }
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs:7111]:
```suggestion
                    // Check for metaclass conflicts
                    if let Err(FunctionalMetaclassConflict {
                        metaclass1,
                        base1,
                        metaclass2,
                        base2,
                    }) = dynamic_class.try_metaclass(db)
                        && let Some(builder) =
                            context.report_lint(&CONFLICTING_METACLASS, call_expression)
                    {
                        builder.into_diagnostic(format_args!(
                            "The metaclass of a derived class (`{class}`) \
                            must be a subclass of the metaclasses of all its bases, \
                            but `{metaclass1}` (metaclass of base class `{base1}`) \
                            and `{metaclass2}` (metaclass of base class `{base2}`) \
                            have no subclass relationship",
                            class = dynamic_class.name(db),
                            metaclass1 = metaclass1.name(db),
                            base1 = base1.display(db),
                            metaclass2 = metaclass2.name(db),
                            base2 = base2.display(db),
                        ));
                    }
```

But given that this is the exact same message that we emit for static classes with metaclass conflicts in `infer/builder.rs`, maybe we could factor out a standalone `report_*` function in `types/diagnostic.rs`, to avoid the repetition?

File: crates/ty_python_semantic/src/types/class.rs [hunk 64]
```diff
@@ -4061,161 +4417,668 @@ impl<'db> ClassLiteral<'db> {
...
+                    qualifiers,
+                },
+                Some(dynamic),
+            ) => Place::bound(dynamic).with_qualifiers(qualifiers),
+        }
     }
 }
 
+/// Result of instance member lookup from MRO iteration.
+pub(super) enum InstanceMemberResult<'db> {
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs:5173]:
```suggestion
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub(super) enum InstanceMemberResult<'db> {
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 65]
```diff
@@ -6065,6 +6955,73 @@ impl KnownClass {
...
+                        match error {
+                            FunctionalMroError::DuplicateBases(duplicates) => {
+                                if let Some(builder) =
+                                    context.report_lint(&DUPLICATE_BASE, call_expression)
+                                {
+                                    builder.into_diagnostic(format_args!(
+                                        "Duplicate base class{} {} in class `{}`",
+                                        if duplicates.len() == 1 { "" } else { "es" },
+                                        duplicates.iter().map(|base| base.display(db)).join(", "),
+                                        dynamic_class.name(db),
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
                                        "Duplicate base class{maybe_s} {dupes} in class `{class}`",
                                        maybe_s = if duplicates.len() == 1 { "" } else { "es" },
                                        dupes = duplicates.iter().map(|base| base.display(db)).join(", "),
                                        class = dynamic_class.name(db),
```

File: crates/ty_python_semantic/resources/mdtest/call/type.md
Comment (AlexWaygood) [reply crates/ty_python_semantic/resources/mdtest/call/type.md:1]: I'd also love some x-failing tests for the various diagnostics that we plan to add in followups:
- `Protocol` in the bases list
- `TypedDict` in the bases list
- `NamedTuple` in the bases list
- `Generic[T]` in the bases list
- `Enum` (or any `Enum` subclass) in the bases list

File: crates/ty_python_semantic/src/types/enums.rs [hunk 66]
```diff
@@ -139,13 +156,15 @@ pub(crate) fn enum_metadata<'db>(
...
-                                        class
+                                let auto_value_ty =
+                                    if Type::ClassLiteral(ClassLiteral::Static(class))
+                                        .is_subtype_of(db, KnownClass::StrEnum.to_subclass_of(db))
+                                    {
+                                        Type::string_literal(db, &name.to_lowercase())
+                                    } else {
+                                        let custom_mixins: smallvec::SmallVec<
+                                            [Option<KnownClass>; 1],
+                                        > = class
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/enums.rs]: oof, splitting that type annotation over three lines is ugly 😆 Let's just import `SmallVec` here?

```diff
diff --git a/crates/ty_python_semantic/src/types/enums.rs b/crates/ty_python_semantic/src/types/enums.rs
index 2bb0e4e4d1..f5067cc675 100644
--- a/crates/ty_python_semantic/src/types/enums.rs
+++ b/crates/ty_python_semantic/src/types/enums.rs
@@ -1,5 +1,6 @@
 use ruff_python_ast::name::Name;
 use rustc_hash::FxHashMap;
+use smallvec::SmallVec;
 
 use crate::{
     Db, FxIndexMap,
@@ -162,23 +163,22 @@ pub(crate) fn enum_metadata<'db>(
                                     {
                                         Type::string_literal(db, &name.to_lowercase())
                                     } else {
-                                        let custom_mixins: smallvec::SmallVec<
-                                            [Option<KnownClass>; 1],
-                                        > = class
-                                            .iter_mro(db, None)
-                                            .skip(1)
-                                            .filter_map(ClassBase::into_class)
-                                            .filter(|class| {
-                                                !Type::from(*class).is_subtype_of(
-                                                    db,
-                                                    KnownClass::Enum.to_subclass_of(db),
-                                                )
-                                            })
-                                            .map(|class| class.known(db))
-                                            .filter(|class| {
-                                                !matches!(class, Some(KnownClass::Object))
-                                            })
-                                            .collect();
+                                        let custom_mixins: SmallVec<[Option<KnownClass>; 1]> =
+                                            class
+                                                .iter_mro(db, None)
+                                                .skip(1)
+                                                .filter_map(ClassBase::into_class)
+                                                .filter(|class| {
+                                                    !Type::from(*class).is_subtype_of(
+                                                        db,
+                                                        KnownClass::Enum.to_subclass_of(db),
+                                                    )
+                                                })
+                                                .map(|class| class.known(db))
+                                                .filter(|class| {
+                                                    !matches!(class, Some(KnownClass::Object))
+                                                })
+                                                .collect();
 
                                         // `IntEnum`s have the same `auto()` behaviour to enums inheriting from `(int, Enum)`,
                                         // and `IntEnum`s also have `int` in their MROs, so both cases are handled here.
```

File: crates/ty_python_semantic/src/types/instance.rs [hunk 67]
```diff
@@ -35,7 +35,12 @@ impl<'db> Type<'db> {
     }
 
     pub(crate) fn instance(db: &'db dyn Db, class: ClassType<'db>) -> Self {
-        let (class_literal, specialization) = class.class_literal(db);
+        let Some((class_literal, specialization)) = class.static_class_literal(db) else {
+            // Functional classes don't have a class literal; just return a nominal instance.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/instance.rs]:
```suggestion
            // Dynamic classes cannot be `TypedDict`s or protocols and they cannot be
            // the class `builtins.tuple`.
```

But I think it would be more future-proof to do an explicit `match` here over the `ClassLiteral` variant rather than calling `.static_class_literal(db)`. In the future we intend to add another `ClassLiteral` variant corresponding to functional `TypeDict`s; for that variant, we will want to go down the same codepath as the `class_literal.is_typed_dict(db).then(|| Type::typed_dict(class))` bit of this method a few lines below.

File: crates/ty_python_semantic/src/types/list_members.rs
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/list_members.rs:1]: Can we add some tests to https://github.com/astral-sh/ruff/blob/main/crates/ty_python_semantic/resources/mdtest/ide_support/all_members.md that demonstrate which members our autocomplete machinery considers to be available on instances of dynamic classes?

File: crates/ty_python_semantic/src/types/overrides.rs [hunk 68]
```diff
@@ -45,7 +45,7 @@ const PROHIBITED_NAMEDTUPLE_ATTRS: &[&str] = &[
     "_source",
 ];
 
-pub(super) fn check_class<'db>(context: &InferContext<'db, '_>, class: ClassLiteral<'db>) {
+pub(super) fn check_class<'db>(context: &InferContext<'db, '_>, class: StaticClassLiteral<'db>) {
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/overrides.rs:51]: We will want to change this in https://github.com/astral-sh/ruff/pull/22480 so that it accepts dynamic classes too: if we allow dynamic classes to define attributes in their namespace dictionary, we should also check whether those attributes are valid overrides of attributes in their superclasses.

File: crates/ty_python_semantic/src/types/infer/builder.rs (hunk 37 above)
Comment (AlexWaygood) [reply crates/ty_python_semantic/src/types/infer/builder.rs:612]: It looks like most of these checks either don't apply to dynamic classes, or we have them independently implemented elsewhere for dynamic classes. So I think this is fine. But we should rename the method to `check_static_class_definitions, and mention in the docstring that we only iterate over class definitions created using `class` statements.

File: crates/ty_python_semantic/resources/mdtest/call/type.md
Comment (AlexWaygood) [reply crates/ty_python_semantic/resources/mdtest/call/type.md:1]: What happens if you provide an explicit annotation when creating a dynamic class? I don't actually care _too_ much about our behaviour here right now, because we intend to change how this stuff works more broadly pretty soon in https://github.com/astral-sh/ty/issues/136. But let's add a test for it:

```py
T: type = type("T", (), {})
reveal_type(T)
```

File: crates/ty_python_semantic/src/types/infer/builder.rs [hunk 69]
```diff
@@ -5398,6 +5407,27 @@ impl<'db, 'ast> TypeInferenceBuilder<'db, 'ast> {
...
+                                        self.infer_call_expression_impl(
+                                            call_expr,
+                                            callable_type,
+                                            tcx,
+                                        )
+                                    })
+                            } else {
+                                self.infer_call_expression_impl(call_expr, callable_type, tcx)
+                            }
+                        }
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/infer/builder.rs:5419]:
```suggestion
                        // Only handle 3-arg type() calls specially to capture the definition.
                        // 1-arg type() calls are handled by normal call binding.
                        Some(KnownClass::Type)
                            if call_expr.arguments.args.len() == 3
                                && call_expr.arguments.keywords.is_empty() =>
                        {
                            // Try to extract the functional class with definition.
                            // Fall back to regular call binding if extraction fails
                            // (e.g., for cyclic references where names aren't resolved yet).
                            self.infer_functional_type_expression(call_expr, definition)
                                .unwrap_or_else(|| {
                                    self.infer_call_expression_impl(call_expr, callable_type, tcx)
                                })
                        }
```

File: crates/ty_python_semantic/src/types/infer/builder.rs [hunk 70]
```diff
@@ -6001,6 +6031,303 @@ impl<'db, 'ast> TypeInferenceBuilder<'db, 'ast> {
...
+        let db = self.db();
+        let arguments = &call_expr.arguments;
+
+        // First, check if the name argument is a string literal.
+        let name_arg = &arguments.args[0];
+        let name = if let ast::Expr::StringLiteral(string_lit) = name_arg {
+            ast::name::Name::new(string_lit.value.to_str())
+        } else {
+            return None;
+        };
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/infer/builder.rs]: we should check whether we can infer the name as a string-literal _type_ rather than checking whether it's a string-literal _node_, so that we can support things like

```py
name = "some very very long name"
T = type(name, (), {})
```

File: crates/ty_python_semantic/src/types/infer/builder.rs [hunk 71]
```diff
@@ -6001,6 +6031,303 @@ impl<'db, 'ast> TypeInferenceBuilder<'db, 'ast> {
...
+        // used for Protocol/TypedDict detection which doesn't apply here).
+        let placeholder_class: ClassLiteral<'db> =
+            KnownClass::Object.try_to_class_literal(db).unwrap().into();
+
+        let base_classes: Option<Box<[ClassBase<'db>]>> = bases_type
+            .exact_tuple_instance_spec(db)
+            .and_then(|tuple_spec| {
+                tuple_spec
+                    .fixed_elements()
+                    .enumerate()
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/infer/builder.rs]: I think here you want to do something like this:

```diff
diff --git a/crates/ty_python_semantic/src/types/infer/builder.rs b/crates/ty_python_semantic/src/types/infer/builder.rs
index b3cacb5663..96c3243ad0 100644
--- a/crates/ty_python_semantic/src/types/infer/builder.rs
+++ b/crates/ty_python_semantic/src/types/infer/builder.rs
@@ -6077,10 +6077,13 @@ impl<'db, 'ast> TypeInferenceBuilder<'db, 'ast> {
             KnownClass::Object.try_to_class_literal(db).unwrap().into();
 
         let base_classes: Option<Box<[ClassBase<'db>]>> = bases_type
-            .exact_tuple_instance_spec(db)
-            .and_then(|tuple_spec| {
-                tuple_spec
-                    .fixed_elements()
+            .tuple_instance_spec(db)
+            .as_deref()
+            .and_then(|spec|spec.as_fixed_length())
+            .and_then(|tuple| {
+                tuple
+                    .elements_slice()
+                    .iter()
                     .enumerate()
                     .map(|(idx, base)| {
                         // First try the standard conversion.
diff --git a/crates/ty_python_semantic/src/types/tuple.rs b/crates/ty_python_semantic/src/types/tuple.rs
index dfc484cabd..2bd955432b 100644
--- a/crates/ty_python_semantic/src/types/tuple.rs
+++ b/crates/ty_python_semantic/src/types/tuple.rs
@@ -1313,6 +1313,13 @@ pub enum Tuple<T> {
 }
 
 impl<T> Tuple<T> {
+    pub(crate) fn as_fixed_length(&self) -> Option<&FixedLengthTuple<T>> {
+        match self {
+            Tuple::Fixed(tuple) => Some(tuple),
+            Tuple::Variable(_) => None,
+        }
+    }
+
     pub(crate) const fn homogeneous(element: T) -> Self {
         Self::Variable(VariableLengthTuple::homogeneous(element))
     }
```

There's two changes here:
- Use `tuple_instance_spec()` rather than `exact_tuple_instance_spec()`. Tuple subclasses should be fine here. We could actually add a test for this:
- Make sure that the tuple is a fixed-length tuple. `Tuple::fixed_elements()` doesn't do this for you: if it's a tuple like `tuple[int, *tuple[str, ...]]`, it will give you the `int` element (the "fixed element"), then stop.

File: crates/ty_python_semantic/resources/mdtest/call/type.md (hunk 56 above)
Comment (charliermarsh) [reply crates/ty_python_semantic/resources/mdtest/call/type.md]: Thank you, sorry. These are missed renames.

File: crates/ty_python_semantic/src/types/infer/builder.rs [hunk 72]
```diff
@@ -6001,6 +6031,303 @@ impl<'db, 'ast> TypeInferenceBuilder<'db, 'ast> {
...
+            Some(Type::unknown())
+        }
+    }
+
+    /// Try to infer a 3-argument `type(name, bases, dict)` call expression.
+    ///
+    /// This handles `type()` calls outside of assignment contexts (e.g., as base classes).
+    /// Returns `Some(Type)` if the call matches the pattern, `None` to fall through to
+    /// regular call binding.
+    fn try_infer_functional_type_call(
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/infer/builder.rs]: It looks like there's quite a lot of duplication between this and the method above. Can we not have them both call into a `infer_functional_type_call_impl` method or something?

File: crates/ty_python_semantic/src/types/mro.rs [hunk 73]
```diff
@@ -106,6 +85,16 @@ impl<'db> Mro<'db> {
             resolved_bases.push(ClassBase::Generic);
         }
 
+        let class = class_literal.apply_optional_specialization(db, specialization);
+
+        // Special-case `NotImplementedType`: typeshed says that it inherits from `Any`,
+        // but this causes more problems than it fixes.
+        if class_literal.is_known(db, KnownClass::NotImplementedType) {
+            return Ok(Self::from([ClassBase::Class(class), ClassBase::object(db)]));
+        }
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/mro.rs]: I've been meaning for a while now to move this special casing to `class.rs`, where it would make more sense. Since this code is moving anyway in this PR, you could make that change here (or in a standalone PR and then rebase this on top of it):

```diff
diff --git a/crates/ty_python_semantic/src/types/class.rs b/crates/ty_python_semantic/src/types/class.rs
index 32029a5617..ded5d5d9bc 100644
--- a/crates/ty_python_semantic/src/types/class.rs
+++ b/crates/ty_python_semantic/src/types/class.rs
@@ -2280,20 +2280,24 @@ impl<'db> StaticClassLiteral<'db> {
         let class_definition =
             semantic_index(db, self.file(db)).expect_single_definition(class_stmt);
 
-        if self.is_known(db, KnownClass::VersionInfo) {
-            let tuple_type = TupleType::new(db, &TupleSpec::version_info_spec(db))
-                .expect("sys.version_info tuple spec should always be a valid tuple");
-
-            Box::new([
-                definition_expression_type(db, class_definition, &class_stmt.bases()[0]),
-                Type::from(tuple_type.to_class_type(db)),
-            ])
-        } else {
-            class_stmt
+        match self.known(db) {
+            Some(KnownClass::VersionInfo) => {
+                let tuple_type = TupleType::new(db, &TupleSpec::version_info_spec(db))
+                    .expect("sys.version_info tuple spec should always be a valid tuple");
+
+                // Special-case `NotImplementedType`: typeshed says that it inherits from `Any`,
+                // but this causes more problems than it fixes.
+                Box::new([
+                    definition_expression_type(db, class_definition, &class_stmt.bases()[0]),
+                    Type::from(tuple_type.to_class_type(db)),
+                ])
+            }
+            Some(KnownClass::NotImplementedType) => Box::new([]),
+            _ => class_stmt
                 .bases()
                 .iter()
                 .map(|base_node| definition_expression_type(db, class_definition, base_node))
-                .collect()
+                .collect(),
         }
     }
 
diff --git a/crates/ty_python_semantic/src/types/mro.rs b/crates/ty_python_semantic/src/types/mro.rs
index eb6e05e58c..9f60c590ac 100644
--- a/crates/ty_python_semantic/src/types/mro.rs
+++ b/crates/ty_python_semantic/src/types/mro.rs
@@ -8,7 +8,7 @@ use crate::Db;
 use crate::types::class_base::ClassBase;
 use crate::types::generics::Specialization;
 use crate::types::{
-    ClassLiteral, ClassType, DynamicClassLiteral, KnownClass, KnownInstanceType, SpecialFormType,
+    ClassLiteral, ClassType, DynamicClassLiteral, KnownInstanceType, SpecialFormType,
     StaticClassLiteral, Type,
 };
 
@@ -86,13 +86,6 @@ impl<'db> Mro<'db> {
         }
 
         let class = class_literal.apply_optional_specialization(db, specialization);
-
-        // Special-case `NotImplementedType`: typeshed says that it inherits from `Any`,
-        // but this causes more problems than it fixes.
-        if class_literal.is_known(db, KnownClass::NotImplementedType) {
-            return Ok(Self::from([ClassBase::Class(class), ClassBase::object(db)]));
-        }
-
         let original_bases = class_literal.explicit_bases(db);
 
         match original_bases {
```

**Review by AlexWaygood — COMMENTED** [review]
This looks very good, and I think it's close! My main comment on this pass is I think we could do with a bunch more tests

File: crates/ty_python_semantic/resources/mdtest/call/type.md (hunk 60 above)
Comment (charliermarsh) [reply crates/ty_python_semantic/resources/mdtest/call/type.md]: (Adding a TODO for now though happy to rebase on that if you want to merge it!)

File: crates/ty_python_semantic/src/types/class.rs [hunk 74]
```diff
@@ -400,6 +440,371 @@ impl<'db> VarianceInferable<'db> for GenericAlias<'db> {
...
+        self,
+        db: &'db dyn Db,
+        name: &str,
+        policy: MemberLookupPolicy,
+        mro_iter: impl Iterator<Item = ClassBase<'db>>,
+    ) -> PlaceAndQualifiers<'db> {
+        match self {
+            Self::Static(class) => class.class_member_from_mro(db, name, policy, mro_iter),
+            Self::Dynamic(_) => {
+                // Functional classes don't have inherited generic context and are never `object`.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
                // Dynamic classes don't have inherited generic context and are never `object`.
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 75]
```diff
@@ -400,6 +440,371 @@ impl<'db> VarianceInferable<'db> for GenericAlias<'db> {
...
+
+    /// Returns whether this is a known class.
+    pub(crate) fn is_known(self, db: &'db dyn Db, known: KnownClass) -> bool {
+        self.known(db) == Some(known)
+    }
+
+    /// Returns the default specialization for this class.
+    ///
+    /// For statement-based classes, this applies default type arguments.
+    /// For functional classes, this returns a non-generic class type.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
    /// For static classes, this applies default type arguments.
    /// For dynamic classes, this returns a non-generic class type.
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 76]
```diff
@@ -400,6 +440,371 @@ impl<'db> VarianceInferable<'db> for GenericAlias<'db> {
...
+        match self {
+            Self::Static(class) => class.identity_specialization(db),
+            Self::Dynamic(_) => ClassType::NonGeneric(self),
+        }
+    }
+
+    /// Returns the generic context if this is a generic class.
+    ///
+    // TODO: We should emit a diagnostic if a functional class (created via `type()`) attempts
+    // to inherit from `Generic[T]`, since functional classes can't be generic. See also: `is_protocol`.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
    // TODO: We should emit a diagnostic if a dynamic class (created via `type()`) attempts
    // to inherit from `Generic[T]`, since dynamic classes can't be generic. See also: `is_protocol`.
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 77]
```diff
@@ -400,6 +440,371 @@ impl<'db> VarianceInferable<'db> for GenericAlias<'db> {
...
+    pub(crate) fn generic_context(self, db: &'db dyn Db) -> Option<GenericContext<'db>> {
+        self.as_static().and_then(|class| class.generic_context(db))
+    }
+
+    /// Returns whether this class is a protocol.
+    ///
+    // TODO: We should emit a diagnostic if a functional class (created via `type()`) attempts
+    // to inherit from `Protocol`, since functional classes can't be protocols. See also: `generic_context`.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
    // TODO: We should emit a diagnostic if a dynamic class (created via `type()`) attempts
    // to inherit from `Protocol`, since dynamic classes can't be protocols. See also: `generic_context`.
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 78]
```diff
@@ -400,6 +440,371 @@ impl<'db> VarianceInferable<'db> for GenericAlias<'db> {
...
+    pub(crate) fn is_protocol(self, db: &'db dyn Db) -> bool {
+        self.as_static().is_some_and(|class| class.is_protocol(db))
+    }
+
+    /// Returns whether this class is a `TypedDict`.
+    // TODO: We should emit a diagnostic if a functional class (created via `type()`) attempts
+    // to inherit from `TypedDict`. To create a functional TypedDict, you should invoke
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
    // TODO: We should emit a diagnostic if a dynamic class (created via `type()`) attempts
    // to inherit from `TypedDict`. To create a functional TypedDict, you should invoke
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 79]
```diff
@@ -400,6 +440,371 @@ impl<'db> VarianceInferable<'db> for GenericAlias<'db> {
...
+        match self {
+            Self::Static(class) => class.file(db),
+            Self::Dynamic(class) => class.file(db),
+        }
+    }
+
+    /// Returns the range of the class's "header".
+    ///
+    /// For statement classes, this is the class name and any arguments passed to the `class` statement.
+    /// For functional classes, this is the entire `type()` call expression.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
    /// For static classes, this is the class name and any arguments passed to the `class` statement.
    /// For dynamic classes, this is the entire `type()` call expression.
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 80]
```diff
@@ -400,6 +440,371 @@ impl<'db> VarianceInferable<'db> for GenericAlias<'db> {
...
+    /// Returns the top materialization for this class.
+    pub(crate) fn top_materialization(self, db: &'db dyn Db) -> ClassType<'db> {
+        match self {
+            Self::Static(class) => class.top_materialization(db),
+            Self::Dynamic(_) => ClassType::NonGeneric(self),
+        }
+    }
+
+    /// Returns the `TypedDict` member lookup.
+    /// Functional classes cannot be `TypedDicts`, so this delegates to the Stmt variant.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
    /// Dynamic classes cannot be `TypedDicts`, so this delegates to the Stmt variant.
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 81]
```diff
@@ -400,6 +440,371 @@ impl<'db> VarianceInferable<'db> for GenericAlias<'db> {
...
+
+impl<'db> From<StaticClassLiteral<'db>> for ClassLiteral<'db> {
+    fn from(literal: StaticClassLiteral<'db>) -> Self {
+        ClassLiteral::Static(literal)
+    }
+}
+
+impl<'db> From<DynamicClassLiteral<'db>> for ClassLiteral<'db> {
+    fn from(functional: DynamicClassLiteral<'db>) -> Self {
+        ClassLiteral::Dynamic(functional)
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
    fn from(dynamic: DynamicClassLiteral<'db>) -> Self {
        ClassLiteral::Dynamic(dynamic)
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 82]
```diff
@@ -470,67 +875,82 @@ impl<'db> ClassType<'db> {
...
-        class_literal.definition(db)
+    /// Returns the definition for this class, if available.
+    pub(crate) fn definition(self, db: &'db dyn Db) -> Option<Definition<'db>> {
+        self.class_literal(db).definition(db)
+    }
+
+    /// Returns the type definition for this class.
+    ///
+    /// For statement-based classes, returns `TypeDefinition::StaticClass`.
+    /// For functional classes, returns `TypeDefinition::DynamicClass` if a definition is available.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
    /// For static classes, returns `TypeDefinition::StaticClass`.
    /// For dynamic classes, returns `TypeDefinition::DynamicClass` if a definition is available.
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 83]
```diff
@@ -1183,8 +1650,10 @@ impl<'db> ClassType<'db> {
         // consolidate the two? Can we invoke a class by upcasting the class into a Callable, and
         // then relying on the call binding machinery to Just Work™?
 
-        let (class_literal, _) = self.class_literal(db);
-        let class_generic_context = class_literal.generic_context(db);
+        // Functional classes don't have a generic context.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
        // Dynamic classes don't have a generic context.
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 84]
```diff
@@ -1386,6 +1860,24 @@ impl<'db> From<GenericAlias<'db>> for ClassType<'db> {
...
+
+impl<'db> From<StaticClassLiteral<'db>> for Type<'db> {
+    fn from(stmt: StaticClassLiteral<'db>) -> Type<'db> {
+        Type::ClassLiteral(stmt.into())
+    }
+}
+
+impl<'db> From<DynamicClassLiteral<'db>> for Type<'db> {
+    fn from(functional: DynamicClassLiteral<'db>) -> Type<'db> {
+        Type::ClassLiteral(functional.into())
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
    fn from(dynamic: DynamicClassLiteral<'db>) -> Type<'db> {
        Type::ClassLiteral(dynamic.into())
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 85]
```diff
@@ -2087,7 +2587,11 @@ impl<'db> ClassLiteral<'db> {
         let (metaclass, class_metaclass_was_from) = if let Some(metaclass) = explicit_metaclass {
             (metaclass, self)
         } else if let Some(base_class) = base_classes.next() {
-            let (base_class_literal, _) = base_class.class_literal(db);
+            // For functional classes, we can't get a StaticClassLiteral, so use self for tracking.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
            // For dynamic classes, we can't get a StaticClassLiteral, so use self for tracking.
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 86]
```diff
@@ -2138,8 +2642,12 @@ impl<'db> ClassLiteral<'db> {
             let Some(metaclass) = metaclass.to_class_type(db) else {
                 continue;
             };
+            // For functional classes, we can't get a StaticClassLiteral, so use self for tracking.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
            // For dynamic classes, we can't get a StaticClassLiteral, so use self for tracking.
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 87]
```diff
@@ -2162,11 +2669,12 @@ impl<'db> ClassLiteral<'db> {
             });
         }
 
-        let (metaclass_literal, _) = candidate.metaclass.class_literal(db);
-        Ok((
-            candidate.metaclass.into(),
-            metaclass_literal.dataclass_transformer_params(db),
-        ))
+        // Functional classes don't have dataclass transformer params.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
        // Dynamic classes don't have dataclass transformer params.
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 88]
```diff
@@ -3240,22 +3678,20 @@ impl<'db> ClassLiteral<'db> {
...
-            .iter_mro(db, specialization)
-            .filter_map(|superclass| {
-                if let Some(class) = superclass.into_class() {
-                    let (class_literal, specialization) = class.class_literal(db);
-                    if field_policy.matches(db, class_literal, specialization) {
+        let matching_classes_in_mro: Vec<(StaticClassLiteral<'db>, Option<Specialization<'db>>)> =
+            self.iter_mro(db, specialization)
+                .filter_map(|superclass| {
+                    let class = superclass.into_class()?;
+                    // Functional classes don't have fields (no class body).
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
                    // Dynamic classes don't have fields (no class body).
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 89]
```diff
@@ -4071,170 +4443,678 @@ impl<'db> ClassLiteral<'db> {
...
+/// Foo = type("Foo", (Base,), {"attr": 1})
+/// ```
+///
+/// The type of `Foo` would be `<class 'Foo'>` where `Foo` is a `DynamicClassLiteral` with:
+/// - name: "Foo"
+/// - bases: [Base]
+///
+/// This is called "functional" because it mirrors the terminology used for `NamedTuple`
+/// and `TypedDict`, where the "functional form" means creating via a function call
+/// rather than a class statement.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]: outdated

File: crates/ty_python_semantic/src/types/class.rs [hunk 90]
```diff
@@ -4071,170 +4443,678 @@ impl<'db> ClassLiteral<'db> {
...
+    }
+
+    /// Returns the range of the `type()` call expression that created this class.
+    pub(super) fn header_range(self, db: &'db dyn Db) -> TextRange {
+        let module = parsed_module(db, self.file(db)).load(db);
+        let node = module.get_by_index(self.node_index(db));
+        node.range()
+    }
+
+    /// Get the metaclass of this functional class.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
    /// Get the metaclass of this dynamic class.
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 91]
```diff
@@ -4071,170 +4443,678 @@ impl<'db> ClassLiteral<'db> {
...
+    /// Derives the metaclass from base classes: finds the most derived metaclass
+    /// that is a subclass of all other base metaclasses.
+    ///
+    /// See <https://docs.python.org/3/reference/datamodel.html#determining-the-appropriate-metaclass>
+    pub(crate) fn metaclass(self, db: &'db dyn Db) -> Type<'db> {
+        self.try_metaclass(db)
+            .unwrap_or_else(|_| SubclassOfType::subclass_of_unknown())
+    }
+
+    /// Try to get the metaclass of this functional class.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
    /// Try to get the metaclass of this dynamic class.
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 92]
```diff
@@ -4071,170 +4443,678 @@ impl<'db> ClassLiteral<'db> {
...
+                base2: *base,
+            });
+        }
+
+        Ok(candidate)
+    }
+
+    /// Iterate over the MRO of this functional class using C3 linearization.
+    ///
+    /// The MRO includes the functional class itself as the first element, followed
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
    /// Iterate over the MRO of this dynamic class using C3 linearization.
    ///
    /// The MRO includes the dynamic class itself as the first element, followed
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 93]
```diff
@@ -4071,170 +4443,678 @@ impl<'db> ClassLiteral<'db> {
...
+                    .instance_member(db, name)
+            }
+        }
+    }
+
+    /// Look up a class-level member by iterating through the MRO.
+    ///
+    /// Uses `MroLookup` with:
+    /// - No inherited generic context (functional classes aren't generic).
+    /// - `is_self_object = false` (functional classes are never `object`).
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
    /// - No inherited generic context (dynamic classes aren't generic).
    /// - `is_self_object = false` (dynamic classes are never `object`).
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 94]
```diff
@@ -4071,170 +4443,678 @@ impl<'db> ClassLiteral<'db> {
...
+                .with_qualifiers(TypeQualifiers::CLASS_VAR);
+            } else if name == "__dataclass_params__" {
+                // There is no typeshed class for this. For now, we model it as `Any`.
+                return Place::declared(Type::any()).with_qualifiers(TypeQualifiers::CLASS_VAR);
+            }
+        }
+
+        let result = MroLookup::new(db, self.iter_mro(db)).class_member(
+            name, policy, None,  // No inherited generic context.
+            false, // Functional classes are never `object`.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
            false, // Dynamic classes are never `object`.
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 95]
```diff
@@ -4071,170 +4443,678 @@ impl<'db> ClassLiteral<'db> {
...
+                // Simplified `TypedDict` handling without type mapping.
+                KnownClass::TypedDictFallback
+                    .to_class_literal(db)
+                    .find_name_in_mro_with_policy(db, name, policy)
+                    .expect("Will return Some() when called on class literal")
+            }
+        }
+    }
+
+    /// Try to compute the MRO for this functional class.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
    /// Try to compute the MRO for this dynamic class.
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 96]
```diff
@@ -4071,170 +4443,678 @@ impl<'db> ClassLiteral<'db> {
...
+    /// Uses C3 linearization when possible, falling back to sequential iteration
+    /// with deduplication when there's an error (duplicate bases or C3 merge failure).
+    #[salsa::tracked(heap_size = ruff_memory_usage::heap_size)]
+    pub(crate) fn mro(self, db: &'db dyn Db) -> Mro<'db> {
+        self.try_mro(db)
+            .unwrap_or_else(|_| Mro::functional_fallback(db, self))
+    }
+}
+
+/// Error for metaclass conflicts in functional classes.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]:
```suggestion
/// Error for metaclass conflicts in dynamic classes.
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 97]
```diff
@@ -4071,170 +4443,678 @@ impl<'db> ClassLiteral<'db> {
...
+///
+/// This mirrors `MetaclassErrorKind::Conflict` for regular classes.
+#[derive(Debug, Clone)]
+pub(crate) struct FunctionalMetaclassConflict<'db> {
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]: Should be renamed to `DynamicMetaclassConflict`

File: crates/ty_python_semantic/src/types/class_base.rs [hunk 98]
```diff
@@ -359,7 +372,13 @@ impl<'db> ClassBase<'db> {
     pub(super) fn has_cyclic_mro(self, db: &'db dyn Db) -> bool {
         match self {
             ClassBase::Class(class) => {
-                let (class_literal, specialization) = class.class_literal(db);
+                let Some((class_literal, specialization)) = class.static_class_literal(db) else {
+                    // Functional classes can't have cyclic MRO since their bases must
+                    // already exist at creation time. Unlike statement classes, we do not
+                    // permit functional classes to have forward references in their
+                    // bases list.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class_base.rs]:
```suggestion
                    // Dynamic classes can't have cyclic MRO since their bases must
                    // already exist at creation time. Unlike statement classes, we do not
                    // permit dynamic classes to have forward references in their
                    // bases list.
```

File: crates/ty_python_semantic/src/types/mro.rs [hunk 99]
```diff
@@ -299,15 +293,119 @@ impl<'db> Mro<'db> {
...
+
+    pub(super) fn from_error(db: &'db dyn Db, class: ClassType<'db>) -> Self {
+        Self::from([
+            ClassBase::Class(class),
+            ClassBase::unknown(),
+            ClassBase::object(db),
+        ])
+    }
+
+    /// Attempt to resolve the MRO of a functional class (created via `type(name, bases, dict)`).
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/mro.rs]:
```suggestion
    /// Attempt to resolve the MRO of a dynamic class (created via `type(name, bases, dict)`).
```

File: crates/ty_python_semantic/src/types/mro.rs [hunk 100]
```diff
@@ -299,15 +293,119 @@ impl<'db> Mro<'db> {
...
+    ///
+    /// Uses C3 linearization when possible, returning an error if the MRO cannot be resolved.
+    pub(super) fn of_dynamic_class(
+        db: &'db dyn Db,
+        functional: DynamicClassLiteral<'db>,
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/mro.rs]: parameter should be renamed

File: crates/ty_python_semantic/src/types/mro.rs [hunk 101]
```diff
@@ -299,15 +293,119 @@ impl<'db> Mro<'db> {
...
+                if has_dynamic_bases {
+                    Ok(Self::functional_fallback(db, functional))
+                } else {
+                    Err(FunctionalMroError::UnresolvableMro)
+                }
+            }
+        }
+    }
+
+    /// Compute a fallback MRO for a functional class when `of_dynamic_class` fails.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/mro.rs]:
```suggestion
    /// Compute a fallback MRO for a dynamic class when `of_dynamic_class` fails.
```

File: crates/ty_python_semantic/src/types/mro.rs [hunk 102]
```diff
@@ -299,15 +293,119 @@ impl<'db> Mro<'db> {
...
+    ///
+    /// Iterates over base MROs sequentially with deduplication.
+    pub(super) fn functional_fallback(
+        db: &'db dyn Db,
+        functional: DynamicClassLiteral<'db>,
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/mro.rs]: parameter should be renamed

**Comment by charliermarsh** [comment]
(Back to draft while I address feedback.)

File: crates/ty_python_semantic/src/types/mro.rs [hunk 103]
```diff
@@ -390,19 +512,36 @@ impl<'db> MroIterator<'db> {
         }
     }
 
+    fn first_element(&self) -> ClassBase<'db> {
+        match self.class {
+            ClassLiteral::Static(literal) => ClassBase::Class(
+                literal.apply_optional_specialization(self.db, self.specialization),
+            ),
+            ClassLiteral::Dynamic(functional) => {
+                ClassBase::Class(ClassType::NonGeneric(functional.into()))
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/mro.rs]:
```suggestion
            ClassLiteral::Dynamic(dynamic) => {
                ClassBase::Class(ClassType::NonGeneric(dynamic.into()))
```

File: crates/ty_python_semantic/src/types/mro.rs [hunk 104]
```diff
@@ -544,3 +680,15 @@ fn c3_merge(mut sequences: Vec<VecDeque<ClassBase>>) -> Option<Mro> {
         }
     }
 }
+
+/// Error kinds for functional class MRO computation.
+///
+/// These mirror the relevant variants from `MroErrorKind` for regular classes.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/mro.rs]:
```suggestion
/// Error kinds for dynamic class MRO computation.
///
/// These mirror the relevant variants from `MroErrorKind` for static classes.
```

**Comment by AlexWaygood** [comment]
I think you're using `SubsequentMroElements::Owned()` more than you need to -- you could do this:

```diff
diff --git a/crates/ty_python_semantic/src/types/class.rs b/crates/ty_python_semantic/src/types/class.rs
index 2ac60dce6c..00ca535dc3 100644
--- a/crates/ty_python_semantic/src/types/class.rs
+++ b/crates/ty_python_semantic/src/types/class.rs
@@ -4848,19 +4848,10 @@ impl<'db> DynamicClassLiteral<'db> {
     ///
     /// Returns `Ok(Mro)` if successful, or `Err(FunctionalMroError)` if there's
     /// an error (duplicate bases or C3 linearization failure).
+    #[salsa::tracked(returns(ref), heap_size=ruff_memory_usage::heap_size)]
     pub(crate) fn try_mro(self, db: &'db dyn Db) -> Result<Mro<'db>, FunctionalMroError<'db>> {
         Mro::of_dynamic_class(db, self)
     }
-
-    /// Compute and cache the MRO for this functional class.
-    ///
-    /// Uses C3 linearization when possible, falling back to sequential iteration
-    /// with deduplication when there's an error (duplicate bases or C3 merge failure).
-    #[salsa::tracked(heap_size = ruff_memory_usage::heap_size)]
-    pub(crate) fn mro(self, db: &'db dyn Db) -> Mro<'db> {
-        self.try_mro(db)
-            .unwrap_or_else(|_| Mro::functional_fallback(db, self))
-    }
 }
 
 /// Error for metaclass conflicts in functional classes.
diff --git a/crates/ty_python_semantic/src/types/mro.rs b/crates/ty_python_semantic/src/types/mro.rs
index 9677b27603..9bb923b40a 100644
--- a/crates/ty_python_semantic/src/types/mro.rs
+++ b/crates/ty_python_semantic/src/types/mro.rs
@@ -435,6 +435,15 @@ impl<'db> FromIterator<ClassBase<'db>> for Mro<'db> {
     }
 }
 
+impl<'db> IntoIterator for Mro<'db> {
+    type Item = ClassBase<'db>;
+    type IntoIter = std::vec::IntoIter<ClassBase<'db>>;
+
+    fn into_iter(self) -> Self::IntoIter {
+        self.0.into_iter()
+    }
+}
+
 /// Iterator that yields elements of a class's MRO.
 ///
 /// We avoid materialising the *full* MRO unless it is actually necessary:
@@ -537,9 +546,14 @@ impl<'db> MroIterator<'db> {
                     SubsequentMroElements::Borrowed(full_mro_iter)
                 }
                 ClassLiteral::Dynamic(functional) => {
-                    let mro = functional.mro(self.db);
-                    let elements: Vec<_> = mro.iter().skip(1).copied().collect();
-                    SubsequentMroElements::Owned(elements.into_iter())
+                    let mut full_mro_iter = match functional.try_mro(self.db) {
+                        Ok(mro) => SubsequentMroElements::Borrowed(mro.iter()),
+                        Err(_) => SubsequentMroElements::Owned(
+                            Mro::functional_fallback(self.db, functional).into_iter(),
+                        ),
+                    };
+                    full_mro_iter.next();
+                    full_mro_iter
                 }
             })
     }
@@ -684,7 +698,7 @@ fn c3_merge(mut sequences: Vec<VecDeque<ClassBase>>) -> Option<Mro> {
 /// Error kinds for functional class MRO computation.
 ///
 /// These mirror the relevant variants from `MroErrorKind` for regular classes.
-#[derive(Debug, Clone)]
+#[derive(Debug, Clone, PartialEq, Eq, get_size2::GetSize, salsa::Update)]
 pub(crate) enum FunctionalMroError<'db> {
     /// The class has duplicate bases in its bases tuple.
     DuplicateBases(Box<[ClassBase<'db>]>),
```

But I'm a bit confused about why `Mro::functional_fallback` is as complex as it is, and why the fallback isn't stored on the error returned `DynamicClassLiteral::try_mro`. If we computed and stored the fallback MRO in a way more similar to what we do for static classes, we might not need the `SubsequentMroElements` enum at all.

File: crates/ty_python_semantic/src/types/infer/builder.rs (hunk 72 above)
Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/infer/builder.rs]: Added some shared helpers...

**Comment by charliermarsh** [comment]
Yeah you're right. I think the functional MRO went through several iterations and I must've solved whatever required the enum along the way. Thanks!

File: crates/ty_python_semantic/src/types/infer/builder.rs [hunk 105]
```diff
@@ -5399,6 +5408,31 @@ impl<'db, 'ast> TypeInferenceBuilder<'db, 'ast> {
...
+                                && call_expr.arguments.keywords.is_empty() =>
+                        {
+                            // Try to extract the functional class with definition.
+                            // Fall back to regular call binding if extraction fails
+                            // (e.g., for cyclic references where names aren't resolved yet).
+                            self.infer_functional_type_expression(call_expr, definition)
+                                .unwrap_or_else(|| {
+                                    // Use Overwrite mode because infer_functional_type_expression
+                                    // may have already stored expression types for the arguments
+                                    // before returning None.
```
Comment (charliermarsh) [inline crates/ty_python_semantic/src/types/infer/builder.rs]: This seems wrong, looking into it.

File: crates/ty_python_semantic/src/types/infer/builder.rs [hunk 106]
```diff
@@ -6002,6 +6036,263 @@ impl<'db, 'ast> TypeInferenceBuilder<'db, 'ast> {
...
+    /// Extract the class name from the first argument of a `type()` call.
+    ///
+    /// Returns `Some(Name)` if the name is valid (string literal or assignable to str),
+    /// `None` if it should fall through to regular call binding for error reporting.
+    fn extract_functional_type_name(&self, name_type: Type<'db>) -> Option<ast::name::Name> {
+        let db = self.db();
+        if let Some(literal) = name_type.as_string_literal() {
+            Some(ast::name::Name::new(literal.value(db)))
+        } else if name_type.is_assignable_to(db, KnownClass::Str.to_instance(db)) {
+            Some(ast::name::Name::new("<unknown>"))
```
Comment (charliermarsh) [inline crates/ty_python_semantic/src/types/infer/builder.rs]: (I suspect this is _not_ what you had in mind @AlexWaygood.)

File: crates/ty_python_semantic/src/types/infer/builder.rs (hunk 105 above)
Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/infer/builder.rs]: Still not sure I have the ideal approach here.

File: crates/ty_python_semantic/resources/mdtest/call/type.md [hunk 107]
```diff
@@ -0,0 +1,763 @@
...
+### Protocol bases
+
+```py
+# Protocol bases work - the class is created as a subclass of the protocol
+from typing import Protocol
+
+class MyProtocol(Protocol):
+    def method(self) -> int: ...
+
+ProtoImpl = type("ProtoImpl", (MyProtocol,), {})
```
Comment (charliermarsh) [inline crates/ty_python_semantic/resources/mdtest/call/type.md:690]: I think we said we wanted to ban this as a known simplification @AlexWaygood -- is that right?

Comment (charliermarsh) [reply crates/ty_python_semantic/resources/mdtest/call/type.md:690]: Ah no -- it was inheriting from `Protocol` itself.

Comment (AlexWaygood) [reply crates/ty_python_semantic/resources/mdtest/call/type.md:690]: yeah, inheriting from protocol classes is fine, it just doesn't seem necessary to support creating a _new_ `Protocol` class using `type()` (which you'd do by including `Protocol` itself in the bases list)

File: crates/ty_python_semantic/resources/mdtest/call/type.md [hunk 108]
```diff
@@ -0,0 +1,752 @@
...
+
+Foo = type("Foo", (Base,), {})
+Bar = type("Bar", (Base,), {})
+
+static_assert(not is_disjoint_from(type[Foo], type[Bar]))
+```
+
+## Using dynamic classes with `super()`
+
+Dynamic classes can be used as pivot in `super()`:
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/call/type.md]:
```suggestion
Dynamic classes can be used as the pivot class in `super()` calls:
```

File: crates/ty_python_semantic/resources/mdtest/call/type.md [hunk 109]
```diff
@@ -0,0 +1,752 @@
...
+# Create a dynamic class that inherits from another dynamic class.
+ChildCls = type("ChildCls", (Parent,), {})
+reveal_type(ChildCls)  # revealed: <class 'ChildCls'>
+
+# Child instances have access to attributes from the entire inheritance chain.
+child = ChildCls()
+reveal_type(child)  # revealed: ChildCls
+reveal_type(child.base_attr)  # revealed: int
+
+# Child instances are subtypes of Parent instances.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/call/type.md]:
```suggestion
# Child instances are subtypes of `Parent` instances.
```

File: crates/ty_python_semantic/resources/mdtest/call/type.md [hunk 110]
```diff
@@ -0,0 +1,752 @@
...
+def takes_parent(x: Parent) -> None: ...
+
+takes_parent(child)  # No error - ChildCls is a subtype of Parent
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/call/type.md]:
```suggestion
takes_parent(child)  # No error - `ChildCls` is a subtype of `Parent`
```

File: crates/ty_python_semantic/resources/mdtest/call/type.md [hunk 111]
```diff
@@ -0,0 +1,752 @@
...
+reveal_type(T.__mro__)  # revealed: tuple[type, ...]
+```
+
+## Invalid calls
+
+Other numbers of arguments are invalid:
+
+```py
+# error: [no-matching-overload] "No overload of class `type` matches arguments"
+type("Foo", ())
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/call/type.md]:
```suggestion
reveal_type(type("Foo", ()))  # revealed: Unknown
```

File: crates/ty_python_semantic/resources/mdtest/call/type.md [hunk 112]
```diff
@@ -0,0 +1,752 @@
...
+
+# TODO: keyword arguments should be supported for `__init_subclass__` calls
+# error: [no-matching-overload] "No overload of class `type` matches arguments"
+type("Foo", (), {}, weird_other_arg=42)
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/call/type.md]:
```suggestion
# TODO: the keyword arguments for `Foo`/`Bar`/`Baz` here are invalid
# (you cannot pass `metaclass=` to `type()`, and none of them have
# base classes with `__init_subclass__` methods),
# but `type[Unknown]` would be better than `Unknown` here
#
# error: [no-matching-overload] "No overload of class `type` matches arguments"
reveal_type(type("Foo", (), {}, weird_other_arg=42))  # revealed: Unknown
# error: [no-matching-overload] "No overload of class `type` matches arguments"
reveal_type(type("Bar", (int,), {}, weird_other_arg=42))  # revealed: Unknown
# error: [no-matching-overload] "No overload of class `type` matches arguments"
reveal_type(type("Baz", (), {}, metaclass=type))  # revealed: Unknown
```

File: crates/ty_python_semantic/resources/mdtest/call/type.md [hunk 113]
```diff
@@ -0,0 +1,752 @@
...
+type("Foo", Base, {})
+
+# error: [invalid-argument-type] "Argument to class `type` is incorrect: Expected `tuple[type, ...]`, found `tuple[Literal[1], Literal[2]]`"
+type("Foo", (1, 2), {})
+
+# error: [invalid-argument-type] "Argument to class `type` is incorrect: Expected `dict[str, Any]`, found `dict[str | bytes, Any]`"
+type("Foo", (Base,), {b"attr": 1})
+```
+
+## `type[...]` as base class
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/call/type.md:439]: I still think this should cause us to emit a diagnostic. However, having seen the ecosystem report, I think perhaps it should be a different error code to `unsupported-base` (maybe `unsupported-dynamic-base`?). It seems fairly common for users to create dynamic classes with `type[]` types as a base class, and the whole point of dynamic classes is after all that you can create them... dynamically. Making it a different error code to the one we use for unsupported bases in static class definitions will allow users to switch off only the diagnostic regarding dynamic classes, if they find it really noisy. (And maybe we should actually have it disabled by default, since it's quite strict.)

File: crates/ty_python_semantic/resources/mdtest/call/type.md [hunk 114]
```diff
@@ -0,0 +1,752 @@
...
+
+Self-referential class definitions using `type()` are detected. The name being defined is referenced
+in the bases tuple before it's available:
+
+```pyi
+# error: [unresolved-reference] "Name `X` used when not defined"
+X = type("X", (X,), {})
+```
+
+## Dynamic class names (non-literal strings)
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/call/type.md:526]: It might be fun to add this test too:

```py
def make_classes(name1: str, name2: str):
    cls1 = type(name1, (), {})
    cls2 = type(name2, (), {})

    def inner(x: cls1): ...

    # error: [invalid-argument-type] "Argument to function `inner` is incorrect: Expected `main.<locals of function 'make_classes'>.<unknown> @ main.py:2`, found `main.<locals of function 'make_classes'>.<unknown> @ main.py:3`"
    inner(cls2())
```

File: crates/ty_python_semantic/resources/mdtest/call/type.md [hunk 115]
```diff
@@ -0,0 +1,752 @@
...
+    # Instances have dynamic attribute access due to Unknown base
+    instance = cls()
+    reveal_type(instance)  # revealed: Cls
+    reveal_type(instance.any_attr)  # revealed: Unknown
+    reveal_type(instance.any_method())  # revealed: Unknown
+
+    return cls
+```
+
+When bases is a module-level variable holding a tuple of class literals, we can extract the base
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/call/type.md]:
```suggestion
When `bases` is a module-level variable holding a tuple of class literals, we can extract the base
```

File: crates/ty_python_semantic/resources/mdtest/call/type.md [hunk 116]
```diff
@@ -0,0 +1,752 @@
...
+
+Point3D = type("Point3D", (Point,), {})
+reveal_type(Point3D)  # revealed: <class 'Point3D'>
+```
+
+### Enum bases
+
+```py
+# Enum subclassing via type() is not supported - EnumMeta requires special dict handling
+# that type() cannot provide. This applies even to empty enums.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/call/type.md:736]: It seems like it is _possible_ to create an empty enum using `type()` if you try realy really hard. But yeah, we don't need to support this 😆

```pycon
>>> import enum as e
>>> type("E", (e.Enum,), e.EnumDict())
<enum 'E'>
```

File: crates/ty_python_semantic/resources/mdtest/call/type.md [hunk 117]
```diff
@@ -0,0 +1,752 @@
...
+## `__init_subclass__` keyword arguments
+
+When a base class defines `__init_subclass__` with required keyword arguments, those should be
+passed to `type()`. This is not yet supported:
+
+```py
+class Base:
+    def __init_subclass__(cls, *, required_arg: str, **kwargs):
+        super().__init_subclass__(**kwargs)
+        cls.config = required_arg
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/call/type.md]: It doesn't need to be a keyword argument. Even if it's a positional-or-keyword argument in the `__init_subclass__` signature, that makes it a required keyword argument when subclassing that class (because there's no other way to pass arguments to a superclass's `__init_subclass__` method except by passing keyword arguments in the class statement or a dynamic `type()` call).

```suggestion
When a base class defines `__init_subclass__` with required arguments, those should be
passed to `type()`. This is not yet supported:

```py
class Base:
    def __init_subclass__(cls, required_arg: str, **kwargs):
        super().__init_subclass__(**kwargs)
        cls.config = required_arg
```

File: crates/ty_python_semantic/resources/mdtest/dataclasses/dataclasses.md
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/dataclasses/dataclasses.md:1]: If you do it as

```py
from dataclasses import dataclass

X = dataclass(type("X", (), {}))
```

do we store a `Definition` for the `X` class there? I think it's okay if we don't (this should come up very rarely), I'm just curious

I guess ideally we'd add some dedicated tests for goto-definition in https://github.com/astral-sh/ruff/blob/main/crates/ty_ide/src/goto_type_definition.rs, which would include edge cases like this, but it's fine for that to be a followup. I realise that this PR is dragging on a bit!

File: crates/ty_python_semantic/resources/mdtest/ide_support/all_members.md [hunk 118]
```diff
@@ -870,6 +870,102 @@ static_assert(not has_member(F, "__match_args__"))
...
+Attributes from the namespace dict (third argument) are not tracked:
+
+```py
+from ty_extensions import has_member, static_assert
+
+DynamicWithDict = type("DynamicWithDict", (), {"custom_attr": 42})
+
+# Namespace dict attributes are not available for autocomplete
+static_assert(not has_member(DynamicWithDict, "custom_attr"))
+static_assert(not has_member(DynamicWithDict(), "custom_attr"))
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/ide_support/all_members.md]:
```suggestion
# TODO: these should pass -- namespace dict attributes are not yet available for autocomplete
static_assert(has_member(DynamicWithDict, "custom_attr"))  # error: [static-assert-error]
static_assert(has_member(DynamicWithDict(), "custom_attr"))  # error: [static-assert-error]
```

File: crates/ty_python_semantic/resources/mdtest/ide_support/all_members.md [hunk 119]
```diff
@@ -870,6 +870,102 @@ static_assert(not has_member(F, "__match_args__"))
...
+class Base:
+    base_attr: int = 1
+
+DynamicSingle = type("DynamicSingle", (Base,), {})
+instance = DynamicSingle()
+
+# TODO: Instance members should be available but currently are not
+static_assert(not has_member(instance, "base_attr"))
+static_assert(not has_member(instance, "__repr__"))
+static_assert(not has_member(instance, "__hash__"))
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/ide_support/all_members.md]:
```suggestion
# TODO: these should pass; instance members should be available
static_assert(has_member(instance, "base_attr"))  # error: [static-assert-error]
static_assert(has_member(instance, "__repr__"))  # error: [static-assert-error]
static_assert(has_member(instance, "__hash__"))  # error: [static-assert-error]
```

File: crates/ty_python_semantic/resources/mdtest/call/type.md [hunk 120]
```diff
@@ -0,0 +1,752 @@
...
+
+bases = (Base,)
+Cls = type("Cls", bases, {})
+reveal_type(Cls)  # revealed: <class 'Cls'>
+
+instance = Cls()
+reveal_type(instance.attr)  # revealed: int
+```
+
+## Variadic arguments
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/call/type.md:603]: I would also be interested in some tests where the `*args` and/or `**kwargs` arguments "fill up" an unknown number of parameters in the `type()` call, e.g.

```py
def f(*args, **kwargs):
    A = type(*args, **kwargs)
    reveal_type(A)

    B = type("B", *args, **kwargs)
    reveal_type(B)

    C = type("C", (), *args, **kwargs)
    reveal_type(C)

    D = type("D", (), {}, **kwargs)
    reveal_type(D)
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 121]
```diff
@@ -400,6 +444,372 @@ impl<'db> VarianceInferable<'db> for GenericAlias<'db> {
...
+        }
+    }
+
+    /// Returns the metaclass instance type for this class.
+    pub(crate) fn metaclass_instance_type(self, db: &'db dyn Db) -> Type<'db> {
+        match self {
+            Self::Static(class) => class.metaclass_instance_type(db),
+            Self::Dynamic(class) => class.metaclass(db),
+        }
+    }
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs]: this doesn't look correct -- I think we should do something like this here:

```diff
diff --git a/crates/ty_python_semantic/src/types/class.rs b/crates/ty_python_semantic/src/types/class.rs
index 3ab1659f9e..48c4049704 100644
--- a/crates/ty_python_semantic/src/types/class.rs
+++ b/crates/ty_python_semantic/src/types/class.rs
@@ -596,12 +596,11 @@ impl<'db> ClassLiteral<'db> {
         }
     }
 
-    /// Returns the metaclass instance type for this class.
+    /// Return a type representing "the set of all instances of the metaclass of this class".
     pub(crate) fn metaclass_instance_type(self, db: &'db dyn Db) -> Type<'db> {
-        match self {
-            Self::Static(class) => class.metaclass_instance_type(db),
-            Self::Dynamic(class) => class.metaclass(db),
-        }
+        self.metaclass(db)
+            .to_instance(db)
+            .expect("`Type::to_instance()` should always return `Some()` when called on the type of a metaclass")
     }
 
     /// Returns whether this class is type-check only.
@@ -2585,14 +2584,6 @@ impl<'db> StaticClassLiteral<'db> {
             .unwrap_or_else(|_| SubclassOfType::subclass_of_unknown())
     }
 
-    /// Return a type representing "the set of all instances of the metaclass of this class".
-    pub(super) fn metaclass_instance_type(self, db: &'db dyn Db) -> Type<'db> {
-        self
-            .metaclass(db)
-            .to_instance(db)
-            .expect("`Type::to_instance()` should always return `Some()` when called on the type of a metaclass")
-    }
-
     /// Return the metaclass of this class, or an error if the metaclass cannot be inferred.
     #[salsa::tracked(cycle_initial=try_metaclass_cycle_initial,
         heap_size=ruff_memory_usage::heap_size,
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 122]
```diff
@@ -400,6 +444,372 @@ impl<'db> VarianceInferable<'db> for GenericAlias<'db> {
...
+        match self {
+            Self::Static(class) => class.header_range(db),
+            Self::Dynamic(class) => class.header_range(db),
+        }
+    }
+
+    /// Returns the deprecated info if this class is deprecated.
+    pub(crate) fn deprecated(self, db: &'db dyn Db) -> Option<DeprecatedInstance<'db>> {
+        self.as_static().and_then(|class| class.deprecated(db))
+    }
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs:634]: It's fine not to support dynamic classes being marked as deprecated, but in that case we should probably emit a diagnostic if somebody tries to do something like

```py
from warnings import deprecated

X = deprecated(type("X", (), {}))
```

File: crates/ty_python_semantic/src/types/class.rs [hunk 123]
```diff
@@ -400,6 +444,372 @@ impl<'db> VarianceInferable<'db> for GenericAlias<'db> {
...
+
+    /// Returns whether this class is final.
+    pub(crate) fn is_final(self, db: &'db dyn Db) -> bool {
+        self.as_static().is_some_and(|class| class.is_final(db))
+    }
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/class.rs:641]: same here, I guess ideally we'd emit a diagnostic for this if we don't want to support it

```py
from typing import final

X = final(type("X", (), {}))
```

File: crates/ty_python_semantic/resources/mdtest/call/type.md
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/call/type.md:1]: We should also emit a diagnostic (but don't currently on this branch) if you try to use an `@final` class as the base class for a dynamic class, e.g.

```py
from typing import final

@final
class Base: ...

type("X", (Base,), {})
```

This is maybe a counter-argument to https://github.com/astral-sh/ruff/pull/22291/files#r2678657516 -- if we looped through all dynamic class definitions in `TypeInferenceBuilder::check_class_definitions` as well as all the static class definitions, it might have been harder to forget to implement this check... but I'm guess there's a lot of stuff in that method that currently assumes that we have a `StmtClassDef` AST node, so it may be that what you have right now is the best design.

File: crates/ty_python_semantic/src/types/function.rs [hunk 124]
```diff
@@ -1739,7 +1737,9 @@ impl KnownFunction {
                 if class.is_protocol(db) {
                     return;
                 }
-                report_bad_argument_to_get_protocol_members(context, call_expression, *class);
+                if let Some(class) = class.as_static() {
+                    report_bad_argument_to_get_protocol_members(context, call_expression, class);
+                }
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/function.rs]: It seems like we should also emit a diagnostic for

```py
from ty_extensions import get_protocol_members

get_protocol_members(type("X", (), {}))
```

?

But this isn't high-priority, since `get_protocol_members` is mostly an internal debugging tool

**Comment by AlexWaygood** [comment]
@charliermarsh -- I pushed a commit fixing up and simplifying some of the `type()` expression parsing in `infer/builder.rs`, hope that's okay!

File: crates/ty_python_semantic/src/types/mro.rs [hunk 125]
```diff
@@ -544,3 +657,47 @@ fn c3_merge(mut sequences: Vec<VecDeque<ClassBase>>) -> Option<Mro> {
         }
     }
 }
+
+/// Error for dynamic class MRO computation with fallback MRO.
+#[derive(Debug, Clone, PartialEq, Eq, get_size2::GetSize, salsa::Update)]
+pub(crate) struct DynamicMroError<'db> {
+    kind: DynamicMroErrorKind<'db>,
+    fallback_mro: Mro<'db>,
+}
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/mro.rs:668]: Is the reason why this is a separate struct to `MroError` is because the kinds of errors that could occur for dynamic class definitions is only a subset of the kinds of errors that could occur for static class definitions? If so, maybe it's worth saying that in the struct doc-comment?

File: crates/ty_python_semantic/src/types/mro.rs [hunk 126]
```diff
@@ -544,3 +657,47 @@ fn c3_merge(mut sequences: Vec<VecDeque<ClassBase>>) -> Option<Mro> {
...
+
+    /// Return the fallback MRO to use for type inference.
+    pub(crate) fn fallback_mro(&self) -> &Mro<'db> {
+        &self.fallback_mro
+    }
+}
+
+/// Error kinds for dynamic class MRO computation.
+///
+/// These mirror the relevant variants from `MroErrorKind` for regular classes.
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/mro.rs]:
```suggestion
/// These mirror the relevant variants from `MroErrorKind` for static classes.
```

**Comment by AlexWaygood** [comment]
From my perspective, I think this is basically ready to go now! My remaining concerns are https://github.com/astral-sh/ruff/pull/22291#discussion_r2677500504 (which I'd like @MichaReiser's or @carljm's opinion on) and https://github.com/astral-sh/ruff/pull/22291#discussion_r2679453580.

File: crates/ty_python_semantic/resources/mdtest/call/type.md
Comment (charliermarsh) [reply crates/ty_python_semantic/resources/mdtest/call/type.md:1]: I believe I did this in https://github.com/astral-sh/ruff/pull/22499. I can revisit the approach in that review (RE whether it's worth using check_class_definitions), if that works?

Comment (AlexWaygood) [reply crates/ty_python_semantic/resources/mdtest/call/type.md:1]: yeah sure!

File: crates/ty_python_semantic/resources/mdtest/call/type.md [hunk 127]
```diff
@@ -0,0 +1,792 @@
...
+    B = type("B", *args, **kwargs)
+    reveal_type(B)  # revealed: <class 'str'>
+
+    # Has string and tuple, but unknown additional args
+    C = type("C", (), *args, **kwargs)
+    reveal_type(C)  # revealed: type
+
+    # All three positional args provided, only **kwargs unknown
+    D = type("D", (), {}, **kwargs)
+    reveal_type(D)  # revealed: type
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/call/type.md:646]:
```suggestion
    # TODO: `type[Unknown]` would cause fewer false positives
    reveal_type(B)  # revealed: <class 'str'>

    # Has string and tuple, but unknown additional args
    C = type("C", (), *args, **kwargs)
    # TODO: `type[Unknown]` would cause fewer false positives
    reveal_type(C)  # revealed: type

    # All three positional args provided, only **kwargs unknown
    D = type("D", (), {}, **kwargs)
    # TODO: `type[Unknown]` would cause fewer false positives
    reveal_type(D)  # revealed: type
```

File: crates/ty_python_semantic/resources/mdtest/call/type.md [hunk 128]
```diff
@@ -0,0 +1,794 @@
...
+
+```py
+def f(*args, **kwargs):
+    # Completely dynamic: could be 1-arg or 3-arg form
+    A = type(*args, **kwargs)
+    reveal_type(A)  # revealed: type[Unknown]
+
+    # Has a string first arg, but unknown additional args from *args
+    B = type("B", *args, **kwargs)
+    reveal_type(B)  # revealed: <class 'str'>
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/call/type.md:636]: I think here as well, `type[Unknown]` would cause fewer false positives (so I'd add a TODO here) -- it's ambiguous here whether we should pick the first overload (which would lead to us inferring `<class 'str'>` or the second overload (which would lead to us inferring a dynamic class-literal type). But either `<class 'str'>` or a dynamic class-literal type are both assignable to `type[Unknown]`, and it's a forgiving type that allows you to access most attributes on it.

Comment (charliermarsh) [reply crates/ty_python_semantic/resources/mdtest/call/type.md:636]: (Adding TODOs, going to tackle these in a separate PR.)

File: crates/ty_python_semantic/src/types/class.rs (hunk 50 above)
Comment (MichaReiser) [reply crates/ty_python_semantic/src/types/class.rs]: Including `NodeIndex` here is inherently problematic for incrementality. The `NodeIndex` changes if any new node is inserted before the class definition, which results in a new interned `StaticClassLiteral`. The result of this is that any cached data on the `StaticClassLiteral`s identity goes out the window when someone make changes above the `type` call expression (even in entirely unrelated scopes). So this is roughly as bad as holding on to the AST node itself (from an incrementality perspective).


The way we normally avoid this is by holding on to the `Definition` which gives access to the AST node (but in a way that doesn't affect the ID of `Definition`). 

What do we use this information for? Could we compute it using `definition` instead?

Alex is also right that we should avoid reading this field in cross-module queries, but, unfortunately, the problem is even more severe.

Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/class.rs]: We can't really use `Definition` here, since these can be created without a `Definition` -- they don't always bind to a name. For example:

```python
class Url(
    typing.NamedTuple(
        "Url",
        [
            ("scheme", typing.Optional[str]),
            ("auth", typing.Optional[str]),
            ("host", typing.Optional[str]),
            ("port", typing.Optional[int]),
            ("path", typing.Optional[str]),
            ("query", typing.Optional[str]),
            ("fragment", typing.Optional[str]),
        ],
    )
):
    ...
```

The dynamically-created `typing.NamedTuple` doesn't have a definition.

Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/class.rs]: These are, admittedly, rare though -- in case that affects how we'd think about the performance impact.

File: crates/ty_python_semantic/resources/mdtest/call/type.md (hunk 113 above)
Comment (charliermarsh) [reply crates/ty_python_semantic/resources/mdtest/call/type.md:439]: (I added this! It's a separate diagnostic, disabled by default.)

File: crates/ty_python_semantic/src/types/class.rs (hunk 50 above)
Comment (MichaReiser) [reply crates/ty_python_semantic/src/types/class.rs]: I'll try to have a look tomorrow. What do we use it for? Is it for diagnostics?

We could also consider to create `Definition`s for those always but I assume the problem is that we don't know the `NamedTuple` until it is too late. 

I've to look at where we intern this dynamic types. An alternative would be to use a tracked struct over an interned struct because tracked struct's allow you to exclude a field from its identity. However, their identity is also defined differently. It is based on value equality and by which query created the tracked struct. That means, two `NamedTuple` with exact the same values but from different call sites would resolve to different salsa ids. I don't know if that's a problem.

Although I'm slightly scared that they're broken in fixpoint iteration.

Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/class.rs]: Let me see if I could store an enum with `Expression` here instead for those use-cases?

File: crates/ty_python_semantic/src/types/diagnostic.rs [hunk 129]
```diff
@@ -841,6 +842,32 @@ declare_lint! {
     }
 }
 
+declare_lint! {
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/diagnostic.rs:845]: You need to add the new error code to https://github.com/astral-sh/ruff/blob/e4ba29392bb768965ba16ba86aba7d482e4f2ea8/.github/mypy-primer-ty.toml#L4-L8 or it'll be disabled by default in mypy_primer/ecosystem-analyzer runs.

Also, could we state clearly in the docs why it's disabled by default? (Because it won't fail at runtime, and may be noisy on codebases that are using `type()` in highly dynamic ways.)

You also need to run `cargo dev generate-all` to regenerate `ty.schema.json` and the generated docs files.

File: crates/ty_python_semantic/src/types/class.rs (hunk 50 above)
Comment (AlexWaygood) [reply crates/ty_python_semantic/src/types/class.rs]: > We could also consider to create `Definition`s for those always but I assume the problem is that we don't know the `NamedTuple` until it is too late.

I think it would probably be too expensive to create a `Definition` for every call expression, but it might be possible to only create `Definition`s for call expressions inside the `ast::Argument`s for `class` statements? That would probably cover almost all use cases.

@charliermarsh I also think it would be fine to defer "inline" dynamic classes for now -- this PR is huge! We should probably focus on getting something over the line at this point, so that we can iterate on it. Saying that we currently only support `type()` classes when they're on the right-hand side of an assignment statement seems like a reasonable way to cut scope for now.

**Comment by charliermarsh** [comment]
I dropped support for "dangling" `type(...)` expressions for now. I attempted to retain all existing tests with appropriate TODOs.

File: crates/ty_python_semantic/resources/mdtest/call/type.md [hunk 130]
```diff
@@ -0,0 +1,796 @@
...
+
+Unpacking arguments with `*args` or `**kwargs`:
+
+```py
+class Base: ...
+
+# Unpacking a tuple for bases
+bases_tuple = (Base,)
+Cls1 = type("Cls1", (*bases_tuple,), {})
+reveal_type(Cls1)  # revealed: <class 'Cls1'>
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/call/type.md:615]:
```suggestion
from ty_extensions import reveal_mro

class Base: ...

# Unpacking a tuple for bases
bases_tuple = (Base,)
Cls1 = type("Cls1", (*bases_tuple,), {})
reveal_type(Cls1)  # revealed: <class 'Cls1'>
reveal_mro(Cls1)  # revealed: (<class 'Cls1'>, @Todo(StarredExpression), <class 'object'>)
```

(The `@Todo` type will be fixed by https://github.com/astral-sh/ruff/pull/22503)

File: crates/ty_python_semantic/resources/mdtest/call/type.md [hunk 131]
```diff
@@ -0,0 +1,796 @@
...
+
+```py
+# Protocol bases work - the class is created as a subclass of the protocol
+from typing import Protocol
+
+class MyProtocol(Protocol):
+    def method(self) -> int: ...
+
+ProtoImpl = type("ProtoImpl", (MyProtocol,), {})
+reveal_type(ProtoImpl)  # revealed: <class 'ProtoImpl'>
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/call/type.md:691]: could be useful to add a `reveal_mro` call here too

File: crates/ty_python_semantic/resources/mdtest/call/type.md [hunk 132]
```diff
@@ -0,0 +1,796 @@
...
+```py
+# TypedDict bases work but TypedDict semantics aren't applied to dynamic subclasses
+from typing_extensions import TypedDict
+
+class MyDict(TypedDict):
+    name: str
+    age: int
+
+DictSubclass = type("DictSubclass", (MyDict,), {})
+reveal_type(DictSubclass)  # revealed: <class 'DictSubclass'>
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/call/type.md:710]: and here

File: crates/ty_python_semantic/resources/mdtest/call/type.md [hunk 133]
```diff
@@ -0,0 +1,796 @@
...
+```py
+# NamedTuple bases work but the dynamic subclass isn't recognized as a NamedTuple
+from typing import NamedTuple
+
+class Point(NamedTuple):
+    x: int
+    y: int
+
+Point3D = type("Point3D", (Point,), {})
+reveal_type(Point3D)  # revealed: <class 'Point3D'>
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/resources/mdtest/call/type.md:726]: and here

File: crates/ty_python_semantic/src/types/diagnostic.rs [hunk 134]
```diff
@@ -841,6 +842,36 @@ declare_lint! {
...
+    /// ## What it does
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/diagnostic.rs:846]: It could also be good to say explicitly that this is the same rule as `unsupported-base`, but applied to classes created using `type()` rather than classes created using `class` statements

File: crates/ty_python_semantic/src/types/infer/builder.rs [hunk 135]
```diff
@@ -6002,6 +6020,239 @@ impl<'db, 'ast> TypeInferenceBuilder<'db, 'ast> {
...
+            node_index: _,
+        } = &call_expr.arguments;
+
+        if !keywords.is_empty() {
+            return None;
+        }
+
+        let [name_arg, bases_arg, namespace_arg] = &**args else {
+            return None;
+        };
```
Comment (AlexWaygood) [inline crates/ty_python_semantic/src/types/infer/builder.rs:6051]: we may want to check whether any of these were starred expressions and return `None` if so, e.g.

```py
a = (1, 2, 3)
b = (3, 4, 5)
c = (6, 7, 8)

X = type(*a, *b, *c)
```

**Review by AlexWaygood — APPROVED** [review]
LGTM! (But maybe give @carljm a chance to have another once-over if he wants to, before landing 😄)

File: crates/ty_python_semantic/src/types/class.rs (hunk 50 above)
Comment (charliermarsh) [reply crates/ty_python_semantic/src/types/class.rs]: > Including NodeIndex here is inherently problematic for incrementality. The NodeIndex changes if any new node is inserted before the class definition, which results in a new interned StaticClassLiteral. The result of this is that any cached data on the StaticClassLiterals identity goes out the window when someone make changes above the type call expression (even in entirely unrelated scopes). So this is roughly as bad as holding on to the AST node itself (from an incrementality perspective).

As an aside: I think this comment is using `StaticClassLiteral` when it should be `DynamicClassLiteral`?

Comment (AlexWaygood) [reply crates/ty_python_semantic/src/types/class.rs]: yes

File: crates/ty_python_semantic/src/types/diagnostic.rs [hunk 136]
```diff
@@ -841,6 +842,40 @@ declare_lint! {
...
+    /// def factory(base: type[Base]) -> type:
+    ///     # `base` has type `type[Base]`, not `type[Base]` itself
+    ///     return type("Dynamic", (base,), {})  # error: [unsupported-dynamic-base]
+    /// ```
+    ///
+    /// [method resolution order]: https://docs.python.org/3/glossary.html#term-method-resolution-order
+    /// [`unsupported-base`]: https://docs.astral.sh/ty/rules/unsupported-base
+    pub(crate) static UNSUPPORTED_DYNAMIC_BASE = {
+        summary: "detects dynamic class bases that are unsupported as ty could not feasibly calculate the class's MRO",
+        status: LintStatus::preview("1.0.0"),
```
Comment (MichaReiser) [inline crates/ty_python_semantic/src/types/diagnostic.rs:874]: It looks like claude loves to make this up as preview("1.0.0")
