### PR TITLE
Better error message when `--config` is given a table key and a non-inline-table value

### LINKED ISSUE #13995: Cannot set config option with struct type from command-line
While trying out some adhoc testing, I ran the following:
```
ruff check --extend-select=PT --config 'lint.flake8-pytest-style="csv"'
```

which resulted in the error:

```
error: invalid value 'lint.flake8-pytest-style="csv"' for '--config <CONFIG_OPTION>'

  tip: A `--config` flag must either be a path to a `.toml` configuration file
       or a TOML `<KEY> = <VALUE>` pair overriding a specific configuration
       option

Could not parse the supplied argument as a `ruff.toml` configuration option:

invalid type: string "csv", expected struct Flake8PytestStyleOptions
in `lint`

For more information, try '--help'
```

according to the tip (and the help text) it *should* work, but... doesn't. I'm not sure if there is a format where it does work, but if nothing else it's unclear.

I can imagine this applies to other options that use this form, but this is the only one I've found.

Ruff: 0.7.1

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
## Summary

Resolves #13995.

## Test Plan

`cargo nextest run` and `cargo insta test`.

### CODE REVIEW

**Comment by AlexWaygood** [comment]
This is great! I think we can do even better with a few tweaks, though. With your branch currently, this is the error message I get:

```
~/dev/ruff (cli-config)⚡ % cargo run -- check . --config='lint.flake8-pytest-style="csv"'
   Compiling ruff v0.8.6 (/Users/alexw/dev/ruff/crates/ruff)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 2.51s
     Running `target/debug/ruff check . '--config=lint.flake8-pytest-style="csv"'`
error: invalid value 'lint.flake8-pytest-style="csv"' for '--config <CONFIG_OPTION>'

  tip: A `--config` flag must either be a path to a `.toml` configuration file
       or a TOML `<KEY> = <VALUE>` pair overriding a specific configuration
       option

`lint.flake8-pytest-style` is a table.
Did you mean to use one of its subkeys instead? Possible choices:
lint.flake8-pytest-style.fixture-parentheses
lint.flake8-pytest-style.parametrize-names-type
lint.flake8-pytest-style.parametrize-values-type
lint.flake8-pytest-style.parametrize-values-row-type
lint.flake8-pytest-style.raises-require-match-for
lint.flake8-pytest-style.raises-extend-require-match-for
lint.flake8-pytest-style.mark-parentheses

Could not parse the supplied argument as a `ruff.toml` configuration option:

invalid type: string "csv", expected struct Flake8PytestStyleOptions
in `lint`

For more information, try '--help'.
```

But if I apply this diff to your branch:

```diff
--- a/crates/ruff/src/args.rs
+++ b/crates/ruff/src/args.rs
@@ -978,23 +978,25 @@ The path `{value}` does not point to a configuration file"
                     let prefixed_subkeys = format!("{set}")
                         .trim_ascii()
                         .split('\n')
-                        .map(|child| format!("{key}.{child}"))
+                        .map(|child| format!(" - `{key}.{child}`"))
                         .join("\n");
 
                     tip.push_str(&format!(
                         "
 
-`{key}` is a table.
-Did you mean to use one of its subkeys instead? Possible choices:
+`{key}` is a table of configuration options, but only a single option can be
+overridden with `--config`. Did you want to override one of the table's subkeys?
+
+Possible choices:
 {prefixed_subkeys}"
                     ));
                 }
-            };
-
-            tip.push_str(&format!(
-                "\n\n{}:\n\n{underlying_error}",
-                config_parse_error.description()
-            ));
+            } else {
+                tip.push_str(&format!(
+                    "\n\n{}:\n\n{underlying_error}",
+                    config_parse_error.description()
+                ));
+            }
         }
```

Then it becomes:

```
~/dev/ruff (cli-config)⚡ [2] % cargo run -- check . --config='lint.flake8-pytest-style="csv"'
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.36s
     Running `target/debug/ruff check . '--config=lint.flake8-pytest-style="csv"'`
error: invalid value 'lint.flake8-pytest-style="csv"' for '--config <CONFIG_OPTION>'

  tip: A `--config` flag must either be a path to a `.toml` configuration file
       or a TOML `<KEY> = <VALUE>` pair overriding a specific configuration
       option

`lint.flake8-pytest-style` is a table of configuration options, but only a single option can be
overridden with `--config`. Did you want to override one of the table's subkeys?

Possible choices:
 - `lint.flake8-pytest-style.fixture-parentheses`
 - `lint.flake8-pytest-style.parametrize-names-type`
 - `lint.flake8-pytest-style.parametrize-values-type`
 - `lint.flake8-pytest-style.parametrize-values-row-type`
 - `lint.flake8-pytest-style.raises-require-match-for`
 - `lint.flake8-pytest-style.raises-extend-require-match-for`
 - `lint.flake8-pytest-style.mark-parentheses`

For more information, try '--help'.
```

which feels significantly more readable to me. WDYT?

**Comment by AlexWaygood** [comment]
> This is rather misleading, because you _can_ pass an inline table as the value:

Oh, great point! I forgot how my own feature worked :-) We can scrap that clause, then.

**Review by AlexWaygood — APPROVED** [review]
LGTM, thank you!

File: crates/ruff/src/args.rs [hunk 1]
```diff
@@ -967,11 +969,36 @@ It looks like you were trying to pass a path to a configuration file.
...
+
+            match Options::metadata().find(key) {
+                Some(OptionEntry::Set(set)) if !value.starts_with('{') => {
+                    let prefixed_subkeys = format!("{set}")
+                        .trim_ascii()
+                        .split('\n')
+                        .map(|child| format!("- `{key}.{child}`"))
+                        .join("\n");
+
+                    tip.push_str(&format!(
```
Comment (MichaReiser) [inline crates/ruff/src/args.rs:984]: This will not only list fields but also sub-tables, which I think is confusing (at least with how the message is phrased because setting `lint.isort` wouldn't be a correct option either):

```
`lint` is a table of configuration options.
Did you want to override one of the table's subkeys?

Possible choices:

- `lint.allowed-confusables`
- `lint.dummy-variable-rgx`
- `lint.extend-ignore (deprecated)`
- `lint.extend-select`
- `lint.extend-fixable`
- `lint.external`
- `lint.fixable`
- `lint.ignore`
- `lint.extend-safe-fixes`
- `lint.extend-unsafe-fixes`
- `lint.ignore-init-module-imports (deprecated)`
- `lint.logger-objects`
- `lint.select`
- `lint.explicit-preview-rules`
- `lint.task-tags`
- `lint.typing-modules`
- `lint.unfixable`
- `lint.flake8-annotations`
- `lint.flake8-bandit`
- `lint.flake8-boolean-trap`
- `lint.flake8-bugbear`
- `lint.flake8-builtins`
- `lint.flake8-comprehensions`
- `lint.flake8-copyright`
- `lint.flake8-errmsg`
- `lint.flake8-quotes`
- `lint.flake8-self`
- `lint.flake8-tidy-imports`
- `lint.flake8-type-checking`
- `lint.flake8-gettext`
- `lint.flake8-implicit-str-concat`
- `lint.flake8-import-conventions`
- `lint.flake8-pytest-style`
- `lint.flake8-unused-arguments`
- `lint.isort`
- `lint.mccabe`
- `lint.pep8-naming`
- `lint.pycodestyle`
- `lint.pydocstyle`
- `lint.pyflakes`
- `lint.pylint`
- `lint.pyupgrade`
- `lint.per-file-ignores`
- `lint.extend-per-file-ignores`
- `lint.exclude`
- `lint.ruff`
- `lint.preview`

For more information, try '--help'.
```


Using the `Display` output and then reparsing it also seems fragile, considering that we have the structured metadata. 

I'd suggest to add a `collect_fields` method to `OptionSet` that collects the direct children of `set` and then map over the field names.

**Review by MichaReiser — COMMENTED** [review]
This looks great. I'm a bit worried about the output parsing and I think we can improve the handling if `set` itself has sub-table entries.

**Review by MichaReiser — APPROVED** [review]

File: crates/ruff/tests/lint.rs [hunk 2]
```diff
@@ -780,6 +780,94 @@ fn each_toml_option_requires_a_new_flag_2() {
     ");
 }
 
+#[test]
+fn value_given_to_table_key_is_not_inline_table_1() {
+    // https://github.com/astral-sh/ruff/issues/13995
+    assert_cmd_snapshot!(Command::new(get_cargo_bin(BIN_NAME))
+        .args(STDIN_BASE_OPTIONS)
+        // spaces *also* can't be used to delimit different config overrides;
+        // you need a new --config flag for each override
```
Comment (AlexWaygood) [inline crates/ruff/tests/lint.rs:789]: this comment is irrelevant to this test; I think it was just copied and pasted from the test immediately above

```suggestion
```

File: crates/ruff/tests/lint.rs [hunk 3]
```diff
@@ -780,6 +780,94 @@ fn each_toml_option_requires_a_new_flag_2() {
...
+    "#);
+}
+
+#[test]
+fn value_given_to_table_key_is_not_inline_table_2() {
+    // https://github.com/astral-sh/ruff/issues/13995
+    assert_cmd_snapshot!(Command::new(get_cargo_bin(BIN_NAME))
+        .args(STDIN_BASE_OPTIONS)
+        // spaces *also* can't be used to delimit different config overrides;
+        // you need a new --config flag for each override
```
Comment (AlexWaygood) [inline crates/ruff/tests/lint.rs:826]:
```suggestion
```
