### PR TITLE
[`flake8-pytest-style`] Rewrite references to `.exception` (`PT027`)

### LINKED ISSUE #8650: Rewrite exception references in PT027 fix
```python
from unittest import TestCase, main


class TestFoo(TestCase):

    def test_foo(self):
        with self.assertRaises(Exception) as exc:
            raise Exception('foo')
        assert str(exc.exception) == 'foo'


main()
```

gets converted by `ruff --fix --select PT027 --unsafe-fixes foo.py` into:
```python
from unittest import TestCase, main
import pytest


class TestFoo(TestCase):

    def test_foo(self):
        with pytest.raises(Exception) as exc:
            raise Exception('foo')
        assert str(exc.exception) == 'foo'


main()
```

causing:
```
E
======================================================================
ERROR: test_foo (__main__.TestFoo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "foo.py", line 10, in test_foo
    assert str(exc.exception) == 'foo'
AttributeError: 'ExceptionInfo' object has no attribute 'exception'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

correct would be:
```python
from unittest import TestCase, main
import pytest


class TestFoo(TestCase):

    def test_foo(self):
        with pytest.raises(Exception) as exc:
            raise Exception('foo')
        assert str(exc.value) == 'foo'


main()
```

### PR DESCRIPTION
**Pull request by InSyncWithFoo**
## Summary

Resolves #8650.

## Test Plan

`cargo nextest run` and `cargo insta test`.

### CODE REVIEW

File: crates/ruff_linter/src/rules/flake8_pytest_style/rules/assertion.rs [hunk 1]
```diff
@@ -364,9 +367,84 @@ impl Violation for PytestUnittestRaisesAssertion {
 }
 
 /// PT027
-pub(crate) fn unittest_raises_assertion(
+pub(crate) fn unittest_raises_assertion_call(checker: &mut Checker, call: &ast::ExprCall) {
+    // Bindings in `with` statements are handled by `unittest_raises_assertion_with`.
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_pytest_style/rules/assertion.rs:371]: Do you mean `unittest_raises_assertion_binding`?

File: crates/ruff_linter/src/rules/flake8_pytest_style/rules/assertion.rs [hunk 2]
```diff
@@ -266,47 +268,48 @@ fn check_assert_in_except(name: &str, body: &[Stmt]) -> Vec<Diagnostic> {
...
-                            )
-                            .unwrap_or(expr.range()),
-                        )));
-                    }
-                }
-                Some(diagnostic)
-            } else {
-                None
-            }
+) {
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_pytest_style/rules/assertion.rs:276]: It took me a while to realise that the changes here are entirely unrelated to the PR itself. It can be helpful for changes like this to either add a comment that you decided to refactor it but it's unrelated or make its own PR

File: crates/ruff_linter/src/rules/flake8_pytest_style/rules/assertion.rs [hunk 3]
```diff
@@ -364,9 +367,84 @@ impl Violation for PytestUnittestRaisesAssertion {
 }
 
 /// PT027
-pub(crate) fn unittest_raises_assertion(
+pub(crate) fn unittest_raises_assertion_call(checker: &mut Checker, call: &ast::ExprCall) {
+    // Bindings in `with` statements are handled by `unittest_raises_assertion_with`.
+    if let Stmt::With(ast::StmtWith { items, .. }) = checker.semantic().current_statement() {
+        if items
+            .iter()
+            .any(|item| item.context_expr.range() == call.range && item.optional_vars.is_some())
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_pytest_style/rules/assertion.rs:375]: Do I understand it correctly that what we want to test if `context_expr` is the `call`? If so, I suggest using `AnyNodeRef::ptr_eq`, it makes it more explicit rather than comparing ranges.

File: crates/ruff_linter/src/rules/flake8_pytest_style/rules/assertion.rs [hunk 4]
```diff
@@ -364,9 +367,84 @@ impl Violation for PytestUnittestRaisesAssertion {
...
+
+/// PT027
+pub(crate) fn unittest_raises_assertion_binding(
     checker: &Checker,
+    binding: &Binding,
+) -> Option<Diagnostic> {
+    if !matches!(binding.kind, BindingKind::WithItemVar) {
+        return None;
+    }
+
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_pytest_style/rules/assertion.rs:394]: Nit: I'd remove this, it's already covered by line 397

File: crates/ruff_linter/src/rules/flake8_pytest_style/rules/assertion.rs [hunk 5]
```diff
@@ -364,9 +367,84 @@ impl Violation for PytestUnittestRaisesAssertion {
...
+        let mut ancestors = semantic.expressions(node_id).skip(1);
+
+        let Expr::Attribute(ast::ExprAttribute { attr, .. }) = ancestors.next()? else {
+            continue;
+        };
+
+        if attr.as_str() == "exception" {
+            edits.push(Edit::range_replacement("value".to_string(), attr.range));
+        }
+    }
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_pytest_style/rules/assertion.rs:420]: A short inline comment explaining what this block does would be helpful
```suggestion
    // Rewrite all references to `context_var.exception` to `context_var.value`
    // ```py
    // .. Example
    // ```
    for reference_id in binding.references() {
        let reference = semantic.reference(reference_id);
        let node_id = reference.expression_id()?;

        let mut ancestors = semantic.expressions(node_id).skip(1);

        let Expr::Attribute(ast::ExprAttribute { attr, .. }) = ancestors.next()? else {
            continue;
        };

        if attr.as_str() == "exception" {
            edits.push(Edit::range_replacement("value".to_string(), attr.range));
        }
    }
```

File: crates/ruff_linter/src/rules/flake8_pytest_style/rules/assertion.rs [hunk 6]
```diff
@@ -364,9 +367,84 @@ impl Violation for PytestUnittestRaisesAssertion {
...
+
+    unittest_raises_assertion(call, edits, checker)
+}
+
+#[inline]
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_pytest_style/rules/assertion.rs:425]: Inline mainly helps with cross-crate calls and it should mainly be used for hot-functions (there's a trade off with increased code size). Inlining more code can also lead to some compiler optimizations to no longer be applied because the function becomes too large. Furthermore, the compiler already applies heuristics to decide when to inline a function. That's why `inline` should only be used where it matters, I don't think it matters here.
```suggestion
```

File: crates/ruff_linter/src/rules/flake8_pytest_style/rules/assertion.rs [hunk 7]
```diff
@@ -364,9 +367,84 @@ impl Violation for PytestUnittestRaisesAssertion {
...
+            Some(&item.context_expr)
+        } else {
+            None
+        }
+    })
+}
+
+fn unittest_raises_assertion(
     call: &ast::ExprCall,
+    extra_edits: impl IntoIterator<Item = Edit>,
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/flake8_pytest_style/rules/assertion.rs:446]: `impl` can lead to monomorphization and we don't need the flexibility here. We always have a vec (or can easily create an empty one)
```suggestion
    extra_edits: Vec<Edit>,
```

**Review by MichaReiser — APPROVED** [review]
Thanks. A few nit comments

**Review by MichaReiser — APPROVED** [review]
