### PR TITLE
refine pyupgrade's TimeoutErrorAlias lint (UP041) to remove false positives

### LINKED ISSUE #8565: UP041 false-positive in the case of target=py310
Hi!

UP041 (which is introduced in https://github.com/astral-sh/ruff/pull/8476) suggests to replace `asyncio.TimeoutError` with `TimeoutError` even when `target-version` is set to `py310`. And it offers the "safe" fix. But in the case of 3.10 this fix is "unsafe" (see. [asyncio.TimeoutError](https://docs.python.org/3.10/library/asyncio-exceptions.html#asyncio.TimeoutError) in py310 docs)

### PR DESCRIPTION
**Pull request by BurntSushi**
Previously, this lint had its alias detection logic a little
backwards. That is, for Python 3.11+, it would *only* detect
asyncio.TimeoutError as an alias, but it should have also detected
socket.timeout as an alias. And in Python <3.11, it would falsely
detect asyncio.TimeoutError as an alias where it should have only
detected socket.timeout as an alias.

We fix it so that both asyncio.TimeoutError and socket.timeout are
detected as aliases in Python 3.11+, and only socket.timeout is
detected as an alias in Python 3.10.

Fixes #8565

## Test Plan

I tested this by updating the existing snapshot test which had erroneously
asserted that socket.timeout should not be replaced with TimeoutError in Python
3.11+. I also added a new regression test that targets Python 3.10 and ensures
that the suggestion to replace asyncio.TimeoutError with TimeoutError does not
occur.

### CODE REVIEW

**Comment by alex-700** [comment]
@BurntSushi hi! Thanks for the PR!

If I understand correctly, you decide to leave linting `asyncio.TimeoutError` even for `py310` (but make the fix unsafe).
IMHO, it looks a bit counterintuitive.
The user, targeted to `py310`, can do nothing with the triggered lint about `asyncio.TimeoutError`, but suppressing.
Should we just do not produce a warning about `asyncio.TimeoutError` in the case of `py310`?

**Comment by charliermarsh** [comment]
Ah yeah, I think we may have misdiagnosed in the original issue. We probably shouldn't raise on `asyncio.TimeoutError` in Python 3.10 _at all_. The initial PR actually suggests that this was the intention:

Screen Shot 2023-11-09 at 5 08 56 PM

But then has this code:

```rust
/// Return `true` if an [`Expr`] is an alias of `TimeoutError`.
fn is_alias(expr: &Expr, semantic: &SemanticModel, target_version: PythonVersion) -> bool {
    semantic.resolve_call_path(expr).is_some_and(|call_path| {
        if target_version >= PythonVersion::Py311 {
            matches!(call_path.as_slice(), [""] | ["asyncio", "TimeoutError"])
        } else {
            matches!(
                call_path.as_slice(),
                [""] | ["asyncio", "TimeoutError"] | ["socket", "timeout"]
            )
        }
    })
}
```

We probably want to return both errors if >= Python 3.11, and only `socket.timeout` error if Python 3.10?

**Comment by alex-700** [comment]
@charliermarsh yes. 
Something like 
```rust
/// Return `true` if an [`Expr`] is an alias of `TimeoutError`.
fn is_alias(expr: &Expr, semantic: &SemanticModel, target_version: PythonVersion) -> bool {
    semantic.resolve_call_path(expr).is_some_and(|call_path| {
        if target_version >= PythonVersion::Py311 {
            matches!(
                call_path.as_slice(),
                [""] | ["asyncio", "TimeoutError"] | ["socket", "timeout"]
            )
        } else {
            matches!(call_path.as_slice(), [""] | ["socket", "timeout"])
        }
    })
}
```
^ to minimize a difference from the current code.

Or maybe something like
```rust
/// Return `true` if an [`Expr`] is an alias of `TimeoutError`.
fn is_alias(expr: &Expr, semantic: &SemanticModel, target_version: PythonVersion) -> bool {
    semantic
        .resolve_call_path(expr)
        .is_some_and(|call_path| match call_path.as_slice() {
            [""] => true,
            ["socket", "timeout"] if target_version >= PythonVersion::Py310 => true,
            ["asyncio", "TimeoutError"] if target_version >= PythonVersion::Py311 => true,
            _ => false,
        })
}
 ```
or (implicitly used the information that target_version >= py310)
```rust
/// Return `true` if an [`Expr`] is an alias of `TimeoutError`.
fn is_alias(expr: &Expr, semantic: &SemanticModel, target_version: PythonVersion) -> bool {
    semantic
        .resolve_call_path(expr)
        .is_some_and(|call_path| {
            matches!(call_path.as_slice(), [""] | ["socket", "timeout"])
            || matches!(call_path.as_slice(), ["asyncio", "TimeoutError"] if target_version >= PythonVersion::Py311)
        })
}
```

P.S. I am actually does not understand why the check for [""] is here 😄

**Comment by BurntSushi** [comment]
Right, the `unsafe` fix on Python 3.10 for `asyncio.TimeoutError` was what I was uncertain about. I structured this PR such that all I have to do is drop the last commit. I fixed the logic as @charliermarsh indicated above in the first commit. :-)

**Comment by BurntSushi** [comment]
Okay, I've dropped the last commit and updated the PR description.

File: crates/ruff_linter/src/rules/pyupgrade/rules/timeout_error_alias.rs [hunk 1]
```diff
@@ -61,12 +61,20 @@ impl AlwaysFixableViolation for TimeoutErrorAlias {
...
+        } else {
+            // N.B. This lint is only invoked for Python 3.10+. We assume
+            // as much here since otherwise socket.timeout would be an unsafe
+            // fix in Python <3.10. We add an assert to make this assumption
+            // explicit.
+            assert!(
+                target_version >= PythonVersion::Py310,
+                "lint should only be used for Python 3.10+",
+            );
+            matches!(call_path.as_slice(), [""] | ["socket", "timeout"])
```
Comment (charliermarsh) [inline crates/ruff_linter/src/rules/pyupgrade/rules/timeout_error_alias.rs:77]: We can remove the `[""]` piece from this and the preceding branch -- I think that was just a misunderstanding in the original PR. (It has no effect.)

**Review by charliermarsh — APPROVED** [review]
Excellent, thanks!
