### PR TITLE
enforce required imports even with useless alias

### LINKED ISSUE #14283: [Infinite loop] PLC0414 conflicts with I002 if a useless alias is required
[`useless-import-alias` (PLC0414)](https://docs.astral.sh/ruff/rules/useless-import-alias/) conflicts with [`missing-required-import` (I002)](https://docs.astral.sh/ruff/rules/missing-required-import/) in Ruff 0.7.3 if the latter rule is configured to require an alias that the former rule considers useless.

```console
$ echo 1 | ruff check --isolated --select I002,PLC0414 --config 'lint.isort.required-imports = ["import numpy as numpy"]' - --unsafe-fixes --fix

error: Failed to converge after 100 iterations.

This indicates a bug in Ruff. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BInfinite%20loop%5D

...quoting the contents of `-`, the rule codes I002, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
1
-:1:1: I002 Missing required import: `import numpy as numpy`
Found 101 errors (100 fixed, 1 remaining).
[*] 1 fixable with the --fix option.
```

### PR DESCRIPTION
**Pull request by dylwil3**
This PR handles a panic that occurs when applying unsafe fixes if a user inserts a required import (I002) that has a "useless alias" in it, like `import numpy as numpy`, and also selects PLC0414 (useless-import-alias)

In this case, the fixes alternate between adding the required import statement, then removing the alias, until the recursion limit is reached. See linked issue for an example.

# Tests to confirm panic resolved:

```console
$ echo 1 | cargo run --quiet -p ruff -- check --no-cache --isolated --select I002,PLC0414 --config 'lint.isort.required-imports = ["from module import this as this"]' - --unsafe-fixes --fix
from module import this as this
1
Found 1 error (1 fixed, 0 remaining).
```

```console
$ echo 1 | cargo run --quiet -p ruff -- check --no-cache --isolated --select I002,PLC0414 --config 'lint.isort.required-imports = ["import numpy as numpy"]' - --unsafe-fixes --fix
import numpy as numpy
1
Found 1 error (1 fixed, 0 remaining).
```

Closes #14283

### CODE REVIEW

**Comment by dylwil3** [comment]
Not so happy about the big diff in such a simple rule for an edge case... I welcome alternative suggestions!

**Comment by dylwil3** [comment]
Done! It also occurred to me that it might be better to keep the diagnostic but elide the fix for useless-import-alias. That would serve the purpose of warning the user that something was amiss, and they could override the warning by ignoring the rule.

File: crates/ruff_linter/src/rules/pylint/rules/useless_import_alias.rs [hunk 1]
```diff
@@ -52,6 +53,73 @@ pub(crate) fn useless_import_alias(checker: &mut Checker, alias: &Alias) {
...
+pub(crate) fn useless_importfrom_alias(
+    checker: &mut Checker,
+    alias: &Alias,
+    module: Option<&str>,
+    level: u32,
+) {
+    let Some(asname) = &alias.asname else {
+        return;
+    };
+    if alias.name.contains('.') {
```
Comment (charliermarsh) [inline crates/ruff_linter/src/rules/pylint/rules/useless_import_alias.rs:94]: Why this part?

Comment (dylwil3) [reply crates/ruff_linter/src/rules/pylint/rules/useless_import_alias.rs:94]: I don't know... This seems to have been there since the original implementation: https://github.com/harupy/ruff/blob/d765fbe5ddca1fa7b735256ebb303799a2e7aa95/src/pylint/plugins.rs#L16

I don't think it's possible to have an alias with a dot in it... maybe it's supposed to be an early return? Is checking for a dot faster than comparing two strings? Certainly can't be that much of a speed up... Anyway, happy to remove it.

Comment (charliermarsh) [reply crates/ruff_linter/src/rules/pylint/rules/useless_import_alias.rs:94]: Thanks. Do you mind removing it (here and in the linked location) in a separate PR?

**Comment by charliermarsh** [comment]
Do you mind adding a dedicated test for this? Sorry!

File: crates/ruff_linter/src/rules/pylint/rules/useless_import_alias.rs [hunk 2]
```diff
@@ -53,6 +54,75 @@ pub(crate) fn useless_import_alias(checker: &mut Checker, alias: &Alias) {
         return;
     }
 
+    // While the fix is specified as always available,
+    // the presence of a user-specified required import (I002)
+    // with a useless alias causes an infinite loop. So
+    // in this case we keep the diagnostic but omit the fix.
+    // See https://github.com/astral-sh/ruff/issues/14283
```
Comment (MichaReiser) [inline crates/ruff_linter/src/rules/pylint/rules/useless_import_alias.rs:61]: I don't think our testing framework will accept that an always fixable fix isn't always fixable, which makes sense.

File: crates/ruff_linter/src/rules/pylint/rules/useless_import_alias.rs (hunk 1 above)
Comment (MichaReiser) [reply crates/ruff_linter/src/rules/pylint/rules/useless_import_alias.rs:95]: Would it make sense to implement helper methods on the `isort` settings to test if it is a required import to avoid duplicating the logic?

Comment (dylwil3) [reply crates/ruff_linter/src/rules/pylint/rules/useless_import_alias.rs:107]: Ok! Refactored to use new helper methods on `isort` settings, and I will follow up after this PR is merged to get rid of the check for "."

**Comment by dylwil3** [comment]
> Do you mind adding a dedicated test for this? Sorry!

Added!

File: crates/ruff_linter/src/rules/pylint/rules/useless_import_alias.rs (hunk 2 above)
Comment (dylwil3) [reply crates/ruff_linter/src/rules/pylint/rules/useless_import_alias.rs]: Of course you're right! Changed to "Sometimes" with special message/fix title emitted in case of conflict.

File: crates/ruff_linter/src/rules/pylint/rules/useless_import_alias.rs [hunk 3]
```diff
@@ -52,8 +65,76 @@ pub(crate) fn useless_import_alias(checker: &mut Checker, alias: &Alias) {
...
+        UselessImportAlias {
+            required_import_conflict: false,
+        },
+        alias.range(),
+    );
+    diagnostic.set_fix(Fix::unsafe_edit(Edit::range_replacement(
+        asname.to_string(),
+        alias.range(),
+    )));
+    checker.diagnostics.push(diagnostic);
```
[the remark this answers is not in the document]
Comment (dylwil3) [reply crates/ruff_linter/src/rules/pylint/rules/useless_import_alias.rs:95]: After creating the diagnostic, the `UselessImportAlias` object is no longer accessible so we can't change the `required_import_conflict` field to `false`. I could create a mutable instance of the violation, but I'd still have to make the diagnostic twice unless I'm missing something (which I probably am!)

File: crates/ruff_linter/src/rules/pylint/rules/useless_import_alias.rs [hunk 4]
```diff
@@ -52,8 +65,76 @@ pub(crate) fn useless_import_alias(checker: &mut Checker, alias: &Alias) {
...
+) {
+    let Some(asname) = &alias.asname else {
+        return;
+    };
+    if alias.name.contains('.') {
+        return;
+    }
+    if alias.name.as_str() != asname.as_str() {
+        return;
+    }
```
[the remark this answers is not in the document]
Comment (dylwil3) [reply crates/ruff_linter/src/rules/pylint/rules/useless_import_alias.rs:113]: I'm not sure I understand the suggestion because `required_member_import` might check for something like `import numpy` which is not aliased at all (and shouldn't cause an early return). This block seems to belong to the logic of "are you aliased and useless" rather than "are you required", right?

File: crates/ruff_linter/src/rules/pylint/rules/useless_import_alias.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (MichaReiser) [reply crates/ruff_linter/src/rules/pylint/rules/useless_import_alias.rs:95]: You could assign `requried_import_conflict` to a variable and initialize the property with it?

File: crates/ruff_linter/src/rules/isort/settings.rs [hunk 5]
```diff
@@ -75,6 +75,29 @@ pub struct Settings {
     pub length_sort_straight: bool,
 }
 
+impl Settings {
+    pub fn requires_module_import(&self, name: String, as_name: Option<String>) -> bool {
```
[the remark this answers is not in the document]
Comment (dylwil3) [reply crates/ruff_linter/src/rules/isort/settings.rs:79]: In the `isort` implementation we are doing the reverse thing: iterating through the required imports and unpacking them to see if they are found (and adding them if not), rather than packaging up some strings into a named import and then checking if the isort settings contain that. So I'm not sure how to use these specific methods in that case. (apologies again if I'm misunderstanding something here!)

File: crates/ruff_linter/src/rules/pylint/rules/useless_import_alias.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (MichaReiser) [reply crates/ruff_linter/src/rules/pylint/rules/useless_import_alias.rs:113]: Makes sense. I assumed that a similar check exists in the isort code and I wanted to deduplicate it. Thanks for explaining.

File: crates/ruff_linter/src/rules/pylint/rules/useless_import_alias.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (dylwil3) [reply crates/ruff_linter/src/rules/pylint/rules/useless_import_alias.rs:95]: 🤦 duh thanks 😄
